### ISSUE TITLE
Proposal on game's tokenomics.

### ISSUE THREAD

**Issue by AshishKumar-AK** [sunflower-land/sunflower-land#100]
Another proposal but it is purely handled by tokenomics. It will not stop the bots but it may give some breather to polygon congestion.

1. Introduce two token system into the game. Like one representing farmers yield in the game $SFFYield and other one having monetary token value like $SFF.
2. In the game you earn in yield token $SFFYield by farming but you need to swap it to SFF token for monetary value.
3. You can make $SFFYield token to be swappable via only a fixed smart contract of a game for $SFF tokens. this will avoid issues faced by players during halving and DEVs can implement halving tokenomics on it too.
4. Make the swap contract which will handle swapping of yield token to SFF token, allow swapping greater than the certain value. This will also increasing holding of token by users and reduce too many smaller swap transactions.
5. Don't force time based game save. Let users bear the gas cost of data commit transactions they are willing to do on polygon. Just show a estimated gas monetary cost counter in the game UI which will let user know about the estimated cost to save their game after all their changes.

**Comment by AshishKumar-AK** [comment]
Putting re-write update tokenomics proposal which I posted in discord channel here too:

1. Introduce two token system into the game. Like one representing farmers yield in the game $SFFYield and other one having monetary token value like $SFF.
2. In the game you earn in yield token $SFFYield by farming but you need to swap it to SFF token for monetary value.
3. You can make $SFFYield token to be swappable via only a fixed smart contract of a game for $SFF tokens. this will avoid issues faced by players during halving and DEVs can implement halving tokenomics on it too. (using oracle here, we can control and provide dynamic SFF token conversion to yield token, like in some season, potato or in another wheat will be more reward bearing/ NFT tokens can too have their equivalent SFF values) 
4. Make the swap contract which will handle swapping of yield token to SFF token, allow swapping greater than the certain value. This will also increasing holding of token by users and reduce too many smaller swap transactions. put a transaction charge on this swap about 5% as well which goes to LP pool.

**Comment by adamhannigan** [comment]
@AshishKumar-AK Some great ideas here. The team is currently working on a new design and improvements!

I like your point around fixing the halving issue, that was really frustrating for players.

**Comment by AshishKumar-AK** [comment]
> @AshishKumar-AK Some great ideas here. The team is currently working on a new design and improvements!
> 
> I like your point around fixing the halving issue, that was really frustrating for players.

Thanks for consideration. Glad i could be helpful for any inputs. Yes I proposed the changes to address halving and liquidity issues with the game token
