### ISSUE TITLE
[BUG]: NO Anti-Cheat function | BOT Detection ⚠

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#101]
## Issue:
- ### 💀❗ This game doesn't seems to have any, either `Anti-Cheat` or `BOT detection` functionality ❗

It is obvious that lots of players are using multiple bots to to do their work in turn congesting the Polygon Blockchain.
This game should implement features to avoid **BOTS**  and any **UNFAIR** tactics that could cause congestion of the Polygon Blockchain as well as UNFAIR to **REAL** Players.

### Feel free to discuss and find various possible solutions 👍

> Possible Solution: 😊
> - Add **CAPTCHA** (**C**ompletely **A**utomated **P**ublic **T**uring test to tell **C**omputers and **H**umans **A**part) to Save Button, such that before players can save their state of the game they need to **PASS** the CAPTCHA test
> - Services like **reCAPTCHA**, **hCaptcha**, etc. could be used.
> - Though, [**GEETEST**](https://www.geetest.com/en/) seems promising 💪
>   > (Binance uses GEETEST for BOT detection).

> P.S I'm not a web3 dev, **please ignore this solution** :)

## BOTS available online:
> Not pastings the links here as it MIGHT encourage people to use them
- Dev's pls contact me, so that I can provide you with the links for case study.

## DISCLAIMER:
I DO NOT SUPPORT OR ENCOURAGE THE USE OF BOTS OR ANY KIND OF CHEAT OR TACTICS THAT COULD BE CONSIDERED AS UNFAIR MEANS.

**Comment by j923sneaks** [comment]
bro bots interact directly w/ the smart contract. captcha wont solve this

**Comment by JeromeRadlach** [comment]
we wont use web2.0 API's to manage access to a web3 app (dapp)

**Comment by Pranav-yadav** [comment]
> bro bots interact directly w/ the smart contract. captcha wont solve this

as, I said **Possible** Solution, Only suggestion :)

Feel free to discuss various ways by which this problem can be solved 👍

**Comment by AshishKumar-AK** [comment]
Please also check couple of solutions I suggested here:

https://github.com/sunflower-farmers/sunflower-farmers/issues/99
https://github.com/sunflower-farmers/sunflower-farmers/issues/100

**Comment by j923sneaks** [comment]
> > bro bots interact directly w/ the smart contract. captcha wont solve this
> 
> as, I said **Possible** Solution, Only suggestion :)
> 
> Feel free to discuss various ways by which this problem can be solved 👍

ok now that a backend server's being introduced, might as well add this to the overall solution :)

**Comment by jpaulodev** [comment]
> ok now that a backend server's being introduced, might as well add this to the overall solution :)

I was thinking on that yesterday and thought that a centralized server would be better than interacting with the contract always we need to save our progress. I'm a web2.0 dev and don't know much about how the blockchain works in the deep but by adding this new server would be possible to only write in the blockchain when claiming our rewards/profits, like a lot of other games does? If so that would solve the problem with the gas!

And what a great job you guys are doing! I wish I could contribute a little to the project haha

**Comment by Pranav-yadav** [comment]
For **backend** solution in **`v2`**, I think that -
## ✔Blocking (player) _address_ based on the _`number of transactions`_ done OR _`number of tokens minted`_ in certain period of time.
> another _blocking criteria_ could also be implemented. The Idea remain same. 😊

> ### e.g. Backend should block the player (_address_) who exceeds `5` transactions in `1 minute`
> for example only

- This approach would either require maintaining own DB and (or) using underlying blockchain API's to determine the number of tx's done by player (_address_) during given time period.

- It will also apply to **multiple accounts** (in the context that, e.g. a player with `5` accounts performs `5` tx's under `1 minute`, then all these addresses should get blocked)
  > for considering the Multiple Accounts, the **_blocking criteria_** must be specified carefully.


> P.S.: I'm not a web3 dev :) please ignore if this doesn't aligns with web3
Let me know if this approach seems feasible, and feel free to discuss other approaches.👍

@adamhannigan @chris-calo @spencerdezartsmith @j923sneaks what do you think ?

**Comment by TerritorialBreak5** [comment]
But, multi-account is allowed, and if you gonna block an certain address based on the number of transactions or number of tokens minted, prob many people would be blocked. You need to think in something that would really affect bots and not legit people.

**Comment by Pranav-yadav** [comment]
> But, multi-account is allowed, and if you gonna `block an certain address` based on the number of transactions or number of tokens minted, prob many people would be blocked. You need to think in something that would really affect bots and not legit people.

### Don't consider `Block` as permanent but, something like `Slow Mode` on Discord / `Rate Limiting` in chatrooms 😎
> like, 
> When **`Slow Mode / Rate Limiting`** is enabled for specific `address` (account), the player won't be able to perform any (in game) actions for some period of time.

### If `Blocking Criteria` is specified correctly, then obviously it shouldn't affect legit players :)

**Comment by adamhannigan** [comment]
@Pranav-yadav 

I think rate limiting is a really good option at this point. Right now we are planning to auto-save/sync with our centralised server to do verification.

This will happen every minute or so. 

For the initial release, we will have an MVP anti-bot mechanism that will use a captcha and also a light detection on the data being sent (i.e. is it human possible to click as fast as the player has done.

The solution won't be perfect at the start, but we hope to catch 99% of cases. At the point it will be a bit of cat and mouse as we strengthen our verification system and add new layers over time.

I like the idea of Slow Mode when we believe we detect a bot. Even if it is a human, we won't completely shut down their game play.

**Comment by TerritorialBreak5** [comment]
That's sound a pretty good idea, the rate limit, and I think it would be more efficient then blocking player address based on the number of transactions, when you don't know if it's a bot or a real player.

**Comment by Pranav-yadav** [comment]
@adamhannigan @spencerdezartsmith assuming backend fix has been implemented for this issue, sill I think it would better idea to add **CAPTCHA** (_gamified, not the usual_)  to Buttons, where player is trying to use **`MAX`** withdraw / sell functionality.

CAPTCHA will be shown **`only`** when player is using MAX (or amount is `greater` than specific threshold like `> 50% of total available`)

I guess this should;
- restrict micro UI bots
- add extra security


If u think this isn't necessary, we can close this issue :)

**Comment by adamhannigan** [comment]
@Pranav-yadav The solution will be a range of small different improvements.

The CAPTCHA is a good idea for some cases.

We won't even really 'close' the botting issue 😓 Instead we will continuously be making improvements around it.

**Comment by Pranav-yadav** [comment]
For new readers:

#366 (Discord OAuth) & #388 (FingerprintJS 🤖 🪓) can be included in this discussion 👍
Both FEAT PR's improve the Bot Detection and limits multi-accounting (_for beta_).

**Comment by tiffanydys** [comment]
Hi @Pranav-yadav I think this issue can be closed now 😄

**Comment by Pranav-yadav** [comment]
Nope 😅

As previously stated by Adam, we continuously need to improve the Bot detection as well cheat/scripts detection .

Day by day peeps will come with new scripts and botting methods, so the game also needs to be updated with new anti-cheat and anti-botting functionalities. 😊
