### ISSUE TITLE
[BUG] Can't claim from Wishing Well

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#1013]
WW Contract -  0x939f4401 = "Fail"
Cannot claim from wishing well, despite having liquidity in there and wishing well tokens for over 3 days.
Severity: Medium
Drakandalankasch Farm ID 138665
0xfc8A3499FC7188aFd4ba6C1f7E694ACe65fee912

Possibly also affected Farm ID 20488

Wishing well says "It's time to grant your wish!"

Checked for an API error, no API error, so it seems to be related to the contract. Contract gets an "Fail" with "execution reverted."

Last successful wishing well claim was 4d 57h ago, block 28597014.
https://polygonscan.com/tx/0x877894a8d9757f4eac848716383e465fccfa73e04ba3ab1c9f79d6397548b63c

6.768748 Wishing well tokens were added 7d9h ago, block 28462052.
https://polygonscan.com/tx/0xeb98486ba210b7318b5b7a9766055744d9e85a1027b38bb244a78643252d2c5c

He did not withdraw any WW tokens since.

He did add some liquidity to the quickswap pool, 3d 13h ago (335.35 tokens worth) but he didn't add any extra WW tokens (understandable, since he'd need to claim his WW reward first, and he can't do that.)

![image](https://user-images.githubusercontent.com/105506388/170337980-1c96853a-c94a-482a-a626-d7c8fb2b9d34.png)
![image](https://user-images.githubusercontent.com/105506388/170338017-c441d03b-4822-4b7d-97b2-70875b11c33d.png)

Different, but semi-related bug:
Wishing well claim always shows 0 SFL since 0.3.19 update, while actually awarding another amount. ChickenCX, ZaZa and a few others have confirmed this.
![image](https://user-images.githubusercontent.com/105506388/170339188-6033783b-b216-4941-8d0a-385482686e8f.png)

**Comment by adamhannigan** [comment]
@sir-canada The error has been fixed 👍 

The UI still displays the "0 SFL" - the team is working on this
