### ISSUE TITLE
[BUG] Melon Dusk quest shows "Mint Now" when quest not started

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#1025]
Completing MoM quest before SFL quest started results in a problem.

The in-game interface will show you a mint dialog only and the contract will fail.

These conditions must be met for this bug to occur:
- [x]  Player has NOT start the quest on the SFL side. (Missing engine core)
- [x]  Player has **completed** the quest on MoM (7 sunflowers) and **has been airdropped** the crossover token.

This showing he's been airdropped the MSF token:
https://polygonscan.com/address/0x8fc3be28daf4010e38ab5237d78f40b555daa79b#tokentxnsErc721

This showing he has not acquired the engine core:
https://polygonscan.com/token/0x22d5f9b75c524fec1d6619787e582644cd4d7422?a=0x12355Ab594fA25E2db5Bb4bE86924F2b48999309#inventory

This is a player who came from the MoM side, completing the quest on mars, then coming over to our game to play SFL.

Expected Result:
User should be prompted to craft an engine core to go to mars
After crafting the engine core, he should be prompted to complete the mission to mint the observatory.

Actual Result:
User is only prompted to complete the observatory. 
It makes no mention of the engine core.

The minting contract requires token 910, so when he tries to mint, it fails.
"Something went wrong."

He did try to mint, a few times actually, and it failed every time:
https://polygonscan.com/tx/0x579f031989ceea9a5fe675bdfdd51930ce9ac78059a611e2d01d19427a53f591
https://polygonscan.com/tx/0x6370b7f819fbc542a2ebe88a639292e9ca2d821d9ac4a7d9e1da14fbd9d764f3
https://polygonscan.com/tx/0xc1f8e8263f45fa63ff27a0c7d20bffe47410278ec50b17c454f92f0b17821092
https://polygonscan.com/tx/0x30bfba45566e951cfcf157a04d800cf2c2c8d67d0d1fd8db9c336be116272eff

![image](https://user-images.githubusercontent.com/105506388/170860031-9a909906-e1d3-4504-9848-cabed9b2652d.png)
![image](https://user-images.githubusercontent.com/105506388/170860035-82e9cb9a-e132-472d-8c97-a5c440a03edf.png)

Additional affected users:
CASUALmente, Farm ID 137906

Also bug, which isn't as important.
[BUG] Observatory NFT does not show in the in-game inventory.

Players have reported the observatory does not show in the in-game **inventory** after syncing. It's an invisible item that appears only on the map and withdraw.

**Comment by brian-man** [comment]
The mint is likely failing because the Engine Core (910) is burned in the transaction to mint the Observatory (911).

The SFL game UI should ensure that the rocket repair quest experience happens if 910 is absent, even if MoM reports the MoM-side requirements are completed.

**Comment by krwilhelm** [comment]
I am experiencing the same issue. Had the supplies for the engine, but when entered goblin village and talked to melon, it went straight to Mint Now screen. What can I do to complete the mission to get the observatory? Address: 0x8BEAE86Ec56cDC59E517E3D61CBfe55fFF84DEa3

**Comment by sir-canada** [comment]
Thank you @adamhannigan for personally fixing this one! Really shows you looking out for the players! :+1: 

I actually counted personally around 30 players who complained about the issue, the real number might've been much higher (people who didn't speak english, people who didn't complain).

It has been tested by one person now and confirmed to be solved. I am closing this issue.
