### ISSUE TITLE
[BUG] Contract Sync error 'ERC20: transfer amount exceeds balance'

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#1026]
A sync problem seems to exist with newly received (not minted) farms. 

TimberWolf Farm ID 54652

Details:
When someone receives a farm, instead of minting it (either through opensea purchase, or however this guy got it) it is not able to sync and fails. In this case, ERC20: transfer amount exceeds balance'

I often tell people to reset session, which usually fixes it, but I've also had many players complain about not having a warning to reset session on new farm purchases.

I asked him show his SFL (0.798) and inventory, given the error. Barely anything.
![image](https://user-images.githubusercontent.com/105506388/170879889-7b1efc48-6869-4d84-a68a-0bc11607a6b0.png)
![image](https://user-images.githubusercontent.com/105506388/170879905-9ad4834e-dda4-408b-8418-50bd9f53cce1.png)

**Comment by adamhannigan** [comment]
Thanks @sir-canada 👏 

It looks like this issue is popping up again. Our solution going forward is to replace the "Reset session" button with a "Refresh" button. This will align the blockchain with our server without resetting progress. The estimated time of this feature is about 2 weeks.

In the meantime however, a reset session is needed

**Comment by sir-canada** [comment]
> Thanks @sir-canada clap
> 
> It looks like this issue is popping up again. Our solution going forward is to replace the "Reset session" button with a "Refresh" button. This will align the blockchain with our server without resetting progress. The estimated time of this feature is about 2 weeks.
> 
> In the meantime however, a reset session is needed

Thank you @adamhannigan!

I highly appreciate the estimated time! It gives the people a fair a choice to decide whether he wishes to wait or not instead of waiting an uncertain amount of time :)

**Comment by sir-canada** [comment]
Another user had problems syncing within 24 hours. It is not a new farm. I tried to convince him to reset, but insists on not resetting. Should I tell him if he doesn't reset, he will have to wait 2 weeks?

sprmwhale   Farm ID 12663

Fail with error 'ERC1155: burn amount exceeds balance'

I did a comparison of the Preview Response from his sync request, vs his on-chain inventory.

The problem seems to be it wants to burn **22 cauliflower seeds**, but the on-chain data shows he only has **17 cauliflower seeds.**

{
    "sessionId": "0x255e2433cc792eac20d774759d37aa6c689950c9155463daf4d35cfc2b268641",
    "captcha": "03AGdBq278Wr3Jog-qdmbDo9lyludk1ZSRheqmbRceLzwEW4qVyMD-wSjRfUpfvzkJac5t07LyV3SR06cDjVYyYBSGGA6N1HSRglpOTEUQofkkVzMBXG0RqJnQ-hcpEZApvAJUccF4xvncxVL0GpTso0_mzur6ue9Qk25h3yxmyYEZ9-czw4418qIFXRsMaYXJXINSFyYWH5MvxNudwACLGfohay4NT1EMFit1EkGkbhLAEdgU1QqtSV_u6vifcM1LGB3nXMJ50iGtYK-ZUaiYRsxa8OhEOi7FNcX7AJhB9nQPEpODEcR8QrtaMad_o9c1CXNjrPFSfpUS0Ej6Thy8wKIM4kweZEQdD-0l3IZg2xJOR_BnQ1ZpW405WccHDn-9H1DQz5tJjzlxTdjwOfaeZ0Y-vH1HjVvvC-hbcr7r6qxmcAGDE3vcuHBl3xCX-2LQjkgtlEIEw4FkNF7GIA6pJNL8ejhjT5vlhhncGsh6F99Sd0efKEEYvwnY3rTfS9MAmS7jGevpDg4Yr8jnUTKmbMdh5XaiRlp0pg"
}

{
    "sessionId": "0x255e2433cc792eac20d774759d37aa6c689950c9155463daf4d35cfc2b268641",
    "farmId": 12663,
    "sender": "0x1453b44A38E631eD4eC467EbBd998CfF6AC437A4",
    "tokens": "690900000000000000",
    "deadline": 1653978830,
    "mintIds": [
        102,
        604,
        704,
        101,
        106,
        205
    ],
    "mintAmounts": [
        "12000000000000000000",
        "1000000000000000000",
        "1",
        "400000000000000000000",
        "3000000000000000000",
        "26400000000000000000"
    ],
    "burnIds": [
        602,
        103,
        **107**,
        105
    ],
    "burnAmounts": [
        "3000000000000000000",
        "70000000000000000000",
        "**22000000000000000000**",
        "2000000000000000000"
    ],
    "signature": "0x40cdd377bf8a122c197de1ed3715f8d411a0cc385600068038fb3f19525d9c257808bdadf1f130a4e613fd543f55cfc284d986225bf3ac8a5d42f60ec460ce971c"
}

https://polygonscan.com/token/0x22d5f9b75c524fec1d6619787e582644cd4d7422?a=0x17bd5f824ca1b075d79ab128b3a1fcb61be563a4#inventory
**107**  **17000000000000000000**

![image](https://user-images.githubusercontent.com/105506388/171160196-56ccb8f8-6a0c-4eb5-b5ca-67c0fd522192.png)

Contract fail link:
https://polygonscan.com/tx/0xa1fb3e52a5ce0072a81fac2acf6b37a672583628804bfb5f572d776c70a9c977

**Comment by adamhannigan** [comment]
Thanks @sir-canada This is very useful.

In this case the fix will need to wait until we have the new feature to refresh

**Comment by c-py** [comment]
> > In this case the fix will need to wait until we have the new feature to refresh
> 
> Thank you! I will be sure to let him know!

@sir-canada The new feature to allow players to refresh without losing progress is coming next week. Players who are currently stuck will be able to use that functionality next week to unblock themselves :). Stay tuned for the announcement 🇨🇦 🍁
