### ISSUE TITLE
[NFT] Spoky Pumpking

### ISSUE THREAD

**Issue by Kiulg** [sunflower-land/sunflower-land#1032]
## Spoky Pumpking ![Raw](https://user-images.githubusercontent.com/18270876/171079167-40fba7c4-3de1-43b2-adda-11906ba524c0.gif)

A baby pumpkin, possessed by the spirit of a goblin that died choking on pumpkin soup.

Reduces pumpkin production time by 15%.

## Supply

6666

### Crafting Costs

- 666 Pumpking
- 15 Stones
- 2 Wood
- 50 SFL

[Link](https://docs.sunflower-land.com/crafting-guide)

---

### Contributor

Sunflower Land is an open source game built by a community of hundreds of developers and artists across the globe.

Come join us on [Github](https://github.com/sunflower-land/sunflower-land)

Designed by @Kiulg
![Large](https://user-images.githubusercontent.com/18270876/171079165-7d9e6b83-fab9-4efc-9cd7-e09e2328a0ce.gif)

![Screenshot](https://user-images.githubusercontent.com/18270876/171079221-7b20db12-b83a-473b-a49d-c637ce7b38d6.png)

**Comment by adamhannigan** [comment]
Thanks for contributing. For ideas and NFTs proposals we use AHA so the community can vote on them.

Would you be able to add this idea to our ideas portal?

https://sunflower-land.ideas.aha.io/

Thanks 🤗
