### ISSUE TITLE
[BUG] Crafting "Engine Core" 500 - Could not mint your object

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#1034]
Attempting to craft engine core, leads to a 500 Internal Server Error, "Could not mint your object."

MZ / Ga8oxlugo Farm ID 49553

Sanity checks
- Farm contract address shows sufficient items for mint.
- Farm is active.
- Tried another browser. Same issue.

{
    "captcha": "0x",
    "item": "Engine Core",
    "sessionId": "0x3016792174a025f64d10f477d896a02b7f2ffd7ea49ef1faed243390fc39b539"
}

He was able to mint the mole, 5 hours ago, with no issues. So it's unlikely to be something on his end?

![image](https://user-images.githubusercontent.com/105506388/171093015-a38e4fd7-723b-485d-993a-3598e6d68de6.png)

**Comment by adamhannigan** [comment]
@sir-canada Did the user sync their farm before attempting to mint an item?

Often users need to sync before going into Goblin village to ensure the off chain and on chain data is aligned

**Comment by sir-canada** [comment]
> @sir-canada Did the user sync their farm before attempting to mint an item?
> 
> Often users need to sync before going into Goblin village to ensure the off chain and on chain data is aligned

great news! that actually fixed it! he synced 5 hours before trying, so I didn't think it would be the issue, next time I will always have them sync before posting. thank you!
