### ISSUE TITLE
[BUG] mistaken resources consuming display when crafting multiple pickaxes

### ISSUE THREAD

**Issue by Mo-Feng** [sunflower-land/sunflower-land#1035]
As shown below, the resources consuming display does not represent correctly(or at least, it's misleading).
Initial state:
![微信图片_20220531152826](https://user-images.githubusercontent.com/35367885/171116904-1af76c90-fc26-4806-8721-dfaea34177ee.png)
crafting 3 pickaxes:
![微信图片_20220531152833](https://user-images.githubusercontent.com/35367885/171117121-ed7c9f8f-55b4-407c-a6e6-5e53c3f5a1a2.png)
crafting 2 stone pickaxes:
![微信图片_20220531152838](https://user-images.githubusercontent.com/35367885/171117170-bc15f6ac-5c15-4a8c-882d-cc27025af8ec.png)

The resources consumed duplicate but not the SFL.

**Comment by newb23** [comment]
Bollocks. I'll bet this is an issue in my calls to the toast handler. I'll get on this ASAP to see what I can do. I already wanted to flesh this feature out more, so, this is good motivation.

Thank you for bringing it to my attention!

**Comment by AzaroQL** [comment]
@newb23 Hey, are you still working on that? I can take a look at that issue.

**Comment by c-py** [comment]
@AzaroQL it would be awesome if you could take a look at this 🎉
