### ISSUE TITLE
[CHORE] Whitepaper Updates

### ISSUE THREAD

**Issue by tiffanydys** [sunflower-land/sunflower-land#1036]
# Description
Hello everyone, 
This Issue is about updating the whitepaper documentation at https://docs.sunflower-land.com/

https://docs.sunflower-land.com/timeline
<img width="838" alt="image" src="https://user-images.githubusercontent.com/18549210/170941708-1daf8336-c874-442e-8b76-ff23fa357376.png">

<hr>

add @c-py https://twitter.com/craigpgray
<img width="638" alt="image" src="https://user-images.githubusercontent.com/18549210/170950669-a9fb7a37-fab3-439f-aedf-e539f1f9c6dc.png">

<hr>

https://docs.sunflower-land.com/getting-started/getting-setup
<img width="876" alt="image" src="https://user-images.githubusercontent.com/18549210/170949946-55757ea1-2ce7-4f6a-8b70-268f3612815e.png">

<hr>

https://docs.sunflower-land.com/getting-started/how-to-play
<img width="837" alt="image" src="https://user-images.githubusercontent.com/18549210/170952314-441edeef-dbff-4f20-99fb-54c222e2deb9.png">

<hr>

https://docs.sunflower-land.com/crafting-guide/farming-and-gathering
![image](https://user-images.githubusercontent.com/18549210/170965793-a6216cf3-a77a-427b-a695-4a1bb59b6c7f.png)
![image](https://user-images.githubusercontent.com/18549210/170966140-fa45eabf-201e-4c42-be13-675f9ed1bc31.png)

<hr>

https://docs.sunflower-land.com/crafting-guide/rare-and-limited-items
<img width="797" alt="image" src="https://user-images.githubusercontent.com/18549210/170967157-2d3d21c2-d856-4293-85b5-e9e7b0f2dcfd.png">
<img width="805" alt="image" src="https://user-images.githubusercontent.com/18549210/170967639-2b61b0fd-f043-41ef-9118-49f9ff10ef67.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/18549210/171111741-9427c2db-c085-45a8-a5cf-856fee9ec561.png">

<hr>

https://docs.sunflower-land.com/crafting-guide/rare-and-limited-items#decorations
<img width="778" alt="image" src="https://user-images.githubusercontent.com/18549210/171112109-54ec6859-589c-4999-857a-2e9a2ddec6ff.png">

<hr>

https://docs.sunflower-land.com/crafting-guide/skill-tree
<img width="670" alt="image" src="https://user-images.githubusercontent.com/18549210/171112921-552cc582-d54e-465b-b31b-fce7faafd16f.png">
<img width="649" alt="image" src="https://user-images.githubusercontent.com/18549210/171112637-1692df90-b360-4209-8d55-19504c6d1c50.png">

<hr>

https://docs.sunflower-land.com/fundamentals/roadmap/6-month-roadmap
<img width="805" alt="image" src="https://user-images.githubusercontent.com/18549210/171113650-601e0e3e-d240-4fc8-961c-9a003f7c7643.png">

<hr>

https://docs.sunflower-land.com/fundamentals/depositing-and-custody
<img width="874" alt="Screen Shot 2022-05-31 at 3 13 11 PM" src="https://user-images.githubusercontent.com/18549210/171114250-3c25f6ec-057a-456b-9636-8a95a2421386.png">

<hr>

https://docs.sunflower-land.com/fundamentals/withdrawing
<img width="876" alt="image" src="https://user-images.githubusercontent.com/18549210/171114647-ae547d27-343e-4149-b031-f7a912730b97.png">

<hr>

https://docs.sunflower-land.com/fundamentals/team
<img width="841" alt="image" src="https://user-images.githubusercontent.com/18549210/171115355-d273f450-e0b3-4ee8-a4a9-6d6e9e3ea628.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/18549210/171115930-83397852-4f6e-42c8-b6fe-622f64fd982b.png">

<hr>

https://docs.sunflower-land.com/support/faq
<img width="906" alt="image" src="https://user-images.githubusercontent.com/18549210/171118108-baec8df7-dca2-4c50-8521-c069312220d0.png">

**Comment by adamhannigan** [comment]
Great work @tiffanydys 🤗 

We will get to this shortly

**Comment by spencerdezartsmith** [comment]
I have updated the whitepaper! Thanks for this @tiffanydys 🤓
