### ISSUE TITLE
[BUG] Fail with error 'SunflowerLand: Deadline Passed'

### ISSUE THREAD

**Issue by Labochi** [sunflower-land/sunflower-land#1038]
![image](https://user-images.githubusercontent.com/103340944/171250275-af229d3b-6d54-427a-bcef-52938d916c55.png)

**Comment by Labochi** [comment]
Hi, there are some people experiencing this issue when syncing.

https://polygonscan.com/tx/0x9c26630e179ff9088a3751612debf70803db7f7334acf80abb55d04ec37e8022
Address: 0x4f02edf8f112717b49964e163da200d32a9cd723
Farm ID: 141241

**Comment by adamhannigan** [comment]
@Labochi 

This means they took longer than 5 minutes to submit a transaction.

For security reasons, we require that once we sign a transaction that it is submitted within 5 minutes.

This error can be caused from:

- Gas price too low and it takes 5 minutes to get mined on the blockchain
- The user takes longer than 5 minutes to click "Accept" in Metamask
