### ISSUE TITLE
Prestige mode

### ISSUE THREAD

**Issue by Makkers1990** [sunflower-land/sunflower-land#1048]
Hey all,

I’m playing since version 1. I think it’s a nice game but it does get repetitive. At this point I’m level 10 in farming and gaining exp doesn’t give me more benefits (yet). What if…

Why would we add a prestige system? When you reach level 10 farming (for example) you can prestige your harvesting level for a X amount of SFL and/or goods.

When you enter prestige mode, your harvesting level goes back to 1. But your prestige level will increase with 1. This comes with a bonus of +1% (example) while harvesting. When you prestige for the 2nd time, your prestige level will become 2 and you earn a total of +2% while harvesting (example). The same system would apply for the level system for resource gathering (wood, stone, iron, gold). 

Entering prestige mode does mean you lose your selected skills. This is also a good play for people who want to change their skills. Now they can, but they’ll have to prestige. 

Prestige mode also stimulates the burning rate, as it requires SFL and resources. 

What are your thoughts?

**Comment by Amelavnyt** [comment]
This might be a good idea but if you want a feature like this to be added it needs to be voted by the community. you can post it on https://sunflower-land.ideas.aha.io/ if it gets enough votes, there is a good chance it will be added to the road map

**Comment by Makkers1990** [comment]
> This might be a good idea but if you want a feature like this to be added it needs to be voted by the community. you can post it on https://sunflower-land.ideas.aha.io/ if it gets enough votes, there is a good chance it will be added to the road map

Thanks! I just posted it on the website you suggested.

**Comment by adamhannigan** [comment]
Thanks for raising this. I will close this issue and move the conversation to Aha ideas.
