### ISSUE TITLE
[BUG] Wrong farm id of a moderator

### ISSUE THREAD

**Issue by Idkwhoami42** [sunflower-land/sunflower-land#1050]
Farm id of @ Rhaegal in the town hall says #0.

![image](https://user-images.githubusercontent.com/70280407/172152212-f524569c-44bf-4be7-b35d-4450009523c1.png)

**Comment by adamhannigan** [comment]
Good spot! Thanks for raising this @Idkwhoami42

**Comment by MatheusPoliCamilo** [comment]
Already fixed in [this commit](https://github.com/sunflower-land/sunflower-land/commit/bd4e3d155e5f074a669296bd4774780d7ecab33c).

**Comment by MatheusPoliCamilo** [comment]
Already fixed in [this commit](https://github.com/sunflower-land/sunflower-land/commit/bd4e3d155e5f074a669296bd4774780d7ecab33c) by @Rofrtd.
