### ISSUE TITLE
test help localhost

### ISSUE THREAD

**Issue by jesussource** [sunflower-land/sunflower-land#106]
hello I would like to try some nft articles that I am creating and I would like to test it on localhost with ganache but I cannot compile the code truffle gives me errors when compiling, does anyone know how to do it?

various version errors in truffle solidity and yarn or npm install ...

**Comment by aayusharyan** [comment]
What are the errors you are getting. Please share them as well.

**Comment by jesussource** [comment]
> What are the errors you are getting. Please share them as well.

ok the first error I get when installing yarn in the project is this

yarn install v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@truffle/hdwallet-provider > @trufflesuite/web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime@7.13.15" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@truffle/hdwallet-provider > @trufflesuite/web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime > babel-plugin-polyfill-corejs2 > @babel/helper-define-polyfill-provider@0.2.0" has unmet peer dependency "@babel/core@^7.4.0-0".
warning " > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
warning " > @babel/preset-env@7.14.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > reactour@1.18.6" has unmet peer dependency "react-is@^16.8 || ^17.0.0-0".
warning " > @typescript-eslint/eslint-plugin@4.18.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@4.18.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@4.18.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > eslint-config-prettier@8.1.0" has unmet peer dependency "eslint@>=7.0.0".
warning " > eslint-plugin-import@2.22.1" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0".
warning " > eslint-plugin-jsx-a11y@6.4.1" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning " > eslint-plugin-prettier@3.3.1" has unmet peer dependency "eslint@>=5.0.0".
warning " > eslint-plugin-react@7.22.0" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning " > eslint-plugin-react-hooks@4.2.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > eslint-plugin-simple-import-sort@7.0.0" has unmet peer dependency "eslint@>=5.0.0".
[4/4] Building fresh packages...
$ if [ ! -d '.husky' ]; then husky install; fi
It was not expected ! at this time.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by aayusharyan** [comment]
Ohh, I believe you are trying to install this on Windows. Not sure why but it broke for me as well. I just moved that to WSL and have been working fine on that. 😅

**Comment by adamhannigan** [comment]
@jesussource The team is working on some new docs on how this will work in Sunflower Land. 

We will keep you posted. For now I will close this as the mechanism will be a little bit different in the new version of the game.
