### ISSUE TITLE
[GAMEPLAY] What is NFT supply based on?

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1062]
The time we have since launching an NFT, to accumulate resources is short. Its is only encouraging the big ones.

I've been playing for over a month with a old farm, never withdrawn a SFL and cant reach NFTs. 
Even if I invest SFL, I won't be as strong as those that are. If you visit the first farms you will see how much resource they have.  Was this resource  given to them? The game is in the hands of them. What do they do to keep this game healthy?

The NFTs are not posted in the whitepaper.
https://docs.sunflower-land.com/crafting-guide/rare-and-limited-items

and view we have for this is that:
![image](https://user-images.githubusercontent.com/74167741/172651661-f296abcb-9f7f-41aa-ab21-9f0220552e6b.png)
Is it the best way to launch a NFT?

Since we have this info from 3rd party

![image](https://user-images.githubusercontent.com/74167741/172652738-22c2cb7f-e45e-4037-8339-e026fd4f3fb0.png)

is this info available on discord or what?

Can't we have this information in the game and give everyone an equal opportunity?

I believe you should think better, you are strengthening a minority and frustrating the rest.

**Comment by future2back** [comment]
I believe the information is not very clear.

![image](https://user-images.githubusercontent.com/74167741/172763105-9d3f0f23-8e35-48ad-beb5-2e66a96cb5ea.png)

![image](https://user-images.githubusercontent.com/74167741/172763229-5908e605-8d31-4e91-a464-e9a49b006a9e.png)

![image](https://user-images.githubusercontent.com/74167741/172763358-45db6446-ac04-4387-8f27-4b72549ab3d8.png)

**Comment by adamhannigan** [comment]
@future2back Thanks for raising this bug report.

The "?" was added since the game mechanic/prices were still being decided by the community. We did not want to display incorrect information and then change it last minute. This would cause a lot of confusion with the community.

That said, your feedback is extremely valuable about giving more heads up to the community about upcoming NFTs and what is required. We will take this on board going forward.

The "?" will be removed this weekend

**Comment by future2back** [comment]
> @future2back Thanks for raising this bug report.
> 
> The "?" was added since the game mechanic/prices were still being decided by the community. We did not want to display incorrect information and then change it last minute. This would cause a lot of confusion with the community.
> 
> That said, your feedback is extremely valuable about giving more heads up to the community about upcoming NFTs and what is required. We will take this on board going forward.
> 
> The "?" will be removed this weekend

@adamhannigan Thanks for replying

Why don't you put the release date on the NFT? Changing "coming soon" to "On 07/31/22". Just to illustrate the idea...

![image](https://user-images.githubusercontent.com/74167741/173000588-22ca2443-4259-4361-9a0d-5436e85d15aa.png)

You also could add more info to NFTS in game.



![image](https://user-images.githubusercontent.com/74167741/172999160-333efb5b-974e-4977-b718-f95ccb2c4bcf.png)


![image](https://user-images.githubusercontent.com/74167741/173000051-8fa291f0-2714-4ebf-bd61-024a346e9667.png)

or something like that for 2nd page.

![image](https://user-images.githubusercontent.com/74167741/173002652-fe707e5d-96b1-4a03-8f9e-1dc8901fe692.png)

This change would make better use of spaces and would bring more information about the NFTs.



But the main reason for the discussion is about the division of these NFTs. They are not reachable with for "normal players" with the current process. We couldn't define a strategy to get it. Will the little ones be able to craft something good? Not even with luck? Will the big ones lost crafting something good? Not even out of luck?


I will be attentive to your comments,


Thank you.

**Comment by future2back** [comment]
Why not add **_luck_** in addition to **_resources_** to get the NFTs? It would help to burn resources, bring different user experiences. and a little more justice in crafting the NFTs.

**Comment by future2back** [comment]
Thank you for implementing in-game announcements !
