### ISSUE TITLE
[ART] Trader npc

### ISSUE THREAD

**Issue by Rofrtd** [sunflower-land/sunflower-land#1063]
We are seeking art for a Trader NPC.

The idea is that this npc will show up on your farm with weekly quests offering items to trade.

Requirements

    Raw minified file
    Screenshot of art in the game
    Fits aesthetic and dimensions of game 

Submitting art you agree to the terms and conditions of the game and have read the art contributing guidelines.

Looking forward to seeing the awesome contributions 🤗

**Comment by future2back** [comment]
A good strategy for the game is to learn pixel art.

**Comment by LittleEins** [comment]
### Trader NPC
Preview
![trader-with-fox](https://user-images.githubusercontent.com/104184348/172772682-fee2844d-3842-4395-9a58-73c100723841.gif)

Separate minified raw files:
Trader with bag:
![trader-raw-with-bag](https://user-images.githubusercontent.com/104184348/172772767-b90357ac-ecad-4406-b9ec-f06c82963fe3.gif)
Trader w/o bag:
![trader-raw](https://user-images.githubusercontent.com/104184348/172772800-bc3c6f9a-e4e5-41f6-bf55-405a86a77043.gif)
Fox:
![metamask-100-rawl](https://user-images.githubusercontent.com/104184348/172772817-8c894f2a-6be0-4ce2-bfc3-20a996670951.gif)

**Comment by sfwhat** [comment]
### Trader NPC with boat or cart
![trader](https://user-images.githubusercontent.com/95937808/172839492-54541103-9f20-4d27-8661-866512bc45af.gif)
### Assets
Boat![traderstillpng (1)](https://user-images.githubusercontent.com/95937808/172839354-8848c988-6de1-4557-b33a-f59d802300f1.png)
Cart![traderstillpng (2)](https://user-images.githubusercontent.com/95937808/172839357-f750d946-8d99-4e4a-b745-227bb275eda6.png)
Boat with man![tradergifs (1)](https://user-images.githubusercontent.com/95937808/172839358-f14dc313-3f95-46a3-8629-7311296b6841.gif)
Cart with man![tradergifs (2)](https://user-images.githubusercontent.com/95937808/172839359-73ba0ae6-949a-4a35-8778-1e5cc13b4bee.gif)

**Comment by VadimasVP** [comment]
### **1.**
![final](https://user-images.githubusercontent.com/102822587/172842088-aa3fb24d-dd9a-4aa5-b0df-7278190fe92a.gif)
![npc](https://user-images.githubusercontent.com/102822587/172842257-42cae7fe-cced-42ef-8ac3-032b9e5bcc3d.gif)
![trader](https://user-images.githubusercontent.com/102822587/172842280-16e17fa4-1dbf-440c-b9e9-8d8e95c15ef6.gif)

### **2.**
![final1](https://user-images.githubusercontent.com/102822587/172842432-47515076-44cc-40fe-8386-5f53868e3c53.gif)
![npc1](https://user-images.githubusercontent.com/102822587/172842470-098ecd86-378d-453c-afec-557d6a8ee2d8.gif)
![trader1](https://user-images.githubusercontent.com/102822587/172842488-0df17443-276e-40c8-8aff-eae02ea10c38.gif)

**Comment by eArL2384** [comment]
The Wandering Trader loved by all lores with his trusted Alpaca


Wandering trader full
![wandering traderfull](https://user-images.githubusercontent.com/104702521/172843336-13709142-6603-4389-b257-8e02bab2379b.png)

alpaca x carpets/rags
![wandering traderxcarpetraw-export](https://user-images.githubusercontent.com/104702521/172843403-a4978699-0df6-4651-b3b2-27f9f56ffc62.png)

Asset raw
![wandering trade raw](https://user-images.githubusercontent.com/104702521/172843475-67e2d998-b9ed-40b0-af4f-ae99ee666d24.png)

![carpet](https://user-images.githubusercontent.com/104702521/172843504-1ee0c783-ce64-4402-ba50-76cfdce1390a.Png)

entry
Farm ID 434
Dc ID: eArL2384 l Farmhand #6898

**Comment by Kiulg** [comment]
### Mysterious merchant  ![Mercader](https://user-images.githubusercontent.com/18270876/172901301-7ffc4c63-df13-4942-be46-3578b5ff9a87.gif)

A merchant who doesn't like goblins because of that is so careful with they, and carry valuable things to exchange whit you. 

![Mercaderb](https://user-images.githubusercontent.com/18270876/172901216-eaa34d78-88f8-47f2-886b-ad3c10954443.gif)

_I'll attach the screenshoot later_

**Comment by zxearl** [comment]
![pixil-gif-drawing (22)](https://user-images.githubusercontent.com/104722435/172980684-7a873532-0a9c-4def-aa32-107c831e7ce7.gif)
![pixil-gif-drawing (21)](https://user-images.githubusercontent.com/104722435/172980705-201c95ff-ff8b-48eb-9fb0-5bf90fe8e138.gif)
![pixil-gif-drawing (21)](https://user-images.githubusercontent.com/104722435/172981101-b5090d2e-aba4-4f18-b7e9-05ea59c4abce.gif)

**Comment by zxearl** [comment]
Merchandise Trader 
offers goods from all over the world

![pixil-gif-drawing (24)](https://user-images.githubusercontent.com/104722435/172992622-11bd93bc-d312-44c6-a46a-d54f3f980ccd.gif)
![pixil-gif-drawing (25)](https://user-images.githubusercontent.com/104722435/172992627-e1990888-2944-45c2-87e1-0e280f02bb4a.gif)
![Pixilart Sprite Sheet (8)](https://user-images.githubusercontent.com/104722435/172992764-bc760ba7-862b-44eb-86cf-03d8214a1f7c.png)

Dc: zxearl

**Comment by benaxol12** [comment]
Trader NPC
![Trader npc](https://user-images.githubusercontent.com/98098031/173220723-cfa56488-c330-4af9-b746-d08e147a9ebf.gif)

Shopping Cart
![Shopping cart](https://user-images.githubusercontent.com/98098031/173220741-1a11ab17-0684-4ad8-b9ba-6d81a862b65a.png)

![Trader npcx2](https://user-images.githubusercontent.com/98098031/173220864-423faed3-fbe0-4641-aedc-18c261d5c4f2.gif)


Trader's hat and outfit may change based on upcoming events

![Trader NPC Hats](https://user-images.githubusercontent.com/98098031/173220856-f1ce1032-29d7-4e28-8082-f1a5aafeb2f9.png)

**Comment by esp123** [comment]
Philippines Mini Carabao Caravan
![caravan1x1](https://user-images.githubusercontent.com/74337946/174751831-bbc4967a-b503-47f4-9f49-a11d66698f36.gif)
![caravan](https://user-images.githubusercontent.com/74337946/174751847-9c944a5e-27fd-40a2-8351-b4409c14e042.gif)

discord: deeefault#0033

**Comment by adamhannigan** [comment]
Awesome submissions everyone ❤️ 

@VadimasVP Art has been added to the game 👏 The character fit the 'medieval' like theme of the game. Love your work! 🏆
