### ISSUE TITLE
[PROPOSAL] Welcome "Cakes" with a wooden cake event 

### ISSUE THREAD

**Issue by Yougottabekiddingme123** [sunflower-land/sunflower-land#1069]
## Summary of Request

Coinex has just purchased a significant chunk of SFL from the liquidity pool. This might put a strain on the liquidity and spread it a bit thin in the short term. A quick boost in production of SFL is not needed urgently but will help provide additional short-term liquidity. At the same time we have an opportunity to celebrate the coming of a Bakery (Cakes) to Sunflower Land.

## Proof of Community Demand
Who doesn't like a nice celebration and a reward?

Benefits
1.	Provide short term (once off ) boost to liquidity
2.	Celebrate the coming of Cakes to Sunflower Land
3.	Burn Excess wood in the system

Suggestion
Have a once off “craft a wooden cake event” to celebrate the coming of “CAKES” to Sunflower Land.
Players are unable to craft cakes until chickens come out and provide eggs. Thus a wooden cake would be the solution.

Crafting a wooden cake would require:
XX Wood + xx Stone = 20 -50 SFL reward (once off) 
Players will be given a boost of 20 -50 SFL above the cost of production. This is a once off event.

## Contributors

Request for Art

- TODO

## Technical Requirements

xx
xx

1. TODO

### Backend Updates Needed

xx

1. TODO

### Smart Contract Updates Needed

xx
xx

1. TODO

## UI/UX Design Requirements

xx
xx

1. TODO

## Assets Needed

1 x Wooden Cake NFT

1. TODO

**Comment by adamhannigan** [comment]
@Yougottabekiddingme123 Great idea 👌 

Do you mind posting this issue in our ideas portal. This gets more visibility across our players and helps them vote on issues as well.

https://sunflower-land.ideas.aha.io/

Once done post the link here and we will see to it 🤗
