### ISSUE TITLE
During Maintenance Bot detection Mechanism | Discussion

### ISSUE THREAD

**Issue by aayusharyan** [sunflower-land/sunflower-land#107]
There have been mentions about a blacklist functionality blacklisting the bot addresses from using the game. I have a couple of points which I would like to open for discussion. 

1. Are we going to blacklist them from completely playing the game ever again? or are we simply going to reset their gameplay and set everything back to zero?
2. What is the mechanism for detecting which address is a bot or not. Are we going to have a hard limit on the block ID (as in anyone after a certain block ID, say after 5 hours from the maintenance) is a bot? or are we going to have some certain condition such as anyone who has interacted with the contract more than 10 times is a bot or anyone who has grown their SFF or any other token balance by more than 25% is a bot?
3. For if any address becomes a false positive. What are the ways with which they can be un-blacklisted and their account restored. Maybe like a form or something which can be reviewed later by someone or a group of someones who has the authority to unblock. (That's not decentralization, I know, but implementing a voting system for this will be a bit overkill).

These are just proposals, I can help with writing the code as well, but wanted to get the discussion going for the specification.

**Comment by mGranTY** [comment]
i'm also worried, i run the local version to test my NFTs and interact with contract, will i be considered a bot? we need answers.
