### ISSUE TITLE
[ART] Posters + Fan Art

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#1071]
## Summary

Posters, promotional banners, and fan-art.

The purpose of this request is to gather fan art that we can display in our Sunflower Studios during live streams. We would like to rotate fan art on a weekly basis and give shoutouts during our live streaming of the development of the game.

## Requirements

- Minified art submission
- Original files (aseprite, illustrator etc.)
- Aspect ratio for posters

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

You agree to the project's terms and conditions:
https://docs.sunflower-land.com/support/terms-of-service

Note: Your art & mechanic may be modified/altered by the community if needed.

## Rewards

There is no guarantee of rewards by contributing to the project. Based on past history however, artists are airdropped their designs or surprise with in game rewards 😉 

## Deadline

No strict deadline on this. We would like to do a live stream on Tuesday so looking for some initial art work to showcase and shoutout for the community ❤️

**Comment by MrSnorch** [comment]
Concept of a witch to be turned into a scarecrow by farmers after the great war
![ведьма2](https://user-images.githubusercontent.com/104712725/172979342-c07445f1-b3ee-4126-950c-bc418e84f3a1.png)
![ведьма v2](https://user-images.githubusercontent.com/104712725/172979789-45440bcd-e275-439b-aca8-8e6e13f69a59.png)

**Comment by Netherzapdos** [comment]
### Which side will have the shovel?
---
![SFL Pokemon Battle Raw](https://user-images.githubusercontent.com/101855553/172982453-6732a023-5e77-4b7f-a4b5-48b82bd80fef.png)

Original file: https://mega.nz/file/Th9GHDLZ#Zu2HGlVAQCRfnfj8mZTZDVrAvzE4QIsc8DJwbrw0s4c (Direct upload here doesn't support .aseprite 💀 )

Aspect Ratio: 3:2

Super excited for the livestreams let's goo🔥 

`Farm ID: 591`
`Twitter: @netherzapdoss`

**Comment by sfwhat** [comment]
### Got Wood?
Asset
![sposterwood](https://user-images.githubusercontent.com/95937808/173028789-3cc5c57b-95fd-4880-804c-4e7dc612bd2e.png)
1:1
![xposterwood](https://user-images.githubusercontent.com/95937808/173028778-e44ee48b-6696-406d-8aca-28fa3ffd43a3.png) 

![Sprite-0003-Recovered-Recovered-export](https://user-images.githubusercontent.com/95937808/173029950-f655ea52-e210-427d-8f8c-c9143d43992c.png)

**Comment by kotovkot56** [comment]
**European art goblin!**
![europe_goblin](https://user-images.githubusercontent.com/105886943/173033195-43a326a8-1c01-4388-9bbc-7e7d8569394f.png)

**Comment by digital-farms** [comment]
The logo for my Sunflower land game group in the ru community)

🌻**Цифровой колхоз**
https://t.me/digital_farms
![ЦКЛОГОТИППНГ](https://user-images.githubusercontent.com/105886943/173037110-9497f320-6ebe-419e-ab9e-312bc4d4c31c.png)

**Comment by tiffanydys** [comment]
I've submitted this before on artists-chat but you guys might like it so here it goes

<img width="400px" src="https://user-images.githubusercontent.com/18549210/173100773-09cdd9fd-3d26-4e73-a7f7-788c8ab5e640.png">
<img width="400px" src="https://user-images.githubusercontent.com/18549210/173100808-aab5e524-26f1-49d4-9fd3-c70277d9ec92.png">
<img width="400px" src="https://user-images.githubusercontent.com/18549210/173100815-5771aba9-e920-4dfb-a5f5-4134e923e202.png">

**Comment by tiffanydys** [comment]
Made this one for the brewing war.
<img width="400" src="https://user-images.githubusercontent.com/18549210/173170195-e6bd9c24-0c36-4592-8274-1f235d0b1b07.gif">

**Comment by benaxol12** [comment]
**Twitter Banner**
![Twitter_Banner](https://user-images.githubusercontent.com/98098031/173228655-190f09d0-644f-45c3-9c5b-b1d7f4252bb1.png)

**Goblin Land** 
![GoblinLand](https://user-images.githubusercontent.com/98098031/173228679-b34e3e11-7f11-4844-896d-2371269487a8.gif)

**Memories from the war**
![Goblin war](https://user-images.githubusercontent.com/98098031/173228718-1fe588e1-6097-4238-84fc-24e32cbcfa8e.png)

**When we wait v2**
![land](https://user-images.githubusercontent.com/98098031/173228780-d9e7051b-a80d-4391-9b9e-031c13c577e6.png)

**After a long time our fields will be like this**
![Abandoned](https://user-images.githubusercontent.com/98098031/173228802-ab247e1b-afb3-4c86-86c3-0bf664fef9c2.png)

**For wood lovers**
![WOOD POSTER](https://user-images.githubusercontent.com/98098031/173229119-845492a2-f50b-4ca1-9e9a-ecfa483d55f6.png)

**Comment by JcEii** [comment]
### My Idea about Goblin war (Fan Art)

**Goblin War: Goblin vs Hob Goblin**

1:1
![1](https://user-images.githubusercontent.com/105348036/173387711-1964a5bb-06c9-4365-b008-cd84e2a572c3.png)

### My own Idea about my fishing nft proposal (maybe poster or fan art)

**Mr. J**

1:1
![2](https://user-images.githubusercontent.com/105348036/173388516-7ab2ec31-12e0-42c8-b5c2-8c51521429b1.gif)

**Comment by Vergelsxtn** [comment]
I know it's not pixelated but I tried my best to make it look the same with the game, I called it "SFL RTX-ON" I made this long time ago and thanks to everyone who likes it😘
![SFL-RTXON-FANART-Vergelsxtn](https://user-images.githubusercontent.com/99605039/173473645-fcaee235-4f65-4843-a08a-3cc6dbccc2be.jpeg)

**Comment by Kiulg** [comment]
![Animals](https://user-images.githubusercontent.com/18270876/173991540-7a8376bd-cf70-4c0e-9770-34a1fd994425.png)
