### ISSUE TITLE
[BUG] Can click on VIP red door when visiting a farm

### ISSUE THREAD

**Issue by MajoDurco** [sunflower-land/sunflower-land#1082]
## Summary of Bug

When visiting a farm (of VIP player) you can click on the VIP red door and see the modal as you would be a VIP. But in the end, you cannot get access to the discord VIP channel.

## Steps to Reproduce

1. Visit a player who is a VIP
2. Click on the red door
3. Click it through and you will get to the discord auth page

## Expected Behavior

You either should be able to click on the red door at all when visiting or only see a modal with some suitable message.

## Actual Behavior

You can click on the red door like you are a VIP player.

## Screenshots

https://user-images.githubusercontent.com/13154028/173249053-8d91ae92-8b34-493c-baf8-cb555c480621.mov

**Device Information (please complete the following information):**

- Device: Macbook Pro
- OS: MacOS
- Browser/App: Brave
- Version: V1.39.122

**Comment by MajoDurco** [comment]
Let me know what the expected behavior should be, I'd like to fix it myself if that's possible.

**Comment by ShiningMinions** [comment]
Great find :+1: . IMO, the VIP door should be disabled when visiting someone else's farm. Probably should get a coreDev's opinion first before writing codefix.

**Comment by 0xsunflowerstudios** [comment]
@MajoDurco Hey Majo 👋 

Great find, you are right. We should disable this when visiting someone else's farm. Feel free to pick this one up. Thanks for helping out 🤗
