### ISSUE TITLE
[BUG] Rocky the Mole (Fix Requirements)

### ISSUE THREAD

**Issue by samadi307** [sunflower-land/sunflower-land#1083]
Requirements of NFT "Rocky the Mole" in opensea is not the same at the game
![image](https://user-images.githubusercontent.com/53188622/173268440-713a2e27-0c5e-4699-8342-03e6ebd95570.png) ![image](https://user-images.githubusercontent.com/53188622/173268500-02409a25-b304-47f9-bd03-5f70ca5c95c0.png)

**Comment by Wolwar** [comment]
not a bug, just good for material burning
