### ISSUE TITLE
[ART] Gift Box / Airdrops

### ISSUE THREAD

**Issue by stevew00dy** [sunflower-land/sunflower-land#1085]
## Summary

I would like to explore the opportunity to create more social interaction within your farms. This could be done by a user adding a bundle of resources from their bank and sending them to another player. 

When received they would appear on the farm in a gift box with a popup alerting the farmer that they have received a gift. 

The team can use this for giveaways and players can use this to interact with each other.

## Requirements

- Minified art submission
- Dimensions and colour palette match the gameplay
- Screenshot of the asset used in the game
- Original art, no plagiarism

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

You agree to the project's terms and conditions:
https://docs.sunflower-land.com/support/terms-of-service

Note: Your art & mechanic may be modified/altered by the community if needed.

**Comment by paluras** [comment]
![BOXBIG](https://user-images.githubusercontent.com/98059798/173572916-ecb8707d-524a-4ff0-ac85-89990cb01015.png)
![BOXSMALL](https://user-images.githubusercontent.com/98059798/173572934-773cfa7d-67c0-42b2-a4df-cbee7009fecb.png)
![Screenshot 2022-06-14 150435](https://user-images.githubusercontent.com/98059798/173572937-2b63883f-1970-49eb-a4df-0a34bedf7da6.png)
Mint animation?
![boxxxxxxxxxxxxxxxxx_pa_boxxxxxxxxxxxxxxxxx_01](https://user-images.githubusercontent.com/98059798/173574018-f0a69340-ac74-440a-907c-525aaa4982ee.gif)

**Comment by Vergelsxtn** [comment]
![giftboxes-preview](https://user-images.githubusercontent.com/99605039/173580520-52d052c6-1e65-49cf-9de9-426588c6156c.gif)

V1
![giftbox-blue-v1](https://user-images.githubusercontent.com/99605039/173580844-d0a5bbc9-e1a0-48a8-b582-8cee40dcc297.png)
![giftbox-pink-v1](https://user-images.githubusercontent.com/99605039/173580988-1e749584-678c-4c23-952b-fe4cf94330d9.png)
![giftbox-yel-v1](https://user-images.githubusercontent.com/99605039/173580916-fdae313b-4a53-4c57-9dd5-906ceb85b026.png)

V2
![giftbox-blue-v2](https://user-images.githubusercontent.com/99605039/173581091-b13a4879-7f07-4cbf-b565-744a586f1f3f.png)
![giftbox-pink-v2](https://user-images.githubusercontent.com/99605039/173581157-b9621cce-3d84-4c88-beae-0b1813838475.png)
![giftbox-yel-v2](https://user-images.githubusercontent.com/99605039/173581208-0d9e39b9-2829-4eea-8f65-a62f5dcf13e3.png)

**Comment by Netherzapdos** [comment]
### Aidrop Box
---

Was a bit bored so decided to try out as well 😋 

Preview:
![Airdrop Gift L](https://user-images.githubusercontent.com/101855553/173594796-7d7ab3f8-e9d2-4ec3-8c99-4c234d37e7cf.gif)

Raw:
![Airdrop Gift R](https://user-images.githubusercontent.com/101855553/173595021-aaebb445-0a5c-4f0a-b74f-2a1db2e7035d.gif)

**Comment by MrSnorch** [comment]
![background — копия](https://user-images.githubusercontent.com/104712725/173637647-0a3885e1-0ddc-4275-bb16-65664fed7efb.png)
![loot box](https://user-images.githubusercontent.com/104712725/173637715-67067628-1c6b-4b03-8298-41111054e07c.png)

**Comment by Kiulg** [comment]
![Boxb](https://user-images.githubusercontent.com/18270876/173729426-601d80cf-b5e2-4b2a-95cc-737cc4f375f3.gif)

![Box](https://user-images.githubusercontent.com/18270876/173729438-b056ad30-de1a-4b3a-b981-c8d52925390e.gif)

**Comment by eArL2384** [comment]
here some boxes for you steve

![violet](https://user-images.githubusercontent.com/104702521/173962493-9b600a6f-68c2-4d9c-bdc0-86db0228ca39.gif)
![red](https://user-images.githubusercontent.com/104702521/173962508-dfaa31f9-546d-4385-a4e0-d1624c1885d9.gif)
![green](https://user-images.githubusercontent.com/104702521/173962526-d4796d87-9fa8-4e15-b473-c79afa77aa98.gif)
![blue](https://user-images.githubusercontent.com/104702521/173962535-45a1d1af-78b8-49df-8c2b-d0aa4459005b.gif)
![completeboxes](https://user-images.githubusercontent.com/104702521/173962561-dcada9d7-8c36-4f27-8457-fc8707a0b2db.png)

**Comment by esp123** [comment]
![stork-deliverybg](https://user-images.githubusercontent.com/74337946/174096305-6b318dcf-a355-42ca-bace-52b1aa730a77.png)
![stork-delivery32](https://user-images.githubusercontent.com/74337946/174096308-429dfa2a-515b-4e20-a8f7-213173ada0a6.png)
![stork-deliveryx5](https://user-images.githubusercontent.com/74337946/174096310-ca8dfa52-6483-46d2-9fd4-cc2b6d406a5b.png)

Stork, gifts instead of babies XD.

**Comment by Xliteee** [comment]
How do you like my version?
Xlite#0092

![chest2](https://user-images.githubusercontent.com/104664729/175363115-8bb3d697-9395-4ed6-a953-5e50df422b67.gif)
![chest](https://user-images.githubusercontent.com/104664729/175363094-14abecb5-3e43-4310-b8a2-ae1d81f4db2f.png)
![demo](https://user-images.githubusercontent.com/104664729/175363176-03e82594-8491-4eb9-8435-59216dd7e10b.gif)
