### ISSUE TITLE
[BUG] Save sound config

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1086]
## Summary of Bug

Could you please save our sound config in game?

## Steps to Reproduce

Provide detailed step-by-step instructions for how this bug can be reproduced.

1. TODO

## Expected Behavior

save our sound config in game

## Actual Behavior

Have to mute music everytime i start game.

## Screenshots

**Device Information (please complete the following information):**

- Device: [e.g. iPhone6, Pixel 6a]
- OS: [e.g. iOS, Linux, Windows, Android]
- Browser/App [e.g. firefox, safari, chrome, metamask mobile]

**Comment by future2back** [comment]
> could you elaborate more about your issue?
> 
> do you mean by saving sound config is not to set muted or re-adjust the volume of the music?




I mean that game sounds and music config, as paused and volume should be saved.

**Comment by 0xsunflowerstudios** [comment]
@future2back Hey there, thanks for raising this. This is currently being discussed and worked amongst the engineers. We are aiming to release this over the coming weeks 🚀

**Comment by AzaroQL** [comment]
How to reproduce it? I mean I never had an issue with music playing when I open the game. And the sound setting is saved between sessions.

**Comment by Demonbane18** [comment]
I've never had this problem as well, music is always paused everytime I login

**Comment by aayusharyan** [comment]
Browser - Firefox
Steps to Repro -
1. Open the game, sign the message and login.
2. Mute the in game music.
3. Refresh
4. Music starts playing again....

**Comment by future2back** [comment]
> Browser - Firefox Steps to Repro -
> 
>     1. Open the game, sign the message and login.
> 
>     2. Mute the in game music.
> 
>     3. Refresh
> 
>     4. Music starts playing again....

That's it! Whenever I enter the game I have to mute the sound.

Are the sound settings saved as crops and seeds for example?


Thank you.
