### ISSUE TITLE
[CHANGE] Custom Input in Buying & Selling

### ISSUE THREAD

**Issue by hujikol** [sunflower-land/sunflower-land#1089]
## How the Feature is Currently Working

Currently, the buying and selling experience is quite exhausting, we need a lot of clicking when we want to sell custom amounts and not all of the stock, and also so much clicking with custom buying amounts.

### _i.e. we need to click 69 times the 'buy 1' button when we want to buy 69 seeds of beetroot._
<img src="https://user-images.githubusercontent.com/12151051/173821290-8aeb3b44-0d3a-4023-b708-98f648d12f9b.png" width="540" />

### _or, we should click 100 times to sell the pumkins if I want to keep the remaining 300's_
<img src="https://user-images.githubusercontent.com/12151051/173821772-f9d339e5-c875-4fbb-8bfd-5870904b813d.png" width="540" />

## How the Feature Should Be Changed

In that matter, I suggest a solution to add a custom input field, and a stepping button, but also do pick max avaliable to buy or to sell. This custom input can also be implemented in the future in-game market feature or even in the withdraw panel.

> I'm also aware there is already a great solution in PR #1079 , which is to withdraw by long-pressing the mouse button.
> But in my opinion, it is just not so optimal way to do so, i.e. we want to withdraw 5k items at a time but we need to wait like 5 or more seconds to fill up the 5000 items.

## Proof of Community Demand
This issue is based on my aha proposal: https://sunflower-land.ideas.aha.io/ideas/SFL-I-130

Lot of farmers also need the same feature to be implemented (source discord suggestion channel ):
<img src="https://user-images.githubusercontent.com/12151051/173818721-16f61233-4679-4474-a031-924db046c2d4.png" width="640" />

<img src="https://user-images.githubusercontent.com/12151051/173820970-45049df9-0d1c-4096-ad84-51de5a8444d0.png" width="640" />

<img src="https://user-images.githubusercontent.com/12151051/173822742-b785a251-8948-49e5-9883-a2e9f2e980d7.png" width="640" />

<img src="https://user-images.githubusercontent.com/12151051/173822783-32dd176d-4d8e-4d32-9a2c-1bd6d0947bb6.png" width="640" />

<img src="https://user-images.githubusercontent.com/12151051/173822854-1846a8e4-0a0c-4f76-b1ae-c3c8c82f2811.png" width="640" />

<img src="https://user-images.githubusercontent.com/12151051/173822932-3f88e507-b2d2-4014-a981-26e57b3d7454.png" width="640" />

## Contributors

- Me ( UIX Design, Base code, and logic )
- ??? ( Code Refactoring )
- ??? ( Custom Unit Testing )

## Technical Requirements

**1. Custom Input Field.**

**2. Set default input value to 1.**

**3. Increment/ decrement button** 
to easily add or minus field value.

**4. Disable the increment button** 
if balance < seed price * quantity and also if space is not enough.

**5. Disable the decrement button**
if items are not in inventory and also input field value < 2.

**6. Max/ All button** 
to set the value of the input field to the max available to buy/ sell quantity.

**7. Buy/ Sell button** 
to execute the action based on an input field value.

**8. Disable the buy button** 
if balance < seed price * quantity and also if space is not enough.

**9. Disable the sell button** 
if items are not in inventory and also input field value > item is in inventory.

## UI/UX Design Requirements

Here is my design about the UIX needed.

### Buying
<img src="https://user-images.githubusercontent.com/12151051/173822206-a4f1bf17-70de-4e0d-b56a-302623f8c0eb.png" width="540" />

### Selling
<img src="https://user-images.githubusercontent.com/12151051/173822379-faebebc6-4c37-42e6-899d-fa146a5f6d92.png" width="540" />

**Comment by future2back** [comment]
Is it now allowed to store all that amount of seeds? That's not how it worked.

**Comment by NotKeen** [comment]
I give a thumbs up to this idea with my thumb that is sore from withdrawing wood.

**Comment by franvi** [comment]
Please 🥺

**Comment by future2back** [comment]
I like it, but the action itself would be more work.

**Comment by spencerdezartsmith** [comment]
I left a comment on the PR for this but missed this issue. We know that this is a pain point for folks and we have had many different proposed ideas/PR's. We would like to stay away from input boxes. They are not a great solution for us for many different reasons.

We think a solution for now would be to add a `Sell 10` button so you can sell by multiples. I left the same feedback on the PR.

**Comment by hujikol** [comment]
Thank you for the feedback, will work on that `Sell 10` ASAP while designing better UX without input boxes (it's quite hard actually 😭)
