### ISSUE TITLE
[BUG] Boosts for Chickens are partially applied (Coop, Skills)

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#1091]
## Summary of Bug

Wrangler Buff (10% faster time) not evident after feeding chickens. 10% of 2 days is 4.8 hours so we should at least see `1 day 19 hours`

## Steps to Reproduce

Provide detailed step-by-step instructions for how this bug can be reproduced.

1. Plant/Harvest wheat
2. Buy chicken
3. Feed chicken
4. Hover chicken -- ERROR: shows `1 day 23 hours`

## Expected Behavior

should at least see `1 day 19 hours`

## Actual Behavior

shows `1 day 23 hours`

### Analysis

Should include a time reduction function in `feedChicken.ts` to similarly to `plant.ts` where Seed Specialist badge is checked and proper buff is applied.

![image](https://user-images.githubusercontent.com/89294757/173957426-388f1404-49bd-4170-82e8-d2cd92e9b9a2.png)

## Screenshots

![image](https://user-images.githubusercontent.com/89294757/173956891-18598139-3b6e-462c-8ae3-6438de10f92b.png)

**Device Information (please complete the following information):**

- Device: PC
- OS: Windows,
- Browser/App: Brave
- Version

**Comment by j923sneaks** [comment]
Fixed in #1094 but Multiplier was removed atm. Updating the name of this issue for tracking.

![image](https://user-images.githubusercontent.com/89294757/174214112-0bc19a69-564b-448a-a9b7-213261be7cfc.png)

**Comment by adamhannigan** [comment]
Thanks for raising this, the team has just released the fix 🚀
