### ISSUE TITLE
Calculating LP SFF Equivalent Positions at Snapshot

### ISSUE THREAD

**Issue by AncientHorse** [sunflower-land/sunflower-land#110]
I mentioned to Bumpkin Builder in Discord that I would like to volunteer to write a module to address this.

Issue: 
Unlike SFF tokens which are easy to identify in snapshot, identifying the SFF token equivalent of LP holders is not.  When an individual enters an LP position, they receive a "Uniswap V2" token(s) associated with the smart contract with their percentage share of the liquidity pool.  Liquidity Providers are an important part of the Sunflower Land ecosystem and a fair, objective and auditable way of calculating their SFF tokens should be created.  

Resolution:
In order to calculate the number of SFF tokens associated with a wallet, the total number of SFF associated with each LP at block #23451693 will be recorded.  Preliminarily, it appears active liquidity pools at 23451693 existed at Quickswap and Sushiswap.  Using Polygonscan API (Pro), the total number of "Uniswap V2" tokens for each LP will be recorded.  Then a list of all wallets holding aforementioned tokens at 23451693 can be generated to determine proportionate share.  Finally, when SFFv2 is released, wallets can receive SFFv2 based on proof of each "Uniswap V2" tokens they held at snapshot or they could simply be airdropped, whichever the core devs and/or community believe is better.

All of the code used to generate this will be submitted here so anyone and everyone can review it, however, I can't release my Polygonscan API key to more than a few people for independent auditing.

I strongly encourage any feedback while I create this module and look forward to expanding Sunflower Land's repo.  I'm AncientHorse on Discord if anyone wants to DM me.

**Comment by adamhannigan** [comment]
@AncientHorse Apologies for the late response! The team has been deep in the weeds with V2.

It would be amazing if you could help us calculate those LP positions/create some scripts.

**Comment by AncientHorse** [comment]
I'm on it.  I admit, I'm much older than you young guys and my preferred scripting language is csh/tcsh.  Now that I'm in semi-retired I'm going to force myself to finally learn bash.  I'll do the initial code in tcsh and then make another version in bash.  My biggest problem is getting polygonscan.com to give me the API key I need.  Once I finally get that, I can easily calculate everyone's SFF position at primary snapshot.  Sadly, there was severe impermanent loss for LPs for the pairing token but that's the risk of being in crypto.  However, the community needs to take care of the folks that provide liquidity to make the game fun!  Promise, I'm on it and will share code in both tcsh and bash.

**Comment by adamhannigan** [comment]
@AncientHorse Thanks so much, we really appreciate it!

Agreed, we need to reward those providing LP since they are so important to the game.

**Comment by AncientHorse** [comment]
I think I got this working but it's not elegant.  It has two parts:

1) The first part uses bash and the Covalent API to poll the addresses at block 23451693 and creates json files.  This is the raw data before manipulation.
2) The second part is written in PHP.  It cleans up the raw data and introduces a new field called "percent" which is the sum of all LP tokens divided by the tokens of each address (thus calculating percent of pool by address).  My API times out when trying to calculate the SFF in each contract at 23451693 so I'm currently using a variable for that and hopefully someone who has access to the snapshot can tell me the actual value later. 

Once I clean everything up, I'll submit pull request with the scripts in a separate dir than everything else.
