### ISSUE TITLE
[BUG] Whitescreen when Returning from Contributor's Farm (from Townhall)

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#1105]
## Summary of Bug

Whitescreen when going back from a contributor's farm (from townhall). Game url shows `/play/#/undefined/33`

## Steps to Reproduce

Provide detailed step-by-step instructions for how this bug can be reproduced.

1. Go to townhall
2. Click on a contributor's farm
3. click Back -- ERROR: whitescreen on the page, url shows undefined

## Expected Behavior

Should return to splash page i.e. Let's Farm modal

## Actual Behavior

Whitescreen on the page, url shows undefined

## Screenshots

https://user-images.githubusercontent.com/89294757/174521991-f5f80704-fbe9-4a6a-b95b-7515653c002f.mp4

**Device Information (please complete the following information):**

- Device: PC
- OS: Windows
- Browser/App: Brave
- Version

## NOTES

Possible cause is in `authMachine.ts` -> `visitingContributor` state where undefined value in either `.pathname` or `.farmId`. It was hard to test in Testnet because the server gives errors or forever loads 😢

**Comment by spencerdezartsmith** [comment]
Fixed 😄
