### ISSUE TITLE
Local Dev help

### ISSUE THREAD

**Issue by my9527** [sunflower-land/sunflower-land#111]
when i try  truffle compile,  there aways ends up with error " Truffle is currently using solc >=0.6.0 <0.8.0, but one or more of your contracts specify "pragma solidity ^0.8.0" ";

branch: main
Truffle v5.4.27 (core: 5.4.27)
Solidity - >=0.6.0 <0.8.0 (solc-js)
Node v12.18.1
Web3.js v1.5.3

when i try branch 2-dynamic-pricing, it success.

**Comment by chefilip** [comment]
I have the same issue as well. Looking for some help !

**Comment by my9527** [comment]
> 

i tried a way out, you can use remix online; compile sols that pragma is defined >=0.6.0 <0.8.0; then sols defined ^0.8.0;  make sure you compile all >=0.6.0 <0.8.0 first, otherwise you will same the same error mentiond above;

**Comment by chefilip** [comment]
I see what you are doing. Thanks, I will try it. Basically, there are 2 types of prama definition, it should be a better way to improve this setup process.
