### ISSUE TITLE
[FEAT] Barber Shop Building NFT - Customizable Hair Designs

### ISSUE THREAD

**Issue by sfwhat** [sunflower-land/sunflower-land#1110]
## Summary of Request

There is currently no sense of represented self in game as a Player. Customizable character design makes players feel more included and personalized. To solve this we created a new building NFT and hair styles for a Farmer NPC within game aestethics.

## Proof of Community Demand

![SS](https://user-images.githubusercontent.com/95937808/174683803-28c21d75-04c0-482b-a5a6-2674dfa57d54.png)

## Contributors

Idea and Art @SfWhat
Idea and UI @ihsanser 

## Technical Requirements

Front-End code

Add the Barber Shop building NFT to the Farmer Blacksmith
Find a place in Farmers Land to which the NFT will be displayed
Add Barber Shop NFT in Farmers Land
Add metadata for OpenSea requirements

### Backend Updates Needed

Add Barber Shop NFT with the following requirements:
1000 Wood (To used as walls)
25 Iron (To used as nails)
5 Hammer ( To hammer down nails)
Supply: 10000

### Smart Contract Updates Needed

Add a function call to mint the Barber Shop NFT

## UI/UX Design Requirements

Display interaction screen on click
Left and right buttons to swipe between styles and choose button to confirm changes

![hairui](https://user-images.githubusercontent.com/95937808/174685466-d99703ba-774f-41ac-8b20-66a361792a7e.gif)

## Assets Needed

Barber Shop Building 
![barbershopgif](https://user-images.githubusercontent.com/95937808/174685522-6a34c947-0c2c-48e1-b4b0-2ec239d5a13c.gif)

Hair styles, community artists can make more on a request
![Hairs (1)](https://user-images.githubusercontent.com/95937808/174685565-d0b298c5-108c-4843-88d0-284132833613.png)![Hairs (2)](https://user-images.githubusercontent.com/95937808/174685566-42854a4b-9aca-4a62-872e-0d438120e3ac.png)![Hairs (3)](https://user-images.githubusercontent.com/95937808/174685568-566dd87c-07e7-4269-8fea-30cc319af14c.png)![Hairs (4)](https://user-images.githubusercontent.com/95937808/174685569-87a893e8-0adf-44df-a856-6cc4c718e5bd.png)![Hairs (5)](https://user-images.githubusercontent.com/95937808/174685571-0a432282-eeb0-441d-86dd-56715e89b274.png)![Hairs (6)](https://user-images.githubusercontent.com/95937808/174685572-c02d8471-d484-4026-b688-1d51e3187546.png)![Hairs (7)](https://user-images.githubusercontent.com/95937808/174685573-be96a88e-00db-4a44-b642-f07b99eaeb0b.png)![Hairs (8)](https://user-images.githubusercontent.com/95937808/174685575-a1c082ab-b007-40cf-a090-82612d1c9a66.png)

Barber Shop in Farmers Land
![barberintown](https://user-images.githubusercontent.com/95937808/174685614-3df4bbdd-3d92-49ad-9df6-a13e97adbe0f.gif)

Farmer NPC in front of Home building
![npcinfront](https://user-images.githubusercontent.com/95937808/174685642-2f3f67f4-62b4-45d3-9d0b-6a3f8b437387.png)

**Comment by DonatasDee** [comment]
Would also be awesome if the hairstyle wasn't locked to a color and we had the chance to mix and match. :)

I'm all for customization, great work!

**Comment by Sunboygg** [comment]
Great idea, we need more customization! Helmets, hats, caps, maybe draw more headgear store?

**Comment by X-Quinn** [comment]
I'd love to make tons of fun hair designs!!

**Comment by sfwhat** [comment]
Thank you I am glad that community likes this idea
@DonatasDee that would be great to choose colors on a particular hair style
@Sunboygg Yes and maybe event related hats would make a great collection
@X-Quinn we have great artists in this community thank you!

**Comment by spencerdezartsmith** [comment]
Hey! Thank you for this issue 🤩 . It's excellent and we would like to keep the discussion going. We're going to be using Github Discussions for this so I will be closing this issue but could you please copy this proposal over?

https://github.com/sunflower-land/sunflower-land/discussions
