### ISSUE TITLE
Proposal - Multilanguage

### ISSUE THREAD

**Issue by Q4FOIL** [sunflower-land/sunflower-land#113]
For V2 i propose to create different "teams" dedicated to languages.

There is no multi-lang system yet

Have a nice day

**Comment by ricocrivelli** [comment]
I can help with Brazilian Portuguese!

**Comment by HoxNiky** [comment]
I can help for Chinese

**Comment by HoxNiky** [comment]
I can help for Chinese

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
