### ISSUE TITLE
Fruit counter on favicon

### ISSUE THREAD

**Issue by avalla** [sunflower-land/sunflower-land#114]
Hello, I was thinking that would be useful to add a badge on favicon with fruit counter.

I can develop it, I would add a State for Counter to App.tsx and use Context to add / remove items in Field.tsx

When timeleft goes to 0 the counter the counter will be increased, when fruit is harvested it will be decreased.

Thanks :)

**Comment by adamhannigan** [comment]
@avalla This is a great idea!

Now we have the new code structure, would you be interested in jumping on this?

**Comment by avalla** [comment]
Yes, I will try :)
Do you have any idea to add this feature in a cleaner way?

Thanks!
