### ISSUE TITLE
[CHORE] Goblin Village 'Extra green border'

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#1154]
## Summary

Extra green border on left/bottom in **goblin village**.

![image](https://user-images.githubusercontent.com/105506388/176063197-4e06d040-5543-4787-9d9f-7f9813ea7b80.png)
![image](https://user-images.githubusercontent.com/105506388/176063212-7c1a1c18-291a-4d4d-afb1-cefc52d4007e.png)
![image](https://user-images.githubusercontent.com/105506388/176063224-3768d3a0-a7b2-4901-b048-6b994c344ef9.png)

CSS definitely not my strong suit, just saw this reported twice with no issue/pull request. No idea what needs to be done.

**Comment by AzaroQL** [comment]
Aspect ratio should remain the same after the crop.

**Comment by azarzaza** [comment]
Team,
 I fixed the image in my repo; could you please look at it and verify the changes?
[](https://github.com/sunflower-land/sunflower-land/commit/6be308386bf77cf9bdebd4a99591753eff0aa112)

**Comment by AzaroQL** [comment]
@Demonbane18 Maybe just crop a little bit of map to preserve aspect rate? It is easier than filling the gap and wont affect whole picture that much.

**Comment by Demonbane18** [comment]
I made a PR and used the existing sprites to fixed the gaps as well and maintained 1280x640 resolution

**Comment by Demonbane18** [comment]
@sir-canada i think you can close this issue now :)

**Comment by azarzaza** [comment]
Oh, you've already raised the PR request, which is great.
