### ISSUE TITLE
[BUG] Moles still act as tiered on Bank Withdraw

### ISSUE THREAD

**Issue by Ant-Redstone** [sunflower-land/sunflower-land#1163]
## Summary of Bug

Moles got their buffs split, but the withdraw function from bank didn't get updated, so Nugget and Rocky the Mole can't be withdraw if there is a stone being replenished, while they shoulded be withdrawable.

## Steps to Reproduce

If you got a Rocky the Mole or Nugget

1. Mine a stone (and save)
2. Go to your Goblin Village → Bank → Withdraw → Withdraw SFL Item
3. Select the Mole you have (besides Tunnel Mole)

## Expected Behavior

Be able to select your mole that buffst only an ore, and no ores are replenishing

## Actual Behavior

You can't withdraw it because a stone is replenishing

## Screenshots

- OS: Windows
- Browser: Chrome
- Version:  102.0.5005.115

**Comment by j923sneaks** [comment]
i'll take this one.
