### ISSUE TITLE
Chicken Sound Effect

### ISSUE THREAD

**Issue by khunso-id10440** [sunflower-land/sunflower-land#1166]
adding a Chicken Sound Effect when u claim the egg from the chickens will be great !

https://user-images.githubusercontent.com/108534865/176927118-b67079d9-25c2-4ce3-9a38-4c350051db11.mp4

dont forgot to turn on the volume :)

**Comment by Demonbane18** [comment]
honestly it's a bit loud, I prefer it be just a plop sound just like in stardew valley and minecraft, if it will ever have a hatching sound

**Comment by khunso-id10440** [comment]
u mean like that 

https://user-images.githubusercontent.com/108534865/176964623-4b11da80-ff8b-406e-a399-c171e773b98f.mp4

?

**Comment by MrSnorch** [comment]
> @Demonbane18ты имеешь в виду так?
> 
>  новый_1.mp4

perfect

**Comment by Demonbane18** [comment]
yeah something like that would work but idk if mc sounds can be used since this is an NFT game with money involved probably go for something more original or modified would do but have the same effect

**Comment by khunso-id10440** [comment]
@Demonbane18 i think the idea is clear for now thx for ur advice !

**Comment by adamhannigan** [comment]
@khunso-id10440 Thanks for contributing with this idea 🤗 

For these sort of proposals/ideas we generally start the conversation in a Github Discussion. Once it has community consensus and team approval we move the implementation into a Github issue ❤️

**Comment by khunso-id10440** [comment]
> @khunso-id10440 Thanks for contributing with this idea 🤗
> 
> For these sort of proposals/ideas we generally start the conversation in a Github Discussion. Once it has community consensus and team approval we move the implementation into a Github issue ❤️
> 
> Do you mind opening this as a Github Discussion?

not in all go ahead !
