### ISSUE TITLE
Grace Period and your Twitter Post

### ISSUE THREAD

**Issue by pieman64** [sunflower-land/sunflower-land#117]
Is the grace period based on the block immediately before your Twitter post at https://twitter.com/0xSunflowerLand/status/1480511921480732672

The SFF community would probably like to know the applicable block during the pause for building out V2 of the game, thanks.

**Comment by adamhannigan** [comment]
@pieman64 Yes, the block is around the time of that Twitter post.

There are actually multiple snapshots that have been taken that are being used to determine who is eligible for the airdrop.

**Comment by pieman64** [comment]
Hi @adamhannigan

I checked Discord and I haven't seen any updates on the various snapshots relating to SFF.
Do you have any updates?
