### ISSUE TITLE
[ART] Land Expansion water movement

### ISSUE THREAD

**Issue by Rofrtd** [sunflower-land/sunflower-land#1174]
## Summary

As we're building the future of SFL with Land Expansion we are in need of some water movement (GIF) for the vast ocean we'll be building on.

See example below, this example is a using a 320x320 image with transparent background (also below). But a bigger image would be better as this 320x320 still looks too repeated.

Remember to do the animation taking care of the edges, see how the edges match with the other side for us to be able to repeat them.

<img width="709" alt="Screen Shot 2022-07-03 at 11 24 31 pm" src="https://user-images.githubusercontent.com/25412194/177070769-37c0c7be-0b43-4d73-a24c-a299790c66e2.png">

![water-deco](https://user-images.githubusercontent.com/25412194/177070856-1a5620bc-73f7-41f8-a6e7-456c89cf8fcc.png)

## Requirements

- Minified art submission
- Dimensions and colour palette match the gameplay

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

You agree to the project's terms and conditions:
https://docs.sunflower-land.com/support/terms-of-service

Note: Your art & mechanic may be modified/altered by the community if needed.

## Rewards

There is no rewards by contributing to this issue.

**Comment by paluras** [comment]
I did this as a experiment a while back and to see how animations would work inside of a Tiled project.
![Sprite-0001_pa_New animation](https://user-images.githubusercontent.com/98059798/177110666-c9a53366-6bdc-434b-b77d-990d17e95eb2.gif)
![background](https://user-images.githubusercontent.com/98059798/177110791-9d6f2682-e9b8-4a7e-b82c-8d55ae962f1b.gif)

**Comment by Rofrtd** [comment]
> I did this as a experiment a while back and to see how animations would work inside of a Tiled project. ![Sprite-0001_pa_New animation](https://user-images.githubusercontent.com/98059798/177110666-c9a53366-6bdc-434b-b77d-990d17e95eb2.gif) [ ](https://user-images.githubusercontent.com/98059798/177110666-c9a53366-6bdc-434b-b77d-990d17e95eb2.gif) ![Sprite-0001_pa_New animation](https://user-images.githubusercontent.com/98059798/177110666-c9a53366-6bdc-434b-b77d-990d17e95eb2.gif) [ ](https://user-images.githubusercontent.com/98059798/177110666-c9a53366-6bdc-434b-b77d-990d17e95eb2.gif) ![background](https://user-images.githubusercontent.com/98059798/177110791-9d6f2682-e9b8-4a7e-b82c-8d55ae962f1b.gif) [ ](https://user-images.githubusercontent.com/98059798/177110791-9d6f2682-e9b8-4a7e-b82c-8d55ae962f1b.gif) ![background](https://user-images.githubusercontent.com/98059798/177110791-9d6f2682-e9b8-4a7e-b82c-8d55ae962f1b.gif) [ ](https://user-images.githubusercontent.com/98059798/177110791-9d6f2682-e9b8-4a7e-b82c-8d55ae962f1b.gif)
> 
> ![whater](https://user-images.githubusercontent.com/98059798/177112904-94c1c9fe-7346-4b2a-bd98-58db4d0d8008.gif) [ ](https://user-images.githubusercontent.com/98059798/177112904-94c1c9fe-7346-4b2a-bd98-58db4d0d8008.gif) ![whater](https://user-images.githubusercontent.com/98059798/177112904-94c1c9fe-7346-4b2a-bd98-58db4d0d8008.gif) [ ](https://user-images.githubusercontent.com/98059798/177112904-94c1c9fe-7346-4b2a-bd98-58db4d0d8008.gif) the example might be a bit too crowded and repetitive

https://user-images.githubusercontent.com/25412194/177169904-5329d9c9-9658-4471-b99b-d68f764f8237.mov

**Comment by Kiulg** [comment]
![ingame](https://user-images.githubusercontent.com/18270876/177241325-dc14f21a-285d-4498-ac79-3be51f534c77.gif)


![water](https://user-images.githubusercontent.com/18270876/177240908-45075ae7-bf6d-435b-8e57-3d378c6382c5.gif)

Do you think is too much?

**Comment by eArL2384** [comment]
i Have some Idea since the expansion is in an open space water turbulence is affected by wind as well so here is what I have for you

resized for viewing

![water asset](https://user-images.githubusercontent.com/104702521/178136912-6462f38d-5e58-4fa6-8140-d1b61f4b9be1.gif)

here is what it'll look like when the land is introduced

![waterlandexpansiontrial](https://user-images.githubusercontent.com/104702521/178136954-180ab67d-1b91-48d3-9201-620d3e77228c.gif)



here is the asset 1x1 192x192 

![waterv1](https://user-images.githubusercontent.com/104702521/178136978-8151981a-ca79-4d27-832d-3613d94d757c.gif)


![waterv2](https://user-images.githubusercontent.com/104702521/178136990-6db1696e-f13c-453b-9cc0-0012a4517fdf.gif)

**Comment by Kiulg** [comment]
@paluras what do you use for that movement?

**Comment by paluras** [comment]
> @paluras what do you use for that movement?

It's a program called pixelover.
