### ISSUE TITLE
[CHORE] Add selection for opensea - tradable

### ISSUE THREAD

**Issue by Joshua-CZ** [sunflower-land/sunflower-land#1178]
## Summary

Possibility of selection on opensea, better filtering.

## TODO

In the future there will be more nft, a breakdown for players to know what is tradable and what is only in-game. Btw: I am not a native speaker, perhaps a better word to describe 

If interested I can add it to all .json ERC-1155

![tradable item](https://user-images.githubusercontent.com/108211825/177214861-87f0ff3a-ec06-40f3-a7a4-e9848476780b.PNG)
![tradable item 1](https://user-images.githubusercontent.com/108211825/177215840-c98135db-9998-455a-9707-56e056f21c41.PNG)

1. TODO

**Comment by veenhdek** [comment]
I like the spirit of the proposal to make opensea filtering more robust I think we may want to move it to discussions, as with the in-game Trader capabilities coming we may tie it more to withdrawable vs not or 1:1 to the in game categories of: Foods, Quest Items, Seeds, Badges (which are all un-withdrawable) vs crops, nfts, resources, tools which are withdrawable

**Comment by adamhannigan** [comment]
This looks good to me. Feel free to go ahead and implement this 💪 

Great idea 👏

**Comment by Joshua-CZ** [comment]
Hi, everybody,here's what I'm working on. I will leave the worksheet open for your testing.

https://docs.google.com/spreadsheets/d/1oXFNFzO6Jtlt_JdBEuLSIJYzySGn-o--UMXibFaV9p4/edit?usp=sharing

Goals
- uniform structure
- easy to add more items
- easy to add more items for OpenSea
- possibility to use for other markets

I state that I'm not a programmer, but I'm so excited about this project that I'm just creating. If there is an easier way, stop me. 
note: parsing is hell :)

**Comment by AzaroQL** [comment]
@Joshua-CZ, traded flag was added to metadata.
![image](https://user-images.githubusercontent.com/9656961/190665223-2c1ee503-91c5-4c2c-8b4a-9c99c1e92230.png)
