### ISSUE TITLE
Possible to become a farmer?

### ISSUE THREAD

**Issue by defido** [sunflower-land/sunflower-land#118]
Hello good humans! Possible I can be a farmer in this new farm-land? Always wanted to see myself in 3D picking carrots. We can make a 3D character on my side as we already have character designs & 3D modellers. 🍡

**Comment by adamhannigan** [comment]
@defido That sounds really cool!

Right now, the aesthetics of the game just supports the 2D sprites. Would you be interested in creating a 2D character for yourself?

**Comment by defido** [comment]
@adamhannigan You bet your bottom dollar I would! 

We can take of the design & animation to your spec. 2D sprites aren't overly complicated.

The best email is info@defido.com

**Comment by adamhannigan** [comment]
@defido Looking forward to seeing the artwork!

**Comment by defido** [comment]
I have reached out to your email, please reply there, then we can discuss exactly what we need to make and then we'll get to work!
