### ISSUE TITLE
[BUG]  Wrong image on Opensea of the Carrot Cake

### ISSUE THREAD

**Issue by ilNomade** [sunflower-land/sunflower-land#1195]
![Schermata 2022-07-07 alle 12 20 36](https://user-images.githubusercontent.com/106592209/177751569-9e56ae2b-aa2a-4496-84cd-9725ef061049.png)

**Comment by veenhdek** [comment]
Yep, looks like the 508.json (carrot cake) references the 509.png (beetroot cake) rather than 508
<img width="959" alt="Screen Shot 2022-07-07 at 8 13 41 AM" src="https://user-images.githubusercontent.com/79071868/177783004-637240ef-a28e-4bc6-923c-a7ddb1a834b3.png">

**Comment by Joshua-CZ** [comment]
> @Joshua-CZ when you raise the PR for your change can you modify this png reference?

This needs to be solved complexly (not patches), see my earlier proposal.

**Comment by veenhdek** [comment]
Issue can be closed.
