### ISSUE TITLE
Additional Wallet Compatability

### ISSUE THREAD

**Issue by stevew00dy** [sunflower-land/sunflower-land#1197]
In order to deliver of the mission of providing a web3 game for mass adoption we need to ensure that friction is removed as much as possible from the onboarding process. 

This proposal is to integrate two additional sources for wallet connections when dealing with the web3 aspect of the game. 

These are in additional to the already existing Metamask solution being used on MATIC

1, Create an integration to wallet connect. 
https://docs.walletconnect.com/quick-start/dapps/react-native

This will allow those who use wallets like Trust Wallet and also 3rd party providers who want to build out tooling solutions to have access in order to do so.

2, CoinBase Wallet
https://www.coinbase.com/wallet

There are 3 reasons I want to suggest Coinbase, The first is that it's a global wallet that is known and trusted by many entering Crypto for the first time. Anyone on the Coinbase exchange will have the ability to easily transition into a web3 wallet which removes the need for adding networks and tokens as well as metamask. 

The second reason is to allow the listing of SFL on the Coinbase CEX, this is required for point 3

Reason 3 is to enable Coinbase Pay
https://www.coinbase.com/pay-sdk

This would allow users (once listing in reason 2 is complete) to deposit from a bank account or credit card directly into their farm in SFL without needing to use a DEX.

For onboarding I see this as vital for mass adoption.

**Comment by 0xsunflowerstudios** [comment]
@stevew00dy This is awesome mate and on our radar. We will start playing around with some of these good UX packages.

Can we please move this to a Github Discussion. Once we are ready to implement and decided on the actual tech, we can move it to issues 😄 🤗 

For visibility, we are looking at the following to integrate multiple wallets https://github.com/Uniswap/web3-react
