### ISSUE TITLE
Scarecrow

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#120]
A scarecrow will be an NFT that is used to improve the rate at which wheat is collected.

We are looking for an improved version of the scarecrow than the one that is in the game.

**Comment by Aestnelis** [comment]
![biggscarecrow](https://user-images.githubusercontent.com/98103679/150436344-b04766d7-58cf-43ac-b43a-120b3b19b9c9.png)
Just a quick scarecrow, I can edit as well as you want!

**Comment by benaxol12** [comment]
The scarecrow with goblin style ![goblin](https://user-images.githubusercontent.com/98098031/150511286-164ca475-e05b-4005-8140-63d7429c9dae.png)

it has a hidden wheat icon on it  ![wheat](https://user-images.githubusercontent.com/98098031/150511947-085ea07a-1767-46d6-9145-a4088bfd875b.png)

**Comment by adamhannigan** [comment]
@Aestnelis @benaxol12 These are both great! Let's get them into the game

**Comment by benaxol12** [comment]
@adamhannigan I'm so glad, putting the smaller sizes here 
![52x110](https://user-images.githubusercontent.com/98098031/150532590-ce0f4845-980b-408d-8cc0-7bad06dbb5ef.png) ![26x55](https://user-images.githubusercontent.com/98098031/150532593-bf597e12-6c5c-4ae8-924b-f51667ddfa81.png)

**Comment by Aestnelis** [comment]
> @Aestnelis @benaxol12 These are both great! Let's get them into the game

If wanted i can edit!
![bigscarecrow](https://user-images.githubusercontent.com/98103679/150550462-3e815593-f1de-40e4-af09-ea6cc684457e.png)
![biggscarecrow](https://user-images.githubusercontent.com/98103679/150550472-60be2a27-70d6-410c-9717-419f9d213857.png)
  Thank you!
