### ISSUE TITLE
[CHANGE] Goblin Bank Deposit Description

### ISSUE THREAD

**Issue by hujikol** [sunflower-land/sunflower-land#1206]
## How the Feature is Currently Working

Currently, we have a new function for the 'Refresh' button that is to minimize the 'Sync on Chain' method, when depositing items we can now only just do the 'Refresh' button and not have to sync. 

## How the Feature Should Be Changed
So for that reason, there is no need to sync on-chain whenever we deposit an SFL token or item we just simply press the 'Refresh' button. Need to update the description of **point number 6 (for tokens)** and **point number 4 (for items)** in the Goblin Bank for Depositing items or SFL tokens.

<img src="https://user-images.githubusercontent.com/12151051/178138774-c3131416-886d-4db0-9b16-af03f629384b.png" width="360" /><img src="https://user-images.githubusercontent.com/12151051/178138891-48431132-0856-48f2-b151-9fbfade02c7c.png" width="360" />

### SFL Tokens
**Before**
6. Once the transaction has been completed successfully, open the menu inside Sunflower Land and click "Sync on Chain"

**After**
6. Once the transaction has been completed successfully,  open the menu inside Sunflower Land and click "Refresh" inside the setting.

### SFL Items
**Before**
4. Once the transaction has been completed successfully, open the menu inside Sunflower Land and click "Sync on Chain"

**After**
4. Once the transaction has been completed successfully,  open the menu inside Sunflower Land and click "Refresh" inside the setting.

**Comment by veenhdek** [comment]
See recommendations on [PR 1207](https://github.com/sunflower-land/sunflower-land/pull/1207#issuecomment-1179707415)
