### ISSUE TITLE
Cave / Mining

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#121]
This is a request for a cave/mining artwork that will be used in the quarry section of the game.

In the future, the idea is that this will be a portal to more advanced mining mechanics.

**Comment by adamhannigan** [comment]
Amazing art work from Synedes in Discord ❤️ 

![caverna_mineranimation](https://user-images.githubusercontent.com/11745561/150339766-8b408712-b3ee-4317-bb30-69534409b6bb.gif)

**Comment by Synedes** [comment]
Correct Size
![cavernsunflowersize](https://user-images.githubusercontent.com/98273814/152556620-5274cfa6-0c5a-43c7-9f6e-bec939c1319d.gif)
![image](https://user-images.githubusercontent.com/98273814/152556628-fe300492-fa53-4307-87c3-f66c4a4196d7.png)
