### ISSUE TITLE
Info on owned items and remnants

### ISSUE THREAD

**Issue by Q4FOIL** [sunflower-land/sunflower-land#1214]
For example if you need to Craft "Potato Cake" you need to have 500 potato, it's possibile to see how much you have without open invetory?

Example :

Now :

Potato 500
Weath 10
Eggs 15

After : 

Potato 350/500
Weath 9/10
Eggs 11/15

![Schermata 2022-07-11 alle 13 05 06](https://user-images.githubusercontent.com/58088988/178250942-f5435c65-7c0b-41c2-9cc5-25907d12b7f2.png)

**Comment by Demonbane18** [comment]
honestly not a good feature to add, you can try to open it in on github discussions and if you people seem to like it we can work on doing it

**Comment by Q4FOIL** [comment]
> 

Yes, i want more feedback :P 

@veenhdek

**Comment by Demonbane18** [comment]
> > honestly not a good feature to add, you can try to open it in on github discussions and if people seem to like it we can work on doing it, I can personally work on it
> 
> I think you meant "honestly not a bad feature", or "honestly a good feature". Either way I agree and may play around with what it'll take to add it too :)
> 
> @Q4FOIL do you want to move this to discussions see what community sentiment is?

yeah

**Comment by hujikol** [comment]
Refer to discussion #1218 , here is my approach on it.


https://user-images.githubusercontent.com/12151051/178996560-ffa20778-c341-4334-8820-569de4a59f77.mp4


NB: it could also be implemented on goblin village, but currently I don't have the testnet access so I just build the one on farmer town. A PR will be created if I have access and also build it in testnet or someone that has access can collaborate to do it too.

**Comment by veenhdek** [comment]
Love it! @hujikol I would say go ahead and open a draft PR, (click the little arrow next to submit PR and select Draft) then when you get testnet or if I get mine configured now that I have it I would be happy to help you!
