### ISSUE TITLE
[CHANGE]  Add hyperlink on announcements

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1219]
## How the Feature is Currently Working

Sometimes you put a "Read more" as you did talking about the Chickens, but sometimes not, like you did about the Cake event "[bake off](https://docs.sunflower-land.com/fundamentals/special-events/the-great-sunflower-bakeoff)" since we have the documentation, I don't see why not make it available in easy access. 

## How the Feature Should Be Changed

Will you win the great [bake off](https://docs.sunflower-land.com/fundamentals/special-events/the-great-sunflower-bakeoff)?

Provide a summary for how this feature should be changed.

## Proof of Community Demand

Will you win anything if you collect these cakes at the event?

How do devs calculate if this event is accessible to normal players? A game where events are inaccessible does not seem to be attractive to new players.  Announcements and information needs to be better centralized and clearer, this must be in the game.

**Comment by 0xsunflowerstudios** [comment]
Yes, I agree on this. We will keep this issue open until the next announcement is made and ensure that it includes a link. 👏

**Comment by future2back** [comment]
Not solved. Game lacks documentation.

There is a need and bad habit of pin information on discord.

0xsunflowerstudios

What is **Wicker Man** for?
