### ISSUE TITLE
Sunflower Tombstone

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#122]
A Sunflower Tombstone will be a special edition decorative NFT that players can craft.

It symbolises the death of Sunflower Farmers 😢

**Comment by paluras** [comment]
![Grave111](https://user-images.githubusercontent.com/98059798/150340852-43332808-f6f7-4bb7-9348-e16834238925.png)

Farmers Grave.

**Comment by SrCouve** [comment]
![Akita statue](https://user-images.githubusercontent.com/98098233/150341709-03473c9f-e103-44d8-8a34-0d76fb07149d.png)


     **Akita Statue**
    _Symbol of loyalty_

**Comment by SrCouve** [comment]
![Akita statue](https://user-images.githubusercontent.com/98098233/150342044-9a4ed656-6e41-4710-be31-33f345963349.png)

Akita Statue.
Symbol of loyalty

**Comment by SrCouve** [comment]
![Akita statue](https://user-images.githubusercontent.com/98098233/150342268-3c11be3d-a657-4138-a179-a8fc13949181.png)

Akita Statue 
Symbol of Loyalty.
![termin (1)](https://user-images.githubusercontent.com/98098233/150342398-20f7e6b1-3674-4248-a3bb-f289384302be.gif)

**Comment by adamhannigan** [comment]
> ![Grave111](https://user-images.githubusercontent.com/98059798/150340852-43332808-f6f7-4bb7-9348-e16834238925.png)
> 
> Farmers Grave.

Looks good to me!

Thinking about the recipe costs:
1 Stone, 10 Sunflowers and 1 SFF

Total Supply: 10000 - hoping this enables all the OG farmers from Sunflower Farmers to get a chance to grab their tombstone

**Comment by paluras** [comment]
> > ![Grave111](https://user-images.githubusercontent.com/98059798/150340852-43332808-f6f7-4bb7-9348-e16834238925.png)
> > Farmers Grave.
> 
> Looks good to me!
> 
> Thinking about the recipe costs: 1 Stone, 10 Sunflowers, and 1 SFF
> 
> Total Supply: 10000 - hoping this enables all the OG farmers from Sunflower Farmers to get a chance to grab their tombstone

Sounds good to me.
Glad I could be of help

**Comment by paluras** [comment]
![Gravev1](https://user-images.githubusercontent.com/98059798/150415574-87ab7c7e-3ece-441d-a5d3-288a23150e58.jpeg)

I uploaded it in the original size.

**Comment by cambrios1** [comment]
![SFF_Grave](https://user-images.githubusercontent.com/98171636/150548481-71452390-9e94-43f3-a397-5d3d1ecb08c4.png)

cross-posted from discord per request.

**Comment by soteleon** [comment]
I tried to make something like a tomb but parallel to the ground, how about it?

![TOMB PRUEBA 1 1s-export](https://user-images.githubusercontent.com/94320699/150659941-89671747-e46d-4f91-8065-41f6bc19b491.png)

**Comment by soteleon** [comment]
Here is a smaller one

![TOMB PRUEBA 1 sin hojas 80](https://user-images.githubusercontent.com/94320699/150660528-decf0bd8-4f53-40eb-99fb-a74d174849d5.png)

**Comment by adamhannigan** [comment]
@cambrios1 We will add this one in to the game. It will be an airdrop to the die hard players of SFF (farm was a certain level ;) )

What is your address, we will make sure you get a few airdropped on launch 🤗

**Comment by cambrios1** [comment]
@adamhannigan can we DM on discord? request sent
