### ISSUE TITLE
[CHANGE] Loan of items to quests

### ISSUE THREAD

**Issue by ratodapraiana** [sunflower-land/sunflower-land#1222]
## How the Feature is Currently Working

I noticed that some players are borrowing items for others to complete their quests. Since having multiple accounts is not allowed, this practice seems to have an advantage over other players.
The idea of Sunflower and Gobling keys is to reach Apprentice Beaver and Rocky the Mole or to borrow it? This is affecting the game, Play together Vs Play Alone.

## How the Feature Should Be Changed

Investigate and punish those who are doing this.

## Proof of Community Demand

Provide clear, numerical evidence proving that community demand exists for this desired change. This can be community polls, discord screenshots, Aha! proposals, etc.

## Contributors

If know, please provide the list of contributors who will be working on this feature.

- TODO

## Technical Requirements

Provide clear, step-by-step instructions for HOW this change will be implemented. Keep sentences short, and use sub-bullets if needed. Developers should be able to look at this list and effortlessly start programming the new feature change.

1. TODO

### Backend Updates Needed

Provide a list of what backend updates will be needed to support this feature. Write N/A if none needed.

1. TODO

### Smart Contract Updates Needed

Provide a list of what smart contract updates will be needed to support this feature. Write N/A if none needed.

1. TODO

## UI/UX Design Requirements

Provide a list of UI/UX design considerations needed to support this feature. A UI/UX designer should be able to easily design new game interfaces after reading this list. Write N/A if none are needed.

1. TODO

## Assets Needed:

Provide a list of assets needed to support this feature. This can be new sound-effects, music, graphics, gifs, etc. An asset creator should be able to easily design a new asset after reading this list. Write N/A if none are needed.

1. TODO

**Comment by future2back** [comment]
This is not possible, is it?

**Comment by ShiningMinions** [comment]
@ratodapraiana I highly recommend you move this to a Github Discussion instead, and close this issue:

See: https://github.com/sunflower-land/sunflower-land/discussions

**Comment by adamhannigan** [comment]
Thanks for the suggestion. Could you please move this into the Github discussions?
