### ISSUE TITLE
Sunflower Land Map

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#123]
This is a request to design the terrain and map decorations.

The current version only has the farm with a lot of empty space around it. In the future this space will be filled with Forests (chopping wood), Caves (Mining) and other features. Right now it is empty and we were hoping to fill it out with decorations, trees, flowers, cliffs etc.

We would like to keep the farm where it is on the map. This will ensure that in the Game everything still lines up correctly.

Please see attached the `.tmx` file for Tiled. You can find the base assets by reaching out to one of the engineers on Discord.

**Comment by Synedes** [comment]
new Assets modified and created for the winter.
![winter](https://user-images.githubusercontent.com/98273814/150707320-e8870ed9-09e3-4b87-86a3-5b26e2373b24.png)

**Comment by Synedes** [comment]
new Assets modified and created for the fall.
![autumm exemple](https://user-images.githubusercontent.com/98273814/150707618-6f0db9d6-8476-44de-8e26-3096a5c521d8.png)

**Comment by Synedes** [comment]
active for spring and summer, I just miss more flowers hahaha, I also made some for the aquatic environment
![spring](https://user-images.githubusercontent.com/98273814/150707775-4b80ab0e-eb69-42ca-b974-522d75ffb42a.png)

**Comment by Synedes** [comment]
all assets :)
![allassets](https://user-images.githubusercontent.com/98273814/150707865-b0c98c96-a06d-400f-9b0b-a0600df9b934.png)

**Comment by paluras** [comment]
![image](https://user-images.githubusercontent.com/98059798/150748234-5ab86c7c-a19d-403e-b8e2-3a3a6889fa22.png)
![Background-1-24-22-Paluras_mess](https://user-images.githubusercontent.com/98059798/150748914-6cac0fe4-ebaf-4787-b966-b036d0af9a8e.png)

Two terrains structures, Hill, and a Dig site(hole in the ground).
