### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#125]
Similar to Sunflower Farmers, add the music player into the repo.

**Includes**

- Romy's famous music
- Play
- Pause

**Comment by rickfurt** [comment]
On it

**Comment by rickfurt** [comment]
## Follow WIP preview

### Desktop - Compact
<img width="1216" alt="Screen Shot 2022-01-23 at 10 11 57 pm" src="https://user-images.githubusercontent.com/26861091/150675727-8a0f89be-101c-495c-b7ce-c696c010b6da.png">

### Desktop - Extended
<img width="1216" alt="Screen Shot 2022-01-23 at 10 12 13 pm" src="https://user-images.githubusercontent.com/26861091/150675725-a926ae43-d65e-40b5-bfe4-8a97764dadbb.png">

### Mobile - Compact
<img width="373" alt="Screen Shot 2022-01-23 at 10 11 18 pm" src="https://user-images.githubusercontent.com/26861091/150675775-414f4a2e-aa8c-4058-b61f-6b1d3abf2667.png">

### Mobile - Extended 
<img width="379" alt="Screen Shot 2022-01-23 at 10 21 05 pm" src="https://user-images.githubusercontent.com/26861091/150675940-ae0998c3-fe51-4d55-b5a7-fc0f7b8ccd3e.png">

**Comment by adamhannigan** [comment]
Looks amazing @rickfurt 

I would make one small UI suggestion - is it possible to add more padding between the minimise arrow and the player?

Also, do you have any ideas how we can make the slider look more on theme with the game? (I.e. pixel art UI)

<img width="237" alt="Screen Shot 2022-01-23 at 12 17 58 pm" src="https://user-images.githubusercontent.com/11745561/150685468-d6ce9ce9-98a5-4437-bd89-ce304bb9ae84.png">

**Comment by rickfurt** [comment]
Thanks for the feedback, I have an idea to customise the slider in a way more in theme with the game.

**Comment by adamhannigan** [comment]
@rickfurt Nice, I am looking forward to seeing the PR 💪

**Comment by Rofrtd** [comment]
@rickfurt thanks mate, Let's get a pairing sesh to finish this up! 🌻

**Comment by rickfurt** [comment]
I'm working to fix the issues into the music player.

* On Mobile -> the volume controls will be hidden( use the device native controls for volume instead )
* On safari/Chrome -(desktop) -> the autoplay is disabled by default due to its policy so the music player will start as paused until the user interact with it

If there are other alternatives I missed I'd like to know so we can make the music player even better.
