### ISSUE TITLE
[BUG] Travelling Salesman seconds left

### ISSUE THREAD

**Issue by jadler** [sunflower-land/sunflower-land#1252]
## Summary of Bug

The traveling salesman time remaining in seconds shows wrong values ​​(negative values).

## Expected Behavior

Show the time remaining to update the goods to be traded.

## Actual Behavior

On the day the goods were expected to be updated, the time remaining counter is displayed with negative values.

## Screenshots

![Imgur](https://i.imgur.com/qbjUDtp.png)

**Device Information (please complete the following information):**

- Device: PC
- OS: Linux
- Browser/App: Brave
- Version 1.41.96

**Comment by veenhdek** [comment]
Looks like the salesman disappeared as expected now, however maybe if you do not refresh your screen he continues to stand there. Will do some testnet testing to see if that's the reason.

**Comment by veenhdek** [comment]
Fix merged, issue can be closed
