### ISSUE TITLE
When I sync, the SFL token count goes down

### ISSUE THREAD

**Issue by DemonDG** [sunflower-land/sunflower-land#1270]
Before i sync,my sfl count is 129.6438. When i sync,the SFL token count goes 128.9438.
My farm is #91022,It happened 10 minutes ago.
And I'm sure I saved all the progress before syncing.
![380891658797635_ pic](https://user-images.githubusercontent.com/17607276/180901818-add0f483-33a4-4b34-b913-d9d741420291.jpg)
![380901658797642_ pic](https://user-images.githubusercontent.com/17607276/180901828-bcff80a0-cf3c-4d59-b77d-3b4a955c7138.jpg)
.

**Comment by DemonDG** [comment]
I record a video in this link.@adamhannigan 
https://twitter.com/bailong_wang/status/1551777587567161345?s=20&t=Lsd4ooi1VLENUOyw6UUkfw

**Comment by future2back** [comment]
Did you sell cake on this sync?

**Comment by DemonDG** [comment]
> Did you sell cake on this sync?
yes,i sell the cake then sync

**Comment by veenhdek** [comment]
When you sold cake I'll bet you got 14.7 SFL it's just rectifying that

**Comment by NotKeen** [comment]
> When you sold cake I'll bet you got 14.7 SFL it's just rectifying that as we've seen it other places

Yep I noticed that too. My guess: The Green Thumb boost (+5% sell value) is being applied to cakes, too. At least in the UI. Then on sync, the amount gets corrected by the smart contract.

**Comment by DemonDG** [comment]
> When you sold cake I'll bet you got 14.7 SFL it's just rectifying that as we've seen it other places

i try agian.When i sell my wheat cake,i receive 14.7 SFL.

**Comment by DemonDG** [comment]
> > When you sold cake I'll bet you got 14.7 SFL it's just rectifying that as we've seen it other places
> 
> Yep I noticed that too. My guess: The Green Thumb boost (+5% sell value) is being applied to cakes, too. At least in the UI. Then on sync, the amount gets corrected by the smart contract.

You are right sir.

**Comment by veenhdek** [comment]
I think for now you can close this issue as its a UI bug but not breaking

**Comment by DemonDG** [comment]
> I think for now you can close this issue as its a UI bug but not breaking

ok,i close this issue.
