### ISSUE TITLE
[BUG] Can not create World / pay donation (METAMASK)

### ISSUE THREAD

**Issue by Malocey** [sunflower-land/sunflower-land#1293]
# Summary of Bug

## Screenshots

![image](https://user-images.githubusercontent.com/110396933/182145132-240ff0aa-a3c3-4286-98a8-7280a44cfe9f.png)

### Here you can See The Instant error I get back.

![image](https://user-images.githubusercontent.com/110396933/182146987-f3b16284-8cb9-4ae9-864d-263ef0418e56.png)

### Here is the 137 Error I get

![image](https://user-images.githubusercontent.com/110396933/182156264-4c6b62ed-1286-40eb-8625-39d8c7156de7.png)

### If you need additional info I'm ready to share

**Comment by j923sneaks** [comment]
All 150k farms have been minted so it returns an error as expected.

@adamhannigan i think we need to refactor `AuthMachine` to execute check supply first before checking access. Looks like it's not going to `supplyReached` state. I want to PR but I'll defer to you for the correct flow 😄

**Comment by Malocey** [comment]
Okay, that is information that would be nice if this stood on the website or anywhere or on google :D ^^. Can anyone provide me the discord link? Because the website link doesn't work.

![image](https://user-images.githubusercontent.com/110396933/182165509-02651aa0-4649-4eed-8d0b-6946f98aea39.png)

**Comment by veenhdek** [comment]
> https://sunflower-land.com/discord.gg/sunflowerland

Not sure where you found that full link (if you could tell us that'd be great) the discord link is the second part only. discord.gg/sunflowerland

**Comment by veenhdek** [comment]
> Okay, that is information that would be nice if this stood on the website or anywhere on google :D ^^.

Like @j923sneaks said it is supposed to say max reached when minting we will fix that :)

**Comment by Malocey** [comment]
> > https://sunflower-land.com/discord.gg/sunflowerland
> 
> Not sure where you found that full link (if you could tell us that'd be great) the discord link is the second part only. https://discord.gg/sunflowerland
> 
> The first part is the website https://sunflower-land.com/

:) Yeah I see it after It after I copied the Links. I found the discord link here https://sunflower-land.com/#community

![image](https://user-images.githubusercontent.com/110396933/182205470-1b599f22-9e45-4f37-a64e-945280f061b8.png)

**Comment by veenhdek** [comment]
Thanks for pointing that out, it has been fixed! 🚀

**Comment by roderickvella** [comment]
Same problem here. Thanks

**Comment by adamhannigan** [comment]
Thanks for raising this. @j923sneaks You are right. I will check out these flows now, and make sure the smart contract interactions are working as intended

**Comment by adamhannigan** [comment]
https://github.com/sunflower-land/sunflower-land/pull/1303

**Comment by Malocey** [comment]
> Thanks for pointing that out, it has been fixed! 🚀

No problem, I'm glad to be helpful ✊ 🚀

**Comment by j923sneaks** [comment]
![image](https://user-images.githubusercontent.com/89294757/182735488-d71c9b5e-44e6-4757-a4f4-99fcbb952c63.png)

in production 🚀

**Comment by Malocey** [comment]
Alright I see the update is live so this "BUG" can be closed thanks for help
