### ISSUE TITLE
[BUG] I can't withdraw Wicker Man

### ISSUE THREAD

**Issue by vitt0** [sunflower-land/sunflower-land#1297]
## Summary of Bug

I'm not being able to withdraw the Wicked Man NFT, every time that I try I get the "Something went wrong!" error. I'm also having the same problem with the "trading ticket's" and I try to withdraw others NFT's and I dind't have any problem with them.

## Steps to Reproduce

1) Go to goblin town
2) Click on "Bank"
3) Withdraw -> SFL Item 
4) Select Wicked Man 
5) Click on the withdraw buttom, complete the captcha
6) The "Something went wrong!" error appears

## Screenshots

![image](https://user-images.githubusercontent.com/11968934/182256376-eb2069a1-8efc-40ac-ae52-01e80a6c26ac.png)

## Device Information 

- Device: Computer
- OS: Windows 10
- Browser: Chrome
- Version: 103.0.5060.134 (Build oficial) (64 bits)

**Comment by adamhannigan** [comment]
Thanks for raising this @vitt0 

The team is looking into this now.

**Comment by adamhannigan** [comment]
Solved as of last week 👍
