### ISSUE TITLE
[BUG] Can not Harvest - Goblin Shovel Gone

### ISSUE THREAD

**Issue by hujikol** [sunflower-land/sunflower-land#1298]
## Summary of Bug

Following the same issue in discussion #1292 

## Steps to Reproduce

Provide detailed step-by-step instructions for how this bug can be reproduced.

1. Time to harvest crops
2. Harvesting crops
3. Can't harvest the ready crops
   > No shovel stolen modal pop up

## Expected Behavior

There should be a warning pop-up when the shovel is stolen

## Actual Behavior

No warning pop-up has to refresh the page to make the warning appears

https://user-images.githubusercontent.com/12151051/182275634-2886332a-bece-4362-9537-ca46a3f32d5c.mp4

https://user-images.githubusercontent.com/12151051/182275600-30eb5855-2de7-44c6-aaf4-d19ecc018662.mp4

**Device Information:**

- Device: Desktop PC
- OS: Windows 10
- Browser/App: Firefox
- Version 103.0.1 (64-bit)

**Comment by adamhannigan** [comment]
Thanks for raising this. This has been solved in our latest release 🤗 

https://github.com/sunflower-land/sunflower-land/releases/tag/v0.5.7-goblin-shovel-modal-fix

**Comment by kelvint83** [comment]
> 

This has not been fixed yet.
