### ISSUE TITLE
Farm Upgrades / Goblins

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#132]
In Sunflower Land, we want to gamify more of the aspects of the game. We will tell the narrative of Goblins versus humans.

At the beginning, you will find Goblins are blocking off certain areas of the farm. You must pay them to go away and give you new seeds.

**Includes**

- Goblins standing on fields
- Upgrade modals
- Upgrade farm action / business logic
- Unlock crops
- Unit tests

**Comment by gabiqueiroga** [comment]
I dont know if I got the ideia, but..

![goblin_swimming](https://user-images.githubusercontent.com/69090306/151066361-c4440612-6a53-4613-9f52-aaf94a24eccb.gif)

https://user-images.githubusercontent.com/69090306/151066763-83ffd6f5-1dca-45b2-a69c-dffd2fb8e9e4.mp4

**Comment by adamhannigan** [comment]
@gabiqueiroga This is great. We will get this in! Thank you 🤗

**Comment by adamhannigan** [comment]
The MVP upgrade system is now live in `main` branch
