### ISSUE TITLE
[CHANGE] Allow Backing-out of the Hoarding Modal

### ISSUE THREAD

**Issue by ShiningMinions** [sunflower-land/sunflower-land#1354]
## Background:
Please see original discussion here: https://github.com/sunflower-land/sunflower-land/discussions/1307

As a player, it is extremely frustrating when I get a "Hoarding" message. I'm being forced to sync, and I cannot close this modal, nor undo my previous action.

![Hoarding Modal](https://user-images.githubusercontent.com/103600068/182886571-03bdcac8-c996-4f75-aec1-bb4f4b8b3470.png)

## How the Feature is Currently Working

Here are my current choices when I receive a "Hoarding" modal popup:

1. I can hard-refresh my browser and lose all of my progress back to the last auto-save.
2. I can press the "Sync" button, but it's a pain because I would have preferred to do a few more actions before syncing (i.e. chop some more wood, harvest a few more crops, etc.) - then sync after these. A modal I cannot close stops me from this preparation.

## How the Feature Should Be Changed

Allow me to close the modal, which therefore reverts my previous action (i.e. the action which caused this modal to appear). This gives me a chance to prepare the rest of my farm for a sync.

## Proof of Community Demand

See upvotes and discussion: https://github.com/sunflower-land/sunflower-land/discussions/1307

## Contributors

- I have my hands tied ATM with other things. I am asking if some other community dev can pick this up and implement.

## Technical Requirements

1. Add a new button to this modal "Back".
2. Add the "X" icon top-right of modal.
3. When you click "Back" button or "X" icon, the following should happen:
 a. Revert the player's last action, which caused the Hoarding modal to appear (in this example, player harvested one too many eggs).
 b. Close the modal.
4. If the player conducts the same action again, then show this modal again and repeat same process.

### Backend Updates Needed

N/A

### Smart Contract Updates Needed

N/A

## UI/UX Design Requirements

1. Just add a "Back" button to the already-existing modal.

## Assets Needed:

N/A

**Comment by AzaroQL** [comment]
I also face this from time to time and Im forced to reload the page in order to prepare my farm for sync.

Ill try to look at this today/tomorrow and will update on results.

**Comment by ShiningMinions** [comment]
> I also face this from time to time and Im forced to reload the page in order to prepare my farm for sync.
> 
> Ill try to look at this today/tomorrow and will update on results.

This is especially bad for chicken coop holders with mutant chickens. I get this message quite literally all the time for eggs.

**Comment by Polysemouse** [comment]
Instead of reverting the player's last action, I would recommend preventing the action in the first place (see my comments in [#1307](https://github.com/sunflower-land/sunflower-land/discussions/1307).  That might be easier to implement and will have less chance to mess up the game state
