### ISSUE TITLE
[CHORE] Localize Bank Withdraw Conditions & Not Withdrawable by Default

### ISSUE THREAD

**Issue by ShiningMinions** [sunflower-land/sunflower-land#1355]
## Summary

I am constantly seeing the following bugs appear over and over again:
1. Item shouldn't be withdraw-able, but is.
2. Item should be withdraw-able, but is not.

This is due to the ever-growing list of niche withdraw conditions based on the player's current farm state. Therefore, I recommend we rethink this function. Here is how the function is currently lookng:

File: `bankUtils.ts`

```ts
export function canWithdraw({ item, game }: CanWithdrawArgs) {
  // Coming soon
  if (isSeed(item)) {
    return false;
  }

  // Coming soon
  if (item in SKILL_TREE) {
    return false;
  }

  // Coming soon
  if (item in FOODS()) {
    return false;
  }

  // Quest item
  if (item in QUEST_ITEMS) {
    return false;
  }

  if (item === "Engine Core" || item == "Observatory") {
    return false;
  }

  if (item in SHOVELS) {
    return false;
  }

  // Make sure no trees are replenishing
  if (
    item === "Woody the Beaver" ||
    item === "Apprentice Beaver" ||
    item === "Foreman Beaver"
  ) {
    return Object.values(game?.trees).every((tree) => canChop(tree));
  }

  if (item === "Kuebiko" && hasSeeds(game.inventory)) {
    return false;
  }

...etc...

}
```
One major reason this bug keeps reoccurring is that **an item is withdraw-able by default**. Instead, we should flip this logic by stating: **an item is NOT withdraw-able, UNLESS explicitly allowed**.

I recommend that instead of one monolithic withdraw function, we somehow store this localized logic on the item level, using some sort of lookup process. Perhaps this would be best extending the "CraftableItem" type in `features/game/types/craftables.ts`, or something like this:

```ts
export interface CraftableItem {
  id?: number;
  name: CraftableName;
  description: string;
  tokenAmount?: Decimal;
  ingredients?: Ingredient[];
  disabled?: boolean;
  requires?: InventoryItemName;
  isPlaceholder?: boolean;

  // NEW FIELD HERE - This means by default, NOTHING is withdrawable UNLESS I EXPLICITLY write it here.
  // This would save a lot of bugs from occurring by default.
  canWithdraw?: boolean | (gameMachine, goblinMachine) => boolean;
}
```
In this way, our `canWithdraw()` function can be much simplified into something like the following:

```ts
export function canWithdraw(item: CraftableItem) {
 const canWithdraw: boolean = typeof item.canWithdraw === 'function' ? item.canWithdraw() : !!item.canWithdraw;
 return canWithdraw;
}
```

## TODO

1. Implement some localized approach for detecting if an item is withdraw-able or not. See above example of an approach which can be taken.
2. Ensure that an item is NOT withdrawable by default UNLESS explicitly allowed.
3. Ensure bank withdraw tests are up to date and no existing tests break.

**Comment by adamhannigan** [comment]
@ShiningMinions This is a great suggestion 👏 

The conditions around withdraws are getting a bit of makeover in land expansion. Essentially anything that is placed on the farm, cannot be withdrawn.

This logic will get added over the next 2-3 weeks so I would suggest we go forward with this change, but hold off until we make the updates with land expansion 😄

**Comment by Myth727** [comment]
> @ShiningMinions This is a great suggestion 👏
> 
> The conditions around withdraws are getting a bit of makeover in land expansion. Essentially anything that is placed on the farm, cannot be withdrawn.
> 
> This logic will get added over the next 2-3 weeks so I would suggest we go forward with this change, but hold off until we make the updates with land expansion 😄

Just to clarify,  let's use foreman beaver for example purposes. If I place him down after land expansion then it's permanently not withdrawable? Or just while it's placed down?

**Comment by Polysemouse** [comment]
I feel like the logic overhaul is really needed as we get into more possible states for NFTs in our farm, now that we can remove placed NFTs from the island
