### ISSUE TITLE
[ART] A goblin Flag-Art that will be displayed in all farms to symbolize the winning faction of the Quiz event

### ISSUE THREAD

**Issue by SteveChickenCX** [sunflower-land/sunflower-land#1359]
## Summary

This is a request for an asset that will be displayed on all farms to symbolize the winning faction of the Quiz event.

This is not an NFT and you don't need to craft it, it's an addition to the existing map!

At first we thought about a big Goblin flag that differs from the current NFT goblin flag, but we can roll with other type of assets that will symbolize the winning of the goblin team!

## Requirements

- Minified art submission
- Dimensions and colour palette match the gameplay
- Screenshot of the asset used in the game
- Original art, no plagiarism

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

You agree to the project's terms and conditions:
https://docs.sunflower-land.com/support/terms-of-service

Note: Your art & mechanic may be modified/altered by the community if needed.

## Rewards

Pride!, Double Pride if you are a goblin team member!

**Comment by rchrdbq** [comment]
Goblin winner banner!

![BannerSmall](https://user-images.githubusercontent.com/81706056/186219775-6efc79f9-78c4-4dd7-b9ad-8b475057d7b6.png)
![BannerBig](https://user-images.githubusercontent.com/81706056/186219793-048e191e-65ee-4efe-ae1b-ab9f1c695f24.png)
![Preview2](https://user-images.githubusercontent.com/81706056/186219828-994a487b-b061-4ff6-a599-9b611c0ad2c4.png)
![Preview](https://user-images.githubusercontent.com/81706056/186219841-eea8a754-0da1-4c7b-a612-d711c4cf92f0.png)

**Comment by MrSnorch** [comment]
![флаг](https://user-images.githubusercontent.com/104712725/187038333-38646177-3a98-49c3-a446-0d0edfa6051f.png)
![флаг-export](https://user-images.githubusercontent.com/104712725/187038344-3da7a814-e7bf-4200-8a82-34c0020eaf4a.png)
![на карте](https://user-images.githubusercontent.com/104712725/187038345-2324bc98-5fc5-446b-a4eb-a2b24adbf35a.png)

**Comment by MrSnorch** [comment]
![флаг v21](https://user-images.githubusercontent.com/104712725/187043746-7d38eea1-5d72-4f79-b187-376786ea90a0.png)
![флаг v21-export](https://user-images.githubusercontent.com/104712725/187043748-3f112264-244c-4a59-a696-f270017ff3e9.png)
![флаг v2](https://user-images.githubusercontent.com/104712725/187043749-d29551c4-8cb4-414a-9e3e-2c20af83d0be.png)

**Comment by Netherzapdos** [comment]
### **Quiz** Event Winner
---

Preview:
![Goblin Quiz Winner P](https://user-images.githubusercontent.com/101855553/188054116-69a572a0-d6fa-43ee-9df5-37763d84a9a7.gif)

Raw File:
![Goblin Quiz Winner R](https://user-images.githubusercontent.com/101855553/188054147-b3d46a69-f4be-4f65-aebf-bc04e5838b30.gif)

Let's go Team Goblin 💚
