### ISSUE TITLE
Pumpkin Soup

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#138]
<img width="586" alt="Screen Shot 2022-01-20 at 4 19 53 pm" src="https://user-images.githubusercontent.com/11745561/150407440-bef44880-ec9a-4403-bf41-3c207b75cdc9.png">

<img width="287" alt="Screen Shot 2022-01-20 at 4 19 50 pm" src="https://user-images.githubusercontent.com/11745561/150407458-9920525b-a601-4ee9-90b3-44f8142def0c.png">

The game is going further into the idea of crafting and collecting resources. In the new version, we are exploring gameplay mechanics to upgrade your farm. Instead of just acquiring $SFL, you will also need certain items.

In this case, pumpkin soup would cost 5 pumpkins and 5 tokens.

Any ideas what Pumpkin Soup could look like?

It would be great to explore something for Cabbage and Cauliflower as well 🤔

**Comment by Aestnelis** [comment]
![bigpumpkinsoup](https://user-images.githubusercontent.com/98103679/150422035-6c44de12-a84c-49e6-8292-65c575c21f2f.png)

**Comment by paluras** [comment]
![pumkinsoupbig](https://user-images.githubusercontent.com/98059798/150492236-70cfedf6-e68c-4e27-9f60-b16ee41b2dd4.png)
![pumkinsoup](https://user-images.githubusercontent.com/98059798/150492246-5018c5e6-6167-4ced-90a1-d6da8e9344e6.png)
