### ISSUE TITLE
[BUG] Find goblin

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1406]
Got find the goblin playing on mobile, goblin was not visible.
Connected on desktop, not asking for find goblin and can plant without problems.
Connected again on mobile, get message to find goblin on login, gobling is visible on map.

**Comment by hujikol** [comment]
It could happen when the goblin assets are not rendered yet, it has a similar issue with the bonus seed chest being missing in the bonus modal, while it just shows the bumkin or even sometimes none of them are showing in the bonus seed modal.

**Comment by Polysemouse** [comment]
The goblin shovel is now removed from the game.  Ticket can be closed
