### ISSUE TITLE
Additional Wallet Support

### ISSUE THREAD

**Issue by stevew00dy** [sunflower-land/sunflower-land#1408]
Wallet Integration. 

We are looking to setup wallet integrations for user onboarding. 

There are a few things we need to consider and this overview will lay out the steps required. 

I'm looking for a small team that can work on this and get it ready for the core devs to action. 

Step 1 - Create a UI for the in game wallet integration

Step 2 - Connect Coinbase
Step 3 - Connect Wallet Connect

Step 4 - Other Wallets - Will open a new screen that offers 1inch, trust wallet and sequence

Step 5 - Connect Coinbase SDK and setup matic purchase from in game (direct to the users wallet)

The first popup will need to show when first accessing the game but there should also be a menu option whilst inside the game that people can use to swap between wallet providers they have connected. 

They will be required first to connect the wallet to their account and each account can only have one wallet connected. 

A user can have a metamask, coinbase and other wallet connected to the farm but once a wallet is connected, it can't then be used on another farm.

I'm thinking about the idea that they will not be able to disconnect their wallet to then connect another. This would require a support ticket to stop multiaccounting.

**Comment by stevew00dy** [comment]
This is a good example of how the UI could look

https://github.com/sunflower-land/sunflower-land/discussions/1284#discussioncomment-3290744

**Comment by AzaroQL** [comment]
Started working on it.

**Comment by stevew00dy** [comment]
![image](https://user-images.githubusercontent.com/5225886/202223343-681abc8c-aba2-44d0-b3f2-9d0b9d7f3f3d.png)
Potential concept for login. 

Recommend removing coinbase from the top section and allowing a user to pin their fav wallet here. 

Change initial text to Connect your Web3 Wallet

Change secondary text to Other available wallets.
