### ISSUE TITLE
[BUG] Formats for Time Left are not consistent

### ISSUE THREAD

**Issue by Polysemouse** [sunflower-land/sunflower-land#1422]
![image](https://user-images.githubusercontent.com/107602352/190565660-ecf557c9-a6c9-4223-abb0-bd0eea928f3b.png)

## Summary of Bug

Formats for time left is not consistent across the game.

## Steps to Reproduce

Mine or plant a resource that takes more than an hour to harvest.  When it should show `5hr 0mins` it shows `5hr 42 secs`

## Expected Behavior

These strings should be shown (mid formats):
5 hours, 0 minutes, 24 seconds -> `5hr 0mins`
1 day, 0 hours, 0 minutes, 2 seconds -> `1d 0hrs`
(values are rounded down, showing the 2 most significant units)

These strings should be shown (short formats):
5 hours, 0 minutes, 24 seconds -> `5hrs`
1 day, 0 hours, 0 minutes, 2 seconds -> `1d`
(values are rounded down, showing the 1 most significant unit)

## Actual Behavior

These strings are shown instead (mid formats):
5 hours, 0 minutes, 24 seconds -> `5hr 24secs`
1 day, 0 hours, 0 minutes, 2 seconds -> `1d 2secs`
(values are rounded down, but not showing the 2 most significant units)

These strings should be shown (short formats):
5 hours, 0 minutes, 24 seconds -> `6hrs`
1 day, 0 hours, 0 minutes, 2 seconds -> `2d`
(most games show the time as the rounded down value, not the rounded up value)

These strings are shown instead:

## Fix

In `src/lib/utils/time.test.ts`:

```typescript
function getTimeUnits(seconds: number) {
  const secondsPart = Math.ceil(seconds % ONE_MIN);
  const minutesPart = Math.floor((seconds / ONE_MIN) % ONE_MIN);
  const hoursPart = Math.floor((seconds / ONE_HR) % 24);
  const daysPart = Math.floor(seconds / ONE_DAY);

  return [
    daysPart && timeToStr(daysPart, "day"),
    hoursPart && timeToStr(hoursPart, "hr"),
    minutesPart && timeToStr(minutesPart, "min"),
    secondsPart && timeToStr(secondsPart, "sec"),
  ].filter(Boolean);
}

export function secondsToString(
  seconds: number,
  options: TimeStringOptions = { separator: "" }
) {
  const secondsCeil = Math.ceil(seconds);
  if (secondsCeil < ONE_MIN) {
    return timeToStr(secondsCeil, "sec", options);
  }

  if (seconds < ONE_HR) {
    const minutesCeil = Math.ceil(seconds / ONE_MIN);
    return timeToStr(minutesCeil, "min", options);
  }

  if (seconds < ONE_DAY) {
    const hoursCeil = Math.ceil(seconds / ONE_HR);
    return timeToStr(hoursCeil, "hr", options);
  }

  const daysCeil = Math.ceil(seconds / ONE_DAY);
  return timeToStr(daysCeil, "day", options);
}
```

should be 

```typescript
function getTimeUnits(seconds: number) {
  const secondsPart = Math.ceil(seconds % ONE_MIN);
  const minutesPart = Math.floor((seconds / ONE_MIN) % ONE_MIN);
  const hoursPart = Math.floor((seconds / ONE_HR) % 24);
  const daysPart = Math.floor(seconds / ONE_DAY);

  return [
    daysPart && timeToStr(daysPart, "day"),
    (daysPart || hoursPart) && timeToStr(hoursPart, "hr"), // <-- changes here
    (daysPart || hoursPart || minutesPart) && timeToStr(minutesPart, "min"), // <-- changes here
    timeToStr(secondsPart, "sec"), // <-- changes here
  ].filter(Boolean);
}

export function secondsToString(
  seconds: number,
  options: TimeStringOptions = { separator: "" }
) {
  const secondsFloor = Math.floor(seconds); // <-- changes here
  if (secondsFloor < ONE_MIN) { // <-- changes here
    return timeToStr(secondsFloor, "sec", options); // <-- changes here
  }

  if (seconds < ONE_HR) {
    const minutesFloor = Math.floor(seconds / ONE_MIN); // <-- changes here
    return timeToStr(minutesFloor, "min", options); // <-- changes here
  }

  if (seconds < ONE_DAY) {
    const hoursFloor = Math.floor(seconds / ONE_HR); // <-- changes here
    return timeToStr(hoursFloor, "hr", options); // <-- changes here
  }

  const daysFloor = Math.floor(seconds / ONE_DAY); // <-- changes here
  return timeToStr(daysFloor, "day", options); // <-- changes here
}
```

**Comment by veenhdek** [comment]
Is it inconsistent anywhere? I personally like the seconds coming up after it reaches 5 hours and 0 min that would be expected behavior to me, the next significant units that are actively counting...

**Comment by Polysemouse** [comment]
@veenhdek with the current implementation, it will show "59mins 60secs" after chopping a tree.  Definitely something to change there.

The inconsistency come from when some values are rounded down and some values are rounded up for different time displays (see original post)

**Comment by future2back** [comment]
What happend to it???


![image](https://user-images.githubusercontent.com/74167741/194976344-1d961c8f-cd3f-433d-91c1-a65ac2cb8470.png)

**Comment by Polysemouse** [comment]
@future2back  All time displays are now rounded down.
