### ISSUE TITLE
Potato Statue

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#144]
Looking for some new inspiration for a potato statue. This is to encourage our new players to work hard to get gather Potatos.

This will be an NFT, so we need to avoid using the base asset pack.

This is what we currently have:

<img width="261" alt="Screen Shot 2022-01-21 at 12 28 11 pm" src="https://user-images.githubusercontent.com/11745561/150553825-fc5e14ce-a657-4382-beb0-3feb2ae63eb9.png">

**Comment by Telknub** [comment]
![PotatoStatue4](https://user-images.githubusercontent.com/38796969/150599672-5ec32dda-098c-4253-b7d1-c67e33bac7bc.png)

Tweaked this potato statue I made a few weeks ago. If you want I can remove the small potatoes and grass from the statue. I also made this cauliflower statue.

![CauliflowerStatue4](https://user-images.githubusercontent.com/38796969/150600964-db20dd86-8c2d-492f-aca7-5e34a08db8f7.png)

**Comment by adamhannigan** [comment]
> ![PotatoStatue4](https://user-images.githubusercontent.com/38796969/150599672-5ec32dda-098c-4253-b7d1-c67e33bac7bc.png)
> 
> Tweaked this potato statue I made a few weeks ago. If you want I can remove the small potatoes and grass from the statue. I also made this cauliflower statue.
> 
> ![CauliflowerStatue4](https://user-images.githubusercontent.com/38796969/150600964-db20dd86-8c2d-492f-aca7-5e34a08db8f7.png)

That potato statue is beautiful!!!

Are you happy for us to use this in the game?

**Comment by Telknub** [comment]
> > ![PotatoStatue4](https://user-images.githubusercontent.com/38796969/150599672-5ec32dda-098c-4253-b7d1-c67e33bac7bc.png)
> > Tweaked this potato statue I made a few weeks ago. If you want I can remove the small potatoes and grass from the statue. I also made this cauliflower statue.
> > ![CauliflowerStatue4](https://user-images.githubusercontent.com/38796969/150600964-db20dd86-8c2d-492f-aca7-5e34a08db8f7.png)
> 
> That potato statue is beautiful!!!
> 
> Are you happy for us to use this in the game?

Yes! I would love for you guys to use this in the game!

**Comment by adamhannigan** [comment]
@Telknub Have you got a minified version of this art? Where 1 pixel is actual 1px wide. Thanks! 🤗

**Comment by Telknub** [comment]
@adamhannigan
![PotatoStatueFinal](https://user-images.githubusercontent.com/38796969/152234895-f3ba3d3a-fe54-4eee-8f30-d00cac811ff9.png)

Sorry! I knew I had to send it but I forgot...

**Comment by adamhannigan** [comment]
@Telknub What is your Polygon address? We will airdrop you a statue on launch 🤗

**Comment by Telknub** [comment]
> @Telknub What is your Polygon address? We will airdrop you a statue on launch 🤗

Will send a DM on Discord. I am an ambassador on the server so it will be easy for you to check that it is really me.
