### ISSUE TITLE
Golden Cauliflower

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#145]
To inspire people to collect Cauliflowers and Gold. Any ideas how a Golden Cauliflower would look like?

This will be an NFT, so we need to avoid using the base asset pack.

**Comment by Telknub** [comment]
![GoldenCauliflower](https://user-images.githubusercontent.com/38796969/150601631-a1a498a2-879b-4458-8006-81d7e23e4371.png)

Just changed the colors on the Cauliflower I made for my cauliflower statue that I posted on the potato statue request.

**Comment by benaxol12** [comment]
Maybe like this 😄 
![56x68_](https://user-images.githubusercontent.com/98098031/150631267-6a88cb20-921b-49b4-bf4d-c7a14ec8b9dc.png)
![56x68](https://user-images.githubusercontent.com/98098031/150631202-eca343fa-3bc5-47eb-ad20-2eb74d49ccf6.png)
![29x31 gif](https://user-images.githubusercontent.com/98098031/150631160-6fb87e9c-7382-4963-ae70-2214639967bb.gif)
![98x92](https://user-images.githubusercontent.com/98098031/150631164-71747578-c53f-4e35-89a4-da6821a7fdc5.gif)

**Comment by adamhannigan** [comment]
> Maybe like this 😄 ![56x68_](https://user-images.githubusercontent.com/98098031/150631267-6a88cb20-921b-49b4-bf4d-c7a14ec8b9dc.png) ![56x68](https://user-images.githubusercontent.com/98098031/150631202-eca343fa-3bc5-47eb-ad20-2eb74d49ccf6.png) ![29x31 gif](https://user-images.githubusercontent.com/98098031/150631160-6fb87e9c-7382-4963-ae70-2214639967bb.gif) ![98x92](https://user-images.githubusercontent.com/98098031/150631164-71747578-c53f-4e35-89a4-da6821a7fdc5.gif)

That's cool. Does that mean when you plant a Cauliflower it would actually turn Gold?

**Comment by Valdeques** [comment]
![Golden Cauliflower](https://user-images.githubusercontent.com/5396264/150643744-dec76c64-45c7-4747-b926-454dfbe6b978.png) 
![Golden Cauliflower Plant](https://user-images.githubusercontent.com/5396264/150643749-d76b00cb-15e6-48ee-9920-fef038e592ef.png)

**Comment by benaxol12** [comment]
> > Maybe like this 😄 ![56x68_](https://user-images.githubusercontent.com/98098031/150631267-6a88cb20-921b-49b4-bf4d-c7a14ec8b9dc.png) ![56x68](https://user-images.githubusercontent.com/98098031/150631202-eca343fa-3bc5-47eb-ad20-2eb74d49ccf6.png) ![29x31 gif](https://user-images.githubusercontent.com/98098031/150631160-6fb87e9c-7382-4963-ae70-2214639967bb.gif) ![98x92](https://user-images.githubusercontent.com/98098031/150631164-71747578-c53f-4e35-89a4-da6821a7fdc5.gif)
> 
> That's cool. Does that mean when you plant a Cauliflower it would actually turn Gold?

Yes, if player have some luck.

**Comment by soteleon** [comment]
Holy cauliflower

![coliflower](https://user-images.githubusercontent.com/94320699/150665362-5f795b3f-4761-4f1a-895e-606eb9c6922a.png)

**Comment by soteleon** [comment]
Holy cauliflower 
![coliflowe300r](https://user-images.githubusercontent.com/94320699/150665473-69884cf6-c835-4f35-a501-217fbbf527cd.png)

![coliflowe300 2r](https://user-images.githubusercontent.com/94320699/150665623-69717def-1d9c-4ba8-a26e-6ea787c0c5f8.png)

**Comment by paluras** [comment]
![Cauliflowernom1shine1_2](https://user-images.githubusercontent.com/98059798/150680024-fab225fa-0b42-4a18-bf2c-c1122dbb4b93.png)
![Cauliflowernom1shine1_2_Smallsparkle](https://user-images.githubusercontent.com/98059798/150680025-28adf27f-470a-479c-8e3b-b3f5d5657b6c.png)
![Cauliflowernom1shine1_2_sparkle](https://user-images.githubusercontent.com/98059798/150680026-cd68ed2e-a895-4820-bd21-a3c1c5d161c1.png)
![Cauliflowernom1shine1s](https://user-images.githubusercontent.com/98059798/150680027-d3ea5449-7583-4bdb-97f4-969a1a2eb04a.png)

**Comment by soteleon** [comment]
1000 Trophie maybe?

![Uploading coliflowe100 trophie.png…]()

**Comment by soteleon** [comment]
> 1000 Trophie maybe?
> 
> ![coliflowe100 trophie](https://user-images.githubusercontent.com/94320699/150684541-cc9726b7-63da-4c61-ab2a-c2517c3956fc.png)
> 
> ![coliflowe200 trophie](https://user-images.githubusercontent.com/94320699/150684576-8dea7eed-130f-4516-b99d-40f07dc0be7c.png)

A pixelated one 40x32 px
![TROHPIE CAULIFFLOWR 40X32](https://user-images.githubusercontent.com/94320699/150804013-87323b0e-9a56-434c-a557-3ecbbb78d799.png)

**Comment by paluras** [comment]
![Cauliflowernom1shine1s-export-export](https://user-images.githubusercontent.com/98059798/150937655-c4bd5d3b-6f38-46b9-bb74-1457319c2ebe.png)
![Cauliflowernom1shine1s-export-expor1t](https://user-images.githubusercontent.com/98059798/150937665-f63e6f53-29fe-47b2-a5ca-c2cf5b306b23.png)
 Tried to clean it up a bit.

**Comment by soteleon** [comment]
God bless this godly vegetal

![golden cauli bigpng gif](https://user-images.githubusercontent.com/94320699/151087481-60339fa8-fdc4-4208-bafd-a3865b93db2c.gif) (The gif came out weird)
![golden cauli bigpng](https://user-images.githubusercontent.com/94320699/151087487-ca2fd9c1-daaf-4e48-b732-159af428e951.gif)
![golden cauli](https://user-images.githubusercontent.com/94320699/151087488-840adae5-fd68-4623-b05d-61751108d4ab.png)

**Comment by cambrios1** [comment]
![Golden_Cauli](https://user-images.githubusercontent.com/98171636/151135504-39c93c26-fa41-418e-8c83-27a0c6919021.png)

**Comment by Sarapico** [comment]
hi :)
![pixil-frame-0(15)](https://user-images.githubusercontent.com/98893182/152205922-72ba9520-0478-4d96-991b-05a8ad58f3ba.png)
![pixil-frame-0(16)](https://user-images.githubusercontent.com/98893182/152205929-e0b76c45-3309-4a6d-8245-f28d2f9732af.png)
![pixil-frame-0(17)](https://user-images.githubusercontent.com/98893182/152205947-ecee318e-f773-4636-bef8-ea4577fb6d14.png)

**Comment by adamhannigan** [comment]
@paluras We have found a winner. Congratulations!

More details to come. You will be airdropped a Golden Cauliflower on launch 🤗
