### ISSUE TITLE
Onboarding Ramp (Fiat into Crypto)

### ISSUE THREAD

**Issue by stevew00dy** [sunflower-land/sunflower-land#1453]
Due to the delayed communications with Coinbase on their CEX listing I'm looking into opportunities for user onboarding and a reliable simple solution. 

RAMP . Network is the onboarding ramp that Axie uses and I've also personally used them to onboard more than 7 figures from fiat into crypto so I trust them, I've met the team in person and I feel they will be a good simple solution to ensure we allow people the ability to purchase Crypto in game. 

The ONLY challenge with this is getting the SFL listed which I will work on but is also a lengthy process. To ensure that we get started, I propose that we start with MATIC and also add a UI for swap

This way users can by MATIC directly in game or via the website and then swap it for SFL. 

[Ramp Website](https://ramp.network/)
[Official Docs](https://docs.ramp.network/)

**Comment by mGranTY** [comment]
hey @stevew00dy can you explain the mode you want it in SFL? there are three ways we can implement this as explained in the docs(https://docs.ramp.network/web/quick-start-web/) 

Overlay mode, Hosted mode and Embedded mode. 

For overlay and Embedded mode we need to add the ramp sdk to sunflower lands dependencies (https://www.npmjs.com/package/@ramp-network/ramp-instant-sdk)

**Comment by stevew00dy** [comment]
I'll need to confirm with Adam but I think it makes sense for a more seemless experience to consider embedded

**Comment by stevew00dy** [comment]
Spoken with RAMP today. They will provide clarity on what onboarding will look like - Will update this within the week

**Comment by stevew00dy** [comment]
After extensive conversations with many providers we have found a solution with Wyre. They have agreed to terms that will be beneficial to our users and we will look into integrating with them after Land Expansion is launched.
