### ISSUE TITLE
[BUG] Community Garden Shows 50 SFL in top right corner, regardless of SFL balance

### ISSUE THREAD

**Issue by SuperSynapse** [sunflower-land/sunflower-land#1469]
## Summary of Bug

SFL Balance in Community Garden displays as 50 SFL regardless of _ACTUAL_ SFL balance

## Steps to Reproduce

Step 1: Go to the Community Garden

Step 2: Observe the top right corner's SFL balance

## Expected Behavior

Expected to see actual balance of SFL in the Community Garden. Took me by suprise when I saw 50 SFL in the top corner.

Have refreshed my browser several times, and this issue still shows.

## Actual Behavior

Whenever you travel to the Community Garden the SFL Balance displays as 50 SFL regardless of actual SFL balance

## Screenshots
![Community Garden Bug](https://user-images.githubusercontent.com/51135442/193478618-28820a34-fe87-443a-8556-1edfb5bb7ec0.PNG)

**Device Information (please complete the following information):**

- Device: PC
- OS: Windows 10 - 64 bit
- Browser/App: Brave
- Version: [Version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit)](https://brave.com/latest/)

Farm ID: 27617
Discord: SuperSynapse#0786

**Comment by TaRaSiSt** [comment]
And it is necessary, because in the garden, mint happens for resources from the wallet. The garden is not connected to the farm, it is a separate location. Therefore, here is another indicator of SFl
