### ISSUE TITLE
[BUG] SFL Token Image

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#1471]
## Summary of Bug- Image of Sunflower in Top right hand corner not loading/rendering in. 
![Screenshot_20221002-210306_MetaMask](https://user-images.githubusercontent.com/96928557/193485308-fb15befd-dbce-4bf1-a496-a02295b2a565.jpg)

**Comment by Myth727** [comment]
New issue @adamhannigan 
When clicking on I'm human for verification with the captcha. Goes from the check ✔️ then changes to a red dot and says failure...but loads up the remaining screens to pay gas and sync.

**Comment by Myth727** [comment]
https://user-images.githubusercontent.com/96928557/193644411-1b9ebfc7-a50f-4910-941f-73c239595e3a.mp4

**Comment by Myth727** [comment]
@adamhannigan I was able to get same results when syncing again so I recorded it for you to see. Enjoy :)

**Comment by hujikol** [comment]
> New issue @adamhannigan When clicking on I'm human for verification with the captcha. Goes from the check ✔️ then changes to a red dot and says failure...but loads up the remaining screens to pay gas and sync.

You can kindly make a new issue for this matter because it's not related to this [BUG] SFL Token Image #1471 issue

**Comment by Myth727** [comment]
> > New issue @adamhannigan When clicking on I'm human for verification with the captcha. Goes from the check ✔️ then changes to a red dot and says failure...but loads up the remaining screens to pay gas and sync.
> 
> You can kindly make a new issue for this matter because it's not related to this [BUG] SFL Token Image #1471 issue

I was assuming I might need to do such. Busy atm, just trying to help show whatever bugs or issues I find. If I have time later I'll create a new post for the other issue. Have a good morning :)

**Comment by Myth727** [comment]
Accidentally closed this as complete.

**Comment by Myth727** [comment]
@adamhannigan peek over this stuff when you have the chance

**Comment by Myth727** [comment]
Reopening!

**Comment by adamhannigan** [comment]
Good spot, thanks for raising this 👏

**Comment by Myth727** [comment]
> Good spot, thanks for raising this 👏

No problem,  would you like to note it down and have me close this out? Otherwise I'll leave it open til you

**Comment by Myth727** [comment]
> Good spot, thanks for raising this 👏

Thanks, I'll close this out now. Assuming you noted it down and will get it taken care of :)
