### ISSUE TITLE
[BUG] Undead Rooster price/supply

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1516]
Hello guys

Price/supply from Undead Rooster was:

![image](https://user-images.githubusercontent.com/74167741/195407643-de32e8c5-0f8b-481b-91f9-cc01cfa3dd08.png)

And now it is:

![image](https://user-images.githubusercontent.com/74167741/195414207-531e461e-6328-4034-8058-c6c54594988e.png)

What happened?

**Comment by Myth727** [comment]
I assume they are just adjusting the price points and total supply. If I could share or give out extra warbonds I would totally send you a few.

**Comment by future2back** [comment]
I cant believe this. It would be a tremendous lack of respect for users. I invested in resources and synchronized to contribute when i saw the opportunity to get this.

If they changed it, i changed my strategy, lost my time and resources and will not be reachable for me. What a fail!

I cant believe they will do that. I will be waiting for an official announcement.

**Comment by Myth727** [comment]
Yes wait for an announcement and please don't go off my assumptions.

**Comment by j923sneaks** [comment]
![image](https://user-images.githubusercontent.com/89294757/195506046-925d253b-b960-4017-86db-fc047f459924.png)

It's 1k wb and 5k supply so the current in game is correct. The team misconfigured then corrected so dont feel slighted.

**Comment by Myth727** [comment]
> ![image](https://user-images.githubusercontent.com/89294757/195506046-925d253b-b960-4017-86db-fc047f459924.png)
> 
> It's 1k wb and 5k supply so the current in game is correct. The team misconfigured then corrected so dont feel slighted.

Would be nice if warbonds could be transferred now. Cause I'd totally send @future2back what he needs to mint the item he wanted before it's too late.
