### ISSUE TITLE
Contributing Guidelines & Milestones

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#152]
Include Contributing Guidelines and Milestones so developers and designers can contribute efficiently.

The goal of this is to:

- Find out what work can be helped out with
- The deadlines of upcoming pieces of work
- Pull request/issue criteria for consistency

## Includes

- [x] Developer Contributing.MD
- [x] PR template
- [x] Designer Contributing.MD
- [x] Milestones

**Comment by adamhannigan** [comment]
@Pranav-yadav I thought we could move the conversation over here.

For the milestone, I have taken the roadmap approach:

- Beta
- Resource Gathering + Minting NFTS
- Crowd Sourced Crafting
- Artwork/UX enhancements (for all other improvements along the way).

**Comment by Pranav-yadav** [comment]
> @Pranav-yadav I thought we could move the conversation over here.
> 
> For the milestone, I have taken the roadmap approach:
> 
> * Beta
> * Resource Gathering + Minting NFTS
> * Crowd Sourced Crafting
> * Artwork/UX enhancements (for all other improvements along the way).

Great 👍 🚀
