### ISSUE TITLE
[DOC.]: Security Policy Missing 

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#156]
### Issue: Security policy Missing
Suggest how users should report **security vulnerabilities** for this repository

### Scope
- Documentation ~ Security

### Tasks

- [ ] Add security policy to the repo.

**Comment by adamhannigan** [comment]
@Pranav-yadav Great point!

Have you seen any good examples of projects that do this well?

**Comment by Pranav-yadav** [comment]
> @Pranav-yadav Great point!
> 
> Have you seen any good examples of projects that do this well?

Yep @adamhannigan
E.g.:

- [Ethereum Solidity](https://github.com/ethereum/solidity/security/policy)
- [Polygon bor](https://github.com/maticnetwork/bor/security/policy)
- [Ethereum Go](https://github.com/ethereum/go-ethereum/security/policy)
