### ISSUE TITLE
[LEGAL]: Licence(s) Proposal

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#157]
### Scope:
- Legal ~ Licencing

### 📃  Proposal
for;
#### Front-end Code only:
- [**MIT**](https://opensource.org/licenses/MIT) _(for code only, though not sure about any other licence(s))_
  > Copyright Notice Example 👇 
  > Sunflower-Land Code © 2022 by Thought Farm Pty Ltd is licensed under [MIT](https://opensource.org/licenses/MIT)

#### all Multimedia Assets Only:
- [**Attribution-NonCommercial-NoDerivatives 4.0 International**](https://creativecommons.org/licenses/by-nc-nd/4.0/) _(for all multimedia assets only, though not sure about other licence(s))_
  > Copyright Notice Example 👇 
  > Sunflower-Land Multimedia Assets © 2022 by Thought Farm Pty Ltd is licensed under [Attribution-NonCommercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/)

---
Though I suggest to remix licence(s) as per the needs (like in case of NFT's, Tokens and other in game resources)

Feel free to discuss and suggest any other approaches 👍 

> P.S.: I'm not a professional legal adviser
---

### DISCLAIMER & NOTE:
Above text / markdown / html is for **example only**. It does **NOT** represents the original Licence(s) for Sunflower-Land repo.

**Comment by adamhannigan** [comment]
@Pranav-yadav Something that devastated the team last time was that people cloned the repo and scammed others.

There were games popping up for instance where the charity donation went directly to their wallet. We want to provide some legal protection to prevent others from copying/modifying and creating one of these versions.

I'm big on sharing the code and want others to learn from this project. Ideally they just shouldn't be able to use the same UI/gameplay flows just by cloning the repo - this will confuse players as to which project is the legitimate one.

Any ideas how we can approach this?

**Comment by Pranav-yadav** [comment]
I completely agree with you @adamhannigan 
We need to research for perfect the licence for this use case..
I'll ping if anything comes across..

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
