### ISSUE TITLE
[BUG] Unable to list multiple cakes on market. 

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#1601]
## trying to post 10 pumpkin cakes for sale.

Video attached of me going to market to post 10 pumpkins for sale and getting error message.

## Steps to Reproduce

Watch video, very simple to reproduce 

https://user-images.githubusercontent.com/96928557/199371851-f78bbd6a-80c8-4cc5-b16e-463646e41399.mp4

Simply wanted to notify @adamhannigan of this. Keep up the awesome work everyone :)

**Comment by Polysemouse** [comment]
![image](https://user-images.githubusercontent.com/107602352/199516216-4549ff42-7c2b-4fa4-9b2c-f3bd0454f342.png)
It looks like the maximum number of cakes you can list is 1.  Are there such restrictions in the backend?  If yes, the "List trade" button should be disabled in the front end if the quantity entered is greater than 1.

**Comment by Myth727** [comment]
Agreed on what you said, just wanted to make sure everyone is aware.
