### ISSUE TITLE
Farm Dog NFT

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#161]
Redesign a dog NFT to be more in-line with the style of the game.

The total supply of the dog has already been reached (75). The winning design will get one of these airdropped in the new version 🚀 

**Voting closed: 7th Feb**

Vote on your favourite piece with a ❤️

**Comment by AyoubRhalam** [comment]
![image](https://user-images.githubusercontent.com/43474459/150685234-5e716e8f-7cb7-450c-af45-6c9abaf957f7.png)

**Comment by AyoubRhalam** [comment]
![image](https://user-images.githubusercontent.com/43474459/150685246-369fbf32-7f27-4ac8-8307-a8f745e3d7fc.png)

**Comment by Aestnelis** [comment]
![bigdog](https://user-images.githubusercontent.com/98103679/150685779-abcd135b-f979-467d-a95d-519a66a12304.gif)
![dog](https://user-images.githubusercontent.com/98103679/150685784-037a3de9-9ec8-4663-9e44-e1dc98f89ccc.gif)

**Comment by Driftingwood** [comment]
![53258084-6A78-4106-9B02-FFD17B49EA57](https://user-images.githubusercontent.com/25971765/150692452-528207b8-ef70-4206-8422-3affc7e79f9b.gif)

**Comment by soteleon** [comment]
At some farms I see some dachshund, maybe here it can follow the farmer beating some felines

![dog-export ](https://user-images.githubusercontent.com/94320699/150693788-d628aac7-a9c5-4505-a0a1-54172ac4d05e.png)
![dog-export 2 ](https://user-images.githubusercontent.com/94320699/150693789-62b04e38-5510-4e2a-a15c-f10ff7f81660.png)

(I'll add a gif later)

**Comment by gabiqueiroga** [comment]
WIP

![image](https://user-images.githubusercontent.com/69090306/151474703-21acc2b0-d4fc-495d-b350-6f3272c7d8ea.png)



![DogTest](https://user-images.githubusercontent.com/69090306/151474447-6f6b16ed-e524-4539-9b28-efdfb9e04f79.png)

**Comment by gabiqueiroga** [comment]
Put original dog and other animals for size comparison

![image](https://user-images.githubusercontent.com/69090306/151991896-ffb4b834-f304-4502-95d4-108e5ec18a5b.png)


![image](https://user-images.githubusercontent.com/69090306/151991110-02adc4cc-f872-4f86-bf9d-429f79a20a4d.png)

![dog1](https://user-images.githubusercontent.com/69090306/151991708-d657dea0-8b86-4fc9-8e51-e2ed6e32b06b.png)

**Comment by Leaztat** [comment]
![image](https://user-images.githubusercontent.com/99042548/152581057-0d9dc5c9-76d4-4394-bbc9-233b09435008.png)

**Comment by alicanharmanci** [comment]
https://user-images.githubusercontent.com/43474459/150685234-5e716e8f-7cb7-450c-af45-6c9abaf957f7.png

**Comment by Aestnelis** [comment]
> ![image](https://user-images.githubusercontent.com/99042548/152581057-0d9dc5c9-76d4-4394-bbc9-233b09435008.png)

This is my dog why are you copying ?

**Comment by AND01GAMES** [comment]
![152582332-8599c20b-8efa-47fa-8cca-5d2c99b2d91e](https://user-images.githubusercontent.com/99080139/152643666-ea81019e-eb14-4214-812a-4593955dff15.png)

**Comment by adamhannigan** [comment]
@gabiqueiroga Amazing work! We have a winner 🤗 🏆

**Comment by alicanharmanci** [comment]
0xa21FFea1E0adFd0db67a1Dbb392304f41f84ca7c Do you ship to address?

**Comment by alicanharmanci** [comment]
I got message about earning nft but my message deleted. 0xa21FFea1E0adFd0db67a1Dbb392304f41f84ca7c My Polygon Adress

**Comment by Leaztat** [comment]
What is this about?

**Comment by adamhannigan** [comment]
@alicanharmanci A notification may of been sent if you are watching/subscribed to this issue. Sometimes Github will send you a notification (not us) when an issue is closed.

The winner was chosen 28 days ago as seen above :)
