### ISSUE TITLE
Farm Cat NFT

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#162]
Design a farm cat to replace the previous design in the game.

The total supply has already been minted for this NFT. The design which gets picked will get one of these cats airdropped in the new game 🚀 

**Voting closed: 7th Feb**

Vote on your favourite piece with a ❤️

**Comment by AyoubRhalam** [comment]
![image](https://user-images.githubusercontent.com/43474459/150685454-8a22fd99-d76a-45f3-90a9-f0b87974195b.png)

**Comment by AyoubRhalam** [comment]
![image](https://user-images.githubusercontent.com/43474459/150685486-920952fe-7723-4051-b62b-5ae457a5ee1d.png)

**Comment by soteleon** [comment]
Pedro, the lazy cat

![ca 2t](https://user-images.githubusercontent.com/94320699/150696046-e039bcb2-cd49-47c7-896b-4361924c9d71.png)
![cat](https://user-images.githubusercontent.com/94320699/150696047-dd105bbb-471f-4824-9737-80208a0b4e02.png)

**Comment by gabiqueiroga** [comment]
![VictoriaCat_tail1](https://user-images.githubusercontent.com/69090306/151287954-0aec2d3a-5bdb-4cdd-b000-403df3e4c49e.gif)

**Comment by gabiqueiroga** [comment]
![Sprite-0007](https://user-images.githubusercontent.com/69090306/151293155-d8f5a0a9-f47f-40f1-9fdf-5054971f16e4.gif)

**Comment by gabiqueiroga** [comment]
![victoria1](https://user-images.githubusercontent.com/69090306/152265856-1f4481dd-ac5f-4587-8e5f-37a33a48a47b.png)

![image](https://user-images.githubusercontent.com/69090306/152266541-abff852e-f7b2-4ddd-ba11-f4cd5b8d9b95.png)

**Comment by gabiqueiroga** [comment]
> ![victoria1](https://user-images.githubusercontent.com/69090306/152265856-1f4481dd-ac5f-4587-8e5f-37a33a48a47b.png)
> 
> ![image](https://user-images.githubusercontent.com/69090306/152266541-abff852e-f7b2-4ddd-ba11-f4cd5b8d9b95.png)


for size comparison

![image](https://user-images.githubusercontent.com/69090306/152267793-c40ce31c-5856-41eb-b54f-c643944a580c.png)

**Comment by Llynx014** [comment]
Not and expert but hope it helps you get idea .. 😅
![images](https://user-images.githubusercontent.com/99058887/152624908-e1aff6b4-d549-4dc0-85bd-f2f08af26e71.png)

**Comment by adamhannigan** [comment]
Congratulations @gabiqueiroga We have a winner! Your cat will be used in Sunflower Land and you will be airddropped one on Launch :) 

The results were extremely close. @ItsNight Will also receive an airdrop for their amazing submission ❤️
