### ISSUE TITLE
[BUG] Do not allow "," on trading keyboard mobile

### ISSUE THREAD

**Issue by arconycompany** [sunflower-land/sunflower-land#1622]
## Summary of Bug

When going to the trade place in the goblin village you cannot use the char "," in the sell details. (SFL price)

Making the selling price hard to set on cellphone.

## Steps to Reproduce
[On Mobile]
Go to the goblin village
Use "Trade" 
Try to list something
Trade details : 1 for 1,00

## Expected Behavior

Be able to use "," to set the price with decimal on mobile. 
or
Set the default price to "1,00" instead of "1" so it will be easier to modify

## Actual Behavior

"," char is disabled on mobile so you can't set decimal price.

## Screenshots

![Screenshot_20221104-172553_MetaMask](https://user-images.githubusercontent.com/70727157/200051280-61a53aa6-d8a3-4220-8150-939db35fa67b.jpg)

**Device Information (please complete the following information):**

- Device: [Samsung Galaxy S20 Ultra 5G]
- OS: [Android]
- Browser/App [Metamask mobile]
- Version [v5.6.1 (967)]

**Comment by Ant-Redstone** [comment]
Decimals are with "." which is allowed

**Comment by arconycompany** [comment]
When using "." this just set the price to 0 without adding any decimal value, i can try to put a video of the thing if that help, maybe this is linked to french keyboard tho.

**Comment by JacobSobolev** [comment]
@arconycompany can you check it again?
when I was working on another issue I was able to do that
![image](https://user-images.githubusercontent.com/9072434/202653556-2c3d7187-6b3c-4338-b916-2652a5bb02d7.png)

**Comment by future2back** [comment]
The issue hasn't been fixed yet.
