### ISSUE TITLE
Mushroom

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#164]
A mushroom will randomly appear at a location on the map. Users will need to search their map and forage these.

**Comment by paluras** [comment]
![Shrooms](https://user-images.githubusercontent.com/98059798/150689831-2312e908-d83a-49be-9ca8-09ab49f09895.png)
![Shrooms1](https://user-images.githubusercontent.com/98059798/150689848-2457bfc2-352c-4c86-ad13-450dcd5e6469.png)

**Comment by Aestnelis** [comment]
![lilmushrooms](https://user-images.githubusercontent.com/98103679/150690386-69c400ae-65a1-4b8c-b90b-3df2658f988f.png)
![bigmushrooms](https://user-images.githubusercontent.com/98103679/150690393-10d1c93b-296a-4ccc-a8b3-0b71afb31dc8.jpg)
![bigmushrooms](https://user-images.githubusercontent.com/98103679/150690404-d850e15b-8a45-474a-b01e-232c73e1ac0c.png)

**Comment by Raizak** [comment]
![image](https://user-images.githubusercontent.com/97144878/150699848-af02f76b-5aa3-4759-acc9-5ff3bd1604ed.png)

**Comment by soteleon** [comment]
![Mushroom color 1](https://user-images.githubusercontent.com/94320699/150811377-23bdcda2-fe81-45cb-9fd5-cd9df544651d.png)
![Mushroom color 2](https://user-images.githubusercontent.com/94320699/150811380-56e80ba3-5315-4836-8904-e033517067a2.png)
![Mushroom color 3](https://user-images.githubusercontent.com/94320699/150811382-f9f76f02-e1e5-4b52-8068-18091410e767.png)
![Mushroom color 4](https://user-images.githubusercontent.com/94320699/150811384-1096b45f-8ad0-420f-98ce-fe18b7e3c105.png)

![all mushrooms](https://user-images.githubusercontent.com/94320699/150811443-3333ac48-023b-44d8-9c22-3c660da19953.png)

The more colorful, more dangerous is it, 20px wide

**Comment by soteleon** [comment]
> ![Mushroom color 1](https://user-images.githubusercontent.com/94320699/150811377-23bdcda2-fe81-45cb-9fd5-cd9df544651d.png) ![Mushroom color 2](https://user-images.githubusercontent.com/94320699/150811380-56e80ba3-5315-4836-8904-e033517067a2.png) ![Mushroom color 3](https://user-images.githubusercontent.com/94320699/150811382-f9f76f02-e1e5-4b52-8068-18091410e767.png) ![Mushroom color 4](https://user-images.githubusercontent.com/94320699/150811384-1096b45f-8ad0-420f-98ce-fe18b7e3c105.png)
> 
> ![all mushrooms](https://user-images.githubusercontent.com/94320699/150811443-3333ac48-023b-44d8-9c22-3c660da19953.png)
> 
> The more colorful, more dangerous is it, 20px wide

![all mushrooms-export](https://user-images.githubusercontent.com/94320699/150821005-f5d132dc-4cf2-4335-84e7-668ae8101d78.gif)
Glittering can be a good idea too

**Comment by cambrios1** [comment]
![Mushroom](https://user-images.githubusercontent.com/98171636/151428014-2e61d682-062a-407d-921c-9f94a16e25d0.png)
amanita muscaria. this is the way.

**Comment by Sarapico** [comment]
Hi :)
![pixil-frame-0(5)](https://user-images.githubusercontent.com/98893182/152167689-63b310b1-729d-4e29-95f2-131eba9f43dd.png)
![pixil-frame-0(4)](https://user-images.githubusercontent.com/98893182/152167714-aec6e902-b6ee-49fd-8068-f11ceabc42de.png)
![pixil-frame-0(3)](https://user-images.githubusercontent.com/98893182/152167723-94cd3aca-2a8e-428a-88fe-25a2d8f18721.png)
![pixil-frame-0](https://user-images.githubusercontent.com/98893182/152167740-f5e89ef9-18cc-453c-bf52-4656c756b417.png)
![pixil-frame-0(1)](https://user-images.githubusercontent.com/98893182/152167784-9a8969bb-6cfa-48f9-877f-9a7369d0461c.png)
![pixil-frame-0(6)](https://user-images.githubusercontent.com/98893182/152167826-8881b3e7-373a-4259-adf6-b4855519c735.png)
![tela](https://user-images.githubusercontent.com/98893182/152167870-e0c88aca-b274-4ce3-8c39-ffb47a97d32c.png)

**Comment by Sarapico** [comment]
New version

![pixil-frame-0 (12)](https://user-images.githubusercontent.com/98893182/152409352-0f9e9a41-adf4-4f8e-8c84-3194c01e43a6.png)![pixil-frame-0 (14)](https://user-images.githubusercontent.com/98893182/152409397-4af73432-cc59-4c73-a7df-b714c6f77abf.png)![pixil-frame-0 (16)](https://user-images.githubusercontent.com/98893182/152409401-d0916917-0a81-4fbe-ab31-5f6b5b3c21f0.png)![pixil-frame-0 (18)](https://user-images.githubusercontent.com/98893182/152409406-156c0a93-ab9a-488b-a58a-2a92db2348a2.png)

![pixil-frame-0 (13)](https://user-images.githubusercontent.com/98893182/152409509-da7218ac-703b-4b8a-9634-c6918f9c3640.png)![pixil-frame-0 (15)](https://user-images.githubusercontent.com/98893182/152409536-4837633c-10ef-4872-93c1-c183472be7e3.png)![pixil-frame-0 (17)](https://user-images.githubusercontent.com/98893182/152409548-a418f24d-3ffc-4570-97e8-ee58ffa54814.png)![pixil-frame-0 (19)](https://user-images.githubusercontent.com/98893182/152409560-483ef884-9691-4e53-9403-de025ec753b9.png)
![pixil-frame-0 (20)](https://user-images.githubusercontent.com/98893182/152409605-e984cdbf-e7dc-4a7a-8083-fe5fadfdc4c5.png)

**Comment by Rouemn** [comment]
I wanted to help the project somehow, so I decided to make a mushroom,,, Maybe I'll try other things in the future :)
Different colors can also be done n.n
(If there is any problem with the format, please let me know)

![Cogumelo](https://user-images.githubusercontent.com/103075606/161859414-9420b1b2-4c28-43bc-9c3c-b1040519da1b.png)

![Cogumelo2](https://user-images.githubusercontent.com/103075606/161860205-b081280d-6b13-4a41-9c81-8dda20808b01.png)

![Preview](https://user-images.githubusercontent.com/103075606/161860506-0d6d9055-95ae-4dbf-8fce-da135081d072.PNG)

**Comment by Driftingwood** [comment]
Here is my art for a couple mushroom varieties. 
![Shroom bg](https://user-images.githubusercontent.com/25971765/164159797-915bfe3a-bb6d-4f37-99e7-002cf4a638d4.png)
![Shrooms](https://user-images.githubusercontent.com/25971765/164160053-3fc3cd65-4222-47ed-b6fb-d8fc2d458f36.png)

**Comment by AKCH1N** [comment]
### Classical Ones
### Red Mushroom
![red mushroom x500](https://user-images.githubusercontent.com/44812103/164853072-ad829a07-c236-4aa5-887c-a690ab9c1fc6.png)   ![red mushroom original](https://user-images.githubusercontent.com/44812103/164853154-64bf34ab-f8aa-4a2b-9eba-916e1fa352ec.png)
### Mushroom Head
![Mushroom Head x500](https://user-images.githubusercontent.com/44812103/164857119-e03840f3-dc93-4365-ae00-08a7481e5f6e.png)   ![Mushroom Head original](https://user-images.githubusercontent.com/44812103/164857126-91ed0a97-2fb5-490a-85dc-0ad143343145.png)

**Comment by cargomesplay** [comment]
![cogumelo2](https://user-images.githubusercontent.com/104114336/164873209-8263f4a4-a374-4daf-98bd-ede045587350.gif)
![cogumelo2-big](https://user-images.githubusercontent.com/104114336/164873211-b32f7765-743d-488f-9320-0e3b46536a2e.gif)

Farmer id: #29147
wallet in game farm: 0xb0E023545A38F10b6C787f37648695137aD94A91
wallet: 0xf06a69aCa1BB0182F1D1CB188E052A8FB1C71295

twitter
https://twitter.com/cargomesplay

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
