### ISSUE TITLE
Sunflower Army NFT

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#165]
Design an NFT that will represent the community. Players will be able to mint the NFT in game.

Steve Woody: I will give an additional **$100 bonus** to the winning designer of the SunFlower Army nft - that the core team picks to add into the game.

**Comment by Synedes** [comment]
oday I'm going to tell you a story, from the medieval Sunflower era where noble agricultural warriors fought for their place on the moon, fighting the FUD and participating in the construction of a rocket to make a golden sunflower grow on the moon.

It was they who witnessed the hype and the downfall but stood their ground and kept trusting that the end was not the end but only the beginning.

They weren't the avengers, but the sunflower community.

So they were, honored with golden statues, with a touch of unbreakable magic.

![trofeucommunitysfundo](https://user-images.githubusercontent.com/98273814/150686998-4562ede2-5707-4575-b2c1-229b05de315b.png)

**Comment by soteleon** [comment]
> oday I'm going to tell you a story, from the medieval Sunflower era where noble agricultural warriors fought for their place on the moon, fighting the FUD and participating in the construction of a rocket to make a golden sunflower grow on the moon.
> 
> It was they who witnessed the hype and the downfall but stood their ground and kept trusting that the end was not the end but only the beginning.
> 
> They weren't the avengers, but the sunflower community.
> 
> So they were, honored with golden statues, with a touch of unbreakable magic.
> 
> ![trofeucommunitysfundo](https://user-images.githubusercontent.com/98273814/150686998-4562ede2-5707-4575-b2c1-229b05de315b.png)

this one is a winners from all sides! lovely!

**Comment by Aestnelis** [comment]
Hey, here is my art for the contest, yeah i just tried...
But let me explain to you! They are not bots :) They may seem small but they have the huge community and support behind them! With this power they can do everything they want to do. But sometimes this unstoppable power is causing them to break big rocks. No no, don't worry this will make the sunflower pop out of the ground and shine better!

![bigsunflower](https://user-images.githubusercontent.com/98103679/151845241-b4051942-0b4e-4307-b7d7-a8547ba74cfc.png)
![bigsunflowa](https://user-images.githubusercontent.com/98103679/151845167-0a8ddb9e-0291-4b81-9d2d-b3ef86b3d489.png)

**Comment by adamhannigan** [comment]
@Aestnelis Looks amazing! One small suggestion is to use a different sunflower than the one used in the game - We can't use the base asset pack sprites in NFTs as it could be considered 'reselling' art in some countries.

**Comment by Aestnelis** [comment]
> @Aestnelis Looks amazing! One small suggestion is to use a different sunflower than the one used in the game - We can't use the base asset pack sprites in NFTs as it could be considered 'reselling' art in some countries.

Ohh thanks for that i really forgot about the sunflower!
![sunflowercontest](https://user-images.githubusercontent.com/98103679/152028832-71179ea7-3b8a-4e2b-9ee4-4401cb8a4c92.png)
![bigsunflowercontest](https://user-images.githubusercontent.com/98103679/152028860-4182a4bf-aa1c-4940-9106-74b4c79e46a2.png)
![Sunflowercontestbackgroundpng](https://user-images.githubusercontent.com/98103679/152029308-b0a9c7db-f992-4905-a867-06d4c4e35712.png)

**Comment by WUUYE** [comment]
![459404729e12b9190293964a2091acc](https://user-images.githubusercontent.com/99791101/154442240-b9a532bc-6763-49dc-91d5-033adbd57080.png)
![jsfhduiahdsufnbsdjfbhewurheiwur huerf](https://user-images.githubusercontent.com/99791101/154442291-61801c5b-af36-40ec-9680-d4a8bc25f0c5.png)
Although Sunflower is injured now and not strong enough, we will still protect you. never give up！

**Comment by adamhannigan** [comment]
Some great submissions ❤️ The sunflower rock by @Aestnelis is now in the game. Congratulations!

**Comment by Aestnelis** [comment]
> Some great submissions ❤️ The sunflower rock by @Aestnelis is now in the game. Congratulations!

Thank you!
