### ISSUE TITLE
Caulfilower Recipe

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#166]
To upgrade your farm, players will need to collect Cauliflowers and craft a recipe containing Cauliflowers.

This will be given to the Goblins to move off the land.

**Includes**

- Design a piece of food that has Cauliflower in it.

**Comment by soteleon** [comment]
This is a dish we often eat where we alive, more in summer though, The cauliflower is deep fried with flour, eggs, spices and it´s accompanied with some salad, of course, for a recipe for the game, it can be a simpler one like, Only cauliflowers and flour from wheat
![recipe](https://user-images.githubusercontent.com/94320699/150688792-4ff26066-dcc4-4d33-99a3-d788ef6e8048.png)


![fried cauliflower 2 mas grande](https://user-images.githubusercontent.com/94320699/150687201-f3a89d22-e89e-4aa5-88e1-10919af80ae2.gif)
![fried cauliflower](https://user-images.githubusercontent.com/94320699/150687203-28671273-510c-4d53-a601-9f60e6ab0186.png)

**Comment by soteleon** [comment]
> This is a dish we often eat where we live, more in summer though, The cauliflower is deep fried with flour, eggs, spices and it´s accompanied with some salad, of course, for a recipe for the game, it can be a simpler one like, Only cauliflowers and flour from wheat ![recipe](https://user-images.githubusercontent.com/94320699/150688792-4ff26066-dcc4-4d33-99a3-d788ef6e8048.png)
> 
> ![fried cauliflower 2 mas grande](https://user-images.githubusercontent.com/94320699/150687201-f3a89d22-e89e-4aa5-88e1-10919af80ae2.gif) ![fried cauliflower](https://user-images.githubusercontent.com/94320699/150687203-28671273-510c-4d53-a601-9f60e6ab0186.png)

Or maybe like this, so they look a little like they were fried with the leaves 

![recipe2](https://user-images.githubusercontent.com/94320699/150689181-def98dda-504d-4a9b-9dd6-f19692e3066c.png)

**Comment by adamhannigan** [comment]
<img width="303" alt="Screen Shot 2022-01-24 at 10 58 05 am" src="https://user-images.githubusercontent.com/11745561/150796084-25c9e589-e6f0-4241-a765-c2a2ea73e602.png">

The Goblin is jumping with joy! @soteleon Nice work :)

**Comment by soteleon** [comment]
> <img alt="Screen Shot 2022-01-24 at 10 58 05 am" width="303" src="https://user-images.githubusercontent.com/11745561/150796084-25c9e589-e6f0-4241-a765-c2a2ea73e602.png">
> 
> The Goblin is jumping with joy! @soteleon Nice work :)

Awesome! be careful though, Too much and that will be a fatty goblin
