### ISSUE TITLE
Cabbage Recipe

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#167]
To upgrade your farm, players will need to collect Cabbage and craft a recipe containing Cabbage.

This will be given to the Goblins to move off the land.

**Includes**

- Design a piece of food that has Cabbage in it.

**Comment by paluras** [comment]
![Cabage](https://user-images.githubusercontent.com/98059798/150692390-ca032a75-d8dc-4092-ad9a-c13c59ef256c.png)
![Cabbage](https://user-images.githubusercontent.com/98059798/150692395-d3c75727-24fc-4fbb-90fb-2957763a4c1d.png)

Cabbage stew and a vegan cabbage burrito

**Comment by soteleon** [comment]
Cabagge Chicken soup - Maybe it´s not a must to add chicken to the recipe as they produce eggs at the farm, but maybe it can be:

-Cabagge x3
-Carrots x2

And maybe another stuff? we do have here some cabagge stew too, maybe I can try to make it in a different way

20px wide

![Sprite-0001](https://user-images.githubusercontent.com/94320699/150825657-81cd70f3-af02-4b73-9b7a-69efd0c2860e.png)

**Comment by paluras** [comment]
![PickeldCabbage](https://user-images.githubusercontent.com/98059798/150946971-dbecc05c-0ced-48d2-a1e7-5da40d01d00c.png)
![PickeldCabbage_small](https://user-images.githubusercontent.com/98059798/150946976-59d75a6c-53b4-409d-a75a-50b022bbb147.png)

Homemade sauerkraut

**Comment by soteleon** [comment]
![fish   pumpink cabagge](https://user-images.githubusercontent.com/94320699/150976197-ea48d095-aa5e-4fea-b678-d9f600840bf8.png)
![fried cabagge big](https://user-images.githubusercontent.com/94320699/150976202-96381385-1a1d-4d35-92c6-931ff603af61.png)
![fried cabagge](https://user-images.githubusercontent.com/94320699/150976205-8986897f-34c6-4731-83c8-1ee20799936e.png)  Fried Fish with cabbage and mashed pumpkin
![pumpkin_05-export](https://user-images.githubusercontent.com/94320699/150976206-ba41a15a-f951-495a-8109-b8ed0138b1af.png)
![Sprite-0001](https://user-images.githubusercontent.com/94320699/150976208-a3c8020c-6580-4ac6-8a62-21bcc2e54457.png) Pumpkin cabagge filled

**Comment by adamhannigan** [comment]
These are all amazing!

@paluras This one is looking like the my favourite ❤️

**Comment by adamhannigan** [comment]
@paluras 

Looks good! - <img width="544" alt="Screen Shot 2022-01-25 at 6 12 00 pm" src="https://user-images.githubusercontent.com/11745561/151060486-7481f833-8d41-4974-b03d-be7ab7554b33.png">
