### ISSUE TITLE
White Screen when clicking on crops with seeds. 

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#1690]
Attached is a video of the white screen I'm experiencing when trying to gather my crops. Please note I'm also unable to expand my land, game keeps crashing then also.

https://user-images.githubusercontent.com/96928557/202526237-dc4e522c-8a5b-46fc-bd37-d92d5d354a3a.mp4

**Device Information

- Device: Samsung S22 Ultra

**Comment by JacobSobolev** [comment]
@Myth727 does it happen on all crops?

**Comment by Myth727** [comment]
> @Myth727 does it happen on all crops? does it happen on the desktop as well? if so try recreate the issue and send the console log

Yes it happens on laptop also. I'll do that later tomorrow if not busy, thanks for the advice.

**Comment by Myth727** [comment]
Attaching Log!

vendor.f0b10cbe.js:37 TypeError: Cannot read properties of undefined (reading 'map')
    at CropReward (index.e2d508f9.js:18:89902)
    at m4 (vendor.f0b10cbe.js:35:53022)
    at x4 (vendor.f0b10cbe.js:35:62519)
    at w_ (vendor.f0b10cbe.js:39:9681)
    at m_ (vendor.f0b10cbe.js:39:950)
    at OU (vendor.f0b10cbe.js:39:878)
    at E1 (vendor.f0b10cbe.js:39:731)
    at z4 (vendor.f0b10cbe.js:37:10893)
    at vendor.f0b10cbe.js:35:38815
    at e.unstable_runWithPriority (vendor.f0b10cbe.js:24:3784)
M4 @ vendor.f0b10cbe.js:37
r.callback @ vendor.f0b10cbe.js:37
bw @ vendor.f0b10cbe.js:35
AU @ vendor.f0b10cbe.js:37
RU @ vendor.f0b10cbe.js:39
e.unstable_runWithPriority @ vendor.f0b10cbe.js:24
xu @ vendor.f0b10cbe.js:35
Mu @ vendor.f0b10cbe.js:39
z4 @ vendor.f0b10cbe.js:37
(anonymous) @ vendor.f0b10cbe.js:35
e.unstable_runWithPriority @ vendor.f0b10cbe.js:24
xu @ vendor.f0b10cbe.js:35
vw @ vendor.f0b10cbe.js:35
Jo @ vendor.f0b10cbe.js:35
n7 @ vendor.f0b10cbe.js:39
kj @ vendor.f0b10cbe.js:35
vendor.f0b10cbe.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at CropReward (index.e2d508f9.js:18:89902)
    at m4 (vendor.f0b10cbe.js:35:53022)
    at x4 (vendor.f0b10cbe.js:35:62519)
    at w_ (vendor.f0b10cbe.js:39:9681)
    at m_ (vendor.f0b10cbe.js:39:950)
    at OU (vendor.f0b10cbe.js:39:878)
    at E1 (vendor.f0b10cbe.js:39:731)
    at z4 (vendor.f0b10cbe.js:37:10893)
    at vendor.f0b10cbe.js:35:38815
    at e.unstable_runWithPriority (vendor.f0b10cbe.js:24:3784)

**Comment by Myth727** [comment]
> @Myth727 does it happen on all crops? does it happen on the desktop as well? if so try recreate the issue and send the console log

As for all crops I've only noticed this problem for sunflowers atm. Have not had the same issue with other crops. But now I have about 6 spots that are unused on my end until this issue is fixed.

**Comment by Reda2017** [comment]
happened to me on testnet a week ago. it's the Golden flowers skill. the skill is not implemented yet. but it does block the plots.

**Comment by Myth727** [comment]
> happened to me on testnet a week ago. it's the Golden flowers skill. the skill is not implemented yet. but it does block the plots.

You make we worry about clicking on that skill for the trees. I wanna, bit don't wanna be unable to cut trees for days. Lol
