### ISSUE TITLE
[BUG] NAN MATIC when doing on any on chain functionality (On mobile)

### ISSUE THREAD

**Issue by JacobSobolev** [sunflower-land/sunflower-land#1696]
## Summary of Bug

On mobile only I get NAN MATIC on everything I try to do on the chain.

## Steps to Reproduce

syncing, buying, or selling on the trader
probably wishing well and withdrawing from the bank but didn't test it.

## Expected Behavior

The MATIC should be set for the transaction based on the current load of the network, as it usually does.

## Actual Behavior

It seems to be on mobile only, as on the desktop I didn't get this issue.
when I try to sync or use the trader to buy and sell I get NAN MATIC in the meta mask transaction.
for the trader, I can edit it manually and it goes through but for syncing, it just asks for 300 Matic or something like that.
The major issue is with the sync.

tried clearing the cache but it didn't help.

## Screenshots

| Trader when buying  | Syncing | Syncing after adjusting the gas to market option |
| ------------- | ------------- | ------------- |
| ![Screenshot_2022-11-18-09-46-48-109_io metamask](https://user-images.githubusercontent.com/9072434/202652191-0c144cff-91c4-4d9b-ba4e-bbec9f5277f8.jpg) | ![Screenshot_2022-11-18-09-47-50-190_io metamask](https://user-images.githubusercontent.com/9072434/202652330-ba52070c-26e9-4978-a78c-866696a52338.jpg)  | ![Screenshot_2022-11-18-10-00-46-916_io metamask](https://user-images.githubusercontent.com/9072434/202652454-f7056c6a-340c-4535-b2d9-57645e01ca06.jpg)

**Device Information (please complete the following information):**

- Device: POCO F2 PRO
- OS: Android
- Browser/App Metamask on android
- Version v 5.10.0 (1004)

**Comment by AzaroQL** [comment]
It was MM bug, was fixed by them a while ago so prob this issue can be closed.
