### ISSUE TITLE
Bakery Sprite

### ISSUE THREAD

**Issue by RoboTiberius** [sunflower-land/sunflower-land#170]
I need a sprite for a bakery in game instead of using the blacksmith for food

**Comment by adamhannigan** [comment]
@RoboTiberius I have added the `art request` label. This makes it easy for Artists to search Github and find issues to contribute

**Comment by Aestnelis** [comment]
Here it is!
![Bakery](https://user-images.githubusercontent.com/98103679/150801276-78a39c08-81e0-45c8-a1c8-87c98f08c6f2.png)
![bigBakery](https://user-images.githubusercontent.com/98103679/150801296-04107a17-9567-4cda-91c7-d586d4183001.png)

**Comment by Aestnelis** [comment]
![Chef](https://user-images.githubusercontent.com/98103679/150818169-52ba1e67-e8a1-4107-a674-482bd0b940bf.png)
![bigchef](https://user-images.githubusercontent.com/98103679/150818189-75e5b326-a2ad-4968-afcd-972c061a15a8.png)

**Comment by RoboTiberius** [comment]
> If you want anything just let me know!

Can you make a png with them all together, it's easier to implement that way

**Comment by Aestnelis** [comment]
![pngg](https://user-images.githubusercontent.com/98103679/150852854-4ffdf1fb-42c1-43e5-b23f-54ef9b34c10a.png)
![pnggg](https://user-images.githubusercontent.com/98103679/150852873-86caf488-9958-4d1e-ad56-f006c00c83b9.png)

**Comment by Aestnelis** [comment]
> > If you want anything just let me know!
> 
> Can you make a png with them all together, it's easier to implement that way

![pngg](https://user-images.githubusercontent.com/98103679/150852942-ec2b38f5-b17f-4862-b40c-3bafeb443ab1.png)
![pnggg](https://user-images.githubusercontent.com/98103679/150852966-7b0407da-c626-424a-aa8e-1fe9754bfbba.png)

**Comment by Synedes** [comment]
My outdoor kitchen made of stone and wooden base, with gaston and remy mouse (ratatouille
![cozinha sunflower](https://user-images.githubusercontent.com/98273814/151642794-7fb2afc3-e5d2-4ddc-bf69-9071a013e2bd.png)
![cozinhahighighquality](https://user-images.githubusercontent.com/98273814/151642800-b7ca1263-2c0b-47d9-af7f-d7c1d2bde50b.png)
These assets \/ are the correct size for the game
![cozinhasunflorew](https://user-images.githubusercontent.com/98273814/151642804-1f577c44-f481-4f86-bd0c-cc93f43af551.png)
)
