### ISSUE TITLE
Missing Observatory and War Hammer Nft in Expansion.

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#1701]
When placing items or reviewing my chest/inventory I noticed my observatory and war hammer nft don't show up anymore. Wanted to make sure we fix this as users will view that as missing nfts. 

Keep up the awesome work everyone 👏 ❤️

**Comment by mGranTY** [comment]
Bumpkins wearables will not appear in the in-game inventory, but you can see it if you go to your bank and try to withdraw an item.

For the observatory, we can do a fix for it, just wait :)

**Comment by Myth727** [comment]
> Bumpkins wearables will not appear in the in-game inventory, but you can see it if you go to your bank and try to withdraw an item.
> 
> For the observatory, we can do a fix for it, just wait :)

Appreciate the response. Can't see anything under my withdrawal as jigger is giving me a hard time 3rd time now.

**Comment by Myth727** [comment]
> Bumpkins wearables will not appear in the in-game inventory, but you can see it if you go to your bank and try to withdraw an item.
> 
> For the observatory, we can do a fix for it, just wait :)

Don't forget the observatory has a boost!

**Comment by future2back** [comment]
Hello guys, sorry for invading the topic. Is the quest of War Hammer still available right? Will War Hammer be a Bumpkin wearable? Is it still worth trying to do this quest? Thank you!

**Comment by Myth727** [comment]
@spencerdezartsmith this is still not solved.  Can't do anything with the observatory yet.
