### ISSUE TITLE
Unable to withdraw any items in expansion.

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#1702]
Unable to withdraw any items in expansion.

Using my phone and laptop I'm unable to withdraw any items from the goblin market. Will try to grab console log later when at home on the computer. Recorded issue,  but github will not allow me to upload the 25 second video as I have done many times in the past.

**Comment by Myth727** [comment]
Now Jigger wants to verify me for about a 3rd time haha. Went to its screen and says I'm already verified... another issue to solve later. hoping to get console logs in a moment....nope jigger issue again. adding images in a moment.

**Comment by Myth727** [comment]
![20221118_135011](https://user-images.githubusercontent.com/96928557/202780916-175d0ec0-159f-4a54-8df5-62279a1bf8b2.jpg)


![20221118_135048](https://user-images.githubusercontent.com/96928557/202780964-dcd3800a-31b8-4398-be6c-b128572e43d9.jpg)


![Screenshot_20221118-135113_Chrome](https://user-images.githubusercontent.com/96928557/202781009-435b4076-f1df-473b-a930-f25c87aad6ba.jpg)

**Comment by Myth727** [comment]
No issues with jigger until I opened the console log as loading the game to grab logs of bugs I'm running into.

**Comment by Myth727** [comment]
This seems to be fixed. I'm noting down a few other bugs I'll open soon. But for now yall are making amazing progress!

**Comment by Myth727** [comment]
Thought this was fixed but noticing many issues with it still. Will try to attach video later showing problems.

**Comment by Myth727** [comment]
Having hard time upload video, will start with these images for example purposes.  Can't withdraw my farm dog even tho I removed him and made sure to sync also.

![Screenshot_20221126-142630_MetaMask](https://user-images.githubusercontent.com/96928557/204105910-bcf02133-a952-4c24-98a4-4eafa79aab08.jpg)

![Screenshot_20221126-142648_MetaMask](https://user-images.githubusercontent.com/96928557/204105915-d09a0471-c65a-4319-abe7-62331e2d57f0.jpg)

**Comment by JacobSobolev** [comment]
I have addressed the issue of the seeds in #1768 PR

**Comment by Myth727** [comment]
> I have addressed the issue of the seeds in #1768 PR

Don't see where it was addressed in that code. But ill wait for the update and see if the problem is gone. Then ill close it out if I'm no longer having the issue
