### ISSUE TITLE
[BUG] Favicon Counter on First Load

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#171]
hi @avalla tagging you here as it's your feature and idk your discord. We saw an issue where harvestable crops upon loading the game are not counted. It works when you plant and wait for the timer but not for already harvestable crops.

![image](https://user-images.githubusercontent.com/89294757/150707553-ad807893-28f6-4bc3-9ac8-8c88a6bde0ef.png)

**Comment by avalla** [comment]
@j923sneaks can you tell me how can I simulate that scenario? thanks!!

**Comment by j923sneaks** [comment]
@avalla 

Data is loaded in `constants.ts` as `INITIAL_FARM`. it has `plantedAt: 0` right now but idk if it will be the same when integrated with the backend.

Scenario:
1. run the game <-- counter at 1
2. harvest some crops <-- counter at negative
3. plant and wait <-- counter increments after timer hits 0

btw i added some fixes in #158 but quite certain it doesn't affect the increments.

**Comment by avalla** [comment]
@j923sneaks Interesting, when loading from INITIAL_FARM harvestable counter inside AppIconContext state doesn't works :\
The only solution that I found is to count harvestable items using game state. 

Could you take a look at PR #190 ?
