### ISSUE TITLE
[BUG] Border image not working on Safai

### ISSUE THREAD

**Issue by spencerdezartsmith** [sunflower-land/sunflower-land#173]
The border image which is used on the Panels is not working on Safari.

![Screen Shot 2022-01-24 at 3 12 11 pm](https://user-images.githubusercontent.com/17863697/150721052-d73e190d-70ff-4339-b4ac-5bbe536d649b.png)
![Screen Shot 2022-01-24 at 3 12 22 pm](https://user-images.githubusercontent.com/17863697/150721053-ba5e6744-9607-4327-a0f9-8d34c2b9d8d7.png)

**Comment by Pranav-yadav** [comment]
@spencerdezartsmith  I've found a fix for it.. Will take some time to test it properly.
After successful testing I'll submit the PR :)

**Comment by Pranav-yadav** [comment]
Progress: I'm done with the coding but, as Safari testing needs to be done on real ios device (dev tolls aren't enough) so, in this I'm going to use Browserstack..

**Comment by Pranav-yadav** [comment]
### 🎉 Checkout PR (#212) for fix.

**Comment by adamhannigan** [comment]
@Pranav-yadav Good catch, I forgot to link the issue 😓
