### ISSUE TITLE
Tree chop / wood animation

### ISSUE THREAD

**Issue by spencerdezartsmith** [sunflower-land/sunflower-land#174]
As part of the wood chopping action we would love to have this tree animation (gif). The wood chopping character and chopping action is already available to us but the tree shake and the subsequent wood popping out is not.

All of the sprites are available as part of the asset pack. 

https://user-images.githubusercontent.com/17863697/150756836-ccb1a043-bb15-4be9-ada3-a16aa602b56b.mov

**Comment by AyoubRhalam** [comment]
Ok i'm working on it

**Comment by AyoubRhalam** [comment]
it may take me some time because i need to clear everything around it 69 time 
![image](https://user-images.githubusercontent.com/43474459/150796413-ed14ce3b-be11-475d-bc34-45b4b1125295.png)

**Comment by ItsNight** [comment]
@spencerdezartsmith @adamhannigan like this ?

-
![New Piskel](https://user-images.githubusercontent.com/43474459/150801504-c4007cbb-19df-4d67-99b6-74e0fd671522.gif)

**Comment by ItsNight** [comment]
![Wood Animation](https://user-images.githubusercontent.com/43474459/150801710-c39eee51-bbb5-4f66-acf5-72811359d662.gif)
Like this ? @spencerdezartsmith @adamhannigan

**Comment by ItsNight** [comment]
![ddddddddddddddddddddd](https://user-images.githubusercontent.com/43474459/150809803-b168cfdc-14ba-4ad1-82ca-62d6fa11787b.gif)
@spencerdezartsmith

**Comment by ItsNight** [comment]
![cwx](https://user-images.githubusercontent.com/43474459/150811154-74f6bb8c-cdab-4567-8ece-3042b59502ef.gif)

**Comment by ItsNight** [comment]
here you go i tried my best to remove the axe and everything @spencerdezartsmith @adamhannigan

**Comment by Synedes** [comment]
> ![Wood Animation](https://user-images.githubusercontent.com/43474459/150801710-c39eee51-bbb5-4f66-acf5-72811359d662.gif) Like this ? @spencerdezartsmith @adamhannigan

amazing

**Comment by spencerdezartsmith** [comment]
This is EXCELLENT!!!!!!!!! @ItsNight Thank you so much. You killed this brief! 🚀

**Comment by Rofrtd** [comment]
Ohh wow! @Synedes this is awesome work! 🌻

**Comment by defido** [comment]
> ![Wood Animation](https://user-images.githubusercontent.com/43474459/150801710-c39eee51-bbb5-4f66-acf5-72811359d662.gif) Like this ? @spencerdezartsmith @adamhannigan

What on earth, this is incredible!

**Comment by spencerdezartsmith** [comment]
I am closing this issue because you smashed this out of the park!!!!! Thanks I really appreciate it!
