### ISSUE TITLE
Not able to remove Apon after equipped.

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#1746]
Noticed when testing stuff on LE and putting on Apon to see cake sale prices. Unable to remove Apon now and also noticed anyone having just 1 necklace will run into the same problem.
![Screenshot_20221123-113612_MetaMask](https://user-images.githubusercontent.com/96928557/203606465-95213e02-7b67-4661-8d15-ebef59f24e87.jpg)

**Comment by mGranTY** [comment]
Already fixed :)

**Comment by Myth727** [comment]
> Already fixed :)

Amazing, closing this out. Stay awesome!
