### ISSUE TITLE
[FEAT] Pixel-art avatar builder (NFT)

### ISSUE THREAD

**Issue by 3s2ng** [sunflower-land/sunflower-land#175]
### What
To create a character/avatar builder (pixel-art style).

Users will be able to customize the different attributes such as gender, hair, hair color, eyes, eyeglasses, eyebrows, mouth, beard, hat etc.

Users will be using SFL & GOLD to be able to customize their avatar. 

### Next phase
Sunflower Land Passport.
- passport design
- lists of achievements

_* just throwing some random animal crossing passport here._ 
![fmgzwk2vnkk41](https://user-images.githubusercontent.com/200129/150788067-921c44f5-b23a-4876-8f2c-45e5e2a4a516.png)

**Comment by adamhannigan** [comment]
@3s2ng That is a really awesome idea. Letting the players create their own farm NFT.

I wonder if we could make it truly unique - I.e. You can not set the same combination as someone else

**Comment by adamhannigan** [comment]
Great initiative. I am closing this now due to inactivity.

The artists are currently talking about a system around unique art and Farm NFts
