### ISSUE TITLE
[FEAT] Withdraw Modal UI

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#178]
If you click on Menu -> Withdraw you can send your Farm tokens and assets to a wallet address.

Currently the UI is very messy and lacks some functionality. This request is to improve the UI

**Acceptance Criteria**

- [ ] As a player, I should not be able to withdraw if I have an unsaved session in progress
- [ ] As a player, I should be able to specify how many tokens I can withdraw
- [ ] As a player, I should be able to select which inventory items I want to withdraw
- [ ] As a player, I should be able to specify how much of each inventory item to withdraw
- [ ] Consistent looking pixel art UI
- [ ] Disclaimer that links to https://docs.sunflower-land.com/

**Excludes**

- Smart contract interaction

_Example of Current UI_

<img width="541" alt="Screen Shot 2022-01-24 at 11 27 13 am" src="https://user-images.githubusercontent.com/11745561/150801859-980e369c-51c7-4348-a933-b46cfedf7455.png">

**Comment by ItsNight** [comment]
As a player, I should be able to select which inventory items I want to withdraw

**Comment by j923sneaks** [comment]
> As a player, I should not be able to withdraw if I have an unsaved session in progress

How can we determine unsaved session w/ the current state of the frontend?

> As a player, I should be able to specify how many tokens I can withdraw
> As a player, I should be able to specify how much of each inventory item to withdraw

IMO this is the most difficult part to implement. Is specifying token/item quantity really necessary? Will the backend not recognize withdrawn assets in its balances?

**Comment by j923sneaks** [comment]
@adamhannigan I think we can close this due to PR #228 😄
