### ISSUE TITLE
[BUG] Shovel sold out

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1784]
![image](https://user-images.githubusercontent.com/74167741/204445236-021bd5b3-08a0-4c24-8af2-515d487c335a.png)

Hello guys, why is this shovel sold out? Thank you.

**Comment by Myth727** [comment]
There's only one of those shovels. Maybe they can reword it, but if you made one then you always have it in stock in your inventory.  It should say "Only 1 Per Customer" ....example purposes. 

@adamhannigan 
@spencerdezartsmith 
@Polysemouse

**Comment by future2back** [comment]
> There's only one of those shovels. Maybe they can reword it, but if you made one then you always have it in stock in your inventory. It should say "Only 1 Per Customer" ....example purposes.
> 
> @adamhannigan @spencerdezartsmith @Polysemouse

Thanks for replying my friend. Despite having the resources now, I never did any. It were available but now they are not. Not sure if its a bug or dev team changed it.

Thank you.
