### ISSUE TITLE
[FEAT] UI Feedback when crafting/buying

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#179]
Currently, when you craft, buy or sell an item you get very little feedback.

Once you click the button, your balance/inventory changes but it is not obvious for the user. This could cause a user to accidentally click the 'Craft' or 'Buy' button again

**Acceptance Criteria**

- When an item is crafted, a player should receive some feedback about what ingredients were deducted.
- When a seed is bought, a player should receive some feedback about what ingredients were deducted.
- When an item is sold, a player should receive some feedback about the tokens they earned.
- Mobile support
- Consistent pixel art UI/Theming

**Toast**

A common approach to give feedback to a user is the Toast widget. Consider using the `Toast` from the react bootstrap package we are using.

This means it will work well on Mobile and Desktop.

https://react-bootstrap.github.io/components/toasts/. - Apply pixel art styling (Panels, images, text etc)

<img width="209" alt="Screen Shot 2022-01-24 at 12 28 51 pm" src="https://user-images.githubusercontent.com/11745561/150812482-f2868352-6f5c-4e90-b054-b7048c001abb.png">
<img width="213" alt="Screen Shot 2022-01-24 at 12 29 02 pm" src="https://user-images.githubusercontent.com/11745561/150812520-e0a5eacc-1db0-4e0b-a1ea-e66cfa9faee6.png">

**Comment by j923sneaks** [comment]
@adamhannigan is it possible use `displayPopover` to do it like this?

Example of crafting 10 pickaxes
![image](https://user-images.githubusercontent.com/89294757/151155609-94ea586e-cc16-43cf-9c74-38afc42b306c.png)

"- 20 SFW (or wood icon)"
"- 10 SFL (or SFL icon)"

Either way I think that will really help!

**Comment by adamhannigan** [comment]
@j923sneaks That would be great as well!

**Comment by silici0** [comment]
I think PR #192 solved this open issue :)

**Comment by Rofrtd** [comment]
> I think PR #192 solved this open issue :)

Thanks, will close it.
