### ISSUE TITLE
[BUG] I can't sync and save, my farm is in trouble.

### ISSUE THREAD

**Issue by Fxloydd** [sunflower-land/sunflower-land#1800]
## Summary of Bug

Can anyone help about my farm? I can't synchronize. I changed rpc. I switched to another browser. I even put it in a different wallet to try, but I can neither save nor synchronize. I can't plant for 2 days, I opened a ticket but still waiting

Wallet address: 0xfDa10035adE4E710F870d6bC5a9D64471216bB13
Farm ID: 24076
Discord ID: 915174076128067595

![Screenshot_18](https://user-images.githubusercontent.com/119627963/205149332-03d13798-510b-4668-a30e-c06beca70b7a.png)

**Device Information

- Device: Pc
- OS: Windows 11
- Browser/App : Brave, Chrome
- Version: 0.6.34

Bug Video:
 [New Recording - 01.12.2022 23:10:42](https://vimeo.com/777119817/d9470de152)

**Comment by Myth727** [comment]
Are you able to grab the console logs on a computer and submit that here for the team? It might help them spot where the bug/error is happening.

**Comment by Myth727** [comment]
The general method for capturing a browser console log in most web browsers:
Navigate to the web browser tab where you will reproduce the issue.
From the web browser's tools menu, open the developer tools menu item. Sometimes just right click to see console logs.

**Comment by Fxloydd** [comment]
![image](https://user-images.githubusercontent.com/119627963/205217932-e8f6c6fc-6d39-4801-bfbb-2518d888f99b.png)

![image](https://user-images.githubusercontent.com/119627963/205217954-73b26ec4-afa3-4502-a5c9-e5c81e955207.png)

**Comment by Myth727** [comment]
Thanks, this might help the team when checking this out. Hopefully you see a fix soon mate

**Comment by Myth727** [comment]
@Fxloydd still an issue on your end after the recent updates?

**Comment by gajelou** [comment]
Hello.
Is it still a problem?

**Comment by Myth727** [comment]
> Hello. Is it still a problem?

Now I'm having this issue since the last update. Woke up on the middle of the night to do some farming and could not sync as needed. Same is still going on at the moment for me.

**Comment by Myth727** [comment]
Turns out on my end the bug was because of the new foods. Someone on Twitter suggested that if I eat the foods and then try to sync it should work. And it did!

**Comment by future2back** [comment]
Hello friend @Fxloydd , can you tell us if this issue has been resolved?
Thank you.
