### ISSUE TITLE
Shark Fin Animation

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#183]
NIGHT (Discord) has done a cool shark fin animation.

It would be great to have this appear in the lake once every minute or so as an Easter Egg ;) 

![dscw](https://user-images.githubusercontent.com/11745561/150979466-a1ca3fd0-625a-4d6c-a613-bb5d0350039a.gif)

**Includes**

- An animation that shows the shark fin once every minute in the lake

**Comment by rickfurt** [comment]
on it

**Comment by ItsNight** [comment]
![qcwc](https://user-images.githubusercontent.com/43474459/150991184-b9aa2168-82b9-4cf2-9f70-405b2af14879.gif)
![ddddddddddcw](https://user-images.githubusercontent.com/43474459/150991206-4ab845cd-7581-47ee-8b13-e4f06dac56b1.gif)
Color Fixed
New Shark direction

**Comment by ItsNight** [comment]
![SHARK2](https://user-images.githubusercontent.com/43474459/151005981-57044ca1-cfdd-46c9-a5ca-a5ee79a60d2d.gif)
![SHARK1](https://user-images.githubusercontent.com/43474459/151005989-60fbcda2-bde5-445e-a286-4f4c8ffbb360.gif)

**Comment by ItsNight** [comment]
![SHARK2](https://user-images.githubusercontent.com/43474459/151006690-4ddd8ca1-0670-4e79-a122-616d7fd2bda8.gif)
![SHARK1](https://user-images.githubusercontent.com/43474459/151006709-c7011a3b-da38-4d84-aa87-4849017ebddf.gif)

**Comment by ItsNight** [comment]
![SHARK1](https://user-images.githubusercontent.com/43474459/151007155-23432994-a66c-4717-9815-b1646e748d18.gif)
![SHARK2](https://user-images.githubusercontent.com/43474459/151007162-a4bf79ef-0482-4eef-a6cf-8f7031a6ba54.gif)

**Comment by soteleon** [comment]
![shark fin SMALL](https://user-images.githubusercontent.com/94320699/151007112-14943831-c286-4f55-95f2-13c30357066e.gif) 
small predator

![SHARK FIN PRUEBA](https://user-images.githubusercontent.com/94320699/151007587-8cf52703-3c39-4455-af5b-e7408e6f20f8.gif)
