### ISSUE TITLE
[Feature Request] Announcements

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#184]
## Description 

Hello! This is a request for announcements made by the team to be visible in game. We had this previously with halving banner but that involves changing the frontend and redeploying. What I'm thinking of is a streamlined UX for checking said announcements.

### UI
For the UI, the simplest can be an additional menu item with a badge/icon indicating unread items. However, I would appreciate if we have some sprite to click on the field (similar to bald man). It could be a bulletin board or a mailbox with necessary animations.

Modal appears showing most recent announcements. Each are collapsible to reveal all contents (this might bloat the modal though). 

I do not know if implementing read/unread states need to have backend integration. Maybe we can save a property e.g. `messageId=true` via `localStorage`?

### Backend
I do not know much on the backend, but this should supply the game with announcements. This could be set by the team manually or have some sort of automation. For example, if possible, important announcements posted on social media will be forwarded to the game as well. Plus some logic which sends only important ones and/or limit the amount to avoid bloat.

## 

Given the features the team is currently working on, I don't expect it to be delivered early on, especially without us devs having access to the backend. In the future, I hope 😃

**Comment by adamhannigan** [comment]
@j923sneaks This is a great idea!

I like the idea of bringing it into the game - e.g. clicking on the Bald man.

The local storage approach would work well - for the MVP, we could just include these announcements in the front-end source code. When we need to make an announcement, we just commit the changes.

In the future we can make this more dynamic and more of a CMS backend approach where the marketing team can edit it

**Comment by j923sneaks** [comment]
2022-01-31 [Art Request]

Hello artists! I would like to request some assets to be used in this feature 🙇 This is what it looks like currently

![sfl-mail-art-requests](https://user-images.githubusercontent.com/89294757/151726708-47021a7f-4b98-4b0d-a22c-fc048395bf6a.PNG)

1. Mailbox/es. One for read messages and one for unread. If possible, width is similar to the button at the right. Also consider an exclamation point `!` for unread just like in quests
![mailbox-read](https://mobileimages.lowes.com/productimages/c05037c2-5f8d-47c1-9546-0d1f4fbbed46/05493717.jpg?size=pdhi)
![mailbox-unread](https://media.istockphoto.com/photos/open-mailbox-with-letters-on-rural-backgound-picture-id1285800846?b=1&k=20&m=1285800846&s=170667a&w=0&h=XTNubX7I91KkXbAc4KCVa89AzEOhlbaCgt-MIIOzGhs=)

2. Unread notification. Some sort of red icon/badge which is displayed beside message title
3. Pixelated chevron facing downwards. Something similar to `assets/icons/close.png`

**Comment by j923sneaks** [comment]
hi @adamhannigan can i get the `bald_man` png? im going with that for the time being :)
