### ISSUE TITLE
[PROPOSAL] Planting and Harvesting Time and Prices

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#186]
The purpose of this proposal is to collaborate on the prices that will be used for buying seeds in the game and selling the crops that are grown.

**Assumptions**

1. The anti-botting mechanisms will prevent/minimise any bots playing the game
2. The prices will change proportionally during each halvening period. The prices in this document refer to the initial prices in the game.
3. Multi accounts will exist

**Progressive Gameplay** 

We want farmers to have an equilibrium of challenge and progress as they play the game. We want them to feel rewarded when they reach a new level.

_Ideal time to reach upgrades_

First Upgrade - 3 hours
Second Upgrade - 2 days
Third Upgrade - 1 week
Fourth Upgrade - 2-4 weeks

**Crops are needed to craft items and unlock new gameplay areas**

The purpose of upgrading your farm is not solely to get crops that earn more tokens. Players will need to grow radishes, cauliflowers and parsnips to craft certain NFTs and access certain gameplay.

These crops will be staple ingredients in recipes that are required for humans and goblins to work in Sunflower Land

**NFT Buffs will exist**

If you want to invest in your farm you will be able to do so by crafting limited NFTs - these can be used to increase certain buffs around certain all or all groups, including:

- Time to grow
- Quality of crop (increased sale price)

An example of this is the scarecrow which reduces the time it takes for wheat to grow.

**Reward those who play more**

There have been a few different models forecasted for different crop prices and the most sustainable one that arose was the inversion of prices. The low end crops yield higher ROI. This seems contrary to most games where the more advanced crops earn more money. The key difference here is that we have a secondary market to the game with a real world economy - people will not play the game 'fairly' if it means they can earn more tokens.

If the high end crops were the most lucrative, we would have people setting up 500 farms and managing them manually. (i.e. planting crops that take 24 hours to harvest) - These people are not exactly 'playing' the game and we do not want to reward them compared to other players.

The most profitable strategy in this proposed model is planting Sunflowers 24/7. The only downside is that you will get no sleep.

It is worth noting when performing calculations that most people can only physically play the game for 16 hours a day.

Even though you could make more money opening your phone and planting potatoes every 5 minutes, it is more practical for you to plant a 4 hour crop even though you make a bit less.

### Game Start

At the beginning of the game you start with 3 ripe sunflowers. The player will harvest and sell these flowers to get their first tokens.

**Sunflower**

Seed - $0.01
Crop - $0.02
Time to Grow - 1 minute

**Potato**

Seed - $0.10
Crop - $0.14
Time to grow - 5 minutes

**Pumpkin**

Seed - $0.20
Crop - $0.40
Time to grow - 30 minutes

### First upgrade

<img width="259" alt="Screen Shot 2022-01-25 at 4 45 52 pm" src="https://user-images.githubusercontent.com/11745561/151048308-f005596c-9761-415a-9a6f-b60f28a4f57c.png">

To unlock the second set of fields, you need to craft pumpkin soup. This requires 5 pumpkins and $1 SFL token. The idea is that you need to actually play the game to start and collect resources before unlocking the next level.

Unlocking this field gives players a ripe carrot and cabbage to harvest.

**Carrot**

Seed - $0.50
Crop - $0.80
Time to grow - 1 hour

**Cabbage**

Seed - $1
Crop - $1.50
Time to grow - 2 hours

### Second Upgrade

<img width="246" alt="Screen Shot 2022-01-25 at 4 50 13 pm" src="https://user-images.githubusercontent.com/11745561/151048941-e47decf7-5710-425c-afea-1ef3a1f2b362.png">

To unlock these fields you need to craft Sauerkraut - This needs 10 cabbage and $5 SFL token

**Beetroot** 

Seed - $2
Crop - $2.80
Time to grow - 4 hours

**Cauliflower**

Seed - $3
Crop - $4.25
Time to grow - 8 hours

### Third Upgrade

<img width="246" alt="Screen Shot 2022-01-25 at 4 53 12 pm" src="https://user-images.githubusercontent.com/11745561/151049382-fa88a4dc-c079-4d07-bced-8528aa0e0913.png">

This unlock these fields you need to craft Roasted Cauliflower - This requires 50 cauliflowers and $20 SFL

**Parsnips**

Seed - $5
Crop - $6.50
Time to grow - 12 hours

**Radish**

Seed - $7
Crop - $9.50
Time to grow - 24 hours

### Other Upgrade

The upcoming plants for upgrade will be wheat and kale. These are yet to be decided.

**Comment by Samuvieira07** [comment]
Nice proposal, i support this 100%

**Comment by Andreivv** [comment]
Hi! I have a suggestion to implement this proposal, but it's a little big, so I'll attach a text file here
I also believe that it speaks directly to the proposal you created.

[Crops, burpings and flour..docx](https://github.com/sunflower-land/sunflower-land/files/7939212/Crops.burpings.and.flour.docx)
.

**Comment by AncientHorse** [comment]
> It is worth noting when performing calculations that most people can only physically play the game for 16 hours a day.

I think you are underestimating this community.  :)

**Comment by silici0** [comment]
I would like to seed the upgrade time bigger, like monthly.
I hate the idea that money play the game, instead like all video games, should be time that push you futher into lvls
:)

**Comment by adamhannigan** [comment]
> Hi! I have a suggestion to implement this proposal, but it's a little big, so I'll attach a text file here I also believe that it speaks directly to the proposal you created.
> 
> [Crops, burpings and flour..docx](https://github.com/sunflower-land/sunflower-land/files/7939212/Crops.burpings.and.flour.docx) .

These are some great ideas! Can you open up a new proposal for this. It will make it easier for others to read and give feedback to this idea :)

**Comment by adamhannigan** [comment]
> I would like to seed the upgrade time bigger, like monthly. I hate the idea that money play the game, instead like all video games, should be time that push you futher into lvls :)

For the initial levels, it is important to give new players a glimpse of the upgrades and feel like they are progressing. It is good if within the first day they can even manage an upgrade.

Are you suggesting that the fourth upgrade takes 1 month to upgrade? 

Also, what do you think about taking 1 month to upgrade to wheat/kale?

**Comment by silici0** [comment]
> > I would like to seed the upgrade time bigger, like monthly. I hate the idea that money play the game, instead like all video games, should be time that push you futher into lvls :)
> 
> For the initial levels, it is important to give new players a glimpse of the upgrades and feel like they are progressing. It is good if within the first day they can even manage an upgrade.
> 
> Are you suggesting that the fourth upgrade takes 1 month to upgrade?
> 
> Also, what do you think about taking 1 month to upgrade to wheat/kale?

I have seen a lot games that fullFarm is payable, so in the first month players will just sell a lot of tokens, my first thought in those system, its not a game, usual a game takes skill/time to master (in the NFT case - token rewards), so would be nice we have a time progression mixed with any kind of strategy (save some harvest to create food, to buy/craft nft and so on).
And i would say, more upgrades, more time. :)
I would feel very happy to play this type of game for years...

**Comment by AncientHorse** [comment]
> I have seen a lot games that fullFarm is payable, so in the first month players will just sell a lot of tokens, my first thought in those system, its not a game, usual a game takes skill/time to master (in the NFT case - token rewards), so would be nice we have a time progression mixed with any kind of strategy (save some harvest to create food, to buy/craft nft and so on). And i would say, more upgrades, more time. :) I would feel very happy to play this type of game for years...

I agree lots of people are turned off when they play a game for months only to have someone with come in and buy their way to end game.  It's possible lots of people could instantly buy their way to max level immediately.  I'm not sure there is an easy solution to this as stifling demand for the new token isn't desirable either.  Perhaps there could be a way where players could satisfy some requirements by buying tokens, but there would be a limiting factor as the levels get higher that only game time could satisfy.

**Comment by Andreivv** [comment]
> > I have seen a lot games that fullFarm is payable, so in the first month players will just sell a lot of tokens, my first thought in those system, its not a game, usual a game takes skill/time to master (in the NFT case - token rewards), so would be nice we have a time progression mixed with any kind of strategy (save some harvest to create food, to buy/craft nft and so on). And i would say, more upgrades, more time. :) I would feel very happy to play this type of game for years...
> 
> I agree lots of people are turned off when they play a game for months only to have someone with come in and buy their way to end game. It's possible lots of people could instantly buy their way to max level immediately. I'm not sure there is an easy solution to this as stifling demand for the new token isn't desirable either. Perhaps there could be a way where players could satisfy some requirements by buying tokens, but there would be a limiting factor as the levels get higher that only game time could satisfy.

Look at this idea I brought up, I don't know if it's explained well, but it talks a lot with what is being talked about here by you.
https://github.com/sunflower-land/sunflower-land/issues/197 , maybe works

**Comment by silici0** [comment]
@Andreivv love the idea 🇧🇷

**Comment by MarketParticipant** [comment]
"The most profitable strategy in this proposed model is planting Sunflowers 24/7. The only downside is that you will get no sleep."

**Comment by adamhannigan** [comment]
@MarketParticipant This proposal assumes the game has anti-botting mechanisms.

This will include a mix of human verification + rate limiting.

For a real human it is very difficult to maintain more than 2 Sunflower Farms at the same time. On the other hand, it is quite easy for a human to manage 1000 Cauliflower Farms as they have 8 hours between planting and harvesting.

**Comment by kimberlite07** [comment]
Hi! I'd like to air out a concern on having lower tier plants to have higher RIO. It'll work assuming that the antibotting mechanisms would wipe out all bots. However, it would be naive to think that it will, thus we can always expect that bots will always be present as the game goes live. 

Also, during v1 the only upside to planting higher level crops was that I only had to save the game once every 3 days. But in v2, since this advantage will be removed because we wouldn't have to save as often to the blockchain, then I can't see what the advantage of higher level farms will be.

Admittedly, I don't have a good idea to get around this. :/ I hope someone else or the team can think of something.

**Comment by MarketParticipant** [comment]
Sorry I deleted my comment before you replied, Adam.  I was planning to repost it with a spreadsheet to better explain.  I guess rate limiting can do the same thing as the diminishing returns on crops I was suggesting, but like kimberlite07, I'm skeptical of anti-bot measures working for long if there is profit to be had.  The ROI on 100% gains per minute with sunflowers is a healthy incentive for smarter people than I to figure out how to game the system.  It seems smart to do the anti-bot measures and adjust the ROIs.

Still working on the spreadsheet...

**Comment by kimberlite07** [comment]
I read @Andreivv's proposal on introducing stamina and having more of it as the level of farm goes up. I
 think this will offset the lower awards for high level crops.

I also agree to introduce some factors like pests, penalties and whatnot depending on the type of crops there are in a field. This will make the game more interesting and would actually need a strategy than just passively planting and harvesting. We can even add watering as an actual activity by the farmer and not just a visual thing like in v1.

**Comment by noprudhon** [comment]
Aside from the anti-bot mechanism, While multi-accounts are allowed, I think it's important to forbid the usage of any kind of macro/auto-clicker program in/with the game. Like you said you want people to be rewarded for playing the game, not running an auto click macro to harvest sunflowers 24/7 (which are more commonly found in P2E games than full on bots). Besides a zero tolerance on this will make it easy for you to identify who's cheating.

**Comment by adamhannigan** [comment]
@kimberlite07 The game will transition away from farming as the core source ROI. In truth, there is no way to prevent bots who automate basic gameplay. 

Farming will become less profitable over time. The profitable play will come from collecting exotic resources and crafting limited items and/or performing side quests where you will be rewarded in SFL. This will require strategy and will be tough to automate.

Farming will be used mainly as a progression in the game to unlock other areas and craft recipes.

**Comment by kimberlite07** [comment]
> @kimberlite07 The game will transition away from farming as the core source ROI. In truth, there is no way to prevent bots who automate basic gameplay.
> 
> Farming will become less profitable over time. The profitable play will come from collecting exotic resources and crafting limited items and/or performing side quests where you will be rewarded in SFL. This will require strategy and will be tough to automate.
> 
> Farming will be used mainly as a progression in the game to unlock other areas and craft recipes.

I do agree with everything you said and like this as a long-term plan. I hope that there will be a balance between short-term and long-term plans since we won't get to reach those long-term plans without the short-term preparations. 

That said, I've been reading the proposals here and I think these will work well with your plans (although I'm really not an expert so here's to hoping!).

**Comment by adamhannigan** [comment]
@kimberlite07 It will be an evolving game that is for sure.

Players that stay loyal over the next few months will find themselves in a very good position to have valuable and expansive farms ;)

**Comment by silici0** [comment]
> @kimberlite07 It will be an evolving game that is for sure.
> 
> Players that stay loyal over the next few months will find themselves in a very good position to have valuable and expansive farms ;)

I like where you going! ;)

**Comment by kimberlite07** [comment]
Hi @adamhannigan. I was wondering how come all farm plots are already available by level 4? Based on here, if a farmer start at level 1 with 5 farm plots, by level 4 the farm is maxed out already 

I thought the farm is supposed to be at maximum capacity by level 5 and not level 4.

Maybe you should revisit this part of the game?
