### ISSUE TITLE
[PROPOSAL] Tokenomics + Halvening Mechanic

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#187]
The purpose of this proposal is to explore the tokenomics of the project, specifically the halvening mechanism.

Since the token has an infinite supply, the game needs an in-built mechanism that will help drive scarcity. Similar to Bitcoin Halvening, as the game progresses it will become harder to earn the token. 

This is based on the total supply of the token. When a certain threshold is met, the **seed** and **crop** prices will half. This means it becomes twice as hard to earn rewards as the previous period.

**Assumption**

1. Tools are fractionalized. This means players in the future can buy 0.001 of an axe to chop 0.001 of wood. This keeps it engaging for new players to continue playing the game
2. Future NFTs releases will be proportional to the current price - A rare NFT may only cost 0.5 wood and 0.02 tokens in 5 years
3. The total supply will reset at 0 but will quickly skyrocket past 1 million as players activate their airdrops from Sunflower Farmers

## Total Supply Thresholds

The prices below are based on what the sale price of a **sunflower** is.

**Less than 1, 000, 000**
$0.002

**Less than 5, 000, 000**
$0.001

**Less than 10, 000, 000**
$0.0005

**Less than 20, 000, 000**
$0.00025

**Less than 30, 000, 000**
$0.000125

**Les than 40, 000, 000**
$0.0000625

**Less than 50, 000, 000**
$0.00003125

_Same pattern occurs every 10 million tokens_

## Explanation

Every 10 million tokens when the halvening period takes place, it means that it will take twice the amount of effort to reach the next halvening period.

Over time we want these halvening periods to take place less often and stabilise. 

_Forecast to reach total supplies_

**5 million** - 30,000 players - 2 weeks (from start)
**10 million** - 50,000 players - 3 weeks (from start)
**20 million** - 100,000 players - 2 months (from start)
**30 million** - 180,000 players - 3 months (from start)
**40 million** - 300,000 players - 4 months (from start)
**50 million** - 500,000 players - 5 months (from start)

## Block Number / Timestamp

When a threshold is approaching, the game will announce the block number + timestamp that the estimated threshold will be reached. At that point, prices will be instantly changed.

## Burning

When a player saves their off-chain data to the Blockchain and they have a reduction in tokens, the game will send these tokens to the burn address `0x000000000000000000000000000000000000`

This ensures that the total supply will never decrease.

## No reward pool

The initial launch will not include the rewards pool. We will need to design this mechanic as a community and figure out who gets rewarded and with what (it can be a mixture of tokens, resources, tools etc.)

**Comment by AncientHorse** [comment]
I read the tokenomics section but am confused on a couple things:

1) When a player buys seeds, are those tokens burned?
2) When a player buys a non-user generated NFT, are those burned?
3) When a player upgrades their farm, are those burned?

Do all of these purchases go towards the 72 hour reward?

I'm so sorry if this is already explained somewhere and I missed it.  I think this plan looks solid but is largely dependent on players having a variety of things to spend their coins on.  I think a fun aspect would be for players to have a variety of progression paths to chose from but not initially have enough tokens to pursue them all.  This also challenges the player to decide to cash out or keep investing in their farm.

**Comment by adamhannigan** [comment]
@AncientHorse Good points! I have updated the proposal. When buying/crating/upgrading, SFL tokens will be sent to the burn address and so the total supply will not decrease, only the circulating supply.

The initial launch will not include the rewards mechanic yet. The plan is to analyse what identifies a positive player in the game, and reward those people

**Comment by kimberlite07** [comment]
Hey, Adam. I was wondering if when the supply reaches the threshold for halvening to happen, will it be permanent already regardless if the supply goes down as tokens are being spent? It isn't explicitly mentioned so was wondering about that

**Comment by adamhannigan** [comment]
@kimberlite07 Yes, the way the proposed system will work is that a block number / time will be picked as the estimate for the halvening to occur on.

This will make it more predictable and avoid the issue in the old game where supply would fall under the threshold.

**Comment by kimberlite07** [comment]
That's great. Also I noticed the prices indicated in the planting proposal are different. Assuming we start at around 1M tokens as game goes live, which ones are we following?

**Comment by adamhannigan** [comment]
@kimberlite07 Yes, we will start at 1M tokens go live :) I will update those
