### ISSUE TITLE
Artist NPC (Collectible)

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#189]
The Artist NPC will be a Collectible that will give the owners access to a special channel on Discord (using Collabland). This channel will be used to vote on the art work that is being submitted to the game.

**Request**

- An NPC that looks like an artist

**Warning**

Since this item will be an NFT, we cannot use the base asset pack sprites from SunnySide

**Bonus!!!**

The winning submission will receive the first minted artist NFT 🏆 

## Deadline

22nd February

**Comment by ItsNight** [comment]
**i love the idea**

**Comment by soteleon** [comment]
Something like this works? maybe a dark blue beret could work 

![artis smallt](https://user-images.githubusercontent.com/94320699/151064654-da0eaf96-c360-4e30-9672-9a3008df7d4e.png)
![artist](https://user-images.githubusercontent.com/94320699/151064658-18ff9f9e-2bad-4206-9625-ef27023834db.png)

**Comment by Aestnelis** [comment]
![artist](https://user-images.githubusercontent.com/98103679/151078734-a1bf59ba-dab2-4dfe-afe7-ae5f2ebec588.png)
![bigartist](https://user-images.githubusercontent.com/98103679/151078749-0d1869bf-e6a0-4521-a801-cfc50ffc2a74.png)
If want something to be edited just tell me!

**Comment by benaxol12** [comment]
![Bob orj](https://user-images.githubusercontent.com/98098031/151135814-c7cfbebc-3ba8-4fee-977d-fe272359a1f5.png)
![Bob 4x](https://user-images.githubusercontent.com/98098031/151135816-0433c933-ac4e-414c-9a15-871e9f061b39.png)

in memory of bob ross 🎨 
![Bob Gif](https://user-images.githubusercontent.com/98098031/151135787-56ec4b56-d35e-4294-91f1-b1dcb086104f.gif)
![gify 4x](https://user-images.githubusercontent.com/98098031/151135697-f4120213-589a-4dda-9ab9-b77719886f1f.gif)

**Comment by paluras** [comment]
![Frida](https://user-images.githubusercontent.com/98059798/151155004-fc3b2b86-8f0c-4317-896c-699e4af6fc35.png)
![Fridasmall](https://user-images.githubusercontent.com/98059798/151155012-1ecfff8e-4771-4798-831a-86abf4cc7fed.png)

**Comment by gabiqueiroga** [comment]
![image](https://user-images.githubusercontent.com/69090306/151253389-015267ca-16e7-4627-9830-270f3e8e1ce5.png)
![vanGoghBlack](https://user-images.githubusercontent.com/69090306/151253506-27594393-052f-4851-89be-ee0c7f4862c9.png) ![VanGoghColor](https://user-images.githubusercontent.com/69090306/151253597-13f99250-c16b-439e-b390-333cd1926d1e.png)

**Comment by defido** [comment]
> SunnySide

Haha Bob Ross, awesome!

**Comment by soteleon** [comment]
> ![artist fnial](https://user-images.githubusercontent.com/94320699/151098591-c9e4fcbd-7b11-4844-a312-f39f78606a24.png) ![artist 3](https://user-images.githubusercontent.com/94320699/151068213-c4b3e2ad-0bd6-4042-a19b-c176f6c20649.png) ![artist 3small](https://user-images.githubusercontent.com/94320699/151068215-3302c6d4-8249-4a97-aed1-69c502971fda.png) ![artist fnial minimiunn](https://user-images.githubusercontent.com/94320699/151098618-5452f10e-6bdb-4f26-bf13-cafdc18c4f05.png)
> 
> There, tried to take a broader vision or artist, and tried to keep it simple to fit game aesthetics


Update
![woodhouse](https://user-images.githubusercontent.com/94320699/151271166-8516d045-6fb1-4293-baf9-139589d8d91f.png)
![woodhousebig ](https://user-images.githubusercontent.com/94320699/151271169-224374ff-43ea-4a43-9a03-4551a3368b54.png)

**Comment by defido** [comment]
> > ![artist fnial](https://user-images.githubusercontent.com/94320699/151098591-c9e4fcbd-7b11-4844-a312-f39f78606a24.png) ![artist 3](https://user-images.githubusercontent.com/94320699/151068213-c4b3e2ad-0bd6-4042-a19b-c176f6c20649.png) ![artist 3small](https://user-images.githubusercontent.com/94320699/151068215-3302c6d4-8249-4a97-aed1-69c502971fda.png) ![artist fnial minimiunn](https://user-images.githubusercontent.com/94320699/151098618-5452f10e-6bdb-4f26-bf13-cafdc18c4f05.png)
> > There, tried to take a broader vision or artist, and tried to keep it simple to fit game aesthetics
> 
> Update ![woodhouse](https://user-images.githubusercontent.com/94320699/151271166-8516d045-6fb1-4293-baf9-139589d8d91f.png) ![woodhousebig ](https://user-images.githubusercontent.com/94320699/151271169-224374ff-43ea-4a43-9a03-4551a3368b54.png)

I think maybe the skin colour being lighter would help with the contrast, as the grass is already dark and the cabin is dark.

**Comment by soteleon** [comment]
> > > ![artist fnial](https://user-images.githubusercontent.com/94320699/151098591-c9e4fcbd-7b11-4844-a312-f39f78606a24.png) ![artist 3](https://user-images.githubusercontent.com/94320699/151068213-c4b3e2ad-0bd6-4042-a19b-c176f6c20649.png) ![artist 3small](https://user-images.githubusercontent.com/94320699/151068215-3302c6d4-8249-4a97-aed1-69c502971fda.png) ![artist fnial minimiunn](https://user-images.githubusercontent.com/94320699/151098618-5452f10e-6bdb-4f26-bf13-cafdc18c4f05.png)
> > > There, tried to take a broader vision or artist, and tried to keep it simple to fit game aesthetics
> > 
> > 
> > Update ![woodhouse](https://user-images.githubusercontent.com/94320699/151271166-8516d045-6fb1-4293-baf9-139589d8d91f.png) ![woodhousebig ](https://user-images.githubusercontent.com/94320699/151271169-224374ff-43ea-4a43-9a03-4551a3368b54.png)
> 
> I think maybe the skin colour being lighter would help with the contrast, as the grass is already dark and the cabin is dark. It's really well done!

Indeed! that´s a good suggestion, I felt that some change was missing, something like this maybe?

![woodhousebig ](https://user-images.githubusercontent.com/94320699/151272856-0ba0539f-a794-46ee-a6f6-ee57b962453f.png)

**Comment by defido** [comment]
> > > > ![artist fnial](https://user-images.githubusercontent.com/94320699/151098591-c9e4fcbd-7b11-4844-a312-f39f78606a24.png) ![artist 3](https://user-images.githubusercontent.com/94320699/151068213-c4b3e2ad-0bd6-4042-a19b-c176f6c20649.png) ![artist 3small](https://user-images.githubusercontent.com/94320699/151068215-3302c6d4-8249-4a97-aed1-69c502971fda.png) ![artist fnial minimiunn](https://user-images.githubusercontent.com/94320699/151098618-5452f10e-6bdb-4f26-bf13-cafdc18c4f05.png)
> > > > There, tried to take a broader vision or artist, and tried to keep it simple to fit game aesthetics
> > > 
> > > 
> > > Update ![woodhouse](https://user-images.githubusercontent.com/94320699/151271166-8516d045-6fb1-4293-baf9-139589d8d91f.png) ![woodhousebig ](https://user-images.githubusercontent.com/94320699/151271169-224374ff-43ea-4a43-9a03-4551a3368b54.png)
> > 
> > 
> > I think maybe the skin colour being lighter would help with the contrast, as the grass is already dark and the cabin is dark. It's really well done!
> 
> Indeed! that´s a good suggestion, I felt that some change was missing, something like this maybe?
> 
> ![woodhousebig ](https://user-images.githubusercontent.com/94320699/151273159-0a77f008-d1c0-4771-bac5-468c45be2d0c.png)

Yeah I think that is so much better, it just pops the character out from the backdrop. Really well done!

**Comment by soteleon** [comment]
> Yeah I think that is so much better, it just pops the character out from the backdrop. Really well done!

No, thanks to you for the advice <3

**Comment by gabiqueiroga** [comment]
> > Van Gogh is one of my favorite painters. He made a painting called "Sunflowers" and associated it with gratitude. So, knowing this, I couldn't help but show my gratitude to Van Gogh, the Sunflower Land team and our entire community creating this NFT. I imagine he has lived or would love to live near fields similar to the ones in our game in real life. (Art was based on the original painting)
> > > The sunflower paintings had a special significance for Van Gogh: they communicated ‘gratitude’, he wrote. He hung the first two in the room of his friend, the painter Paul Gauguin, who came to live with him for a while in the Yellow House. Gauguin was impressed by the sunflowers, which he thought were ‘completely Vincent’.    -Van Gogh Museum website
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69090306/151287239-394a8a26-e111-4d44-9db5-c189c9498c2a.png)
> 
> latest version ![image](https://user-images.githubusercontent.com/69090306/151388188-5a828a91-9362-4f39-8ee2-cca0d017419f.png) ![VanGoghSprites](https://user-images.githubusercontent.com/69090306/151391968-72a2538c-0b67-42a1-a6d8-5e5f5d1077d3.png)

latest latest version haha
![image](https://user-images.githubusercontent.com/69090306/152270330-54e79549-11a9-4970-a069-c3cbe302393b.png)

**Comment by Aestnelis** [comment]
![bigsunflower artist](https://user-images.githubusercontent.com/98103679/152654240-750a140c-ad29-4875-9758-d1c8613af7c6.png)

**Comment by Aestnelis** [comment]
![bigsunflower artist](https://user-images.githubusercontent.com/98103679/152654262-d0bb54cf-6718-418e-96af-0d5a5368625e.png)
![bigartist](https://user-images.githubusercontent.com/98103679/152654267-5d0c00da-d5e0-463a-aba4-4c55541c0e2a.png)

**Comment by soteleon** [comment]
> She looks like a friend of mine, I really liked this one!

**Comment by Krabayo** [comment]
![Van-Gogh](https://user-images.githubusercontent.com/28789160/152674194-fd04aa51-d0c6-4711-92a5-1a6b96db433e.png)

**Comment by Vergelsxtn** [comment]
Hi, this is john the giant man he's an artist at sunflower village, everyone is scared of him because of his height, but they really love his art and can't stop looking at it in distance.
![Artist-NPC](https://user-images.githubusercontent.com/99605039/154230487-8c4f8e74-7526-47a9-98f4-326149193465.gif)
![Artist-NPC1](https://user-images.githubusercontent.com/99605039/154230588-87de1db7-8992-4657-b4e5-6ebacd43a5b5.gif)

**Comment by Alexcnder** [comment]
**Oh no is that me drawing myself?!?!?!**!
<br><br><br>
>
![PAINT NFT](https://user-images.githubusercontent.com/87881787/154335142-ba661cd7-5853-469f-adba-15b2c4d85988.png)

**Comment by adamhannigan** [comment]
The winner is @gabiqueiroga 🏆 There were so many great submissions and it was an extremely close choice!

The Van Gogh reference was great and the art fits nicely in the theme of the game ❤️ 

Can you please included the minified assets when you get time

**Comment by adamhannigan** [comment]
Hey all 👋 Just an update, we haven't been able to implement this cleanly in the game design/roadmap yet.

It looks like this will be delayed signifcantly in favour of other features.

We will have an exciting artist skill badge coming soon though 😏
