### ISSUE TITLE
Akita Statue

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#191]
![2SSdfd3223](https://user-images.githubusercontent.com/98098233/151076625-bc806b6b-3e18-4428-86a9-ffa9c358ef74.png)
![2SS3223](https://user-images.githubusercontent.com/98098233/151076631-86c02c18-ef30-4970-ad05-f368cfb3f2ef.png)
![termin (1)](https://user-images.githubusercontent.com/98098233/151076780-5a9e446f-5af8-4391-b552-3127399f9b85.gif)

**Akita Statue**

**Comment by soteleon** [comment]
isn´t that you Hachikō?

**Comment by defido** [comment]
Awesome
