### ISSUE TITLE
NFT Bumpkins shipped to island

### ISSUE THREAD

**Issue by 0gabriel22** [sunflower-land/sunflower-land#1923]
The nft bumpkins items that were sent to the island and lost, when will they return to the account? in my case it's the Golden Spatula that I lost.

**Comment by Myth727** [comment]
> The nft bumpkins items that were sent to the island and lost, when will they return to the account? in my case it's the Golden Spatula that I lost.

When you say sent to the island,  did you send the item to your farm address and not attach it to the bumpkin? Just trying to clarify this, it will help to gather the answer then.

**Comment by 0gabriel22** [comment]
> > Os itens nft caipiras que foram enviados para a ilha e perdidos, quando voltam para a conta? no meu caso é a Espátula Dourada que perdi.
> 
> Quando você diz enviado para a ilha, você enviou o item para o endereço da sua fazenda e não o anexou ao caipira? Apenas tentando esclarecer isso, ajudará a reunir a resposta.

Yes, that's what I did!

**Comment by Myth727** [comment]
I would highly suggest reaching out on discord to see if you can get the answer,  otherwise I'm pretty sure it's a lost item. There is a in game warning to not send matic, bumpkin items or non sfl tokens. 

Still worth asking around tho, but some mistakes can't be undone.

**Comment by adamhannigan** [comment]
Hey @0gabriel22 The team is aware of this issue and we know the solution.

Unfortunately this won't be implemented in the short term because of other features that need to be shipped.

A withdrawal mechanism will be coming, it may take just a little while 🙏
