### ISSUE TITLE
Cow / Milk / Beef / Bull

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#195]
This request is for a cow to be used in the game. This will be used for collecting milk and meat.

Bonus points for any sort of animation 🚀 

Used in the Cow/Milk/Beef proposal - https://github.com/sunflower-land/sunflower-land/issues/214

**Comment by soteleon** [comment]
Standin up and one resting

![vaca 1 bigl](https://user-images.githubusercontent.com/94320699/151213276-26a321f5-8ff2-4144-a3ad-d4aa231744db.gif)
![vaca 1 small](https://user-images.githubusercontent.com/94320699/151213280-57894194-343e-4ea4-8a86-2e10b9615764.gif)
![vaca 2 BIGt](https://user-images.githubusercontent.com/94320699/151213284-feb6b9dd-08d4-47cb-90c9-7ed8a0d68aa6.gif)
![vaca 2 small](https://user-images.githubusercontent.com/94320699/151213285-1d5bfef9-cbd2-46d1-a32a-7f396eb3c195.gif)

**Comment by ItsNight** [comment]
animated ?

**Comment by spencerdezartsmith** [comment]
![BullCharacterNoSpots (1)](https://user-images.githubusercontent.com/17863697/151274606-408ee474-b132-4a92-bcb5-75a02f5a56b1.png)

This was a bull that another user had designed during V1.

**Comment by BigKongJosh** [comment]
Dairy Cow Idle
![Dairy Cow Idle](https://user-images.githubusercontent.com/98506626/151290956-78073017-9a54-4861-9016-c2cb3a7a8bea.gif)
Dairy Cow Grazing
![Dairy Cow Grazing](https://user-images.githubusercontent.com/98506626/151290962-dff2334f-8e45-4f51-8d0c-a81016b3525d.gif)
Dairy Cow Idle to Sleep (can be reversed for Sleep to Idle)
![Dairy Cow Idle to Sleep](https://user-images.githubusercontent.com/98506626/151290969-4872e9cd-f88b-4cee-bcef-f482f74f7e03.gif)
Dairy Cow Sleep
![Dairy Cow Sleep](https://user-images.githubusercontent.com/98506626/151290975-faeace5b-77ea-4dbe-a188-bb836047a082.gif)

**Comment by paluras** [comment]
![Cow_smoll](https://user-images.githubusercontent.com/98059798/151413898-3a24ef54-4dfb-49d6-89e4-1f16d46174e8.png)
![Cowl](https://user-images.githubusercontent.com/98059798/151413901-20ea2567-e955-4db2-8837-24be0fb988e8.png)

**Comment by spencerdezartsmith** [comment]
> Dairy Cow Idle ![Dairy Cow Idle](https://user-images.githubusercontent.com/98506626/151290956-78073017-9a54-4861-9016-c2cb3a7a8bea.gif) Dairy Cow Grazing ![Dairy Cow Grazing](https://user-images.githubusercontent.com/98506626/151290962-dff2334f-8e45-4f51-8d0c-a81016b3525d.gif) Dairy Cow Idle to Sleep (can be reversed for Sleep to Idle) ![Dairy Cow Idle to Sleep](https://user-images.githubusercontent.com/98506626/151290969-4872e9cd-f88b-4cee-bcef-f482f74f7e03.gif) Dairy Cow Sleep ![Dairy Cow Sleep](https://user-images.githubusercontent.com/98506626/151290975-faeace5b-77ea-4dbe-a188-bb836047a082.gif) Milk ![Bottle of Milk](https://user-images.githubusercontent.com/98506626/151291590-530ca51c-d114-4b20-8ab4-e83c0a3101d0.png) Beef ![Beef](https://user-images.githubusercontent.com/98506626/151291598-41088d25-feb4-4159-b280-980e73e4f87c.png)

I love this!

**Comment by gabiqueiroga** [comment]
The scene is still a WIP, but I think the cow is ok

https://user-images.githubusercontent.com/69090306/151740596-60ddf131-e78f-4c51-be94-c327180ca862.mp4



![Cow1](https://user-images.githubusercontent.com/69090306/151740623-d551092a-8763-46b1-a99e-a86dcf4e1786.gif)

**Comment by Aestnelis** [comment]
![bigcow](https://user-images.githubusercontent.com/98103679/152594715-acc082b4-5baa-4a87-a6ed-ffb6d419bc7f.gif)
![lilcow](https://user-images.githubusercontent.com/98103679/152594768-08eefea9-bbea-47b8-9766-f8ba1b001f01.gif)

**Comment by Alexcnder** [comment]
> Dairy Cow Idle ![Dairy Cow Idle](https://user-images.githubusercontent.com/98506626/151290956-78073017-9a54-4861-9016-c2cb3a7a8bea.gif) Dairy Cow Grazing ![Dairy Cow Grazing](https://user-images.githubusercontent.com/98506626/151290962-dff2334f-8e45-4f51-8d0c-a81016b3525d.gif) Dairy Cow Idle to Sleep (can be reversed for Sleep to Idle) ![Dairy Cow Idle to Sleep](https://user-images.githubusercontent.com/98506626/151290969-4872e9cd-f88b-4cee-bcef-f482f74f7e03.gif) Dairy Cow Sleep ![Dairy Cow Sleep](https://user-images.githubusercontent.com/98506626/151290975-faeace5b-77ea-4dbe-a188-bb836047a082.gif) Milk ![Bottle of Milk](https://user-images.githubusercontent.com/98506626/151291590-530ca51c-d114-4b20-8ab4-e83c0a3101d0.png) Beef ![Beef](https://user-images.githubusercontent.com/98506626/151291598-41088d25-feb4-4159-b280-980e73e4f87c.png)

Hey i made a Bull real quick matching to this artwork. If i should animate it tell me

![wo background](https://user-images.githubusercontent.com/87881787/160676051-ff8ae7f0-485f-4b2a-9428-8d815e0d0f98.png)

**Comment by jojothe2nd** [comment]
Made a cow a while back, might as well post it here,
![Cow-SFF-2](https://user-images.githubusercontent.com/16280287/164339026-e341abaa-945a-4602-b202-14eafade32c6.png)

**Comment by Nyp-Sfl** [comment]
look at that sweet cow
![cowwwww](https://user-images.githubusercontent.com/104236389/164913022-95dbea85-e434-4846-bc53-3a63cf465f7d.gif)
![cowwww büykw](https://user-images.githubusercontent.com/104236389/164913053-e87a782f-f179-4520-af01-dedeb6303dbc.gif)

**Comment by zxearl** [comment]
![pixil-gif-drawing (14)](https://user-images.githubusercontent.com/104722435/166183405-d4e9c18a-0a6a-4c4f-acb8-219f0c0d5e1a.gif)
![pixil-gif-drawing (9)](https://user-images.githubusercontent.com/104722435/166183418-63a9d330-33c3-474b-ae96-50af9035279f.gif)

ID Farm: 11956
Discord: Zxearl#9817
Polygon: 0x5B1B0C2122C015d583886a4F246bA6d709e53968
