### ISSUE TITLE
Pig / Mud / Manure / Bacon

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#196]
This request is for a pig to be used in the game. This will be used for collecting manure and ingredients.

Bonus points for any sort of animation 🚀 

Used for the upcoming feature - https://github.com/sunflower-land/sunflower-land/issues/213

**Comment by soteleon** [comment]
Small one playing at the mud

![pig big](https://user-images.githubusercontent.com/94320699/151206902-5f0fe6ab-0d9e-477e-8be5-a359ccc267bf.gif)
![pig](https://user-images.githubusercontent.com/94320699/151206906-0d0fc482-92cb-4c1f-93b6-fc293a874678.gif)

**Comment by Aestnelis** [comment]
![pig](https://user-images.githubusercontent.com/98103679/151207097-46a1038f-1f63-4c22-8aed-60f9aad101b3.gif)
![bigcutepig](https://user-images.githubusercontent.com/98103679/151207127-8e154721-d79c-4c6d-81f2-be8f15feddd1.gif)

**Comment by ItsNight** [comment]
sorry its not halal for me HHH im working on it

**Comment by InuBakaBo** [comment]
Pixel art is relatively new to me, and animation is just another level that I haven't delved into yet. I'm just using MSPaint lol... Anyway hope you enjoy my pigs and piglet.

![Pigs - ZoomPreview](https://user-images.githubusercontent.com/98318794/151348605-f998f4d0-4eba-4e26-9f01-bf6882e9f1f6.png)
![Pigs](https://user-images.githubusercontent.com/98318794/151348607-67e7635e-6f67-4d4c-801e-0369a8407970.png)

**Comment by Aestnelis** [comment]
![bigcutepig](https://user-images.githubusercontent.com/98103679/151576251-4fcc7dcc-c50c-4bc1-9445-7d29c7464128.gif)

**Comment by gabiqueiroga** [comment]
https://user-images.githubusercontent.com/69090306/151844507-7ca2262f-19fc-422a-9698-b438eb6ce7f9.mp4

![pig1](https://user-images.githubusercontent.com/69090306/151844519-b8017998-91d3-4efe-b7d0-4f63ecdd09c1.gif)

**Comment by defido** [comment]
> pig2.mp4 
> ![pig1](https://user-images.githubusercontent.com/69090306/151844519-b8017998-91d3-4efe-b7d0-4f63ecdd09c1.gif) ![pi2](https://user-images.githubusercontent.com/69090306/151850485-727f7582-01aa-4309-bade-3822dca2bff3.gif)

Love the cow.

**Comment by Driftingwood** [comment]
Here's my piggy.
![pig](https://user-images.githubusercontent.com/25971765/152276073-1d2d9bd4-9740-4b1e-9ffa-31e7b14a72bc.gif)
![Big-Pig](https://user-images.githubusercontent.com/25971765/152276355-8e3e6605-1412-4690-bb26-9a5ca3f4f466.gif)

**Comment by Alexcnder** [comment]
Fertilizer
![Fertil 1on1](https://user-images.githubusercontent.com/87881787/152445235-ca9fa699-a394-4e70-ad8e-1cb541b2735d.gif)
bacon!
![Bacon 1st](https://user-images.githubusercontent.com/87881787/152446816-bd0d52dc-fe00-4776-9018-a5bd7eeabb0f.png)

**Comment by Sarapico** [comment]
![pixil-frame-0 (1)](https://user-images.githubusercontent.com/98893182/152795934-92072e93-e51e-4d16-aa5a-5587193b07c7.png)![pixil-frame-0 (2)](https://user-images.githubusercontent.com/98893182/152795950-b1ef5b0a-d15a-4562-8d61-71f68ad08681.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/98893182/152795983-ec709ffa-a904-447b-baac-b37045973a8e.gif)
![pixil-gif-drawing](https://user-images.githubusercontent.com/98893182/152796007-4ffb8e61-972c-4c9b-9905-789c1b1e2dcd.gif)

**Comment by cambrios1** [comment]
Manure
![Manure-1px](https://user-images.githubusercontent.com/98171636/156369692-36dde752-f127-4bf3-b8f9-235b3eec4bdf.gif)

![Manure-big](https://user-images.githubusercontent.com/98171636/156369712-63164a88-a0fc-46c5-bbe7-4e911f4d30b9.gif)

![ingamemanure](https://user-images.githubusercontent.com/98171636/156369871-6965d6ae-609b-4e1a-91fa-3ed48a170743.gif)

**Comment by Netherzapdos** [comment]
**Raw Asset (Bacon)**
![Sprite-0004](https://user-images.githubusercontent.com/101855553/159021218-e48d2763-2cc6-40c9-95fb-6c52aafd1589.gif)

**Enlarged** 
<img src="https://user-images.githubusercontent.com/101855553/159021218-e48d2763-2cc6-40c9-95fb-6c52aafd1589.gif" width="90" height="60">

**In-game Preview**
https://user-images.githubusercontent.com/101855553/159026248-0fe40895-fa8d-430e-8b95-90373f1c0f85.mp4

**Polygon Address**

> 0xBE6f742Fa865F94902D0a49CC12F23FDb2C5AE68

Note: This is my first time submitting so I'm not sure yet how to effectively enlarge small gifs without losing quality. Still learning my way around animated pixel art! :)

**Comment by Aestnelis** [comment]
Single pig/ Pig in Mud/ Manure/ Bacon
![lilpig](https://user-images.githubusercontent.com/98103679/164886828-39b60b31-444d-4950-920a-53e9ec130e2e.gif)
![bigpig](https://user-images.githubusercontent.com/98103679/164886833-ed58edd7-36c7-41dd-8930-27b5f7cbc289.gif)
![Sunflowerpig](https://user-images.githubusercontent.com/98103679/164887050-39d62049-ccd3-4c6a-9945-48e2c4b1b0e4.gif)

![lilpngpigbaconmanuremud](https://user-images.githubusercontent.com/98103679/164886842-18be8975-f2fd-4899-8977-dc5adad89b95.gif)
![bigpngpigbaconmanuremud](https://user-images.githubusercontent.com/98103679/164886848-c25ef92b-96cd-4893-8f60-d47730c74e98.gif)
![sunflowerpngpigbaconmanuremud](https://user-images.githubusercontent.com/98103679/164886855-0cfd1688-3b6e-42e1-8e1f-6079f44e6f80.gif)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
