### ISSUE TITLE
[PROPOSAL] Planting, Stamina, types of cultivation and gameplay.

### ISSUE THREAD

**Issue by Andreivv** [sunflower-land/sunflower-land#197]
**I hope I posted it working correctly, as I don't quite understand how this site works.**

The game needs a necessary evil.
I openly agree with this proposal and add a small detail: The blessed flour.
I believe that one way to work with exponential growth is to integrate stamina for planting AND care like watering cans or pest removal. And with the necessary plates for the construction of new plantation spaces, we could make it a little more difficult, bringing a mechanic of cost per site.

What I mean by this?
We will need to constantly manage our planted resources, not just plant the biggest resource gained per upgrade.
I believe in the structural division and game logic, when we have the need to divide the sites between the necessary resources. You won't be able to continue planting your seeds and resources if you don't have a minimum of stamina. And it comes to be retrieved with culinary dishes, items and a BED. a simple NFT acquired as we improve our earnings.
We can also assign a reward proportional to the number of real workers/goblins.

For this, we can activate an instant bonus in the harvest, if you have more than 1 cultivation, you will earn an additional reward of seeds to reduce the cost, giving opportunity to spend on Stamina resources. Maybe items like the scarecrow are great. I believe they are already on the right path in this regard.

If you have your entire farm with a single type of cultivation, in addition to losing a % of the total harvest, per harvest, it increases the chances of invaders, rats, crows, in short. You literally break the balance of cultivation. (which is very current, with all this history of syntropic agriculture)
You also proportionally increase the stamina cost for each crop. To plant 6 radishes, you spend X. To plant 6 additional radishes at the next site, you spend X+ the average items grown proportionately.
But how can we encourage this?
Putting a minimum amount needed for planting for example. (if the farmer wants, of course)

You can choose to plant cauliflower, 3 times instantly.
There must be adjacent spaces free for this.
or you can plant just one.
So for bigger farms, you will have a wider variety of resource, with different timings. This keeps the game running while chasing other resources like wood, iron etc etc etc. It also discourages those players who will only log in every 8 hours for harvesting.

Even with this mechanic, the chance of increasing the harvest reward may be higher for those who do.
Plant a pack of 3 seeds, and earn a higher average. If you want to plant the next entire site of cauliflowers, you will have a higher chance of, rather than a bonus, a penalty.

Perhaps as the game progresses, with resources of milk, honey, eggs and fruits, we will be able to assign a gradual stamina recharge, recovering a part of this resource passively.
 "Eat an omelet with rice and recover 50 stamina + 30% over x hours after reaching zero." In addition to burping all the food around, it also keeps a minimum of resources needed for planting and harvesting.

I really don't know to what extent all this can be useful, but in my view it can be very beneficial for the
 future of the game.

I also like the proposal to decrease gains from larger crops. according to farm level.
maybe it is possible to deploy character upgrade? Increasing daily stamina limit.
This is just an idea. But I believe that well-crafted can turn out to be very relevant in the growth of the project.

@adamhannigan  @spencerdezartsmith

**Comment by adamhannigan** [comment]
Some great detail here @Andreivv 

With these big initiatives, we also need to plan what the simplest version could be. As a team, we don't like to spend months building out a feature. We prefer to build something in a week or two, release that and slowly build on it.

What do you think the most simplest version of this idea could be? I.e. something that could be built in a week?

**Comment by Andreivv** [comment]
@adamhannigan 
We can separate the fields (as they are already being unlocked by upgrade and cost), to make a recognition variable between them, if there are 2 fields of 5 equal spaces, cut the reward, if you have a greater variety of seeds than the amount of available fields, (3 different types for 2 fields) we compare and enlarge the final reward, maybe split between the total fields.

I work with my head on ideas, but I want to learn to program as soon as possible. So I need your logical mindset to see this working or not.

**Comment by Andreivv** [comment]
@adamhannigan 
After a good shower I had a good idea. (here in the south of Brazil it's absurdly hot o.o)

For every 1 additional planting, equal to the previous field (set of 5 farming spaces) increases the chance of X% of the goblin returning asking for more soup. Since you're not properly taking care of the land he gave so lovingly to you.

So the more monocultures you have, the greater the chance of it appearing again. This creates the need to continue producing food. It diversifies the gameplay, gives you a good reason to differentiate your crops, and it's fun too.

**Comment by silici0** [comment]
I think you can start the games as it is right now and implements mechanics on the future, NFT mechanics, group planting to bonus and penalty for disorder planting. Maybe a weather bonus and setback to burn tokens, a lot of possibilities :)

**Comment by adamhannigan** [comment]
@Andreivv I've heard it is very hot in Rio Grande do Sul at the moment. Lots of heat, rain and no beach :( 

The idea of the Goblins returning is actually great 👌 It keeps players returning to planting earlier crops.

Would you mind drawing a diagram around how the simplest version of this would work? It would be good if you can focus on  just one mechanism in this diagram so it is clear how the fundamentals would work.

**Comment by Andreivv** [comment]
> @Andreivv I've heard it is very hot in Rio Grande do Sul at the moment. Lots of heat, rain and no beach :(
> 
> The idea of the Goblins returning is actually great 👌 It keeps players returning to planting earlier crops.
> 
> Would you mind drawing a diagram around how the simplest version of this would work? It would be good if you can focus on just one mechanism in this diagram so it is clear how the fundamentals would work.

 Today we hope make some history on this game <3 
 i hope u understand all, any questions just send me a reply. 
And it's raining! for good õ/ 
Please don't laught, or do. oIHAEHIEHI 
it is the best and fast i can do. 
thanks for your patience. 


![diagram kkkkkk sorry](https://user-images.githubusercontent.com/97338003/151445551-45d9941f-da13-4dbb-ad72-7e0e61afe9b9.png)
![Sorry again kkkk](https://user-images.githubusercontent.com/97338003/151445560-3f200c4f-e6d4-41bb-85a7-4054828f2ca1.png)

**Comment by adamhannigan** [comment]
The team has taken on some of the progress + skill based into our beta. Great feedback 👏 

Closing for now until we have time to expand the current skill + stamina ideas
