### ISSUE TITLE
[PROPOSAL] Wheat, Scarecrow + Flour

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#198]
This proposal explores how wheat would fit into the Sunflower Land Economy. Wheat will be considered an **exotic** crop that is hard to gather and used in rare treats and recipes.

**How to unlock the wheat seed?**

Wheat is an exotic crop that players would unlock after they have harvested beetroots. Once a player has collected 20 beetroots, they will be able to craft **Beetroot Dip** and trade this with a Goblin to unlock Wheat seeds.

## Wheat

_Prices are based on initial game prices_

Buy Price - $1
Sell Price - $5
Time to Grow - 3 days

## Scarecrow NFT

Crafting a scarecrow enables users to grow Wheat 3x faster.

<img width="200" alt="Screen Shot 2022-01-26 at 5 42 59 pm" src="https://user-images.githubusercontent.com/11745561/151243828-8f1f9320-2109-4e68-918f-66c28fb7837f.png">

Players will first need to earn wheat before they can craft it.

## Flour

Flour will be used in sweet recipes and rare NFTs

<img width="199" alt="Screen Shot 2022-01-26 at 5 44 10 pm" src="https://user-images.githubusercontent.com/11745561/151243981-ae95fd1c-180a-4cf5-a705-f226207c002d.png">

## Sunflower Cake

A rare NFT (Supply 100-200) that will be crafted to celebrate the game. It requires:

- 50 SFL
- 10 Flour
- 10 Eggs

Designed by Mr_Findlay on Discord 👏 

![cake](https://user-images.githubusercontent.com/11745561/151367030-1b6ecc4c-57f6-417a-99ad-5eb5d7ce1951.gif)

**Comment by BigKongJosh** [comment]
![Pancake](https://user-images.githubusercontent.com/98506626/151368818-a4b390ca-89ea-4260-bc29-9724cdf68043.png)
Make Pancakes using Eggs, Flour and Honey

**Comment by kimberlite07** [comment]
Was wondering what the sunflower cake nft will be. I hope it will have utility and not just as a decorative nft. :)

**Comment by adamhannigan** [comment]
> Was wondering what the sunflower cake nft will be. I hope it will have utility and not just as a decorative nft. :)

Any suggestions?

**Comment by BigKongJosh** [comment]
> > Was wondering what the sunflower cake nft will be. I hope it will have utility and not just as a decorative nft. :)
> 
> Any suggestions?

Perhaps you get a small gift on each anniversary of SFL? (SFL launch date)

**Comment by kimberlite07** [comment]
I was thinking it'll be better to have it monthly gift on same date like example (Jan 1, Feb 2, so on...). The gifts doesn't need to be lucrative so long as the gifts are more "felt" than having a yearly thing.

**Comment by kimberlite07** [comment]
I was thinking it'll be better to have it monthly gift on same date like example (Jan 1, Feb 2, so on...). The gifts doesn't need to be lucrative so long as the gifts are more "felt" than having a yearly thing.

**Comment by kimberlite07** [comment]
Also i think it would be better for wheat to be accessible only after the 3rd upgrade say for example radish or parsnips. It's like fourth upgrade after the 3rd one.

**Comment by adamhannigan** [comment]
> Also i think it would be better for wheat to be accessible only after the 3rd upgrade say for example radish or parsnips since it is an exotic crop making it harder to gather. It's like fourth upgrade after the 3rd one.

Now we need a recipe for radishes, any ideas?

**Comment by kimberlite07** [comment]
> > Also i think it would be better for wheat to be accessible only after the 3rd upgrade say for example radish or parsnips since it is an exotic crop making it harder to gather. It's like fourth upgrade after the 3rd one.
> 
> Now we need a recipe for radishes, any ideas?


I was thinking instead of 20 beetroots to make Beetroot Dip as requirement for wheat, we can do 20 radishes to make Radish Dip instead.
