### ISSUE TITLE
[PROPOSAL] Bees + Honey

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#199]
This proposal explores how bees and honey will fit into the Sunflower Land ecosystem. This will be a feature that comes after crops, chopping and mining. It will be good as a community to start designing the mechanics of this feature.

Artwork is supplied by BigKong on Discord - Amazing work ❤️ The first queen bee + bee yard NFTs will be going your way.

## Bees

You can buy bees using the Sunflower Land token. You cannot transfer these between farms.

Price: 1 SFL

<img width="10" alt="Honey_Bee" src="https://user-images.githubusercontent.com/11745561/151244861-7ba9a643-bd20-43a8-b026-165eef6cd83a.png">

## Honey

Honey will be used in a range of different recipes. It cannot be sold for SFL.

![Honey](https://user-images.githubusercontent.com/11745561/151244928-4460fe27-9933-448e-8431-3b37a1cae3bb.png)

## Queen Bee NFT

If you own the Queen Bee, you will earn an extra 5 bees per week.
 
<img width="10" alt="Queen_Bee" src="https://user-images.githubusercontent.com/11745561/151244637-91894e7a-012a-4962-b4a5-0fbd747dfc2a.png">

Price: 100 Honey + 50 SFL

## Bee Hive

Each day you will be able to click on your Bee Hive to harvest your honey. For each bee you own, you receive 1 piece of honey.
![Bee_Hive](https://user-images.githubusercontent.com/11745561/151245071-37e9571f-ee6e-4455-ab98-ea62785106b7.png)

## Bee Box NFT

A Bee Yard NFT produces 3x the amount of honey each day.

![Bee_Box](https://user-images.githubusercontent.com/11745561/151245203-5b54a769-cf27-41bd-8879-e433ed790e9e.png)

Price - 50 Honey, 50 wood, 50 SFL

**Comment by soteleon** [comment]
The art is superb!

**Comment by zeldamajora** [comment]
great proposal

**Comment by Ramtin9** [comment]
Lets say i have 100 SFL and buy 100 bees. Then i will get 100 honeys per day and won't need to bother and provide the Queen Bee NFT or even the Bee box NFT!
These NFTs must be requested due to daily tasks or to produce something like honeycomb to access other lands and features.
Unless you require a lot of honey to those recipes.

What if:

We buy hives for 5 SFL (maximum 3 hives per farm)
 Each hive will hold up to 100 bees
 Each bee will be 0.5 SFL
 Every 5 bees produces a single honey per day but they die a week later and need to be bought and replaced again.
 If the Queen Bee is provided, the bees won't die and 5 more bees will be added to the hive every week (until the number of bees reaches 100 per hive)
 When the hive reaches 100 bees, the bees will be able to produce a perfect honeycomb with some honeys and sunflowers which is needed to access new resources.
 In addition, each 100 beehives will plant a random crop near it every day by pollination.
 Having a Bee Box will enable you to Pollinate and make honey 2× a day.

**Comment by kimberlite07** [comment]
> Lets say i have 100 SFL and buy 100 bees. Then i will get 100 honeys per day and won't need to bother and provide the Queen Bee NFT or even the Bee box NFT! These NFTs must be requested due to daily tasks or to produce something like honeycomb to access other lands and features. Unless you require a lot of honey to those recipes.
> 
> What if:
> 
> We buy hives for 5 SFL (maximum 3 hives per farm) Each hive will hold up to 100 bees Each bee will be 0.5 SFL Every 5 bees produces a single honey per day but they die a week later and need to be bought and replaced again. If the Queen Bee is provided, the bees won't die and 5 more bees will be added to the hive every week (until the number of bees reaches 100 per hive) When the hive reaches 100 bees, the bees will be able to produce a perfect honeycomb with some honeys and sunflowers which is needed to access new resources. In addition, each 100 beehives will plant a random crop near it every day by pollination. Having a Bee Box will enable you to Pollinate and make honey 2× a day.


I don't quite get why hives need to be bought. I think it's just a representation of the bees in-game. So I think no need to buy them, just the bee yard nft.

 I also assume that bees have unlimited supply just like the cows and pigs. So to control the growing supply, 
i agree with your proposal that they may die off after a certain number of days (which is also the usual case irl). Although, I think it's necessary they still die even with the queen bee. It's incentive of producing 5 bees per week is already okay.


As for the bee yard, I also think x3 is too much, no? Maybe x2 is fine already? Also I like @Ramtin9's idea of pollination as well. Maybe we can add that a bit later, I suppose it'll be quite complex (Was thinking it can go have something to do with the greenhouse that was proposed in the chat if i remember correctly).


Questions to @adamhannigan:

1. What will be the supply for the bee nft and bee yard nft?
2. Will the queen bee be able to breed more queen bee nft like the bull or will it's supply be hardcapped?
3.  Can we adjust the number of produced honey per bee? Maybe instead of one honey per day, one honey every two days? [Though, maybe we can also just adjust the ingredient ratio for the recipes to balance out supply/demand]

**Comment by Ramtin9** [comment]
> > Lets say i have 100 SFL and buy 100 bees. Then i will get 100 honeys per day and won't need to bother and provide the Queen Bee NFT or even the Bee box NFT! These NFTs must be requested due to daily tasks or to produce something like honeycomb to access other lands and features. Unless you require a lot of honey to those recipes.
> > What if:
> > We buy hives for 5 SFL (maximum 3 hives per farm) Each hive will hold up to 100 bees Each bee will be 0.5 SFL Every 5 bees produces a single honey per day but they die a week later and need to be bought and replaced again. If the Queen Bee is provided, the bees won't die and 5 more bees will be added to the hive every week (until the number of bees reaches 100 per hive) When the hive reaches 100 bees, the bees will be able to produce a perfect honeycomb with some honeys and sunflowers which is needed to access new resources. In addition, each 100 beehives will plant a random crop near it every day by pollination. Having a Bee Box will enable you to Pollinate and make honey 2× a day.
> 
> I don't quite get why hives need to be bought. I think it's just a representation of the bees in-game. So I think no need to buy them, just the bee yard nft.
> 
> I also assume that bees have unlimited supply just like the cows and pigs. So to control the growing supply, i agree with your proposal that they may die off after a certain number of days (which is also the usual case irl). Although, I think it's necessary they still die even with the queen bee. It's incentive of producing 5 bees per week is already okay.
> 
> As for the bee yard, I also think x3 is too much, no? Maybe x2 is fine already? Also I like @Ramtin9's idea of pollination as well. Maybe we can add that a bit later, I suppose it'll be quite complex (Was thinking it can go have something to do with the greenhouse that was proposed in the chat if i remember correctly).
> 
> Questions to @adamhannigan:
> 
> 1. What will be the supply for the bee nft and bee yard nft?
> 2. Will the queen bee be able to breed more queen bee nft like the bull or will it's supply be hardcapped?
> 3. Can we adjust the number of produced honey per bee? Maybe instead of one honey per day, one honey every two days? [Though, maybe we can also just adjust the ingredient ratio for the recipes to balance out supply/demand]
> 
> Edit: Kinda realized x3 is okay. Realized the bee yard is expensive (plus if you guys consider the bees dying after x days)

Thanks. I came up with other options too:

 Each bee will cost 0.02 SFL
 Every 5 bees(1 SFL) produce a single honey per day but they die three days later(max 3 honeys per 5 bees) and need to be bought and replaced again.
 If you don't have 5 bees and lets say you have 3, they won't make honey or die and stay still.
 [Or we can skip the last phrase and make it 1 honey per bee(1 SFL) per day]
 If the Queen Bee is provided, bees won't die 'till a week(7 honeys) and 1 new bee will be added to the hive every week(dies after 7 honeys product and will be replaced with a new bee)
 Also we can craft more Queen Bees.
 When the hive reaches for example 50 bees, they will be able to produce a perfect honeycomb(when needed) with some honeys and sunflowers to access new resources(for example to goblins so they let us access new areas)
 In addition, a 50 beehive will plant a free random crop near it every day by pollination
 More QB you craft more Pollination will happen during the day(if you have 3 QB and 50 bees, you get 3 free random crop a day)  
 Having a Bee Box will enable a 50 beehive to Pollinate every 12hrs and make honey 2× a day but it has to be limited 
 With more honeys have been made we craft more Queen Bees until we get 50 stable bees everyday
 However we might find ourselves with a lot of honeys in the end, for that we can think of other ways to burn them and earn something else, for example when we craft the perfect honeycomb that would allow us to access new lands, we face with animals that are in love with honey(like i found out on google: Bears, Skunks, Raccoons, Opossums, Honey Badgers) And if you don't provide them honey they will hostage one of your QBs time to time and maybe kill them.
with providing they each will give us some features instead...

**Comment by adamhannigan** [comment]
@Ramtin9 @kimberlite07 Some great discussion points.

I would like to call out the idea of the bees dying. This is great as it helps keep supply low and makes the resources scarcer (an aspect we want in the game).

I am all for reducing the rate of collection as well :) 

I think we cap the amount of hives per farm, but the more you expand your farm the more hives you can grow. This keeps people focussed on one account instead of multi account :)

**Comment by Gvstav0** [comment]
- Hello, I'm bringing some ideas for the core mechanics of bees. I did a little research on how things work in real life as a basic starting point.

- In order begin to beekeeping, you will need a natural hive. To acquire this hive we will need to produce a recipe and do a favor to the goblin (quest like). With that done  the goblin will look for a hive into the forest.


- This hive can be inhabited by a maximum number of bees that will produce honey. 

- With a  certain number of bees, a hive is capable of producing a royal jelly that will feed a specific larva that will become a queen bee. (I believe it has requirements besides the number of bees and resources for the production of the royal jelly -> queen bee. Time can be an important factor needed to produce it, as bees produces different things throughout their  lifespan)


 -      (the next topic has math and I'm pretty unsure) 
-      Queen bees have a much longer life cycle than other bees. The queen will be able to produce +/- enough bees to maintain a hive. I don't know if when the queen dies the quest should be done again. 


- For the bee box you will need: beehive + wood + iron. The bee box can support more bees and they will produce a higher % of honey. 


 -  The bee box can also gather surplus wax. (according to specialists, the production of wax is equivalent to 2 - 3% of the total honey produced. 
 
-  Wax can have many use cases. For example, it can be used to produce fuel for lamps (goblins and humans need to see in the dark of a cave), or maybe even in a war wax might be useful.


- To finish I want to say that would be fun to have  some RNG into bees lifespan. I would like to hear more perspectives

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
