### ISSUE TITLE
[BUG] Rounded values on cooking.

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#1993]
## Summary of Bug

This rounded values on cooking are confusing us. While was cooking i didn't know that I wouldn't have enough resources for the new one and planted something lasting. Could you please check it?

1. TODO

## Expected Behavior

Something was proposed by @Myth727 on #1862

![image](https://user-images.githubusercontent.com/74167741/210964654-d6aeee88-d506-4bc1-a636-6fce69524b46.png)

## Actual Behavior

Rounded values on cooking are confusing UI.

## Screenshots

![image](https://user-images.githubusercontent.com/74167741/210962864-ce1296ac-bbed-4b2f-9260-c934ccf000c3.png)

![image](https://user-images.githubusercontent.com/74167741/210962300-c78a81d7-43d2-487a-b9e9-2f1b94dc9ed7.png)

**Comment by Myth727** [comment]
@future2back I'd one this as the pull request is already submitted #1948 

Thanks for looking out tho :)
