### ISSUE TITLE
DOG - Artists, community, help us make our little dog character better!

### ISSUE THREAD

**Issue by defido** [sunflower-land/sunflower-land#200]
![defido_sunflower_farmers](https://user-images.githubusercontent.com/95591037/151259913-f688a791-a7dc-422e-a643-654a9a0e8b2a.jpg)

Hello, we are making a character to be in game, it is a dog farmer. Just for fun, as we love the project. Please let me know if you have feedback.

We are going to:

Change the skin colour, make the hat bigger, turn the character to fit the current style of art, round the head.

Current size is 16x16, please let me know if we can make it bigger, as we wanted to add a fork :)

If there are any artists who think they could make an animated dog version better, please do! Or DM me and let's talk, we can pay for you to help us, I want to make a great sprite for the Defido the dog character :D

**Comment by defido** [comment]
![Defido FInal24](https://user-images.githubusercontent.com/95591037/151262032-32638e66-7f5c-4f59-a972-306a8ea7f57b.jpg)

The art style was to follow our logo + farmers overalls and a straw hat, but we can work on making it more refined, look forward to community input!

**Comment by benaxol12** [comment]
Hi Defido!
![defido 68x88 gif](https://user-images.githubusercontent.com/98098031/151317394-3ba45841-70fd-478d-a19a-1953061ee222.gif) 
17x22 is original version. (I increased the size for preview)

**Comment by defido** [comment]
> Hi Defido! ![defido 68x88 gif](https://user-images.githubusercontent.com/98098031/151317394-3ba45841-70fd-478d-a19a-1953061ee222.gif) 17x22 is original version. (I increased the size for preview)

Awesome :D Look at this little head bob!

**Comment by defido** [comment]
![1-2](https://user-images.githubusercontent.com/95591037/151911880-552f534f-fa98-49ca-8a14-e1a27d5865b2.png)
![2](https://user-images.githubusercontent.com/95591037/151911885-737e289b-5614-42da-85e0-e0347ae8d5c0.png)

Here's what we came up with. Not animated. :D

**Comment by adamhannigan** [comment]
> ![1-2](https://user-images.githubusercontent.com/95591037/151911880-552f534f-fa98-49ca-8a14-e1a27d5865b2.png) ![2](https://user-images.githubusercontent.com/95591037/151911885-737e289b-5614-42da-85e0-e0347ae8d5c0.png)
> 
> Here's what we came up with. Not animated. :D

This is super cute!

**Comment by defido** [comment]
> > ![1-2](https://user-images.githubusercontent.com/95591037/151911880-552f534f-fa98-49ca-8a14-e1a27d5865b2.png) ![2](https://user-images.githubusercontent.com/95591037/151911885-737e289b-5614-42da-85e0-e0347ae8d5c0.png)
> > Here's what we came up with. Not animated. :D
> 
> This is super cute!

Thanks Adam, now we just gotta animate the little fella.
