### ISSUE TITLE
Hi .Faced with such a problem a month ago I went into the game there was a window with a ship, moved not clear where and there I can not normally land and earn, how on my main land tell me how to move back ? give feedback to my email ignatovdavid681@gmail.com

### ISSUE THREAD

**Issue by Devid14881** [sunflower-land/sunflower-land#2005]
## Summary of Bug

Provide a brief summary of the bug you found.

## Steps to Reproduce

Provide detailed step-by-step instructions for how this bug can be reproduced.

1. TODO

## Expected Behavior

Provide a description of what you expected to happen.

## Actual Behavior

Provide a description of what actually happened.

## Screenshots

**Device Information (please complete the following information):**

- Device: [e.g. iPhone6, Pixel 6a]
- OS: [e.g. iOS, Linux, Windows, Android]
- Browser/App [e.g. firefox, safari, chrome, metamask mobile]

**Comment by Devid14881** [comment]
Hi .Faced with such a problem a month ago I went into the game there was a window with a ship, moved not clear where and there I can not normally land and earn, how on my main land tell me how to move back ? give feedback to my email ignatovdavid681@gmail.com

**Comment by future2back** [comment]
This is land expansion. 


Read game docs.

**Comment by adamhannigan** [comment]
The Moonseekers took over Sunflower Land and all players were forced to evacuate to Sunflower Isles on December 20th.

This was part of the gameplay. One day we hope to return to Sunflower Land once we can remove the Moonseekets
