### ISSUE TITLE
Donation animation

### ISSUE THREAD

**Issue by spencerdezartsmith** [sunflower-land/sunflower-land#201]
As part of the game onboarding we have a donation step. This interaction with the blockchain can take up to 30 seconds. I would love a gif that could be used as part of the loading screen. I am thinking we could use one of the character sprites and they could be rolling a coin to a world globe or something along those lines?

Ideally this animation would be running horizontal so it would fit inside a loading modal. Ideas?

**Comment by paluras** [comment]
![World](https://user-images.githubusercontent.com/98059798/151655359-f04b7e3f-b816-4d5e-b5a1-d297bddb854a.gif)

A spinning globe, working on a coin now.

**Comment by paluras** [comment]
![coin2](https://user-images.githubusercontent.com/98059798/151657967-02b4d5f8-9350-40b1-8bcb-49f3b2755c8a.gif)

**Comment by spencerdezartsmith** [comment]
Thank you @paluras! Really appreciate your work ❤️

**Comment by spencerdezartsmith** [comment]
> Thank you @paluras! Really appreciate your work ❤️

Hey @paluras ... I have been playing around with this animation and I am wondering if we can maybe switch up the color palette a little so that it aligns with the app colors a little more. See this screenshot I have attached. See how the blues and greens are a little off?
<img width="593" alt="Screen Shot 2022-02-01 at 3 52 34 pm" src="https://user-images.githubusercontent.com/17863697/151914796-76b22c74-92d5-4bce-8a0b-8bc8a48a4f68.png">

**Comment by paluras** [comment]
> > Thank you @paluras! Really appreciate your work ❤️
> 
> Hey @paluras ... I have been playing around with this animation and I am wondering if we can maybe switch up the color palette a little so that it aligns with the app colors a little more. See this screenshot I have attached. See how the blues and greens are a little off? <img alt="Screen Shot 2022-02-01 at 3 52 34 pm" width="593" src="https://user-images.githubusercontent.com/17863697/151914796-76b22c74-92d5-4bce-8a0b-8bc8a48a4f68.png">

 Working on it right now.

**Comment by paluras** [comment]
![image](https://user-images.githubusercontent.com/98059798/151925675-ac7705bf-3c41-4b6e-b920-7d77d5c748f1.png)

On the right is with the new colors.

**Comment by cambrios1** [comment]
![donation](https://user-images.githubusercontent.com/98171636/151979572-8e68978a-c8bc-4487-bdc6-57102bd0a4c8.gif)

**Comment by Le-Marquis** [comment]
> @spencerdezartsmith Something like this? ![donation](https://user-images.githubusercontent.com/98171636/151979572-8e68978a-c8bc-4487-bdc6-57102bd0a4c8.gif)

nice :)

**Comment by defido** [comment]
> @spencerdezartsmith Something like this? ![donation](https://user-images.githubusercontent.com/98171636/151979572-8e68978a-c8bc-4487-bdc6-57102bd0a4c8.gif)

Add a coin, make it a banker lol. I dunno. It's nice though.

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith Something like this? ![donation](https://user-images.githubusercontent.com/98171636/151979572-8e68978a-c8bc-4487-bdc6-57102bd0a4c8.gif)

This is great too! I will play around and see which one works out!

**Comment by cambrios1** [comment]
Let me know if you need any changes.

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith Something like this? ![donation](https://user-images.githubusercontent.com/98171636/151979572-8e68978a-c8bc-4487-bdc6-57102bd0a4c8.gif)

Hey @cambrios1 would you be able to make the globe smaller? Maybe like 1/3 smaller than it is currently?

**Comment by cambrios1** [comment]
@spencerdezartsmith yes! working on it now.

**Comment by cambrios1** [comment]
@spencerdezartsmith how's this?
![Donation-Animation-smaller](https://user-images.githubusercontent.com/98171636/152642291-0d54c894-7108-4ede-99e1-4e00c53c6c51.gif)

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith how's this?
> 
> ![Donation-TP](https://user-images.githubusercontent.com/98171636/152642933-3977ed4f-ae51-4da4-840e-ad1f0cb1ba21.gif)

This is a better size but I think the goblin needs a longer runway. Because if I make this the full length of the modal the scale increases a lot. If I keep it this size then the goblin is running out of thin air. See images.

Original size. 
<img width="508" alt="Screen Shot 2022-02-06 at 12 24 40 pm" src="https://user-images.githubusercontent.com/17863697/152664540-f99f7918-409e-4c69-96db-c5dfec3bf877.png">

Full width.
<img width="507" alt="Screen Shot 2022-02-06 at 12 25 00 pm" src="https://user-images.githubusercontent.com/17863697/152664553-17eccb2d-0dfa-4c39-afbb-1a2117dfb3e8.png">

If we could just make the gif wider but the height the same we should be good.

**Comment by cambrios1** [comment]
Ahh...gotcha. This one's 480px wide.
![Donation-Small-Long](https://user-images.githubusercontent.com/98171636/152673813-83f2fd12-fe77-4bb7-81a5-62841045a0ec.gif)
