### ISSUE TITLE
Move the art style away from the SunLand

### ISSUE THREAD

**Issue by defido** [sunflower-land/sunflower-land#202]
I am not sure if this has been brought up, but I think the original designer is not impressed with his art style being used. 

From seeing the incredible animations & art coming from some of the community members, would it not be better to do a quick community art direction to move away from the original artist?

https://danieldiggle.itch.io/sunnyside

Maybe it's too big of a task?

**Comment by BigKongJosh** [comment]
This has been discussed to death already. The game is allowed to use the art from Daniels pack for the base gameplay. It's the art for NFTs that will not be using any of Daniel's work. Also, the developers want the art style to be similar to sunnyside world.

**Comment by defido** [comment]
> This has been discussed to death already. The game is allowed to use the art from Daniels pack for the base gameplay. It's the art for NFTs that will not be using any of Daniel's work. Also, the developers want the art style to be similar to sunnyside world.

Argh. Got it. Didn’t see it had been widely discussed. But had seen the frustration from the artist on Twitter. 

I’ll close this out then. 😎
