### ISSUE TITLE
Fruit Seeds Missing!

### ISSUE THREAD

**Issue by Myth727** [sunflower-land/sunflower-land#2031]
When you guys have the time please peak over farm 26, I originally purchased 11 seeds per fruit before they all got locked in an update. Once fruit trees could be planted I collected 5 dead pieces of wood. Then planted 2 berry plants, 2 apple trees and 1 orange tree. Next day all my remaining fruit seeds disappeared and I had to start fresh with buying them. Take all the time on looking into this. Just wanted to make yall aware. 

Also mod badge gives 35% more wood. But does not work on wooden shrub or fruit trees when getting removed. 

![Screenshot_20230112_002756_Firefox](https://user-images.githubusercontent.com/96928557/212217558-6f06a975-7ad6-4689-b0e4-925d34cb308e.jpg)

Last thing on my mind is a typo/missing word in the Bumkin Quest description. 

"Do you to wear Bumpkin Wearables that show off your amazing fruit picking skills?"

Maybe it was supposed to say...

Do you want to wear Bumpkin Wearables that show off your amazing fruit picking skills?

![Screenshot_20230112_204215_Chrome](https://user-images.githubusercontent.com/96928557/212217974-25c40236-4b15-440f-bfec-4bc9aae08f00.jpg)

Ok I'll leave you guys with that for the moment,  enjoy

**Comment by mGranTY** [comment]
@c-py changed the seeds value type from wei to ether, this means that some seeds were burned, there was a talk about returning them. We are still looking into it.

As for the mod badge, i need to talk with a core dev to confirm if the boost should apply in fruit trees or not.

**Comment by Myth727** [comment]
Thanks, as I'm not in discord I don't get to see these talks. So I gotta make sure to take my notes and post then when possible.  I would suggest make the mod badge do what it says... +35% wood, would be odd to do anything else for it. I also posted a suggestion on discussions related to change axes ro shovels for digging up the tree roots. This will help burn more resources, atleast when it comes to foreman holders like myself.

**Comment by Myth727** [comment]
@Polysemouse @mGranTY @adamhannigan any updates on these issues?

**Comment by Polysemouse** [comment]
@Myth727 We are still waiting for devs for the updates.

**Comment by Myth727** [comment]
I'd love to close this out, as well as see other issues closed so we look like we are making progress as a community. @adamhannigan please take the time to address some of these things :) <3

**Comment by future2back** [comment]
Hello friend @Myth727, can you tell us if this issue has been resolved?
Thank you.
