### ISSUE TITLE
[BUG] food impossible to make in the grub shop

### ISSUE THREAD

**Issue by NomiceBinocle** [sunflower-land/sunflower-land#2053]
![652DBC9D-3DFF-4C45-A6E4-DEC5469B83DE](https://user-images.githubusercontent.com/121914676/213042821-b311df6d-c389-4f1c-a010-9892c38e64ba.jpeg)

**Comment by therocco** [comment]
I'm pretty sure you sell the food to the grurb shop that you make on your island

**Comment by NomiceBinocle** [comment]
> Je suis à peu près sûr que vous vendez la nourriture au magasin de grurb que vous faites sur votre île

yes of course but this week several players had the pancake which is impossible to craft because the honey is not available

**Comment by therocco** [comment]
> > Je suis à peu près sûr que vous vendez la nourriture au magasin de grurb que vous faites sur votre île
> 
> yes of course but this week several players had the pancake which is impossible to craft because the honey is not available

We'd have to look through the source code to confirm but I suspect those are players with a beta pass testing a new feature which could make that item available like they did with fruit trees a few weeks ago. That is just a hypothesis however.

**Comment by future2back** [comment]
The issue has been resolved, this topic can be closed.

Thank you.
