### ISSUE TITLE
[PROPOSAL] Tractor

### ISSUE THREAD

**Issue by Alexcnder** [sunflower-land/sunflower-land#206]
This proposal explores how tractors can be used

Please help us make the tractor cool

>

**Usage**

Hey All this is what Zikou and me came up withtractor 
1st Usage : "Offline Farmer"
The Tractor will auto replant seeds that were put into the "Tractor Inventory". The tractor Inventory will be limited to a 660 Seed cap. (making it neccesary to refill Sunflower Seeds every 30mins...)
Fuel/Meal:
The Meal is used to hire a goblin to work on you’re  tractor. Once served he start to burn 1 meal every 6 hours. He will harvest an replant the seeds that were put into the inventory. This could be a great thing to incentive for people to plant not so profitable plants like Parsnip. So we thought 1 Meal would be 1 Parsnip+ 1 Sunflower

2nd Usage: "Restocktractor"
A tractor NFT could have different usage such as acces to a better market place it will be available every 24h and will sell 11 random seeds for a reduced Price (Half the Price)
/wentractor
>
![Deposit](https://user-images.githubusercontent.com/87881787/156232397-6d787464-a8d7-4909-89d4-c07db11bbfad.png)

> 

**Tractor**
![New Color](https://user-images.githubusercontent.com/87881787/156229437-8fad380f-2422-4342-911b-7e52f69517b9.gif)

> 
maintenance
**wentractor**

**Comment by adamhannigan** [comment]
Thanks for sharing @Alexcnder I'm curious how the prices will change by 5%.

In the game how will we convey this to users? (i.e. are the crops bigger or the prices just update in the shop)

**Comment by Alexcnder** [comment]
> Thanks for sharing @Alexcnder I'm curious how the prices will change by 5%.
> 
> In the game how will we convey this to users? (i.e. are the crops bigger or the prices just update in the shop) 
**I would say the tractor is like a kind of lucky charm giving u a 5% chance for an extra Drop**

**Comment by Alexcnder** [comment]
What do u guys think the Supply should be

**Comment by Z1kou** [comment]
Hello Alexcnder , I really like the idea of the tractor being able to plant everything , My humble suggestions : 

-adding a goblin on top of it and replacing fuel with a certain meal (To add more usage for the cooking section )
-For me i think it wont be interesting to give a player a tool to automatically plant everything when they are offline that would beat the feel of the grind and engagement u have when u log on every certain time to plant and manage your farm ( though its hella convenient ) , or add a debuff to that like ( crops farmed through a tractor would have a lower yield or quality reducing there price by a certain percentage ) ,
-A tractor NFT could have different usage such as acces to a better market place ? ( every X hours or days u can use ur tractor to travel to town and buy seeds with a reduced price )

I have other ideas but i would like to discuss with u these first what do you think @Alexcnder

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
