### ISSUE TITLE
[PROPOSAL] Sunflower Fair

### ISSUE THREAD

**Issue by ExtremeCheddar** [sunflower-land/sunflower-land#209]
This proposal looks to grow the Sunflower Metaverse.

We are a small group of friends who have put together an idea to build out our own little area within the Sunflower Metaverse. We would like to bring to life what we are currently calling the Sunflower Fair!

The Sunflower Fair is just that, a fair! Filled with carnival games and competitions that the community of Sunflower Land can participate in. We would look at keeping the art style and flavour of Sunflower Land and bring the fair to the community in the form of games of chance as our first offering.

The initial offering would be the Farmers Wheel. This is something that we can put together within a short timeframe and would be the foundation of the fair. From there we can then build upon that and really bring the fair to life.

The Farmers Wheel would use the Sunflower Land token for gameplay.

### Sunflower Fair – Farmers Wheel
1. User begins by connecting their Metamask wallet to the platform via Polygon (auto-connection for returning users)
2. A deposit/withdrawal screen (not shown) allows the user to deposit or withdraw SFF to their Sunflower Fair account
3. On the game screen the user can place their choices for the upcoming spin. Spins occur once per minute
4. Users can risk a maximum of 50 SFF on their address per 24 hour period (resets at midnight UTC)
 
![fair1](https://user-images.githubusercontent.com/24790353/152065510-a8d8f27a-5a6e-4673-87ea-a38f5f1a2c47.png)

5. Once the countdown hits 0 the player will get taken to an in-game animated spinning wheel which will then show the results. (The below is just a rough example to give you an idea of what it might look like, odds on the wheel are not correct).

![fair2](https://user-images.githubusercontent.com/24790353/152065568-342ffcd2-eeb5-4e32-9ac1-71b0ff700c2e.png)

6. The player’s choices are graded. The player can then choose to play again or leave the fair.

### Tokenomics
There is no native token to Sunflower Fair (currently). As all wagers must be placed in SFF, this adds utility to the SFF token as it allows existing players to use their tokens within Sunflower Fair. It also means that other users from outside of the SFF ecosystem must acquire SFF tokens in order to participate, thereby adding to the use cases for SFF and improving returns for holders and LP providers of SFF.

### Pixel Artists
The one thing our team does not have at the moment is a pixel artist and we would be looking to find people from within the Sunflower Land community that we can work with to bring our project to life.

**Comment by defido** [comment]
Pixel Artists
The one thing our team does not have at the moment is a pixel artist and we would be looking to find people from within the Sunflower Land community that we can work with to bring our project to life.

This would be very good, pixel artist/animator, think it's a high priority. Community, you can be it!

**Comment by adamhannigan** [comment]
@ExtremeCheddar I love this idea.

I think a native token to the fair makes sense. You can buy these with SFL and then exchange them for prizes (rare items or NFTS).

Have you though about what the tokenomics for this would look like?:
- What is the exchange rate from SFL -> token
- What is the utility of the token (what can you buy with it)
- How much time does a user need to spend to earn enough tokens for an item.

**Comment by AncientHorse** [comment]
@adamhannigan @ExtremeCheddar Would coins be minted if a player wins and burned if they lose?

**Comment by ExtremeCheddar** [comment]
@adamhannigan 
Our initial thoughts were not to spin up a new token, mainly because we dont have much experience in that area at the moment and just to make it easier for us to get a product out there for the community to use. The amount of effort into a new token which has very little utility to start with (used to play on the Farmers Wheel) probably isnt worth it, but we are defintely open to having our minds changed.

Our thought process was the get the Farmers Wheel up and running with players using SFL to play, and once we had ironed out all the kinks and it was working correctly this would be enough time to see how successful the project is and whether people will actually use it, as well as work on what utility our own token could have and other ways we could use it in games and events we continue to develop for Sunflower Land.

@AncientHorse 
In regards to minting and burning of SFL, we would initially hold a balance of SFL. When players win they deduct from our balance, and when they lose they add to our balance. On a regular basis, perhaps weekly, we would reconcile to see if the wheel made or lost SFL for the week. If there was a loss, we would carry that loss over cumulatively as an amount that needs to be made up for, until the balance is back to break even. If there is a profit, we could distribute the SFL as such (percentages not final and open to feedback):
- 30% gets burnt
- 16% gets sent to our development team
- 4% get sent to the Sunflower Team
- 50% to remain in our SFL balance (initially)
  1. we need to grow the balance so that in time we can increase the SFL risked per 24 hr period
  2. as user numbers increase, we need a larger balance to offset increased volatility  
  3. if the project is successful to the point that the balance is not at risk from volatility, we could at that stage change the distribution so that some of the 50% goes to our development team and some gets burnt

**Comment by defido** [comment]
Honest question. Does this not act like a lucky dip, gambling chance kind of mechanism? Also seems really similar to the “you need to pay to play more” from candy crush. 

When the real reward and what made the game popular was the simplicity of farm to make money. 

I could be totally wrong.

**Comment by ExtremeCheddar** [comment]
@defido  yes this is a game of chance. We are looking to expand the Sunflower Land Metaverse, so trying different mechanics and making games/events that the community can play and participate in that try to be different from the main game. You dont want all the gameplay to be the same and you want to be able to play the game in different ways.

Our small team has a lot of different games and event ideas that we would love to continue to create for the community, but we needed a starting place and the Farmers Wheel seemed like a good balance of something we can do as an easier project and deliver within a reasonable timeframe

**Comment by adamhannigan** [comment]
@ExtremeCheddar Creating the underlying token is quite easy if it falls under the Sunflower Land project.

We are using the ERC1155 standard so it is as easy as choosing a unique ID for the token (e.g. the number 1002). The mechanisms can still exist for your team to get a percentage of that token.

Spin the wheel is a good MVP. I would suggest framing it in a way that is not tied to 'Gambling' - There is a whole other world of Crypto Regulation that your team would not want to enter there 😅

**Comment by AncientHorse** [comment]
@ExtremeCheddar @adamhannigan  

I urge caution.  

- Sunflower: 1/1
- Potato: 3/1
- Pumpkin: 5/1
- Beets: 11/1
- Cauliflower: 23/1
- Turnip: 47/1

This combination of odds is also known as the "Big Six Wheel" and is an unequal game of chance and has one of the highest house edges in a casino.  https://en.wikipedia.org/wiki/Big_Six_wheel

This should be disclosed in the documentation otherwise there is the possibility of disparaging complaints of "scam" and whatnot.

Given the odds, I wouldn't play this.

**Comment by ExtremeCheddar** [comment]
@AncientHorse @adamhannigan 
Hi Guys, to remove the gambling aspect out of the Farmers Wheel how about we then make it similar to planting/harvesting.(we were trying to avoid this to have different mechanics in the game)

You can play the Famers Wheel and there are two options:
1. Spin the Farmers Wheel to spend 1 SFL to return 1 SFT(Sunflower Fair Token) after a set period of time (eg 1 hour)
2. Spin the Farmers Wheel to spend 1 SFL to return either 0, 1 or 3 SFT(Sunflower Fair Token) after a set period of time (this period of time would be shorter than option 1)

This way there is a guaranteed way to earn SFT and if you feel like taking a chance or want tickets faster there is a non guaranteed way to do it. This also tries to make it slightly different than straight up planting/harvesting.

All the numbers listed above are just examples and can/will be changed. This is just to try and work out what type of gameplay would be acceptable. Once we figure this out i will post up a new proposal with more details.

**Comment by adamhannigan** [comment]
@ExtremeCheddar I like this. It is simple and we can build it out and test with players 👌 

I'm curious, what sort of prizes do you have in mind for people to spend the tokens on?

**Comment by ExtremeCheddar** [comment]
@adamhannigan 
As a team we have had some further thoughts on what we can do and below is the rough idea, if this looks good we will then put it through as a new proposal with more details.

Instead of a wheel we are thinking about a capsule vending machine with luxury items(those vending machines where you put in 20c and it spits out a plastic egg that you then open for a prize)

all numbers below are subject to change, this is just an example of what we can do.

You can play the capsule vending machine with three options:
1. Spend 1 SFL to return a capsule with 1 SFT after a set period of time
2. Spend 1 SFL to return a capsule with either 0, 1 or 3 SFT after a set period of time
3. Spend 10 SFT  for a capsule that could win luxury in-game items. Potential outcomes are:
	- Win 5 SFT
	- Win 20 SFT
	- Win 50 SFT
	- Win Sunflower Statue
	- Win Golden Egg
	- Win Christmas Tree
	- Win Chicken Coop
	
- The luxury items would be bought by our team and incorporated into the game. 
- The odds of winning a luxury item would be really low as these items can be quite expensive. 
- Different luxury items can be added/removed as they are released.
- The most common outcome by far would be Win 5 SFT
- This gives the chance of someone who might never be able to afford one of these items to get one (although chances are really low)
- There would be a hard limit on the number of times a player could use the capsule machine per 24 hours
- We can release NFTs which increase the hard limit if players are interestedAs a team we have had some further thoughts on what we can do and below is the rough idea, if this looks good we will then put it through as a new proposal with more details.

Instead of a wheel we are thinking about a capsule vending machine with luxury items(those vending machines where you put in 20c and it spits out a plastic egg that you then open for a prize)

all numbers below are subject to change, this is just an example of what we can do.

You can play the capsule vending machine with three options:
1. Spend 1 SFL to return a capsule with 1 SFT after a set period of time
2. Spend 1 SFL to return a capsule with either 0, 1 or 3 SFT after a set period of time
3. Spend 10 SFT  for a capsule that could win luxury in-game items. Potential outcomes are:
	- Win 5 SFT
	- Win 20 SFT
	- Win 50 SFT
	- Win Sunflower Statue
	- Win Golden Egg
	- Win Christmas Tree
	- Win Chicken Coop
	
- The luxury items would be bought by our team and incorporated into the game. 
- The odds of winning a luxury item would be really low as these items can be quite expensive. 
- Different luxury items can be added/removed as they are released.
- The most common outcome by far would be Win 5 SFT
- This gives the chance of someone who might never be able to afford one of these items to get one (although chances are really low)
- There would be a hard limit on the number of times a player could use the capsule machine per 24 hours
- We can release NFTs which increase the hard limit if players are interested

**Comment by adamhannigan** [comment]
@ExtremeCheddar Great idea 👌 

One suggestion is to first release your own NFTs that give utility to the SFT. It might get a bit expensive buying some of the other NFTs. The Egg/Coop/Tree were all more than 1 ETH at one point.

On the technical side, we would need to consider how to manage the off-chain state of a user's SFT balance or if this is completely on-chain. This is because when a user plays Sunflower Land they are not saving every action directly to the Blockchain, instead they perform multiple actions over a day and then they sync this to the Blockchain.

If you wish to deploy your own ERC20 token, where the team gets rewards, the best approach would be doing a completely on-chain smart contract approach. Currently our off-chain architecture won't support managing the mints/burns of other ERC20 tokens and distributing rewards to developers. 

To go the on-chain approach, your team would get more control over the token and would be easier to manage your own development lifecycle. There are a few points to consider here:
- The user must have the SFL in their MetaMask wallet (not their farm address)
- Random Number Generators are not possible purely in Smart contracts - You would need to consider integrating with an Oracle (like ChainLink) which would ensure people could not cheat the system

**Comment by ExtremeCheddar** [comment]
@adamhannigan new proposal is up https://github.com/sunflower-land/sunflower-land/issues/274
