### ISSUE TITLE
[BUG] Protected images CORS errors in local dev environment

### ISSUE THREAD

**Issue by therocco** [sunflower-land/sunflower-land#2106]
## Summary of Bug

When running a local development server there are a slew of errors in the console related to CORS issues from trying to load the protected image assets from a server without valid cross origin settings.

## Steps to Reproduce

Run the dev server and open http://locahost:3000 in your browser and view the errors in the dev console

1. TODO

## Expected Behavior

Protected image assets should be loaded through a proxy since the testnet assets server does not have appropriate cross origin settings

## Actual Behavior

Chrome throws errors due to trying to load images with invalid cross origin settings and manipulating them via `<canvas />`

## Screenshots

![Screenshot from 2023-01-26 15 38 50](https://user-images.githubusercontent.com/801056/215240422-ec9c8927-c4ad-45af-a444-7ca227edb594.png)

**Device Information (please complete the following information):**

- Device: Dell XPS 13 Plus, Dell XPS 15 9510, Pixel 7 Pro
- OS: Linux (Dell laptops), Android
- Browser/App: Chrome (Linux), MetaMask (Android)
- Version [e.g. 22]: v1.0.72

**Comment by future2back** [comment]
Hello friend @therocco, can you tell us if this issue has been resolved?
Thank you.

**Comment by therocco** [comment]
> Hello friend @therocco, can you tell us if this issue has been resolved? Thank you.

Not sure, it was an issue when I stopped playing the game and trying to contribute over the summer. Won't be available to check if it's been fixed or not for a few days due to work. Best way to check would be to just open the developer console and looks for CORS errors when loading the game locally.
