### ISSUE TITLE
[PROPOSAL] Cows / Milk / Meat

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#214]
Cows are an animal in Sunflower Land used for gaining new resources.

## Cow

Please refer to this art request - https://github.com/sunflower-land/sunflower-land/issues/195

**Requires**

- 20 SFL
- Level 4 Farm upgrade

## Milk

Example Artwork from BigKong 🏆 
![Bottle of Milk](https://user-images.githubusercontent.com/11745561/152412917-af6c8321-5a29-4f97-9d69-9d181cc351ff.png)

Each day you will be able to milk a cow for a bottle of milk. Milk will be used in crafting recipes and fuelling workers that are needed to expand land and construct buildings

## Beef

If you feed a cow consecutively for 2 weeks you will be able to **burn** it for 5 pieces of beef.

Beef is used crafting recipes and feeding Goblins.

## Bull (NFT)

A bull gives you the chance of mating with other cows/bulls. Each day you will have 20% chance that your bull has had special occasion with one of your cows.

If your bull + cow mated, there is a 98% chance that a new cow will be added. There is a 2% chance that another bull is made.

1 bull limit per farm

**Requires**

- 100 wheat (bulls are hungry)
- 5 gold (bull ring)
- 100 SFL

Initial Supply - 200
Total Supply - 200 * (0.2 per day * 3.65- each bull can product 3.5 bulls each year = **700 bulls each year**)

**Comment by AncientHorse** [comment]
@adamhannigan I like running all these ideas by my daughters, ages 8 and 11, to make sure we get their blessing.  I think we'll have to soften the language in the docs on this one though.  One thing that makes this game unique is the incredibly wide appeal for both kids and adults.  That said, this sounds great and think I need a whiteboard to start creating the crafting workflows.  :)

**Comment by AncientHorse** [comment]
Perhaps replace the word "sex" with "special occasion."  This makes it an inside joke for adults that know what it means and for the kids...it's just that...a special occasion!

**Comment by Rofrtd** [comment]
> Perhaps replace the word "sex" with "special occasion." This makes it an inside joke for adults that know what it means and for the kids...it's just that...a special occasion!

I like it too. haha

**Comment by j923sneaks** [comment]
I feel like 98% is too high, almost a guarantee. Also is 20% limited to each cow or all are considered? Even with burn mechanics i think it's better to tweak these probabilities. 

Suggestion for "special occasions"
34% nothing happens
64% cow
2% bull

Total supply description seems like it's only for a single player? each of us who has both bull and cow have 20% chance

**Comment by kimberlite07** [comment]
Also, is the price of the cow too high? It's even higher than the bull which is an NFT. Given that hard caps are in place for collecting resources, maybe we can lower the price of the cow. :)

**Comment by kimberlite07** [comment]
Oh another question. Is a farmer allowed to mint multiple bulls or is it limited to one per farm?

**Comment by AncientHorse** [comment]
Do any animals ever expire?  If the bull is a rare item but could be generated, would there eventually be so many of them they wouldn't be rare anymore?  What if bulls die after 12 months and turned into beef.

**Comment by kimberlite07** [comment]
> Do any animals ever expire? If the bull is a rare item but could be generated, would there eventually be so many of them they wouldn't be rare anymore? What if bulls die after 12 months and turned into beef.


I doubt that will happen easily. The initial supply is very low as compared to the player base. The chance of getting a bull after the special occasion is low as well (which is nice). Even if the supply will be at a thousand, it will still considered rare. 


One thing that we can implement is to place a limit for a bull/cow to produce an offspring within say a week. Say for example, the bulls were able to produce 3 calves for the week so the next time they get to produce will be already the next week.

**Comment by adamhannigan** [comment]
@AncientHorse Good call out, I have changed it to something more friendly.

@j923sneaks The idea is that we want to keep the total supply of bulls low so they remain rare. I think 500-1000 entering circulation each year is a good metric around this. What do you think?

@kimberlite07 That was a typo, it should be 20 SFL (not gold). Thanks :) One bull per farm. 

The bulls would not expire. We will explore burning mechanics for NFTs/FTs in the future but for simplicity we are keeping them fixed :)

**Comment by j923sneaks** [comment]
@adamhannigan i was thinking that the generation of cows is high, not the bulls. It's basically 20% chance to get a cow each day (98% is almost 100%), thus inflating the cow supply. but if demand for beef is high then perhaps it will offset. Maybe shorten feeding time required to burn? (e.g. from 2 weeks to 1 week)

**Comment by spencerdezartsmith** [comment]
@adamhannigan Do you think we could potentially put a limit on a bull fertility. So rather than expire, he would no longer be able to produce offspring. At which time you can burn for beef? Maybe a year? Also with the limit of 1 bull per farm, if a bull is born the farm will have more than one bull. Will it mean that only one bull is able to mate? Essentially pushing the other bull to be sold?

**Comment by spencerdezartsmith** [comment]
In regards to the 1 bull limit per farm, what happens when a bull is created through reproduction? Does that bull not factor into the 20% chance of a special occasion thus encouraging folks to sell the new bull? 

I agree that the numbers could be tweaked a little. We could drop the chance of a cow to perhaps 80% or @j923sneaks numbers were ok too. I do think that with the limited supply of bulls its unlikely to influx cows at any major rate. 

I know there was talk about expiration... maybe we could consider the idea that fertility of a bull has a expiration. Once a bull is no longer fertile then they can be burned for beef? It would need to be a term that assured that the bull circulation continued though. Would want an extinction to occur 😅

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
