### ISSUE TITLE
Minerals (Stone, Iron, Gold)

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#216]
This is a request for an improvement of the current minerals including:
- Stone
- Iron
- Gold

This includes the rocks that will be placed on the map and also the materials that are collected (e.g. Iron Ore)

**Comment by paluras** [comment]
![ores](https://user-images.githubusercontent.com/98059798/152514193-591ad89c-146b-450c-af0d-7d8f68c9fb02.png)
![image](https://user-images.githubusercontent.com/98059798/152514553-7276817c-0363-4b77-83b4-75dbbbbc350a.png)
![ores](https://user-images.githubusercontent.com/98059798/152514665-27fba7c6-4edf-4b87-a2d8-85309c5ec658.png)

I will think of more designs.

**Comment by kimberlite07** [comment]
> ![ores](https://user-images.githubusercontent.com/98059798/152515112-48a31bf2-2502-435f-a499-5839091ba36f.png)
> 
> ![image](https://user-images.githubusercontent.com/98059798/152514553-7276817c-0363-4b77-83b4-75dbbbbc350a.png) ![ores](https://user-images.githubusercontent.com/98059798/152515031-3cfe13ed-030d-4d7c-af76-4e969cb0fac9.png)
> 
> I will think of more designs.


Great designs! Maybe you can add like sparkly effect to the gold so that it'll have that gold feel more 😄

**Comment by paluras** [comment]
![SomeGolds](https://user-images.githubusercontent.com/98059798/152634794-4f3089db-38a7-44d9-8428-5662a1e641ba.png)
Day 2 of gold.

**Comment by kimberlite07** [comment]
> ![SomeGolds](https://user-images.githubusercontent.com/98059798/152634794-4f3089db-38a7-44d9-8428-5662a1e641ba.png) Day 2 of gold. Edit:Also started making rocks, i also started to hate rocks . ![image](https://user-images.githubusercontent.com/98059798/152636996-030b5a0d-686a-4e17-8c77-6325743d6d01.png)


Your gold bars are amazing! Seeing the chunk-sized, maybe it's possible that gold bits may also pop out, what do you think @adamhannigan?

Too bad you hate rocks. I kinda like them, in fact I majored in studying em back in college 😂

**Comment by paluras** [comment]
> > ![SomeGolds](https://user-images.githubusercontent.com/98059798/152634794-4f3089db-38a7-44d9-8428-5662a1e641ba.png) Day 2 of gold. Edit:Also started making rocks, i also started to hate rocks . ![image](https://user-images.githubusercontent.com/98059798/152636996-030b5a0d-686a-4e17-8c77-6325743d6d01.png)
> 
> Your gold bars are amazing! Seeing the chunk-sized, maybe it's possible that gold bits may also pop out, what do you think @adamhannigan?
> 
> Too bad you hate rocks. I kinda like them, in fact I majored in studying em back in college 😂

Thank you!
I'm just making stone rocks now,it will be easy to add some gold/silver particles to them.

(I also have to study making them now,wished i did earlier 😂)

**Comment by paluras** [comment]
![Goldstone](https://user-images.githubusercontent.com/98059798/152763452-9307e145-b174-4f20-a41f-1c818861ab02.png)
![Goldstone](https://user-images.githubusercontent.com/98059798/152763494-407f8fe7-0fad-4a23-a552-33d794fae75c.png)

![image](https://user-images.githubusercontent.com/98059798/152763885-ec1b80ee-9e59-4223-ba77-3af74e8261c8.png)

**Comment by paluras** [comment]
![iron](https://user-images.githubusercontent.com/98059798/152861079-f6a5e5a3-736f-4ec3-84c0-4f39adcaf188.png)
![image](https://user-images.githubusercontent.com/98059798/152861521-77e06b9f-0548-4592-b0d7-7e3bbd761163.png)

**Comment by kimberlite07** [comment]
These are so cool @paluras. Amazing! Although I'd have to say the gold color of the gold ore is more pale yellow than golden yellow :)

**Comment by paluras** [comment]
![iron](https://user-images.githubusercontent.com/98059798/152938529-51bb316b-1392-49f4-af10-8a140dcd0a2b.png)
![iron_big](https://user-images.githubusercontent.com/98059798/152938552-74aba12a-f274-457b-b82d-a1861393679e.png)
![Goldstone](https://user-images.githubusercontent.com/98059798/152938562-f65b58bf-2b13-42ad-ad65-3d52b9ab87fa.png)
![Goldstone_big](https://user-images.githubusercontent.com/98059798/152938571-39fbc65d-ef57-472e-b91e-eb69cc14dac0.png)

Increased the gold saturation on @kimberlite07 suggestion.

**Comment by kimberlite07** [comment]
> 

I loveee them! I hope everyone likes them too!

**Comment by paluras** [comment]
> > 
> 
> I loveee them! I hope everyone likes them too!

Thank you!

**Comment by adamhannigan** [comment]
@paluras These are great. The team will add them in this week 🤗

**Comment by paluras** [comment]
Glad i could help ❤️
