### ISSUE TITLE
[PROPOSAL] Sunflower Land SHERRIF IMPLEMENTATION

### ISSUE THREAD

**Issue by Z1kou** [sunflower-land/sunflower-land#220]
I posted this in community art , Community -ideas and im gonna post it here too since i really think this got great potential !!!
it also involves a new mechanic implementation so here it is here ! "**_I Heard some of y'all endorsing those pesky goblins wanting to give them food or what not , My gran-grandaddy once told me BOY if they aint part of the soil then make em under it with this revolver of foil_**"- SunFlower SHERIFF 

 **THE IDEA**

(I present to you an idea of the second narrative like mentioned in the AMA maybe we can choose to side with the goblins but what if we dont wanna ? what If we can do this another way? , Why not hire a sheriff and he catches the  goblines on your farm.

**THE GAME MECHANICS**
its gonna be the same fee of making a pumpkin soup with the same results but one pushes the narrative in one way and one pushes it to another like many games such as undertale choosing a pacifist or genocide  way would give u  pros/cons that are different to each other maybe if you choose to be friendly with goblins XX crops grows faster While XX gets a debuff and VICE VERSA anyways here is my idea of a SFL Sheriff in all his glory ), Ps: The art is just a quick visualisation of the idea it is very  much open to improvement i just want to know your opinion guys on the idea and if it will be a good implementation story wise to add to the richeness of the SFL world story" 

**THE USES**
1-Pushes the storyline or narrative in 2 different ways giving it good potential for the expention of the storyline of our game later .(Example: Creation of weekly events or monthly such as goblins vs Sherrif in which we could add New rewards and NFT's based on contribution)

2-When one says rewards one says sacrifices,much like the pumpkin soup that burns ressources to get , hiring a sherrif would be a great way to use the ressources that are lacking a use and making everypart of our crops usable thus giving exposure to every part of the game.

3-Using the western like great sound track of romy (Seriously that man's stuff is good xd)

4-Possibility of implementing more game mechanics that play arround sherrifs( such as land expansion, instead of buying the land from a window why not buy it by signing a contract with the authority of SSL which is in our case the sherrif giving more richnesss to the storyline again and providing another use for Land Expansion)

**Comment by Z1kou** [comment]
![PESKY GOBLINS](https://user-images.githubusercontent.com/98262339/152590945-8fb18871-a4ce-4c80-a4f9-d88ffbe93fd5.PNG)
![SHERRIFF](https://user-images.githubusercontent.com/98262339/152590949-5319e5ac-5e01-4646-b0f4-126ae713482b.PNG)

**Comment by adamhannigan** [comment]
@Z1kou Great idea. I love the idea of giving the player the choice of what path they want to go down.

Bribe the Goblins or take them out 😆 

How long would you hire a Sherrif for? (would they disappear after a certain time) - Also, perhaps they could be used to collect Goblin heads as a resource.

**Comment by Z1kou** [comment]
> @Z1kou Great idea. I love the idea of giving the player the choice of what path they want to go down.
> 
> Bribe the Goblins or take them out 😆
> 
> How long would you hire a Sherrif for? (would they disappear after a certain time) - Also, perhaps they could be used to collect Goblin heads as a resource.


-Since we would have to look at this from a fair point of view i think the sherrif would work on propotion to what kind of recipe u feed him the higher the quality the longer he works or make the timer identical to that of the pumpkin soup .

-I also really love the idea of the goblin head ressource maybe have a ressource for when u use a sherrif and another ressource for when you bribe the goblin pesks 

this ressources would then be used to craft trophies that would give an effect related to what path u took( +5% Duration of affect of either the sherrif or the soup / -5% Crafting ressources)

-Add a badge when u reach a certain use of either the sherrif or the pumpkin soup with rising rarity EXAMPLe:10usage Bronze medale , 1000usage diamond medal ( this could give u a one time effect every milestone and or gain a NFT when u reach a legendary amount ) its fun working for a hard goals with small rewards on the way to find urself at the ennd with an amazing NFT and THE RIGHT TO BRAG ABOUT IT xd

**Comment by adamhannigan** [comment]
Closing for now as it won't be implemented in the near term.

I know you have had a lot more ideas around this lately. Let's regroup in a couple months to explore how this would work with the new Sunflower Land ecosystem
