### ISSUE TITLE
[BUG] sunflower land stuck at loading and connecting 

### ISSUE THREAD

**Issue by metalshelltoe** [sunflower-land/sunflower-land#2306]
## Summary of Bug

does not go past connecting and loading screens

## Steps to Reproduce

happens after connecting wallet

1. TODO

## Expected Behavior

load the game
## Actual Behavior

stuck on the connecting and loading screens
## Screenshots

**Device Information (please complete the following information):**

- Device: iphone xr
- OS:  iOS
- Browser/App [metamask mobile]
- Version

**Comment by lp-webdev** [comment]
I'm having the same issue. Word is that it's to do with the 6.0 update and is only affecting iOS. It would be good to see this rectified because using Safari limits other aspects like making purchases. ATM I have to make purchases on my laptop.

**Comment by PALOLAX** [comment]
![5D1F0E12-F5E0-43EF-9BA1-8FAC822C8CFE](https://user-images.githubusercontent.com/105823712/224586549-5f3d228b-2770-458e-b211-addde064989e.png)
I phone 11 
Metamask 
Last version 
Same problem

**Comment by Otakriss** [comment]
Same, can't be connected to the network. Im stuck at the loading screen. 

Phone : Iphone 7 
OS : IOS 
Last update of Metamask.

i realy think  it's only for Iphone users. Iphones are so useless... Zero problems with android.

**Comment by metalshelltoe** [comment]
i just ended up accessing via pc. mobile still having issues.

**Comment by future2back** [comment]
This problem is not related to sunflower land, but to [MetaMask](https://github.com/MetaMask/metamask-mobile/issues/5840).

Its solved on 6.2.0 version of MetaMask.

**Comment by metalshelltoe** [comment]
Ok, thanks.

**Comment by Otakriss** [comment]
Thanks for the information. I can be connected to Sunflower Land now. Thank you for your answer.


________________________________
De : metalshelltoe ***@***.***>
Envoyé : lundi 27 mars 2023 01:42
À : sunflower-land/sunflower-land ***@***.***>
Cc : Otakriss ***@***.***>; Comment ***@***.***>
Objet : Re: [sunflower-land/sunflower-land] [BUG] sunflower land stuck at loading and connecting (Issue #2306)


Ok, thanks.

**Comment by future2back** [comment]
The issue has been resolved, this topic can be closed.
