### ISSUE TITLE
[BUG] Click area of Crop

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#232]
<img width="57" alt="Screen Shot 2022-02-07 at 11 15 59 am" src="https://user-images.githubusercontent.com/11745561/152804875-bccb1bf1-344b-4c4c-bb63-a2db3d9d18d8.png">

When hovering over a crop, there is a small space above the crop that is currently clickable. This often leads to a user planting a crop in the wrong position.

**Expected Behaviour**

Only hovering on the crop/soil allows you to plant/harvest

**Comment by Pranav-yadav** [comment]
Yeah, been waiting for someone to fix it.
Tho, I have a fix in mind (other than introducing new div's. This would increase the render time a little bit for large farms).
Will try implement the new approach.

Others pls don't wait for to fix it, feel free to open a PR with fix 👍
