### ISSUE TITLE
Token Icon

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#233]
This is a request for an icon to be used to represent the Sunflower Land Token. This will be used on game and in exchanges

<img width="383" alt="Screen Shot 2022-02-07 at 11 25 27 am" src="https://user-images.githubusercontent.com/11745561/152806853-dbd19692-b51b-44c8-83ac-db1a80a6ad41.png">

**Where will this be used?**

- The Fav Icon (in the tab of the browser)
- Exchanges
- In the game

The icon will be extremely small in some use cases so we need something that is not extremely detailed

Size Example:

<img width="154" alt="Screen Shot 2022-02-08 at 11 42 15 am" src="https://user-images.githubusercontent.com/11745561/153009855-53ee51ca-307b-4bd7-bec9-1e80542daa4f.png">

**Problem**

The current token looks quite similar to the Sunflower Crop.  Now that Sunflowers are a resource, it can be confusing to players whether they need to collect Sunflowers or the Sunflower Land Token.

<img width="314" alt="Screen Shot 2022-02-07 at 11 25 37 am" src="https://user-images.githubusercontent.com/11745561/152806823-bd5a9ae9-8865-425c-82b5-6f63952b3a35.png">

**Requirements**

- Pixellated - 16px x 16px maximum

**Comment by Alexcnder** [comment]
this is the below 32x32
![FINAL WITHDRAW SMALL](https://user-images.githubusercontent.com/87881787/152811326-50491c48-3fa2-4bee-a8ed-32696749f3a7.png)
![FINAL WITHDRAW SMALL](https://user-images.githubusercontent.com/87881787/152811408-630d24d6-65e0-4d52-b573-02a3c3e41a74.png)
im currently doing a 64x64 aswell

**Comment by BigKongJosh** [comment]
![token](https://user-images.githubusercontent.com/98506626/152841582-b067c4da-d1c9-4e74-8361-b8dafc247166.png)
![Token](https://user-images.githubusercontent.com/98506626/152841439-be0608c0-1120-4e97-9b33-87c120fbbc08.gif)
![tokensmall](https://user-images.githubusercontent.com/98506626/152841449-7d40ac19-333e-4fa5-a04c-34454daf8305.gif)

**Comment by cambrios1** [comment]
16px x 16px
![SF-Token](https://user-images.githubusercontent.com/98171636/152874304-11ac5c25-5da4-4794-839b-01d0bcde8dd2.gif)
![SF_Token_Ani](https://user-images.githubusercontent.com/98171636/152874311-05bf9379-c2a7-4304-a148-1a747b81f732.gif)

**Comment by cekingenn** [comment]
![sunflower .jpg](https://user-images.githubusercontent.com/76853495/152877511-56bac8c3-1af0-4f77-995d-e65fb6310558.jpg)

**Comment by kimberlite07** [comment]
> 

This is so cool but the rotation is so fast it's making me dizzy hahahah

**Comment by Sarapico** [comment]
![pixil-frame-0 (12)](https://user-images.githubusercontent.com/98893182/152912572-64eaad44-5637-4fab-8b88-7ff7e8722cf1.png)
![pixil-frame-0 (13)](https://user-images.githubusercontent.com/98893182/152912581-8703a342-9f50-400c-8c26-0d001d991385.png)

**Comment by benaxol12** [comment]
Sunflower Land Token 16x16
![Token Orj](https://user-images.githubusercontent.com/98098031/152934724-5d047a52-8fab-4bc1-b0ea-b2183c33441f.png)
![Token 64x](https://user-images.githubusercontent.com/98098031/152934728-6f79f601-ca24-4b05-b2e2-f17c66a28579.gif)

**Comment by Z1kou** [comment]
> ![sunflower .jpg](https://user-images.githubusercontent.com/76853495/152877511-56bac8c3-1af0-4f77-995d-e65fb6310558.jpg)

Don't take photos from Google my fried !

**Comment by Vergelsxtn** [comment]
16x16 - SFL TOKEN (can be improve)
![SFL-TOKEN](https://user-images.githubusercontent.com/99605039/153822746-b0730257-4471-47b3-bdd2-7565245a0f96.gif)
![SFL-TOKEN-B](https://user-images.githubusercontent.com/99605039/153822883-4374a597-737b-4f32-8e3e-7afdeeebab83.gif)

**Comment by adamhannigan** [comment]
<img width="148" alt="Screen Shot 2022-02-14 at 8 27 05 am" src="https://user-images.githubusercontent.com/11745561/153855902-f795c3bc-a27c-4943-9863-92f811b05e08.png">
<img width="143" alt="Screen Shot 2022-02-14 at 8 25 44 am" src="https://user-images.githubusercontent.com/11745561/153855913-dd51f36d-88d4-447b-b6cb-9e394efa01f3.png">
<img width="150" alt="Screen Shot 2022-02-14 at 8 22 37 am" src="https://user-images.githubusercontent.com/11745561/153855915-a5cda815-2012-4a4d-bc09-155f4a3ba2ca.png">

@Vergelsxtn @cambrios1 @BigKongJosh 

Here is a screenshot of the tokens in the game. Each of your designs each have pros and cons when used in the game's UI. I'm wondering if we can combine the best of each 🤗 

@BigKongJosh It looks a bit too pixellated and the black outline feels too heavy against the brown background. The sunflower logo looks great 👌 

@cambrios1 The colours look on point and look the most consistent with the colours used in the game. It is bright and stands out. I'm curious how we could make it more identifiable as a sunflower. The idea is that players would spot the coin and immediately associate it with Sunflower Land

@Vergelsxtn This is my favourite animation - it does not distract the user too much but gives the shiny effect of a coin. Compared against the brown background the colours look a little dull though.

What are your thoughts how we can combine/improve the token?

**Comment by Vergelsxtn** [comment]
Ok I will update the coin🤗

**Comment by cambrios1** [comment]
@adamhannigan Thank you for the feedback. I made it a little more like the original to emphasize the flower part of it. I could make a simpler/less distracting animation where it just tips slightly side to side (instead of spinning). Let me know if I'm headed in the right direction. 
![Token2](https://user-images.githubusercontent.com/98171636/153871415-9bfb9a75-f446-4539-86d8-7bcba4f57224.png)

**Comment by Vergelsxtn** [comment]
SFL-TOKEN IDLE
![SFL-TOKEN1](https://user-images.githubusercontent.com/99605039/153876473-0882ee3f-4eb2-4120-831e-cd9d28cc5e91.png)
![SFL-TOKEN2](https://user-images.githubusercontent.com/99605039/153876514-3606b8da-2826-451c-b57b-12d01f3829ec.png)
SFL-TOKEN GIF
![SFL-TOKEN-16x16](https://user-images.githubusercontent.com/99605039/153876726-2fed50b3-c408-46f4-b7b2-aae371f11182.gif)
![SFL-TOKEN-128x128](https://user-images.githubusercontent.com/99605039/153876778-71338b32-dc3d-4011-b900-7b32fe148513.gif)

**Comment by adamhannigan** [comment]
@cambrios1 Very nice ❤️ 

I think it might look better without the dark border on the right hand side. What do you think?

Since it is a UI icon, the shadows of the game don't really appply

<img width="189" alt="Screen Shot 2022-02-14 at 3 00 41 pm" src="https://user-images.githubusercontent.com/11745561/153920422-f5ddf5ff-dda4-4df0-a4b3-1605110ca828.png">

**Comment by adamhannigan** [comment]
@Vergelsxtn 👏 Getting closer with the colours 😍 

<img width="192" alt="Screen Shot 2022-02-14 at 3 02 13 pm" src="https://user-images.githubusercontent.com/11745561/153920631-4f0f26f0-51db-4925-85fc-775178bde0ca.png">

This will be a tough decision by the community

**Comment by adamhannigan** [comment]
@cambrios1 I like the light border :)

**Comment by cambrios1** [comment]
@adamhannigan here's a shiny version
![TokenShine](https://user-images.githubusercontent.com/98171636/153964036-8b2f8e95-5222-481d-bd0a-cbca2c90ea06.gif)

**Comment by Vergelsxtn** [comment]
How about this one? ( I adjust the colors )
![External](https://user-images.githubusercontent.com/99605039/153970013-f2cb2a90-04a1-4021-af72-cb3b74e4094a.png)

**Comment by Vergelsxtn** [comment]
I also made a new design.
![2ndtoken](https://user-images.githubusercontent.com/99605039/153973791-8b001d98-2ce1-4d88-9594-27cc791f6712.png)
![2ndtoken1](https://user-images.githubusercontent.com/99605039/153973811-085fb28b-7da1-44ce-94ef-856fc33bdad0.png)
![2ndtokens](https://user-images.githubusercontent.com/99605039/153973823-a766fd70-5dd8-4d4e-8445-bda0aac83881.png)
![2ndtokens1](https://user-images.githubusercontent.com/99605039/153973835-1125b935-c372-4a19-89d8-85b37b6fdc2a.png)

( I will add the animation later..)

**Comment by Sarapico** [comment]
![pixil-frame-0 (1)](https://user-images.githubusercontent.com/98893182/154085252-add7549b-6a2c-49a6-ad96-817b50372e7d.png)
![pixil-frame-0](https://user-images.githubusercontent.com/98893182/154085283-a603af69-9ba2-425f-9be8-b61b3b8916e5.png)

![pixil-layer-Layer 2](https://user-images.githubusercontent.com/98893182/154084190-99c9a193-0b40-4965-b144-a9c5cc74c50c.png)
![pixil-layer-Layer 2 (1)](https://user-images.githubusercontent.com/98893182/154084219-29ad093d-f358-42dd-a67c-8d9897bad9e6.png)

**Comment by adamhannigan** [comment]
<img width="143" alt="Screen Shot 2022-02-15 at 6 01 33 pm" src="https://user-images.githubusercontent.com/11745561/154148540-83e0daa6-5e7c-40dd-aff2-99e0380b390d.png">
<img width="148" alt="Screen Shot 2022-02-15 at 6 01 06 pm" src="https://user-images.githubusercontent.com/11745561/154148543-d54d8260-65e3-4697-a2fc-c5e5a42f951a.png">

These both look amazing 👏 

Right now I would have to go with @cambrios1 It is distinct and recognisable ❤️

**Comment by adamhannigan** [comment]
We are feeling generous today, keep an eye on your farm when we launch for a golden surprise ;)
