### ISSUE TITLE
Error modal sprite animations

### ISSUE THREAD

**Issue by spencerdezartsmith** [sunflower-land/sunflower-land#234]
I am building out a few different error modals. As we all no errors suck and we hate to see them BUT how about we at least make them cute 😺 . I have attached a video of one of the error modals we already have that is doing a good job at being adorable. This is a guide to what I am talking about. 

Error modals I will be adding:

Wrong Chain - the user is connected to a chain other than polygon
No Web3 - the user does not have metamask installed

https://user-images.githubusercontent.com/17863697/152879075-f846288d-b3bc-40e4-a6e8-3252f573fd42.mov

**Comment by cekingenn** [comment]
Congratulations, you're working hard my friend. I'm looking forward to the game

**Comment by cekingenn** [comment]
Please add me airdrop 🌻🌻🌻

**Comment by gabiqueiroga** [comment]
> 

I did it! I'm glad you liked!

**Comment by benaxol12** [comment]
First try (No Web3 - the user does not have metamask installed)
![deneme](https://user-images.githubusercontent.com/98098031/152988856-bbd19a2c-c96f-48c7-a081-96af10b17811.gif)

**Comment by spencerdezartsmith** [comment]
> First try (No Web3 - the user does not have metamask installed) ![deneme](https://user-images.githubusercontent.com/98098031/152988856-bbd19a2c-c96f-48c7-a081-96af10b17811.gif)

I wonder if along this line of thinking we have a fox that is almost taunting the character and he is trying to catch the fox?

**Comment by spencerdezartsmith** [comment]
> ![FARMER BOI](https://user-images.githubusercontent.com/98262339/152995179-687503d9-fe59-4aa8-8d89-d97688b3755d.gif)
> 
> Tried making an animation this is just an idea if u like it i can try to improve it ! (Ps: My first ever animation !)

Great job on your first animation! How do you think we can connect it back to the error at hand ie. Either connected to the wrong chain or no metamask?

**Comment by Z1kou** [comment]
> > ![FARMER BOI](https://user-images.githubusercontent.com/98262339/152995179-687503d9-fe59-4aa8-8d89-d97688b3755d.gif)
> > Tried making an animation this is just an idea if u like it i can try to improve it ! (Ps: My first ever animation !)
> 
> Great job on your first animation! How do you think we can connect it back to the error at hand ie. Either connected to the wrong chain or no metamask?
![FARMER BOI](https://user-images.githubusercontent.com/98262339/153451899-771fc117-e1d5-4421-86bd-9a089af8075d.gif)
 


Made some upgrades to it ! 

back to our subject i really didnt focus on the examples u gave i thought i would just make a gif that would show when a error pops my idea of this is that the server is facing an over load or that an unexpected error happened xd
