### ISSUE TITLE
Sync on chain sprite animation 

### ISSUE THREAD

**Issue by spencerdezartsmith** [sunflower-land/sunflower-land#235]
When a user clicks the `Sync on chain` button they will move into a loading state while the transaction completes. We would love some cool animation for the loading modal. 

Open to suggestions on what this would be... I guess the vibe would be someone hard at work putting all your hard earned actions on chain. 

🤗

**Comment by cekingenn** [comment]
Please add me airdrop 🌻🌻🌻

**Comment by Andreivv** [comment]
![The Creatooor](https://user-images.githubusercontent.com/97338003/152888781-a35c4fe6-c29e-4026-83c1-37b0d5e6a384.gif)
 

kk i made this for some "nft creator in the future but.." we can go on this way maybe, with other "art word" like," prossessing.. " 
"making a whole cake right now" xD, i made just for fun, if this idea is nice, maybe i can create some thing based on this. 

@spencerdezartsmith

**Comment by spencerdezartsmith** [comment]
> ![The Creatooor](https://user-images.githubusercontent.com/97338003/152888781-a35c4fe6-c29e-4026-83c1-37b0d5e6a384.gif)
> 
> kk i made this for some "nft creator in the future but.." we can go on this way maybe, with other "art word" like," prossessing.. " "making a whole cake right now" xD, i made just for fun, if this idea is nice, maybe i can create some thing based on this.
> 
> @spencerdezartsmith think on this like a ideia, there are some errors and things to do.. but if it's ok, i can work on it.

Yeah it’s good! Could he be tipping vegetables into that machine and we could use it as the syncing gif potentially?

**Comment by adamhannigan** [comment]
@spencerdezartsmith @Andreivv 

We will have a separate loading screen when a user mints a rare item (e.g. Sunflower Statue).

I think this Art animation would be a perfect use case for that 🚀

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith @Andreivv
> 
> We will have a separate loading screen when a user mints a rare item (e.g. Sunflower Statue).
> 
> I think this Art animation would be a perfect use case for that 🚀

Oh yeah thats a good idea

**Comment by Andreivv** [comment]
![Loadingdong ](https://user-images.githubusercontent.com/97338003/153514003-89063eb2-a115-4fcc-bc52-0238edd9ddf9.gif)

**Comment by ItsNight** [comment]
> > ![Loadingdong ](https://user-images.githubusercontent.com/97338003/153514003-89063eb2-a115-4fcc-bc52-0238edd9ddf9.gif)
> > Colors and size are ajustable, but i think is really nice
> 
> I like this for loading but the the background and border would need to go. It would just need to be the imagery. Also just confirm that the colors used in the ellipsis are sampled from the games color palette.
![Uploading Sprite-0004qq.gif…]()
![Sprite-00012qsss2](https://user-images.githubusercontent.com/43474459/156931909-81800455-8c47-4416-a3ec-6fe4734b73a2.gif)

**Comment by ItsNight** [comment]
Update
![Sprite-000ss4qq](https://user-images.githubusercontent.com/43474459/156934066-3045620b-58fa-4c8c-9231-eab0a2b4a6cb.gif)
![Sprite-03005](https://user-images.githubusercontent.com/43474459/156934067-d1960cc3-15a9-44f8-9ff2-fc8280f61b3c.gif)

**Comment by Andreivv** [comment]
![Capturaraaa](https://user-images.githubusercontent.com/97338003/157584470-0c1ac700-c0b9-40c9-9033-3c1e92bbbb3d.JPG)


> 

I allready have the otimization, but i can't send a GIF. just a Ase prite file. no pixel random and borders. i'm allready send on Discord but not here.

**Comment by Andreivv** [comment]
@spencerdezartsmith  How can i send an aseprite file here? i can't do it. i'll tag you on the correct File in Discord right now
