### ISSUE TITLE
Low Cost Collectible Items

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#238]
This is an art request for multiple low-cost decorative items. There is no specific ask, just cute items to decorate your farm with. We will be looking to release **3-5** of these items on launch 🚀 

The purpose of these items is to provide a low barrier of entry for crafting for new users. They will be limited, but hopefully all of our initial users will be able to mint one in time

**Example**

- Pot Plant
- Supply (50,000)
- Costs - 1 SFL and 1 Sunflower

**Requirements**

[Specs](https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md#artwork-specs)

**Comment by benaxol12** [comment]
![TreeOrj](https://user-images.githubusercontent.com/98098031/153020250-718e21cb-d2ae-4788-8469-3545233a207d.png)
![Tree](https://user-images.githubusercontent.com/98098031/153020015-d8f80fa0-e615-4332-906d-cfcb68dc6be0.png)

**Comment by kimberlite07** [comment]
Please please make a hammock 😌

**Comment by danuribeiv** [comment]
here is a life ring so that nobody drowns in the lake:)

![Life Ring](https://user-images.githubusercontent.com/10442760/153038568-87d1ad58-9261-4868-be3e-419136a6d23f.png)
![Life Ring 5x](https://user-images.githubusercontent.com/10442760/153038581-4a39285f-12f3-4d5a-a4fa-db00c67b0212.png)
![example](https://user-images.githubusercontent.com/10442760/153038626-8576d18b-bdc6-418f-a50b-cf51bb326646.png)

**Comment by paluras** [comment]
![cactus](https://user-images.githubusercontent.com/98059798/153042469-ca0b6626-d2bc-4a55-8b86-8aa5bacb407c.png)
![cactusORIGINAL](https://user-images.githubusercontent.com/98059798/153042489-6ec21c7b-5d31-48f1-8a1e-cb5b01314f87.png)

Exotic plant: a cactus!

**Comment by Synedes** [comment]
Small fountain
![smallfontain](https://user-images.githubusercontent.com/98273814/153046752-3cba242c-2ad6-452c-85e5-c1a31eec72a6.gif)
![smallfontainhighquality](https://user-images.githubusercontent.com/98273814/153046767-7f7b4f2a-c5bf-4843-97b1-90fb10ebd0c4.gif)
![image](https://user-images.githubusercontent.com/98273814/153046813-683cd6f2-df56-4d40-bab2-64c8045d627a.png)

**Comment by Andreivv** [comment]
![aaa](https://user-images.githubusercontent.com/97338003/153065243-a11d8cfb-cbf6-4b2c-849e-c119c50d7c3b.jpg)


Oh, i made this in december, just for fun and for my dog farmer xD (onde day i'll have one u.u) 
Maybe worth to increase something in your relationship with your pet o/

**Comment by Alexcnder** [comment]
> 
Supply:
60k~ maybe a cool Number like 61118 or 63636
1 per Farm 
Boat Price:
1 Wood + 1SFL/Matic

**Comment by Alexcnder** [comment]
> > **The Boat**
> 
> It docks at ur Farm and might help u in the future on the sea! ![BOAT On the sea](https://user-images.githubusercontent.com/87881787/153041259-c2126dc0-88b8-4097-8cf1-992581509739.png)
> 
> > **Maybe the Icon of the NFT**
> 
> ![BOAT NFT](https://user-images.githubusercontent.com/87881787/153041377-02c3b557-2f67-45e0-9199-2bd8b933ee12.png)
> 
> > **Actual changes to ur Farm**
> 
> ![BOAT](https://user-images.githubusercontent.com/87881787/153041581-3d10068f-3736-4378-bce8-1c41488ab909.png)
> 
> Suggestions for traits drawing and utility appreciated!

Supply:
60k~ maybe a cool Number like 61118 or 63636
1 per Farm
Boat Price:
1 Wood + 1SFL/Matic

**Comment by Sarapico** [comment]
Bird house
![pixil-frame-0 (9)](https://user-images.githubusercontent.com/98893182/153087405-6f0e1486-1343-4b7a-bf50-949b129e2e5b.png)
![pixil-frame-0 (6)](https://user-images.githubusercontent.com/98893182/153087441-418e697e-ce09-49f3-be90-9232bb0378fd.png)
![pixil-frame-0 (5)](https://user-images.githubusercontent.com/98893182/153087467-eb9f53da-53cf-494d-8af9-805e74e81653.png)

**Comment by Synedes** [comment]
As the game doesn't have birds yet, I decided to make a corner for them :)
![birdnook](https://user-images.githubusercontent.com/98273814/153088764-cf9dd4c5-97c8-494d-88cb-be0905338cc9.gif)
![birdnookhighquality](https://user-images.githubusercontent.com/98273814/153088783-2f762d0f-d95c-4345-ade2-4c0309227893.gif)
![image](https://user-images.githubusercontent.com/98273814/153088842-7a9cd44b-be87-4b01-be56-27fbc9c5c9ff.png)

**Comment by Sarapico** [comment]
@Synedes OMG. I need this.

**Comment by Synedes** [comment]
> @Synedes OMG. I need this.

Now that I posted mine that I saw yours, we thought of the same purpose together, yours could be added to various game trees, I really hope to see yours in the game! <3 *-*

**Comment by gabiqueiroga** [comment]
some nice little bowls

![bowls](https://user-images.githubusercontent.com/69090306/153098119-03644ba2-abc0-45c8-9c97-f80ba88d3165.png)

![image](https://user-images.githubusercontent.com/69090306/153098123-6913af25-41ae-4bef-a234-341d19cba2b8.png)

**Comment by gabiqueiroga** [comment]
rats

![rats](https://user-images.githubusercontent.com/69090306/153098398-7737e51f-0f5a-4f3a-b3f1-2cc939a2237d.png)

![image](https://user-images.githubusercontent.com/69090306/153098636-9adbe642-a2cc-453b-b80e-2013dd65c476.png)

![image](https://user-images.githubusercontent.com/69090306/153098673-b3a0fc10-956d-49f9-86b4-18559ef8ddc8.png)

**Comment by cambrios1** [comment]
![Manure-big](https://user-images.githubusercontent.com/98171636/153209402-e76d0403-6b3c-4080-aeaa-0dcec2e5445c.gif)
![manure-small](https://user-images.githubusercontent.com/98171636/153209412-8214e47d-78ca-40f3-b810-7d8436b24f77.gif)
cow pie / manure

**Comment by adamhannigan** [comment]
@Andreivv @paluras @cambrios1 @benaxol12 @Aestnelis 

Just a reminder that we have a new Artwork Spec requirements.

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md#artwork-specs

We ask that you also include screenshot of where your artwork would appear in the game. This makes it easier to identify which pieces would feel consistent with the game palette/theme 🤗

**Comment by sfwhat** [comment]
I made a weather vane!
![0xaBf097ba4004F7D28A584d8C7883CEd792C3A61a](https://user-images.githubusercontent.com/95937808/153290098-a23631e9-9836-4efd-94a7-d715eaaeb8cb.png)
![final](https://user-images.githubusercontent.com/95937808/153290222-25e1a8ab-169b-4aa7-8889-72503836481c.png)

**Comment by cambrios1** [comment]
Manure pile

1px:
![Manure-1px](https://user-images.githubusercontent.com/98171636/153388268-170edc4e-0b59-43b1-8f76-266a2556983f.gif)

larger:
![Manure-big](https://user-images.githubusercontent.com/98171636/153388290-e0ddfc58-16be-4668-993f-db90566626f2.gif)

In game:
![ingamemanure](https://user-images.githubusercontent.com/98171636/153388328-6f8a8fd0-2c9a-4b03-a2a5-74292e35da01.gif)

**Comment by adamhannigan** [comment]
Some great additions! We will be slowly adding a few of these into the game. Great work everyone 👏 

Keep an eye out for the creations. Right now we are adding in the Shrek and the water fountain.

@Synedes @Aestnelis
