### ISSUE TITLE
[BUG] No Toast indicator shown after collecting Easter Eggs

### ISSUE THREAD

**Issue by johannesunana** [sunflower-land/sunflower-land#2418]
## Summary of Bug

No Toast indicator is shown on the screen after collecting the Easter Eggs.

## Steps to Reproduce
1. Log in to the farm.
2. Look for the seven Easter Eggs on the farm during the 12-hour time period.
3. When an Easter Egg is found, click to collect it.
4. The Easter Egg goes to the inventory.

## Expected Behavior
A Toast (similar to the feature in #192 or the fix used in #2071 for the Lunar New Year Event) that indicates the collected Easter Eggs should be displayed to the user right after clicking the egg.

## Actual Behavior
The Easter Egg goes to the inventory, but no indicator is shown after collecting the eggs.

## Screen Recording
https://user-images.githubusercontent.com/99703415/230698093-8aaf9536-2a10-4417-a980-02338756a015.mp4

**Device Information:**

- Device: ASUS VivoBook 15 X505Z
- OS: Windows 10 Version 22H2 (Build 19045.2728)
- Browser/App: Brave Browser (Desktop)
- Version: 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)

**Comment by Polysemouse** [comment]
Addressed by https://github.com/sunflower-land/sunflower-land/pull/2170
