### ISSUE TITLE
[BUG] Send to farm button remains enabled without Collectible selection in Deposit

### ISSUE THREAD

**Issue by johannesunana** [sunflower-land/sunflower-land#2420]
## Summary of Bug

The **Send to farm** button at Bank Deposit (introduced in #2249) remains enabled and clickable even when no Collectible has been selected to be sent to the player's farm.

## Steps to Reproduce

1. A supported ERC-1155 token from the Sunflower Land Collectibles collection should be in the player's Personal Wallet.
2. Log in to the farm and go to the Goblin Retreat.
3. Select the **Bank** to access the **Deposit**.
4. Do not select any Collectible. The space under **Your farm will receive** should be empty.
5. Click the **Send to farm** button. The player's default Web3 wallet will open as a blockchain transaction is requested.
6. Reject the transaction.
7. Select and deselect the same Collectible. The space under **Your farm will receive** should be empty again.
8. Click the **Send to farm** button. The Web3 wallet will open again.

## Expected Behavior

If the player has not selected any Collectible from their Personal Wallet and the space under **Your farm will receive** is empty, or if the player has deselected any previously selected Collectible, the **Send to farm** button should change its state to disabled and should not be clickable to the player. It is expected to be enabled and clickable only when the player has selected a Collectible.

## Actual Behavior

The **Send to farm** button state remains enabled even if no Collectible is selected or a previously selected Collectible is deselected, allowing players to click it.

## Screenshots

![bandicam 2023-04-10 03-11-03-789](https://user-images.githubusercontent.com/99703415/230792506-4297cef7-c3bb-4d34-89b4-d7d5e913af1f.jpg)

## Screen Recording

https://user-images.githubusercontent.com/99703415/230792525-cf4f0c39-5a28-4d02-bd7b-0fb91850f73f.mp4

**Device Information:**

- Device: ASUS VivoBook 15 X505Z
- OS: Windows 10 Version 22H2 (Build 19045.2728)
- Browser/App: Brave Browser (Desktop)
- Version: 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)

**Comment by future2back** [comment]
Hello friend @johannesunana, can you tell us if this issue has been resolved?
Thank you.

**Comment by johannesunana** [comment]
Hello @future2back, thank you for the ping I actually forgot about this issue I opened. Just checked again, both in Goblin Retreat and Home. Looks like it's been fixed for a long time. I'll close this issue now.
