### ISSUE TITLE
[BUG] hoarder limit

### ISSUE THREAD

**Issue by ReC82** [sunflower-land/sunflower-land#2451]
Everything is already mentionned here : https://discord.com/channels/880987707214544966/1095736094340960307/1095798817531641886

Do you guys looking to those request ?  I know there's a bunch of non-sense there but time to time there's real issues.  Someone from the team has to check there.

Im sure you're doing all you can but before new stuff, please correct the bugs !

friendly,

L. ;)

**Comment by ReC82** [comment]
[](url)
![2023-04-17 01_32_39-Window](https://user-images.githubusercontent.com/10573611/232349575-89f4eb63-d26d-4151-bba0-1f6feb5b271b.png)

translation : 

A :
So I have this message whatever I do.  Cut trees, harvest sfl, whatever
I'm force to be f*** because the gale is broke or what ?

B:
They rise down the hoarder limit, it piss me since a some days

A :
Limits are the same, just the game is not well coded.

b : ...

A : The don't care, devs wins more if we sync more.

...

feel the mentality here. :( that's sad.  do something.

**Comment by ReC82** [comment]
I understand the hoarding thing, but we should be able to still be able to do something else.

**Comment by future2back** [comment]
Hello friend @ReC82, can you tell us if this issue has been resolved?
Thank you.
