### ISSUE TITLE
Add Polygon Network Button

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#246]
If the user is not on the Polygon Network, provide a button which will add the setup to their MetaMask.

This is similar to PolygonScan which has a MetaMask button down the bottom - https://mumbai.polygonscan.com/

Example when on testnet (We will want it for testnet and mainnet).

<img width="171" alt="Screen Shot 2022-02-09 at 9 26 45 am" src="https://user-images.githubusercontent.com/11745561/153200887-3504b689-6a37-4c14-8a65-c2d0a6e4060d.png">

**Requirements**

When a user first accesses the game and does not have Polygon setup, show the button.

Clicking this adds the Polygon network to their Metamask.

**Comment by Pranav-yadav** [comment]
@adamhannigan @martayfun ig this issue has been fixed & can be closed 👍
