### ISSUE TITLE
Team Donation

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#248]
With the latest withdrawal proposal, many people asked if there could be an in-game mechanism where people could donate more to the team.

This request is to gamify the donation to the team and make it fun.

Some ideas include:
- Buying a pixel art coffee for the team
- Homeless person begging for money
- Neckbeard developer

This proposal is open to any sort of ideas.

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

**Comment by rickfurt** [comment]
I'm not an artist but, I was picturing in my head something like that. 

What if there's a new character as a homeless sitting next to the shop and if no donations are made in a certain period the homeless steals one crop( as if it was to eat or something).

It's a bit crazy idea but could work in a monthly period I guess.

**Comment by Z1kou** [comment]
A story line to this would be add a character to every donation side :( like i said with the radio / music side add a ferryman with alot of music tools - The devs donation should have a worrying mayor who worries about the land and proposes for us to donate ect...)

**Comment by SFL-Aeon** [comment]
> I'm not an artist but, I was picturing in my head something like that.
> 
> What if there's a new character as a homeless sitting next to the shop and if no donations are made in a certain period the homeless steals one crop( as if it was to eat or something).
> 
> It's a bit crazy idea but could work in a monthly period I guess.

I’m sorry but I think many will be against this as this is a continual fee and not a donation. If you don’t “donate” then it’ll impact your farm/revenue.

There are plenty who want to donate to the cause but forcing it ontop of all the other proposed revenue methods will be a bit extreme.

**Comment by rickfurt** [comment]
Yeah, u guys are right.

But maybe instead of losing a crop what about if the character:

- Helps finding items for u in the map or, 
- Take care of your crops 
- Help to keep the goblins away or something in these lines.

Just trying to think ways to motivate users to donate or something.

**Comment by Sarapico** [comment]
> Yeah, u guys are right.
> 
> But maybe instead of losing a crop what about if the character:
> 
>     * Helps finding items for u in the map or,
> 
>     * Take care of your crops
> 
>     * Help to keep the goblins away or something in these lines.
> 
> 
> Just trying to think ways to motivate users to donate or something.

if you gain any kind of advantage in return, that's not a donation anymore. Youre just paying for that.

**Comment by rickfurt** [comment]
It has to do something in the game, either advantageous or disadvantageous, otherwise many wouldn't donate.

**Comment by spencerdezartsmith** [comment]
I agree that the donation shouldn't be connected to anything as its simply a donation. Folks who donation can be rewarded in other ways. 

What if there was just a little coffee stand somewhere in the game and that was where you could "Buy a coffee" for the team?

**Comment by adamhannigan** [comment]
@spencerdezartsmith Doesn't look like any of us, but here is my attempt of a 'nerd'

![nerd](https://user-images.githubusercontent.com/11745561/153771366-163a10ac-7a17-43d2-9007-9c6d6a54ec3d.gif)

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/11745561/153771379-aa0570b0-7b44-4d23-bfe6-e2e405d097f2.gif)

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith Doesn't look like any of us, but here is my attempt of a 'nerd'
> 
> ![nerd](https://user-images.githubusercontent.com/11745561/153771366-163a10ac-7a17-43d2-9007-9c6d6a54ec3d.gif)
> 
> ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/11745561/153771379-aa0570b0-7b44-4d23-bfe6-e2e405d097f2.gif)

You win mate. He's going in! 🤓

**Comment by Z1kou** [comment]
> @spencerdezartsmith Doesn't look like any of us, but here is my attempt of a 'nerd'
> 
> ![nerd](https://user-images.githubusercontent.com/11745561/153771366-163a10ac-7a17-43d2-9007-9c6d6a54ec3d.gif)
> 
> ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/11745561/153771379-aa0570b0-7b44-4d23-bfe6-e2e405d097f2.gif 

This little guy got me both chuckling and impressed !

**Comment by Vergelsxtn** [comment]
I made the homeless Idea!

Idle:
![Donation-Idle](https://user-images.githubusercontent.com/99605039/153902996-51c912dd-e8e7-48a1-8b7c-cbaa147328e0.png)
![Donation-Idle1](https://user-images.githubusercontent.com/99605039/153903081-dfc3aed2-cbe5-48ba-b33c-e3aebdcbfa33.png)
![Homeless-land](https://user-images.githubusercontent.com/99605039/153903266-c388b9a3-c8ef-4fe5-b2ec-cc1d633dbebb.jpg)
Gif:
![Donation-GIF](https://user-images.githubusercontent.com/99605039/153903678-87262f12-9098-44fd-bba6-e592d2d031fc.gif)
![Donation-GIF1](https://user-images.githubusercontent.com/99605039/153903753-45c1c013-6a4a-407f-9e0a-4985f6fbd820.gif)

( If something wrong, please tell me thanks )

**Comment by Z1kou** [comment]
> A story line to this would be add a character to every donation side :( like i said with the radio / music side add a ferryman with alot of music tools - The devs donation should have a worrying mayor who worries about the land and proposes for us to donate ect...)
![MAYOR ANIMATION 400%](https://user-images.githubusercontent.com/98262339/154178086-07e3dd6d-f405-4e99-9a12-89a60777e9ae.gif)
![MAYOR ANIMATION WITH BACKGROUND 400%](https://user-images.githubusercontent.com/98262339/154178092-4b10b28c-6fdb-401a-b1a0-ee6bd7e5ab71.gif)
My iteration of this with a story line is a  mayor that worries about the SunFlowerLand and asks for help (In a Donation to the devs !)

**Comment by rickfurt** [comment]
I like that @Z1kou

**Comment by Z1kou** [comment]
> I like that @Z1kou , maybe the character design could be a mayor instead of a farmer.

I tried to keep it simple i will try to make some improvement on it !

**Comment by adamhannigan** [comment]
Going with Vergel's design 👏
