### ISSUE TITLE
[PROPOSAL] Side Quests

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#249]
The purpose of Side Quests is to introduce a new game play mechanic that encourages farmers to play and earn with a challenging progression system.

## Goal

- Reward strategic players, not click farmers
- Add unique quests that keep players engaged.

## Description

Each week a player will be randomly generated an item that will be in **hot demand**. Items in hot demand can be sold for vast amounts of Sunflower Land Tokens. If a player collects the necessary ingredients, they can craft and sell this item.

_Characteristics_

1. Each player has a different randomly generated item - Bots cannot prepare for what it will be
2. Items should take 3-4 days to collect the necessary ingredients
3. Items get more difficult to acquire and more profitable the more you expand your farm.

## Examples

_In these examples the rewards will be relative to whatever the halvening period is. Just imagine they are significant_

**Early quest for beginners**

Goblin - "I am preparing a present for my girlfriend but I need 10 stone, 23 Sunflowers and 12 Cauliflowers. I will give you **10 SFL** if you can find these items for me"

**Quest for advanced players**

Wizard - "I am creating a potion to turn pigs into Goblins. I need 10 wheat, 5 emeralds and 20 radishes. I will give you **100 SFL** if you can find me these ingredients"

**Comment by AncientHorse** [comment]
I like this.  As I explore the map, I keep thinking there should also be a low reward "find" quest every now and again.  Something like "I lost 4 pumpkins.  If you help me find all 4, you can have one!"  The items would be randomly spread throughout the map so players can't just go to discord and ask for the locations.  It would also be fatiguing for players with multiple accounts.

**Comment by kimberlite07** [comment]
This is a nice idea! Keeps the game fun and exciting. I just have a question.

1. What will the system be for the rewards after completing the side quest? Since the items will be randomized, I reckon these items will have varying prices. 

Also a few suggestions:
1. Maybe have the rewards hardcapped so that you guys can easily keep track of the tokens being minted and analyze how the side quests affect the economy as time goes by.

2. If you guys do put a hardcap on the rewards, you can either set a specific amount to be distributed among farmers in different farm levels or make the rewards first come first serve so there's competition. :)

**Comment by adamhannigan** [comment]
@AncientHorse I agree. The map is already enjoyable to scroll around. I imagine adding 'hidden' rewards would encourage users even more to search around 🤗 

@kimberlite07 Great points. This will definitely be a mechanic that we will need to fine tune over time and track how people are earning them.

For simplicity, a player won't craft a new item, instead they will just exchange the ingredients needed :) 

I really like the idea about first come first served - I.e. the first 5 people to do it each day get a 200% bonus. It will be difficult though since each user will be required to collect different ingredients (this is to help prevent the bots from predicting it).

**Comment by Ramtin9** [comment]
This is amusing. Similar to the order system in Kawaii Island; gather collectables, crops and burn them in exchange for some SFL and EXP (experience to level up farm and things)
Daily quests, weekly quests and maybe some special quests.
It could start from easy tasks with low awards to harder tasks with higher awards and maybe leaderboards and season events like Axie where top players (top EXPs) win some SFL tokens at the end of each season.

Other than this i like the idea of "rare mutant crops" that Adam mentioned on Discord.
Once i read something about the Chainlink VRF and RNG system which would be helpful in this case; imagine there are some Rare, Epik, Legendary... crops with a total random chance of harvesting while planting your everyday seeds.
e.g. (1mil supply):
Sunflower             buy          sell          chance         profit
Usual                   0.002      0.004           95%               2×
Rare                     0.002       0.01              5%                5×
Epik                     0.002        0.02              1%              10×
Legendary          0.002        0.04             0.1%            20×

And maybe same thing with the seeds too; 0.1% chance that a planted crop drop a rare seed which makes you be able to plant rare plants and so on...

**Comment by Synedes** [comment]
I love an idea, it will generate one more reason to take care of the farm, because it will make it more fun.

I believe that having Quests can greatly expand the game and increase the possibilities

I think it's risky to tee rewards too high.

quests with smaller rewards but with a quest cycle every 4 days would be more interesting for the game economy I think

The implementation can also be used to expand the map considering how long it might take to complete.

example
- Collect 20 Autumn-themed Mushrooms
- clear 10 fallen autumn theme leaves

reward - autumn map release

therefore, mushrooms and leaves would randomly appear on the map over the course of days.

estimated completion 4 days.

This is just an idea.

**Comment by Z1kou** [comment]
Love the idea this is my time to shine so lets start by the 2 examples you gave and what i think about them 👍 

1-Quests are the bread and butter of game everyone loves them on one condition the rewards are worth the hussle that is something i would like if we keep in mind while working on this mechanisme of the game we gotta (keep the quests simple and interactive and have quests that suits every type of players from quick quests with little rewards to legendary quests with rewards that are so much worth it) 

 2- personally id like if we used quests after getting the statistics of beta ( Check whats the least used crops of the game and encourage players to plant them for quests and  maybe give more thought into why these crops dont get the same love as others and present them with greater interest - again imma rant about why sherrifs would fit perfectly into this if a goblin will be burning the pumpkin soup then pumpkins would become valuable so if we add a counterpart of goblins (sheriffs) and we use them with raddish soup, raddishes would gain the same value  now what if we add 1 quest for goblins with pumpkin soup lets say call it : (LOVE AT FIRST SIGHT: feed a pumkin soup to 50 goblins) and add 1 counter quest for it with sherrifs with raddish soup :( FOOD FOR THE STASH : gift 50 raddish soup to the lovely Sherrif ),the reward could be in SLF , A unique goblin / sherrif item / or a 1 time use boost to a certain crop ,we could play with rewards depending on whats lacking and what would be better for the story of the game in the future , we would have 2 quests that burn 2 sets of recipes with 2 rewards so if we have to spend 10hours to do the goblins quest to do them both we would need 20hours  increasing play time while rewarding the players with value in game and even a potential event advantage if we move the narrative to having a monthly war between humans and goblins and or a carnaval of love between humans and goblins depending on how many farmers did which line of trees( if the total of those who did goblin quests during the month is higher we have a carnaval and if we did the sherrifs quests we have a war )

3- Having daily quests to encourage daily login of players ( the daily quests shouldnt be tokens tbh we saw how axie's daily quests of 25 tokens overloaded the market and made SLP value have a fall without a parachute ) , id suggest giving daily a set of collectible seeds that if u gather 7 of them ( meaning u played everyday for a week) you would get a reward choosing from tokens to crops or mining tools ) but if u choose to keep them for a month you would get even higher rewards such as a limited usage of Victoria maybe have her for a week without having the NFT something like that so those who were late to the party would be able to use the NFT's but in a rental like system , so The TLDR of this : U play daily u get reward at the end of week your crazy and hold the rewards till the end of the month u get even better rewards and / rent a existing NFT for a week 

4- would love random quests such as a 
  A-grandma hobbinson has fallen in the pond get a fishing rod and save her ( reward a soup of your choice ) , 
  B-Goblin Steve (im sorry steve had to do it to ya xD) has lost his princesse in the woods help him find her (reward steve helps u 
      farm for an hour increasing the crops time by °0.25 percent ) ,
  C-The MONSTER Polygone is threating to the destroy the land appase his hunger by fixing his broken gas fee's (reward you get 
   to play the game xD )



Anyways i got many more ideas but i figure it would get longer to read so imma stop here for now !

**Comment by SFL-Aeon** [comment]
What about instead of the first 5 people you implement a decreasing reward system based on the number of people who complete the quest? That way it’s not targeted to the individual quest but the overall side quest entity. This way it rewards those who are collecting and holding various token and items while allowing others a chance to compete as well.

**Comment by adamhannigan** [comment]
@Z1kou Long read but it was worth it!

The daily quests is a great idea. We want to keep players engaged and returning daily 🤗 

@SFL-Aeon Love it ❤️

**Comment by Z1kou** [comment]
@adamhannigan im sorry bro about the long messages xd i just have too many ideas would have been easier if i could just send u the ideas in ur head directly xd but instead i try to detail em out as much as possible so u get what im thinking clearly !

**Comment by Aleks0010** [comment]
I propose to add to the reward for tasks, a convenient tool "watering can" or "rain", a one-time tool that accelerates the growth of all currently planted crops by 50%.

**Comment by gokhanhoca** [comment]
awesome idea. you can improve on this like daily quest,elite quests (really hard to do but with big rewards for people wanna spend more time in the game in that day) weekly quests, group quests with friends.

lore quests if you want to bring lore into the game.campaign quests.

other than crafting quests, there can be other ideas to brainstorm.
like puzzle quests,riddle quests, treasure hunts in the game, quests like i lost my lucky mining pick please find it and bring it back to me or give this to X quests. quests like i am sick please take these 5 pickaxes and bring me 10 stones you can have the extra stones and this is the payment.quests like here is 10 seeds please bring me 10 pumpkins.

those are the things that come up in 5 mins. if we can think we can come up really good things for this system.

**Comment by agcm19** [comment]
I like the idea of hidden quests. In games that I played before there were plenty of hidden/side quests. Like you need to click a certain object before it triggers a prompt or you need to carry certain pieces of objects to initiate a quest, you can also talk to an NPC who will ask farmers to fetch things for it In exchange for some info about the game or some materials. Also, you can like create random events wherein farmers can only participate if they have the specific crop/item in their basket. For example, in today's event, only those with 50 carrots in their basket are able to click or speak with the NPC and get a quest so if no more carrots, farmers need to plant or will be forced to use sync to replenish stock, or the NPC can request farmers to spare some materials like a piece of wood and stone or combination of crops and other resources (put different NPCs for each faction. goblin team gets different quest from sunflower team)  rewards can either be resources like wood or stone or a day pass to use/rent expanded lands in the future. (we can further this idea by putting a market where the items wanted by the NPC can only be obtained if farmers trade certain items but there's a twist! both teams can buy all items in the shop to prevent the other faction from completing their quest  😈 so if ever a wallet holds an unreasonable amount of materials the losing team will surely investigate that wallet :D cause they will speculate that it is a bot unless the owner defends himself/herself in the discord channel or prove no bot has been used, also we can use the quests as a point system. like a good farmer needs 50 pts to maintain the color of his farm in OS. getting less than that and his farm will get back to verification again 👯 sorry if my idea is hard to understand I'm not at my best at the moment but just want to type the idea so it will not be forgotten hehe

*** idea for the NPC for each side is to have the members of each faction work together to unlock the function of their NPC then they will report their progress in their respective channels :D  they can also discuss strategies to outplay the opposing team 

the sooner the NPC gets unlocked the sooner the faction can farm their rewards :) 

I will come back here from time to time to restructure/revise my proposal

**Comment by dongdong-gitt** [comment]
so cool i like it

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
