### ISSUE TITLE
[BUG] Maneki Neko + Daily Reward modal interfere with eachother

### ISSUE THREAD

**Issue by ShiningMinions** [sunflower-land/sunflower-land#2501]
## Summary of Bug

The modals between Maneki Neko and Daily Rewards chest seem to interfere with each-other when claiming one after the other. When I claim my daily food from Maneki Neko, then immediately claim my rewards chest, I receive a Maneki Neko modal hijacking the rewards chest. This also happens to me sometimes vice-versa.

## Steps to Reproduce

1. Wait until Daily Rewards chest + Maneki Neko are both claimable.
2. Claim food from Maneki Neko.
3. Claim daily reward from chest by confirming transaction.

## Expected Behavior

I am presented with each individual modal, and can successfully claim each.

## Actual Behavior

The Maneki Neko modal strangely re-appears, and then hijacks the daily rewards modal.

## Screenshots

N/A

**Device Information (please complete the following information):**

- Device: PC and Pixel
- OS: Linux and Android
- Browser/App: Brave Desktop and Metamask Mobile
- Version [e.g. 22]: v1.3.22

**Comment by future2back** [comment]
@ShiningMinions Hello friend, can you tell me if this issue has been resolved?
Thank you.
