### ISSUE TITLE
[CHANGE] Restock block bucks 

### ISSUE THREAD

**Issue by JCtapuk** [sunflower-land/sunflower-land#2540]
It is not profitable to spend block bucks in this game. So why not change the mechanics to spend 1 ticket on 1 building. That is, if the tools are used up and the seeds are not. Then only 1 block can drop the specified building. This will allow you to better orient yourself which way the player is going. For example, I often grow in the garden and the tools are rarely, as a result, there were a lot of pickaxes left, but I had to dump everyone
PS Sorry for the google translation

**Comment by MiSTeR1995** [comment]
Go to the discord, in RU, we will discuss your proposal!  A lot of people are waiting for you there.

**Comment by future2back** [comment]
0.5 buck per store.
I don't know, friend, but I think that would devalue the resources even more.
