### ISSUE TITLE
Farm NFT

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#255]
When Sunflower Land launches, each farm will be a unique NFT on the Blockchain. This means it will pop up on secondary markets such as Open Sea.

This is a request for the image that will be used to represent the farm.

When we officially launch, there will be a nice reward for the winning piece of art.

**Closes: 15th February**

**Requirements**

- Original art, cannot reuse the base asset pack.
- Something that represents the land/farm ownership

**Example**

This an example of an NFT land plot

<img width="900" alt="Screen Shot 2022-02-11 at 5 30 53 pm" src="https://user-images.githubusercontent.com/11745561/153665814-7dcf91ec-721c-4987-8083-49d03ab67a5d.png">

**Comment by ItsNight** [comment]
![Sunflower Land NFTc](https://user-images.githubusercontent.com/43474459/153679091-6e786c63-a308-4720-b15e-90ba983abb2d.png)

**Comment by ItsNight** [comment]
> ![HouseSmoke_original](https://user-images.githubusercontent.com/98059798/153714459-5f9c989b-886a-47a5-8447-344407dd7d1e.png) ![HouseSmoke_big](https://user-images.githubusercontent.com/98059798/153714461-cf87ffc0-5812-4251-bd73-7cc4af5eff36.png) ![House_big](https://user-images.githubusercontent.com/98059798/153714462-c55e2e51-7975-40aa-a153-d9a7f452d8bf.png) ![House_original](https://user-images.githubusercontent.com/98059798/153714463-b7d85556-cf6a-4f7d-b267-0904a8de01c5.png) Edit: Fixed roof.
> 
> ![HouseSmoke_original](https://user-images.githubusercontent.com/98059798/153714858-28aaf738-cde6-4224-bd02-51f166afd7b3.png) ![House_original](https://user-images.githubusercontent.com/98059798/153714861-54883cef-0acb-4be4-96af-9b496c3154c6.png)
> 
> Editedit: Smaller platform. ![House_smallerplatforml](https://user-images.githubusercontent.com/98059798/153715574-68e47499-97f8-464f-aee0-67197ea342f7.png)

Your art should be the one who adam gonna be choosing congrat from now on good job

**Comment by paluras** [comment]
> > ![HouseSmoke_original](https://user-images.githubusercontent.com/98059798/153714459-5f9c989b-886a-47a5-8447-344407dd7d1e.png) ![HouseSmoke_big](https://user-images.githubusercontent.com/98059798/153714461-cf87ffc0-5812-4251-bd73-7cc4af5eff36.png) ![House_big](https://user-images.githubusercontent.com/98059798/153714462-c55e2e51-7975-40aa-a153-d9a7f452d8bf.png) ![House_original](https://user-images.githubusercontent.com/98059798/153714463-b7d85556-cf6a-4f7d-b267-0904a8de01c5.png) Edit: Fixed roof.
> > ![HouseSmoke_original](https://user-images.githubusercontent.com/98059798/153714858-28aaf738-cde6-4224-bd02-51f166afd7b3.png) ![House_original](https://user-images.githubusercontent.com/98059798/153714861-54883cef-0acb-4be4-96af-9b496c3154c6.png)
> > Editedit: Smaller platform. ![House_smallerplatforml](https://user-images.githubusercontent.com/98059798/153715574-68e47499-97f8-464f-aee0-67197ea342f7.png)
> 
> Your art should be the one who adam gonna be choosing congrat from now on good job

Thank you ! Your art is impressive,great 3D skills!

**Comment by Vergelsxtn** [comment]
Hope this can help❤
![Land-transp](https://user-images.githubusercontent.com/99605039/153760956-3325d4eb-2ac5-47de-980d-423b75cb1d7a.png)
![Land-white (1)](https://user-images.githubusercontent.com/99605039/153760976-f524055a-0958-4cd3-a7c0-e1b2b332b2e6.png)
![test-land](https://user-images.githubusercontent.com/99605039/153760986-ed30a118-8c3c-4e89-a414-01b175b33bc7.png)

**Comment by Vergelsxtn** [comment]
Added some improvements.
![Land-no_backg](https://user-images.githubusercontent.com/99605039/153802123-62330fba-6887-4e34-9738-545034740ce5.png)
![Test-landF](https://user-images.githubusercontent.com/99605039/153802158-1467527f-db34-4568-b1f9-6dca771055f7.png)
![Land-w_backg](https://user-images.githubusercontent.com/99605039/153802205-566749ed-6ace-4fac-ad39-d7c63cf48088.png)

**Comment by Z1kou** [comment]
![NFT TRY 2](https://user-images.githubusercontent.com/98262339/153802750-60702dc8-473f-4b48-a4c9-ac89c8091329.png)
My humble try !

**Comment by Z1kou** [comment]
![NFT TRY 2](https://user-images.githubusercontent.com/98262339/153802810-8c9cce57-1ccd-4b0e-be67-c5067cfb7217.png)
My Humble Try !

**Comment by Z1kou** [comment]
![NFT TRY 2](https://user-images.githubusercontent.com/98262339/153802984-46455c5d-a4e9-4c21-8a48-2ffc27e0a9c7.png)
My Humble try !

**Comment by noprudhon** [comment]
I've been wanting to contribute some art for a while, but lacked the time, Anyway here's my entry. Hope it will be useful!

![SFL](https://user-images.githubusercontent.com/99010963/153834826-63850dfb-536e-4816-bce4-66d9f5010245.png)

**Comment by paluras** [comment]
> I've been wanting to contribute some art for a while, but lacked the time, Anyway here's my entry. Hope it will be useful!
> 
> ![SFL](https://user-images.githubusercontent.com/99010963/153834826-63850dfb-536e-4816-bce4-66d9f5010245.png)

This looks awesome!

**Comment by noprudhon** [comment]
> This looks awesome! I would recommend changing the sunflower design so it doesn't look so similar to the asset pack.

Thanks! Actually the design of the sunflower is quite different that the one from the asset pack (at least when you're zoomed in)
![sunflower](https://user-images.githubusercontent.com/99010963/153846265-53afdf0c-34a8-42aa-840b-8c15697254b0.png)
.

**Comment by paluras** [comment]
> > This looks awesome! I would recommend changing the sunflower design so it doesn't look so similar to the asset pack.
> 
> Thanks! Actually the design of the sunflower is quite different that the one from the asset pack (at least when you're zoomed in) ![sunflower](https://user-images.githubusercontent.com/99010963/153846265-53afdf0c-34a8-42aa-840b-8c15697254b0.png) .

Then you are all good!Amazing work!

**Comment by Ramtin9** [comment]
Hope you guys like this

**Comment by Ramtin9** [comment]
![2022-02-14_20 08 57](https://user-images.githubusercontent.com/98850902/153917023-1daf4a29-d2cf-4873-a377-6e3c81b277c6.png)
Hope you guys like this

**Comment by Vergelsxtn** [comment]
UPDATED
I added the suggestion's on discord, Thanks👌

Changes:
Added Sunflower
Added text on sign (SFL)
Added background (optional)
![Sunflower-Land-FARM](https://user-images.githubusercontent.com/99605039/154018377-8b0bb6aa-96cb-40f6-bb90-c5e58eeb593c.png)
![Sunflower-Land-FARM1](https://user-images.githubusercontent.com/99605039/154018415-a695c1c4-556d-41c9-b5d5-6270d0618597.png)
Testing.
![LAND-TEST1](https://user-images.githubusercontent.com/99605039/154018475-7d90b8ac-7897-4ed3-9be8-7a7b760feec8.png)
![LAND-TEST](https://user-images.githubusercontent.com/99605039/154018818-d057ac6d-1405-4a0e-9207-b236e82d950f.png)

**Comment by Alexcnder** [comment]
I tried to make it in a more pixel way
![FINAL 500x](https://user-images.githubusercontent.com/87881787/154166949-fd9fbef3-d538-43fe-bc7f-b7e93bc88e3d.png)
![AFTER WATER](https://user-images.githubusercontent.com/87881787/154166960-19d01518-5f48-4663-ba91-c207a1320548.png)
![FArm nft backgrund](https://user-images.githubusercontent.com/87881787/154167082-191eef5a-e544-4da5-9855-b7f4563af56e.png)

**Comment by adamhannigan** [comment]
Well done to all submissions. This was definitely the best art we have had submitted to the project. You should all be so proud 🤗 

We have a winner 🏆 👏  @noprudhon  

A crowd favourite on Twitter and it looks awesome! 

<img width="1428" alt="Screen Shot 2022-02-16 at 10 03 21 am" src="https://user-images.githubusercontent.com/11745561/154279741-8511aa8c-4f7d-480f-a25e-119e15920dd3.png">

Drop your Polygon address and you will receive the first ever'Farm' pack:

- 50 wood
- 50 stone
- 50 iron
- 50 gold
- Farm Dog
- Farm Cat

**Comment by noprudhon** [comment]
WOW! I'm speechless!

First of all, thank you for the team of Sunflower Land for this opportunity, as well as everybody for choosing my design.

Of course it feels great to win, but even more so to be now an integrant part of this project!

Here's my Polygon address:

0xDb96c32B1503524543691D2F53E671019A26a4BE

Thank you again and congratulations to all the artists that help make this project a reality!
