### ISSUE TITLE
[PROPOSAL] Withdraw Limits to protect the economy

### ISSUE THREAD

**Issue by Stevew00dy** [sunflower-land/sunflower-land#257]
We want to ensure that we have a great game and a healthy economy. We want people to earn money from their time invested but we need to also be realistic that the money generated has to be in return for value (time spent) 

As a result we need a system in place to limit the immediate removal of assets to deter bots and also pump and dumpers. 

My suggestion is a Tier based withdraw system that is baked into the gamification as follows

Farm Level 1 - 4 = No withdraw option

Farm Level 5 = X Limit per week (enough to feel good but not too much to damage the economy)

Farm level 10 = Y Limit per week 

Farm level 15 = No Limits (But would require minting a Bank NFT to enable) - Bank unlocks at lvl 15

The concept of the bank is that the requirements to mint could be adjusted depending on the volume of the economy to protect abuse and to ensure that stability is maintained during key growth phases.

**Comment by adamhannigan** [comment]
@Stevew00dy Well thought out 👏 

If you could pick just one item (restriction) to build out in a prototype for launch, which would it be?

**Comment by AncientHorse** [comment]
Somewhat related, how do players deposit SFL?  For example, if a player wants to buy SFL on Quickswap to mix with pumpkins they grew...

**Comment by SteveChickenCX** [comment]
How about a functions that increases the fees of withdrawal by the amount of withdrawals in a time period?

**Comment by adamhannigan** [comment]
@Pranav-yadav 

I think a player should be able to withdraw an item they craft at any point in the game. Players deserve 100% ownership of items they craft and that is what we are about.

I do like Steve's approach as it is very straight forward / not too complex. We will need to tweak the solution as we can identify what behaviours real players are doing and what behaviours the click-farmers / bots are doing. But as an MVP, I believe it would get us closer to reaching the goal of minimising the harm bots could do.

Tying a withdraw tax/restriction to a farming level also gives users incentives to upgrade and progress their farms. We could do something like the following:

Initial - 30% tax and maximum 1 SFL
Level 2 - 20% tax and maximum 10 SFL
Level 3 - 15% tax and maximum 50 SFL
.... so on

That way it is not too restrictive and will encourage people to progress their farms (from an ROI point of view)

@SteveChickenCX I think this is the direction we will go. A mix of AI / algorithms that we can fine tune to reward players contributing to the ecosystem.

@AncientHorse If you buy SFL (or an item) on an exchange, you send it to your farm's address:

<img width="309" alt="Screen Shot 2022-02-13 at 8 23 54 am" src="https://user-images.githubusercontent.com/11745561/153750735-e00d2416-d216-40e5-bb10-0beb3e6476db.png">

**Comment by noprudhon** [comment]
It may not be easy to implement but a system that could be interesting would be a base decreasing high tax with carry over effect.

Say in exemple a starting tax of 30% that decreases by 2% each day to a minimum of x%. In this first step, players can withdraw at any time but the earlier they claim the higher the tax would be. As such it would be in their interest to wait the longest time possible before making a claim.

After each claim, the tax is reset to its initial base value (30%) plus any previous tax paid. If a player decides to claim at say 16% tax, its timer after the claim would then be set at 46% tax (30% base + 16% penalty from previous claim).

This will highly penalize people or bots trying to claim often, while allowing player to claim whenever they feel like it, if they are willing to pay the penalty fee.

**Comment by Luke9086** [comment]
I think it is definitely not a good idea for our game. We aim to build a decentralized community and metaverse. Everyone has completely control of their assets. If we imposed such restrictions, no one would come to  the game and it would be  impossible for us to flourish! The community has proposed a tax to avoid draining the game which is good enough. We have to keep decentralized and make the game charming  and desirable.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
