### ISSUE TITLE
Visit other farms

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#258]
We want to encourage people to share and visit other people's farms. 

## Goal

- Players will 'share' the link to the farm = free marketing
- Players are incentivised to craft collectibles so they can show them off
- Foundations for cooperative farming.

## How would this work?

You can explore someone's farm by using the `tokenId` of their farm ID. This would go in the URL as a query parameter.

In this case, we are using the 5th minted farm.

`https://sunflower-land.com/play?id=5`

We would load the data directly from the Blockchain - This means it would not display any in-progress farm session data such as planted crops.

**Technical considerations**

In `authMachine` detect if the `id` is in the query parameters. If so, transition into `visiting` state once they have connected to MetaMask. 

In `gameMachine`, if they are in visiting mode then do not load data from the API. Instead load all of their items from the `Inventory.ts` smart contract and their balance from `Token.ts`.

Since planted crops are stored off chain, display Sunflowers in all of the fields instead.

**Comment by Pranav-yadav** [comment]
Most awaited feature, for me at least :)
Whoever works on this feat will definitely gain confidence boost 🚀 as it involves most of the logic of whole game itself.
Best of luck 👍

Will be following this discussion as well, under the upcoming feat PR, to build my knowledge and provide some suggestions.

**Comment by Pranav-yadav** [comment]
> https://sunflower-land.com/play?id=5

@adamhannigan wouldn't it be less confusing & accurate to use **`/farm`** instead of `/play` 🤔, like;
`https://sunflower-land.com/farm?id=<tokenId>`

**Comment by Pranav-yadav** [comment]
Partial, goals feat. merged #296 👍
