### ISSUE TITLE
[BUG] Resources not showing up in farm storage and trade

### ISSUE THREAD

**Issue by gangsteryepyedye** [sunflower-land/sunflower-land#2581]
## Summary of Bug

I tried to trade resources in goblin retreat but it's not showing my resources neither in farm storage or banks, and my sfl amount is not the same on home and goblin retreat, I sold my sfl land once and bought one off opensea.io not sure if that matters

## Steps to Reproduce

go to goblin retreat, click on storage and trade, try to find the resources I have, only showed up two stones

## Expected Behavior

I want to show resources and my sfl in goblin retreat page

## Actual Behavior

only showed two stones and little sfl

## Screenshots

![screenshot1](https://github.com/sunflower-land/sunflower-land/assets/480693/b458d379-2d4a-4a04-9b9e-7cdce1d0807a)
![screenshot2](https://github.com/sunflower-land/sunflower-land/assets/480693/3058b780-8278-4259-94ba-602171a9574f)
![screenshot3](https://github.com/sunflower-land/sunflower-land/assets/480693/b53b2c3d-0b12-4312-88a7-40d582af5b8c)

**Device Information (please complete the following information):**

- Device: PC
- OS: Windows
- Browser/App Edge
- Version 113

**Comment by gangsteryepyedye** [comment]
ok I find the way to sync data on blockchain but it's asking me 4 matic to do so, is it normal

**Comment by elias7905** [comment]
Not a bug, you just need to sync data on chain

**Comment by gangsteryepyedye** [comment]
ok！
