### ISSUE TITLE
🖼 Fanart Competition #1

### ISSUE THREAD

**Issue by CaioCastelo** [sunflower-land/sunflower-land#2633]
Farm: 163639
Discord: Caio C.#6125

![PixelFanArtByWhite2](https://github.com/sunflower-land/sunflower-land/assets/94916379/0c8dd770-fcd2-42b2-83c6-0638abe20b86)

This one was a lot of work, I hope you like it :)

**Comment by future2back** [comment]
@CaioCastelo Hello Friend! Perhaps this topic would be better suited as a discussion rather than an issue.
Thank you.
