### ISSUE TITLE
[BUG] Wallet connect will not connect to dapp through trust wallet.

### ISSUE THREAD

**Issue by proxy7777** [sunflower-land/sunflower-land#2696]
## Summary of Bug

Trust wallet will no longer connect to dapp through new wallet connect.

## Steps to Reproduce

Open dapp on browser and try to connect through trust wallet

1. TODO

## E

To connect to dapp

## Actual Behavior

Just says connecting and no signature request pops up

## Screenshots

**Device Information (please complete the following information):**

- Device: smartphone
- OS: [Android]
- Browser/App ] Brave browser 
- Version

**Comment by future2back** [comment]
Hello friend @proxy7777, can you tell us if this issue has been resolved?
Thank you.
