### ISSUE TITLE
[PROPOSAL] Sunflower Fair Capsule Machine

### ISSUE THREAD

**Issue by ExtremeCheddar** [sunflower-land/sunflower-land#274]
**Sunflower Fair Capsule Machine**

Think of it as a giant gumball machine where you put in your token and you twist the handle, a capsule then comes out of the machine and you open it to reveal your prize.

**Sunflower Fair Token**
We would get the SFL team to create a Sunflower Fair Token(SFT) which would act in the same way as Eggs or Gold. You will be able to purchase SFT tokens and they will each cost 1 SFL. The SFT used to play the Capsule Machine would be burned.

There will be a hard limit on the number of times you can use the Capsule Machine per day. We may release NFTs which will increase this hard limit.This would be the first project that would utilise SFT, any other project in the Sunflower Fair would also use SFT.

**Capsule Machine Options**
There will be 3 options to use on the Capsule Machine:
1. Spend 10 SFL to return a capsule with 10 SFT after a set period of time
2. Spend 10 SFL to return a capsule with either 0, 10 or 30 SFT after a set period of time
3. Spend 10 SFT  for a capsule that could win prizes.

**Capsule Machine Prizes**
The Capsule Machine would have a number of prizes inside, the most valuable of those would be existing Sunflower Land NFTs that we have bought from Opensea. The remainder of prizes will be made up of SFT tokens.

The chance of winning a rare NFT will be very low, as we will need to try and make back the cost of purchasing the NFTs. But this will give everyone a chance to win something they might not be able to afford. We will also be adding the cost of transferring the NFT into the overall cost when working out the odds of winning each prize.

10 SFT to use the Capsule Machine

A sample of prizes you may see in the Capsule Machine:
1 - Christmas Tree
2 - Sunflower Statue
4 - Scarecrow
1 - Chicken Coop
200 - 50 SFT
400 - 20 SFT
800 - 10 SFT
3000 - 5 SFT

The above are all just example numbers and we will release the exact formulas used for working out the odds of winning each prize. We may even be able to display these so that everyone is aware before using the machine.

**Comment by SFL-Aeon** [comment]
Seems interesting. In regards to the prizes I know you said sample yet offering NFTs that they said would never be minted again undermines integrity. If you said NFT equivalent to the rarity of a Christmas tree or similar to the Christmas tree that would be something different.

also in regards to the capsule generating SFT over time seems like a way to limit the number of SFT that could be used by a player. If the idea is to have the entire fair use SFT and it’s not around 24/7 then that restricts users from using the content. 

I’m not well verse enough to review the prizes but my thoughts on the stuff mentioned.

**Comment by ExtremeCheddar** [comment]
@SFL-Aeon There would be no new minting of any NFTs, they would be bought by us(Sunflower Fair Team) from Opensea and then used in the Capsule Machine. As new NFTs are released by the Sunflower Land team we would also purchase some of these to add the to Capsule Machine.

The content will be around 24/7 so you will be able to use it when ever. But just like planting a sunflower you cant harvest it until a period of time is up, and we would be doing the same for SFT. This is to cap people from just buying a bucketload of SFT and spamming the games, this gives everyone a daily chance or two to play the machines and win. We can also look into releasing NFTs which would increase the amount of times you can play the Capsule Machine per day.

**Comment by SFL-Aeon** [comment]
> @SFL-Aeon There would be no new minting of any NFTs, they would be bought by us(Sunflower Fair Team) from Opensea and then used in the Capsule Machine. As new NFTs are released by the Sunflower Land team we would also purchase some of these to add the to Capsule Machine.
> 
> The content will be around 24/7 so you will be able to use it when ever. But just like planting a sunflower you cant harvest it until a period of time is up, and we would be doing the same for SFT. This is to cap people from just buying a bucketload of SFT and spamming the games, this gives everyone a daily chance or two to play the machines and win. We can also look into releasing NFTs which would increase the amount of times you can play the Capsule Machine per day.

Must’ve missed the part you said buy, which you clearly did (My bad). 

I personally think if this goes through implementing a new NFT rather than buying NFTs at the start. Later on when the older NFTs are rarer then maybe as a grand prize or jackpot you could do so. 

I think bringing on some artist will be needed for the fair concept anyways so why not have them draft up some rewards as well.

In regards to the tokens I assumed the token would be used on various things outside just this once instance which is why I mentioned it. What I personally would like to see is the fair as it’s own map and sprite and mini games that occurs once a week or strictly over the weekend. You could still have the coins be passed on a growth cycle but this makes it something people don’t get bored of doing every day and gives some elusiveness to it. Just my thoughts though

**Comment by ExtremeCheddar** [comment]
@SFL-Aeon We were thinking about creating some of our own NFTs, but the hard part is making sure they have some kind value associated with them so that people want to play the game to acquire them. I think having a mixture would be a nice balance as some of the previous NFTs like the Chicken Coop are very limited in number compared to the amount of people playing the game at the time.

This would be just the first of many games we would introduce to the Fair but want to make it fairly easy and straight forward to start with just because this will be our first "crypto" project, and want to make sure we get it right before getting more complex.

**Comment by adamhannigan** [comment]
@ExtremeCheddar I am wondering if there is a minimum prize that users could also get. I.e. a piece of coal or cow dung.

This could just be 'joke' items that ensures that a player is actually receiving something in the exchange.

**Comment by ExtremeCheddar** [comment]
@adamhannigan We could easily ad a joke prize that you would get and could potentially use for something later on down the track. Would there be anything else needed to get approval to start putting it all together?

**Comment by Stevew00dy** [comment]
I wonder if there is a need to have SFT or if that step can be removed to simply use SFL as a burning mech .

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
