### ISSUE TITLE
[ART] Crop Boosts

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#278]
This is an art request for a range of different items which will be used to 'boost' farming abilities. These will be limited in supply (100-2000) and can only be crafted at the Blacksmith.

The purpose of these items will be to give a special buff to players and act as a unique decoration on your farm. These could be golden statues, lucky trinkets, special potions etc.

Whatever crop you choose, the ingredients will include the crop which it will give a boost to.

**Example**

Lucky Rabbit. Those with a lucky rabbit will receive twice the carrots when harvesting.

To craft a lucky rabbit you need to collect 100 carrots + 50 SFL.

**Available Crops**

We already have a design for the Cauliflower and I am thinking of repurposing the Potato Statue & Sunflower Statue to give a buff. 

The remaining crops that need a 'Special item' are:

- Pumpkin
- Cabbage
- Parsnip
- Beetroot
- Carrot
- Radish.

# Prize

Each of these items will be limited in supply. For each winning crop design, the artist will be airdropped the item they have created.

**Deadline**

We will want these items to be live on launch to provide more utility for the crops - **27th February**

**Requirements**

Refer to the Art specs here: https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

**Comment by Sarapico** [comment]
Pumpkin : Jack O'Lantern
![pixil-frame-0 (11)](https://user-images.githubusercontent.com/98893182/154368252-75a8f7b0-5c94-4144-af6e-7d9a53a1177e.png)
![pixil-frame-0 (15)](https://user-images.githubusercontent.com/98893182/154368261-e8092277-4d75-4e62-bc53-52aa54378bc2.png)

*still thinkin in some adjust maybe

**Comment by Aestnelis** [comment]
Radish: Radish Spirit from Spirited Away
![radish spirit](https://user-images.githubusercontent.com/98103679/154378927-7cae25c9-edbd-442d-b44c-72134a2c8868.png)
![bigradish spirit](https://user-images.githubusercontent.com/98103679/154378962-c33b4124-46b4-4bf9-a751-f1c15e350e96.png)
![image](https://user-images.githubusercontent.com/98103679/154379009-96c4bc16-4a24-4813-971d-2f498ef51419.png)

**Comment by gabiqueiroga** [comment]
I made two kinds of potion bottles so they can be part of a collection and have two purposes: one could drop more crops and the other could make them grow faster.

Ex: Beetroot Potion. Is it just beetroot juice? It makes beetroot grow 2x faster anyway.

Empty / Pumpkin or Carrot / Beetroot or Cabbage /  Radish  / Parsnip

![image](https://user-images.githubusercontent.com/69090306/154400233-97dfbf13-b915-455b-b2c4-8aa67298ed2d.png)

**Comment by SFL-Aeon** [comment]
> 

I think this would be an awesome Halloween exclusive NFT.

**Comment by SFL-Aeon** [comment]
> Pumpkin : Jack O'Lantern ![pixil-frame-0 (16)](https://user-images.githubusercontent.com/98893182/154370482-6cc5ce66-b68b-4b59-88d0-269253770558.png) ![pixil-frame-0 (17)](https://user-images.githubusercontent.com/98893182/154370497-19341076-1e78-4ca3-b66d-4e1d0ee25cef.png) ![pixil-frame-0 (18)](https://user-images.githubusercontent.com/98893182/154370503-5dda337e-21b0-4557-8e5d-a568cc39de32.png)
> 
> *still thinkin in some adjust maybe

I think this would be an awesome Halloween exclusive NFT. Would fit the season and time.

**Comment by paluras** [comment]
The radish friend came to cheer up his fellows and make them grow faster.

![image](https://user-images.githubusercontent.com/98059798/154458117-b74b5c0e-b356-4a61-a309-cfec33949195.png)
![radishfriend](https://user-images.githubusercontent.com/98059798/154458135-7e17726d-fe78-4a0a-b256-ce9ac2fbfef0.gif)
![radishfriendx300](https://user-images.githubusercontent.com/98059798/154458138-3d160c86-cef0-4ce5-9959-6a021bd187d4.gif)

**Comment by Alexcnder** [comment]
Parsnip the Turtle He normally lives below the sea but his love for parsnips is bigger
![Sea turtle save 1](https://user-images.githubusercontent.com/87881787/154492475-f346bece-5776-4d18-bc7e-e631cd1c2a44.png)

**Comment by Z1kou** [comment]
My Idea of  A Pumkim The Wizard Pumpkin:
![PUMKIN ELDER WITCH HAT PURPLE](https://user-images.githubusercontent.com/98262339/154495194-d418f2fd-3c1f-4719-b90d-52a72c5a2e55.png)

Him Using magic !
![PUMKIN ELDER WITCH HAT PURPLE](https://user-images.githubusercontent.com/98262339/154495206-308383fe-1462-45c1-a489-a991d2bfdebd.gif)

Him In the Map !
![PUMKIN ELDER !](https://user-images.githubusercontent.com/98262339/154495235-90bac248-c9f2-4854-a6ef-f674704454e2.png)

**Comment by paluras** [comment]
Only the worthy will wield the carrot sword and its true power.

![image](https://user-images.githubusercontent.com/98059798/154512947-33a9295d-5d1f-4594-892c-92bacb0937ad.png)
![carotsword](https://user-images.githubusercontent.com/98059798/154512983-8644bf80-ca7c-454a-be0e-b088bfbab754.png)
![carotsword2](https://user-images.githubusercontent.com/98059798/154512988-5e5be224-d502-4bec-a015-b85c6d892b79.png)
![carrotattack22-export](https://user-images.githubusercontent.com/98059798/154513002-c3ea26c2-e02b-443d-aa45-d62503915997.gif)

**Comment by Aestnelis** [comment]
Little Dancing Beetroots
![lil dancing betroots](https://user-images.githubusercontent.com/98103679/154529538-ec4e2fd3-5078-44ff-9212-2a455d4ff48d.gif)
![big dancing betroots](https://user-images.githubusercontent.com/98103679/154529548-2d925d7e-3a92-4327-b0c8-d917229d431c.gif)
![bigg dancing betroots](https://user-images.githubusercontent.com/98103679/154529565-4e7b0396-c7c2-4c3e-98fc-1c5990418252.gif)

**Comment by Sarapico** [comment]
Beetroot: legends say the first beet came from an ancient forest creature.
![pixil-frame-0 (30)](https://user-images.githubusercontent.com/98893182/154552471-de98ef7c-de4b-450f-9ac0-d6d90de9aa01.png)
![pixil-frame-0 (31)](https://user-images.githubusercontent.com/98893182/154552484-ffc3cae4-d47b-41a1-b46f-4353ec86b409.png)
![pixil-frame-0 (32)](https://user-images.githubusercontent.com/98893182/154552487-48a45ff4-4afc-471c-b76a-1ab2d7868ee3.png)

**Comment by Alexcnder** [comment]
> Hey @Alexcnder you turtle is very cool, but what about a different head?i made a example for you. feel free to use, improve or discard, its just an idea. ![pixil-frame-0 (6)](https://user-images.githubusercontent.com/98893182/154729330-757f9d8d-b716-43f5-81f8-9cb09dbe42bb.png)
>
@Sarapico Great idea i made some slight adjustments
![Sarapico](https://user-images.githubusercontent.com/87881787/154732975-dee64e9f-5f48-4eab-9a5c-2e06a466f110.gif)

**Comment by adamhannigan** [comment]
@Sarapico Love it! Looks like a smurf ;)

We have to be careful using the base asset pack (Goblin assets) as we don't want to use them in NFTs to avoid looking like reselling art

**Comment by kimberlite07** [comment]
Hi, Adam. Would just like to air a concern. I hope you guys consider some caution if you ever decide to give crop boost to every crop.

If the reason for this is to burn tokens, maybe we can look at other NFTs.

Providing NFTs that boost for every plant will definitely not be healthy to the economy of the game. 

Boost for crops that take a lot longer time to harvest does make sense because of 1) lower yield, 2) longer waiting time. If you provide boosts for high yield, faster growing crops; growth of token supply will become unhealthy. Furthermore, high yield, faster growing crops doesn't need "boosts" since at the first place, they grow faster and give higher yield. They do not have anything "lacking" for them to need boosting.


That's all. Looking forward to new developments!

**Comment by adamhannigan** [comment]
Great points @kimberlite07 

You are right, we are not planning to saturate these boost items in the game. 

If we introduce low level crop boosts, they would be for separate purposes - e.g creating Golden carrots (each carrot has a X% chance of turning into Gold)

**Comment by adamhannigan** [comment]
These were hands down the most creative submissions we have ever seen 🤗 Awesome work everyone 👏 The art is getting better and better each week.

For this round, we have chosen 2 winners. There will be more items in the future and more chances to get your items in. We will likely come back to this list and choose some more winners so stay tuned.

@benaxol12 Mysterious Parsnip
@paluras Carrot Sword

Congratulations 👏 🏆
