### ISSUE TITLE
> This is definitely something that came across my mind too. Maybe we could trade the animal to the goblin butcher and then you get back impossible meat (fake meat). There can be some narrative that goblins are vegetarians and they put on the cows on cow island where they live happily forever.

### ISSUE THREAD

**Issue by Chucrutty** [sunflower-land/sunflower-land#2888]
> This is definitely something that came across my mind too. Maybe we could trade the animal to the goblin butcher and then you get back impossible meat (fake meat). There can be some narrative that goblins are vegetarians and they put on the cows on cow island where they live happily forever.

Ohhh not bad! Build some lore around goblins collecting cows for a secret project they are planning.... and they trade in this magic meat to the player... Players can decide themselves if goblins are really butchering cows or planning something else 👀

_Originally posted by @TheDcol in https://github.com/sunflower-land/sunflower-land/discussions/2240#discussioncomment-4979641_

**Comment by Chucrutty** [comment]
take off the name Meat, put some thing like nutrients

**Comment by future2back** [comment]
@Chucrutty Hello Friend! Perhaps this topic would be better suited as a discussion rather than an issue.
Thank you.
