### ISSUE TITLE
[CHORE] Move the mint of Fruit Picker Set and Pirate Set to Farm instead of Wallet

### ISSUE THREAD

**Issue by eliasSFL** [sunflower-land/sunflower-land#2914]
## Summary

Ever since the feature to deposit bumpkins, any wearable that was introduced after that was either added into the API of the user's farm or minted to the user's farm, rather than minted in the user's wallet, however, currently, the mints of the Fruit Picker Set and Pirate Set still happens in the user's wallet.

## TODO

Please provide a list of TODOs, which will therefore complete this core.

1. Change the Smart Contract to mint the wearable into the user's farm instead of the user's wallet

**Comment by future2back** [comment]
Hello friend @elias7905, can you tell us if this issue has been resolved?
Thank you.
