### ISSUE TITLE
[BUG] Onboarding workflow shown for existing players as well

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#292]
## BUG:
- Onboarding flow (Game Tutorial) is shown for existing players as well.
- looks like same thing is happening while **Visiting Farm** as well, only on _localhost_ .

## SCOPE:
UI/UX

## IMPACT:
🔴 CRITICAL

## EFFECTS:
- -1SFL Player's loss, 🕐  😢 

## CAUSES:
_debugging..._

## FIX:
Let's discuss !

---
more related bugs to be added..

**Comment by jcads** [comment]
I also encountered this bug the very first time I loaded the game after it mas merged with main. I also got the onboarding tutorial when I visited a farm.

**Comment by jcads** [comment]
I think it has something to do with this code
https://github.com/sunflower-land/sunflower-land/blob/ad6ed79f5b46279739ef7fa6b436383fc6026713/src/features/game/lib/gameMachine.ts#L105-L112

**Comment by Pranav-yadav** [comment]
@adamhannigan  https://github.com/sunflower-land/sunflower-land/commit/0bf0b5de310fec7de65cb51401fb532259d9fa9b should fix this issue ?

**Comment by Pranav-yadav** [comment]
This Bug, #292 , is Fixed through commit https://github.com/sunflower-land/sunflower-land/commit/0bf0b5de310fec7de65cb51401fb532259d9fa9b  ,pushed by @adamhannigan
