### ISSUE TITLE
[BUG] Huge Item count overflows are shown

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#294]
## BUG:
Huge Item count overflows are shown 👀 . See the screenshots 👇 

<details><summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/55224033/154746493-07b55f26-9c4d-45bd-ba5d-ffa2ed6b471b.png" />

<img src="https://user-images.githubusercontent.com/55224033/154746924-0c809b2b-7dc7-42f5-aec8-385ec83fcf26.png" />
</details>

## SCOPE:
UI/UX

## IMPACT:
🟠 LOW

## EFFECTS:
rich farmer's opening inventory on mobile -> 😕
😆 

## CAUSES:
_debugging.._

## FIX:
Let's discuss !

---
PS: It's a known issue/bug :)
Desc.: TBA

**Comment by adamhannigan** [comment]
@Pranav-yadav This is related to a change in the way we handle crops. We have made them conformant to the 18 decimal ERC20 standard. This makes it easier to trade them in liquidity pools.

This won't be an issue anymore but may exist on some old testnet accounts (until we nuke the data)

**Comment by Pranav-yadav** [comment]
@adamhannigan you might need to reopen this issue as the count overflows are shown on the **Mainnet** as well see 👇 

![image](https://user-images.githubusercontent.com/55224033/155743562-95d9532b-4a54-4d3f-a283-4e782e673824.png)
![image](https://user-images.githubusercontent.com/55224033/155743792-734e9ddc-11b3-435b-90d1-740885f5ff72.png)

Even showing exponents isn't looking good see 👇 
![image](https://user-images.githubusercontent.com/55224033/155744446-b1bdf42b-fee8-4b7f-95b2-9d34abbb874e.png)


I've a fix in mind, should I open a PR ?
