### ISSUE TITLE
[BUG] 🔴 Input type `text`, in visit farm

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#297]
## BUG:
In Visit Farm Modal, inside the form, the input type is set to `text` tho, `FarmId`'s seems to be of type `number` 😕 

## SCOPE:
UI/UX

## EFFECTS:
- leads to other bugs;
- Unable to use <kbd>⬆️</kbd> & <kbd>⬇️</kbd> keys for manipulating it's value from kbd _(no one likes to <kbd>⬅️ Backspace</kbd> and manually enter just to ++/-- by 1-2)_

## IMPACT:
🔴 CRITICAL (UI/UX)

<details><summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/55224033/154794731-2e4d3c4b-e3f6-47ea-96a3-ad6e0a5d5090.png" />
</details>

---
_debugging..._

**Comment by j923sneaks** [comment]
I wouldnt say critical coz there's still validation i.e. clicking visit does nothing. but feel free to add `number` type 😄

**Comment by Pranav-yadav** [comment]
> I wouldnt say critical coz there's still validation i.e. clicking visit does nothing. but feel free to add `number` type 😄

Yep @j923sneaks It's not critical under technical/code scope 😄 , rather is under UI/UX scope when u consider production grade UI/UX.
