### ISSUE TITLE
[BUG] 🔴 Unable to go back to page, shown after signing

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#298]
## BUG:
After player signs the metamask request and clicks on "**Explore a friend's farm**" _by mistake :)_ they can **_not_** go back. 😞 

## SCOPE:
UI/UX

## EFFECTS:
- need to reload/refresh the page :(

## IMPACT:
🟠  😞 🧑‍🌾 

## FIX:
- Back button should be provided

---
Related to (#issue) _TBA_

**Comment by j923sneaks** [comment]
Fair enough, having `Back` to go back to `readyToStart` state

**Comment by Pranav-yadav** [comment]
Fixed by #299 :)
