### ISSUE TITLE
[BUG] Farm Address Confusion

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#307]
This issue aims to address the confusion around the farm address in the bottom right of the HUD.

<img width="306" alt="Screen Shot 2022-02-21 at 9 25 33 am" src="https://user-images.githubusercontent.com/11745561/154955005-5e6f841e-752d-4a91-8551-15b653f380ae.png">

**Problem**

Players continuously think this is a bug since it is different to their MetaMask address.

**Suggestions**

I don't have a solid suggest yet but here are some options:

1. Add a label to the UI - `Your Farm's NFT address - Send tokens here`

2. Remove it

The purpose of this address is so players know where to send their tokens to. To avoid confusion, this may be better presented in a modal. I.e. You click an in-game bank and it provides instructions for sending SFL to your farm.

**Comment by jcads** [comment]
Maybe we could change the icon to something different that closely resembles the Farm NFT.

**Comment by Rofrtd** [comment]
Can we have an option on the menu like `Farm info`? 
This would open a modal with general info like farm-id, address, maybe even date created...

**Comment by spencerdezartsmith** [comment]
I think the farm address will be useful when people are withdrawing. We can a tooltip or a title to it that says farm address, also we can add the farm NFT image instead of the person to indicate this.

**Comment by adamhannigan** [comment]
@spencerdezartsmith Is this something you think would help players when withdrawing? I feel like we can abstract this away from most of our gamers as it does not really assist the 'withdraw' process.

The less information, the simpler it can be

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith Is this something you think would help players when withdrawing? I feel like we can abstract this away from most of our gamers as it does not really assist the 'withdraw' process.
> 
> The less information, the simpler it can be

Yeah true. Then let’s take it out and have it on hand to add back if we feel like it adds value when people have multiple farms?

**Comment by adamhannigan** [comment]
@spencerdezartsmith Sounds good to me 👍

**Comment by Pranav-yadav** [comment]
> Can we have an option on the menu like `Farm info`? This would open a modal with general info like farm-id, address, maybe even date created...
Yep.

@Rofrtd u might wanna see PR #296 for something similar ??
