### ISSUE TITLE
[PROPOSAL] Token burn and reduce multi-account

### ISSUE THREAD

**Issue by plofus** [sunflower-land/sunflower-land#308]
-Hello everyone, my idea aims to burn tokens and try to reduce multi-account. To explain my idea simply, the developers will create a huge land where each player can rent a small part of this large land and plant their vegetables there against SFF which will be burned. For prices and quantity I let you debate if you liked the idea. This message was written in French and translated by google translation.
Plofus

**Comment by adamhannigan** [comment]
@plofus You may be intersted in the #215 proposal around land expansion.

The idea is that you would spend SFL to mint new land as an NFT 🤗  Is this similar to what you were thinking?

**Comment by plofus** [comment]
@adamhannigan In the heart of the idea it is quite similar except that my idea aims to burn tokens and therefore to increase its price. Moreover, by renting a plot, you will have to pay, the rental and the seed. But his idea remains approximately the same as mine.

**Comment by adamhannigan** [comment]
Closing so we can focus attention on #215 and centralise feedback there 🤗
