### ISSUE TITLE
[ART] Sunflower Land Bank

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#309]
This is a request for a Sunflower Land bank. This would be used to withdraw and deposit SFL into the game.

It should ideally be the same size as the market or blacksmith.

**Requirements**

Since this is not an NFT, we can use the base asset pack from Sunny Side. The art should fit in nicely with the other building in the game :) 

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

**Deadline**

26th February.

**Winner**

Pick your item: Dog, Cat, Golden Egg or Coop ⭐

**Comment by Z1kou** [comment]
Finally we can add More shine to the game !

**Comment by ItsNight** [comment]
![image](https://user-images.githubusercontent.com/43474459/155034588-02386dd4-79fb-43a0-aef8-906fed39e2d6.png)

**Comment by ItsNight** [comment]
![image](https://user-images.githubusercontent.com/43474459/155034598-478cf83c-35bb-429d-8915-44f2fb432425.png)

**Comment by ItsNight** [comment]
![image](https://user-images.githubusercontent.com/43474459/155035071-31ecbfa1-70b4-444b-84a9-7dd8d6d79f5a.png)

**Comment by ItsNight** [comment]
![image](https://user-images.githubusercontent.com/43474459/155035084-f6d57e1b-a85e-42ca-9e90-50d7d1eb8ed9.png)

**Comment by Aestnelis** [comment]
Will add here!

**Comment by paluras** [comment]
![Bank](https://user-images.githubusercontent.com/98059798/155120349-d7ff9827-15d0-47dd-a174-99cbb69510d0.png)

![image](https://user-images.githubusercontent.com/98059798/155120185-068e7263-6582-4e47-b020-ec4191022d5b.png)

**Comment by Aestnelis** [comment]
![bigsunflowerbanks](https://user-images.githubusercontent.com/98103679/155238617-b2846123-7240-4ea3-81bf-b402bb27d7ac.gif)
![biggysunflowerbanks](https://user-images.githubusercontent.com/98103679/155238651-00983b4d-1044-4060-9e61-73591081dab1.gif)
![littlesunflowerbanks](https://user-images.githubusercontent.com/98103679/155238669-37344821-b183-426a-acc8-cd617dd1c6ec.gif)

**Comment by Sarapico** [comment]
![pixil-frame-0 (45)](https://user-images.githubusercontent.com/98893182/155443143-a8ac740e-e3bd-4e3b-af94-1f8bfefe6ea3.png)![pixil-frame-0 (42)](https://user-images.githubusercontent.com/98893182/155443156-925b38b6-e67f-4490-b347-fbff17eaa143.png)
![pixil-frame-0 (26)](https://user-images.githubusercontent.com/98893182/155443174-238f0907-412b-4cc3-955a-60637e6be85e.png)![pixil-frame-0 (25)](https://user-images.githubusercontent.com/98893182/155443179-e186b023-9a66-4df8-8539-2f511eec2d01.png)
![pixil-frame-0 (27)](https://user-images.githubusercontent.com/98893182/155443188-60e003a8-eed8-44ec-8f6b-eaea207813df.png)

**Comment by cambrios1** [comment]
![bankinart](https://user-images.githubusercontent.com/98171636/155512920-b3358b48-f532-433d-ae29-3e4929f5f5d5.jpg)

![bank_large](https://user-images.githubusercontent.com/98171636/155512927-65e6e037-b86d-4217-907f-33c466749d57.png)

![bank](https://user-images.githubusercontent.com/98171636/155512941-4edec729-9831-4807-b344-a50f0cb5012f.png)

**Comment by SFL-Aeon** [comment]
> design!
> 
> Small SFL Bank (png)

I think this would better as a farmers market or where players go to trade resources between others

**Comment by benaxol12** [comment]
![Bank1](https://user-images.githubusercontent.com/98098031/155836285-88babd27-4dde-46e8-afd9-652f0ca627db.gif)
![bankpng](https://user-images.githubusercontent.com/98098031/155836344-a2abfbe0-d18e-4533-800d-db7c72f941fa.png)
![Bank 12](https://user-images.githubusercontent.com/98098031/155836185-ae323693-b5b4-4d43-af4d-044f382299d2.gif)

**Comment by adamhannigan** [comment]
This was a really hard decision between @paluras and @Aestnelis 

The winner is @Aestnelis 👏 Congratulations 🏆 

Amazing work and thanks for the different options. Would it be possible to get #2 in the same color palette as #4? #2 is my favourite but the colors are a bit dark

**Comment by Aestnelis** [comment]
Hey, that made me so happy!! Thanks a lot! @adamhannigan If want more edit i can change with pleasure. 
![lilChosenbank](https://user-images.githubusercontent.com/98103679/155880776-cf218dcf-99d8-40e0-9151-e28dbe16b6b0.gif)
![bigChosenbank](https://user-images.githubusercontent.com/98103679/155880777-2b53eff6-b5b5-4278-ae3c-8a81d5de8cd4.gif)
