### ISSUE TITLE
[BUG] error

### ISSUE THREAD

**Issue by LeksLuter** [sunflower-land/sunflower-land#3139]
## Summary of Bug

Provide a brief summary of the bug you found. 

Error when going home

## Steps to Reproduce

Goblin village, crossing the planet to the village. Sometimes this error occurs.

## Screenshots

![2023-11-12_18-01-22](https://github.com/sunflower-land/sunflower-land/assets/40381491/ce3f2200-f97c-4321-b162-ba6479f96355)

**Device Information (please complete the following information):**

- Device: [PC]
- OS: [, Windows x64,]
- Browser/App [chrome, metamask app]

**Comment by 0xSacul** [comment]
Hey @LeksLuter, are you still experiencing this issue?

**Comment by LeksLuter** [comment]
Got caught yet
![2023-11-25_16-57-46](https://github.com/sunflower-land/sunflower-land/assets/40381491/66702d86-c211-46df-8f2d-29bf84a7122b)
Appears when canceling a sale in the goblin village
![2023-11-25_17-01-43](https://github.com/sunflower-land/sunflower-land/assets/40381491/c289d843-08e0-4eb8-815d-b66622eb75b1)



> Hey @LeksLuter, are you still experiencing this issue?
The error is gone

**Comment by future2back** [comment]
Hello friend @LeksLuter, can you tell us if this issue has been resolved?
Thank you.
