### ISSUE TITLE
[FEAT] Seed Crop Preview

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#333]
<img width="74" alt="Screen Shot 2022-03-06 at 6 56 10 am" src="https://user-images.githubusercontent.com/11745561/156918194-70858bc4-2e24-4d92-b5bf-d174ec9dc595.png">

As a player, it can be confusing seeing the images of seeds as they do not clearly indicate which crop they will produce.

**Includes**

When displaying a seed in the inventory/preview box, also display a small version of the crop that it will produce. This should appear inside of the same box (bottom right corner for instance)

**Comment by j923sneaks** [comment]
i think i can do this 😃

**Comment by j923sneaks** [comment]
@adamhannigan would consider bottom left position? I feel the right part the the shortcut is too crowded if the crop image is bottom right. then again, I don't see other games/apps have sub icons on bottom left. just asking :)

bottom left
![shortcut-cropImage-bottom-left](https://user-images.githubusercontent.com/89294757/157053095-6d3668c8-1a33-4f92-b926-1b5c5b06cf65.PNG)

bottom right
![shortcut-cropImage-1](https://user-images.githubusercontent.com/89294757/157053346-a4e6c80d-5e3d-4482-9050-0949b3adf362.PNG)

**Comment by adamhannigan** [comment]
@j923sneaks Neither look great to me. Could we minimise the seed as well?

I.e. the seed is in one corner, and the plant in the other corner?

**Comment by j923sneaks** [comment]
@adamhannigan how about this? I had to enlarge the box to properly fit them at the bottom corners

![image](https://user-images.githubusercontent.com/89294757/157140075-fff8e757-fdb6-4809-a4dd-6c73d1c9e0da.png)

**Comment by adamhannigan** [comment]
@j923sneaks Looking better now 👍
