### ISSUE TITLE
[FEAT] Improve Inventory

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#334]
A lot of feedback has been given throughout Beta around the inventory being difficulty and buggy to navigate.

The aim of this ticket is to make the inventory more usable. The main suggestion includes just having 2 tabs:

1. A tab for items (seeds, tools, crops all shown together)
2. A tab for collectibles (Food, NFTs etc.)

Also, when displaying on mobile we need to show more items horizontally so split the panes as shown below.

**Includes**

- Increase modal width on Desktop
- Increase modal height on mobile
- 2 tabs in inventory - Basket & Collectibles
- Fix warping of some inventory images

<img width="372" alt="Screen Shot 2022-03-06 at 7 00 00 am" src="https://user-images.githubusercontent.com/11745561/156918310-a875f90f-7ce9-40b5-8209-06a17e3f208a.png">

**Comment by shigo1** [comment]
I think that having buttons for the different inventory categories ( nfts, crops and resources) instead of the scrollbar/arrows
would give a smoother experience imo
