### ISSUE TITLE
[BUG] Seed Stock Mobile issue

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#335]
On mobile, the seed stock is wrapping onto the line of text (see attached).

**Expected Behaviour**

A user should be able to see the seeds in stock, and all of the image/text below when on mobile or desktop

![IMG_4529](https://user-images.githubusercontent.com/11745561/156918369-1ec8e5e4-4337-4aed-a7e9-8d8a536ed448.png)

**Comment by jcads** [comment]
Would something like this be good?

![image](https://user-images.githubusercontent.com/50954098/156933456-1c736431-61ef-4251-9255-5615a98079f3.png)

**Comment by adamhannigan** [comment]
@jcads Yes, much neater.
