### ISSUE TITLE
[BUG] Remove notification counter

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#338]
<img width="153" alt="Screen Shot 2022-03-06 at 7 13 04 am" src="https://user-images.githubusercontent.com/11745561/156918718-aae43bdd-3191-4eeb-b095-059dbc575a03.png">

The notification counter has been a source of confusion and bugs. Until we can implement it in a maintainable way, remove it from the code

**Includes**

- Removing all the code related to the notification counter

**Comment by j923sneaks** [comment]
indeed. i tried to maintain this but tbh the issues keep piling... I might take this one
