### ISSUE TITLE
[BUG] Metamask signature overflow

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#341]
Reported by @Pranav-yadav on Discord.

BUG: Message text shown in sign request in metamask is overflowing & overflow is clipped. (it's Metamask's bug, but, we can improve it😊)

BUG DESCRIPTION: You'll be able to see this effect when you're trying to sign request in metamask.

EXPECTED BEHAVIOR: (we can improve the ux by adding \n after specific no. of char in each line of message, let's say after evry 53rd char)

BUG SCOPE: UX

BUG IMPACT: Intermediate
Unable read the req. msg that's overflown & clipped.

BUG CONDITIONS: N.A.

BUG REPLICATED: seen everyday :) 

DEVICE USED: Desktop PC

BROWSER USED: Chrome w/ metamask

![overflow_is_clipped](https://user-images.githubusercontent.com/11745561/156919071-5d62c49e-4a1a-4039-b12a-185d04dc8fcf.png)

**Comment by Pranav-yadav** [comment]
Fix is on the way 😇
