### ISSUE TITLE
[BUG] Mining tooltip too far away

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#342]
<img width="257" alt="Screen Shot 2022-03-06 at 7 24 59 am" src="https://user-images.githubusercontent.com/11745561/156919101-fa5fc1a2-4c28-42bb-bee8-80a9083bae11.png">

As seen in the screenshot, the tooltip should be closer to the rock.

**Comment by j923sneaks** [comment]
on it
