### ISSUE TITLE
[FEAT] Blacklist error

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#344]
The backend has been storing a list of Blacklisted accounts, but has not disabled them from playing the game since we are in beta testing.

When an account has been blacklisted for botting, we want to display an error message indicating what has happened. This can be creative - consider using the skeleton animations

**Includes**

- UI only error modal

Work with backend dev to get the blacklisted flag returned to the UI

**Comment by Z1kou** [comment]
Something like this ? 

![SKELETON AND FARMER RUNNING](https://user-images.githubusercontent.com/98262339/156945626-65b0459b-72e1-4f47-a7d9-d2009521855a.gif)

**Comment by adamhannigan** [comment]
@Z1kou Yes, very scary! 😱

**Comment by Pranav-yadav** [comment]
@adamhannigan you can assign this one to me, if anyone is not working on it already.
Would be challenging as well as interesting.

**Comment by adamhannigan** [comment]
@Pranav-yadav This one will need to wait until the backend starts returning the Blacklisted response. The ETA on that is about 1 week 😄

**Comment by Z1kou** [comment]
@adamhannigan @Pranav-yadav  Is the animation for this good or is there some improvement that i can do (Such as centering the characters more or making them a bit closer to each other when they hunting each other )?

**Comment by Pranav-yadav** [comment]
> @adamhannigan @Pranav-yadav Is the animation for this good or is there some improvement that i can do (Such as centering the characters more or making them a bit closer to each other when they hunting each other )?

It's already awesome bro. Tho if possible you can try to increase and decrease the distance between them after some milliseconds, this is gonna give goosebumps xD 👍

**Comment by Pranav-yadav** [comment]
👍
