### ISSUE TITLE
[BUG] Visiting Farm ID incorrect

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#354]
<img width="334" alt="Screen Shot 2022-03-08 at 10 18 21 am" src="https://user-images.githubusercontent.com/11745561/157245645-e769e371-749e-4176-affa-922251c736bf.png">

When visiting a farm, the ID is no longer showing in the bottom right.

**Steps to reproduce**

1. Enter Farm ID
2. Visit Farm

**Expected output**

`You are visiting #2 farm`

**Comment by j923sneaks** [comment]
will check
