### ISSUE TITLE
[ART] Wood Collectibles

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#355]
This is a request for craftable wooden decorations in the game. We are looking for items that can encourage the burning of wood.

**Requirements**

1. The item requires wood to be crafted.

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

**Winners**

The team will choose 2 decorations to add into the game. Both of these will have a limited supply and require significant wood. The chosen artists will get airdropped their winning decorations 🤗 

**Deadline**

18th March

**Comment by Z1kou** [comment]
Coming back to this comment soon🤠

**Comment by gabiqueiroga** [comment]
me too!

**Comment by SrCouve** [comment]
![Dog house (1)](https://user-images.githubusercontent.com/98098233/157296725-67621c89-7987-4c80-9607-2f627de8d5e2.png)

**Comment by SrCouve** [comment]
![Dog house x](https://user-images.githubusercontent.com/98098233/157296870-c82392ab-e8d6-419b-9703-b9246fb5535a.png)
![Dog house](https://user-images.githubusercontent.com/98098233/157296980-f30d46d5-8c64-41a4-b4f6-c03f4476b8af.png)


Dog House

may have some effect related to the dog's ability

**Comment by SrCouve** [comment]
![image](https://user-images.githubusercontent.com/98098233/157297744-9e831715-9f47-40bd-8dd6-aa4a99bf0701.png)

**Comment by paluras** [comment]
Made this boat a while back.
![image](https://user-images.githubusercontent.com/98059798/157401398-148b52e2-85fb-40ce-871d-77260bee256b.png)
![Boat](https://user-images.githubusercontent.com/98059798/157401440-88e654cb-3e91-49d5-b0cb-24d998824677.png)

**Comment by Vergelsxtn** [comment]
Comfort room for everyone🙈
![Wooden-CR](https://user-images.githubusercontent.com/99605039/157403429-d2290060-0551-4041-8ce0-a33306679763.png)
![Wooden-CR1](https://user-images.githubusercontent.com/99605039/157403506-85d7fabc-e522-464a-8f47-64d9a260f454.png)

**Comment by Alexcnder** [comment]
i did a boat aswell a good time ago
![BOAT ON LINE](https://user-images.githubusercontent.com/87881787/157507285-e9f63c30-b823-4972-bae7-f3fc27be9756.png)
![BOAT with LINE](https://user-images.githubusercontent.com/87881787/157507288-c0a6add0-7ace-4beb-a706-9b1fa4c30914.png)

![BOAT On the sea](https://user-images.githubusercontent.com/87881787/157506489-62aadcd0-0a45-428e-8aad-bd46a57c0ce9.png)

**Comment by Vergelsxtn** [comment]
Storage box
![box](https://user-images.githubusercontent.com/99605039/157576488-d87dd8df-b643-4e09-973f-404330f59a23.png)
![box1](https://user-images.githubusercontent.com/99605039/157576524-992bf572-1187-4cc1-8c3c-fb484ab4b0f6.png)

**Comment by Vergelsxtn** [comment]
Wooden swing
![swing](https://user-images.githubusercontent.com/99605039/157576977-93d9ff9e-17e4-44a4-97d3-ba4db5bfe9d4.png)
![Swing1](https://user-images.githubusercontent.com/99605039/157577020-ed1d589e-38e9-4d1f-b473-8c4a446fef1b.png)

**Comment by sfwhat** [comment]
Wooden totem
![totemmoo (1)](https://user-images.githubusercontent.com/95937808/157658840-ccf4074c-1475-4feb-9666-c4e89f1f3621.png)
![totemmoo (2)](https://user-images.githubusercontent.com/95937808/157658844-0b33f19a-d2d2-457f-bf35-fcd1cbbdc0be.png)
![totemmoo](https://user-images.githubusercontent.com/95937808/157658847-be3d0a96-295c-4aec-94e8-d2a90f4ec7c2.png)

**Comment by Sarapico** [comment]
Tiki Idol
![pixil-frame-0 (5)](https://user-images.githubusercontent.com/98893182/157680487-8e32449b-6010-4303-8494-dec490eb56d9.png)![pixil-frame-0 (6)](https://user-images.githubusercontent.com/98893182/157680524-abd88259-df1f-402c-a349-a564c33b11ee.png)
![pixil-frame-0 (7)](https://user-images.githubusercontent.com/98893182/157680555-f8ea5379-d48b-44d7-b42c-feaa68d7266e.png)
![pixil-frame-0 (8)](https://user-images.githubusercontent.com/98893182/157680584-ef460732-679c-43d6-a847-a210b19e5ba2.png)

**Comment by SrCouve** [comment]
![Goblin 1](https://user-images.githubusercontent.com/98098233/157758566-de6dec60-3e90-4d9d-beaa-66eeeb985c44.gif)
![Goblin 2](https://user-images.githubusercontent.com/98098233/157758575-f7b3a771-e7cd-471f-8570-c1f578bce017.gif)
![Goblin 3](https://user-images.githubusercontent.com/98098233/157758580-33366b60-f95a-4c63-b0ce-fd053731b5f5.gif)

**Comment by SrCouve** [comment]
![Goblin 2 (2)](https://user-images.githubusercontent.com/98098233/157774584-51e5b810-3a0f-4178-9aad-fa6c75f08b90.gif)
![Goblin 2 (1)](https://user-images.githubusercontent.com/98098233/157774597-80e103c2-a208-4793-b075-ff9850a4548c.gif)
![Goblin 2 (3)](https://user-images.githubusercontent.com/98098233/157774604-6fef8ccb-d67e-434d-8085-b0429d08ab4d.gif)

**Comment by SrCouve** [comment]
![Goblin 2 (2)](https://user-images.githubusercontent.com/98098233/157774676-a52fbdea-db96-4f1f-8eb2-f2565471d993.gif)
![Goblin 2](https://user-images.githubusercontent.com/98098233/157774679-95522a33-487c-49cd-9110-8ed26e060459.gif)
![Goblin 2 (3)](https://user-images.githubusercontent.com/98098233/157774687-f2c9cf83-a1af-4764-92ae-ecb33428e77f.gif)

**Comment by SrCouve** [comment]
![Goblin 2 (5)](https://user-images.githubusercontent.com/98098233/157774887-8e74baad-2680-4771-bdea-80d8adb41798.gif)
![Goblin 2 (4)](https://user-images.githubusercontent.com/98098233/157774890-455d14a9-1c78-462d-9c63-d89d8210d6e6.gif)
![Goblin 2 (6)](https://user-images.githubusercontent.com/98098233/157774896-31269f18-1578-4b67-8f59-bd70048f1c11.gif)

**Comment by SrCouve** [comment]
![image (14)](https://user-images.githubusercontent.com/98098233/157901201-1dfc1555-01da-44e2-9117-68312145c3df.png)
![image (12)](https://user-images.githubusercontent.com/98098233/157901221-b3332072-ab1b-43a1-9582-3ac17b8c25e6.png)
![image (13)](https://user-images.githubusercontent.com/98098233/157901242-9e149f23-7fcb-42e0-b235-8e3b589871b7.png)
![image (15)](https://user-images.githubusercontent.com/98098233/157901252-05408b93-02df-4f8d-a3da-01e43b41bea5.png)

**Comment by Alexcnder** [comment]
This is the Heart of the Fleet of the Goblin Navy

This would cost:
maybe **1000-3000 Wood** or more?
**Low Supply**

![SHIP 4](https://user-images.githubusercontent.com/87881787/157935707-4bdc497f-0f3d-4770-964a-b62e58fc8a8c.png)
![SHIP 54](https://user-images.githubusercontent.com/87881787/157935721-c23eaa26-f9f6-4cf4-8386-3e24e74d0041.png)
![SHIP On water](https://user-images.githubusercontent.com/87881787/157935726-89772bfc-6aed-4772-bce5-b16b31c0be44.png)

**Comment by Aestnelis** [comment]
Here is the flags, i can add more if wanted.
![flagss](https://user-images.githubusercontent.com/98103679/157956807-9dea643d-75d7-4974-95a0-b769009cee37.gif)
![bigflagss](https://user-images.githubusercontent.com/98103679/157956833-e72d337c-c4c1-4e69-86d7-3c68b09e704b.gif)
![bigflagsonsunflower](https://user-images.githubusercontent.com/98103679/157956865-b400d5ac-f582-41c0-b62a-7a00be25c720.gif)

**Comment by benaxol12** [comment]
Level 1 Viking Helmet (Maybe in the future, you can reach higher levels with materials such as bone, stone, iron, gold)
![viking hat 17x9](https://user-images.githubusercontent.com/98098031/158990083-72549b71-2c6c-4b74-89ed-4ed1538285fa.png)
![viking hat 4x](https://user-images.githubusercontent.com/98098031/158990225-b86398da-7134-4d50-8a17-f648662556c4.png)
![skeleton hat](https://user-images.githubusercontent.com/98098031/158990257-55b7d0c1-81da-423a-ad45-b1de4cda684b.png)

Umbrella Hat 
![Wood Hat 23x13](https://user-images.githubusercontent.com/98098031/158990644-20f88714-eb8a-467e-b9e6-fe1c9165652f.png)
![Wood Hat 4x](https://user-images.githubusercontent.com/98098031/158990766-43fed178-4ab6-431c-a4e7-ef5693854c15.png)
![wood hat](https://user-images.githubusercontent.com/98098031/158990805-e06c794e-b12d-42d6-b4c2-92d29ddd0e64.png)

Clock to speed up wood regeneration time 
![clock x1](https://user-images.githubusercontent.com/98098031/158991175-93908289-4e21-4516-aaa4-cf7ee1c54c01.gif)
![clock x4](https://user-images.githubusercontent.com/98098031/158991616-0d92f27b-cad8-44c1-a056-960c33035d74.gif)
![Clock](https://user-images.githubusercontent.com/98098031/158991678-f487286f-1ab1-4154-82a5-6802d9eade10.gif)

**Comment by Andreivv** [comment]
![beaver dam](https://user-images.githubusercontent.com/97338003/159009632-0eac768b-a368-4228-9e60-cf95c69fed52.PNG)

**Comment by adamhannigan** [comment]
Amazing contributions everyone!

The team has decided the 2 winners for this round of designs.

@Aestnelis Flag/Tailor design 🏆 
@benaxol12 Viking Helmet 🏆 

Well done 👏 The artwork was consistent with the game and had creative utility for the wood resource! Well done 😄

**Comment by adamhannigan** [comment]
@SrCouve I found a great use case for your treasure chest! Great work 👏 Looks super cute

<img width="539" alt="Screen Shot 2022-03-19 at 5 45 57 pm" src="https://user-images.githubusercontent.com/11745561/159137849-754bdfce-3619-4d02-a31b-5a2b2809ea64.png">
