### ISSUE TITLE
[ART] Clouds

### ISSUE THREAD

**Issue by spencerdezartsmith** [sunflower-land/sunflower-land#358]
This is a request for some clouds that will cover the southern part of the map. We're looking to have sections of the map be "discoverable". We would like to have clouds covering the area. We had one attempt by community member NIGHT but there are some issues with it so we would like to open it up to all the artists. 

Here is a screenshot of the first attempt. I think it highlights well what we're trying to do but the issue is that the pixels are massive. This looks fine when scrolled out but when at the normal zoom level the pixels are way to big. We think this might be better as a repeatable image(s). Maybe the clouds don't go all the way to the corners?? Not sure. Any ideas are welcome!

We also don't need the shadow as we can implement in CSS. 🤗 

*Normal zoom*
<img width="1788" alt="Screen Shot 2022-03-06 at 10 49 05 pm" src="https://user-images.githubusercontent.com/17863697/157358221-3ab70474-d6de-418a-92ea-30ba5d51208c.png">

*Zoomed out*
<img width="1051" alt="clouds-zoom-out" src="https://user-images.githubusercontent.com/17863697/157358309-6e677ddb-66b4-4a6a-9c6c-accff5e78a83.png">

**Comment by paluras** [comment]
I made some clouds a while back.Can make different patterns when combined, let me know what you think.
![image](https://user-images.githubusercontent.com/98059798/157398263-2f21cfa8-1ea6-463b-902c-e28f4da9d3b8.png)
![image](https://user-images.githubusercontent.com/98059798/157398310-df166e4a-73b5-4f8d-98cb-56543ccf5e10.png)

**Comment by paluras** [comment]
https://user-images.githubusercontent.com/98059798/157400455-3260f096-b248-498c-9095-f33361165a49.mp4

Game example,  the clouds need to be cleaned and arranged better but that's the main idea.

**Comment by spencerdezartsmith** [comment]
> I made some clouds a while back.Can make different patterns when combined, let me know what you think. ![image](https://user-images.githubusercontent.com/98059798/157398263-2f21cfa8-1ea6-463b-902c-e28f4da9d3b8.png) ![image](https://user-images.githubusercontent.com/98059798/157398310-df166e4a-73b5-4f8d-98cb-56543ccf5e10.png)

Thanks! I will give them a go!

**Comment by paluras** [comment]
> > I made some clouds a while back.Can make different patterns when combined, let me know what you think. ![image](https://user-images.githubusercontent.com/98059798/157398263-2f21cfa8-1ea6-463b-902c-e28f4da9d3b8.png) ![image](https://user-images.githubusercontent.com/98059798/157398310-df166e4a-73b5-4f8d-98cb-56543ccf5e10.png)
> 
> Thanks! I will give them a go!
![Sprite-0003](https://user-images.githubusercontent.com/98059798/157422894-c697e4cc-4c93-43a8-ab5c-8e51875adf8c.png)
![Sprite-0004](https://user-images.githubusercontent.com/98059798/157422900-53b73703-ef0c-4a4b-9098-ad014d5e7ce0.png)
![Sprite-0001](https://user-images.githubusercontent.com/98059798/157422902-6eec5eb1-35d8-42de-8e0f-2bf95b8be485.png)
![Sprite-0002](https://user-images.githubusercontent.com/98059798/157422903-3d8489d3-425a-4c40-9320-7c098bdcd9a3.png)
Exported them nicely

**Comment by Z1kou** [comment]
I personally think that having clouds will be a huge let down visually for the players if its covering the map, I think locking the player from scrolling with a visual barrier like stated by Adam in discord is better visually and fuctionally, Graying out the parts of the game that u need to unlock or locking the scroll to them is better from a visual point of view and better incensitive to keep the players looking forward to more, also with having thicc obstacles u could be able to unlock new areas using tools such as axes and pickaxes and SFL but for Clouds I dont think there would be a correlation between ingame ressources and tools and the removal of a cloud !

**Comment by spencerdezartsmith** [comment]
> I personally think that having clouds will be a huge let down visually for the players if its covering the map, I think locking the player from scrolling with a visual barrier like stated by Adam in discord is better visually and fuctionally, Graying out the parts of the game that u need to unlock or locking the scroll to them is better from a visual point of view and better incensitive to keep the players looking forward to more, also with having thicc obstacles u could be able to unlock new areas using tools such as axes and pickaxes and SFL but for Clouds I dont think there would be a correlation between ingame ressources and tools and the removal of a cloud !

Yeah I hear what you're saying. We spoke about it at our last meeting. We're going to give the clouds a go and have a little npc mentioning the idea of land expansion which is what we're going for. Its not set in stone but we will have a play with this solution as well as others. I'll ping you when its done to get your feedback!

**Comment by Protocteur** [comment]
there is some glitch in clouds, i made a screenshot that summarize those i found + those report by other users so far in beta channel on discord.

<img width="707" alt="SFL2" src="https://user-images.githubusercontent.com/11633176/158488724-72d86ef2-21a0-4482-bcce-cc66f0bc5cdb.png">

**Comment by spencerdezartsmith** [comment]
> there is some glitch in clouds, i made a screenshot that summarize those i found + those report by other users so far in beta channel on discord.
> 
> <img alt="SFL2" width="707" src="https://user-images.githubusercontent.com/11633176/158488724-72d86ef2-21a0-4482-bcce-cc66f0bc5cdb.png">

Thanks you for this. We have a PR open with the fixes atm 🙏🏼
