### ISSUE TITLE
[BUG] Rock/Trees reappear

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#361]
**Details**

If you chop down a tree or mine a rock during the middle of an autosave, once the autosave is completes the rock/tree will reappear. If you try again you will receive an error on the next save

**Steps to reproduce**

1. Chop a tree during the middle of autosave
2. Try chop tree again

**Technical details**

This happens because the random values are coming back from the server side and updating the game state. Instead of updating the entire game local state we should instead only update the values generated on the server (i.e. Random Number values)

**Comment by InuBakaBo** [comment]
Yup this happens quite frequently. Don't think I get many other something is wrong errors.
