### ISSUE TITLE
[PROPOSAL][FEAT] Scroll to NFT in Map

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#363]
## Description

Our NFTs are all over the map and it may be confusing for farmers where they are located. Just like in "Crops" and "Water" options in menu, something like "View Sunflower Statue" will scroll to the statue. Will need think of good UX when introducing this. 

## Implementation

It doesn't make sense including a view button on the modal when scrolling to the NFT at center point since it will be covered. We could close the modal once clicked but I don't think it's good UX. 
![image](https://user-images.githubusercontent.com/89294757/158017556-221da78b-6682-4bee-8bbe-217cae1a2b9f.png)

Alternatively, we can attach click handlers on the shortcuts but it will include additional item check i.e. scroll only for NFTs.
![image](https://user-images.githubusercontent.com/89294757/158017595-d6a01815-047a-443d-b764-05c685e91405.png)

Your thoughts? 🤔

**Comment by Z1kou** [comment]
I agree that NFT's since their place is predetermined are confusing to find sometimes, I like the idea of having a viewing function especially since new players will have no idea if they got the NFT and everyone that owns something wants to have control of it / see it in his farm, I suggest Having the NFT'S separated To 2 category, functional ones which arent gonna be on the map like golden cauli ,and visual ones that are gonna be on the map , for those on the map how about giving them  a hover function when u put ur mouse on them in inventory or the side tool bar that takes u directly to them

**Comment by j923sneaks** [comment]
> I suggest Having the NFT'S separated To 2 category, functional ones which arent gonna be on the map like golden cauli ,and visual ones that are gonna be on the map

Thanks for pointing golden cauli! I actually forgot we can have such cases😅

**Comment by j923sneaks** [comment]
Some rapid prototypes:

A. Button to view (Modal open)

https://user-images.githubusercontent.com/89294757/158020644-014a6f72-3a7b-4fa4-840e-a20e6bee5730.mp4

B. Button to view (Modal close)

https://user-images.githubusercontent.com/89294757/158020653-a2279fb8-4a66-4e74-a88f-654c0ef9028f.mp4

C. Shortcut click

https://user-images.githubusercontent.com/89294757/158020719-8ee4c252-4883-4f50-ba7c-235cc98a9efc.mp4

A does not make sense and B feels like breaking the "flow" of the user (viewing items in inventory). For C, it's not obvious that clicking the shortcut will scroll to the NFT.

**Comment by Z1kou** [comment]
I think a combination of B and C is cool , I like B the most if someone wants to view there NFT they will want to see it, i suggest for the inventory closing when u view and opens after 3 seconds giving enough time to the player to recognise the place of the  NFT in the Map

**Comment by spencerdezartsmith** [comment]
I do like this idea. TBH I actually like A the most. I think UX wise it highlights where the NFT is without breaking you out of the flow. I wonder if `View` is the right word. Maybe it could be `Locate` or something like that which indicates that you will be taken to the location of the NFT. If you choose to close the modal it will be in the area 🤔

**Comment by j923sneaks** [comment]
@spencerdezartsmith Not a UX guy so I'll defer to you.

> It doesn't make sense including a view button on the modal when scrolling to the NFT at center point since it will be covered. 

Is this behavior acceptable UX wise i.e on button click, scroll in the background then users will just have to close the modal manually if they choose to finish browsing inventory? Never thought of it that way, maybe I was forcing myself to have "immediate" result when clicking the button.

or maybe consider @Z1kou 's idea which is close and reopen after x seconds. I will have to save the active tab and selected item to resume the flow. doable, i think.

I tried to modify the config in `scrollIntoView` but thinking `center` is still the best.
