### ISSUE TITLE
[BUG]: 🟠  In-game actions Conflicts aren't handled at all <-- 500 😏 

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#379]
### BUG: In-game action Conflicts aren't handled at all 😏 
<sup>(Read till the end & then conclude 👍)</sup>
### BUG DESC.:
When a player is logged into game from two or more devices and performs actions on one of the device and hopefully autosave saves the progress, and if the player opens/switches to another device and performs actions without refreshing/reloading the tab then he **will get DEATH SCREEN 💀**

### CAUSE:
It happens because, API is returning **`500`** 😆
_Seems Adam forgot to add the explicit logic for this case and just set it to return 500 (implicitly) 😄_

### POSSIBLE SOLn: (My Suggestions)
1. It should be handled professionally on API side and API should return **`BAD REQUEST`** (/ whatever u think suits best 👍)..
2. Handle this on frontend with unique error/warning modal stating cause (in short) and advising player to refresh/reload the tab/page.

PS: Just suggesting UX  improvements 👍 

---

### `v3` Suggestions 😉:
web sockets can be implemented to achieve two-way (Browser <--> API) dynamic & event driven in-game UX. 😇

**Comment by Z1kou** [comment]
I did notice this with my account yesterday but i thought it was just because of my bad internet 🤦‍♂️
