### ISSUE TITLE
[BUG]: kbd (up, down, left and right) are working when any modal is open

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#386]
## BUG DESC.:
kbd up, down, left, right and <kbd>W</kbd>,<kbd>S</kbd>,<kbd>A</kbd>,<kbd>D</kbd> resp. are working even when any modal is open.

## SCOPE:
UI/UX

## IMPACT:
- Unable to use the `scrollbar` in Items _(Basket & (Collectibles <-- I don't have any of them tho 😞) )_
- _not good for production grade websites/webapps_

## FIX:
- The events should only be fired/(or captured) when there is **NO** open modal. Also, there exists another simple approaches to fix this. 👍

**Comment by adamhannigan** [comment]
@Pranav-yadav Agreed. I'm wondering how useful these keys actually are and how often people are using them.

The quick fix would be disabling them entirely for now

**Comment by Pranav-yadav** [comment]
> 

Yep, most of the UX depends on accessibility using kbd keys at least for desktop..

And, we don't need to entirely disable them :) There's workaround will open a PR if I get time to work on it. 👍

**Comment by Don4quixote** [comment]
Has this issue been solved ? Otherwise I will open a PR too

**Comment by Pranav-yadav** [comment]
> Has this issue been solved ? Otherwise I will open a PR too

Not yet.. 
Go ahead 👍

**Comment by Don4quixote** [comment]
hum I need some precision, do you want me to make you able to use those keys for scrolling down the items scrollbar ? 
or do you want me to only block the capturing of those events for all the open modals ?

**Comment by Pranav-yadav** [comment]
@emro-chicken-union-leader hey mate !
Any progress on your implementation ?
If you haven't started on fix then do let us know. 😊

**Comment by emro-chicken-union-leader** [comment]
We were actually working on another improvement for the loading of the images with my friend, but we are going to switch back to that issue and resolve it shortly.

**Comment by pedropaulodf** [comment]
@Pranav-yadav It seems the issue is already resolved and added to the game. You can confirm @yelppp?

**Comment by Pranav-yadav** [comment]
Yep. Closing this..
