### ISSUE TITLE
[BUG] All Wearables items with boosts cannot be withdraw. 

### ISSUE THREAD

**Issue by HashubYC** [sunflower-land/sunflower-land#3889]
## All Wearables items cannot be withdraw. 

My farm doesn't have any crop. But I can't withdraw . 
All Wearables with boosts items cannot be withdraw. 
Collectibles items can be withdraw.

## Steps to Reproduce

Go to Retreat and withdraw Wearables with boosts .
Report an error WD-001

- Device: PC
- OS: Windows
- Browser/App: chrome
- Version:  125

**Comment by Serissa4000** [comment]
Should i stop planting any corps before withdraw? I tried withdraw SFL and Wearables but all faild.
