### ISSUE TITLE
[ART] Radish Meal

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#389]
To unlock wheat, players will need to craft a recipe made from radishes. This will be used to bribe a Goblin and unlock the next set of fields.

**Requirements**

- Consistent with theme and pixellation of game.
- Looks nice in Kitchen modal and on farm.

E.g

<img width="116" alt="Screen Shot 2022-03-16 at 2 13 49 pm" src="https://user-images.githubusercontent.com/11745561/158648798-d8491242-7fd6-4bd3-94d6-82f382892d43.png">
<img width="520" alt="Screen Shot 2022-03-16 at 2 13 55 pm" src="https://user-images.githubusercontent.com/11745561/158648812-79ec2f9d-a894-426b-a774-53f94a98a42e.png">

**Comment by Aestnelis** [comment]
![image](https://user-images.githubusercontent.com/98103679/158663768-367aa0b5-83a9-4467-b940-b7ec14189622.png)

![bigParnshipmeal](https://user-images.githubusercontent.com/98103679/158663705-c8e43660-f972-4dab-92d0-a44de37f1e32.png)
![Parnship](https://user-images.githubusercontent.com/98103679/158663724-d7783865-0c56-490c-b159-e5743bc55037.png)

**Comment by cambrios1** [comment]
As much as we're farming--we should really have some raw veggies.

Radish Salad!
![salad](https://user-images.githubusercontent.com/98171636/158668930-8ad18cd6-f942-45f0-9fe1-84fb752be5f0.png)

![radish salad-big](https://user-images.githubusercontent.com/98171636/158668971-843125cf-1fa0-4d95-b5a2-8df806d93667.png)

![radish salad-sm](https://user-images.githubusercontent.com/98171636/158668985-4e08d814-6468-404b-849e-e3d484b1f1e9.png)

![radish-salad-bkgrd](https://user-images.githubusercontent.com/98171636/158668995-a94361ca-05fa-4fb0-88b7-5f02af9669b1.png)

**Comment by Telknub** [comment]
I made two versions, one with a wooden bowl and another in a porcelain-ish bowl.

![raDISH800](https://user-images.githubusercontent.com/38796969/158672891-91bb5abc-6092-448e-9315-3b9bfb14d387.png)
![Sprite-00071](https://user-images.githubusercontent.com/38796969/158672921-5ac5f6a6-f67e-4e68-907e-391fbebcfd2a.png)
![raDISH](https://user-images.githubusercontent.com/38796969/158672951-b56892c7-52dd-40b6-8aae-d6c1975f6a8d.png)

![raDISH2800](https://user-images.githubusercontent.com/38796969/158672983-8732673e-1122-4506-a199-d1f2017e7f5d.png)
![Sprite-0007](https://user-images.githubusercontent.com/38796969/158673004-c4570898-d2fa-443d-8328-27e08f15513d.png)
![raDISH2](https://user-images.githubusercontent.com/38796969/158673028-b4f24b46-4434-4d53-ac9c-2966f34196c1.png)

**Comment by paluras** [comment]
![image](https://user-images.githubusercontent.com/98059798/158689033-76690360-c59a-4f0a-9d47-44a68907373a.png)
![radishpie](https://user-images.githubusercontent.com/98059798/158689140-66b6a3a2-bf1f-41a6-8d65-2130b68930e3.png)
Radish pie for goblins.

**Comment by Alexcnder** [comment]
The raddish salad
![RADISH SALA true D](https://user-images.githubusercontent.com/87881787/158707863-7591c143-c4ee-4762-998a-0c811107f9ab.png)

![RADISH SALAD](https://user-images.githubusercontent.com/87881787/158707796-118a4627-7cfa-412a-bdbe-ce5448264889.png)
![RADISH SALA true D](https://user-images.githubusercontent.com/87881787/158707954-64716d21-5143-4d57-9489-b66684a21184.png)

![Screenshot 2022-03-17 002601](https://user-images.githubusercontent.com/87881787/158707815-6a1832f6-6850-4804-b578-cb7a3020ec80.jpg)

**Comment by Lukisu** [comment]
Chef's Advice Radish Salad
![image](https://user-images.githubusercontent.com/98527636/158901462-8adcbb43-1f72-4ab9-8858-271ee1537985.png)
![image](https://user-images.githubusercontent.com/98527636/158901493-7abc2771-be9f-4bd6-8e31-6c65c60ebb36.png)
![image](https://user-images.githubusercontent.com/98527636/158901556-542cfd21-5426-43f3-879a-814a61ecdfcf.png)

**Comment by Z1kou** [comment]
A Farmer's Favorite : PICKLED RADDISH

![RADISH JAR Smaller ](https://user-images.githubusercontent.com/98262339/159135630-a005e289-37f4-4d23-9dd7-3253efbad5fa.png)


![RADISH JAR Smaller 300% ](https://user-images.githubusercontent.com/98262339/159135655-b96a6b2a-5a9b-4e92-9ca7-d47ddd727908.png)

![UI FREE-export](https://user-images.githubusercontent.com/98262339/159135658-aa03736c-8baf-4cad-8420-01293d48b1a7.png)

![RADISH JAR IN MAP300%](https://user-images.githubusercontent.com/98262339/159135659-c8b6e478-4c64-4e07-bac2-c72e74859932.png)

**Comment by benaxol12** [comment]
Tasty Radish Salad 😋 
![Radish Salad orj](https://user-images.githubusercontent.com/98098031/159153888-eb553f7f-7a5c-48f1-8e5f-1318fb07061f.png) 
![Radish Salad 8x](https://user-images.githubusercontent.com/98098031/159153896-b5bf3eb2-c8d9-4270-8193-aa4db8b26f59.png)
<img width="520" alt="Radish Salad Menü" src="https://user-images.githubusercontent.com/98098031/159154112-a5b83f17-80a9-429d-97e9-67e9e2f0b77b.png">

![Goblin Radish Salad](https://user-images.githubusercontent.com/98098031/159153910-625e64ae-62b8-40ba-97f1-f4c00ffc1083.png)

**Comment by Netherzapdos** [comment]
Radish Cocktail

Raw Asset:
![Radish Cocktail](https://user-images.githubusercontent.com/101855553/159620025-0d7b7c94-e30d-4d34-ab88-b3b8c56a9908.png)

Previews:
![Radish Cocktail Large](https://user-images.githubusercontent.com/101855553/159620043-5501c7f8-aead-4e0e-9e75-040888537e45.png)

![Radish Cocktail Preview 1](https://user-images.githubusercontent.com/101855553/159620055-b89521da-274c-40fe-8b6b-ac11e5e7c97e.jpg)

![Radish Cocktail Preview 2](https://user-images.githubusercontent.com/101855553/159620059-d43c169e-731b-4273-8cc3-37c7cd0ec172.jpg)

**Comment by adamhannigan** [comment]
@paluras Going with your design for the creativity! We don't have pie in the game yet ❤️

**Comment by paluras** [comment]
> @paluras Going with your design for the creativity! We don't have pie in the game yet ❤️

Thank you !! ❤️❤️
