### ISSUE TITLE
[ART] Badges

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#398]
The new skill progression system enables players to choose a path in the game and receive bonuses in this area. Once a player reaches level 5 and level 10 in an area, they can choose a skill.

These skills will be represented by badges.

_Inspiration: An example of skill badges in Star Dew valley_
<img width="628" alt="Screen Shot 2022-03-18 at 5 26 48 pm" src="https://user-images.githubusercontent.com/11745561/159078514-43da3ffd-6744-414e-8237-9ab5a476d8b3.png">

**Requirements**

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

- A set of small badges that can be shown on the player's details and also on their farm NFT
- Should fit pixellated aesthetics of the game
- Gender neutral, if you design a male face, also include a badge with a female face please ❤️ 

<img width="471" alt="Screen Shot 2022-03-18 at 5 14 41 pm" src="https://user-images.githubusercontent.com/11745561/159077098-825b6465-0346-410e-a3d4-9a7af1183482.png">

**Skill Badges**

We need a set of badges:

Farming:
1. Green Thumb (a level 5 crop badge)
2. Barn Manager (a level 5 animal boost)
3. Seed specialist (a level 10 expert crop grower)
4. Wrangler (a level 10 expert animal boost)

Tools:
1. Lumberjack (a wood level 5 badge)
2. Prospector (a mining level 5  boost)
3. Logger (a level 10 expert tree chopper)
4. Gold Rush (a level 10 expert miner boost)

**Deadline**

22nd March

This feature is in response from the beta feedback for progression in the game. The aim will be to ship this for Open Beta.

**Award**

Skill badges will be available for everyone so we can't offer a rare NFT. The winner will receive a full set of badges (something that could take 3 months to achieve through gameplay on multiple farms) 🤗

**Comment by Alexcnder** [comment]
Farming:

    Green Thumb (a level 5 crop badge)
![Greenthumb-expor 3t](https://user-images.githubusercontent.com/87881787/159122297-d9e82e0f-249a-4cd6-9491-20cb979fd349.png)

    
    Barn Manager (a level 5 animal boost)
    
    
![Crawl auf Wis 1h](https://user-images.githubusercontent.com/87881787/159122312-313d37af-9fdd-4946-8164-bc1b79384567.png)


    Seed specialist (a level 10 expert crop grower)
    
    
![Best greenthumb 1](https://user-images.githubusercontent.com/87881787/159122319-c1fe0412-b9fb-41c3-8b59-7447d2c61538.png)


    Wrangler (a level 10 expert animal boost)

![Crawler 33 ](https://user-images.githubusercontent.com/87881787/159122326-3c6287d5-506e-4209-b145-d4adc44e0994.png)

**Comment by Sarapico** [comment]
![pixil-frame-0 (87)](https://user-images.githubusercontent.com/98893182/159125413-17664491-7d41-4665-be4c-ee3a6ae1ee00.png)![pixil-frame-0 (89)](https://user-images.githubusercontent.com/98893182/159125415-89603358-7c18-47a7-8cf6-491eed35a27a.png)![pixil-frame-0 (91)](https://user-images.githubusercontent.com/98893182/159125419-249e0aa3-773f-4a3c-81ef-0c24f929e7c7.png)![pixil-frame-0 (93)](https://user-images.githubusercontent.com/98893182/159125425-6b3345ed-af3f-46ff-928d-597c53f7c6d7.png)
![pixil-frame-0 (88)](https://user-images.githubusercontent.com/98893182/159125438-08b5dc25-7699-49ab-8a75-b5710fc800c6.png) ![pixil-frame-0 (90)](https://user-images.githubusercontent.com/98893182/159125443-17b50345-a24f-4a2e-a9aa-64248afdcfee.png) ![pixil-frame-0 (92)](https://user-images.githubusercontent.com/98893182/159125448-d4c6cfce-28cd-4196-a759-069bb2ac37c0.png) ![pixil-frame-0 (94)](https://user-images.githubusercontent.com/98893182/159125450-6ea9e0ba-1aad-4a9e-9cca-1496afcc020c.png)

![pixil-frame-0 (95)](https://user-images.githubusercontent.com/98893182/159125464-9a37954b-ad84-46d9-8db8-c8e046c5617c.png)![pixil-frame-0 (97)](https://user-images.githubusercontent.com/98893182/159125471-c0d59682-8685-46d5-a121-813e1e051180.png)![pixil-frame-0 (99)](https://user-images.githubusercontent.com/98893182/159125476-e07b8f58-477f-431d-a8cf-3ce128a13947.png)![pixil-frame-0 - 2022-03-19T113635 791](https://user-images.githubusercontent.com/98893182/159125483-61a5823c-c1c0-40ca-af80-45263105129d.png)
![pixil-frame-0 (96)](https://user-images.githubusercontent.com/98893182/159125490-ece380ad-7d4f-45dd-97a2-224fcee0c637.png) ![pixil-frame-0 (98)](https://user-images.githubusercontent.com/98893182/159125493-00b7cc48-d342-42a7-82bb-be773afbb374.png) ![pixil-frame-0 (100)](https://user-images.githubusercontent.com/98893182/159125496-c7df7b0a-4e38-431a-9d46-8c99e4fbc630.png) ![pixil-frame-0 - 2022-03-19T113638 664](https://user-images.githubusercontent.com/98893182/159125500-53337ace-e64e-4d4c-9b0f-3dba17c386d2.png)

**Comment by Alexcnder** [comment]
**Lumberjack (a wood level 5 badge)**
![Lumberjack](https://user-images.githubusercontent.com/87881787/159129010-8a0ebe3f-1863-467c-a283-7bb92f54fc8a.png)

**Logger (a level 10 expert tree chopper)**

![Logger ](https://user-images.githubusercontent.com/87881787/159129009-f03610df-37a7-4a84-97eb-d07937bcb3dc.png)

**Prospector (a mining level 5 boost)**

![Prospector](https://user-images.githubusercontent.com/87881787/159129011-03ca78a8-06ba-4a77-a208-11fa8d9baec5.png)

**Gold Rush (a level 10 expert miner boost)**

![Gold Rush](https://user-images.githubusercontent.com/87881787/159129008-136f628e-c7c3-4413-bef2-c8050d52c5f4.png)

**Comment by paluras** [comment]
![Lumber](https://user-images.githubusercontent.com/98059798/159129891-f3651026-2164-4ebb-98bf-60379925b292.png)
![Lumber1](https://user-images.githubusercontent.com/98059798/159129892-301a9fa4-11c8-4970-ac17-9734ca3b1965.png)
Something like this?

**Comment by gabiqueiroga** [comment]
![image](https://user-images.githubusercontent.com/69090306/159130374-dda8b0d1-bdfc-49cc-a1c3-b22f9d8d02fd.png)

**Comment by ItsNight** [comment]
![Sprite-0006](https://user-images.githubusercontent.com/43474459/159131948-4a7e6f22-d713-4aed-aa26-75e7dd29ed2b.png)
![Sprite-0006-export](https://user-images.githubusercontent.com/43474459/159131959-7102681d-a8c6-4028-be3e-0b45593de566.png)

**Comment by Netherzapdos** [comment]
Raw Assets:

(Animated & Non-Animated)

**Green Thumb**
![Green Thumb Badge (Animated Raw Asset](https://user-images.githubusercontent.com/101855553/159153307-d4ddd8c5-3d00-4504-870f-7a49f9dbc62a.gif) ![Green Thumb Badge (Non-animated Raw Asset](https://user-images.githubusercontent.com/101855553/159153324-bb83df9a-2173-484d-8e71-152ac7f889e6.png)


**Barn Manager**
![Barn Manager Badge (Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153340-68c31857-308a-4565-b145-b374c3fdc93a.gif) ![Barn Manager Badge (Non-Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153342-f83149e5-a028-4f57-a045-ffe2a28e794e.png)


**Seed Specialist**
![Seeds Specialist Badge (Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153347-f2060fbf-13f9-4e08-be24-ff4d72cac102.gif) ![Seeds Specialist Badge (Non-Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153349-3e01472c-781b-424d-80b5-d217824ca1aa.png)


**Wrangler**
![Wrangler Badge (Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153353-56bf2d5a-edeb-4f1c-99ab-8ffefb782b20.gif) ![Wrangler Badge (Non-Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153356-bc500823-024b-4471-bfec-ba696b37034f.png)

=======================================================

Larger Preview:

(Animated & Non-Animated)

**Green Thumb**
![Green Thumb Badge (Animated Raw Asset Enlarged)t](https://user-images.githubusercontent.com/101855553/159153397-32f23198-a5a3-4e42-bc23-d36f4b55eb85.gif) ![Green Thumb Badge (Non-animated Raw Asset Enlarged)t](https://user-images.githubusercontent.com/101855553/159153402-2332f407-57f7-4e77-b210-be3b69e0ebaf.png)

**Barn Manager**
![Barn Manager Badge (Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153407-95b6baa0-2923-4606-8eb5-461f967075b0.gif) ![Barn Manager Badge (Non-Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153410-628a9ead-115d-4468-b867-aaeab0495ac7.png)


**Seed Specialist**
![Seeds Specialist Badge (Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153454-882d1b9a-fdec-4447-a8ae-eabd614fee36.gif) ![Seeds Specialist Badge (Non-Animated Enlargedt)](https://user-images.githubusercontent.com/101855553/159153460-42eff78e-3d20-4159-acd0-b8665cfd98a0.png)


**Wrangler**
![Wrangler Badge (Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153463-ded1eca0-325d-4e9a-86c2-241d2c676189.gif) ![Wrangler Badge (Non-Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153469-04311765-b229-4268-9113-ff11d64e060d.png)

Polygon Metamask Address:
> 0xBE6f742Fa865F94902D0a49CC12F23FDb2C5AE68

**Comment by paluras** [comment]
![Herbalist_tree](https://user-images.githubusercontent.com/98059798/159159482-ec75bf1e-bb2e-4f8d-9416-6f61d134e629.png)
![Herbalist_tree_big](https://user-images.githubusercontent.com/98059798/159159485-6715814b-5e65-4451-8bc4-2957e35708c5.png)
Green thumb and seed specialist.

**Comment by BlackDragonSG** [comment]
![image](https://user-images.githubusercontent.com/78077293/159167641-378a9625-606f-4755-8cea-006f2b047a6e.png)
![image](https://user-images.githubusercontent.com/78077293/159167651-8001aac4-20f3-4d41-9985-052e544ae7a9.png)
![image](https://user-images.githubusercontent.com/78077293/159167666-bf352491-8344-440f-9a9f-7b4452ef68b8.png)
![image](https://user-images.githubusercontent.com/78077293/159167676-e10fb011-79de-4353-8baa-2ec7e2d26869.png)
![image](https://user-images.githubusercontent.com/78077293/159167703-eb7acb3f-e075-4f08-b1e7-fe54d2a119fe.png)


![image](https://user-images.githubusercontent.com/78077293/159167728-fd0a1f4e-7552-454a-804e-75f10a086530.png)
![image](https://user-images.githubusercontent.com/78077293/159167736-bf1798e6-f2a1-4e1d-a898-74276c56a660.png)
![image](https://user-images.githubusercontent.com/78077293/159167742-0e837bfd-532e-4ef4-9f5d-469b825eb726.png)
![image](https://user-images.githubusercontent.com/78077293/159167750-3996d33b-7bb7-4dc9-b068-5dbabb704779.png)
![image](https://user-images.githubusercontent.com/78077293/159167758-f7b6fdf3-1087-4d6c-bb65-0b0a3bff1542.png)

**Comment by SteveChickenCX** [comment]
> Raw Assets:
> 
> (Animated & Non-Animated)
> 
> **Green Thumb** ![Green Thumb Badge (Animated Raw Asset](https://user-images.githubusercontent.com/101855553/159153307-d4ddd8c5-3d00-4504-870f-7a49f9dbc62a.gif) ![Green Thumb Badge (Non-animated Raw Asset](https://user-images.githubusercontent.com/101855553/159153324-bb83df9a-2173-484d-8e71-152ac7f889e6.png)
> 
> **Barn Manager** ![Barn Manager Badge (Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153340-68c31857-308a-4565-b145-b374c3fdc93a.gif) ![Barn Manager Badge (Non-Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153342-f83149e5-a028-4f57-a045-ffe2a28e794e.png)
> 
> **Seed Specialist** ![Seeds Specialist Badge (Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153347-f2060fbf-13f9-4e08-be24-ff4d72cac102.gif) ![Seeds Specialist Badge (Non-Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153349-3e01472c-781b-424d-80b5-d217824ca1aa.png)
> 
> **Wrangler** ![Wrangler Badge (Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153353-56bf2d5a-edeb-4f1c-99ab-8ffefb782b20.gif) ![Wrangler Badge (Non-Animated Raw Asset)](https://user-images.githubusercontent.com/101855553/159153356-bc500823-024b-4471-bfec-ba696b37034f.png)
> 
> =======================================================
> 
> Larger Preview:
> 
> (Animated & Non-Animated)
> 
> **Green Thumb** ![Green Thumb Badge (Animated Raw Asset Enlarged)t](https://user-images.githubusercontent.com/101855553/159153397-32f23198-a5a3-4e42-bc23-d36f4b55eb85.gif) ![Green Thumb Badge (Non-animated Raw Asset Enlarged)t](https://user-images.githubusercontent.com/101855553/159153402-2332f407-57f7-4e77-b210-be3b69e0ebaf.png)
> 
> **Barn Manager** ![Barn Manager Badge (Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153407-95b6baa0-2923-4606-8eb5-461f967075b0.gif) ![Barn Manager Badge (Non-Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153410-628a9ead-115d-4468-b867-aaeab0495ac7.png)
> 
> **Seed Specialist** ![Seeds Specialist Badge (Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153454-882d1b9a-fdec-4447-a8ae-eabd614fee36.gif) ![Seeds Specialist Badge (Non-Animated Enlargedt)](https://user-images.githubusercontent.com/101855553/159153460-42eff78e-3d20-4159-acd0-b8665cfd98a0.png)
> 
> **Wrangler** ![Wrangler Badge (Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153463-ded1eca0-325d-4e9a-86c2-241d2c676189.gif) ![Wrangler Badge (Non-Animated Enlarged)](https://user-images.githubusercontent.com/101855553/159153469-04311765-b229-4268-9113-ff11d64e060d.png)
> 
> Polygon Metamask Address:
> 
> > 0xBE6f742Fa865F94902D0a49CC12F23FDb2C5AE68

This Egg is amazing ♥

**Comment by InuBakaBo** [comment]
They're badges so I thought they should be like metal badges/medals. Work in Progress...
![image](https://user-images.githubusercontent.com/98318794/159217082-12bf9ee8-0536-41f5-b498-595ca34f87f9.png)
![image](https://user-images.githubusercontent.com/98318794/159217440-067ccb28-df36-4bee-bbd5-be212c669e1c.png)

**Comment by Andreivv** [comment]
Waaaaaaaaaaaaaaaaaaaaaazzzzzzzzzzzzzzzzzzzzaaaaaaaaaaaaaaaaaaaaaaaapppppppppppppp FOLKS!


I brought you a bunch of badges with some modifications between them.
I'm doing some others.
I believe they fit the game's theme very well, both in the irony of - Woody Beaver - being the apex of forest destruction, as well as representing some specific things, such as the seed that looks like a musical note.

I really liked it.


![Baaaadges correct](https://user-images.githubusercontent.com/97338003/159321086-b64d5825-df86-49f5-9be4-83db06f837f0.jpg)


![Badgesssssss](https://user-images.githubusercontent.com/97338003/159321397-8182b5be-1b3f-4a43-b95d-6bf5ea2f57b1.PNG)

**Comment by benaxol12** [comment]
Level 5:

![Green thumb 14x15](https://user-images.githubusercontent.com/98098031/159433717-d4e362b6-7de4-4750-9e7c-f5bdcf66f57c.png) Green Thumb (a level 5 crop badge) - (14x15 px)

![Barn Manager 10x12](https://user-images.githubusercontent.com/98098031/159433925-c82bb12a-0d0b-4ba2-8f8a-76cc371cd9fd.png) Barn Manager (a level 5 animal boost) - (10x12 px)

![Lumberjack 10x11](https://user-images.githubusercontent.com/98098031/159434135-5209ce33-c9c7-41de-86b9-0929868324e0.png) Lumberjack (a wood level 5 badge) - (10x11 px)

![Prospector 15x9](https://user-images.githubusercontent.com/98098031/159434528-024736f0-3f50-4a16-96b3-b2ac7d2a309b.png) Prospector (a mining level 5 boost) - (15x9 px)

Level 10:

![Seed specialist 16x15](https://user-images.githubusercontent.com/98098031/159435106-1e3a4ec4-99ce-49e1-ab32-99d29d6b6fd4.png) Seed specialist (a level 10 expert crop grower) - (16x15 px)

![Wrangler (14x16)](https://user-images.githubusercontent.com/98098031/159435408-512ebe39-e144-4da2-ab4f-42c9a8a3ebea.png) Wrangler (a level 10 expert animal boost)  - (14x16 px)

![Logger 14x16](https://user-images.githubusercontent.com/98098031/159435568-4faebf7a-bf7c-466f-813a-a3b42df935c5.png) Logger (a level 10 expert tree chopper)  - (14x16 px)

![Gold expert 12x16](https://user-images.githubusercontent.com/98098031/159435709-2926ca23-b937-4f1e-a3af-3e515971cace.png) Gold Rush (a level 10 expert miner boost) - (12x16 px)
![Badges test](https://user-images.githubusercontent.com/98098031/159437101-dee91dc3-c508-44b2-8662-65a18a01fb04.png)

**Comment by adamhannigan** [comment]
Another round of awesome submissions! The team tested each of these in the game's UI and have made the decision on the following. We found that a range of badges from different submissions looked best in the UI.

The winners are 🏆 🚀 

Green Thumb - @gabiqueiroga 
Barn Manager -  @benaxol12 
Seed Specialist - @ItsNight 
Wrangler - @Alexcnder 
Lumberjack - Undecided, none fitted the aesthetic amazing. We are using a placeholder for now
Prospector - @benaxol12 
Logger - @Alexcnder 
Gold Rush - @benaxol12 

The team is polishing off these features, your badges will be airdropped over the coming weeks 🤗 @Alexcnder and @benaxol12 if you could DM/send me your farm ID would be great!

**Comment by gabiqueiroga** [comment]
> Another round of awesome submissions! The team tested each of these in the game's UI and have made the decision on the following. We found that a range of badges from different submissions looked best in the UI.
> 
> The winners are 🏆 🚀
> 
> Green Thumb - @gabiqueiroga Barn Manager - @benaxol12 Seed Specialist - @ItsNight Wrangler - @Alexcnder Lumberjack - Undecided, none fitted the aesthetic amazing. We are using a placeholder for now Prospector - @benaxol12 Logger - @Alexcnder Gold Rush - @benaxol12
> 
> The team is polishing off these features, your badges will be airdropped over the coming weeks 🤗 @Alexcnder and @benaxol12 if you could DM/send me your farm ID would be great!

![greenthumb_badge](https://user-images.githubusercontent.com/69090306/159592068-5e1580c3-d6c5-40c6-8080-e25af5f3babe.png)

**Comment by adamhannigan** [comment]
Just a note, all winners will be receiving the Green Thumb badge 🤗 

The level 10 badges are being redesigned and the functionality is not yet delivered so we want to ensure you get something that is working from day 1 😄
