### ISSUE TITLE
[PROPOSAL] Disabling the browser's built-in zoom functions and adding custom buttons to the game.

### ISSUE THREAD

**Issue by Cyvid7-Darus10** [sunflower-land/sunflower-land#399]
Sometimes players' browsers have already set their zoom values, so it would look bad once they start the game.

Adding the zoom-in and zoom-out buttons instead to the game would be great.

**Comment by adamhannigan** [comment]
Agreed. It would also be good to limit how far a player can zoom out. This would prevent the green edges appearing on 25% zoom level.

**Comment by adamhannigan** [comment]
Closing for now for inactivity
