### ISSUE TITLE
[ART PROPOSAL] Sun Flower Variants

### ISSUE THREAD

**Issue by BlackDragonSG** [sunflower-land/sunflower-land#403]
![SunflowerLand_Smiley_20x30](https://user-images.githubusercontent.com/78077293/159146183-c4a5a283-9c2b-40ec-a878-d88a8f04736f.png)

![Sunflower_Smiley-large_Preview](https://user-images.githubusercontent.com/78077293/159146189-827936cd-468e-4ba5-a505-396fb5862f2d.png)

![SunflowerLand_Smiley_Preview](https://user-images.githubusercontent.com/78077293/159146194-5650699b-7db2-4ffa-b2a4-0a2e97f4c1ec.png)

0x50172FC410F27b011187743102Fd3FBC63A89AEE

**Comment by adamhannigan** [comment]
Nice surprise for players. What functionality would this sunflower have?

**Comment by SteveChickenCX** [comment]
> Nice surprise for players. What functionality would this sunflower have?

Double harvest!

0.1% chance to pop up , just a neat hidden egg.

**Comment by SteveChickenCX** [comment]
![download](https://user-images.githubusercontent.com/99016671/159175935-74095f32-fb83-46fc-80ee-40c5e63d3dab.png)
Behold my Mighty Scary Pumpkin

**Comment by BlackDragonSG** [comment]
I would like to think of it in that direction meaning we could even mint NFT seeds growing that has singular random growth with different emojis and different benefits.

**Comment by adamhannigan** [comment]
#507 Closing now as this can be covered in mutant crops 🤗

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
