### ISSUE TITLE
[PROPOSAL] New flavor texts for all crops except Sunflower

### ISSUE THREAD

**Issue by Muddshoe** [sunflower-land/sunflower-land#408]
Currently, all crops barring Sunflowers have the flavour text of “a nutritious plant for any diet”.

I propose multiple possible changes for the flavour texts for the other crops, 

If a suggestion doesn’t have any explanation, it’s probably because it’s super self-explanatory, so much so that I don’t feel like explaining it LOL (usually with regards to nutrition). 

Also, these don’t have to be the ones that end up being put in the game. But the current flavour texts seem like a relic of an older, less polished time. These small, easy-to-do changes help a bit in making the game a bit “fuller”. At least imo.

✅ Current: “A nutritious plant for any diet”

🌻Sunflower: “A sunny flower”

🍠 Radish: 
Suggestion 1: “Legend says these were once used in melee combat” [Radishes are used in Princess Peach in Super Smash Bros Melee]

Suggestion 2: “Give it some time, it’s worth the wait!” [Radishes are currently the crops with the longest growth period]

🥔 Potato: 
Suggestion 1: “Healthier than you might think!” [Potatoes are more than just carbs!]

Suggestion 2: “Boil em, mash em, stick em in a stew” [Lord of the Rings reference]

 🎃 Pumpkin: 
Suggestion 1: “Ooooh, spoookyy~~” [Pumpkins tend to be associated with halloween, and by extension “scariness”]

Suggestion 2: “I think we have a carving knife somewhere…” [Carved pumpkins]

Suggestion 3: “You could put something in this” [Reference to Pumpkins in the PvZ series, though could extend generally to Jack-O-Lanterns]

🥕Carrot: 
Suggestion 1: “They’re good for your eyes!” 

Suggestion 2: “A rabbit’s best friend” [Popular connection between rabbits and carrots]

Suggestion 3: “Eh, what’s up doc?” [Bugs Bunny reference]

🍠 Beetroot: 
Suggestion 1: “Apparently, they’re an aphrodisiac…” [Historically and mythologically, such as in Rome. Aphrodite apparently ate Beets to make herself more appealing]

Suggestion 2: “Good for hangovers!” [Nitric acid in beets can combat hangovers]

🥬 Cabbage: 
Suggestion 1: “Once a luxury, now a food for many” [Cabbages were once a luxury food for the rich in Ancient Rome, but they’ve been instrumental in preventing famines and being an all around cheap and healthy food]

Suggestion 2: “All you need is cabbage and water” [Some say that Diogenes the philosopher ate nothing but cabbage and water to survive]

Suggestion 3: “It’s a bit basic, but it passes the test” [Red cabbages specifically are used for DIY litmus tests which tests for the pH (acidity and basicity) level of substances] 

🍠 Parsnip: 
Suggestion 1: “Great for a diet!”

Suggestion 2: “Not to be mistaken for carrots” [They’re very, very closely related and somewhat look alike]

Suggestion 3: “Hehe, snip snip!” [Parsnip-snip?]

Suggestion 4: “Hey, be careful with that!” [Parsnip shoots and leaves are poisonous, but mainly its because of the name like Suggestion 3]

🥦Cauliflower: 
Suggestion 1: “Now in 4 different colours” [Apparently Cauliflowers come in 4 different colours: white, green, orange, and purple]

Suggestion 2: “Excellent rice substitute!” [Cauliflower rice]

**Comment by adamhannigan** [comment]
Agreed. These are much better. Hopefully a developer will pick these up pre-launch 🤞
