### ISSUE TITLE
[PROPOSAL] ELEMENTAL ELDER WIZARD EVENT

### ISSUE THREAD

**Issue by Z1kou** [sunflower-land/sunflower-land#409]
**Idea for  An Event for Sunflower Land.                       _Time: 7:45 PM  02/03/2022_

Event Name : Elemental Elder Wizard's** 

Event Description :The sunny land is getting back on it's feet, The breeze is breathing life into the sunflower land, All the life within is ready for a start of a new page, Both farmers and goblins ready to make yield, But far in the distance a howling breeze is setting in, magic is boiling up in the deepest dark of the forest? Three mysterious Wizards set in the Land, Where did they come from ?, What's there purpose here Armed by there wands and trusted veggies they are here to fullfill there thirst for alchemy and luckly u have all they could need ,Crops LOTS OF CROPS , They are offering up rewards for Your lovely hand planted veggies (finally someone understands our premium farming skills ) , What will you get in return? Hope in https://sunflower-land.com/play/ And find out !

https://user-images.githubusercontent.com/98262339/159178594-59a64af2-de8d-494c-8b80-28a26f0f7ada.mp4

**Event In-game Summary :** 3 Wizard NPC Are introduced to the map they would trade you crops for an event currency  that you could use later for all sort of rewards from buffs to even having a little rad , beet , pumkin as your new farm companion  (these are the wizards pets) !

**Event Mechanism :** Introduction of a new temporary currency : Wizard Gold for the sake of convenience Imma write as WG from here on out (this would be the main currency used through out the event)                                                                                                                  
                
                 -Each crop given to the mages would be rewarded with a certain number of merit token The system of token 
distribution is as follows: Crop : 

     (First time given the crop) - (Second time giving the crop withing 2 days) - (3rd time giving the crop within 4 days)
                            Sunflower : 0.1 - 0.05 - 0.001
                            Potato : 0,5 - 0.25 - 0.1
                            Pumpkin : 1 - 0.5 - 0.25
                            Carrot : 1,5 - 1 - 0.5
                            Cabbage : 3 - 2 - 1
                            Beetroot : 7,5 - 5 - 3
                            Cauliflower : 15 - 7 - 4
                            Parsnip : 30 - 15 - 10
                            Radish : 60 - 20 - 10

                            
//The idea here is to give every day the player to earn 60 Wizard Gold Daily For 20 days straight (CAP),they could either choose to give a radish in one day , 2 parnsnip day 2, 3 cauliflower day 3 , then switch back to radish , or give a variety of low yielding crops in 1 day then use radish and parsnip for day 2 and 3 or they want to give 1 radish day one then 3 radish's day 2 then 6 radishes day 3 the choice is yours , this gives flexibility of crops used and increases the planting of all different crops making people be thoughtful and quircky of what they give the wizards  Giving them by the end of the event 1200 Wizard Gold to work with if they did the quest everyday since the start of the event to the end of it//

//The reward system will be progressive and broken down into 3 levels: Level 1: You can buy Potato , Pumpkin , Carrot  Potions from the Wizard Shop
                  
           (Pay In Ressources And SFL to unlock)                       Level 2: Adds Cabbage, Beetroot , Cauliflower Potions Wizard Shop

           (Pay In Ressources A SFL to unlock)                         Level 3: Adds Parsnip, Radish & Companion's to the Wizard Shop

**Wizard Gold usage** : Introduction of ERC115 NFT 1 Time Use NFT's  That get burnt when u use it like axe but have the effect of golden cauliflower
                     
                     
                     30 WG : One time use Potato Potion : Double the price of your next potato batch( The first 22 Potato's you sell after getting this effect gives                               you double the  price )
   
                     60 WG : One time use Pumkin Potion : Double the price of your next pumpkin batch ( The first 22 Pumpkin you sell after getting this effect gives                               you double the  price )
                    
                     80 WG : One time use golden Carrot : Double the price of your next Carrot batch ( The first 22 Carrot you sell after getting this effect gives                               you double the  price )
                     
                     120 WG : One time use golden Cabbage : Double the price of your next Cabbage batch ( The first 22 Cabbage you sell after getting this effect gives                               you double the  price )

                     250 WG : One time use Golden Beetroot : Double the price of your next Beetroot batch ( The first 22 Beetroot he sells after getting this                                         effect gives him double the price )
 
                     
                     300 WG : One time use Golden Cauliflower : Double the price of your next cauliflower batch ( The first 22 Cauliflowers he sells after getting this                              effect gives him Double the price )

                     400 WG : One time use Golden Parnsip : Double the price of your next Parnsip batch ( The first 22 Parnsip he sells after getting this                                           effect gives him double the price )

                     600 WG :  One time use Golden Radish : Double the price of your next Beetroot batch ( The first 22 Radish he sells after getting this                                           effect gives him double the price )

                     
                     1080 WG : 3 Wizards companion (Little beet , Little Pumkin , Little Rad) they will be rare collectible (5% to triple the price Of A Batch of Crops                                                                                                                                                        1 time per day).
 

//With this we have a linear system that could either reward u with more yield if u engage with the wizards and satisfy there needs of variety of crops every day or u could grind for the 3 little companions that look cute and most definetly would want to be in your farm ! //

**Requirements for this event :** 
       
                              -3 wizard characters drawn and there Animation ( Already did that/ Work in progress ) Done
                              -Creation of the  Wizard Gold token this could be off-chain or on chain  (WIP)
                              -Creation of the Wizard Gold token ( I can do that ) (Done)
                              - Adding the text for the Wizards ( this is for lore )  (WIP)
                              - Creation of the interface of dialogue for the wizards ( WIP)
                              - Coding of the event mechanism  (WIP)
                              - Coding of the event reward system and adding an interface for that (WIP)
                              - Merging all the characters and their interface dialogue and rewards interface in the game (WIP)
                              

**Update 20/03/2020:**      

                       -Set up the contracts For Usable NFT's (ERC115 format) and Companion's NFT
                      
                       -Interaction with the NPC. 2 tabs (One for rewards and one for Trading corps for wizard Gold)

                       -Adding the unlocking system of the rewards of NPC

                       -Adding the wizard token as a currency that does not interact with blockchain.
   
                       -Adding the beetroot wizard and pumpkin wizard in both biomes with lore of the event

                       -Changing the  asset of the NPC when you mint the companion's
                               

**Event goal :** 

            - Have a event as we are lunching the game making the game more appealing and encouraging people to hope in early to 
              the hype train, Having a goal is the bread and butter of video game's, from grinding to finally reaching your end goal after 
              hours of work i want for every one to experience that feeling and have as much fun as possible when the game launches 
              this is not just a play to earn crypto project this is a video game that is meant to entertain us earning should come second.
             
             -This event can count as a season 0 test for the game events and data collected from it would help design the
              next events .
             
             -This event will be away to help with the early stability of the game token and encourage people to plant a more variety of 
             crops making it less of a plant to get money and more of plant to play !
           
             -This event could be used as a way to lunch different NFT's and potential have different parts of it with a fun elaborate 
             storyline.
       
             -This event could be used to introduce a fun way to raise funds for different campaings and or raise fund to cover fee's where 
             its needed (Example: money to maintain a server)
 
             -This event can unlock the way for a bigger and more rich storyline, Giving both more possibilities and flexibility with the 
              direction the game wants to go story wise
             
             -Its gonna be alot of work but its gonna be fun !

Zikou & Amon : Thank you very much for reading , Any Suggestions / improvement are more than welcome !
  

PS: EVERYTHING HERE IS A WIP.
            
![WIZARD HAT ICON Second Try](https://user-images.githubusercontent.com/98262339/159178628-f988cf6e-677c-4f06-9eed-a1ed9c98e6f1.png)
![1-TIME USE PUMPKIN300](https://user-images.githubusercontent.com/98262339/159178631-0b5b1fd9-be8d-4183-9b05-e91db71bbe25.png)
![Beetroot Wizard Prototype 300%Winter Background](https://user-images.githubusercontent.com/98262339/159178632-e0ed4b84-8e84-456d-843a-d9353de08803.gif)
![Companion V4 pumkin groove](https://user-images.githubusercontent.com/98262339/159178634-02f66060-580f-470f-91bd-424f8952bc63.gif)
![Pumpkin wizard300 Orange background %](https://user-images.githubusercontent.com/98262339/159178637-70b1a392-0d43-4bf7-9822-7ace0a99d91c.gif)
![Radish wizard 300% Green Background](https://user-images.githubusercontent.com/98262339/159178639-7ec0cdf1-196a-4a9f-9599-b71aab9d25dc.gif)
![WIZARD GOLD BAR200%centered ](https://user-images.githubusercontent.com/98262339/159178640-9b8585cd-b359-4772-8a57-4f27ce090348.png)

**Comment by SFL-Aeon** [comment]
Looks good zikou/Amon. Have you considered each companion separate? A chance of one out of 3? This would allow more of a chase event and encourage people to trade these between each other or on the open market. Maybe have to change rates based on that yet could encourage more participation.

**Comment by Z1kou** [comment]
> Looks good zikou/Amon. Have you considered each companion separate? A chance of one out of 3? This would allow more of a chase event and encourage people to trade these between each other or on the open market. Maybe have to change rates based on that yet could encourage more participation.

The idea here is introduction of a new concept to the game, Magic & Alchemy , During the event the only Npc you will need to interact with is the  Radish wizard which would be next to your farm , the rest 2 wizards will be each in a biome , their purpose there would be to tell lore for those who are interested( about the event and maybe give hints into upcoming events) I want to leave this part open to set up future events and a potential 3rd faction that would be neutral in the upcoming war between goblins and human's, Wizards would be the wisdom carriers who will lent out their services for those who pay them fairly !

**Comment by Netherzapdos** [comment]
Yo Z1kou, hope you don't mind me leaving some questions here regarding the lore. Figured it'd be beneficial too for those who want to contribute to the lore and needs some background info to start with :) 

- Do you want to give hints as to where they came from, their purpose, and if they are sentient enough to understand that they are talking vegetables?
- Are the two other wizards responsible for giving the lore; pumpkin and radish?
- Will the pets have lore as well?
- Is there going to a particular lore about the Wizard Gold? 
- Should a goblin vs human war be hinted? 
- Also, if there's any lore you guys are already thinking of and want to build on that, please do share as it would give me and others an idea as well on how to continue :) 

* Might have some new questions down the line but for now this will do.

**Comment by Z1kou** [comment]
@Netherzapdos  I am humbled and happy to see the multiple questions gonna answer them now all : 

1-There origins are still vague since the intention here is to give them a sense of mysterie, the origins would be handled by future events like most franchise do when presenting a story, a teaser is they are a race of evolved vegetable sort of mutants that are well versed in magic and bring prosperity and alchemy to every land they go to. 

 2-Yes the Radish wizard would becovering the event trading system, while the pumpkin and beetroot will be in the 2 other biomes, Clicking on them will give u a dialogue of them that will tell you a bit of lore about the event, and about why they are  here 

3-The Pets are the trusted companions of the wizards, they share a relativity of veggie blood more like distant relatives, they do have a good affinity for magic tho ;)

4-Yes, like i said in 1- its a mysterie at first but later its gonna have its own lore and the game logic behind it

5-It depends on when the event would be finished, if it was finished and maybe delivered as the prequel of the war it will play a big role in hinting the war!

6-The core peace of lore here is: the wizards come from a sentient veggital race, they are proficient in both alchemy and magic and venture around the SFL world trading ressources for there unique benifits for those who pay them approprally, think of them as traveling merchant but they deal in magic and alchemy !

7- All your questions are welcome ! thank you for reading all of this

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
