### ISSUE TITLE
[PROPOSAL] Plant rotting time

### ISSUE THREAD

**Issue by FamousiksLv** [sunflower-land/sunflower-land#411]
So yeah, Plant rotting time. When your plant has grown you have time limit (rotting time) in which you need to harvest if  you didn't harvest in time then you lose your plant.

Sunflower - 5 minutes
Potatoe - 15 minutes
Pumpkin - 30 minutes
Carrot - 1 hour
Cabbage - 2 hours
Beetroot - 4 hours
Cauliflower - 8 hours
Parsnip - 12 hours
Radish - 16 hours

This is just an example, feel free to change the time limits. Every rotten plant SFL would go to burn address.
And yea maybe later you could add nft's or perks which increases rotting time.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
