### ISSUE TITLE
[ART] Blacklisted Farm

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#414]
This is an art request for an NFT representation of a farm that is blacklisted.

When bots are detected we will blacklist their account. We want to avoid anyway accidentally buying a farm NFT that was blacklisted. On OpenSea, we want the images to be different with a clear "BLACKLISTED" label visible.

**Requires**

- A square png similar to our current design
- A clear "Blacklisted" label
- Unique design of evil things (rainclouds, goblins, skeletons etc.)

<img width="326" alt="Screen Shot 2022-03-21 at 12 34 52 pm" src="https://user-images.githubusercontent.com/11745561/159295934-ae872a45-b27c-4fe5-9f05-3cd5e83b7a2f.png">

**Comment by Pranav-yadav** [comment]
💯 was thinking about these feat recently along with on the Visit Farm feature <-- here there should be clear watermark stating "Blacklisted" on the map, so even if someone tries to scam using these images they should no be able to.
(why not completely stop people from visiting such farms? <-- No. anyone should be able to verify the state of the farm before buying it.)

**Comment by SFL-Aeon** [comment]
Someone more talented than me maybe could design this but I would think having the original farm nft with BLACKLISTED tilted at a 45 degree angle from left to right (from water to cave)would look good.

**Comment by Pranav-yadav** [comment]
@adamhannigan a Board fixed near the land stating "Blacklisted" will be great similar to for sell boards hahah.

or Stamp in the middle stating "Blacklisted" would also be great.

@ astnelis @ zaikou @ _adding_.... any arts for this ?

**Comment by paluras** [comment]
> @adamhannigan a Board fixed near the land stating "Blacklisted" will be great similar to "FOR SELL" boards hahaha.
> 
> or Stamp in the middle stating "Blacklisted" would also be great.
> 
> @Aestnelis @Z1kou @paluras any arts for this ?

Imma see what i can do
![image](https://user-images.githubusercontent.com/98059798/159302002-6c52a11d-bab4-46a6-b30e-696392738e2b.png)
Image for easy acces.

**Comment by adamhannigan** [comment]
@Pranav-yadav This would be perfect in the game. While we are in our MVP stage we are trying to keep the visiting farm state on chain. This saves us dev effort and server costs.

I imagine in a month or so once we get revenue we can start building out this functionality.

**Comment by Sacuul** [comment]
I see something like this, I'm not sure about the colors and the text but I thinks it's a good start
![uhoh-blacklisted-farm](https://user-images.githubusercontent.com/63975424/159304697-b50992d2-bd7f-471c-b33c-841416a39c14.png)
!

**Comment by paluras** [comment]
![Badfarm](https://user-images.githubusercontent.com/98059798/159327497-45a6c60f-5b7a-4271-8fa3-4b11d3669fa2.png)
![Badfarm2](https://user-images.githubusercontent.com/98059798/159327499-290830f3-1b1a-47c3-a854-78ce1247fa70.png)
And Blacklisted writen over it .

**Comment by paluras** [comment]
![Badfarm3](https://user-images.githubusercontent.com/98059798/159328962-47282ce1-1b1c-4ff0-8272-f458aaf67636.png)
Something like this but i think someone can do it better in photoshop or something.

**Comment by adamhannigan** [comment]
@paluras @benaxol12 Awesome job 👏 I will include this now and we will see some blacklisted farms begin to appear 😈
