### ISSUE TITLE
[PROPOSAL] Mutant Crops

### ISSUE THREAD

**Issue by block-kid** [sunflower-land/sunflower-land#417]
**Proposal:** Introduce hybridization/mutation mechanics to crops. We've all been chatting about it for a while, so I thought I'd throw something up here!

**Mechanics**
- crops have a low % chance of dropping mutants
- these mutants may present in different ways 
   - e.g. higher sale value, 
   - higher productivity (multi drop on harvest), 
   - resource yielding (also drop wood, gold etc on harvest) etc..
- you can sell them, use them to craft or keep them
**Expansive Mechanics**
This is where it gets fun!
- as you explore the map, you find a eccentric hermit living in the mountains they seem to have a way with plants..
- they love rare and odd plants and get excited when you find say you found some!
- they ask if they can have them and you oblige, because how can you resist the joy it brings them.
- they say to come back and they'll have something to repay your kindness
- after some time they present you with a stable seed line, with characteristics of the initial mutant!
- this new seed can now either be bought from the shop as usual, or from the hermit in exchange for food(more use cases for the kitchen)
**Possible buffs and randomization**
- higher chance of mutant drops with higher farming skill
- a chance of a random trait appearing the the new seed produced by the hermit. This could be influenced by pay extra resources or $SFL
The possibilities are endless!! 😄

**Comment by adamhannigan** [comment]
"eccentric hermit living in the mountains" - I love this!

This definitely makes sense for a direction to go with mutant crops. For MVP, they will just start of as collectibles/rare items. 

Over time this gameplay would be useful 👏

**Comment by block-kid** [comment]
@adamhannigan I absolutely agree. MVP with a crop variant that slots into the existing ecosystem of farm/shop/craft. Then add layers of utility, as the map and narrative of SFL evolve. An implementation you and the team are already doing a great job on! ❤️

**Comment by adamhannigan** [comment]
Lets continue the convo on this proposal https://github.com/sunflower-land/sunflower-land/issues/507
