### ISSUE TITLE
[PROPOSAL] Fibre Crops

### ISSUE THREAD

**Issue by block-kid** [sunflower-land/sunflower-land#418]
**Proposal**
Add fibre crops, such as cotton, hemp and linen. These could be used to craft value added trade goods at the tailor.
**Mechanics**
- slow growing crop
- can add spinning and weaving or just use it directly to craft _Cloth_ and _String_
- can be dyed using beets, carrots etc
- _cloth_ can be sewn into garments and _string_ into fishing nets etc
- _cloth_ could be embroidered with gold to create fancy garments to impress the goblin royalty
- used with iron and leather to craft armour

**Comment by adamhannigan** [comment]
Great ideas @block-kid 

I honestly never thought about the fibre crops but it makes a lot of sense. Your ideas around dye are awesome utility as well 👏

**Comment by adamhannigan** [comment]
Closing now in favor of #194 proposal. Please add further discussion there
