### ISSUE TITLE
Better rock shadows.

### ISSUE THREAD

**Issue by paluras** [sunflower-land/sunflower-land#433]
The black outline feels out of place so i tried to blend it a bit better.
![image](https://user-images.githubusercontent.com/98059798/160069918-f6a1d407-9c18-448a-a470-a000bd0d3b96.png)
![image](https://user-images.githubusercontent.com/98059798/160068906-87bfe361-b892-4ed2-9528-29422e8fdb77.png)
![image](https://user-images.githubusercontent.com/98059798/160068972-09884237-98c5-47b8-9973-793e3066dc85.png)

Gold
![gold_empty](https://user-images.githubusercontent.com/98059798/160069443-1db1733e-5c0f-4999-a6fc-473649e90d1f.png)
![gold_spark](https://user-images.githubusercontent.com/98059798/160069168-70056945-8143-4518-bbab-35b160f56c66.png)
![gold_rock](https://user-images.githubusercontent.com/98059798/160069192-793535e4-c26e-4f3d-a80f-4ffa5ea69ff6.png)

Iron
![iron_empty](https://user-images.githubusercontent.com/98059798/160069230-cee2fb54-d5bc-4b64-bb84-0c5cdccef887.png)
![iron_spark](https://user-images.githubusercontent.com/98059798/160069232-1f75c74c-69f9-4b05-88a9-f2fa727f3969.png)
![iron_rock](https://user-images.githubusercontent.com/98059798/160069249-3044c944-0026-4231-bb2f-cdc48f498886.png)

Stone
![stone_empty](https://user-images.githubusercontent.com/98059798/160069641-a69ec40d-9f8b-43f8-92be-524ac413aaa5.png)
![stone_spark](https://user-images.githubusercontent.com/98059798/160069294-64686701-909c-4b72-9a58-2140afc1e861.png)
![stone_rock](https://user-images.githubusercontent.com/98059798/160069305-c8b9e23f-9c9c-459b-a96f-6b437cd0cafd.png)

**Comment by adamhannigan** [comment]
@paluras Thanks for taking the initiative with this. It definitely looks better 🤗

**Comment by paluras** [comment]
> @paluras Thanks for taking the initiative with this. It definitely looks better 🤗

Glad I could help!
