### ISSUE TITLE
Suggestion about new farm animals

### ISSUE THREAD

**Issue by Aestnelis** [sunflower-land/sunflower-land#436]
Deleted.

**Comment by adamhannigan** [comment]
@Aestnelis I love the art! I would suggest finding a different utility for the ducks since Chickens already produce eggs.

Is there another output ducks give?

**Comment by Aestnelis** [comment]
> @Aestnelis I love the art! I would suggest finding a different utility for the ducks since Chickens already produce eggs.
> 
> Is there another output ducks give?

### **Duck meat, to feed the dog/cat or other animals like beaver.**  

When the dog eats duck meat, its productivity may increase slightly. Or we can also use it to feed when he is tired and his productivity is low.

If the Beaver gets hungry, he will get tired and thus his wood yield will decrease. This prevents the Beaver from being over powered and provides SFL burn.

If the beaver gets tired, we can cook him duck meat (crafting with recipes in kitchen) to revive him.

This also becomes a resource for the beaver to constantly chop wood. It can be the same in a dog or cat. When the dog eats duck meat, its productivity may increase slightly. Or we can also use it to feed when he is tired and his productivity is low.
