### ISSUE TITLE
[PROPOSAL] New uses for the flag

### ISSUE THREAD

**Issue by RogGarcia** [sunflower-land/sunflower-land#440]
(this text has been automatically translated)
The flags could have, in addition to the decorative function, the possibility of creating a sort of ranking of the "countries" that would be presented in the form of a table, as an interesting curiosity, with total accumulated capital, amount of wood, gold, number of farms etc. This ranking of all goods produced by a given flag could also serve to activate some incentives or penalties for specific items, such as collective quests or a collective objective. As an example, if a country manages to accumulate 500,000 wood, everyone (with such a flag) gains 5% more production in some product.

Later, this function could be expanded to the economic area and regional markets could be created, for domestic consumption and also for exporting large amounts of goods to the international market, adding a mechanic similar to guilds in RPG games.

**Comment by adamhannigan** [comment]
@RogGarcia I really like this idea.

It would be like joining a guild and trying to contribute to that guild 👏
