### ISSUE TITLE
[ART] Scary Scarecrow

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#447]
This is an art request for an upgraded version of the scarecrow. Players will need to craft this using a regular scarecrow and it will give a crop boost to players.

**Requirements**

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

- Screenshot of the art on the attached backdrop. Pixel size should be the same as the game.

![map](https://user-images.githubusercontent.com/11745561/160247714-71a7431e-d879-4d19-ab02-9998b9f262d0.png)

**Deadline**

30th March

**Winner**

2 winners will be announced
500 SFL + scary scarecrow

**Comment by paluras** [comment]
![scarecrow-export1](https://user-images.githubusercontent.com/98059798/160244652-3e8a93b4-70a5-4a14-8b27-d2b6c988ea77.png)
![Scare](https://user-images.githubusercontent.com/98059798/160244654-91b7ea07-92d2-43d8-8cf4-4f91c7ec291e.png)
![scarecrow](https://user-images.githubusercontent.com/98059798/160244661-a0121aae-6901-4a17-ad15-e3bf088d8d9a.png)
![Screenshot 2022-03-26 164315](https://user-images.githubusercontent.com/98059798/160244663-1995b808-a90a-4a87-bbac-ae696f8b6c8a.png)
second one has a different hat outline..

**Comment by adamhannigan** [comment]
![scary_pumpkin](https://user-images.githubusercontent.com/11745561/160249402-f083556d-c2b5-46c7-96e2-2d167393b1d7.png)
![sacreu_2](https://user-images.githubusercontent.com/11745561/160249404-62771968-12e3-4e04-bf17-d67cb443d07c.png)

I've used this hanging/droopy clothes as reference - [link](https://www.google.com/search?q=pixel+art+scarecrow&sxsrf=APq-WBu-Yd-T1hMKV_BByUvn5qF0CtF_CA:1648310678374&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjC5Nrjk-T2AhXiILkGHfK7DSIQ_AUoAXoECAEQAw&biw=1639&bih=825&dpr=2#imgrc=FAK-V16lKkzfvM).

**Comment by Alexcnder** [comment]
The scary scary scarecrow covered in a sheet of radish polyester

![on background](https://user-images.githubusercontent.com/87881787/160250756-a1d15709-4161-47b9-99cb-4573b24de203.png)
![6](https://user-images.githubusercontent.com/87881787/160250794-1637a09c-44b0-453d-9609-1d97984966b6.png)

**Comment by ItsNight** [comment]
![Sprite-00s04](https://user-images.githubusercontent.com/43474459/160251003-15eae5db-7d91-4140-9d8a-93a133533cda.png)
![160249402-f083556d-c2b5-46c7-96e2-2d167393b1d7-export](https://user-images.githubusercontent.com/43474459/160251006-da255d8e-3736-4dfd-83ad-27f064da797f.png)
![Sprite-ss00s04](https://user-images.githubusercontent.com/43474459/160251086-af57bcae-be04-40a7-b5bf-77ac0b946fa5.png)

**Comment by na66ime** [comment]
Hey guys, first time drawing on Aseprite. Hope you guys like it ;)
![Back](https://user-images.githubusercontent.com/102286455/160252258-31542e8f-a6ea-449f-beea-c9cf0b3f063b.png)
![Scarecrowd](https://user-images.githubusercontent.com/102286455/160252254-3904245a-60d4-462a-b0fd-a68c15d24fe9.png)

**Comment by na66ime** [comment]
Hey guys, first time here and first time drawing on Aseprite. 
![back2](https://user-images.githubusercontent.com/102286455/160252334-d3084a79-285e-4677-8dbe-ac077adbc0bc.png)
![Scarecrowd](https://user-images.githubusercontent.com/102286455/160252337-84839b22-1a81-49ea-9fac-c7531f481c50.png)

**Comment by Aestnelis** [comment]
Scary Scarecrow With His Crow
![scarecrowgif](https://user-images.githubusercontent.com/98103679/160254114-10833a24-e0c3-46b5-b10c-9b3dbba1052c.gif)
![bifscarecrowgif](https://user-images.githubusercontent.com/98103679/160254120-658b3ea4-2f5a-4fcb-86de-13b0827a4297.gif)
![bigssscarecrowgif](https://user-images.githubusercontent.com/98103679/160254124-5b2ad9e1-c26a-40c5-ad35-dcd108349874.gif)

**Comment by gabiqueiroga** [comment]
WIP 
![image](https://user-images.githubusercontent.com/69090306/160256634-4019224f-926e-49cb-9bef-068d8d5b0741.png)

**Comment by adamhannigan** [comment]
@Aestnelis This is beautiful!

Do you think we could make it smaller though? compared to other objects in the game it would be huge (i.e. twice the height of a human)

**Comment by na66ime** [comment]
![scarysn](https://user-images.githubusercontent.com/102286455/160258430-0f88bc71-9865-44a0-ad94-acaad9d65185.png)
Scary enough
![back4](https://user-images.githubusercontent.com/102286455/160258427-52768837-136e-4da3-9658-212789203a5b.png)

**Comment by Aestnelis** [comment]
> @Aestnelis This is beautiful!
> 
> Do you think we could make it smaller though? compared to other objects in the game it would be huge (i.e. twice the height of a human)

Thanks @adamhannigan, adding here! 
![littlescarecrow](https://user-images.githubusercontent.com/98103679/160259106-224bdf7b-dcfb-48e5-96c0-6ea67cce75a6.gif)
![biglittlescarecrow](https://user-images.githubusercontent.com/98103679/160259110-89904543-7d59-4b28-be90-7963519c31dc.gif)
![biglittlesscarecrow](https://user-images.githubusercontent.com/98103679/160259114-755bcd17-2270-459d-9720-2a31d3a522db.gif)

**Comment by SrCouve** [comment]
![ESPANTA](https://user-images.githubusercontent.com/98098233/160262798-fb3b2bf5-fee0-4666-88d6-b5a42533fd8c.png)
![ESPANTA 2](https://user-images.githubusercontent.com/98098233/160262800-58d69785-b209-4879-8d64-f3f8e025dcc1.png)
![ESPANTA4](https://user-images.githubusercontent.com/98098233/160262802-19000af6-8cd0-4720-9a35-6a68dfb48766.png)
I tried to make it a size that was proportional to the characters
and use the game's own pumpkin as a resource

**Comment by Vergelsxtn** [comment]
Hi @adamhannigan it's based on the artwork you submitted, I hope it's ok with you.😊

Blue variant-
![scarecrow-prev-blue](https://user-images.githubusercontent.com/99605039/160262968-52a890db-1291-49a3-ad2e-26fcfc056684.png)
![scarecrow-prev-blue1](https://user-images.githubusercontent.com/99605039/160262972-cb77085b-8d72-4f37-a854-6251d58d16a2.png)
Red variant-
![scarecrow-prev-red](https://user-images.githubusercontent.com/99605039/160263062-93332348-6ce9-472b-bd0a-68da6dcc233e.png)
![scarecrow-prev-red1](https://user-images.githubusercontent.com/99605039/160263063-050b3375-22cc-4c9a-b173-2849401c4245.png)

**Comment by Vergelsxtn** [comment]
Hi @adamhannigan it's based on the artwork you submitted, I hope it's ok with you.😊

Blue variant-
![scarecrow-prev-blue](https://user-images.githubusercontent.com/99605039/160262968-52a890db-1291-49a3-ad2e-26fcfc056684.png)
![scarecrow-prev-blue1](https://user-images.githubusercontent.com/99605039/160262972-cb77085b-8d72-4f37-a854-6251d58d16a2.png)
Red variant-
![scarecrow-prev-red](https://user-images.githubusercontent.com/99605039/160263062-93332348-6ce9-472b-bd0a-68da6dcc233e.png)
![scarecrow-prev-red1](https://user-images.githubusercontent.com/99605039/160263063-050b3375-22cc-4c9a-b173-2849401c4245.png)

**Comment by SrCouve** [comment]
![Espanta](https://user-images.githubusercontent.com/98098233/160263488-42d20387-946d-461e-ae21-f6a023a449cf.gif)
![espant](https://user-images.githubusercontent.com/98098233/160263489-2f2ec2b2-8132-43b7-9e5f-df432c1c5d6b.gif)
![espan](https://user-images.githubusercontent.com/98098233/160263491-afb06aca-483d-4f12-87c0-74c8a710b8d9.gif)

I tried to make it a size that was proportional to the characters
and use the game's own pumpkin as a resource

**Comment by Vergelsxtn** [comment]
Hi @adamhannigan it's based on the artwork you submitted, I hope it's ok with you.😊

☆ Wind effect Animation - Added
☆ w/wo, farming fork
=========
![Scarecrow-animated](https://user-images.githubusercontent.com/99605039/160265166-25fa98d0-518b-4b10-88fe-78cbff6b145c.gif)
![Scarecrow-animated-1](https://user-images.githubusercontent.com/99605039/160265169-683da57f-cb48-4ad7-8191-ec607e38c927.gif)
========
![Scarecrow-animated-prop](https://user-images.githubusercontent.com/99605039/160265191-a745f657-5d8b-451f-986d-abab7fcadeb5.gif)
![Scarecrow-animated-prop1](https://user-images.githubusercontent.com/99605039/160265199-5a5a85db-106e-41b7-8703-faa9e42a4f22.gif)

**Comment by Vergelsxtn** [comment]
Glowing variant
![scarecrow-tmp](https://user-images.githubusercontent.com/99605039/160269005-04e36687-482e-45fd-8b96-3c898655f429.gif)

**Comment by SrCouve** [comment]
This scarecrow is meant to look like an upgrade from the past version
![New Piskel (20)](https://user-images.githubusercontent.com/98098233/160278817-859c9f78-73e6-43bb-a8f1-61bf60c38662.gif)
![New Piskel (17)](https://user-images.githubusercontent.com/98098233/160278822-aa734943-71f9-4852-b1c0-50015a477155.gif)
![New Piskel (21)](https://user-images.githubusercontent.com/98098233/160278858-c9416524-1f5c-4b06-8967-89150e3e08c8.gif)

**Comment by SrCouve** [comment]
This scarecrow is meant to look like an upgrade from the past version
![New Piskel (1)](https://user-images.githubusercontent.com/98098233/160278993-68ed02d6-acd1-4963-a834-97f6531cbcfc.png)
![New Piskel (23)](https://user-images.githubusercontent.com/98098233/160278999-c5624549-b717-416b-8703-5f42a9ca2407.gif)
![New Piskel (22)](https://user-images.githubusercontent.com/98098233/160279001-ddda8e12-d937-45d0-bbe8-afcf57fb34f3.gif)

**Comment by ziddlesticks** [comment]
Left - Animated. Right - Not Animated
![bestofthebestscarecrow](https://user-images.githubusercontent.com/102470098/160282666-711ef8c9-2df7-4197-85cd-2836d13537e2.gif) 
![bestofthebestscarecrow1](https://user-images.githubusercontent.com/102470098/160282678-7ee3c5ba-824c-4993-8b9b-e5691388cd3e.png)
![bbestofthebestscarecrow](https://user-images.githubusercontent.com/102470098/160282709-581c2ccd-ed4d-4cc4-8117-af0b88d939b2.gif)

**Comment by ziddlesticks** [comment]
Left - Animated. Right - Not Animated
![bestofthebestscarecrow](https://user-images.githubusercontent.com/102470098/160282868-f4c96d84-5d16-4138-b4c3-a5de516ee5bc.gif)
![bestofthebestscarecrow1](https://user-images.githubusercontent.com/102470098/160282870-2960b978-9f29-4159-b31a-8900ad4d4a73.png)

**Comment by Telknub** [comment]
HI, :)
Here is my first entry.
I have another idea I would like to try and will probably send it later separately.
This one I made two versions, one with tomato sauce (wink) and another without it.

"Legends say that crow cries can be heard late at the night and it's scythe is never fully clean."

![EcS](https://user-images.githubusercontent.com/38796969/160288471-10e2125a-d0d8-438e-9074-4945cb61f969.png)
![EsS](https://user-images.githubusercontent.com/38796969/160288473-035aa9f3-b3ee-4a2c-a5fe-3ca7b49161c5.png)
![SSsS](https://user-images.githubusercontent.com/38796969/160288474-284daa6a-cf84-4554-879a-63d31dcaec80.png)
![SScS](https://user-images.githubusercontent.com/38796969/160288475-c5a47d93-a767-4696-8cd8-a6eab03e758d.png)

If needed I can animate its face and the "tomato sauce" dripping to make it even more spoooooky.

**Comment by Z1kou** [comment]
Something feels off if you look long enough....
Small version :[Scare crow early work](https://user-images.githubusercontent.com/98262339/160288661-a00ee846-1bfd-42db-bdef-d960244e2918.gif)

Scaled version no Background :
![Scare crow early work](https://user-images.githubusercontent.com/98262339/160288682-74e42337-78de-4b58-928d-b991033d338f.gif)

Scaled version With Background :
![Scare crow early work300%](https://user-images.githubusercontent.com/98262339/160288693-a0be3deb-985d-4744-9e43-4329e0305650.gif)

**Comment by sfwhat** [comment]
Goblin Scarecrow

![reis](https://user-images.githubusercontent.com/95937808/160306919-f12b7cc1-9430-40a4-a4c5-9a0b25f38c4f.gif)
![reis (1)](https://user-images.githubusercontent.com/95937808/160306991-cbd85c1d-9c74-488c-a561-e73c8ceedee2.gif)
![backg](https://user-images.githubusercontent.com/95937808/160307146-60c55c06-bcc3-4197-a0c6-f3e274fe25f1.png)

**Comment by Vergelsxtn** [comment]
Don't mess with this scarecrow or else..
![Scary-scarecrow](https://user-images.githubusercontent.com/99605039/160328985-d840c5b9-caa8-4e29-b01f-05067c1d1ca8.gif)
![Scary-scarecrow1](https://user-images.githubusercontent.com/99605039/160329012-251d91fe-fa7f-4e4a-a75d-778ffc2ac4ba.gif)

**Comment by sfwhat** [comment]
The Glitchcrow

![horror gif](https://user-images.githubusercontent.com/95937808/160397537-097603cf-b9e5-4497-89d1-316566a5716b.gif)
![horror smallgif](https://user-images.githubusercontent.com/95937808/160397541-dc414f5c-6933-415b-8911-3ee411adf21c.gif)
![horror](https://user-images.githubusercontent.com/95937808/160397544-7da1429b-0e9a-4943-951c-41b1fde1f8c8.png)

**Comment by SrCouve** [comment]
![New Piskel (25)](https://user-images.githubusercontent.com/98098233/160450756-118047f1-5c34-4a5b-bad7-559bb216f7ca.gif)
![New Piskel (29)](https://user-images.githubusercontent.com/98098233/160451014-3c76e36e-9976-4e12-a7a4-67f733d6b0b9.gif)

![New Piskel (7)](https://user-images.githubusercontent.com/98098233/160450790-e16b8704-f085-40d4-97a1-65685f26ab37.png)
![New Piskel (26)](https://user-images.githubusercontent.com/98098233/160450924-003e6a90-3942-4c07-9bf2-61a33af5c0ca.gif)
![New Piskel (24)](https://user-images.githubusercontent.com/98098233/160450950-00e35fd2-637c-4cac-93b7-533c6f087bf2.gif)

**Comment by na66ime** [comment]
![sna](https://user-images.githubusercontent.com/102286455/160452472-83337489-b77b-440a-9c7b-e0870ebfc9c2.gif)

**Comment by Alexcnder** [comment]
**scary :O Scarecrow**
 
![Red eyed SAw](https://user-images.githubusercontent.com/87881787/160483994-d21b26cb-ef77-4563-ab47-db19d3099294.png)
![scarecrow RED EYED](https://user-images.githubusercontent.com/87881787/160484014-1824e844-2222-4420-b896-7e6145f057f7.png)

**Comment by Vergelsxtn** [comment]
![Scarecrow-noBG](https://user-images.githubusercontent.com/99605039/160486846-a8d1aafa-14b1-4eb0-b20f-67254efadfe9.gif)
![Scary-scarecrow](https://user-images.githubusercontent.com/99605039/160486913-23047e3c-810c-4467-9db3-b6d44ee33e7d.gif)

![Scarecrow-noBG1](https://user-images.githubusercontent.com/99605039/160487018-c908820a-2e15-483d-a59a-f9af11a8d894.gif)
![Scary-scarecrow1](https://user-images.githubusercontent.com/99605039/160487376-98f17ff9-8b58-49ea-8f04-a78ba61cfa7b.gif)

**Comment by Aestnelis** [comment]
**Made two version of that ScareCROW**

![Darkscarecrow](https://user-images.githubusercontent.com/98103679/160643157-de91a690-2bdd-422a-8ff7-251737c09123.gif)
![bigDarkscarecrow](https://user-images.githubusercontent.com/98103679/160643188-4788c16c-80cd-4651-b43b-95474afb9ffc.gif)
![SunflowerDarkscarecrow](https://user-images.githubusercontent.com/98103679/160643227-ea0be3a7-6d3e-4117-936a-bb8679ac726d.gif)




![lastscarecrow](https://user-images.githubusercontent.com/98103679/160643301-76105554-9fc8-4cb0-9f91-020f890aa289.gif)
![biglastscarecrow](https://user-images.githubusercontent.com/98103679/160643324-42035fc9-6889-41ae-8cd1-3b490927fd9f.gif)
![sunflowerbiglastscarecrow](https://user-images.githubusercontent.com/98103679/160643358-e4cda9ce-c176-4cb7-a363-7f37cfa2ac23.gif)

**Comment by benaxol12** [comment]
### Two Goblin Scarecrows
![goblin-1](https://user-images.githubusercontent.com/98098031/160651306-26eb3b07-ac06-4dfc-b092-724d5646a8cd.png)
![goblin-2](https://user-images.githubusercontent.com/98098031/160651308-86451a51-1cf3-41d2-a046-8cac561c0a91.png)

![goblin1](https://user-images.githubusercontent.com/98098031/160651346-10847127-9363-42ee-8368-2a17efefe359.png)
![goblin2](https://user-images.githubusercontent.com/98098031/160651352-85df93b7-1632-4dad-82bd-f0bcb8bf421a.png)


### Special Scarecrows 
If you are lucky after planting a pumpkin, this pumpkin will turn into a special pumpkin and you can produce scarecrows with this pumpkin.
I can't even imagine what will happen when you collect all color (Coming Soon)

![Pumpkin variant12](https://user-images.githubusercontent.com/98098031/160649000-a91bce84-8fe3-4517-8efe-6a6c5bf93974.png)


I didn't want to send each one individually as it would take up too much space.

Edited with reference to the scarecrow posted by @adamhannigan

**Comment by adamhannigan** [comment]
This has hands down been the most creative submissions we have seen so far. Well done everybody 👏 

The winners are:

@benaxol12 Goblin Scarecrow 🏆 
@Aestnelis Purple Scarecrow 🏆 

These 2 fit the game aesthetic on the fields and in the UI. The animations from everyone were mind blowing ❤️
