### ISSUE TITLE
[FEAT] Random Chicken Placement on Daily Reset

### ISSUE THREAD

**Issue by jovylle** [sunflower-land/sunflower-land#4486]
## Summary of Request

As a player, I would like the chickens in the game to be randomly placed at any available location upon daily reset. Currently, chickens stay where the player places them and do not move unless manually relocated. By adding random placement of chickens at reset, this feature could enhance the feeling of a dynamic and lively farm, offering small surprises each day. Players would still retain the ability to manually move chickens on demand, preserving player control.

## Proof of Community Demand

1. N/A, I only thought this on my own carefully.
  
## Contributors

- TODO

## Technical Requirements

1. At the end of each day (during the reset), implement logic to randomly place chickens on any available, unoccupied tile.
2. The random placement logic should avoid tiles that are blocked by objects or other animals.
3. Ensure that chickens can still be moved manually by players, overriding the random placement when desired.

### Backend Updates Needed

1. Backend support for tracking and updating chicken positions during the daily reset.
2. N/A for any major architectural changes.

### Smart Contract Updates Needed

1. N/A

## UI/UX Design Requirements

1. N/A - No new UI/UX elements required as the existing interface for moving chickens is retained.

## Assets Needed

1. N/A - No new assets are required since the feature does not involve new visuals or sounds.

**Comment by brian-man** [comment]
Please no.  Don't do random stuff to my farm.  That's called a bug not a feature.  It would suck.

**Comment by Dionis404** [comment]
It doesn't make any sense for the following reasons: 
1. Many players don't have free space
2. The chickens will be moved to the coop.
