### ISSUE TITLE
[ART/PROPOSAL] Farm Cat House

### ISSUE THREAD

**Issue by Aestnelis** [sunflower-land/sunflower-land#455]
Deleted.

**Comment by adamhannigan** [comment]
@Aestnelis Great idea. A decor NPC would be much appreciated 🤗 Finally Victoria has somewhere to sleep!

From an art POV, I have 2 bits of feedback:

1. The colour palette seems a bit dull compared to the sunnyside base asset pack. It doesn't quite have that consistent feel
2. Most of the items in the game are short and stubby (i.e. houses, people, trees). The skinny poles and height of this cat house sort of breaks that pattern. I would suggest trying to flatten and fatten the cat house if possible. (perhaps use one poll that is much thicker)?

**Comment by na66ime** [comment]
We could also add a small house for the dog, here's my idea:
![doghouse](https://user-images.githubusercontent.com/102286455/160634044-91a51ad8-e0ee-4bab-81c9-0752e248655e.gif)
![doghouse3](https://user-images.githubusercontent.com/102286455/160634102-34f147fb-6a5b-4487-bc8a-979e4a6f9568.gif)

**Comment by Aestnelis** [comment]
> 
Hey, thanks for the feedbacks! I will fix them and send with a decor NPC!

**Comment by Aestnelis** [comment]
> @Aestnelis Great idea. A decor NPC would be much appreciated 🤗 Finally Victoria has somewhere to sleep!
> 
> From an art POV, I have 2 bits of feedback:
> 
> 1. The colour palette seems a bit dull compared to the sunnyside base asset pack. It doesn't quite have that consistent feel
> 2. Most of the items in the game are short and stubby (i.e. houses, people, trees). The skinny poles and height of this cat house sort of breaks that pattern. I would suggest trying to flatten and fatten the cat house if possible. (perhaps use one poll that is much thicker)?

Hey @adamhannigan, added new versions of this cat tree by applying some feedbacks
![bigsunflowercattreesgif](https://user-images.githubusercontent.com/98103679/161727201-b2347f0c-0da4-479d-b7a2-c8cdee93d91d.gif)
