### ISSUE TITLE
[ART] Marketplace Promo

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#460]
This is a request for material to be used in a marketplace promo on Rarible. They are planning to do a "Sunflower Takeover" and give us a prime listing.

They will require a promo banner that will be showcased. It can either be a short video (mp4) or png.

The promo should display the Sunflower Land brand + show off some of the collectibles and/or gameplay.

**Requirements**

.mp4 or .png file, 3-5MB, 800x800, 3-4 seconds - for homepage feature

**Deadline**

3rd April

**Winner**

750 SFL + unnannounced rare item (Supply 500)

**Comment by SrCouve** [comment]
![sunflot_000045](https://user-images.githubusercontent.com/98098233/160707742-d143d696-f64e-4167-94bd-61e11dbe0ca3.png)

**Comment by Alexcnder** [comment]
So it should be animated?

**Comment by ItsNight** [comment]
![SpritSe-0012](https://user-images.githubusercontent.com/43474459/160715301-e3463873-1fbd-41dd-ba7a-bf93545c9b26.gif)

**Comment by adamhannigan** [comment]
> So it should be animated?

It does not need to be animated. It can be static, or a mp4 - 800x800

**Comment by Vergelsxtn** [comment]
Is 720x720, accepted? (Video mp4)

**Comment by ItsNight** [comment]
![SpritfxeS-0012](https://user-images.githubusercontent.com/43474459/160798559-e47bdf4c-61d2-4dba-a5ca-4fa21174dd4c.gif)
![image](https://user-images.githubusercontent.com/43474459/160798662-274cc5be-ac86-4eec-a7ef-462fb756b00d.png)
![image](https://user-images.githubusercontent.com/43474459/160800065-566ed18b-e33a-44a0-a021-07c270d8c4ab.png)

**Comment by ItsNight** [comment]
![Spddrite-0003](https://user-images.githubusercontent.com/43474459/160929767-ce146194-4b45-47bf-820b-b953ff0c3491.gif)

**Comment by wildwebd** [comment]
First art contribution ❤️ 

File extension : .mp4
Dimensions : 800x800
File size : 507Ko
Duration : Exactly 4 seconds

GIF preview :

![PROMOSFLbyWill](https://user-images.githubusercontent.com/102468955/161083990-53491a93-73d3-4fa6-8405-c344cbb85716.gif)

MP4 :

https://user-images.githubusercontent.com/102468955/161083441-a8ec639a-d045-4a63-9354-022ffd9c12d8.mp4


Polygon address : 0x0C814cC0A33B643635ce520F9E0D868298ABd386

I spent a lot of time on this, I hope you like it 😍

**Comment by SrCouve** [comment]
https://user-images.githubusercontent.com/98098233/161101316-710b6f43-9b99-48c8-b6b8-1faab7dbcb76.mp4

https://user-images.githubusercontent.com/98098233/161101365-0f41c40c-cb05-4ae3-888d-7c6f5bf948c0.mp4


https://user-images.githubusercontent.com/98098233/161101404-baea7eef-c9e5-4e9d-9b89-0802b36ea218.mp4

**Comment by na66ime** [comment]
![promo9](https://user-images.githubusercontent.com/102286455/161121924-aadd4107-1d5d-4892-bbfc-b7b11bdab12c.gif)

**Comment by gabiqueiroga** [comment]
https://user-images.githubusercontent.com/69090306/161137744-b8ead0a1-15fb-499d-be0d-c2801bd2b30f.mp4

**Comment by gabiqueiroga** [comment]
![promo3](https://user-images.githubusercontent.com/69090306/161154212-7c7b5ad4-b95e-4cea-bb68-f93f3f5196e9.gif)

**Comment by gabiqueiroga** [comment]
![Promo 2](https://user-images.githubusercontent.com/69090306/161156724-71e3e2fa-f7f9-4a67-9f88-554baba0b923.gif)

**Comment by RogGarcia** [comment]
Looped videos / v1 e v2 / MP4 800x800px / 4.87mb / 4.78m
Note: the original file does not have these artifacts in animated items. There was probably an automatic compression of the file when uploading to Github. Attached is one of the original videos (ZIP file).

https://user-images.githubusercontent.com/98653977/161161724-6b98a3d7-8247-4d40-aaa4-36145fc7451c.mp4

https://user-images.githubusercontent.com/98653977/161161745-41e16cde-3973-4f37-b8d0-f3fb80fe4804.mp4

[Sequence 01_1.zip](https://github.com/sunflower-land/sunflower-land/files/8393504/Sequence.01_1.zip)

**Comment by na66ime** [comment]
Fixed clouds animation, added a goblin and sunflowers behind the fences.
![promo18](https://user-images.githubusercontent.com/102286455/161167798-78ec01c6-f082-45d2-8d8e-73e763860152.gif)

**Comment by Alexcnder** [comment]
**suggestions are appreciated**

I was inspired by Vergel#8727 picture and The Letters i used were inspired by NIGHT#2858 (but i have redone every single one)

![5 sec preview](https://user-images.githubusercontent.com/87881787/161290209-604a0b3e-be09-4c5b-84c3-aa2c46c4de96.gif)

**Comment by Vergelsxtn** [comment]
> **suggestions are appreciated**
> 
> Is a gif ok or should i convert to a mp4?
> 
> I was inspired by Vergel#8727 picture and The Letters i used were inspired by NIGHT#2858 (but i have redone every single one)
> 
> ![5 sec preview](https://user-images.githubusercontent.com/87881787/161290209-604a0b3e-be09-4c5b-84c3-aa2c46c4de96.gif)

Make a Mp4 format bro, just to be sure.
Looking good💪🕶

**Comment by na66ime** [comment]
> > **suggestions are appreciated**
> > Is a gif ok or should i convert to a mp4?
> > I was inspired by Vergel#8727 picture and The Letters i used were inspired by NIGHT#2858 (but i have redone every single one)
> > ![5 sec preview](https://user-images.githubusercontent.com/87881787/161290209-604a0b3e-be09-4c5b-84c3-aa2c46c4de96.gif)
> 
> Make a Mp4 format bro, just to be sure. Looking good💪🕶

Hey mate, do you know how to export as mp4?

**Comment by DEDYR911** [comment]
[
![Sunflower Land Art](https://user-images.githubusercontent.com/102835718/161351415-bb5b7372-d7ce-4dee-8c5c-2607dbdea091.png)
](url)

**Comment by LeShykun** [comment]
https://user-images.githubusercontent.com/99097146/161363636-7e0466d3-1804-4e7c-884a-fab4b9989fd4.mp4

**Comment by benaxol12** [comment]
.mp4 file, 630 kb, 800x800, 4 seconds 

https://user-images.githubusercontent.com/98098031/161379111-e1eb9b7b-fbfe-4782-835d-02581d070a7c.mp4

**Comment by Alexcnder** [comment]
> > **suggestions are appreciated**
> > Is a gif ok or should i convert to a mp4?
> > I was inspired by Vergel#8727 picture and The Letters i used were inspired by NIGHT#2858 (but i have redone every single one)
> > ![5 sec preview](
> 
> Make a Mp4 format bro, just to be sure. Looking good💪🕶

https://user-images.githubusercontent.com/87881787/161421784-d73dd244-8878-46a8-84ed-e2d5113f39fb.mp4

**Comment by Telknub** [comment]
I was busy and did not have a lot of time to make it, but here is my entry.

https://user-images.githubusercontent.com/38796969/161436160-17739d53-8917-4a43-903d-5a2fc7614f1d.mp4

Hopefully I made it in time :)

**Comment by Z1kou** [comment]
My Neighbor Telk said he will be late for this contest, had to outdo him xD! Here is my take on this Little intro for Sunflower Land, ended up making abit of a long one so 4 second was too short but i managed !
https://user-images.githubusercontent.com/98262339/161481334-0feb9c16-bf52-473f-9fff-084f6bb6a610.mp4

**Comment by adamhannigan** [comment]
Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁 

@wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done! 

The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗 

For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀 

Please comment your Farm ID before 10th of April. 👏

**Comment by ItsNight** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

ID : 24

**Comment by Telknub** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

Thanks and congrats to everyone! 🎉
My farm ID is 86

**Comment by Z1kou** [comment]
Eyy congrats everyone 🎉🎉🎉🎉

My farm if is #87

**Comment by benaxol12** [comment]
My farm ID : 18 😇

**Comment by wildwebd** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

Thank you Adam, thank you Team Rarible guy, and congratulations to all the participants !
I'm so proud to have won, you made my day !
Moreover it was my first art proposal, It motivates me a lot !
Love u all and congrats ❤️ 
Farm ID : 1093

**Comment by LeShykun** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

Was a challenging one  to make a promo on 4 seconds, Congrats @wildwebd !
Farm ID: 27

**Comment by SrCouve** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

Farm ID: 82

**Comment by gabiqueiroga** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

Farm ID: 56

**Comment by Vergelsxtn** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... drum
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months hugs
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! star rocket
> 
> Please comment your Farm ID before 10th of April. clap

Farm ID: 63

Thankyou.

**Comment by RogGarcia** [comment]
Farm ID: 271

Parabéns @wildwebd! ("congrats" in portuguese :) )
Tks!

**Comment by Alexcnder** [comment]
Farm Id: 58

**Comment by DEDYR911** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏


My farm ID : 1084

**Comment by na66ime** [comment]
> Amazing contributions. I've just heard back from our partner at Rarible and we have a winner..... 🥁
> 
> @wildwebd Congratulations! Feedback was that the one showing the gameplay was the most attention grabbing for users. Well done!
> 
> The amount of talent in this proposal was outstanding! We will definitely use a few of these in promotions and social media over the coming months 🤗
> 
> For those that submitted a piece we will also be sending 150 SFL as runner-up prizes! ⭐ 🚀
> 
> Please comment your Farm ID before 10th of April. 👏

Farm ID: 100
