### ISSUE TITLE
[PROPOSAL] Land Expansion: Biomes

### ISSUE THREAD

**Issue by RogGarcia** [sunflower-land/sunflower-land#464]
Hello.
I would like to propose a possible dynamic for land expansion that would be linked to the type of specialization that the player seeks and a second generation of NFTs linked to that proposal.
In general terms, the expansion would follow the logic of skills (Green Thumb, for example) and their improvements in agriculture, livestock, lumberjack and mining.
The general idea is the player, when expanding his lands, chooses the type of land (or biome) that best suits his production strategy.
Each "biome" would give access to a pre-defined amount of original game resources and plantation spaces, as well as special access to a unique resource, collectable only in the chosen biome.

Examples:

>>Biome 01 / Mountains
+6 planting spaces
+4 trees
+1 stone
+1 steel
+1 gold
+3 OAK (SPECIAL FEATURE)

>>Biome 02 / Plain
+10 planting spaces
+2 trees
+2 stone
+1 steel
+1 gold
+3 COPPER (SPECIAL FEATURE)

The amount of  inicial "biomes" depends on the balance the developers want to give the game.
Launching new biomes or land expansions with unique features can be a good marketing strategy for the long term. This is looking like Minecraft... :)

NFTs (second generation)

The second generation of NFTs would be linked to special resources, as it would be impossible to make them with access to only one of the special resources, that is, without exception these NFTs would need oak and copper (in addition to other original game resources)
As each player, or farm, has chosen to expand land for a specific biome, he has access to only one of the possible special resources, which makes trading these special resources between players inevitable.

**Comment by adamhannigan** [comment]
#215 

It would be good to add onto this conversation.

In the proposed design, you would pick 4 different directions to go (mountains, snow, autumn or water). I like the idea of encouraging certain specialisations to go one way 👏
