### ISSUE TITLE
[PROPOSAL] Fair tracking of loyalty into the future

### ISSUE THREAD

**Issue by block-kid** [sunflower-land/sunflower-land#466]
**Issue**
How do we track long term commitment and reward players over time. We will need this mechanism for deciding on future airdrops and Easter egg buffs.

**Proposal**
Check Farmer _exp_ and time since  the Farm was minted _timePast_ = _now - mintTime_

Calculate _renown_ = _exp x timePast_

This is easy to implement and can easily take into account questing _exp_ in the future. Extra variables can be added in the future, e.g. battles won, length of peacetime(time since last battle/war), land size.

**Possible Future Perks**
- airdrops
- buffs 
   - e.g better market prices, 
   - better negotiation/outcomes/rewards with goblins
   - recruitment
   - temporary trade deals
   - special buildings
   - lower withdrawal fees
   - early access to nft minting
 
I'm sure you've already considered such things, but I thought I'd drop this here while it passed through my brain. 🌩️ 
Loving your works as always! ❤️

**Comment by block-kid** [comment]
A note. This also addresses common issues being raised around rewarding **play-to-earn** vs **buy-to-earn**. All the mechanisms above require no capital, only time. But results in the value of a farm increasing with time played, which a player can sell later if they wish. Keeping both players and buyers happy. 🥳

**Comment by adamhannigan** [comment]
@block-kid Great idea. We definitely will release mechanisms that favour the long term players 🚀
