### ISSUE TITLE
[ART/PROPOSAL] Artisans and the re-rolling of NFT looks as a feature/SFL sink

### ISSUE THREAD

**Issue by DonatasDee** [sunflower-land/sunflower-land#473]
This is a collaborative proposal/project by Dee, Tiffanydys and VP from the SFL community.

**Need for Uniqueness (NFU) and its effect on longevity of NFT's.**

The Sunflower Land game has built on its roots by being a community driven game, this proposal targets the art and artists while addressing the need for longevity of the uniqueness of NFT's.

**The current climate of NFT's in SFL:**

The current situation is one of community driven success and the promise that the players see within, especially seeing the art and features as they get created, however with more and more different artists - their different views and representations of assets, the public also gets more likely to get picky and like a specific design, therefore the customization of the farm and it's NFT's is crucial. 

Whilst it's of great need to create many different NFT's for features and additions to functionality, the cosmetic side is just as much if not more important for longevity. The NFT's right now as they are, while providing uniqueness - do it for a very limited amount of time. Need for Uniqueness (NFU) is a concept where the Uniqueness of an item is considered when building a product that has a big lifespan. In fact the buying pressure of the item is increased the longer it can hold its uniqueness.

The issue of keeping consistency of looks regarding the NFT's is a thing that I have seen mentioned by the team. The key here is choosing a winner that has the most modular and creative cosmetic, which then allows others to build on top of it, whilst following specific guidelines - this in effect allows more different art while keeping the same "skeleton" of the asset.

**In short, the points the proposal tries to battle/help:**

- Providing ongoing shelf life and continuous uniqueness for NFT's.
- Rewarding the artists and getting them more involved.
- Constant ability to customize the originality of a farm.
- Another continuous burn mechanism for resources and tokens.

**Having the ability to choose a look for a cost vs. Rolling for them**

There are two ways to go about "skins" in this situation:

- Choosing a look allows for freedom but battles with uniqueness at the same time as people juggle from look to look, by being freely unique - the item loses its uniqueness at the same time, there is no reason to look for unique looks on the 3rd party markets like OS , Rarible and so on.

- Hunting/Having to roll for a particular look creates a different kind of uniqueness that creates scarcity for particular looks that people want to go for, creating buy pressure in the 3rd party markets while still allowing original looks that aren't the base.

**The case for our system and how it would work:**

Firstly, an important criteria for choosing art would include modularity, because that in itself creates more possibility for the community to make their own versions of said NFT's.

The winning artist wins and then there's a second phase where everyone is allowed to build another variation of art built on the same base/skeleton while following the guidelines of the design and its concept. This way every NFT and its associated skins have the community building it and involved in the effort every time - not every NFT needs to have a full palette of different looks at launch if there's not enough art at the deadline, additional art can be submitted and added at any time.

**COST OF REROLLING:**
The cost is a crucial factor when it comes to the system being used constantly or getting underutilized, for this we propose a scaling system that considers the original mint cost and then has a limited amount of re-rolls for the looks.
**HOW IT WOULD WORK:**
Let's say the original cost of an NFT is 1000 SFL at the 5 Million SFL halvening point - that would make the first re-roll of the NFT's skin cost 10% of the mints cost, in this case 100 SFL (this could be halved as many times as we've seen halvening happen). Every re-roll going forwards would multiply the cost x2, so 100/200/400 SFL (would be different if halvenings happened). 

**THE CASE FOR LOCKING UP RE-ROLL ATTEMPTS:**
This is purely to hold up NFT values and drive up scarcity as the re-roll attempts get eaten up. While the lock up number could be changed and the cost alongside with it regarding the multiplication, I think it is pretty crucial to have a lock up period to drive scarcity, provide value for the main token/resources while burning a good amount of it.

_In any case, depending on the feedback we will keep building on the system and the assets it might require._

_We have a bunch of art on this already set as an example along with the in-game NPC's that could represent the mechanic. 
Tiffanydys put everything in the game and made the UI work for the Non-Randomized part of the proposal._

https://user-images.githubusercontent.com/102658496/161299427-42cd014f-d760-4f65-b919-245a91db96eb.mov

https://user-images.githubusercontent.com/102658496/161299439-d4475b85-dc88-4a28-9e53-3f7b77be84da.mov

![FINAL (1)](https://user-images.githubusercontent.com/102658496/161299604-ffe60226-309d-49bb-ab14-679390e521a5.gif)
![COINFLIP](https://user-images.githubusercontent.com/102658496/161299610-176e8437-ef1c-4eec-97c4-31394d99c7bc.gif)

 
![Doge5](https://user-images.githubusercontent.com/102658496/161299694-65fe11fd-308b-43b1-a044-13a4baac1c09.png)
![Doge](https://user-images.githubusercontent.com/102658496/161299697-92a96ecd-755a-4def-8ed3-89cff2883e43.png)
![Doge1](https://user-images.githubusercontent.com/102658496/161299698-7f5a3608-3aeb-4221-8ba1-fb5faad425b1.png)
![Doge2](https://user-images.githubusercontent.com/102658496/161299701-07987e7b-a293-4b05-b875-a37c6a893ffd.png)
![Doge3](https://user-images.githubusercontent.com/102658496/161299704-eaf41528-c0a6-46ca-8fcd-fabc1cf9a34e.png)
![Doge4](https://user-images.githubusercontent.com/102658496/161299708-8e1d8490-a391-4698-88b4-4f191d82e1d3.png)
![Doge6](https://user-images.githubusercontent.com/102658496/161299648-eb3b5b81-2b4c-46e1-9a1f-24c75ec0e1df.png)
![Doge7](https://user-images.githubusercontent.com/102658496/161299651-e03efac0-ec72-4ff3-8e54-23bf18cc0f14.png)
![Doge8](https://user-images.githubusercontent.com/102658496/161299653-11a6ed26-6dd4-4af8-ac5d-8be6a26e8653.png)
![Doge9](https://user-images.githubusercontent.com/102658496/161299655-a48d09e8-6ddc-4e89-957f-ec951277ba99.png)
![Doge10](https://user-images.githubusercontent.com/102658496/161299659-eb5487a5-f5a0-421c-b6bf-95c036573062.png)

![Cat10](https://user-images.githubusercontent.com/102658496/161299765-e95efaa7-8309-4d83-b99e-f9914aa5b41d.png)
![Cat](https://user-images.githubusercontent.com/102658496/161299768-8277aca2-5570-4b62-b820-bea28a60bad5.png)
![Cat1](https://user-images.githubusercontent.com/102658496/161299770-17d6437e-ba0f-422c-8505-6b02a1fb03c4.png)
![Cat2](https://user-images.githubusercontent.com/102658496/161299772-57479322-f153-4707-8108-213917406366.png)
![Cat3](https://user-images.githubusercontent.com/102658496/161299774-7f8c788e-864f-4358-b822-378710a0a0df.png)
![Cat4](https://user-images.githubusercontent.com/102658496/161299777-66922989-1acc-422b-ad5b-247f424adade.png)
![Cat5](https://user-images.githubusercontent.com/102658496/161299778-73eb741e-9877-4ee4-adc3-5e7e71ec6ed1.png)
![Cat6](https://user-images.githubusercontent.com/102658496/161299780-1e99a9a4-0632-4eb5-baa2-fa25c6a81005.png)
![Cat7](https://user-images.githubusercontent.com/102658496/161299782-6806f8b9-c355-4b8a-8d50-48467911fad5.png)
![Cat8](https://user-images.githubusercontent.com/102658496/161299785-1f3717fd-5c95-4c2e-92bc-af8c7bb05634.png)
![Cat9](https://user-images.githubusercontent.com/102658496/161299788-6c0adad2-a46c-4694-98ba-9cb3d1f2424c.png)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
