### ISSUE TITLE
[ART] Zyon Gold Statue

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#477]

**Comment by DonatasDee** [comment]
So not to be THAT guy - and I know the characters name is Zyon, but I'm not sure you want a massive Z on the statue that is about a knight considering the current climate.

**Comment by Compliic** [comment]
Nice idea, I thought it was very beautiful, keep it up farmer.

**Comment by ElcomJ** [comment]
I just loved this art, as well as your Lore, I would love for it to be added to Sunflower Land.

**Comment by SrCouve** [comment]
> So not to be THAT guy - and I know the characters name is Zyon, but I'm not sure you want a massive Z on the statue that is about a knight considering the current climate.

Z is a letter of the alphabet, I chose it because of the aesthetics, this connection makes no sense, sometimes it is discouraging to present something here, I spent hours coming up with this idea, then the first comment is something making a correlation that makes no sense, criticizing art, if I put an A , would I be making an analogy to Anarchism? I understand if it was a symbol that referred to something, now a letter of the alphabet, I had to google it to understand your comment

**Comment by SrCouve** [comment]
**_Tyon Lann:_**
![T Statue](https://user-images.githubusercontent.com/98098233/161396496-c6856982-1406-46e0-9e48-7d9a23b7e038.png)
![T SWORD](https://user-images.githubusercontent.com/98098233/161396498-f483b8a8-c8c3-4a6d-87aa-458003869e65.png)
![T Statue](https://user-images.githubusercontent.com/98098233/161396502-5d885f13-e880-4e8d-a305-043af8370019.gif)
![T SWORD](https://user-images.githubusercontent.com/98098233/161396505-ec2abb00-4671-4287-9afe-81496b748af9.gif)

**Comment by aimlemonade** [comment]
Put a M there for Manbino ;)

**Comment by DonatasDee** [comment]
> > So not to be THAT guy - and I know the characters name is Zyon, but I'm not sure you want a massive Z on the statue that is about a knight considering the current climate.
> 
> Z is a letter of the alphabet, I chose it because of the aesthetics, this connection makes no sense, sometimes it is discouraging to present something here, I spent hours coming up with this idea, then the first comment is something making a correlation that makes no sense, criticizing art, if I put an A , would I be making an analogy to Anarchism? I understand if it was a symbol that referred to something, now a letter of the alphabet, I had to google it to understand your comment

I appreciate the change, there's no need for dramatics. Good job on the statue

**Comment by SrCouve** [comment]
**Nyon Lann**

![N STATUE](https://user-images.githubusercontent.com/98098233/161396789-b0192cba-9510-4803-981c-32deb271f0a7.png)
![N SWORD ](https://user-images.githubusercontent.com/98098233/161396790-937a4076-9eed-4933-ab8b-639e180d4981.png)
![N STATUE](https://user-images.githubusercontent.com/98098233/161396794-4a3e6af0-9e35-46f7-a655-5ded62ff6979.gif)
![N SWORD ](https://user-images.githubusercontent.com/98098233/161396795-015f33d5-1936-44d8-8b08-e3f311799491.gif)
