### ISSUE TITLE
[ART] Rework Gnome 

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#480]
The current gnome is an art of 273x470 size reduced to be the size of the other characters that are between 20x20 and 80x80 because of that he gets the pixel size outside the game's standard,

![image](https://user-images.githubusercontent.com/98098233/161570627-b0f689c1-f868-4196-87ba-174f8f6d4c4b.png)![image](https://user-images.githubusercontent.com/98098233/161473564-9e3a90a7-c07d-4226-af0b-291b9d0a2b0f.png)

Because of that I decided to do a rework for the gnome, in the size of 13x17, in the proportion of the pixel size exactly the same as the other characters in the game

![image](https://user-images.githubusercontent.com/98098233/161570921-a91b06b1-d639-4165-bdfd-a8f5117de57c.png)

![image](https://user-images.githubusercontent.com/98098233/161474981-315aefa3-4510-4000-9245-35dfbee21ec2.png)![Gnome](https://user-images.githubusercontent.com/98098233/161474835-2260893e-7726-44a6-abf2-6fcd0c21395d.png)
![image](https://user-images.githubusercontent.com/98098233/161571610-a5145be3-fef9-4665-93de-4a8c91e3c5e2.png)

**Comment by SrCouve** [comment]
Move:
![GNOME MOVE F](https://user-images.githubusercontent.com/98098233/161649243-5cd3a8aa-9be3-4588-b449-8646982f8a1f.gif)
![GNOME MOVE BIG F](https://user-images.githubusercontent.com/98098233/161649252-1f7d9519-1ffe-4625-b579-ef51f347a6a8.gif)

**Comment by SrCouve** [comment]
Move:
![GNOME MOVE F](https://user-images.githubusercontent.com/98098233/161649766-83b15ace-44e3-4991-90e8-e401968163e5.gif)
![GNOME MOVE BIG F](https://user-images.githubusercontent.com/98098233/161649783-ac693416-fd89-4fd6-a9ee-b4f1b004bcb9.gif)

**Comment by SrCouve** [comment]
Move:
![GNOME MOVE F](https://user-images.githubusercontent.com/98098233/161650037-fd05ae2f-f2f5-476e-9198-0b19f18a2307.gif)
![GNOME MOVE BIG F](https://user-images.githubusercontent.com/98098233/161650045-2dad875a-41eb-47da-a547-9da68a52afda.gif)

**Comment by adamhannigan** [comment]
@SrCouve Awesome work 👏 ❤️ 

Let's get this in the game

**Comment by adamhannigan** [comment]
What is your Farm ID? Will make sure you get one on your farm 🤗

**Comment by SrCouve** [comment]
> What is your Farm ID? Will make sure you get one on your farm 🤗

Farm: 82
Wallet:
0x53cF3645c491241B35c0a90ebfdE5b91A6bFc763

I'm very happy, I'm passionate about this project ♥

**Comment by adamhannigan** [comment]
@SrCouve This is now on testnet 👏 

An extra gnome has been sent to your address ;)
