### ISSUE TITLE
[DOC] - How can i run it local and testnets? 

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#483]
Could you please explain on doc, if i deploy contracts on testnet how can i add this to front? I don't know much about typescript but as i m studying solidity and this is the biggest project available on GitHub, believe it will be very interesting to work with  and contribute to the project. It's a robust with an active community. has already been on PROD and will back soon. I believe this can attract more contributors to the project.

Thank you.

**Comment by adamhannigan** [comment]
@future2back Hey 👋 Glad to have you here.

You can copy the `.env.sample` into a `.env` file to get set up with some of the config + contract addresses.

You won't be able to interact with our server for testnet though as it is currently blocked (botters were using it to practice their algorithms)

**Comment by future2back** [comment]
Hello @adamhannigan thanks for replying.
Inside ` .env.sample`

```
VITE_BETA_CONTRACT=0xdC8Af483b737B6C342649A74E009781Fe2eDFCA6
VITE_SESSION_CONTRACT=0x7BEEB448b602Dd8cf640f670d5164b158C67C556
VITE_FARM_CONTRACT=0xB554607D04D6C3EecAb4Cd19A0cF8218BD82fff0
VITE_INVENTORY_CONTRACT=0xfd3b40980aF8706D77C61782eA1ecEFF7600e344
VITE_TOKEN_CONTRACT=0x1D24F82b5d9d72450C2ed065F51827Eb280FFA38
VITE_WISHING_WELL_CONTRACT=0x8573A4353D90C29b90A157F4E3e3Eb1981D07046
VITE_PAIR_CONTRACT=0xaE42EA9864C36820627068a11959915f817ce809
VITE_DONATION_ADDRESS=0x6D18a54E0fd87FCb84a0510A3eCd8855b7226715
```

on https://github.com/sunflower-land/contracts/tree/main/contracts
Which of these are PAIR_CONTRACT and DONATION_CONTRACT and what are these contracts for?

After contract deployed and `.env` file edited
All i have to do is [getting started](https://github.com/sunflower-land/sunflower-land#-getting-started)
The command `yarn dev` already starts a new http server? What is it for? I m sorry for those questions.



Could you explain me better?


Thank you.
