### ISSUE TITLE
[ART] Pet Birds (that can Dance?!) 

### ISSUE THREAD

**Issue by Netherzapdos** [sunflower-land/sunflower-land#484]
### **Pet Birds**

Hey everyone! This will be my 2nd Art Proposal for the game and really excited to show this one. 

** Play with sound ON for Immersion 😎 **

https://user-images.githubusercontent.com/101855553/161687167-fc5f6a55-2074-4a24-b9e1-65eb3646b16c.mp4

Similar to the Cat and Dog pets (minus the utility), this will be a decorative NFT that aims to yet again help make the game feel more alive, by introducing some colorful, animated birds!

The birds I will be proposing are:

- Parrot
- Blue Jay
- American Woodcock

While they are purely decorative pets, they have a special feature! Every time a farmer plays the SFL Radio on the lower right, all the birds that the farmer currently owns will begin to dance to the music! Once stopped, the birds will go back to their idle animation.

And yes, this is 100% a reference to Minecraft's dancing parrots 🤣 However, I do think it fits the game and adds an element of fun :)

---
### **NFT**

The NFTs will be craftable in the Barn, where the Cat and Dog NFTs are also located. Once crafted, I propose that they be placed in the location as seen in the video (changeable).

The pricing of the NFTs will be:

- Parrot (250 sunflowers)
- Blue Jay (50 pumpkins)
- American Woodcock (10 cabbages)

**Descripttions**

- Parrot "Give me seeds!"
- Blue Jay " *chirp* *chirp* "
- American Woodcock "It looks like it's dancing."

Not really great at thinking of the economic side, so any suggestions to the pricing is appreciated! I was hoping to feed it other crops/food that is appropriate (i.e. Worms) but seeing as the assets are still limited, I'll be sticking with these for now. 

---
### **Assets**

Adjusted as of 4/22 to fit the game's color palettes
Reworked as of 4/24 to reduce the Blue Jay and American Woodcock's sizes. They apparently looked really big before. Now fixed.

Previews & Assets:
**Parrot**
![Parrot Idle L](https://user-images.githubusercontent.com/101855553/164606752-eaa4b532-07aa-41f1-85f6-6c5f4fcf6263.gif) ![Parrot Dancing L](https://user-images.githubusercontent.com/101855553/164606758-8df51334-a12c-4efe-abbd-3f1327a0e7a8.gif)
![Parrot Idle](https://user-images.githubusercontent.com/101855553/164606840-42fa5fc2-e669-42b2-bb98-6b0d98135d6b.gif) ![Parrot Dancing](https://user-images.githubusercontent.com/101855553/164606846-be3f68e0-b25e-4b09-90c1-35d84187e787.gif)

New Dance (200 frames)
![Parrot Dance 2 L](https://user-images.githubusercontent.com/101855553/164608629-69bbe7d3-d40f-441d-b6ad-5d09b6f2c80c.gif)
![Parrot Dance 2](https://user-images.githubusercontent.com/101855553/164608633-bca726c9-12fe-4d64-8149-33fdc7023f00.gif)

New Dance (300 frames)
![Parrot Dance 3 L](https://user-images.githubusercontent.com/101855553/164608767-8720007a-6991-4174-9256-39675fc54be6.gif) ![Parrot Dance 3](https://user-images.githubusercontent.com/101855553/164608778-f3db8ad8-c1d4-451e-985b-74c0ef12c58b.gif)

**Blue Jay**
![Blue Jay Idle New Revision L](https://user-images.githubusercontent.com/101855553/164959129-5acf9c4a-4dde-4d63-a138-a2358dfed0f5.gif) ![Blue Jay Dance Revision L](https://user-images.githubusercontent.com/101855553/164959235-7931d704-b1f5-4e3b-9428-1844647872bb.gif)

![Blue Jay Idle New Revision](https://user-images.githubusercontent.com/101855553/164959130-ff116079-f6e6-4c74-8797-99ec29c25092.gif) ![Blue Jay Dance Revision](https://user-images.githubusercontent.com/101855553/164959261-9e0530d2-3564-4e9f-81d2-482f61fa3b90.gif)

**American Woodcock**
![American Woodcock Idle New Revision L](https://user-images.githubusercontent.com/101855553/164959449-ee0d4719-bcfc-41fa-91c0-5f45aaef9e4c.gif) ![American Woodcock Dance New Revision L](https://user-images.githubusercontent.com/101855553/164959453-176b25e8-6698-4831-90b4-b7b342e8f3a2.gif)

![American Woodcock Idle New Revision](https://user-images.githubusercontent.com/101855553/164959460-5532e48e-004c-4b1d-898c-f01de6740443.gif) ![American Woodcock Dance New Revision](https://user-images.githubusercontent.com/101855553/164959462-3e9af415-8567-44ca-b536-840534537775.gif)

---
### **Last Notes**

If anyone would like to suggest new prices, please do! Pricing stuff is not my forte so any advice and suggestion is appreciated.

ALSO! I currently have another ongoing proposal that involves adding Axolotls into the game! Although not required, if you'd like to submit your own Axolotl design please do check out here: https://github.com/sunflower-land/sunflower-land/issues/456

Animations are already done, so you just have to design your own and paste it over the animation! Thanks everyone for reading!

**Comment by SrCouve** [comment]
The birds were amazing, what a beautiful work bro

**Comment by adamhannigan** [comment]
@Netherzapdos More amazing work. I actually missed this initial proposal! ❤️ 

To remain consistent with the game, I would suggest that the slower animations that move less would fit.

I am in love with the parrot! Let's add this in the game. Any devs want to sneak this on the map somewhere?

**Comment by Netherzapdos** [comment]
Hey @adamhannigan , actually just came back to this proposal as well a few days ago to rework the colors 😆 , but will definitely adjust the dances too 👍

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
