### ISSUE TITLE
[BUG] Continuous recharge has not been credited to the account

### ISSUE THREAD

**Issue by berry226** [sunflower-land/sunflower-land#4864]
## Summary of Bug

Continuous recharge has not been credited to the account

## Steps to Reproduce

Provide detailed step-by-step instructions for how this bug can be reproduced.

1. TODO

## Expected Behavior

Provide a description of what you expected to happen.

## Actual Behavior

Provide a description of what actually happened.

## Screenshots

**Device Information (please complete the following information):**

- Device: [e.g. iPhone6, Pixel 6a]
- OS: [e.g. iOS, Linux, Windows, Android]
- Browser/App [e.g. firefox, safari, chrome, metamask mobile]
![Screenshot_2024-12-04-16-34-17-85](https://github.com/user-attachments/assets/a1060432-e2cc-4005-8d1a-87a41821602d)
![Screenshot_2024-12-04-16-34-03-74_1a01c1dfc8c0ea31a9d50a905953499e](https://github.com/user-attachments/assets/68d8a7fe-b0fe-4d86-b71d-87b63d2edd78)
![Screenshot_2024-12-04-16-33-59-68_1a01c1dfc8c0ea31a9d50a905953499e](https://github.com/user-attachments/assets/6d2649db-6571-4982-9325-8036f2f39db0)
![Screenshot_2024-12-04-15-34-53-25_1a01c1dfc8c0ea31a9d50a905953499e](https://github.com/user-attachments/assets/f1ed7d90-a13c-467c-8768-b3100ebe3ce1)
![Screenshot_2024-12-04-16-34-33-25_1a01c1dfc8c0ea31a9d50a905953499e](https://github.com/user-attachments/assets/e53a2b4c-cfdf-4a4c-ac86-49e325ae143a)

**Comment by berry226** [comment]
After completing the recharge in the upper right corner of the game, I was forced to make a small refund by the game. Then, when I recharged again, I was forced to refund again, and the fees were deducted twice, but they were not credited to my account.

**Comment by Dionis404** [comment]
Do a "Refresh from Chain" and check again
![image](https://github.com/user-attachments/assets/79e2a7ac-e79c-45ea-8182-b2d12045e28b)

**Comment by berry226** [comment]
> Do a "Refresh from Chain" and check again ![image](https://private-user-images.githubusercontent.com/133494217/392335835-79e2a7ac-e79c-45ea-8182-b2d12045e28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTcyNTQsIm5iZiI6MTczMzM1Njk1NCwicGF0aCI6Ii8xMzM0OTQyMTcvMzkyMzM1ODM1LTc5ZTJhN2FjLWU3OWMtNDVlYS04MTgyLWIyZDEyMDQ1ZTI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwMDAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTZlOWIxMWI1YjNjZWY4ZWJjMjBmMjFjMjRjMjcyYTE1ZjJkMmY4NTE1NjU4NDA1OTFjMTRmMzFkMzY1ZTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GbiwWlPEJ-WPXNNf0RRjwcL3LUUyW3rHvW_uus2eNL8)

Thank you for your guidance, both recharges have been credited to the account.
