### ISSUE TITLE
[ART/PROPOSAL] Seed Stock Increase NFT Silo

### ISSUE THREAD

**Issue by WeHawt01** [sunflower-land/sunflower-land#489]
Hello everyone! This is my first Art Proposal 

I hope you will like this. 

So this is a NFT that will help combat halvings and increase productivity for each sync.

![Improved Silo](https://user-images.githubusercontent.com/96753610/161990299-babfa16d-0148-4628-9db2-e3ef96a50ad5.png)

![Improved Silo small](https://user-images.githubusercontent.com/96753610/161990322-42fb9af2-c38d-4019-93fe-52c81d67682b.png)

![Improved Silo (2)](https://user-images.githubusercontent.com/96753610/161990349-965f14a6-cc68-4355-9d1a-bec0ca8aebcd.png)

**Pricing**

I had a different approach on how to craft this item compared to other crafts. It would consist of paying the whole stock of plants equivalent to 1 sync. The plants harvested of course. 

-400 Sunflower seeds 0.001 x 400= 0.4
-200 Potato seeds 0.01 x 200= 2
-100 Pumpkin seeds 0.02 x 100= 2
-100 Carrot seeds 0.05 x 100= 5
-90 Cabbage seeds 0.1 x 90= 9
-80 Beetroot seeds 0.2 x 80= 16
-80 Cauliflower seeds 0.3 x 80= 24
-40 Parsnip seeds 0.5 x 40= 20
-40 Radish seeds 0.7 x 40= 28
-40 Wheat seeds 0.5 x 40= 20

A total cost of 126.4 SFL might not be much but a lot of time is needed.
And all these plants fully harvested will be needed to purchase the silo.
I really liked this unique way of craft recipe.
It is up to you guys either to make it more expensive or tweak the recipe. 
The only problem i see maybe is the display of all the crops for the craft in the shop.

---------------------------------------------------------------------------------------------------------------------------------------------------

**NFT**

This NFT will have a 100% increase in seed stock and a 25% plant sale price increase.
So instead of having 400 Sunflower seeds you will now have 800 Sunflower seeds.

limit: 5000

I have thought about 3 different sizes. And I chose the medium one which for me looked the best.  The colour palette from the wooden silo is completely inspired from the in game House.

![Capture d’écran 2022-04-06 153212](https://user-images.githubusercontent.com/96753610/161986589-03dc7715-0b94-465d-9865-c2910febb9d9.png)

The silo will be a Tier 2 NFT Crop Boost. But could also be the only one 
I was thinking, if this idea is interesting for devs to implement into the game a Tier 1 Sack bag, and as a Tier 3 a Warehouse.
The numbers are all up to you guys of course. I am no expert. If u have any questions please let me know. :)

Thanks for Reading !

Farm:
297
Wallet:
0x2Bf34815C127580Fdb3B04bcf6938A50AFAD1b36

**Comment by Riccus** [comment]
Looks good. Seems to be a useful NFT🌻

**Comment by adamhannigan** [comment]
@WeHawt01 Adding some feedback from earlier.

This makes a lot of sense to me 👌 I'm not sure exactly what it is, but it still looks a bit inconsistent with the other building.

We don't actually have any round objects in Sunflower Land yet so you are setting the precedent 💪 

Do you think we could design this more with a rectangular shape?

**Comment by WeHawt01** [comment]
> @WeHawt01 Adding some feedback from earlier.
> 
> This makes a lot of sense to me 👌 I'm not sure exactly what it is, but it still looks a bit inconsistent with the other building.
> 
> We don't actually have any round objects in Sunflower Land yet so you are setting the precedent 💪
> 
> Do you think we could design this more with a rectangular shape?

Hey Adam, so this was my attempt of making a silo which real life farmers use to stock grains, pasture etc... I was aiming to do a fat one which I will show an image of because that was what I was recommended in the discord art channel. 
![20-943_Social-Media-Graphic-Grain-Bins_highres-350x350](https://user-images.githubusercontent.com/96753610/164168510-b0d3b0e2-f0b0-49a6-bdaa-c5309b7a78cc.jpg)

![metal_silo-1](https://user-images.githubusercontent.com/96753610/164169164-af7a39ec-32a5-498c-806a-78d067272af4.jpg)

So that's what I was aiming for. I will try and see on making it more consistent with the game design and more rectangular ☺️!

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
