### ISSUE TITLE
[ART/PROPOSAL]Potato Buff Special Skin

### ISSUE THREAD

**Issue by WeHawt01** [sunflower-land/sunflower-land#493]
Hey Everyone again :)

I wanted to create a special version of the potato.
I saw that you are wanting to give a buff and purpose to the Potato statue as well as the sunflower statue. So having the potato statue will take effect on the looks of potatoes in game too! This would be a cool addition, where small details make the whole difference.

So this is what it would look like as a potato that has been planted.

![Capture d’écran 2022-04-06 200913](https://user-images.githubusercontent.com/96753610/162043642-473150e8-614b-4c8c-a01f-3e564714aeeb.png)

![plant golden small](https://user-images.githubusercontent.com/96753610/162046339-ced60a0c-4501-4e5b-909f-0929edbae2a7.png)

![plant golden bigl](https://user-images.githubusercontent.com/96753610/162046349-3d9fb188-854b-4135-9672-d39292426bd9.png)

We can even distinguish a small smiley face in that potato :)

I even made a gold look of it when u will be selling them from the shop and when it's in your inventory. 

![crop golden small](https://user-images.githubusercontent.com/96753610/162046384-313c1d7a-43b0-4a82-9e57-4faaa3eccdbb.png)

![crop golden bigl](https://user-images.githubusercontent.com/96753610/162046459-e4336ddf-01bb-4161-9fad-79323a5d3c22.png)

I am wanting to work on making a night theme of the game when it is night in your respective country.
And these potatoes will be glowing making them look even more cooler hehe.

Thanks for Reading !

Farm:
297
Wallet:
0x2Bf34815C127580Fdb3B04bcf6938A50AFAD1b36

**Comment by Riccus** [comment]
Good idea 🌻

**Comment by JacobSobolev** [comment]
I have an addiction to this idea.
the current potato statue is a T1 potato statue.
maybe also change the T1 potato statue requirement to 1K potatoes.
there will be a T2 potato statue, the same design but with a golden potato on top of it:
The cost:
50 stones
20 gold
T1 potato statue

the effect will be 1.25x the rewards from potatoes crops 
and the plants you plant golden potatoes like @WeHawt01 showed in the design.

**Comment by adamhannigan** [comment]
Great proposal! Can I suggest that we move this into mutant crops proposal?

We won't have the bandwidth to add custom crops like this in the short term but we will be able to include it as a mutant crop. 

#507
