### ISSUE TITLE
[ART/PROPOSAL] Mining Mole

### ISSUE THREAD

**Issue by Telknub** [sunflower-land/sunflower-land#494]
This is a proposal for a season 2 NFT that would work in a similar way to the beaver.

Early in January I sent a small idea on artists chat of a new kind of animal NPC:
![image](https://user-images.githubusercontent.com/38796969/162051196-fbde7dc9-ab05-41ce-a497-409fab44187e.png)

Then with the recent addition of the beaver I remembered that I had this mole design and made a few tweaks and additions to it, making it 3 tiers like the beaver and scarecrow.

The inspiration for it is the Star-nosed mole.
  
  
Tier 1 (a mole without anything):
![toperatier1big](https://user-images.githubusercontent.com/38796969/162051533-5e603649-6cc2-4713-bb8e-97a29e3e6603.png)
![toperatier1](https://user-images.githubusercontent.com/38796969/162051538-d0f9593b-dea0-4f30-9fe2-5e53ffdd777b.png)

Tier 2 (a mole with a mining helmet) :

![toperatier2big](https://user-images.githubusercontent.com/38796969/162053435-480f041a-9d52-486c-96bd-7f14090954f0.png)
![toperatier2](https://user-images.githubusercontent.com/38796969/162053453-ee15ada6-dbc5-490d-bd2f-f2eac57f5cc4.png)

Tier 3 (a mole with a helmet and a shovel):

![toperatier3big](https://user-images.githubusercontent.com/38796969/162053488-ac71b86a-b526-432c-949e-db80c45feb59.png)
![toperatier3](https://user-images.githubusercontent.com/38796969/162053499-28a8a2d0-e2f8-4370-afa3-7f86b90d9892.png)

My idea is that they would work in a similar way to the beaver but for stones as their resource.

If anyone has ideas for names for each of them  or any kind of feedback please send your suggestion and thanks for reading this proposal!

**Comment by ElcomJ** [comment]
This really is an NFT that I would love to have on my farm, I loved it completely.
That's what I call pixel art well done, congratulations to the creator.

**Comment by wendin017** [comment]
imagine if you need this mole to get into the mine.

**Comment by Armadi11o** [comment]
Imagine if it would be another animal. Maybe an armadillo? xD (i'm joking this one already is great!!)

**Comment by adamhannigan** [comment]
Very cute! @Telknub 

I wonder if we could get an animation of the mole poking it's head in and out

**Comment by Telknub** [comment]
> Very cute! @Telknub
> 
> I wonder if we could get an animation of the mole poking it's head in and out

I'll try to make it tomorrow!

**Comment by Telknub** [comment]
@adamhannigan 
Hi Adam! I am sorry that I could not make these yesterday, but here they are. I separated the animations because I think you can program them to play as you would like, but if you want I can make just a big loop with a long part of the middle being the idle animation repeating itself.

I don't know if the expressions used below (ascending/descending) are right but I think you can understand it (lol).


Tier 3 animations:

Idle Animation:
![MoleIdle](https://user-images.githubusercontent.com/38796969/164510152-a3225e69-a05b-4137-a194-0b58efcfb164.gif)
![MoleIdle8x](https://user-images.githubusercontent.com/38796969/164510153-c607f632-4e57-4c8f-a7ad-d3d6d7638f54.gif)

Ascending Animation:
![MoleAscending](https://user-images.githubusercontent.com/38796969/164510155-c71643ed-a67f-4ef1-b049-c88763a95aec.gif)
![MoleAscending8x](https://user-images.githubusercontent.com/38796969/164510159-1e7e2e74-39e6-4990-8840-7c214e080f98.gif)

Descending Animation:
![MoleDescending](https://user-images.githubusercontent.com/38796969/164510160-e05b306c-9914-4ec3-a91e-d0c7bbf5f2c1.gif)
![MoleDescending8x](https://user-images.githubusercontent.com/38796969/164510162-e3ce0a55-7fbd-4369-84b5-3e34f0cf0325.gif)

Tier 2 Animations:

Idle:
![Mole2Idle](https://user-images.githubusercontent.com/38796969/164510933-4f1e9758-321c-4fd5-a748-816c20c0dccd.gif)

Ascending:
![Mole2Ascending](https://user-images.githubusercontent.com/38796969/164510978-880ee93f-90f0-4e93-b36b-9b9938a321a2.gif)

Descending:
![Mole2Descending](https://user-images.githubusercontent.com/38796969/164510995-fd6439f5-845d-4d6a-b004-19f5b78bbe93.gif)

Tier 1 Animations:

Idle:
![Mole1Idle](https://user-images.githubusercontent.com/38796969/164511259-edf14d57-e1f0-44b9-9ac6-31e94a48d5ab.gif)

Ascending:
![Mole1Ascending](https://user-images.githubusercontent.com/38796969/164511291-b2c395b1-0a3a-47dd-b973-09a30465d9ea.gif)

Descending:
![Mole1Descending](https://user-images.githubusercontent.com/38796969/164511308-19f27079-18f5-4e1d-9a43-d0314228ff99.gif)

**Comment by adamhannigan** [comment]
@Telknub Love it!

Could you please post it here as well 😏 We have a few mineral based ideas we want to organise together

https://github.com/sunflower-land/sunflower-land/issues/734
