### ISSUE TITLE
[ART/PROPOSAL] Night Theme Farm (whole new vibe!)    :)

### ISSUE THREAD

**Issue by WeHawt01** [sunflower-land/sunflower-land#497]
Sup Everyone !

I got inspired by some games where when it is night the whole game changes aspects energy and vibes.
So I am proposing having a night theme included into the game. And depending if its night time in your country the game will have a night theme. 

I made a small preview of what it would look like.

![Night mode ](https://user-images.githubusercontent.com/96753610/162444880-51bd937f-cd19-4711-a88f-c65553ce1802.png)

![Night Lilly](https://user-images.githubusercontent.com/96753610/162799589-76c564cd-b6c0-475d-87e9-5eac52076c80.png)

I made it a small preview because it would have been to long to make the whole map.
If the game developers would like it added to the game let me know and ill get to work with the full map. 

This is a direct comparison to more easily distinguish the differences.

![Night day](https://user-images.githubusercontent.com/96753610/162444912-a360345c-ac14-49bb-9741-afca97c8269c.png)

- I had thought about mechanics that could be implemented with this night theme. I made rats designs and we could have rats roaming around plants, bats etc... Have goblins roam around town like walking on their tippy toe hehehe.
- Have plants grow slower during night time just like in real life. Making it maybe 10% slower to make it fair. 
- Have a chance of loosing crops during the night because of nocturnal animals eating them. Like let's say 5% chance of loosing a crop.

Opens a whole new category of nft's to exist like bonfires which illuminate during the night. Be able to buy lamp posts as deco within your village to make light during the night. The possibilities can be endless.

And that is everything I had thought about for the night theme addition. 

I hope this feature get implemented into the game as it would be very cool.

Thanks for Reading !

Farm:
297
Wallet:
0x2Bf34815C127580Fdb3B04bcf6938A50AFAD1b36

**Comment by Netherzapdos** [comment]
Great initiative on making a night map :) The night time cycle has definitely been thought of before but I think has been put on the side for now, but it's actually good to see a potential example of what it may look like in the future. 

I had the same idea as well of introducing new mechanics, I'm actually designing axolotls for the game (#456 ) and have made several axolotl species that only spawn during night, so definitely a lot of possibilities here! 

I like the idea of losing crops at night, a passive 5% chance per planted crop might be an okay % chance. Additionally, a new craftable NFT can be introduced that reduces this chance or removes it entirely, maybe a new type of scarecrow? For the slower growth time, might be a bit biased but I like to see my caulis already grown right when I wake up 😂 

Another addition is probably adding things on the map after night. Like piles of leaves, broken wagons, weeds, etc. I believe farmville had a mechanic like this before, just lets you "clean" the farm up after night time and gives bonus resources as well.

Lastly, the night art looks good, personally I think you got the right color for the landscape. Some lighting adjustments could probably be worked on to further emphasize that night feel by emphasizing where sources of lights are.

**Comment by Pranav-yadav** [comment]
Great Initiative 🎉 
This is the way to go.

It's even easy to introduce this in game using Local Time of the player's device and toggling the Day/Night mode.

I'm sure Adam and team will like this and will start planning this, *after the game gets stable launch*.

**Comment by rickfurt** [comment]
Omg, we could totally implement this, changing dynamically using the browser's time or in short day/night cycles.

but this would require the whole map assets.

Btw I can give a try implementing if I have all or  some assets for a prototype.

**Comment by adamhannigan** [comment]
This looks beautiful! ❤️ 

I guess the main concern with adding a night mode is that we would need twice the amount of assets. When we add a new feature, we also need to add support for night mode (which would make upcoming features more work as well).

Until we have a technical solution that makes this seamless, it may actually slow down development on the project 😢

**Comment by brian-man** [comment]
@adamhannigan Perhaps I'm being naive on the visual effect, but can't we just put a filter over the entire page to introduce night? No new art assets required.
