### ISSUE TITLE
可以出偷菜系统啊，有竞争性 出偷菜系统我们东八区的人民就会氪金

### ISSUE THREAD

**Issue by dayanghhh** [sunflower-land/sunflower-land#501]
出一个 偷菜系统，半夜三更我就起床去偷别人的菜，如果别人想偷我的菜 我就升级装备 可以制作防偷菜的NFT 也可以制作偷菜的NFT，，，这样更有竞争性 ，然后还可以 在偷别人菜地 留一个社交熟悉的文字，比如我到此一游，，对方可以追查到谁偷了自己的菜需要NFT  一般情况下没有查看偷菜NFT的 看不到是谁偷了自己的菜

**Comment by Rofrtd** [comment]
Hey @dayanghhh could you please translate that?
