### ISSUE TITLE
[PROPOSAL] Liquidate V1 Farms That Aren't Going To Be Used - Multi Accounts From V1

### ISSUE THREAD

**Issue by JacobSobolev** [sunflower-land/sunflower-land#504]
**Issue:**
People have created and upgraded farms on V1 a lot more than is going to be used in the current version.
People are afraid of losing their investments from V1 but at the same time want to play by the rules and don't want to mint a huge amount of farms and list them on Open sea and possibly get blocked as well.

**Proposal:**
give people a week or so to liquidate the worth (SFF, Farm Level, Crops that aren't harvested) of their farms from V1 to SFL tokens and send it to their farm of choice.
In the process, the farms from V1 will be burned.

we can assume those farms will not have any NFTs as the main purpose of those farms was just to plant and harvest.
But it should be mentioned that they will be burned to give the opportunity to keep only the important farms when multi accounts will be permitted.
I think it will make things easier to implement this way (without the hustle of migrating NFTs or checking for them)

**A way to do it**
I think this can be done off-chain.
In the main menu, before connecting to the farm create another button "Liquidate V1 farm"
once the player clicks the button he will need to connect with that account he wants to liquidate.
In the next menu, it will be displayed the amount of SFF the current farm is worth and an additional field to enter the farm address or ID he/she wishes to send that SFL to.
after confirmation, the farm will be burned and the SFL will be sent to that farm.

**Comment by mecsafonso** [comment]
Good idea, people need to be able to burn v1-farms

**Comment by adamhannigan** [comment]
@JacobSobolev This is in-line with what the team is thinking.

We are speccing out some functionality to merge multiple farms (V1 or V2) into a single farm. More details to come 😄

**Comment by JacobSobolev** [comment]
@adamhannigan great! so I think we can close the issue.
