### ISSUE TITLE
NFT Migration 

### ISSUE THREAD

**Issue by samadi307** [sunflower-land/sunflower-land#506]
Hello,

I made three purchases of Nft's with the address  wallet:  0x596C92C82e1AeAb3a2CC66294df4A822a6DC32a3 on 04/01/2022, then for safety I transferred two NFT's to another wallet 0x103d5f1C7A474C579e58AC534634AD28E79256Ff on 05/01/2022.

 All this was done before the closing date of Sunflower 07/01/2022. When sunflower restarted I noticed that my Nft's were not changed.

So I tried to explain all this to two moderators in the sunflower discord server, NIGHT#2858  and Lucifer-死神#7177, they told me that I have to wait!

Now I'm reaching out to you. What should I do in this case?

PS:
Wallet 1: 0x596C92C82e1AeAb3a2CC66294df4A822a6DC32a3
https://opensea.io/assets/matic/0x938a6942bd09cfac1bc4b2420f581a90fb5d5775/718
Wallet 2: 0x103d5f1C7A474C579e58AC534634AD28E79256Ff
https://opensea.io/assets/matic/0x143ba32499065b5f89c518d5b75a38f3529ce324/822
https://opensea.io/assets/matic/0x143ba32499065b5f89c518d5b75a38f3529ce324/486

Thank you in advance.
Naoui

**Comment by tidalnft** [comment]
Hello. This github is only for development related proposals, discussions and updates. For account related inquiries, please create a ticket through our discord. Thank you.
