### ISSUE TITLE
[ART] Mutant Crops

### ISSUE THREAD

**Issue by AKCH1N** [sunflower-land/sunflower-land#507]
# MUTANT CROPS
*These are my sweet little **_mutant crops_**, hope you like it!*

## Version 1
![Mutant Crops](https://user-images.githubusercontent.com/44812103/162585767-55a68150-db6d-4d31-9998-49922da68fb5.png)
![Mutant Crops 1](https://user-images.githubusercontent.com/44812103/162585766-18bae294-1e78-4dd4-b2d7-6d6d78492201.png)

## Version 2 (Added new mutant crops & Edited the old ones)
![unknown](https://user-images.githubusercontent.com/44812103/162695307-e2872587-ca1a-4acc-b8cf-26838bf04d41.png)
![unknown (1)](https://user-images.githubusercontent.com/44812103/162695314-50749582-6764-4701-ad35-f417658996c5.png)
![unknown (3)](https://user-images.githubusercontent.com/44812103/162695491-973a9777-abfd-4cf0-b49b-d5216d3bc5f9.png)
![unknown (2)](https://user-images.githubusercontent.com/44812103/162695499-9b97e94a-60f9-4f17-94ab-d91ef2b1bd2d.png)

`0xfB33c8f8426Db534C0BA6494D4B9e824B390d658`

**Comment by adamhannigan** [comment]
@AKCH1N These are incredible. I love it!

**Comment by adamhannigan** [comment]
Continued here: https://github.com/sunflower-land/sunflower-land/issues/555
