### ISSUE TITLE
[ART] straw hat monument

### ISSUE THREAD

**Issue by PedroAugusto-BCS** [sunflower-land/sunflower-land#508]
![hat](https://user-images.githubusercontent.com/67617098/162594607-98968456-00ec-48cf-9381-ac82ac7a4b8f.png)

![hat (2)](https://user-images.githubusercontent.com/67617098/162594608-daae38f9-d5f6-4efb-8d89-0ac0c2e895d5.png)

![d](https://user-images.githubusercontent.com/67617098/162594611-769350a6-0bc0-4548-80a5-e9242acc2e5e.png)

a monument with a hat worn by farmers and pirates, seems to have a message in an ancient language 

Farm: 8344

Wallet: 0xe20e153526380752A02DCdbdA0dB01e6666fb940

Discord: pedro3797#7776

**Comment by adamhannigan** [comment]
Hey Pedro, great idea! The best place to get community feedback on these is usually during the competitions we do - see #524
