### ISSUE TITLE
"Transaction expected to fail" error in Metamask due to Frontend not updating after successful transaction and users retrying the action

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#51]
Raising an issue here for tracking. Will observe concerns from discord and will update if there are other causes.

Sample videos:
- https://youtu.be/BiuLAuLagf0
- https://youtu.be/k-_e04Z8blQ

Steps done:
1. Chop wood
2. Submit transaction - Successful transaction BUT app didnt update visuals
4. ~~Click anywhere~~Wait for ~20 secs and chopping animation disappeared
5. Retry chop wood - Transaction is expected to fail error

Root Cause: TBD or intermittent
Possible causes:
- state not transitioning
- isolated on refactored `stake()` code

Notes:
- app is active tab/window
- might not be the sole reason for tx expected to fail error msg
- also happened when mining gold (different session, refreshed and all)

**Comment by ethernetweb** [comment]
I'm looking into this error. Working with TheRoulette to resolve it as well.

**Comment by Adebillions** [comment]
Gas price issue need to be fixed

**Comment by drharryx** [comment]
¡

> Gas price issue need to be fixed

yes, please is real problem.

**Comment by j923sneaks** [comment]
will close the issue for now due to SFL v2. will reopen/new issue if still happening.
