### ISSUE TITLE
Puerto Rican Flag!   Let's get 10 likes..

### ISSUE THREAD

**Issue by riius** [sunflower-land/sunflower-land#513]
It would be an honor for me and many native Puerto ricans to represent their beautiful island, so for that I created a GIF FLAG... Hopefully it makes it into the game :)

![PR_flag](https://user-images.githubusercontent.com/23530366/162630124-1dceb737-5af0-42c0-b85f-1e6f29f36e49.gif)

**Comment by adamhannigan** [comment]
Awesome work @riius 

Can you move this into the #422 Flag requests. It helps us track these ideas 🤗
