### ISSUE TITLE
[ART/PROPOSAL] mutant/shiny crops + Show it off 

### ISSUE THREAD

**Issue by WeHawt01** [sunflower-land/sunflower-land#514]
Hey guys, 

This is a continuation of other mutant crops proposal this includes art from the #412 proposal.
Credit to SteveChickenCX for some plant designs shown in the screenshot.

I made a spot and a special pot for these special mutant crops. So when we will acquire the rare plant we will be able to put on these special pots here.

![Capture d’écran 2022-04-10 195557](https://user-images.githubusercontent.com/96753610/162633115-95fc3821-6ca5-415b-ab56-0daeb2607bbd.png)

![Crop Big pot ](https://user-images.githubusercontent.com/96753610/162633125-430bc8ff-1fa9-48f6-afb4-e5af3d152d49.png)
![Crop Big pot B ](https://user-images.githubusercontent.com/96753610/162633129-afaad28b-1749-402d-82ae-32aca2367c80.png)

I also made the whole collection of all 10 mutant crops.

![Small Sunflower Mutant](https://user-images.githubusercontent.com/96753610/162800500-cc27ef5e-6219-437c-8f01-0ae8c17d5b5c.png)

![Big Sunflower Mutant](https://user-images.githubusercontent.com/96753610/162800530-7dac9fb1-8810-4ca2-b58d-ac04ace85315.png)

![Small Parsnip Mutant](https://user-images.githubusercontent.com/96753610/162800900-4c4c6ec1-a78f-4c1b-a971-0c358d090806.png)

![Big Parsnip Mutant](https://user-images.githubusercontent.com/96753610/162800922-e14d58b3-b9ad-4aeb-8fb9-2b0ae98c299d.png)

![Small Radish Mutant](https://user-images.githubusercontent.com/96753610/162801125-0d570811-5de6-4fbc-9001-64bc17158624.png)

![Big Radish Mutant](https://user-images.githubusercontent.com/96753610/162801143-78408661-348c-4de5-9cba-f7a244be1623.png)

![Small Cauli Mutant](https://user-images.githubusercontent.com/96753610/162801412-f1b80ca3-1ac0-4d91-8cf4-a69fa09b711b.png)

![Big Cauli Mutant](https://user-images.githubusercontent.com/96753610/162801435-14833bef-3d9a-442a-a7c6-87c846650954.png)

![Small Beetroot Mutant](https://user-images.githubusercontent.com/96753610/162801707-2ce67c9a-a4fc-4850-a453-e4d225b670e8.png)

![Big Beetroot Mutant](https://user-images.githubusercontent.com/96753610/162801737-b3bf824b-bb85-40aa-9961-9df86bc78c6f.png)

![Small Wheat Mutant](https://user-images.githubusercontent.com/96753610/162801936-5afbfab4-f4c2-46d4-9094-8b861d89c590.png)

![Big Wheat Mutant](https://user-images.githubusercontent.com/96753610/162801959-bb5b884c-934b-4c23-8a00-bf54f7d9b95d.png)

This would be a cool addition showing off your extremely rare plant.

The mutant plants will not resell for more it is just a pure decoration like in Pokemon your goal is to collect them all even tho they have no real advantage. It is a just collection. And in this case you need to collect 10 of them.
The mutant plants will be extremely like in the old Pokemon games where the odds are around 0.01 %

If you have better or other plant designs feel free to add some more here.

Thanks for Reading !

Farm:
297
Wallet:
0x2Bf34815C127580Fdb3B04bcf6938A50AFAD1b36

**Comment by adamhannigan** [comment]
Continued here: https://github.com/sunflower-land/sunflower-land/issues/555
