### ISSUE TITLE
Ip question

### ISSUE THREAD

**Issue by Gale00** [sunflower-land/sunflower-land#520]
1、My girlfriend and I use the same wifi, Is that gonna be a problem？
2、and Chinese people need to use Vpn to sync on chain，so we may have two different IP or more。I hope you can know this，because most of us have to use Vpn。

**Comment by tidalnft** [comment]
Hello. This github is only for development related proposals, discussions and updates. For account related inquiries, please create a ticket through our discord. Thank you.
