### ISSUE TITLE
[ART] armor for goblin war

### ISSUE THREAD

**Issue by PedroAugusto-BCS** [sunflower-land/sunflower-land#521]
![golbin](https://user-images.githubusercontent.com/67617098/162767420-3c0bc9dd-ecb9-411d-8f03-0580a32b23eb.png)
![kgoblin](https://user-images.githubusercontent.com/67617098/162767432-156de9a2-4813-4416-98b6-c1238f1dbc6c.png)
![goblin](https://user-images.githubusercontent.com/67617098/162767673-e1fd5865-1d34-4dd2-bcbc-0dcf6e2d3d87.png)
![kgoblin10](https://user-images.githubusercontent.com/67617098/162767682-8d404b35-f04e-4cc8-badc-bb575a20dca4.png)
![villager](https://user-images.githubusercontent.com/67617098/162767872-5a8979f3-424d-4ded-a795-a9436bfe7d72.png)
![kvillager](https://user-images.githubusercontent.com/67617098/162767887-6993be0a-2c97-4af7-8c90-9323d2ea9281.png)
![villager](https://user-images.githubusercontent.com/67617098/162768061-1125b87d-d309-414a-bae8-94d0c486c11c.png)
![kvillager10](https://user-images.githubusercontent.com/67617098/162768070-4fa48be0-57a6-4b00-aa60-035cf943cdb9.png)

Farm: 8344

Wallet: 0xe20e153526380752A02DCdbdA0dB01e6666fb940

Discord: pedro3797#7776

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
