### ISSUE TITLE
Add new functionality to the sunflower statue

### ISSUE THREAD

**Issue by Kratka007** [sunflower-land/sunflower-land#522]
Greetings
I would like to propose that players who own the sunflower statue (the one with the HODL inscription on the base) can also receive the hodl tag on discord
This would make this NFT more attractive, considering that today it is only decorative and with the date of the creation of NFT's approaching, this would generate more interest in the community.

**Comment by adamhannigan** [comment]
@Kratka007 We have got some Discord/Web3 integrations on the roadmap. Ideally we want everyone to represent what they have on their farms.

Closing for now as we are currently blocked by the technical implementation
