### ISSUE TITLE
[Bug] Cannot use the app without full screen.

### ISSUE THREAD

**Issue by aayusharyan** [sunflower-land/sunflower-land#532]
I have a multi monitor setup with each monitor of 4K resolution and I generally never make any window full screen and this game I used to play regularly as any other browser window but recently today I cannot use it as a regular window. I need to make it full screen in order to play. This is not a good user experience as the game is not optimized for large screens.

While I do understand that this is for the anti bot mechanism. I would rather suggest to use the visibility API instead of the window size thing.

Looking for views on this. If you can refer to the correct part of code where this thing is happening, I can make a PR for this.

**Comment by aayusharyan** [comment]
Evidence.
![image](https://user-images.githubusercontent.com/16634228/162908130-e4d7125c-ae91-43d3-a030-a76450bd6cf9.png)

**Comment by DenisBardak** [comment]
on macos doesn't work in full screen even when it's open

**Comment by samadi307** [comment]
My browser is full screen but I Have the same issue

**Comment by jcads** [comment]
> If you can refer to the correct part of code where this thing is happening, I can make a PR for this.

https://github.com/sunflower-land/sunflower-land/blob/8caab48241dc2b1f612183d58471e70486a16777/src/features/auth/lib/authMachine.ts#L143-L144

**Comment by akshay-kh** [comment]
> Apparently not a bug, I get the point of monitoring screen size to fight against bots/multi acc, but having to use F11 on Firefox is going a bit too far IMO, I can't even log out of the game before being disconnected.

true this is very annoying to someone who is not bot 😅

**Comment by Pranav-yadav** [comment]
See, there is a bug 💯 , just checked.
*Will* try at my side to fix it.

**Comment by lovrain1007** [comment]
Full screen is too anti-human, I have to work, I can not always full screen
