### ISSUE TITLE
[PROPOSAL] Dog/Cat upgrade NFT And Fishing Store ideas 

### ISSUE THREAD

**Issue by Killu8726** [sunflower-land/sunflower-land#536]
DOG'S HOUSE
	>>Following the same logic as the scarecrows update, the dog house
	could "merge" with the dog, like a craft where you need the
	house and the dog, thus forming a new item,
	so the buff would improve, for example:
		>>Dog speeds up the production of things from sheep
		by 4x, but with the house it would increase the amount by 20%, just 
		like scarecrow works.

CAT LITTER BOX
	>>Working in the same way, the cat would merge with the house to
	craft an improved version of Victoria.

FISH TROPHIES
	>>Fish trophies can be crafted in the Fishing Shop (described below),
	and can be made with a few different types of fish, and can be crafted
	in a little store that can be close to the water, in this case it would be a suggestion
	construction also:
	>>FISHING STORE:
	There you can buy:
	>Baits to improve the chance of catching the fish
	>Sell the fish for a certain amount of SFL
	>Craft Fish Trophies, which would serve to give buffs for fishing
	somehow, from cooldown or increasing the chances
	get a rare fish, etc, make "Tiers" of the Fish Trophy
	(the rarer the fish used to make the trophy, the bigger the buff)
	EXAMPLE:
	>>First fish trophie recipe: 10 trouts, 20wood, 5 SFL
	>>Second fish trophie recipe: first fish trophie, 50 of a rare fish, 50 stone, 50 SFL
	>>Third fish trophie recipe: second fish trophie, that big shark swimming over (maybe), 200 SFL and 50 gold

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
