### ISSUE TITLE
[PROPOSAL] Seed/Crop Removal

### ISSUE THREAD

**Issue by jcmonnett** [sunflower-land/sunflower-land#537]
_This has been brought up a few times and I am hoping to provide a solution that can be implemented._ 

Currently if you are trying to remove plants, if you have leftover seeds you might accidentally plant a new crop. This is extremely bad on mobile because unless you are really zoomed in you may click on an empty plot instead of the crop you are trying to pull. 

**Here are a few ideas for what I am suggesting:**

- Craft a shovel that can be used to remove a single crop/seed.
- Allow removal of the crop/seed if it is within 1 minute of planting at no cost or at cost.
- Allow removal of the crop/seed if player pays 50% of the cost of seed/crop at any time. (Maybe through burning feature?)

There definitely should be repercussions to planting a crop and then removing it during its grow time. Maybe this cost increases the longer it is planted. If a plant is 75% completed, the cost to remove should be 75% the cost of the seed/crop. 

Planting a cauliflower instead of the radish can really hurt your "economy" as now you have crops that are not growing at the same time. You will need to wait until that crop is finished and the others too, that way they grow at the same time. It would be nice if players could undo or pay a price to ensure the right crops are planted.

**Comment by brian-man** [comment]
Workaround: Try to keep a "zero supply" seed in the most-recently-used list below the backpack.  When you later select a "zero supply" seed, then the plant-on-click functionality is blocked even if you "over-click" when harvesting.

Suggestion: Add the shovel option to the backpack (or an always visible button near-by) to effectively say "I don't want an active seed, because I'm not planting right now".

**Comment by ahh1539** [comment]
I think this is a great idea, would definitely enjoy this feature being added!

Do you imagine the shovel being a craftable NFT item with limited quantity or just a part of the base game?

**Comment by brian-man** [comment]
I think it makes sense as part of the base game.

**Comment by o6ris13** [comment]
I had this problem fews times and I think it would be a good solution to allow the removal of seeds planted unintentionally.
By crafting a shovel et least yes !

**Comment by newb23** [comment]
I have asset(s) for this once we get it going. (My next project?!?
![SpadeDW](https://user-images.githubusercontent.com/7065115/165018369-39907ece-acb3-4bc8-9fcc-9fe60261ca50.png)
![SpadeUW](https://user-images.githubusercontent.com/7065115/165018371-fbd59b14-d0da-43b4-be6c-d9b895e1cded.png)
)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
