### ISSUE TITLE
🐰🥚 Easter Egg NFT Hunt

### ISSUE THREAD

**Issue by danuribeiv** [sunflower-land/sunflower-land#542]
### Overview
- Players can mint an Easter Basket NFT starting on Friday April 15th until Sunday April 23rd (no max supply)
- Owners of the Easter Basket NFT can participate in the first Sunflower Land Easter Egg Hunt where players can search and collect 7 Easter Egg NFT’s across their farm.
- A total of 7 unique Easter Eggs can be collected (one for each day of the week starting Sunday, April 17th to Saturday April 23rd)
- Every 24 hours, one of the 7 Easter Egg NFT’s can be found across the map. After 24 hours, the last Easter Egg can no longer be found and a different colored Easter Egg will be available.
- Players who collect all 7 colored Easter Eggs can choose to burn all 7 Easter Eggs and the Easter Basket in order to mint an exclusive Easter Bunny NFT.
- Players can mint only one Easter Egg Basket and can only mint one of each colored Easter Egg.
- Players can trade Easter Eggs on OpenSea in order to complete their collection and mint the Easter Bunny NFT. 

### Easter Basket NFT

![basket](https://user-images.githubusercontent.com/10442760/163686370-47cb8e46-c83f-4339-b28c-5b68d7c52c29.png) (1:1 - 100%)

![basket-5x](https://user-images.githubusercontent.com/10442760/163686382-89d148c4-fc47-402a-b778-919ef0d4556a.png) (5:1 - 500%)

| Title        | Details                                                                                                                        |
|--------------|--------------------------------------------------------------------------------------------------------------------------------|
| Description  | The Easter Basket NFT grants access to the first Sunflower Land Easter Egg Hunt where players can collect Easter Egg NFT’s. |
| Mint Price   | ![token-export](https://user-images.githubusercontent.com/10442760/163301505-94c5cfcc-c833-4ace-b39f-a9e667ba090a.gif) **5** SFL, ![wood](https://user-images.githubusercontent.com/10442760/163301648-f8420c56-9478-4c47-adaa-d4c38275e7ac.png) **50** Wood, ![crop](https://user-images.githubusercontent.com/10442760/163301689-51c220be-9ebb-4e5b-9b77-c2f0d221db8b.png) **50** Carrots                                                                                                     |
| Mint Supply  | No Supply Limit                                                                                                                |
| Release Date | April 15th, 2022                                                                                                               |

### Easter Egg NFT's
| 3:1 (300%)                                                                                                       | 1:1 (100%)                                                                                                           | **Name**   | **Date Available**            | **Total Supply**    |
|------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------|------------|-------------------------------|---------------------|
| ![red](https://user-images.githubusercontent.com/10442760/163511764-1816d558-d9e3-4198-bde1-3a530a7c49d9.png)    | ![red egg](https://user-images.githubusercontent.com/10442760/163719981-da540a52-077e-407b-a0bf-dba530a6c9c4.png)    | Red Egg    | April 17th, 2022 12:00 am UTC | # of Baskets minted |
| ![orange](https://user-images.githubusercontent.com/10442760/163512150-6b8050e4-f6a9-4cf1-83ac-2dac99d66b61.png) | ![orange egg](https://user-images.githubusercontent.com/10442760/163719992-b913209f-b452-4a4f-880e-de38497626c1.png) | Orange Egg | April 18th, 2022 12:00 am UTC | # of Baskets minted |
| ![yellow](https://user-images.githubusercontent.com/10442760/163512478-3aec2124-8aea-4914-8406-2bf4d13697f6.png) | ![yellow egg](https://user-images.githubusercontent.com/10442760/163719998-efaf6ca0-8076-473a-85ec-2bd52182b78f.png) | Yellow Egg | April 19th, 2022 12:00 am UTC | # of Baskets minted |
| ![green](https://user-images.githubusercontent.com/10442760/163512498-7df79715-b6d7-4a5d-be40-821eddf7bb0d.png)  | ![green egg](https://user-images.githubusercontent.com/10442760/163720010-a9b31e6f-222c-46c6-a6cb-fe0998ef7d2f.png)  | Green Egg  | April 20th, 2022 12:00 am UTC | # of Baskets minted |
| ![blue](https://user-images.githubusercontent.com/10442760/163512554-3a6e6bcf-69bd-4d71-bace-3bdf47b2db89.png)   | ![blue egg](https://user-images.githubusercontent.com/10442760/163720022-9905ab36-6c0d-4371-a640-fe9357e5c45c.png)   | Blue Egg   | April 21st, 2022 12:00 am UTC | # of Baskets minted |
| ![purple](https://user-images.githubusercontent.com/10442760/163512685-52f99570-dea8-4e48-8ace-eb5044556442.png) | ![purple egg](https://user-images.githubusercontent.com/10442760/163720028-60402eb0-e9c7-461e-8cdf-9046099fdcff.png) | Purple Egg | April 22nd, 2022 12:00 am UTC | # of Baskets minted |
| ![pink](https://user-images.githubusercontent.com/10442760/163512715-41bf5159-d1e1-4d4d-a0ff-8a254feb59b4.png)   | ![pink egg](https://user-images.githubusercontent.com/10442760/163720034-58af06a3-6d89-44a4-81da-14d1a7009979.png)   | Pink Egg   | April 23rd, 2022 12:00 am UTC | # of Baskets minted |

### Easter Bunny NFT

![easter-bunny](https://user-images.githubusercontent.com/10442760/163686088-796a615a-67dd-4d4d-b866-060b258d36b0.gif) (1:1 - 100%)

![easter-bunny-5x](https://user-images.githubusercontent.com/10442760/163686098-8526e6a7-38b2-4fa8-bdac-ad874e0899bb.gif) (5:1 - 500%)

![easter-bunny-eggs](https://user-images.githubusercontent.com/10442760/163686117-08c9ddbf-6a55-429e-a90a-285a1cc419ef.gif) (1:1 - 100%)

![easter-bunny-eggs-5x](https://user-images.githubusercontent.com/10442760/163686123-0a2b1857-9e04-45a2-9534-c7f9c96fb563.gif) (5:1 - 500%)

![easter bunny](https://user-images.githubusercontent.com/10442760/163686236-a1e275d5-92f4-4058-bd73-cba68e7f77d8.gif)

| Title        | Details                                                                                                                        |
|--------------|--------------------------------------------------------------------------------------------------------------------------------|
| Description  | Players that have collected all 7 Easter Eggs can choose to burn 🔥 their eggs and basket to mint an exclusive Easter Bunny NFT. |
| Mint Price   | ![basket](https://user-images.githubusercontent.com/10442760/163298259-73ddb199-8add-4942-a1b2-8a53b80ed88e.png) Easter Basket NFT + ![eggs](https://user-images.githubusercontent.com/10442760/163320002-5ca47651-5dca-4a20-bacb-7a7afcecd7a3.png) 7 colored Easter Egg NFT’s                                                                                                    |
| Mint Supply  | Lowest # of Easter Egg NFT's                                                                                                                |
| Release Date | April 23rd, 2022                                                                                                               |

**Comment by SteveChickenCX** [comment]
OH YES! 
I love holiday events like this!

I really love the cheap price of it so any player can actually join the event and play it!

**Comment by haYouoo** [comment]
I think this activity is particularly good, so that more new users have a sense of participation. I agree very much

**Comment by wxiaode** [comment]
真棒

**Comment by adamhannigan** [comment]
@danuribeiv Great idea mate. We have got an engineer looking into this implementation as we speak.

Do you mind supplying some images of what the basket would look like in the shop? (when you craft it. I'm wondering if the colour palette would not contrast enough withe brown shop UI background).

It would also be amazing to get the rabbit part of the GIF separate. We would display the rabbit alone in the shop when crafting 😄 (since it is square dimension - with the eggs it makes it a rectangle shape which will resize strangely)

**Comment by haYouoo** [comment]
>What is the estimated price of SFL

**Comment by adamhannigan** [comment]
![egg](https://user-images.githubusercontent.com/11745561/163365927-ab12b848-72a0-4ea8-b4d2-22bb5ae36a35.png)

@danuribeiv Every egg will also show on the Open Sea collection. I'm a bit concerned that some of the eggs may not stand out enough when displayed on Open Sea (i.e they are too small).

Do you have an idea of how they would look on a 800x800 Open Sea display - https://opensea.io/collection/sunflower-land-collectibles

Perhaps we could use a similar egg shape from below and colour it accordingly. This has shading, is a bit larger and would stand out more

![egg](https://user-images.githubusercontent.com/11745561/163366106-edd20b78-00a2-4b59-a626-fc58fb74594c.png)

**Comment by haYouoo** [comment]
> @danuribeiv好主意伙伴。在我们发言时，我们有一位工程师正在研究这个实现。
> 
> 你介意提供一些篮子在商店里的样子吗？（当你制作它时。我想知道调色板是否与棕色商店 UI 背景对比不够）。
> 
> 将 GIF 中的兔子部分分开也会很神奇。制作时我们会在商店里单独展示兔子😄（因为它是方形尺寸 - 用鸡蛋使它变成一个矩形形状，会奇怪地调整大小）

What is the estimated price of SFL

**Comment by simiyet** [comment]
That is an amazing idea! I would love to join if there would be such an event. Tho a basket requiring 50 wood sounds a tat bit too much.

**Comment by cambrios1** [comment]
![eggs-ingame](https://user-images.githubusercontent.com/98171636/163380702-e3614fb9-3784-4b6a-841a-08ced0b1abc2.png)

![eggs (2)](https://user-images.githubusercontent.com/98171636/163380734-24f8122b-d0ff-4dd9-b6db-abcec4428ea6.png)

**Comment by Netherzapdos** [comment]
I've never really colored easter eggs before (not common in my country, or at least in my family 😝) but I've had a lot of fun designing these. Adam asked for some iterations and thought i'd give it a go 😄 This was based on the sprite Adam provided.

Large Previews:
![Green L](https://user-images.githubusercontent.com/101855553/163387674-ee4df292-5b5a-4e08-bb9e-8397b5bbed05.gif) ![Orange L](https://user-images.githubusercontent.com/101855553/163387676-fdcc0a3c-1fb7-4696-9eef-72d2a7cc5fb3.gif) ![Blue L](https://user-images.githubusercontent.com/101855553/163387678-d8c2b6f2-22f8-403c-abc7-33b33dac4721.gif) ![Pink L](https://user-images.githubusercontent.com/101855553/163387680-46853cec-3ad8-4adf-876c-5a4afc46f780.gif) ![Purple L](https://user-images.githubusercontent.com/101855553/163387681-a9bd9efa-2869-4871-84ba-b7b119205692.gif) ![Red L](https://user-images.githubusercontent.com/101855553/163387682-88ac7af0-4d0c-4596-ae71-c4df3be4e977.gif) ![Yellow L](https://user-images.githubusercontent.com/101855553/163387684-84d17211-859a-4337-bc8f-e413392eb24e.gif)

Raw Assets:

![Blue](https://user-images.githubusercontent.com/101855553/163387764-568b0414-9155-4a4f-bc69-4f2912b09e9b.gif) ![Pink](https://user-images.githubusercontent.com/101855553/163387770-cad0c5a6-37da-4664-940e-3996aae283bb.gif) ![Purple](https://user-images.githubusercontent.com/101855553/163387772-a7a6bc09-7974-4398-99ae-64aeae3951bf.gif) ![Red](https://user-images.githubusercontent.com/101855553/163387774-8b4d31d1-6e62-4a1a-829f-26ed4e6e2774.png) ![Yellow](https://user-images.githubusercontent.com/101855553/163387776-121be4f8-3ac5-48a5-879d-e9963e9a0a11.gif) ![Green](https://user-images.githubusercontent.com/101855553/163387779-a3efab6c-7e6d-4b54-8920-599cb1e13964.gif) ![Orange](https://user-images.githubusercontent.com/101855553/163387782-34a41a72-33b9-4cca-b0c6-1a3fffb13c19.gif)

Also, excellent idea, I really love concepts that involve making the player look around the map 😄 Tho probs just me, but I feel like half the amount of logs might be good? Either way, excited to get this into the game!

**Comment by SFL-Aeon** [comment]
> OH YES! I love holiday events like this!
> 
> I really love the cheap price of it so any player can actually join the event and play it!

I agree 100% I think content like this is an incentive for everyone to partake. The low crafting fees doesn’t leave anyone out and it gives light to special holiday events. Content like this is what can promote others to joining or staying. I would hope this content is exclusive to Easter 2022 that way it gives some collectibility as well for unique NFTs in the future.

**Comment by adamhannigan** [comment]
Some amazing egg designs coming in 👏 

@danuribeiv We may need to do a few tweaks to the rabbit as well. I love the animation but the rabbit itself is a bit similar to this one: https://www.dreamstime.com/pixel-sitting-bunny-easter-eggs-day-bit-art-image141045602

Do you think we could tweak it a bit more just to be sure we don't face any issues?

**Comment by danuribeiv** [comment]
updated the 🐰 and 🥚's!

**Comment by InuBakaBo** [comment]
it's a neat idea. it really does reminisce holiday events I have played in random games in the past

**Comment by Kratka007** [comment]
Great idea
For the price of the basket, I would sugest 5 SFL, 25 Wood, 50 Carrots

**Comment by adamhannigan** [comment]
Going live now 🚀

**Comment by gabiqueiroga** [comment]
I know I'm late but I just love bunnies 🥺

![EasterBunny2](https://user-images.githubusercontent.com/69090306/164128664-670298d8-d548-4f49-8272-474166d2a002.gif)
![EasterBunny1](https://user-images.githubusercontent.com/69090306/164128666-b13b326c-c156-42c9-b7be-ecfcff7de2b8.gif)
