### ISSUE TITLE
[PROPOSAL] Compensation for the early chicken adopters V1 

### ISSUE THREAD

**Issue by yelppp** [sunflower-land/sunflower-land#543]
Hello folks,

As the price of the chickens got apparently divided by 2, 
some people that bought a lot of those when the price of SFF was very high in V1, are being now kind of... chickened.
I would even say FRIED chickened.

So seeing this issue, we, as the chicken community protection club,
are proposing to create a compensation.

We do not really know the nature of the compensation, maybe it could be.. a special nft that will come in the future ? 
or something that you think would be logical to do given those particular and unexpected circumstances..

With the hope that you will take in consideration our request.

The chicken community protection club.
Sunflower lands.

![image](https://user-images.githubusercontent.com/103103259/163312038-b0ac8b29-fd82-42db-87ab-1a0b80a3c95a.png)

**Comment by PigaPigaPiga** [comment]
Hi all, I second this proposal/suggestion 👍 

The main difference I see between SFF v1 and now, is that Chickens didn't need Wheat for producing Eggs back then, and now they do .. So apart from being Cheaper to acquire now, they also 'punish' us a bit further by seeming quite demanding to keep up with Wheat-wise (if even possible, depending on Chicken counts) 🤔 Which will be interesting how folds out, but I think this proposal seems very reasonable as well, as that price has indeed received quite the cut

I like the idea of a special NFT in Celebration of the early Chicken Holders a lot, that'd be very special,, if so I'd love to propose the possible name: "1st Priced-Hen" , as a pun on it being connected to the first pricings of Chickens .. and it could be themed as a Medal Wearing Prize-Winning Chicken 🐔🎖️

It doesn't directly scale with the number of Chickens each player had, so as alternatives I suggest;

Recompensing our lost SFL in Chickens by letting our SFF v1 Chickens produce Eggs for a Week leading up to the Official Animal release (possibly without the wheat? 7 days of Wheat is around the 5 SFL reduction)

Or another option could be picking SFF v1 Chicken Holders as early Cow/Pig/Sheep airdrop targets, scaled to our Stock of Chickens. Like at a Sheep per 4 Chickens held (the 20 SFL from the Pigs/Sheep now equal out with the 4x 5 SFL reduced per Chicken prices)

**Comment by Don4quixote** [comment]
I strongly agree for the sheep airdrop, this is a beautiful idea, we need to make the community of golden-eggs aware of it.

**Comment by Meowgikarp** [comment]
yes to the chicken community protection club please! my v2 chickens are half the size compared to the v1 , no longer appears on my screen, refuses to lay eggs for the past 3 months , and demand offerings of wheat before they lay eggs ! I'm going to have fried chicken for the next few months instead : p

**Comment by MistaTinos** [comment]
I also think a compensation is necessary as early adopters most of us have been supporting this project and its developments within the community. All of the above mentioned ideas seem fair especially the airdrop of pigs sheep and cows.
In addition over the last 3 months chickens have been uselless earning us nothing, money that could have been used to farm needed resources or mine valuable minerals and wood needed for the NFTS. 
Ive been caught off guard with teh regular changes in schedule (which i totally understand btw) but this means that im not able to secure the NFTS i harvested for.
Mainly cause i now wont have enough SFL, i though i could buy SFL instead to justify my harvesting and manage to get all NFTS i wanted.
Nevertheless i trust the devs they have shown nothing but greatness

**Comment by sunfloweroglfg** [comment]
I like this concept and endorse it as well!

**Comment by sunfloweroglfg** [comment]
I like this concept and endorse it as well!

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
