### ISSUE TITLE
[PROPOSAL] Farmer Guild/Farmers Market

### ISSUE THREAD

**Issue by GoblinNoLikePotato** [sunflower-land/sunflower-land#544]
**UNDERSTANDING**

1.  resources liquidity pools will be added in the near future.

2.  it takes time to be develop as it has great potential to evolve into something bigger like a fully DEX
(the ambition is to be a multichain and $SFL is the utility token right? 😜)

**PROPOSAL**

1. In the meanwhile, we can add an NPC or a building in game to list out the current total supply of resources (I'm not sure if bank is for this) like what we have with SFL.

2. This will allowed players to :

- have an awareness of resources generated in game(not just SFL!)
- monitor the growth of resources and strategise their farming plan on top of NFT crafting.
- enable the 'supply and demand' play at the earliest
- would be great if we can add the total burn later when crafting is enabled. 

**This should be a feature that can be implement quick and scalable, I hope. 
Cheers🌻

**Comment by InuBakaBo** [comment]
Hello, it's me the NPC. lol

![image](https://user-images.githubusercontent.com/98318794/163337870-4ee95a40-1730-4315-afa5-4fb6c5a344e1.png)

**Comment by GoblinNoLikePotato** [comment]
> Hello, it's me the NPC. lol
> 
> ![image](https://user-images.githubusercontent.com/98318794/163337870-4ee95a40-1730-4315-afa5-4fb6c5a344e1.png)

Yes we should made you that NPC using your image 😉

**Comment by adamhannigan** [comment]
@GoblinNoLikePotato This is a great idea. I see lots of spreadsheets of people doing this.

If we expose this in the game it will involve more people in the strategy side of the game.

I would suggest reaching out on the #devs-chat and seeing if someone wants to help design it 😄

**Comment by Laoshi-Ferdy** [comment]
Very nice idea... I'm looking to it ^^
