### ISSUE TITLE
[PROPOSAL]REVALUATION

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#545]
it is an art in which I dedicated a lot of time both to produce it and to idealize it, I used color palettes that are within the game and followed all the size standards, in the proposal where I talked about it I had very positive feedback from the community
![image](https://user-images.githubusercontent.com/98098233/163334439-3c4a2565-6433-4e07-bbc8-46f0d42714a9.png)
![image](https://user-images.githubusercontent.com/98098233/163334455-4e5a8400-7493-4d03-adf4-3f14bb33291f.png)
and now in the cosmetics item proposal it's the second one that has the most ♥, behind my sword
![image](https://user-images.githubusercontent.com/98098233/163334479-71c0fff3-b6cb-4c86-af89-87aa6b344c45.png)
Because of this positive feedback from the community, I was perfecting the art creating several patterns, to give options to the devs, until spontaneously a certified dev contacted me, added me on discord and offered to do the programming, I know that now you are extremely busy with the launch, I apologize if I'm being boring, but I would like to ask you to re-evaluate the proposed implementation of the game art as I believe it meets all requirements
I leave the art attached below, with the patterns I made and the color palette

@adamhannigan 

![image](https://user-images.githubusercontent.com/98098233/163334284-2b462136-f7d7-4c33-8451-32c30df61baf.png)
![image](https://user-images.githubusercontent.com/98098233/163334290-fafcc97e-9073-4865-bda6-d07c28d0643a.png)
![image](https://user-images.githubusercontent.com/98098233/163334308-5a85f3b0-61d4-4359-befe-2fc98827b80c.png)
![image](https://user-images.githubusercontent.com/98098233/163334314-bcbb5165-117d-489d-9e66-a92ca9259965.png)
![image](https://user-images.githubusercontent.com/98098233/163334322-6a84b1cc-0336-44ee-93df-6128a6fed6d5.png)
![image](https://user-images.githubusercontent.com/98098233/163334330-98d7094b-fa22-4f7a-a490-6866ece5f8c3.png)
![image](https://user-images.githubusercontent.com/98098233/163334346-f3b2ad74-133c-4b9a-82b9-00aded1e1489.png)
![image](https://user-images.githubusercontent.com/98098233/163334362-a3c2d97a-7b59-48b4-9607-9ab87fc1e7a8.png)
![image](https://user-images.githubusercontent.com/98098233/163334592-2a4adf05-e72f-4bed-a1f6-551c2cd88a3a.png)
![image](https://user-images.githubusercontent.com/98098233/163334608-af97ad31-42d4-4d58-84be-f31e2a7690ce.png)
![image](https://user-images.githubusercontent.com/98098233/163334645-ae988e36-c1d2-4af4-9172-9f90bb6f9bf5.png)
![image](https://user-images.githubusercontent.com/98098233/163334687-73684e77-49c1-49d0-a21e-870b5883e0a7.png)
![image](https://user-images.githubusercontent.com/98098233/163334703-b97058a1-c370-438e-8965-bf6cfc568afa.png)
![image](https://user-images.githubusercontent.com/98098233/163334917-3cb80a1f-3f91-4532-a5fe-a29fed8f0b0b.png)

![image](https://user-images.githubusercontent.com/98098233/163335983-633d3a8c-5b9f-48e3-ac5c-b2c1cf76f2e1.png)

https://user-images.githubusercontent.com/98098233/163336243-904e336d-1aed-4f92-bba9-7e5f2ae5fc27.mp4

**Comment by Killu8726** [comment]
Beautiful artwork and concept!!

**Comment by vcferro** [comment]
For me the art is well done, I don't see any problems with the color palette. I also believe it would be nice to be re-evaluated

**Comment by adamhannigan** [comment]
@SrCouve Hey mate. Thanks for chasing this up. The truth is that we have been too busy the last week to focus on anything that wasn't launch related.

In terms of the art, when I suggested consistency with the colour palette I was referring more so to the background/base asset pack. The Golden Cauliflower doesn't fit the background perfectly and isn't placed on the map for that reason.

I would say that the colour palette more closely matching gold looks better 💪 Nice work.

A suggestion would also be to improve the shading on the base of the statue. Almost every item in Sunflower Land is short and chubby (even the goblins 😆 ). The knigth is short and chunky, but the statue is tall. I would suggest removing the 'N' so the base of the statue becomes more consistent with the style in the game.

Here is a reference of a base of the statue that is used in the base asset pack. The shading may be useful in your design.

<img width="29" alt="Screen Shot 2022-04-14 at 1 42 12 pm" src="https://user-images.githubusercontent.com/11745561/163535978-60a2be30-c5f2-453a-b896-94649268a017.png">

Thanks for the submission 👏 We will get round to adding more items we've just got a lot happening with the launch at the moment so we can't give everyone lots of feedback.

**Comment by SrCouve** [comment]
I'm very happy with your answer, and for having pointed me a north, I'll take all the feedbacks and implement it in the art to better suit your pattern.

**Comment by SrCouve** [comment]
@adamhannigan
![rework](https://user-images.githubusercontent.com/98098233/163608120-a33bf8fa-4868-4773-b122-8a0fb61a33e3.png)

Option 1:
![image](https://user-images.githubusercontent.com/98098233/163622156-68cf4b11-1d00-4e81-b121-4e454df9c691.png)![image](https://user-images.githubusercontent.com/98098233/163622226-09c4fa06-e3b8-446a-8062-2976b5948b32.png)![image](https://user-images.githubusercontent.com/98098233/163608747-81859a14-9804-455f-bea0-034e89494df9.png)![image](https://user-images.githubusercontent.com/98098233/163608808-8dc8f84e-914b-4c1e-985b-85b57d8cdd54.png)![image](https://user-images.githubusercontent.com/98098233/163621939-21887e71-305a-4830-93ab-c186ca17d74f.png)  ![image](https://user-images.githubusercontent.com/98098233/163621800-c5bb4129-34b6-433d-b464-40abee6c2523.png)

Option 2:
![image](https://user-images.githubusercontent.com/98098233/163622000-89d4bb71-1239-4697-9df4-2c19ae764818.png)![image](https://user-images.githubusercontent.com/98098233/163622059-4b7f3226-bde7-487a-9d30-7c42e4bb77c8.png)![image](https://user-images.githubusercontent.com/98098233/163622326-850286b0-47e3-4bda-a33b-0587ec572645.png)![image](https://user-images.githubusercontent.com/98098233/163623093-4a9b24f0-f99b-49a9-8e68-727f2e0b31dc.png)      ![image](https://user-images.githubusercontent.com/98098233/163623164-f9a5606c-ed67-4432-8d86-0b824017457a.png)  ![image](https://user-images.githubusercontent.com/98098233/163623227-7a83e540-5348-4299-8923-fbd5abaabe0b.png)


Option 3:
![image](https://user-images.githubusercontent.com/98098233/163622864-664cabfb-ed8d-4e5b-8444-6307e6e4c5b3.png)![image](https://user-images.githubusercontent.com/98098233/163622892-42f06ce8-f374-4421-b250-f72ed6ab661b.png)![image](https://user-images.githubusercontent.com/98098233/163623259-2c10fd45-4f6e-46cb-8413-e2d9806ca15d.png)![image](https://user-images.githubusercontent.com/98098233/163623310-ffdf12b1-3762-4d5d-b0e4-7be991f9b535.png)   ![image](https://user-images.githubusercontent.com/98098233/163623391-26e10bf8-168f-425f-932c-f122b4a8a288.png)  !
[image](https://user-images.githubusercontent.com/98098233/163623441-724a053a-d7ae-4be5-a649-fc4f69da2e03.png)

**Comment by ElcomJ** [comment]
Okay, I must admit that I would really like to have this statue on my farm, I really liked her Art as well as her story.
One thing I noticed about her that I didn't see in the others was that her color palette was all taken from approved NFTs and inside the game, something that is really cool.

And with this last update with a rework on her look she was much nicer to look at and only increased my desire to have her.

Congratulations to the Artist for the great work with this NFT.

**Comment by vcferro** [comment]
For me this one is the most well worked job already posted here

**Comment by adamhannigan** [comment]
Closing as these have been accepted in the latest competition proposal. Well done 👏
