### ISSUE TITLE
In Game Sounds

### ISSUE THREAD

**Issue by Stevew00dy** [sunflower-land/sunflower-land#547]
Can we please enable the ability from the menu to mute in game sound effects and in game music independently. Also to have a volume control for both sources so users can determine the levels they prefer.

**Comment by DonatasDee** [comment]
This was noted and asked for quite a while now, I'm pretty sure Romy said they'll do that.

**Comment by Pranav-yadav** [comment]
@Stevew00dy I've already implemented this features as part of **Settings** option 
## 1. Settings OP (_discontinued cause it's OP :)_ )

> Please ignore the 3rd button (It was for Mute, I had no image so used Pause & /   xD)

![Settings_-_Volume](https://user-images.githubusercontent.com/55224033/163442328-36ec6b82-3f59-4e7a-b112-2b2ef7cd6313.png)


## 2. Abstract Settings (_waiting for any suggestions from Team_)
![abtract-settings](https://user-images.githubusercontent.com/55224033/163442901-2ac07ed5-74b0-449e-8ef8-4a3bdae13c21.png)

**Comment by Pranav-yadav** [comment]
Also, you can have a look at **Logout** option/Button under Menu, PR #492 
Here [[FEAT]: Logout Button 🚀 ](https://github.com/sunflower-land/sunflower-land/pull/492)

Suggestions are welcome 😇

**Comment by Pranav-yadav** [comment]
Should be closed by #659 😊

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
