### ISSUE TITLE
[PROPOSAL] - a possible solution for multiaccounts

### ISSUE THREAD

**Issue by gokhanhoca** [sunflower-land/sunflower-land#552]
Hello, this is coming from a player who loves the project that opened 25 accounts in v1 (since it was legal) but feels sad that can't use the other farms since it is not allowed anymore. 
Yes, I trust the team and believe that I won't get rag pulled from the extra accounts and will be taken care of somehow... anyways...

consider this:
why does the community want to have more accounts? more plots, more planting, more profit, and a bit more fun

but the team wants people to have 1 or at least fewer farms like 5 farms. 

my question and proposal is this:
if people could invest in the same account more then they wouldn't have to open more accounts and this way they wouldn't have to pay extra fees for sending coins multiple times etc.

is this possible:
allow us to expand our land for extra plots for 1 Matic each time? each time it would open 22 more plots but like a new account, we need to unlock parts of that land from goblins. we need to cook the things like pumpkin soup, saurkraut, roasted cauliflower, and radish pie again to unlock parts of that plot again.

Does a person want to have 10 farms? Have 1 farm but spend extra 9 Matic to upgrade that farm to have 220 plots. This creates a seed stock problem, but solution shouldn't be hard to find. like stock number can get bigger for each upgrade farm receives. LVL 1 farm stock for sunflower seeds are 400 seeds. 10th upgrade it can be 400x10=4000. 

I am sure you guys can make this idea work and come up with much better things.

thanks for reading. <3

**Comment by adamhannigan** [comment]
This is where we want to head with the #215 proposal here 🤗 

@gokhanhoca It would be great if you could put your feedback on that issue for collaboration

**Comment by gokhanhoca** [comment]
i am going to coppy paste this here. if needed i will continue to comment to give more feedback and ideas

**Comment by RickFaker** [comment]
about multi-accounts. i want to propose the following: there are 2 people, one of them has a very developed account (which has many open beds, for example 220). the second has 10 accounts, which are not developed and he also has 220 beds. i think there should be a system that would force the dishonest player to spend a lot of time. For example: a system of watering or care for the earth. honest player enough to water the plants on their first 22 beds, and the remaining open beds (220 pieces), will be processed automatically. dishonest player will need to water each account separately, which will take 10 times more time. it should take about 30 minutes a day for an honest player and 30*10=300 minutes for dishonest.
 Someone who has a lot of accounts, at the moment spends very little time to maintain them.
