### ISSUE TITLE
[PROPOSAL] Stages of crops(fresh-normal...)

### ISSUE THREAD

**Issue by gokhanhoca** [sunflower-land/sunflower-land#558]
I think it can be good if there can be different stages of the crop
if you pick the crop fast the crop would be fresh and there can be a chance to get extra yield, after a while it gets less and less yield and if you wait too long it gets rotten(i am not sure about the rotten part people might be really upset about this but the other stages of the crop can motivate people)
kind of like this:
growing: (duh) :D
good/fresh: extra yield or extra chance for mutant crop
normal: a chance for extra seed
bad: regular yield
rotten: no yield or at least something so the shopkeeped will give you the seed back so there is no loss in money just loss of time. and the shopkeeper can say something like "I will take the rotten crop of your hands I can make ....... of them but I will give you money enough for the feeds so you can plant again"

after the crop is ready. there can be a timer.

and the time can be calculated something like this: 
good: %50-%99 of the time it takes 
normal:%100-%199
bad:%200%399
rotten:%500

example:
carrot(1-hour plant)
after it grows there will be a timer
between it is ready and 59min 59 sec it will be fresh
1 hour to 1 hour  59min 59sec normal
2 hours and 4 hours 49 min 49 sec bad
5 hours rotten

**Comment by gokhanhoca** [comment]
hell, if you want there can be extra use from the rotten crops like crafts for alchemy etc. so people would intentionally leave some crops get rotten, extra benefit for extra time for crafting but no SFL profit on shops.

just brainstorming for possible solutions for possible problems with the system.

**Comment by CrisisBomberman** [comment]
I think this is a good idea, it would make ppl motivated and collect their stuff and play the game much constanly.

**Comment by ahh1539** [comment]
What if rotten crops could be used to make fertilizer or some other item so it's not a complete loss. This could also scale with the crop growth time so it would take many more rotten sunflowers to make a fertilizer than say rotten cauliflower. These rotten foods could also be used to craft a funny "Bad Farmer" NFT too. 

example: 
didn't harvest the carrots within their optimum window so they turned rotten
5x rotten carrots can be used to craft one fertilizer that can decrease the grow time of another crop by 25%

**Comment by elvennoia** [comment]
Maybe having extended growth increases the chance of mutant crop since the crops have more time to mutate. but inturn fresh/normal crops will have normal/less yield. this will force us to decide when to harvest for more yield or more mutant crops.

**Comment by adamhannigan** [comment]
@gokhanhoca Great idea. A few people have recommended this and it definitely would help drive engagement with the game. 

Technically, we could implement this as a reduced fractional harvest. For instance, if you harvest a sunflower too late, you only receive 0.8. If you harvest it 1 week late, you only get 0.5
