### ISSUE TITLE
[PROPOSAL] Gnome's magic power

### ISSUE THREAD

**Issue by CrisisBomberman** [sunflower-land/sunflower-land#559]
Since v1, I saw a lot of ideas about what could the gnome's power possibly be.
It will have 4 different powers but these will occur rng based. But first let me explain how it should be triggered.

 _**How the mechanic works:**_
Gnome will be around the farm we use and every 24-48 (can be balanced) you will have a chance to trigger his power by clicking on it or icon on UI.

 _**Power list:**_

-  **Power of Forest:**

1. Gnome calls the power of forest and fertilizes the crops (Animation wise little green sparkles falls into your farm after gnome raises his hands to sky). This buffs varies into 3 buffs depending on rng.
2.   Your chances of getting seed from crops and mutants crops are increased for next harvest.
3.   You will be granted extra gather of field for next gathering (Extra amount of crops like 0.1-0.3)
4.   Trees gets lower cooldown to grow back.

- **Power of Nature:**;

1. Gnome does a various rituals to help your crops by creating seasonal effect (winter spring summer autmn).
2. This changes the environment for a sec to create a buff on your left side of screen. Buff indicates which season's buff you got and these buffs effect some of the seasonal crops such as growing faster or prevent losing a crop (if any sort a rotting system gets implemented)
3. Animation wise every season has a different rituel.
4. Winter: Eats a favorite food and hides under his hat.(like animation we have it covers his all body)
5. Spring: Gnomes starts dancing. (hopps around)
6. Summer:Puts his sunglasses on an lays down and enjoys the view.
7. Autmn: Collects the dried leafs around with harrow.

I hope you guys will like it. Thank you so much for reading

**Comment by Dajoenie** [comment]
This sounds very creative and fun.  There were not very many gnomes issued.  I think this idea would be great for a fairy, pixie, elf, etc. with a higher mint limit.  It would make this idea accessible to more people.

**Comment by Shew123** [comment]
Very creative and versatile proposal for Gnome, It was bought knowing it would have a function in the first version but now it's a pity it's just a decor

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
