### ISSUE TITLE
[PROPOSAL]: Background music for Fountain NFT ⛲

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#562]
## Proposal:
We can play the sound of flowing water (sound of fountain) whenever, player scroll's into view of the fountain ⛲ 
OR whenever Fountain is in viewport.

It'll be a more soothing experience 😄  for hard working farmers 🧑‍🌾  working day and night 😊

So that they can just go to fountain and take a rest and enjoy the nature's beauty and sounds.

PS: I can work on the background music logic for it. 😇
We might need to change the position of the fountain a little bit.

What say everyone ?
Vote on this proposal by adding your reactions 👍 yay , 👎 nay

**Comment by Laoshi-Ferdy** [comment]
Yeah! add more utilities for the fountain. Good job bro!

**Comment by Pranav-yadav** [comment]
@Rofrtd you've new task 😄 
We need Fountain Sound (sound of flowing water/ water falling from height) anything that you find suitable.

Do ping me whenever you are ready with it. Till then, I'll finish the coding and testing with (some dummy sounds).

**Comment by Pranav-yadav** [comment]
Had kept this open for different prupose as the your PR partially (75%) implemented the FEAT, the proposal is little bit diff. but, nvm, will push the complete feat for this proposal when I get time. 😇
