### ISSUE TITLE
Add a channel for content creator

### ISSUE THREAD

**Issue by Laoshi-Ferdy** [sunflower-land/sunflower-land#564]
First of all, I need to thank for Adam, Spencer, Romy, & Steve woody for this amazing game.

This game make me feel that I'm the true owner of my digital asset and I think this game need to be supported for all the content creator that love it too.

As one of content creator in the space, I would like purpose a channel in Sunflower Discord Server so any content creator can post their content to that channel. 

By doing this we can work together to support this game even more.

What do you think?

**Comment by adamhannigan** [comment]
@Laoshi-Ferdy Thankyou! Welcome to the community.

Have you sen #artists-chat and #devs-chat in discord?

We also have #community-ideas 🤗

**Comment by Laoshi-Ferdy** [comment]
> 

Thank you for the response Adam. Oke, I will post the content in that place.
