### ISSUE TITLE
[PROPOSAL] Shade & move 'SOLD OUT' NFTs to the bottom of the list (+ some other suggestions)

### ISSUE THREAD

**Issue by Muddshoe** [sunflower-land/sunflower-land#565]
Hey there, my proposal is pretty self-explanatory. Just shade & move NFTs that are no longer available for crafting to the bottom of the list. While I do like having all of them still viewable on the interface rather than completely getting rid of them, they get in the way of immediately seeing which NFTs are still craftable in-game.

On that matter, maybe do something similar for NFTs that you already own? Like add a green check tag on the top-right of NFTs you've minted and are in your farm and move them all before NFTs that have already sold out.

ALSO, could something be done to distinguish NFTs that are linked to each other in crafting? Not sure what about this specifically but I'm sure something can be done.

Cheers!

**Comment by SuperSynapse** [comment]
Great idea, I even like the idea of the "sold out" NFTs being on a separate tab, with the current opensea price/link

**Comment by ShiningMinions** [comment]
I have my eye on coding this one up for you. Thanks for suggestion :)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
