### ISSUE TITLE
[Proposal/concerns] Banning or limiting multi-accounting can actually kill price and the game totaly, really really quickly.

### ISSUE THREAD

**Issue by gokhanhoca** [sunflower-land/sunflower-land#569]
@adamhannigan 

this will be a long read. I am really sorry for that but I will give examples of other games that had the same problem. I thank you for your patience in reading it. I am only writing because I want this game to be successful and I don't want it to be another good project that had good hopes but had few problems that totally killed it. It happened too many times. Please read it, and look at the examples of other games. Also after reading it, please use some of the money from the ingame revenue from the 1 Matic fee, etc to get consultancy from the financial experts that actually understand the tokenomics of the NFT games, such as Efe Bulduk, I have read that he has helped some of the projects and the tokenomics looks actually promising. Ofc you can find other experts too. Even the game would be extremely fun if the income gets problematic NFT gamers don't play the game and the game dies. It happened too many times. I don't want it to happen on yet another game that I play, especially not this game. I have hopes for this game.

***

I am not a financial expert but I have seen this problem that I am gonna explain in many other games, and I am worried that if you guys ban or limit the multi-accounts it may cause big problems for the future of the game. and I want this game to succeed.

I have been thinking about the SFL price and the possible outcome of banning multi-accounting or limiting it.
I think if you ban or limit the number of multi-accounts the price can't rise much and possibly crash early.

consider this:
how does the price gets calculated for a currency or any item?
supply and demand...

supply is the amount of SFL we will create from our farms and from each halving it will be reduced so, the halving effect should benefit the price

demand. if there is no demand or very little, how can the price increase?

think about this and I have seen this demand problem on other games such as Heroes&Empires(they have created a demand problem on an update on the market currency issue. then they tried to fix it but the price already collapsed so badly after the fix, it didn't help the price or the project) or Axie and SFL problem(probably i don't even need to explain the game is very famous and everyone here probably knows it, yes the halving helps with the supply part but doesn't fix the demand issue I am gonna explain. I am giving examples about demand problems for the tokens and how the price moved or even got crushed after there is very little or no demand for the token.

consider this: Where does the demand for SFL come from? Why do people buy it? On v1 we bought SFL so we can have more accounts and upgrade them to level 3 fast so we can produce 8-hour crops on them. more people heard the game, wanted to play bought SFL earned and liked the game, used the revenues to create new farms and again and again. this happed with more people and the price got higher, so more youtube content, more people enter, they do the same thing the previous people did.

Why would anyone buy SFL? Why would there be a demand for people to buy from swaps? Why would people not wait just a few days on planting themselves and buy some SFL to kickstart their growth to reach plot number 22? How many people would buy it? Would it be more than the supply? or less? I imagine a lot less then the supply. So the price should decrease in this scenario and if there is lower income, less people would play the project even if the game is really fun. Heroes and Empires is seriously fun. The devs work really hard, fix the bugs in just a few hours(they were already a succesful company that have about 8 mobile games that are succesful and have more than 4.5 rating in the google store with some of them more than 500.000 players), etc but till they can fix the price, new people don't come to the game.

If there is no new players in the game this creates a crush. There are many examples of this.

there can and should be other ways to balance this problem. Such as adding supply sinks. I mean ways to spend SFL in the game that a lot of people would actually want to spend and enjoy doing so. Kind of the axe, pickaxe system you guys already added, but more things can be added. Anyways that's not the issue here. that can be a whole separate topic that should be talked about but that's another way to increase the demand by targetting the existing players.

--
I believe allowing multi-accounts may or may not cause long-term supply issues. I am not sure %100. 

but not allowing it might kill the game in short term, really quickly. 

because I am asking the same question: 
Consider this. In a scenario where people can't have a lot of farms and why would someone buy SFL so the price would stay stable or rise? When there is no multi-account, I would never buy SFL, why should I do it? i can upgrade to level 3 in 1 or 2 days easily. and to lvl 4(i mean 22 plots) in 1-2 more days. If I had a lot more farms, sure I couldn't handle the time required for it so i would buy SFL but if I have only 1 farm it is extremely easily done, maybe a few people would do it but i believe most people wouldn't. 
So all of the players in the game will create the sfl, and the NFT creation is not enough SFL sink, very little people wanna buy the token. what happens? the token gets worthless very quickly. what happens when the incone dies? people quit and the project is dead. This is an NFL game, the focus of %99 of the people is the income, the fun of the game is important but if there is no or very little income people that play the NFT games go to games that give the income. NFT gaming didn't reach the regular gamers yet. Regular gamers maybe might play awesome NFT games with low income but that day is very far from preset. The NFT games need the income and the income needs demand for the token. Demand needs 1) new players(they mostly care about the possibility of the income, quality of the game is an extra benefit for the most part) 2) in-game SFL sink. I have ideas for SFL sinks but like i said that should be a separate topic.

-
you can solve the long-term problems with the updates later. but first, the token needs to be valuable for people to be interested. 

If there is no demand for SFL for the NEW PLAYERS. I am afraid that the game cannot survive.

I am gonna explain my Heroes and empires example further. Because it had almost the same problem after that update i have mentioned before.

The token's name is HE. There was a very little in-game sink for the HE and it was easily created. 
You had 5 characters for a team. each character needed 110 HE for the max level for a rare characters. So you needed 550 HE for your team to max level. you could roughly earn about 45 to 55 each day easily. So the ingame sink had no chance to hold the demand so no chance to hold the price stable or increase it. There were very few extra things you could buy but they were not significant either. Most people didn't buy them.

What kept the price? The only way to play the game was to buy characters for your team and you needed HE on the market for that. but there was a problem. The team had a calculation on tokenomics and on each hero sold there was a BNB fee and on each hero sell there was a selling pressure for the HE because the team needed to sell HE to BNB from the team wallet so they could pay the fee for the market for that day. So the BNB price created a price deducing problem slowly but it was coming down. First they blamed the people who used bots and tried to make it harder for bots to have income by reducing the income, then they made the quests harder, then they reduced the daily income 3-to 4 times after that. Each time they reduced the income, 1)the excisting players got really mad and quit the game, 2) fewer people started the game since the income was lesser. 3) yes, that reduced the supply but it created less buying pressure for the token. so less demand.
Then they had done the big mistake. They have decided to change the buying currency for the market from HE to BNB. So no %5 selling pressure from the BNB fee, they said that would increase the price %5 slowly but surely since they would save some money from it and they said they would buy HE with that money and add that to the pool that would fix the price issue.
but there was a huge mistake. HE was %90 used mostly on the market for buying and selling heroes. There was almost no other demand for it, and people would have more supply than they needed, why would people buy HE now? there was no reason other than investing in the game hoping the game would be successful and the token would increase like a regular coin on Binance. There was almost no sink for it, no actual actually demand. The price was about 35 cents. just a few months later, the price is less than 3 cents. Why did this happen? 1) they forgot the demand for the token. 2) they tried to balance the supply by reducing the income for the players. but that caused people the quit the game, or make it for the new players less likely to start the game. The game is totally awesome. the price sucks. even though i love the game, I honestly don't wanna play it anymore.

this can happen in this game too. 

imagine what will happen on May 9th if people don't actually need the SFL for their farms, to upgrade their farms, their multiple farms. Why would there be a demand for the token? what would happen to the price? halving can only be a solution if there is a demand if there is a reason for people to buy the token.

**Comment by bphalanx** [comment]
Totally Agree. This problem should be adressed before realese. Gj man nice insight....

**Comment by Roggol02** [comment]
totally agree and because system halvening multi account it becomes difficult then everyone turns farm and craft other ressource... Then we need new ideas and new nft that you will need sfl ... and from me this game need phase 1 and phase 2 3 ...

**Comment by adamhannigan** [comment]
@gokhanhoca Thanks for the detailed write up, some great points 👏 

To me the fact that players need to create a new account to spend more SFL/MATIC to build up their empire is more of design issue with the current game. Players want to grow crops on more land, the only issue is that farms right now have a limit of 22 plots.

The vision of the game is moving towards land expansion, which means you can do the same action of spending SFL + MATIC to work on new pieces of land, but now your farm will all be organised under 1 account.

The main issue with enabling multi-accounting at scale is that it favours bots and makes it hard to distinguish real players with multiple accounts from bots. Reducing the amount of accounts is a great mechanism to restrict a bot trying to operate on a large scale. 

I suggest that we take a lot of the tokenomics/points you raised but make changes to the core design that encourages people to invest more SFL + MATIC into their current farms instead of having to create separate farms. This has a side effect of also making it much easier for a player to manage their farm. Instead of having to manage multiple accounts and wallets, all of their lands will appear under a single account to view.

**Comment by newb23** [comment]
To throw a couple of cents into the discussion as well, a "happy medium" to the land expansion discussion in contrast to multiple accounts/wallets can certainly be the ability for one address to have X (5?) number of farms with a "switch farm" function to go between them. This will allow for a limited amount of both "multi-accounting" (without actually having multiple accounts to worry about/manage) as well as allow itself to lend towards the "land expansion" path naturally.

Kind of a two birds one stone deal. One of the challenges, obviously, is adding the ability for multiple farms within that single account.

**Comment by ffhjbhh** [comment]
The development team doesn't want the price of sfl to be too high, because this is a game, not a money plate.  The price of sfl does not mean success or failure. Those who speculate when the price is low will leave, and loyal players will stay. This is what they want to see.  And sfl has no pre-sale, no private placement, the development team can maintain the game operation by donating, just like steve said, the price of sfl can be kept at 0.05-0.1$.  So please keep an ordinary mind and look at this game, it is just a game, not a fund.

**Comment by Kubeki** [comment]
@adamhannigan Hi Adam, concerning bans and sanctions, i went to opensea to check some NFT fluctuation and tendencies  suddenly i had to sort out some malicious people or agents transfering some crops and  plenty NFT, here is some of them. 

https://opensea.io/Misha999?tab=activity  (7 carrot swords) no sales or exchange activities 

https://opensea.io/wulihaha?tab=activity (8 carrot swords) no sales or exchange activities

**Comment by InuBakaBo** [comment]
@Kubeki 

> @adamhannigan Hi Adam, concerning bans and sanctions, i went to opensea to check some NFT fluctuation and tendencies suddenly i had to sort out some malicious people or agents transfering some crops and plenty NFT, here is some of them.
https://opensea.io/Misha999?tab=activity (7 carrot swords) no sales or exchange activities
https://opensea.io/wulihaha?tab=activity (8 carrot swords) no sales or exchange activities

I checked and those two are fine. They both had one carrot sword and listed multiple times. Nothing malicious.

https://polygonscan.com/token/0x22d5f9b75c524fec1d6619787e582644cd4d7422?a=0x6c3ea92747484514763bea5cbb8e6fb48718dd97
https://polygonscan.com/token/0x22d5f9b75c524fec1d6619787e582644cd4d7422?a=0xc4649007c0ff94926165e82b44F34bd313b4e1fF
shows both only have transferred 1 carrot sword

https://polygonscan.com/token/0x22d5f9b75c524fec1d6619787e582644cd4d7422?a=0xd33241b559806d2b90cbffe65722a9fbf9ca792f#inventory
https://polygonscan.com/token/0x22d5f9b75c524fec1d6619787e582644cd4d7422?a=0xab705a0421b9e4c51aa6f64ab3a384928d8efdc9#inventory
shows their farm inventory does not have any carrot sword as they had withdrawn their 1 carrot sword into their wallet to trade on OpenSea

**Comment by gokhanhoca** [comment]
@adamhannigan I fully support allowing us to open new lands on the same account instead of making us open other accounts. it is a much better approach for everyone. I think if you can do it before the launch of the token it would be really great for the future of the game since the price can start from a good place. (demand from the start I mean)

**Comment by Katonika** [comment]
Multiple accounts may cause problems for the life of the game, but it would be nice if the nfts in old accounts could at least be transferred to the original account, I think there has been no announcement about it yet.
For example, I have 2 fields in my hand, I crafted nft in both of them, you can open one here in my previous account, what will be my right in the other field

**Comment by sunfloweroglfg** [comment]
> @gokhanhoca Thanks for the detailed write up, some great points 👏
> 
> To me the fact that players need to create a new account to spend more SFL/MATIC to build up their empire is more of design issue with the current game. Players want to grow crops on more land, the only issue is that farms right now have a limit of 22 plots.
> 
> The vision of the game is moving towards land expansion, which means you can do the same action of spending SFL + MATIC to work on new pieces of land, but now your farm will all be organised under 1 account.
> 
> The main issue with enabling multi-accounting at scale is that it favours bots and makes it hard to distinguish real players with multiple accounts from bots. Reducing the amount of accounts is a great mechanism to restrict a bot trying to operate on a large scale.
> 
> I suggest that we take a lot of the tokenomics/points you raised but make changes to the core design that encourages people to invest more SFL + MATIC into their current farms instead of having to create separate farms. This has a side effect of also making it much easier for a player to manage their farm. Instead of having to manage multiple accounts and wallets, all of their lands will appear under a single account to view.



> @gokhanhoca Thanks for the detailed write up, some great points 👏
> 
> To me the fact that players need to create a new account to spend more SFL/MATIC to build up their empire is more of design issue with the current game. Players want to grow crops on more land, the only issue is that farms right now have a limit of 22 plots.
> 
> The vision of the game is moving towards land expansion, which means you can do the same action of spending SFL + MATIC to work on new pieces of land, but now your farm will all be organised under 1 account.
> 
> The main issue with enabling multi-accounting at scale is that it favours bots and makes it hard to distinguish real players with multiple accounts from bots. Reducing the amount of accounts is a great mechanism to restrict a bot trying to operate on a large scale.
> 
> I suggest that we take a lot of the tokenomics/points you raised but make changes to the core design that encourages people to invest more SFL + MATIC into their current farms instead of having to create separate farms. This has a side effect of also making it much easier for a player to manage their farm. Instead of having to manage multiple accounts and wallets, all of their lands will appear under a single account to view.

Completely agree. As a numbers guy you can mitigate alot of this by having to build up 1 farm rather than multi-accounting. Scarcity is built up when you only have the ability to hold "one" of each item to build things up.... the timer buffer on minting an NFT etc.... all adds value. Building out 1 farm at a time should be the way to make this work.

**Comment by sunfloweroglfg** [comment]
> @gokhanhoca Thanks for the detailed write up, some great points 👏
> 
> To me the fact that players need to create a new account to spend more SFL/MATIC to build up their empire is more of design issue with the current game. Players want to grow crops on more land, the only issue is that farms right now have a limit of 22 plots.
> 
> The vision of the game is moving towards land expansion, which means you can do the same action of spending SFL + MATIC to work on new pieces of land, but now your farm will all be organised under 1 account.
> 
> The main issue with enabling multi-accounting at scale is that it favours bots and makes it hard to distinguish real players with multiple accounts from bots. Reducing the amount of accounts is a great mechanism to restrict a bot trying to operate on a large scale.
> 
> I suggest that we take a lot of the tokenomics/points you raised but make changes to the core design that encourages people to invest more SFL + MATIC into their current farms instead of having to create separate farms. This has a side effect of also making it much easier for a player to manage their farm. Instead of having to manage multiple accounts and wallets, all of their lands will appear under a single account to view.



> @gokhanhoca Thanks for the detailed write up, some great points 👏
> 
> To me the fact that players need to create a new account to spend more SFL/MATIC to build up their empire is more of design issue with the current game. Players want to grow crops on more land, the only issue is that farms right now have a limit of 22 plots.
> 
> The vision of the game is moving towards land expansion, which means you can do the same action of spending SFL + MATIC to work on new pieces of land, but now your farm will all be organised under 1 account.
> 
> The main issue with enabling multi-accounting at scale is that it favours bots and makes it hard to distinguish real players with multiple accounts from bots. Reducing the amount of accounts is a great mechanism to restrict a bot trying to operate on a large scale.
> 
> I suggest that we take a lot of the tokenomics/points you raised but make changes to the core design that encourages people to invest more SFL + MATIC into their current farms instead of having to create separate farms. This has a side effect of also making it much easier for a player to manage their farm. Instead of having to manage multiple accounts and wallets, all of their lands will appear under a single account to view.

Completely agree. As a numbers guy you can mitigate alot of this by having to build up 1 farm rather than multi-accounting. Scarcity is built up when you only have the ability to hold "one" of each item to build things up.... the timer buffer on minting an NFT etc.... all adds value. Building out 1 farm at a time should be the way to make this work.
