### ISSUE TITLE
[PROPOSAL] Crop ready sounds

### ISSUE THREAD

**Issue by brian-man** [sunflower-land/sunflower-land#576]
_I don't know if it's against the design intent of the game; if so, just close it I guess.  But I figure I'll ask..._

### Backdrop

I find myself repeating the following pattern:
1. harvest
2. sync if needed
3. buy seeds
4. sunflowers - plant, harvest, repeat
5. potatoes - plant, harvest, repeat
6. (sometimes) watermelons - plant, harvest, repeat
7. (rarely) carrots - plant, harvest, repeat
8. if not bedtime, return to step 2
9. buy <expected sleep duration> seeds
10. plant
11. sleep
12. return to step 1

For steps 5-7, I end up setting timers -- either on PC or phone.

### Proposal

Can we add optional "crop is ready" sounds in the game?

This is a QoL (quality of life) upgrade for players.  Simpler and more immersive.

If when buy/sell/trade is in game, this feature would make it even easier for people to "spend the downtime" in-game with such activities.

### Next steps

If the team approves of this proposal, I'd like to create the PR (draft?) using existing sounds (as temporary placeholders?).

**Comment by slayorktc** [comment]
I have been thinking about this quiet a bit. Currently, I assume, most mobile users are accessing the game from the metamask browser which I don't believe supports notification. Is there a better dapp browser that sunflower can use to push notifications? The other option which requires more work is to build an iOS/android app natively around sunflower land. Ideally with a wallet as well but could also just hook back to metamask for signing (I have seen other apps do this). I would lean toward this being the better option but would require a bit more upfront work. The native app can allow for the user to specify notification amounts, types, etc while also operating inside the phones native notification system (Obey silent, vibrate only, do not disturb, etc)

The other question, which hopefully a dev came chime in on, is how do we get access to non blockchain data (time_left_to_harvest, harvestable, etc).

**Comment by adamhannigan** [comment]
@brian-man I am for this idea 👌 

Do you expect the sounds to be played only while the game is active, or also in the background (i.e. other tabs)

**Comment by brian-man** [comment]
> Do you expect the sounds to be played only while the game is active, or also in the background (i.e. other tabs)

My recommendation:
v1: All sounds are on/off based on the global sound setting regardless of window focus.
v2: Change the global sound setting from on/off to on/focus/off.
v3: Categorize sounds into music, ambient effects (frogs), time effects (item is ready), and action effects (plant, harvest).

**Comment by JacobSobolev** [comment]
@brian-man @adamhannigan 
I think it would be better to put a push notification instead. 
you can easily miss a sound effect, but if we do a push notification when the crops are ready (all of them) it will be much more noticeable.

If this will be implemented we won't have any life left^^
