### ISSUE TITLE
[PROPOSAL] Add a close icon and modal hide event for captcha modal during sync to chain

### ISSUE THREAD

**Issue by okesseko** [sunflower-land/sunflower-land#577]
Once open captcha modal after click the sync to chain button, user can't close the captcha modal unless they do the captcha or refresh whole page.

Maybe we can add a close icon and close event on modal mask just like other modal ex. how to play. Make sure the user has a way to close the modal instead of refreshing the whole page

**Comment by adamhannigan** [comment]
@okesseko Great suggestion, this makes sense to me. We want consistency with the close buttons that are seen throughout the game

**Comment by okesseko** [comment]
Thanks, I did it in the pull request https://github.com/sunflower-land/sunflower-land/pull/578
You can check it 😀
