### ISSUE TITLE
[PROPOSAL] Wait list UI instead of limit UI

### ISSUE THREAD

**Issue by brian-man** [sunflower-land/sunflower-land#585]
### Concern

While it's exciting for people in Beta (and for the developers on the team) to recognize that the 100k slots have been filled, it's a sure way to turn away players that come to the site after getting excited from "socials".

### Recommendation

Replace the "you're too late" sign with "currently full, join the wait list here".

A few benefits:
1. potential players leave the site that day with hope rather than pure frustration
2. players can attach discord accounts immediately (good for both player and game)
3. when more farms are enabled, "first come first serve" is better than "who happens to be in the right time zone"
4. the wait list queue is something that can be used for yet more social promotion
5. the wait list queue is another input into the "how fast should we open" and "what should we prioritize" thinking

**Comment by adamhannigan** [comment]
Agreed @brian-man Much more friendly and inviting 🤗

**Comment by Marcyansir** [comment]
好贴心的操作，点赞。

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by brian-man** [comment]
> Popping in a note saying this can be updated/closed. <3

What makes you say that?

The current user experience is still terrible:

> Supply reached!
>
> 100,00 farms have already been minted
> for open beta. More spots are opening
> soon!

Nothing has improved since this issue was opened.

**Comment by brian-man** [comment]
> Probably because I was thinking about the botting message, not this one. That is entirely my bad.
No worries.  Just found it confusing.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
