### ISSUE TITLE
[Suggestion] Maintain a new type of resource "Energy" and add "Mill".

### ISSUE THREAD

**Issue by JCtapuk** [sunflower-land/sunflower-land#586]
Add a new resource "Energy" all new farmers get 100 energy.
Energy is spent by interacting with the game such as planting seeds or collecting produce.

Where to apply:
- Plant Seeds (-0.01 energy)
- Harvest Produce (-0.01 energy)
- For cutting trees (-0.02 energy)
- For Scavenging Stones, Metal, or Gold (-0.025 energy)
PS And others that developers can decide where to apply it.

Where to replenish energy:
- For applying food "Pizza" (+100 energy)
- For the use of food "Bread" (+25 energy)
PSS Where these food will be taken then the players can buy it for tokens from other players or produce it themselves.

Add new building "Mill"
It will process wheat into flour

Craft can be added up to 4 slots and will produce 1 hour. So you have spent 5 wheat and you have to wait 1 hour to get 5 flour. Since they are grinding the wheat into flour.

In the kitchen add 2 meals:

# Bread
- 5 Flour
- 1 Eggs
- 1 Milk

# Pizza
- 50 Flour
- 5 Eggs
- 5 Milk

These resources may have different numbers at the developer's discretion.
These items can be stored in the bag and used. And also will protect those who want to madly farm sunflower for a few windows as energy it will stop them having to do the opening of the wheat and then produce energy will take a long time in this time can get caught for the bot or multiaccounts.

**Comment by adamhannigan** [comment]
Cool idea @JCtapuk 

With the upcoming land expansion proposal, there have been some great ideas around "stamina".

Would players be able to trade energy or is this a non tradeable?

**Comment by JCtapuk** [comment]
> Крутая идея @JCtapuk
> 
> С предстоящим предложением о расширении земли появилось несколько отличных идей вокруг «выносливости».
> 
> Смогут ли игроки торговать энергией или это не подлежит обмену?

Yes you can sell "Pizza" and "Bread" in OpenSea. Players who buy it can activate it in their inventory to replenish energy. But the energy resource itself is strictly tied to the farm. 

This will give that newcomer to buy from good farmers until he produces his chain of making "Pizza" and "Bread" and so on.

**Comment by eggc95** [comment]
I myself hate games with energy/stamina concept, feels like a mobile game where you have to p2w essentially

**Comment by JCtapuk** [comment]
> I myself hate games with energy/stamina concept, feels like a mobile game where you have to p2w essentially

It's not what you think. Farmers who play the long game will earn money from new players or hitch to speed up the game them new farms will buy from rich farmers.
And this will protect multiacounts.
And sode long game farmers will get money and produce food for newcomers in the end will transform the cycle.
That's why this is an important option to have in the game and not like in other games where energy replenishes automatically here you have to buy from players.

**Comment by eggc95** [comment]
that just makes it worse, it's really not an enticing system to attract new players, they would look at it as an impossible mountain to climb and just turn away from the game since old players seems to be the only ones profiting not to mention the monopoly that old players can possibly have, this much control to veterans is never good for a game and feels too much like an MLM scheme type of system to me

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
