### ISSUE TITLE
[PROPOSAL] Mutated plants, different rarity for pvp battles

### ISSUE THREAD

**Issue by IvanSkazkin** [sunflower-land/sunflower-land#588]
**I understand that the idea is strange but still.** What if mutated vegetables have different types of rarity and damage. And then they can be used in pvp between players)
Also, mutant vegetables will not immediately appear in the inventory, but will be like a lootbox.
Also boxes will be of different rarity.
Then there will be a strong demand for these things. And then you can declare war and earn sfl. Mutated cultures are also needed to defend the garden, for example)

**Comment by haYouoo** [comment]
yes  is good

**Comment by adamhannigan** [comment]
@IvanSkazkin I like this idea.

For launch we will be keeping the idea very bare bones (and just decorative). The same with other decorations, we plan on adding functionality down the track 🤗

**Comment by adamhannigan** [comment]
Let's continue this chat in #507
