### ISSUE TITLE
[PROPOSAL] Introduce an at least 1% growth rate increase for Sunflowers when holding the Sunflower Statue

### ISSUE THREAD

**Issue by Muddshoe** [sunflower-land/sunflower-land#589]
I understand that nothing is permanent until beta finishes, but it feels a bit unfair that the description of the Sunflower Statue was almost secretly changed before minting was allowed. The statue went from previously having an insane potential utility to being only fully a cosmetic, while the crafting requirements stayed entirely the same.

The change I propose (1% growth rate increase for Sunflowers) might be more of a placebo buff than anything, but I want the statue to _at least_ do something. You could even bump it up to 5% or something.

A similar change happened to the gnome, which was previously mentioned to have weather-altering effects to being only a lucky gnome, but at least that change came early during the beta. If features were to be introduced to these NFTs later down the line then maybe the placebo buffs could be remove, but I would like them to have (even if an incredibly weak) effect rather than being completely cosmetic, especially when they were minted with the understanding that they would offer strong buffs.

**Comment by Laoshi-Ferdy** [comment]
I love the fact that this NFT is in the center of the farm

The NFT is really great to show the one who has it is the real OG in sunflower land

For this proposal, I agree if it can be add more utilities to it in other to reward people who are willing to collect the NFT.

**Comment by adamhannigan** [comment]
Hey @Muddshoe Thanks for raising this.

Initially in Sunflower Farmers the description was "Symbol of the holy token" and was purely decorative. The text in Sunflower Land was a placeholder only meant during early beta testing and wasn't meant to show for game launch. 

With all the decorations, the idea is that functionality will be added to them in the future by us or other developers (the beauty of open protocols on the Blockchain). 

In my opinion, I think it is a very rare decoration in the centre of the farm. When we add functionality, I would prefer that it is something more original than just a crop boost. I.e Early access to land expansion. I want to be careful of just giving everything crop boosts as it will saturate the current NFTs.

The gnome was a good lesson from V1. The initial developer/designer launched this as a community crafted NFT but once it launched and sold out left the project and so no one implemented it 😢 We will need to work on a better system when community crafted items go live. They are easy to design, but take much more work to actually implement.

**Comment by adamhannigan** [comment]
@Muddshoe Also worth adding this feedback onto this Github issue - https://github.com/sunflower-land/sunflower-land/issues/587

Looks like you both share some similar ideas 😄

**Comment by sunfloweroglfg** [comment]
Appreciate Adam's prompt response on all of it.

**Comment by sunfloweroglfg** [comment]
Appreciate Adam's prompt response on all of it.

**Comment by Laoshi-Ferdy** [comment]
> In my opinion, I think it is a very rare decoration in the centre of the farm. When we add functionality, I would prefer that it is something more original than just a crop boost. I.e Early access to land expansion. I want to be careful of just giving everything crop boosts as it will saturate the current NFTs.
> 

I agree with Adam about this ^^ Thanks for the response

**Comment by adamhannigan** [comment]
Moving conversation to #587
