### ISSUE TITLE
[PROPOSAL] I propose to offer an additional 50,000 spots to our Discord subscribers.

### ISSUE THREAD

**Issue by O-Houtarou** [sunflower-land/sunflower-land#591]
Now the project is just getting hot, but the 100,000 spots are already full, and many enthusiastic players are complaining in Discord that they can't register, which is blocking other enthusiastic players from participating, so it's better to add another 50,000 spots.

**Comment by adamhannigan** [comment]
@O-Houtarou We definitely will but we need to be careful of scaling too fast.

Right now we are adding new engineers and Discord mods to help support the growing amount of people. If we don't have the systems in place the game would be overloaded by the time we reach 300K+ users and it would be very hard to help out people in the community.

**Comment by Kubeki** [comment]
@adamhannigan We can add gradually like 20k spots each week, because what i see there in Discord is people complaining about limited spots and missing out by buying those blacklisted/gray Lands which is unfortunate, we have to insure new people and introduce newcomers slowly because when i check sold lands i see people buying massively Gray and Blacklisted one which is unfortunate this can have a negative impact and build a negative reputation and the world of blockchain is viral we might again generate a bad buzz into this kind of procedure.

**Comment by adamhannigan** [comment]
@Kubeki That is fair.

From our point we need to ensure our Discord and game can support more users. Adding more players would give us more revenue, but right now we feel we need to improve the quality of the Discord and the game.

I don't want the next 20K users experiencing a game that has bugs and a poor support system.

**Comment by Kubeki** [comment]
@adamhannigan I try my best to help the community on Discord by responding every newcomer and assist every Farmer having an issue or trouble regarding the game, i just report what i've seen recently by helping other's, 80% of people request is about blacklist and land issues if you need any help to reduce the support stress i can help, i am actively helping people i can also drop my discord here, so you can see that i am actively working with you for the love of the community 👍

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
