### ISSUE TITLE
[PROPOSAL]  DECORATION RANK

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#592]
I think the concept of decorative NFTS is cool, but I think it would be interesting to add a decoration rank, where each NFT would give a score (Based on its scarcity and  mint price) and depending on your rank position you would earn a certain amount of SFL (Daily , weekly or monthly) to avoid abusing this system when you wanted your nft to score in that rank you would choose a "hold" option where it would only be withdrawn after the rank score deadline, I think it would be a system cool to encourage the purchase of cosmetic Nfts and gives functionality to them, even Nfts with utilities could enter this rank 

I believe it would be a very interesting mechanic to bring competitiveness to the game, we could also add a new NPC in the city, which would be where we would see the farms of the rank and we could visit them directly by clicking on the rank,
in addition to stimulating trade and the creation of decorative NFTS, it would also stimulate interaction between players, making it more meaningful to visit other farms

**Comment by adamhannigan** [comment]
Some great ideas. Let's continue the chat over in #607
