### ISSUE TITLE
[Art proposal] Beaver animation 

### ISSUE THREAD

**Issue by paluras** [sunflower-land/sunflower-land#593]
Made with the same idle animation as the asset pack 

![beaveraprentice](https://user-images.githubusercontent.com/98059798/163811731-0c6fc36a-1884-4aa2-82d5-e44ed3e6de6b.gif)
![beaverexpert](https://user-images.githubusercontent.com/98059798/163811735-cce89ccd-25ff-473d-ae10-25c316e98748.gif)
![beaver](https://user-images.githubusercontent.com/98059798/163811738-11b16703-09f0-4ad1-8e24-67a8bfed2398.gif)
![beaveraprentice-export](https://user-images.githubusercontent.com/98059798/163811740-af11b1e0-e831-4700-91bd-a77e3b9c2d33.gif)
![beaverexpert-export](https://user-images.githubusercontent.com/98059798/163811741-3dc3b946-002d-4aa0-858b-f23e6fa17c60.gif)
![beaver-export](https://user-images.githubusercontent.com/98059798/163811746-850db1f6-5cae-45fd-b0fe-0c03dbfb55cb.gif)

https://user-images.githubusercontent.com/98059798/163811886-4dbf570e-d3dc-4ea0-91a1-84aa0bed97a4.mp4

**Comment by DonatasDee** [comment]
This is a must, we need to try avoid static living beings as they really look abnormal when everything else actually moves.

**Comment by adamhannigan** [comment]
@paluras Legendary work ❤️

**Comment by adamhannigan** [comment]
https://github.com/sunflower-land/sunflower-land/pull/613
