### ISSUE TITLE
[PROPOSAL] Daily and monthly lottery will speed up SFL burning. Make NFT more valuable rare and expensive

### ISSUE THREAD

**Issue by IvanSkazkin** [sunflower-land/sunflower-land#594]
**Hello.** I propose to create a daily lottery
The players buy a ticket. One ticket 1 sfl (or other amount). When the winner is announced, he will receive 50% sfl of the total prize.
The rest of the SFL can be burned or placed in a wishing well.
This way you can burn SFL faster.
After each harvest, the coin price per ticket is reduced by two

**You can also make a monthly unique NFT**. (it can even be a purely decorative element) 
Only those who participated in 10 lotteries per month can register for participation.
So we would make the NFT market more valuable, we would not break the economy (this is just a decoration). Increased the burning rate of SFL tokens. Thanks

**Comment by adamhannigan** [comment]
@IvanSkazkin Thanks for the suggestion! We've had a few similar ones relating to this.

Unfortunately we can't explore ideas that related to gambling. Even though this is a game, we want to be careful not to cross any area that might be considered as crypto gambling for legal reasons.
