### ISSUE TITLE
Proposal- Shift-click Deposit and removal items

### ISSUE THREAD

**Issue by sunfloweroglfg** [sunflower-land/sunflower-land#597]
Just a simple proposal to have shift-click so it picks 10 of each item (instead of one) to deposit/remove items from the bank.

Thank you

**Comment by IvanSkazkin** [comment]
**Good idea**

**Comment by slayorktc** [comment]
> Just a simple proposal to have shift-click so it picks 10 of each item (instead of one) to deposit/remove items from the bank.
> 
> Thank you

How would this work on mobile?

**Comment by sunfloweroglfg** [comment]
I would think you could hold down one thumb and then click with the other thumb? (so essentially 2 hands, 2 clicks to get a shift click?)

Although we could make it for PC only. Dev's choice.

**Comment by sunfloweroglfg** [comment]
I would think you could hold down one thumb and then click with the other thumb? (so essentially 2 hands, 2 clicks to get a shift click?)

Although we could make it for PC only. Dev's choice.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
