### ISSUE TITLE
Token health & Fishing & In-Game Marketplace

### ISSUE THREAD

**Issue by peakcreativetr** [sunflower-land/sunflower-land#598]
**I have some suggestions for the coin to stay healthy when it comes out;**

- To stabilize the number of players at 100.000 people. In this way, new users will buy their field from those who sell it and provide a commission income to the project from the secondary sale. And a certain percentage of it can be added to the liquidity.

- Establishing a market within the game that can be realized with in-game currency. (Sales gas fee will be paid by matic) In this way, matics purchased can stabilize the price of the coin by taking back the in-game currency.

- Applying for listing on exchanges and making advertising deals with influencers to pave the way for buying and selling coins globally. Providing the coin only for players will prevent the project from standing when liquidity runs low. Listing processes will attract more people's attention.

- I think there should be different rarities such as boats in the Fish section of the game. And the project should do this with Matic for liquidation, not in-game currency. In the following stages, people can rent their boats. There should be parcels in the fish area. A boat should be placed on each plot. Fishing should be different in terms of time and efficiency according to the rarity of the boat.

**Comment by IvanSkazkin** [comment]
> 

**Players**, on the contrary, should do everything in the game for the SFL, and not for the matic. If people don't buy the SFL coin, it will be cheap and won't bring in new players. This is the world of NFT people want to make money here.

**Comment by peakcreativetr** [comment]
> > 
> 
> **Players**, on the contrary, should do everything in the game for the SFL, and not for the matic. If people don't buy the SFL coin, it will be cheap and won't bring in new players. This is the world of NFT people want to make money here.

How do you intend to create the equivalent of the SFL? The amount of tokens people swell is more than enough for all expenses. People must have a reason to buy more tokens. The matic part is not for players; It is just a tool for the liquidity of Sfl. Creating a market place for crops only. And I argue that fees should be done with matic to contribute to the liquidity for the SFL counterpart.

**Comment by peakcreativetr** [comment]
> > 
> 
> **Players**, on the contrary, should do everything in the game for the SFL, and not for the matic. If people don't buy the SFL coin, it will be cheap and won't bring in new players. This is the world of NFT people want to make money here.

Is there any liquidity to meet this when token listing is done? How will it be provided with liquidity to prevent it from falling and to create hype?
