### ISSUE TITLE
[PROPOSAL] The Great Pumpkin

### ISSUE THREAD

**Issue by brian-man** [sunflower-land/sunflower-land#600]
Perhaps "The Great Pumpkin" should be introduced in October, with an event similar to the Easter Bunny.

Maybe you have to find various lost children or something, instead of eggs.

This wiki article is amazing BTW:
https://peanuts.fandom.com/wiki/Great_Pumpkin

**Comment by allefrodrigo** [comment]
Nice idea!

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
