### ISSUE TITLE
[Proposal] -Indroducing daily checkin 🗓️ in game

### ISSUE THREAD

**Issue by Pavan1471** [sunflower-land/sunflower-land#605]
I would like suggest this thing (daily check in) .So,that it will attract more people to the game and remains the people to open the game daily.

My opion on daily checkin 🗓️

Day 1 - 5 sunflower 🌻 seeds
Day 2 - 5 potato 🥔 seeds
Day 3 - 5 Cauliflower 🏵️ seeds
Day 4 - 1 Axe ⛏️
Day 5 - 3 🪵 wood 
Day 6 - 3 wheat 🌾 seeds
Day 7 - Mysterious box 📦 ( It includes Axes ,wheat, cauliflower,wood and one nft)

It's all my proposal only it is better to introduce this and help all the gamers and many people. who is out of SFL in there account.

**Comment by slayorktc** [comment]
I came here to create something similar but I like your idea as well. I was thinking of something like your crops start to rot or go bad after X amount of time to make sure people come back to check daily or weekly. How does something like this get voted on or moved passed proposal, then to an engineer to implement?

**Comment by adamhannigan** [comment]
@Pavan1471 Great ideas. I suggest continuing this idea under the #249 proposal

**Comment by Pavan1471** [comment]
> @Pavan1471 Great ideas. I suggest continuing this idea under the #249 proposal

Thank you Adam sir for choosing feeling really happy hope i will propose more and more.
