### ISSUE TITLE
[BUG] Viewing someones farm only shows sunflowers planted

### ISSUE THREAD

**Issue by slayorktc** [sunflower-land/sunflower-land#611]
After doing some various tests with viewing my wife's farm, I noticed that the token amounts don't update in real time or very often. Also, all garden locations only shows sunflowers not what she actually planted or even if nothing was planted in those spots. Was this intentional for some reason? Too much demand on servers to query? I have pulled down the code and been looking through it. If this part of the code needs someone to help enhance I would love to take a stab as it is in a low risk part of the code from my perspective.

**Comment by slayorktc** [comment]
After doing some more digging, I believe what the person is seeing is the last state that is synced to the chain? I was expecting to see in real time the items and how much time she has left till harvest, etc. Still doesn't explain why it would only show sunflowers planted everywhere though. It should still show what was planted at the time of syncing to chain.

**Comment by j923sneaks** [comment]
Sunflowers is shown as placeholders because the fields progress is purely offchain (on server). Post-launch the devs can give/expose those offchain data and I'll update the visit feature 😄

**Comment by ahh1539** [comment]
@j923sneaks saving that data would also increase the sync gas fees though, no? We should be cognizant of what is needed to save versus what can be read from the game server.

**Comment by j923sneaks** [comment]
I believe it's all accounted for. As @adamhannigan said in discord, sync does the mint/burn of the deltas between server and onchain states.

Also check out #442
