### ISSUE TITLE
[ART PROPOSAL] Cat and Dog animation

### ISSUE THREAD

**Issue by VadimasVP** [sunflower-land/sunflower-land#617]
Good afternoon. 
![fancy-tuxedo](https://user-images.githubusercontent.com/102822587/164229258-e4b19b53-3903-4cdc-b267-36df8233f6f7.gif)

Cat and dog animation. I hope you like it.

![Cat](https://user-images.githubusercontent.com/102822587/164232366-98943559-e045-4266-b016-834ae3c681c8.gif)
![catanim](https://user-images.githubusercontent.com/102822587/164232387-42a52b49-f256-4ec4-a2ed-84bbac0a201d.gif)

https://user-images.githubusercontent.com/102822587/164232759-49f096eb-d57b-452a-85a1-f6e7b21f66a0.mp4

**Comment by JacobSobolev** [comment]
this was implemented, the issue can be closed
