### ISSUE TITLE
[PROPOSAL] Open a mine and add adamantium mining, as well as rare material from space.

### ISSUE THREAD

**Issue by JCtapuk** [sunflower-land/sunflower-land#622]
Add a new set of crafting in the forge

# Adamantium pickaxe
- 1 Iron Pickaxe
- 1 Adamant
- 50 SFL

# Toolkit
- 5 Iron Pickaxe
- 50 SFL

PS Price can be changed to balance costs
--
Add interaction with the mine, clicking on it will open a modal window and it will opissanno the possibility of dropping 10 times in 1 campaign.
- 4 stone (40% chance)
- 3 iron (30% chance)
- 2 gold (20% chance)
- 1 adamantium (10% chance)
And the required resource **Toolkit** and will tell you that when you start mining you can't interact with the mine for a week.

When clicked it takes away your "Toolkit" and goes 7 days until the reward. After 7 days you can collect the reward for example for a hike you successfully collected
- 20 stone
- 6 iron
- 4 gold
- 1 adamantine
And you take his reward.

And the mine in the game has 2 pieces I think that's enough!!!

And also once a week or a month falls meteorite in a random point and you have to have time to break it for 5 adamantine picks to break a piece of meteorite and get the rarest material to create the rarest NFT booster + decorator.

Administrators have the right to change these ideas for the balance of the game.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
