### ISSUE TITLE
[PROPOSAL]:bad start

### ISSUE THREAD

**Issue by inasup** [sunflower-land/sunflower-land#625]
My observations after open registration on April 7th. 

Given the expectation of the release of the game, and also I watched how people received admission at an early stage (the first thousand). I got the impression that this is a good idea, especially when I was finally able to register myself on April 7th.
From my observation of the project at the moment, I see a huge imbalance that will drive the game back into a dead end.

Why will this happen?

1. You have access to first season farms that have huge balances, these farms already have a huge lead.
2. Farms that launched first in the spring in the beta test are in the lead.
3. Given the registration at the moment in 100k accounts, we already have half the amount before halving, this is very bad.
4. What is happening with the farms is just terrible. Your anti-bot system not only does not help, it literally destroys the economy. I will explain with my example. I have one account, which I played with my hands according to your recommendation, but I have to turn on VPN from time to time. My farm has been blacklisted. And there is no information when this check will end. Many owners have been blacklisted, and you yourself see this in the discord.
Unfortunately, there is no concrete information from you on what most players should do at the moment. Burn the commission - for what?
Mining a token and bringing the halving closer? Then it will be much more difficult for new players to enter than the current ones, not to mention those who have farms from the first season.

6. What I see at the moment is that you are blocking players so as not to drain the token on May 9th. But what about the time of these players, who gives the project to swing and bring it to the height again?

in the end, by May 9th, if you do not urgently solve the blocking of farms and the withdrawal of oil and gas to the opensea, you will ruin the project again. In May, the difficulty will be increased, most NFTs are not running or already sold out and hanging on dead farms. The question is, why come new players, if the old ones will say that there was a deception?

you will just lose the trust of the players again

**Comment by JacobSobolev** [comment]
I'm sorry but this is just FUDing.
also, you need to do some more research. go read the white paper once again and be more active on discord.

this game isn't a reward pool game like the others.
the liquidity will be provided by the players who have mined SFL
so "draining" the token isn't possible in the sense you think

**Comment by xiaoqiu06** [comment]
> 我很抱歉，但这只是 FUDing。 另外，你需要做更多的研究。再次阅读白皮书并在不和谐中更加活跃。
> 
> 这个游戏不像其他游戏那样是奖励池游戏。 流动性将由开采 SFL 的玩家提供， 因此在您认为的意义上“耗尽”代币是不可能的


Dear Sir. Our game needs to increase goals and costs. I have read the white paper many times. I found that after the opening of animal husbandry, there will be a problem of reaching the top again. And the obtained eggs and milk did not say how to use it, which would make the game enter a dead end. You can only continuously launch the upper layer, and the game economy of the game needs to be circulated. Here I recommend a name called (tinyworld) as a reference.

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
