### ISSUE TITLE
[QUESTION] CBT players buy everything, but OBT players are left with crumbs

### ISSUE THREAD

**Issue by IvanSkazkin** [sunflower-land/sunflower-land#628]
**Hello.**
I didn't catch if there is an NFT with a limited supply of 1000 pieces. And there were 1000 people on the CBT test. Isn't this unfair? All CBT players just buy all the stuff, and the OBT players don't get anything. They already have a T2 scarecrow and we don't even have radish pie
**The NFT limit of 1000 is very low.**
_They also had much easier farming before the halving._

They also removed resources from the first version of the game.
I think it would be fair if you gave them a limited NFT for participating in the closed beta. Instead of allowing them to be 100 times stronger than the rest of the players at the start

**Comment by adamhannigan** [comment]
Hey @IvanSkazkin Most of the items were farmed from our Sunflower Farmers prototype.

Most of the players already had those items/resources to craft from playing last year. Almost all of our closed beta testers were players from Sunflower Farmers.

**Comment by vcferro** [comment]
Hey adam, will the nfts from my other farms be transferable to my account (since I agree that a huge multi acc [maybe more than 5] can cause some damage for the future of the game)? We invested in the project before but I can't see any news about that...
Thanks man

**Comment by Dajoenie** [comment]
The only thing you could mint in CBT was the flags.  I have 3 flags for a total of 150 SFL.  Wouldn't that 150 SFL (that was SFF) being taken off the table actually help you?  The flags as pretty as they are do nothing and there are plenty left.  That 150 SFL of buying leverage......poof....gone forever.

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3
