### ISSUE TITLE
Sunflower-Land - Design System [Code + Figma]

### ISSUE THREAD

**Issue by michaeltrilford** [sunflower-land/sunflower-land#629]
Design System - Increase productivity & ensure users learn once!

## Objectives

1. Provide tooling to enable anyone the opportunity to create new assets for the game – [Figma Workspace]
2. Provide tooling to allow anyone to prototype a Sunflower-Land UI experience 
3. Document the past `Design Decisions` to discourage solving the same problem differently. This in turn increases the productivity of delivering HIGH-VALUE features to the market.

Within Figma, we will categorise and visualised the available UI. In addition to the UI, we will provide UX guidelines to help maintain consistency at scale.

---

I can lead the setup of this, along with a partner. What we would need from the founders is an Org Figma Account, and we can hopefully improve the Dev & Des experience for the community working on the game.

---

## Workspace Example

<img width="285" alt="CoverExample" src="https://user-images.githubusercontent.com/2483515/164358678-d40c84c3-4825-428c-82b7-409af15b1718.png">

<img width="1259" alt="WorkspaceExample" src="https://user-images.githubusercontent.com/2483515/164358682-5da0d598-46ea-49ff-90e5-b76f0393d825.png">

Once that is completed, we can move to a support model where we work with the founders to help maintain the system by reviewing Figma's PRs and encouraging Sunflower's best practices for building products, so the community creates the most enjoyable `Play-to-Own Crypto Farming Game`.

**Comment by danuribeiv** [comment]
Hey @michaeltrilford! I actually setup an open Figma org a few months ago. Here is the public handle: https://www.figma.com/@sunflowerland. Here is the open invite link: https://www.figma.com/team_invite/redeem/sMVUdIrfn8RbnjP1DyAmzc. Feel free to start setting up the infrastructure and templates there and we can continue to iterate.

**Comment by danuribeiv** [comment]
Also, @michaeltrilford, what's your Discord username? We can continue to chat there. I'm working on creating some more comprehensive design and contribution guidelines and I think this Figma organization could help here.

**Comment by blammas** [comment]
@danuribeiv Michael and myself are both senior creatives, we are planning on starting this from scratch, you’re welcome to contribute

**Comment by michaeltrilford** [comment]
I'm happy to iterate on the existing space, let me check it out when I can.

Is your user name `danuribeiv` on Discord?

**Comment by michaeltrilford** [comment]
We will need a paid version, is this Figma file supported by `Sunflower-Land`?

The benefit of `Paid` is we can distribute the Figma `components` via the `Assets` panel.

<img width="224" alt="Screen Shot 2022-04-21 at 2 57 14 pm" src="https://user-images.githubusercontent.com/2483515/164375246-361da631-9db9-4933-8204-d4395d187e9d.png">

**Comment by blammas** [comment]
> We will need a paid version, is this Figma file supported by `Sunflower-Land`?
> 
> The benefit of `Paid` is we can distribute the Figma `components` via the `Assets` panel.
> 
> <img alt="Screen Shot 2022-04-21 at 2 57 14 pm" width="224" src="https://user-images.githubusercontent.com/2483515/164375246-361da631-9db9-4933-8204-d4395d187e9d.png">

Gotcha, will reach out the devs

**Comment by danuribeiv** [comment]
@michaeltrilford @blammas I think we could start out using the Free plan here: https://www.figma.com/pricing/. It only allows 3 projects and 3 pages within those projects, however, it does allow unlimited collaborators which allows scalability for this open source project. The Professional or Organization plans could get quite expensive ($12 or $45 per user/month) considering this project is open source and will constantly be growing in collaborators.

Maybe in the future we could upgrade to a paid plan if the community agrees to allocate resources to it. The founders @adamhannigan @Rofrtd @spencerdezartsmith can weigh in here too.

**Comment by 0xsha1man** [comment]
I'd be happy to take on the development side of this and spearhead this forward.  That's my professional career all over again.  Though I'm used to taking photoshop files and making them a reality.  This would be amazing.  Go front-end and UX Design Documentation standards!

I am almost just about done with an accessibility guide and concerns I have noticed with the game. That was the other side of my work before I retired. As partially colorblind almost half the text in the game I can't read.  There isn't enough contrast and used to having to explain all of it to designers and stakeholders figured I'd brush that skillset off and applied it here. I should have that completed tonight actually.  Got caught up in something else last night.

**Comment by michaeltrilford** [comment]
> @michaeltrilford @blammas I think we could start out using the Free plan here: https://www.figma.com/pricing/. It only allows 3 projects and 3 pages within those projects, however, it does allow unlimited collaborators which allows scalability for this open source project. The Professional or Organization plans could get quite expensive ($12 or $45 per user/month) considering this project is open source and will constantly be growing in collaborators.
> 
> Maybe in the future we could upgrade to a paid plan if the community agrees to allocate resources to it. The founders @adamhannigan @Rofrtd @spencerdezartsmith can weigh in here too.

Hey,

- Sure thing, But what we want is an official one set up by the founders. Is that the one that was linked or is that a side-project?
- I need to double-check a few things, but 1-3 licenses are all you need. Free plans can still be used by contributors. The goal is to set up a robust system, that's what a paid plan gives. I wouldn't add editing rights to the Design System for everyone.

**Comment by michaeltrilford** [comment]
> I'd be happy to take on the development side of this and spearhead this forward. That's my professional career all over again. Though I'm used to taking photoshop files and making them a reality. This would be amazing. Go front-end and UX Design Documentation standards!
> 
> I am almost just about done with an accessibility guide and concerns I have noticed with the game. That was the other side of my work before I retired. As partially colorblind almost half the text in the game I can't read. There isn't enough contrast and used to having to explain all of it to designers and stakeholders figured I'd brush that skillset off and applied it here. I should have that completed tonight actually. Got caught up in something else last night.

I can help too, `React`, `Emotion`, `Storybook`. I maintain `Design Systems` as my day job.
