### ISSUE TITLE
[New proposal] One-click collection and seeding

### ISSUE THREAD

**Issue by Taodeli** [sunflower-land/sunflower-land#633]
Addition of a new NFT e.g. glove with the function to collect ripe vegetables with one click or to sow seeds with one click.

**Comment by brian-man** [comment]
@Taodeli How does this work when there is a crop reward (the chest UI that gives bonus seeds)?

**Comment by Taodeli** [comment]
> @Taodeli当有作物奖励（提供奖励种子的胸部 UI）时，这是如何工作的？



> @Taodeli当有奖励（提供奖励模式的UI）时，这是如何工作的？
There aren't many treasure chests, so maybe click on them one by one. Or do you have any other better suggestions

**Comment by brian-man** [comment]
Unfortunately, unless the team is ok with "glove gives auto-chest opening" (as a feature) I'm not sure there's a good option.

Aside from the chest issue, the behavior you're describing works pretty well already with double-click / double-tap.

**Comment by Taodeli** [comment]
> 

Haha, yes. I just got bored at the repetition of twenty-two clicks, so it occurred to me that perhaps a way to enhance the experience existed.

**Comment by YetiGains070** [comment]
this is not the greatest idea tbh, will only make it easier for botters to do their thing unfortunately. but i get where you come from with the proposal tho haha

**Comment by tiffanydys** [comment]
> this is not the greatest idea tbh, will only make it easier for botters to do their thing unfortunately. but i get where you come from with the proposal tho haha

I agree, this idea might bring more bot issues rather than being easier for the normal player.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
