### ISSUE TITLE
(new system tian)War system, gear manufacturing, leaderboard rewards and specific life occupations

### ISSUE THREAD

**Issue by xiaoqiu06** [sunflower-land/sunflower-land#634]
War system：A new map with various rare resources. Players can build their own armies and can form alliances。

gear manufacturing：Equipment can be divided into weapons, armor, jewelry. Players can use the resources in their farm to synthesize materials to make equipment.

leaderboard rewards：Leaderboard rewards are mainly used as incentives for players to create and upgrade their army combat power to get leaderboard token rewards.Token rewards can also be changed to create Legendary NFTs for specific materials. And the legendary NFT can improve the token production capacity or other functions

specific life occupations：A specific life role skill means that a player can choose a class, and each player can only choose one class. For example, architects and doctors. The architect has a specific function. He can help players build and upgrade buildings, while other players can only build and upgrade their own buildings and alliance fortresses by looking for players with a specific architect profession. The doctor profession is to heal the attrition of the player's army in the war. Of course, the occupation is not limited to these two. I just have this idea, so that each player can become a specific role to play an indispensable part in the Sunflower game ecology.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
