### ISSUE TITLE
[ART PROPOSAL] Cosmetic Building - Observatory

### ISSUE THREAD

**Issue by VadimasVP** [sunflower-land/sunflower-land#636]
Good evening.

Observatory
![obs](https://user-images.githubusercontent.com/102822587/164505711-14e9c03c-d141-4a7f-b689-4f8b67f7ea1e.gif)
![obs1](https://user-images.githubusercontent.com/102822587/164505724-3c9925b3-05df-4797-b540-b1ce2bdfc7cd.gif)

https://user-images.githubusercontent.com/102822587/164618140-8c231afa-4df2-464c-8c86-da1b5b49d869.mp4

Observatory with windows
![obsglass](https://user-images.githubusercontent.com/102822587/164505886-8227ae7f-fa29-4edf-9cbb-75cda4adf5fd.gif)
![obsglass1](https://user-images.githubusercontent.com/102822587/164505896-d541325e-5b49-47e2-ab3b-4d95a4d78c70.gif)

https://user-images.githubusercontent.com/102822587/164618177-2e0e563e-f1c9-4443-8ed4-62b361d560c2.mp4

Stone observatory
![obsstone](https://user-images.githubusercontent.com/102822587/164506229-77a9928e-56c4-48db-96fa-bbc9e214b7e3.gif)
![obsstone1](https://user-images.githubusercontent.com/102822587/164506243-875386c3-e1a4-4250-a753-446e9185814b.gif)

https://user-images.githubusercontent.com/102822587/164618201-3cc7feaa-40cb-421c-990d-78eb3f352616.mp4

NPC
![nostradamus](https://user-images.githubusercontent.com/102822587/164506564-098192bf-98ca-4c6b-8048-b1cc9b732adf.gif)
![nostradamus1](https://user-images.githubusercontent.com/102822587/164506575-2e418dea-86b9-48fe-96c3-b4c9948cb359.gif)

https://user-images.githubusercontent.com/102822587/164618229-b1f0e0b5-2817-442e-9e63-7a07079fb904.mp4

Have a good day.

**Comment by JacobSobolev** [comment]
@VadimasVP I suggest that you put the asset on the real scene and on an empty location

**Comment by VadimasVP** [comment]
> @VadimasVP I suggest that you put the asset on the real scene and on an empty location

Post is updated.

**Comment by Stevew00dy** [comment]
I love this - looks incredible

**Comment by wendin017** [comment]
how many materials will it take to craft?

**Comment by VadimasVP** [comment]
> how many materials will it take to craft? have any idea?

Honestly didn't think about it. But I think to craft this, you will need to use some amount of stone, wood and SFL.

**Comment by Stevew00dy** [comment]
So the idea here is that in the future - you wouldn't use RSS from sunflower land. This would be an NFT that would be minted from another game and ported into Sunflower Land. The resource gathering would happen in the other game and that would then allow them to claim this item in the game. 

On the otherside, there would also be an NFT that players could claim in the other game (a Sunflower on Mars) and for that they would need to first mint a token in this game. 

Would need to look into the details but ideally this would be the connection between two game communities and economies to open interoperability

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
