### ISSUE TITLE
[BUG] - Change the decimal handling of the Game frontend to match with the Contract.

### ISSUE THREAD

**Issue by aayusharyan** [sunflower-land/sunflower-land#637]
The contract has about 10 decimal places, (give or take) but the game UI can only handle 1. Because of which the game tries to round the number and tries to sell, resulting in insufficient crops error.

Something like this.
![image](https://user-images.githubusercontent.com/16634228/164534878-2a1b7f74-0efc-4367-96d4-ec1dfc5582fd.png)

Now, when I try to sell it, It tries to 1843.4 which obviously cannot sell because it is more than what I have. I cannot perform sell all operation.
![image](https://user-images.githubusercontent.com/16634228/164535074-213066af-ef9f-4a41-8870-eebe9c46cc14.png)

Fix -> Instead of rounding. round down to the nearest decimal and then try to sell.

Priority -> Possibility before the halving.

**Comment by brian-man** [comment]
@aayusharyan This looks like a duplicate of #632.

**Comment by aayusharyan** [comment]
@brian-man 
> Did you happen to buy or trade "externally" to the game and then sync to bring from chain into the game?
Yes, I did actually transfer 99999999 upto last digit in the decimal points and sync, that's why it was showing in game.

 > I don't think it's rounding
UI is showing perfectly fine, but when running the method to withdrawAll, that time it is rounding and 999999999 decimal something will round up which will have the comparison issue. (or Probably an issue with Decimal.js comparison?)

This doesn't seem like a Floating point problem.

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by aayusharyan** [comment]
Thanks for updating. Yeah, closing this.
