### ISSUE TITLE
[UX FEAT] Merge Sound Controls in the Audio Player

### ISSUE THREAD

**Issue by 0xsha1man** [sunflower-land/sunflower-land#642]
![image](https://user-images.githubusercontent.com/104043928/164564269-178476a4-20f3-44ac-ae26-8ac7698d4629.png)

![image](https://user-images.githubusercontent.com/104043928/164565092-220ecfe0-1a05-431b-9ec8-3aecca95a5dd.png)

OBSERVANCES

- The first button placement leads it to believe it is the volume control of the music playing. This is actually a mute toggle for everything else
- Mobile devices have it dangerously close to the other more actively used elements of the hud. Specifically the mute toggle
- The audio player slider toggle placement, due to hand placement on smaller devices, causes it to be inadvertently activated

REQUEST

- Move the mute toggle within the audio player
- Make the mute toggle button control all audio, including the music
- Move the audio player to a different hud location (menu perhaps?) or triggered with a visual radio tower on the map or radio somewhere

**Comment by Pranav-yadav** [comment]
Hey everyone!

Theres no need, as persistent volume ON/OFF settings FEAT # implements it in the settings menu option.

**Comment by 0xsha1man** [comment]
> Hey everyone!
> 
> Theres no need, as persistent volume ON/OFF settings FEAT #659 implements it in the settings menu option.

Could we move all the settings and this player into the menu as well? It'd solve the mobile issue and its placement.

**Comment by Pranav-yadav** [comment]
> Could we move all the settings and this player into the menu as well? It'd solve the mobile issue and its placement.

@0xsha1man actually Music Player needs to be more accessible than those settings. So, that a user can change the songs easily without going to that menu, as well as Play/Pause them easily and instantly. 👍

**Comment by 0xsha1man** [comment]
> > Could we move all the settings and this player into the menu as well? It'd solve the mobile issue and its placement.
> 
> @0xsha1man actually Music Player needs to be more accessible than those settings. So, that a user can change the songs easily without going to that menu, as well as Play/Pause them easily and instantly. 👍

I'll defer the topic and close this out but don't think the placement it is at now will work in the long term.  It was more a trailing thought, if one element is already moving the rest could be copied and pasted with it. Been running on too little sleep juggling stuff.  Ignore me.
