### ISSUE TITLE
[CHORE] Center align all warning text in modals revolving around sync

### ISSUE THREAD

**Issue by newb23** [sunflower-land/sunflower-land#645]
Creating a chore for myself to standardize the modal textboxes to be both, well, standard, attention grabbing, and obvious.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
