### ISSUE TITLE
[PROPOSAL] Drag-and-drop in planting seeds 🌻

### ISSUE THREAD

**Issue by alvinphoebeartemis** [sunflower-land/sunflower-land#649]
This feature was used to mitigate click bots. Instead of clicking the holes, need to drag and aim to the hole and plant seeds.

**Comment by brian-man** [comment]
Please no.  This is a great example of making the game experience suck for players.  Basically the bots win every time that is done.

**Comment by StockSavage** [comment]
No thanks.

**Comment by alvinphoebeartemis** [comment]
Oh I see because I observed this method in playing Farmville 2. Thank you.
