### ISSUE TITLE
[PROPOSAL] NFT's with Farming XP boost / Farm design upgrade nft's

### ISSUE THREAD

**Issue by FamousiksLv** [sunflower-land/sunflower-land#651]
1. I see that there is many nft's which are giving like crop profit/time boosts, but maybe there cold be nft's with xp boosts, like tier 1-3.
Tier 1  10%xp boost, Tier 2  20% xp boost, Tier 3 40% boost. And there could bee nft's for farming/tools.
2. Farm Design Decorative upgrades - I see that there is like fences, roads so there could be a upgrades which upgrades them like default is wood fence, tier 2 stone fence, tier 3 iron fence(just a idea), maybe for roads like some design updates from sand roads to stone roads. :D
3. NFT's which decrease withdraw tax - something like tier 1 -1% tax, tier 2 -2%tax, tier 3 -4%tax, maybe some nft's which lowers sync price

**Comment by MarketParticipant** [comment]
I think this is a great ideas.

**Comment by eggc95** [comment]
1. Sounds interesting to have XP boost, unless more levels are unlocked in the future this NFT will actually get traded so much around newer farms which increases trade volume = more eth for warchest

2. i would like to see some sort of design element to this game as well which makes every farm super unique but i doubt it would probable at least not for another year as many features are on the roadmap and this is not a core mechanic just a really good to have
 
3.  neutral about tax/sync reduction NFTs, too early to tell if it's necessary or good to have and whether it's easy to balance

**Comment by Aminbtdds** [comment]
Great proposal for making more demand for deco. Nfts 🍻🌻

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
