### ISSUE TITLE
[ART] Cat Tree 

### ISSUE THREAD

**Issue by Aestnelis** [sunflower-land/sunflower-land#654]
I don't want our cat Victoria to live in rooftops so here is her cat tree! Cat tree can be a decor NFT since the cat is NFT as well. So that cat owners would be happy that their cat has new bed. Putting here two version of that cat tree. Would love to get some feedbacks.
![cattreedecor](https://user-images.githubusercontent.com/98103679/164808102-685d9c4c-9bdd-40ec-97ba-91a6559581a0.gif)
![bigcattreedecor](https://user-images.githubusercontent.com/98103679/164808275-b1f2b476-fbe8-4c5d-b84d-303cbbc7e904.gif)
![bigsunflowercattreedecor](https://user-images.githubusercontent.com/98103679/164808417-75452294-60b1-4852-8a95-ff4e8aa3c94c.gif)

**Comment by Lukisu** [comment]
Meow meow <3

**Comment by AncientHorse** [comment]
I really like this one.
