### ISSUE TITLE
[ART] Sea Creatures (Fishing Arts)

### ISSUE THREAD

**Issue by AKCH1N** [sunflower-land/sunflower-land#655]
# SEA CREATURES
**Hey! These are my Sea Creatures collection, hope you like it!***
***I would like to suggest the pixel art drawings related to sea creatures and the future fishing system under this title so that they can be found more easily by developers, THANKS!***
## CRAB
![Crab x500](https://user-images.githubusercontent.com/44812103/164815293-28ce7b1c-3f08-4f8e-8f21-598faccf619a.png)               ![Crab Original](https://user-images.githubusercontent.com/44812103/164815296-09db24a0-7515-4430-bd5a-bc54344c1efc.png)
## DOLPHIN
![Dolphin x500](https://user-images.githubusercontent.com/44812103/164815322-a850ad55-65c9-4bf4-b27a-b16e3bde63e8.png)     ![Dolphin original](https://user-images.githubusercontent.com/44812103/164815330-fef1aea6-9011-418b-9beb-4c7250f07261.png)
## OCTOPUS (Animated)
![Octopus x500](https://user-images.githubusercontent.com/44812103/164815360-9ec53bbe-8e50-40b1-8639-55c29c4a7125.gif)       ![Octopus Original](https://user-images.githubusercontent.com/44812103/164815363-994a4773-e45c-47d1-b42e-2f3dd7f81a54.gif)
## SEAHORSE
![Seahorse x500](https://user-images.githubusercontent.com/44812103/164815482-19cbc639-737a-44f1-9157-89cf6073a68a.png)      ![Seahorse Original](https://user-images.githubusercontent.com/44812103/164815492-5852c615-0ced-4c5e-b167-0cf0f22eb6f8.png)
## TURTLE
![Turtle x500](https://user-images.githubusercontent.com/44812103/164815537-3693d213-77c9-4b3f-bb0d-b4e140e2917d.png)        ![Turtle original](https://user-images.githubusercontent.com/44812103/164815541-7dd335f4-2b23-4c06-8b4e-8a275053419c.png)
## WHALE
![Whale x500](https://user-images.githubusercontent.com/44812103/164815649-683ffb15-4667-4ff5-8932-a4611ab8677a.png)           ![Whale Original](https://user-images.githubusercontent.com/44812103/164815656-30b80c0c-8df9-41de-aae8-b4f20b04d1be.png)
## SHARK
![Shark x500](https://user-images.githubusercontent.com/44812103/164815720-8eed28b1-c529-42e4-9a1a-f686d48d1c99.png)          ![Shark Original](https://user-images.githubusercontent.com/44812103/164815725-cbce6db3-81c4-49c6-a8b6-8208a15d6af8.png)
## SWORDFISH
![Swordfish x500](https://user-images.githubusercontent.com/44812103/164815748-253de717-4821-4ad9-b8ee-11000f2d42a3.png)  ![Swordfish Original](https://user-images.githubusercontent.com/44812103/164815753-67682451-1e54-41eb-bd86-d89d79f95e96.png)
## ORANGE FISH
![Orange Fish x500](https://user-images.githubusercontent.com/44812103/164815791-5dbab38f-4881-4828-a549-79b447884501.png)          ![Orange Fish original](https://user-images.githubusercontent.com/44812103/164815805-6167ffb3-9125-4bcf-8f1f-76ddd7673f77.png)
## BLUE FISH
![Blue Fish x500](https://user-images.githubusercontent.com/44812103/164815875-c5cfd754-ba55-4446-aa4a-9d6cfaab1966.png)      ![Blue Fish original](https://user-images.githubusercontent.com/44812103/164815879-e5746168-d25d-4801-bb6f-bb10b584a3b8.png)

*Have a nice one!*
*0xfB33c8f8426Db534C0BA6494D4B9e824B390d658*

**Comment by Nyp-Sfl** [comment]
Starfish, one of the cutest creatures of the sea, is not forgotten when it comes to sea creatures. These cute sea creatures also have great contributions to the sea.
 Tier 1 Starfish increases the seafood production rate by 10%. 
Tier 2 Starfish, on the other hand, allows you to get 20% more seafood in addition to 10% production speed. In addition to these, Tier 3 Starfish also allows you to craft a certain amount of free fishing rods every day. 
Thanks!!!

- Tier1 Starfish (Animated)
![Sprite-0003-export](https://user-images.githubusercontent.com/104236389/164882429-50f777ea-e049-41c0-8b34-b2e4c78c319c.gif)

- Tier2 Starfish (Animated)
![son deneme](https://user-images.githubusercontent.com/104236389/164882447-720f1ae8-2df5-4c51-aeb6-4b1fb01d6364.gif)

- Tier3 Starfish
![son denemet2](https://user-images.githubusercontent.com/104236389/164882459-cc4a3e47-e93b-440d-889a-7fc5de34754d.gif)

**Comment by Nyp-Sfl** [comment]
Many examples of small and simple fish
![balık](https://user-images.githubusercontent.com/104236389/164952981-be28576c-b363-47f8-9143-47af80db78ab.png)
![balık2](https://user-images.githubusercontent.com/104236389/164952983-238f45ec-c92f-499d-a09e-6dc45f34adaf.png)
![Balık3](https://user-images.githubusercontent.com/104236389/164952985-ec4e1871-732b-43ac-b13d-619ce069a856.png)
![balık4](https://user-images.githubusercontent.com/104236389/164952986-687ee3f9-5454-47d1-8d6f-3c8147c029cd.png)
.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
