### ISSUE TITLE
[PROPOSAL] | XP Books NFTs ( more cases to burn SFL )

### ISSUE THREAD

**Issue by LeShykun** [sunflower-land/sunflower-land#657]
👨🏻‍🌾 **Hello fellow farmers** 👨🏻‍🌾, I had an idea of creating some **books** NFTs that increase the amount of xp **instantly**, these nfts can be used as consumables items that gets burned after buying and gives some **SKILL XP** after that, the supply can be 🚨 **unlimited** 🚨!

🔴 **BOOK OF THE WISE FARMER** 🔴
This one gives you +200 XP to the Farming Skill ( prices & art & xp bonus can be changed if this proposal gets approved )

![concept_00000](https://user-images.githubusercontent.com/99097146/164876240-85e6df8e-b421-4c2c-bf3e-f02648a62613.png)

🔴 **BOOK OF THE ENGINEER** 🔴

This NFT also gives +200 XP to the Tools skill

![concept_00001](https://user-images.githubusercontent.com/99097146/164876247-7d4c97d0-1cef-451f-9370-849da4624bba.png)

![farmer2](https://user-images.githubusercontent.com/99097146/164877731-882be2c5-41c4-416d-952b-d8a9a78a96f7.png)
![miner1](https://user-images.githubusercontent.com/99097146/164877733-b62125c7-4826-4a2a-ab28-4f602d8bda2e.png)

**Comment by IvanSkazkin** [comment]
**Good idea**

**Comment by DonatasDee** [comment]
The experience is there to stop whales from controlling the market in the first place.

**Comment by LeShykun** [comment]
@DonatasDee Thank u for the feedback, welp guess ur right in a way, although i don't think paying something around +500 sfl ( to upgrade both skills at max lvl ) , would be that beneficial for whales specially with the other nfts out there (can be bought on secondary market by whales aswell) that gives better improvements to the farm with almost the same sfl cost

In a way, what makes these skills talent valuable is the fact that they're not tradable ( unless someone chose to sell his farm )

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
