### ISSUE TITLE
获得了工头海狸  我希望未来可以拥有自动砍伐的功能

### ISSUE THREAD

**Issue by Give7** [sunflower-land/sunflower-land#658]
1小时成熟一颗树  我不希望 半夜还需要爬起来砍树  我希望未来可以拥有自动砍伐的功能

**Comment by owusei** [comment]
兄弟你这个是多少ETH买的

**Comment by Give7** [comment]
> 



> 兄弟你这个是多少ETH买的

自己去找玩家慢慢交易木头收集起来的

**Comment by CQJTU-Andy** [comment]
自动砍伐有悖于“非自动化”理念，如果开发自动砍伐功能，那自动收菜、自动挖矿恐怕也有需求。这种功能会加剧游戏内物品通胀，不利于游戏长远发展。

**Comment by Give7** [comment]
> 自动砍伐有悖于“非自动化”理念，如果开发自动砍伐功能，那自动收菜、自动挖矿恐怕也有需求。这种功能会加剧游戏内物品通胀，不利于游戏长远发展。

我可以接受雇佣几个小时农夫砍树  只要收益大于支出  也可以一定程度燃烧代币
