### ISSUE TITLE
[PROPOSAL] Boat in the pond ⛵

### ISSUE THREAD

**Issue by alvinphoebeartemis** [sunflower-land/sunflower-land#666]
For improvement, can we also have a boat in the lake for fishing.

**Comment by BlackFish10** [comment]
Good idea

**Comment by SrCouve** [comment]
> For improvement, can we also have a boat in the lake for fishing.

I have an art I made

![image](https://user-images.githubusercontent.com/98098233/164915882-768ed328-5767-463f-829a-bfb15552ca0e.png)

![image](https://user-images.githubusercontent.com/98098233/164915872-1ead2f4c-78d2-46fe-bd2b-85b68fc405fb.png)
![image](https://user-images.githubusercontent.com/98098233/164915887-dea7d29c-9bca-4f70-8006-a66400a275b1.png)
![image](https://user-images.githubusercontent.com/98098233/164915891-033fa4c6-0979-4e72-a0b9-92c81ce41659.png)
