### ISSUE TITLE
[ART] King Chicken!

### ISSUE THREAD

**Issue by d4nnY132** [sunflower-land/sunflower-land#667]
I think King Chiken may be useful with all animals + give some buffs like +25% eggs from default chicken.And we have Woody the Beaver which name is a reference to Steve Woody,King Chicken is a reference to ChickenCX 
![Chicken King](https://user-images.githubusercontent.com/67920456/164911459-05c49729-07ef-4807-9241-a59b57cde2e2.gif)
![Big Chicken King](https://user-images.githubusercontent.com/67920456/164911137-edb9e880-3077-4cdd-9b80-d000413e903a.gif)

**Comment by SteveChickenCX** [comment]
I Approve the design :) ♥

**Comment by d4nnY132** [comment]
UPD: King chicken on gold barrel
![Chicken King barrel](https://user-images.githubusercontent.com/67920456/164943152-1fa28119-062f-4973-868e-8adc157619a3.gif)
![Big Chicken King barrel](https://user-images.githubusercontent.com/67920456/164943155-c444981f-1a6b-47ef-92d1-8c95637beecd.gif)

**Comment by d4nnY132** [comment]
Another one:
![Chicken King coop](https://user-images.githubusercontent.com/67920456/164946382-77411bef-8515-4317-bea9-34219f2d10c9.gif)
![Big Chicken King coop](https://user-images.githubusercontent.com/67920456/164946383-7aadb1b5-d61b-489b-99df-112b1d2bc817.gif)

**Comment by tiffanydys** [comment]
Amazing art ❤️ this could be one of the `rare` nfts with a limited quantity.
Might come back to this once animals get released first. 😄

**Comment by d4nnY132** [comment]
UPD AGAIN:
![Chicken King coop](https://user-images.githubusercontent.com/67920456/164987857-9cd95540-430f-46e7-8153-9711e799a415.gif)
![Big Chicken King coop](https://user-images.githubusercontent.com/67920456/164987860-a906145b-b677-476c-9e22-afabcb850522.gif)

**Comment by Meowgikarp** [comment]
What if the golden egg has a low chance of hatching a king chicken ?!

**Comment by d4nnY132** [comment]
> What if the golden egg has a low chance of hatching a king chicken ?!

Thats great idea
