### ISSUE TITLE
OpenSea wrong descriptions/properties

### ISSUE THREAD

**Issue by CarrotSworded** [sunflower-land/sunflower-land#668]
Hi, 

As i can see in opensea the price for T2 and T3 are not the same as ingame etc..

![image](https://user-images.githubusercontent.com/104263513/164913201-c31cee2c-bb5b-4500-b317-e3519d076c2f.png)
![image](https://user-images.githubusercontent.com/104263513/164913235-d227c1cf-f03a-487e-80a2-32249d82d568.png)

This creates some frustration trough the people in discord that already grinded the materials for those.
Can you do something about it? At least adding fixed prices and boosts?

I bought the dog for example and the boost ingame is not the same as Opensea, if the dog get nerfed as my scarecrow from v1 got... the price of my NFT will have a huge down impact so this is a serious thing.

Thank you

**Comment by tiffanydys** [comment]
<img width="1240" alt="Screen Shot 2022-04-24 at 12 03 09 AM" src="https://user-images.githubusercontent.com/18549210/164913862-db8dda5b-b8e7-4952-a420-0a19dc2ae82b.png">

Checking the history of the metadata file for the apprentice beaver, it was last edited about 18 days ago.
There's a big chance that the one on OpenSea is not yet updated. I'll create a PR for this so it will be updated in OpenSea.

**Comment by SteveChickenCX** [comment]
> <img alt="Screen Shot 2022-04-24 at 12 03 09 AM" width="1240" src="https://user-images.githubusercontent.com/18549210/164913862-db8dda5b-b8e7-4952-a420-0a19dc2ae82b.png">
> 
> Checking the history of the metadata file for the apprentice beaver, it was last edited about 18 days ago. There's a big chance that the one on OpenSea is not yet updated. I'll create a PR for this so it will be updated in OpenSea.

You are the best!

Also pinged the devs about it :)

**Comment by tiffanydys** [comment]
Done. Now we wait for it to be approved 😄
PR Link: #670

**Comment by CarrotSworded** [comment]
Thank you @tiffanydys and @SteveChickenCX !

**Comment by CarrotSworded** [comment]
@tiffanydys It would be nice to update others too, like the Dog, Kuebiko etc.. They all wrong in description or boost!

**Comment by tiffanydys** [comment]
Hi @CarrotSworded it would be nice if you could list it down for me so I could check. Thanks a lot! ✌🏻😄

**Comment by CarrotSworded** [comment]
Farm Dog: 
Supply: says 100 but there are 361 total.
Cost: says 100 SFL but ingame 75 SFL.
Boost: says Herd sheep x4 faster but in OS says whool production 200%

-----

Scarecrow: 
400 Wheat
**100 SFL** > 50 SFL
**50 Wood** > No wood 
Nancy

-----

Kuebiko:
600 Wheat
100 SFL
**50 Wood** > No wood
1 Scarecrow

**Comment by franksunnyflower** [comment]
@CarrotSworded Great catch. Thanks!

**Comment by adamhannigan** [comment]
@CarrotSworded Thanks for raising this. Eagle eye! 💪

**Comment by CarrotSworded** [comment]
Some more corrections that could be made:
![image](https://user-images.githubusercontent.com/104263513/164952275-4fb8b483-a29a-43bd-bce4-378faa75c8b1.png)
![image](https://user-images.githubusercontent.com/104263513/164952377-4a690a72-3f04-4ee0-ba2a-cb2957827fe4.png)
