### ISSUE TITLE
[PROPOSAL] Truck delivery event

### ISSUE THREAD

**Issue by trinity-br** [sunflower-land/sunflower-land#669]
Hello farmers. I would like to give a suggestion that I have been thinking about for quite a long time.

This idea aims to create a ranking system for the most dedicated farmers and also attract even more attention from players within our game, in addition to offering a lot of fun and heating the economy.

My proposal is to create a system of missions and deliveries. In this proposal, a delivery truck would be created, which would appear, for example, every 12 hours (or every  other day), depending on the task to be performed. When that truck arrived, you would have some deliveries to make, for example, deliver 100 carrots+10 rocks. There would be a time limit for you to be able to deliver the truck, and when that time is up, the truck would disappear and return again in 12 hours.

This would move the game economy a lot, as players would focus on producing resources and delivering (as a burning mechanism), also the market would be very busy, as the demand for certain items would increase a lot, generating more buying and selling trade.

When you manage to delivery for the truck, you would earn a bonus and also increase your ranking of deliveries. The hardest trucks to fulfill would give + points/rewards. Upon reaching a certain level in the ranking, you could earn some nft for it. And of course, higher ranked ones would earn rarer nfts.

This ranking could have seasons, just like many other games. At the end of the season, players would be rewarded for their position and the rankings would be reset. A patent system could also be created that would be shown on your farm when visited, so everyone would know your position in the ranking. What would create more interest in the system

That's it, that's my proposal. And I believe it is a great event that would open up great possibilities within the game and could link many other tools present in Sunflower Land.

**Comment by xiaoqiu06** [comment]
非常棒.需要增加消耗

**Comment by Marcyansir** [comment]
That's a good idea.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
