### ISSUE TITLE
[PROPOSAL] 🏆 Achievements in Game 🏆

### ISSUE THREAD

**Issue by paulinhobaiano** [sunflower-land/sunflower-land#671]
**Hello gentlemen**

_Congratulations on v2 that is getting sensational in every way, together we are stronger!
My proposal is that the game add the achievements system with rewards and hall of fame to present the first 3 players who accomplished the achievements._

The achievements would be in the following format;

**"Farm 1.000 SFL "first of all" (Hall of Fame Achievement) + Reward
"Farm 3.000 SFL "first of all" (Hall of Fame Achievement) + Reward**

*Player choice reward (100 farming points, 50 crafting points or SFL)

**Level 1 Craft "500" Gold first of all! (Hall of Fame Achievement) + Reward
Level 2 Craft "2000" Gold first of all! (Hall of Fame Achievement) + Reward
Level 3,4...**

normal accomplishments

**Level 1 Harvest 1k Sunflowers (Reward)
Level 2 Harvest 5k Sunflowers (Reward)
Level 3 Harvest 10k Sunflowers (Reward)
Level 4 Harvest 20k Sunflowers (Reward)**

Market achievements

**Level 1 Trade domestically 50x**
Level 2,3,4...

The higher the level, the lower the fee for future domestic transactions that will eventually come.

NFT Achievements

**Level 1 Have 3 NFT active in your Land**
Level 2,3,4...

I will try to produce the medals for these levels.

**Comment by BanInstinct** [comment]
that's exactly what i was thinking

**Comment by TeissierYannis** [comment]
I don't know if somebody is working on it, but, I started to code this feature, and I want to make a purpose on this repository soon.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
