### ISSUE TITLE
[PROPOSAL] New Lands Release System

### ISSUE THREAD

**Issue by K0blin** [sunflower-land/sunflower-land#672]
I love the concept of everyone being able to play the game, it's really nice. With that in mind I thought of a rarity system in the main lands keeping the supply unlimited. 

A system to have scarcity and exclusivity while remaining open to everyone. 

◇ Golden Lands
♤ Iron Lands 
♡ Stone Lands
♧ Common Lands 

**◇ Golden Lands:** 
These are the 100k lands in the beta. **It has all the resources like Gold, Iron and Stone.**

All beta players will be privileged to own one of these rich lands. And it has the bonus of bringing eternal regret to anyone who tried to cheat and had a land banned. This will serve as a lesson for others.

**♤ Iron Lands:**
100,001 up to 300,000 lands.

These lands will **NOT have gold**, but they will have Iron and Stone. 

**♡ Stone Lands:**
300,001 to 1,000,000 lands

These lands will **NOT have Gold and Iron**, but will have Stone. 

**♧ Common Lands:**
Here will be the lands for those who come after the huge success of the game, these lands are unlimited. 

These will **NOT have Gold, Iron and Stone**, they will only have basic resources like crops and wood. 

**☆ Relation to Lands Expansion ☆**
That way gold, iron and stone resources would be scarce while rewarding the first players and keeping the game open to an infinite amount of players. To get more of these and other rare resources, you'll need to expand lands.

In this way, the release of new lands happens in stages, which helps to control the security of the game against multi-account and bots and favors the FOMO effect, and we are seeing this effect in practice at the moment, with people buying lands in the open sea even knowing that in a few days more will be released.

**Comment by tidalwut** [comment]
I disagree with this. Early players already have an advantage of minting the currently released NFTs and able to save up resources and SFL. If this will be implemented, new players will have a very low chance to get NFTs other than buying from the market.
