### ISSUE TITLE
[PROPOSAL] A More Realistic Climate System

### ISSUE THREAD

**Issue by Ainweb** [sunflower-land/sunflower-land#675]
I see that in the current Sunflower Land, the only variables that affect crop yield and revenue are crop maturity time and crop price after maturity, two inflexible mechanics that turn the game into a game of whack-a-mole at a set time (this becomes especially apparent when you grow sunflowers).
In reality, each plant is affected by the environment to mature at a different time, some plants like humidity, some like sunlight ...... so in the game if there are four seasons and spring, summer, autumn and winter, and each season and weather can affect the crop yield, and even in some seasons can not grow certain crops, such strategic factors will make The game becomes more interesting.
We can take six hours as a season, plant the right crops in the right season, accordingly, the maturity time of certain crops can be shortened, and crops that are not harvested in time will rot, and also, sell winter fruits in summer or summer fruits in winter, so that the reverse season sales can get more revenue ......
More importantly, I think such a mechanism would be beneficial to prevent cheating by bots and scripts, because the climate system can be random and different farms have different weather and therefore need different strategies, so this proposal could greatly increase their costs, if not completely prevent cheating.
What do you think?

**Comment by tiffanydys** [comment]
While I like this idea a lot, it's starting to sound more a lot like Stardew Valley. The last thing this game wants is to become a copycat of an already existing game. 😅

Maybe we can add separate lands in the future with different seasons for each land and we can buy those lands separately and plant seeds in them with respect to their seasons. 🤔 This might take around Q4 though as it is hard to implement.

One thing we can do right now is have the night/day feature and i think that's already being worked on by other artists. 🖼

**Comment by Marcyansir** [comment]
It's a good idea.
