### ISSUE TITLE
[PROPOSAL]in game news/announcements section(in login screen)

### ISSUE THREAD

**Issue by gokhanhoca** [sunflower-land/sunflower-land#677]
we follow the announcements and updates on discord. That works for us but it can't work for many people.

I think the in-game news-announcements section can improve the game.

You can put it on a side of the page on the login menu. It can sit on the right side. There can be sections such as news, announcements, and updates.

It's probably easy for you to implement this but it can have a big positive impact.

**Comment by Stevew00dy** [comment]
I agree this would be a good direction. To further add to this conversation I recommend the following. 

Remove the save button as people keep getting confused with save / sync. Have autosave every 30 seconds and ensure people know that. Don't have an option to manually save.

Replace Save Button with Help Button and that opens a seperate menu (to the main menu)

This menu has, Discord link, Whitepaper link, Knowledge Base link, Inbox (where we can push from discord announcements and faq) 

The inbox would act as a popup screen with a menu of recent titles on the left and when selected it would populate content on the right. 

This would keep most people in game for their support.

**Comment by Stevew00dy** [comment]
![image](https://user-images.githubusercontent.com/5225886/165006026-5f3cd227-ff55-4037-abfd-51af5faed434.png)

Very rough idea

**Comment by brian-man** [comment]
> Have autosave every 30 seconds

Already how it works. :)

**Comment by ShiningMinions** [comment]
@gokhanhoca I think this is a wonderful idea. I think focusing on the **clever** placement of information in-game as much as possible is definitely the way to go (as opposed to expecting the end-player to search it out for themselves). This would add a ton of value for both the end-player + the devs.

Just to further the brainstorming process, and just to suggest another approach, perhaps we can show a modal popup window to the player upon farm login labeled "What's New?" with a list of all new features. This modal would also have a button which would take them to "latest release" page on github if they want more information. It would only show the player this once per new update. What do you think?

**Comment by ShiningMinions** [comment]
> I agree this would be a good direction. To further add to this conversation I recommend the following.
> 
> Remove the save button as people keep getting confused with save / sync. Have autosave every 30 seconds and ensure people know that. Don't have an option to manually save.
> 
> Replace Save Button with Help Button and that opens a seperate menu (to the main menu)
> 
> This menu has, Discord link, Whitepaper link, Knowledge Base link, Inbox (where we can push from discord announcements and faq)
> 
> The inbox would act as a popup screen with a menu of recent titles on the left and when selected it would populate content on the right.
> 
> This would keep most people in game for their support.

@Stevew00dy I have a lot of thoughts and suggestions here as well. Just to keep the topic of this proposal clean, maybe let's start a new one? If you agree, please tag me on it :).

**Comment by Stevew00dy** [comment]
> > Have autosave every 30 seconds
> 
> Already how it works. :)

yes, I mean have this as the only way to save and remove the save button to reduce friction on new players struggling to understand the difference between save and sync.

**Comment by Stevew00dy** [comment]
> @gokhanhoca I think this is a wonderful idea. I think focusing on the **clever** placement of information in-game as much as possible is definitely the way to go (as opposed to expecting the end-player to search it out for themselves). This would add a ton of value for both the end-player + the devs.
> 
> Just to further the brainstorming process, and just to suggest another approach, perhaps we can show a modal popup window to the player upon farm login labeled "What's New?" with a list of all new features. This modal would also have a button which would take them to "latest release" page on github if they want more information. It would only show the player this once per new update. What do you think?

I love the idea of a popup on new updates. (also a red dot to show there is something to check on the menu) 

I think we need to avoid directing people to Github though, whilst it's amazing for people to find this - there is noise from many users and better than only contributors are aware of this / it's not too obvious to normal farmers.

**Comment by brian-man** [comment]
> > > Have autosave every 30 seconds
> > 
> > 
> > Already how it works. :)
> 
> yes, I mean have this as the only way to save and remove the save button to reduce friction on new players struggling to understand the difference between save and sync.

I think it's dangerous to remove explicit Save without making sure that all possible actions (including closing the browser) don't lose state.  Given that the latter is pretty much impossible to handle, removing an explicit Save is undesirable IMO.

A mitigation that makes it slightly less troublesome would be to have a "last saved" string in the UI near the menu and an asterisk next to it when there are actions/changes locally since the last save.

**Comment by ShiningMinions** [comment]
Quick Update: I want to see where the following PR goes first before I start coding this feature: https://github.com/sunflower-land/sunflower-land/pull/681

This is because I will be re-using code here, from that PR.

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
