### ISSUE TITLE
[Art Proposal] Tree skins 

### ISSUE THREAD

**Issue by paluras** [sunflower-land/sunflower-land#678]
I have made a small collection of different trees.
![image](https://user-images.githubusercontent.com/98059798/164973060-b9e9052a-9b48-4310-b925-dc765153710e.png)

Using the spreadsheet animation as a guide I also made them "chop-able"

https://user-images.githubusercontent.com/98059798/164973014-699404aa-3f57-4737-810e-e981c238d2ff.mp4

https://user-images.githubusercontent.com/98059798/164973140-af9d6e44-3b67-49d1-b506-f3c83752ab2c.mp4

![shake_sheet_brad](https://user-images.githubusercontent.com/98059798/164973380-654b569b-c402-4786-856e-401c388ca7f3.png)

**Comment by paluras** [comment]
![shake_sheet](https://user-images.githubusercontent.com/98059798/165245506-00786da1-4552-4356-949e-8275e64ebfe1.png)
![shake_sheet_birch](https://user-images.githubusercontent.com/98059798/165245511-744cbda1-5f7e-40d9-aff6-0e4380ab9ebe.png)
![shake_sheet_brad](https://user-images.githubusercontent.com/98059798/165245513-be389bd4-0bad-47fd-94ab-1ccc3090a7b5.png)
![shake_sheet_palm](https://user-images.githubusercontent.com/98059798/165245515-3ba78b5e-7515-4511-b25a-3bb54b6bb8da.png)
![shake_sheet_redbirch](https://user-images.githubusercontent.com/98059798/165245517-f518ac04-033a-474f-ae38-64b4657939e2.png)
![shake_sheet-export](https://user-images.githubusercontent.com/98059798/165245519-c405274a-499c-41b0-9014-b5ef5e0cee3b.png)
![Slice 1](https://user-images.githubusercontent.com/98059798/165245521-f4341edd-c819-46ca-942e-bbb4f0d1b5f1.png)
![Slice 2](https://user-images.githubusercontent.com/98059798/165245522-cadfbaf5-7b0e-41b3-b290-506c8b71db1e.png)
![Slice 3](https://user-images.githubusercontent.com/98059798/165245524-3e233365-e844-42f0-a368-e07cd4b81855.png)
![Slice 4](https://user-images.githubusercontent.com/98059798/165245526-d14d6e6c-baf9-4bea-8caa-855eecd25394.png)
![Slice 6](https://user-images.githubusercontent.com/98059798/165245528-96396ca5-9f9c-44ad-bf46-09c01be02399.png)
![Slice 7](https://user-images.githubusercontent.com/98059798/165245530-8ee227f7-b1f2-4bba-bd65-52696f7cb1b0.png)
![Slice 5](https://user-images.githubusercontent.com/98059798/165245532-c3f7d82e-5498-4d81-94a6-db8e75833d82.png)

I guess ill just leave this here.

**Comment by LeShykun** [comment]
Awesome results!

**Comment by birborbirb** [comment]
Awesome designs Paluras! A variety of trees is always wecolme! :clap:

**Comment by paluras** [comment]
> Awesome designs Paluras! A variety of trees is always wecolme! 👏

Thank you !

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
