### ISSUE TITLE
[ART PROPOSAL]Sunflower Village needs a king too, doesn't it?🌻

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#680]
Sunflower Village needs a king too, doesn't it?
![image](https://user-images.githubusercontent.com/98098233/164978841-19b58e37-7ef8-4f76-9af8-6c5516d567d6.png)
![image](https://user-images.githubusercontent.com/98098233/164978831-9b75cd40-faff-40cc-99c7-ae671aebcf84.png)

**Comment by F1rezd** [comment]
![KING t](https://user-images.githubusercontent.com/103958221/164995077-beef69a8-9a6c-49bf-af74-3785a2bbfe55.gif)
![KING bigt](https://user-images.githubusercontent.com/103958221/164995078-a0a48352-b251-4f0b-8677-1833a5c2ffe5.gif)

**Comment by SrCouve** [comment]
![KING t](https://user-images.githubusercontent.com/98098233/164995360-fc54e9aa-a0d8-4dfa-8682-a2392584d5f4.gif)
![KING bigt](https://user-images.githubusercontent.com/98098233/164995361-fff58604-880b-4cb5-bcbe-832a40b0289d.gif)

**Comment by SrCouve** [comment]
![KINGKING](https://user-images.githubusercontent.com/98098233/164998171-440ccb81-48ba-40d2-b76c-490e26016cd8.gif)
![KINGKING BIG](https://user-images.githubusercontent.com/98098233/164998172-cfe0a201-8f96-4ebd-a3e7-7ee34f7d89c8.gif)

**Comment by F1rezd** [comment]
![Final king big](https://user-images.githubusercontent.com/103958221/165005510-363c7cb1-2cda-4227-96ef-ea48bdd826a4.gif)

**Comment by SrCouve** [comment]
![Final king big](https://user-images.githubusercontent.com/98098233/165005567-bf28bab2-391b-4218-8941-fdb02d9464e2.gif)

**Comment by SteveChickenCX** [comment]
Nice! I love it!
well done :)
