### ISSUE TITLE
[PROPOSAL] Water gather speed crop boost/ Acid mutant crop chance boost

### ISSUE THREAD

**Issue by NoisyBucheron** [sunflower-land/sunflower-land#684]
Hi, 

Can we add a function for the items based in acid and water? (Acid create mutations, water help crops to grow)

For example: 

Fountain : Crops take 5% less time to grow
Farmer Bath: Crops take 10% less time to grow 
Goblin Bath: Add a 100% chance to get mutant crops

Other ideas:
Potato Statue: Potatoes grow 20% faster (Because you have the certificate to be the best potato farmer > Statue)

<3

**Comment by YetiGains070** [comment]
mutant crops are supposed to be rare so i think 100% would be a bit too much tbh, but other then that i like the idea

**Comment by JacobSobolev** [comment]
the goblin bath didn't make into the game

**Comment by NoisyBucheron** [comment]
@YetiGains070 yes but 100 in 0.01% of chance is still 0.02% (just an example) ^^
