### ISSUE TITLE
[BUG] Upgrading Skill 5 gives http 500 error

### ISSUE THREAD

**Issue by taneryurttas** [sunflower-land/sunflower-land#687]
Request URL: https://api.sunflower-land.com/autosave/{ID}
Request Method: POST
Status Code: 500 

actions: [{type: "skill.learned", skill: "Green Thumb"}]

**Comment by alvinphoebeartemis** [comment]
Hi, I think this issue is already addressed to the developers. Thank you.

**Comment by taneryurttas** [comment]
@alvinphoebeartemis  thx for the info.

**Comment by taneryurttas** [comment]
,

**Comment by taneryurttas** [comment]
Okay
