### ISSUE TITLE
[EVENT] CALL OF THE SPIRITS

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#689]
![CALL OF](https://user-images.githubusercontent.com/98098233/165044334-497f90fc-73c3-414e-afdc-b6ab9c9d9ca2.png)

To participate in the event, the beginning is similar to the easter event, you will have to craft the Rock of Spirits:
![image](https://user-images.githubusercontent.com/98098233/165654134-8842e894-c590-4709-9bdc-24ec1475be6f.png)![image](https://user-images.githubusercontent.com/98098233/165653953-3c9c4298-3323-452d-9679-28229f202810.png)![image](https://user-images.githubusercontent.com/98098233/165653981-0f1d6645-4015-4206-b1c7-649c0e23a475.png)

The Supply will also be the number of active farms, and the crafting items will be simple for any player to make:

**Rock Of Spirits:** 
  _- 5 Wood_
    _- 5 Stones_
    
After the creation of the stone, crystals of 7 different colors appear throughout the day, which can be collected with a click, basically how the egg event worked
![image](https://user-images.githubusercontent.com/98098233/165644359-57dd49eb-c132-4df7-9801-31bcf307d133.png)
![image](https://user-images.githubusercontent.com/98098233/165644247-f19f1aca-39bd-49a0-bb70-19d0fee31ac2.png)

During the event we will have available to craft 10 different Types of spirits, one of each type of harvest:
![image](https://user-images.githubusercontent.com/98098233/165641798-ede85f8a-f735-4698-b81f-39744caed4ed.png)
![image](https://user-images.githubusercontent.com/98098233/165046020-09eeb588-03fc-4d26-a674-bc0ec357cbba.png)![image](https://user-images.githubusercontent.com/98098233/165046167-f94cc362-4efc-48e9-94f5-a6bb89f32944.png)

Each spirit will have the Supply available for the event of 3, totaling 30 spirits, the Craft of each spirit will be composed of 21 
stones 3 of each color, plus a certain amount of their respective vegetable,

**Sunflower Spirit**:10000 Sunflower          
 **Potato Spirit**: 1000 Potatos  
 **Pumpkin Spirit**: 500 Pumpkins
 **Carrot Spirit**:200 Carrots 
 **Cabbage Spirit**:100 Cabbage
 **Beetroot Spirit**:50 Beetroot
 **Cauliflower Spirit**:33 Cauliflower 
 **Parsnip Spirit**:20 Parsnip
 **Radish Spirit**:15 Radish
 **Wheat Seed**:20 Wheats 
 
(The cost is 10 SFL in the current Halving or 5 in the next one, to get any amount of Crop, if the devs find it low, they can put another 0 to get 100 SFL needed or another value, I put 10 because I think it's a fair value, and any person could get it without having to buy crops in OS)

Each spirit will give a buff of 15% (Suggestion) in the amount of your vegetable harvest
Players who can't get the Spirit will be able to put 2 of each stone (14 stones) for a seven day buff of 5% of the vegetable they choose

The objective of the event is to create very rare NFTs, with function but that do not break the game, so the amount is limited, and to reward the most hardworking players, because as the stones cannot be removed from the farm, only the most dedicated players managed to get the spirits.

_the maximum supply of each spirit can reach a maximum of  6 (For devs, sweepstakes or artists) I advise that each person can only airdrop one spirit at most_

![400interact](https://user-images.githubusercontent.com/98098233/165591344-b3a37aa4-141d-494a-9d65-7a4d7e0bf2cf.gif)![Spirit interact cauli](https://user-images.githubusercontent.com/98098233/165591200-8ebe6f7b-e91f-44d5-8162-3284a167c4f8.gif)

**Comment by Killu8726** [comment]
This is a really nice idea of event, i hope it is accepted and released on the game, I just think that 10 SFL is too little price for an NFT that has so low supply

**Comment by Killu8726** [comment]
This is a really nice idea of event, i hope it is accepted and released in the game. Loved the drawings, my favorite is the sunflower spirit

**Comment by BanInstinct** [comment]
Mano, tu só faz coisa sensacional

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
