### ISSUE TITLE
[PROPOSAL] Reset your Skill 

### ISSUE THREAD

**Issue by paulinhobaiano** [sunflower-land/sunflower-land#690]
Good Morning,

As the game progresses, new strategies are implemented and the game moves in other directions without losing the objective.

Today farming is better than animals today.
But in the near future, animals may take their turn!
Many are not earning more SFL now, as they are already trying to anticipate animal production. To help with token burning and even for players to be able to change their strategy at any time in the game, we could add a function in the box to reset selected skills. And the cost would be a value of 50 SFL.
It is a considerable value and it is not low, since;

Players who have Animal Skills, are failing to earn 5% on the sale of plantations for a long time, which if not, but soon there will be 50 SFL or more, left to earn.

I'll try to do the skill reset button, if anyone can do it too, thank you.
![Screenshot_4](https://user-images.githubusercontent.com/65697347/165084725-15d361bd-afe1-4ecc-98ad-e4c4dcb4a05a.png)

**Comment by resquinelato** [comment]
I do not like this idea. The choices have to be done intelligently.

**Comment by paulinhobaiano** [comment]
> I do not like this idea. The choices have to be done intelligently.

If you choose smart, you will benefit more than who would pay to reset skills.

**Comment by resquinelato** [comment]
> > I do not like this idea. The choices have to be done intelligently.
> 
> If you choose smart, you will benefit more than who would pay to reset skills.

But the people who sacrificed the profit for the next updates will be at a disadvantage. I agree that it is a good way to burn SFL. If this is the case that increases the value for a very large amount of SFL, such as 5000. So until the Lands will be more valued at the OpenSea

**Comment by paulinhobaiano** [comment]
> > > I do not like this idea. The choices have to be done intelligently.
> > 
> > 
> > If you choose smart, you will benefit more than who would pay to reset skills.
> 
> But the people who sacrificed the profit for the next updates will be at a disadvantage. I agree that it is a good way to burn SFL. If this is the case that increases the value for a very large amount of SFL, such as 5000. So until the Lands will be more valued at the OpenSea

It has to encourage, discouraging.
I'm suspicious to talk about values, in my perception 5000 SFL is a high value because of the current skills, but it's something that can generate value in land!

**Comment by NoisyBucheron** [comment]
This could be good to burn SFL :)

**Comment by LeShykun** [comment]
maybe can rework the books i made on #657 to reset the skills? (unlimited supply)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
