### ISSUE TITLE
[PROPOSAL] Weekly Event

### ISSUE THREAD

**Issue by TJ0ta** [sunflower-land/sunflower-land#691]
Hi, I had an idea and wanted to share it with the community.
And if every week there was some kind of invasion of a group of bandits or orcs on your farm what would you do?
Would you prepare by putting together some resources to give them willingly and not be pestered or would you confront them and fight for what is yours?
 Well this is the type of event that I came here to propose, where a group would attack your farm once a week and would require some resources, whether gold and wood stones or some specific recipe if you gave them they would reward you with some decorative or some tokens , if they weren't going to invade and pick up some random farming or gathering items, then your damage could be less or greater than having fulfilled your wishes, depending on your luck.

But it doesn't end there, tired of the invasions you can hire a village guard so that the day of the invasion doesn't suffer losses, but it will cost you 2 sfl and 10 potatoes to feed the soldiers. Make your choice.

There would thus be three possible actions to start:

- Collaborate with the invaders and give what they ask for, where in return you would receive something and establish a friendship relationship.

- Not giving them what they ask for or making exchanges and thus suffering the invasion so that the losses will only be discovered after the invasion.

- hire a small team of soldiers to secure your farm.

Of course, in the future, a revenge function can also be added, where you will attack the village of those who invaded you and you can thus get some resource.

This was my idea of ​​a type of event that could exist, I hope you liked it and that you support the idea, whoever has any suggestions for changes can comment too, good ideas are always welcome.

**Comment by alvinphoebeartemis** [comment]
It looks like Clash of Clans. 👀

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
