### ISSUE TITLE
[PROPOSAL]  Fruit Trees!

### ISSUE THREAD

**Issue by Mo-Feng** [sunflower-land/sunflower-land#692]
Hi,

Big fan of farming games, shall we introduce fruit trees and fruit to this marvellous sunflower land? Could we have limited spots for fruit trees/grapevines, which in my opinion can take a considerable time to mature and yield fruits thereafter (and may turn old, having reduced output after some time, and can be cut down to produce wood.) Another interesting thing about fruits is that we can have more recipes to create secondary goods like wine and juice, goblins might want to have a glass of wine :P

Hope this idea helps.

**Comment by NoisyBucheron** [comment]
Genious!

**Comment by JCtapuk** [comment]
> Гениально! Как я не думал об этом раньше!?

I thought you already knew lol... Apple and Appleseed =)
Reminds me of an old game ....
