### ISSUE TITLE
[PROPOSAL] sell and buy number

### ISSUE THREAD

**Issue by BlackFish10** [sunflower-land/sunflower-land#693]
- i want to sell 69 from 83. why do i need to sell one by one. 

- can you guys add a bar that we can choose a number ?

![dghfn](https://user-images.githubusercontent.com/85253676/165134197-525811d9-92d7-44ea-84b0-2352d4633327.JPG)

**Comment by o6ris13** [comment]
Very good idea !

**Comment by JCtapuk** [comment]
If you get 20 likes on this post I will make an extended option to select the number of
Such as selecting 25% of total, 50% of total and 100% of total and progress with the wheel and standard 9 digit number buttons and removing the last digit

**Comment by Thimey** [comment]
@BlackFish10 / @JCtapuk - Had a stab at a solution [here](https://github.com/sunflower-land/sunflower-land/pull/703) 🙂

**Comment by JCtapuk** [comment]
> @BlackFish10 / @JCtapuk - Был удар по решению [здесь](https://github.com/sunflower-land/sunflower-land/pull/703) 🙂

Well the slider will not work well at 1000 quantities. So add a handle next to the button when you press it will open a modal window in it you can press numbers 9 buttons from your phone and many options... Well you get the idea hopefully

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
