### ISSUE TITLE
[PROPOSAL] Withdraw tokens sent by error

### ISSUE THREAD

**Issue by NoisyBucheron** [sunflower-land/sunflower-land#697]
Hi,

Is it possible to add option in the Withdraw window that send every token that is not recognized by the game into the owner wallet? Or see unrecognized tokens like items in this windows and recover them 1 by 1.
This could recover funds people send there by error.

![image](https://user-images.githubusercontent.com/104263513/165179304-be3c5681-4ba0-4596-90ec-505ec74c12e0.png)

**Comment by adamhannigan** [comment]
@NoisyBucheron If an unsupported token gets sent to the farm there is nothing that can be done. That is the good and bad of crypto.

Depending on the token, only the creator of that token may be able to transfer it from the farm address to a different address.

**Comment by brian-man** [comment]
@adamhannigan There's also an attack vector if players try withdraw tokens with "bad actor" implementations.
