### ISSUE TITLE
[ART] Wen Lambo ?

### ISSUE THREAD

**Issue by SpectralSFF** [sunflower-land/sunflower-land#698]
Hello, the team
I've been here since v1 and there were a lot of jokes around the ''wen lambo'' ''wen tractor'', so I decided to mix the two, I hope you like it!

![lambo1-removebg-preview](https://user-images.githubusercontent.com/104400124/165193957-3badb119-59ef-4b13-a9d4-2bad47989bce.png)
![lambo3 (2)](https://user-images.githubusercontent.com/104400124/165193970-e464bfca-1029-43f2-afd1-094d07dc91b2.png)
![lambo2](https://user-images.githubusercontent.com/104400124/165193991-3199ddf6-0f5e-4076-a14e-fc574bfaabc6.png)
![lambo tractor](https://user-images.githubusercontent.com/104400124/165194015-53eb3c70-a8d1-4200-963f-938904228b29.png)

**Comment by SpectralSFF** [comment]
![lambo1 (1)](https://user-images.githubusercontent.com/104400124/165831937-c2de410c-903a-4037-aac5-14e4d936aadd.png)
![lambo2 (1)](https://user-images.githubusercontent.com/104400124/165831953-a7a87c96-27c9-4ef7-a0e8-95d15aa9e39a.png)
![lambo3 (3)](https://user-images.githubusercontent.com/104400124/165831963-5b55e8b8-122c-4070-acab-9e10571c63de.png)
UPDATE

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
