### ISSUE TITLE
[PROPOSAL] SFL Truck 

### ISSUE THREAD

**Issue by Kubeki** [sunflower-land/sunflower-land#699]
Hi I would like trucks to be implemented in game.

![unnamed (1)](https://user-images.githubusercontent.com/97144878/165196680-b647a94d-bfff-48cd-bb2a-247f87bf178a.png)

Buff : Give x100 more supply when Syncing for example :) this can be interesting for someone who want to save some Matics for 

example !

**Comment by vcferro** [comment]
the matic taxes are irrelevant

**Comment by sunfloweroglfg** [comment]
I like the idea!

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
