### ISSUE TITLE
Duplicate passive miner animation for remainder of NPCs

### ISSUE THREAD

**Issue by chris-calo** [sunflower-land/sunflower-land#70]
The miner NPCs have a passive animation when standing still that gives them a bit of life. The remaining NPCs are pretty synthetic feeling in contrast. The proposed solution is to duplicate the animation of the standing miner NPCs onto the others (see below for areas of reference).

#### Example of static NPCs:

<img width="253" alt="Bildschirmfoto 2022-01-01 um 20 12 29" src="https://user-images.githubusercontent.com/3837103/147863598-b9440d10-00bd-4e07-b496-5c5986f7de5d.png">
<img width="139" alt="Bildschirmfoto 2022-01-01 um 20 12 34" src="https://user-images.githubusercontent.com/3837103/147863599-a5362e50-bb81-4851-9807-6253d6f7b940.png">

**Comment by adamhannigan** [comment]
@chris-calo Great idea! We've got a new layout at the moment and could do with some spark to the Blacksmith.

We could reach out on the artists channel to get a gif made.
