### ISSUE TITLE
The buffs from NFT should be increased to be worth mint, now multiple players are better than NFT, which is not good  

### ISSUE THREAD

**Issue by 1176517584** [sunflower-land/sunflower-land#708]
I would suggest that NFT buffs should be increased so that they are worth Mint, and players are willing to spend resources on Mint. If one NFT is not as good as 10-20 farms, or more, then some people would rather get a few more than Mint.  Because of cheap several farms can than NFT brought about by the high income, so you don't have a lot of people to enjoy mintNFT, also can't show the value of the rare NFT, hope the project will in future updates to consider, hope the game will become the future of the first block chain game, is also a loyal players want, the game is really good!

**Comment by oyz0001** [comment]
Right, NFT is not worth as much as owning more farms

**Comment by emro-chicken-union-leader** [comment]
I do agree to that issue. The incentives for building a good farm are not high enough.

**Comment by Aminbtdds** [comment]
We should consider, having multiple farms are forbidden, we should stop that, increasing NFTs buffs(specially t1,t2 ones with 1000 to 5000 supply) will result in inflation and economic imbalance.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
