### ISSUE TITLE
[IDEA] NFT Collect Mechanism 

### ISSUE THREAD

**Issue by yo121-eth** [sunflower-land/sunflower-land#709]
For the recently launched decorative NFT, the minted volume is not high, and many players complain that the income of a single account is much lower than that of illegal players with 2-3 accounts performance.

I hope that the official can introduce an NFT collection mechanism to encourage the development of single-account players, effectively increase NFT sales, and increase burning resources to resist future inflation. 

The function is as follows: The corresponding achievement title of the frame can generate when the number or combination of NFT in the farm matches. Different achievements can add different buff attributes.
like :

1 NFT= Greenhorn，        50% Mutation probability
2-5NFT= horticultural Apprenticeship，     10% more harvest
5-10 NFT= horticulturalists ，          all selling price 5% worth more
11-15 NFT= horticultural expert，    50% Mutation probability
15+ NFT=master gardener，      Generate special map effects or maintain all year spring( for future Season System Development)

The new decorative nft can also be combined with the old nft to get achievements.
like 
Goblin Crown+Nyon Statue = multiple beliefs   (You can receive missions from both factions during the war, or each mission reward increases by 10%)
Those are just a guess depending on the mechanics of war or tasks.

I hope you guys can speak up and say what you think about this` proposal`.
 
Thanks for reading, and I hope you guys have a nice day.

discord nick: TreasureGoblin.wallet#1582

**Comment by ZhangJiaRu** [comment]
That's a good idea

**Comment by gg50903** [comment]
Good idea, those NFT should truly makes one account be much better than multi-accounts that dont use resources.
And will make the decoration NFT more useful

**Comment by TrumHoo** [comment]
This is necessary

**Comment by 604174805** [comment]
Really Great idea for  NFT sustainability, and can stable the price of NFT, but it may also course some issues

**Comment by lixiaomao666** [comment]
Decorative nft is not proportional to its rarity.And empowered nft has no advantage over multi-farm players

**Comment by Unnamad** [comment]
Yes. Today's NFT single-account players don't make as much money as illegally using multiple accounts. If the price of NFT keeps falling, the use of minted NFT to relieve the selling pressure on tokens will not play its role

**Comment by dongdong-gitt** [comment]
好主意，忠实玩家将得到奖励

**Comment by Laoshi-Ferdy** [comment]
> For the recently launched decorative NFT, the minted volume is not high, and many players complain that the income of a single account is much lower than that of illegal players with 2-3 accounts performance.
> 
> I hope that the official can introduce an NFT collection mechanism to encourage the development of single-account players, effectively increase NFT sales, and increase burning resources to resist future inflation.
> 
> The function is as follows: The corresponding achievement title of the frame can generate when the number or combination of NFT in the farm matches. Different achievements can add different buff attributes. like :
> 
> 1 NFT= Greenhorn 50% Mutation probability 2-5NFT= horticultural Apprenticeship 10% more harvest 5-10 NFT= horticulturalists all selling price 5% worth more 11-15 NFT= horticultural expert 50% Mutation probability 15+ NFT=master gardener Generate special map effects or maintain all year spring( for future Season System Development)
> 
> The new decorative nft can also be combined with the old nft to get achievements. like Goblin Crown+Nyon Statue = multiple beliefs (You can receive missions from both factions during the war, or each mission reward increases by 10%) Those are just a guess depending on the mechanics of war or tasks.
> 
> I hope you guys can speak up and say what you think about this` proposal`.
> 
> Thanks for reading, and I hope you guys have a nice day.

~~~

I like this idea... With this implemented, many people will consider to hold NFT in their farm, instead focusing farming with multiple account and focus to withdraw value from the game.

Good for long term sustainability. Nice idea my friend
