### ISSUE TITLE
[PROPOSAL] - Suggestions to deal with Minting Bots

### ISSUE THREAD

**Issue by Stevew00dy** [sunflower-land/sunflower-land#711]
To help combat the bot issues with minting new farms I have the following considerations. 

1, We add a staking option to the minting contract, when farms are minted they are automatically added to the staking contract which is locked for 14 days whilst we validate that they are a genuine human player who is not breaking the TOS.

2, To play the game the NFT must be "staked" into the contract, thus if any foul play would arise that farm can be held for evaluation thus relieving the sell pressure from bad actors on 3rd party marketplaces. 

3, Increase the minting fee to 10 Matic which will help to deter bots from starting the game (Currently 1 Matic is worth the risk of getting caught) - We can enable a deposit scheme where the player, after successful access for 14 days (Login button to click) would be rewarded with a 9 Matic bonus.

4, Worst case and failing above, add KYC

**Comment by SteveChickenCX** [comment]
3. is great , I like it.

**Comment by Kubeki** [comment]
I like the first and third option this can prevent many malicious actions please @adamhannigan take this in consideration 👍

**Comment by emro-chicken-union-leader** [comment]
The 3 is great yeah.

**Comment by emro-chicken-union-leader** [comment]
But on the super long term you need kyc, otherwise the game will break.

**Comment by brian-man** [comment]
https://docs.sunflower-land.com/fundamentals/roadmap#stage-3-decentralised-protocols
> Sunflower Land was built as an open source project with the ideals of being a community driven and a decentralised project.

If this is still a goal, then the family of mechanisms under the banner of "1 account per person" and "anti-bot mitigations" needs to be re-evaluated.  Discord attachment and KYC are in direct opposition to decentralization.

If decentralization is a pillar of the long-term game direction, then the Docs should be updated to reflect that change in direction.

**Comment by brian-man** [comment]
Regarding 1, 2, and 3...

I don't know enough about the implementation to be user (and less than 5 people probably ever will), but I'm not confident any of these measures prevent "smart" bad actors from getting what they want.  Unless you lock a "security deposit" of "significant money" (1000 matic) for "a long time" (a year), smart bad actors can easily play nice for whatever the grace period is for verification and then begin bad behavior.

The longer you make the time and the cost, the "slower" the bad actors accounts will "wake up" sure.  But moving any of those sliders means you're pushing away normal people because you're not just creating a barrier to entry but rather a great wall.

**Comment by hope5151** [comment]
I saw many people still trying to multiaccounting in v2
They using fake discord accounts (not 1 but 10+ accounts) to mint farms from migration event
I really love this game and I hope team can deal with this problems

**Comment by InuBakaBo** [comment]
Yes for 1 and 3

**Comment by Aminbtdds** [comment]
I guess 1st and 3rd one is good and possible to do.

**Comment by David1983110** [comment]
I agree 1and3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
