### ISSUE TITLE
Error when harvesting eggs

### ISSUE THREAD

**Issue by shahabbasian** [sunflower-land/sunflower-land#712]
Hello
In my account (21218), the last 2 colored eggs are left, which produce an error when harvesting.

And the site needs to be refreshed again

**Comment by adamhannigan** [comment]
@shahabbasian Thanks for raising this. It has been fixed in the latest release

**Comment by shahabbasian** [comment]
@adamhannigan 

Hello
No eggs have been found on my land since that day

Has there been a change in the egg display process or is there a problem?
