### ISSUE TITLE
[IDEA]Increase the consumption of materials and SFI, the era of great sailing is coming

### ISSUE THREAD

**Issue by xiaoqiu06** [sunflower-land/sunflower-land#713]
# #**The advent of the age of sailing**

The game can open a new map. Ocean map. And this map doesn't need to be too complicated, it just needs to have a channel to display a snake shape on the map, and each channel has a level.

Map Cases: Here are just some similar maps I searched online.

How to obtain NFT ships: Players need to consume SFL to open the blind box, which randomly generates ships of different colors and rarities

[](url)
![杭1](https://user-images.githubusercontent.com/72883820/165481495-1d3d7d03-57c9-4f74-8da6-1ef2e1eed8d3.png)
![杭2](https://user-images.githubusercontent.com/72883820/165481559-9805d775-1423-464e-8432-12bcde6e1772.png)

These two maps are my small ideas for the era of sunflower sailing. Let me talk about the specific ideas.

Merchant shipbuilding: divided into escort ships and transport ships

NFT - Ship Level = Level 1-10
Escort ships have attributes: blood-attack-defense
Merchant ship: blood-defense-carrying capacity (how many items can be put)

NFT Color: White (n) Green (R) Blue (SR) Purple (ssr) Orange (SSSR)

Rare materials brought back by merchant ships here can upgrade our army of goblins and sunflowers.

Remarks: NFT cards of different colors. His basic attributes are different. And the rarity of the materials collected by the commercial transportation is also different. 
It needs to be remarked here: the commercial transportation is divided into 2 times, going and going back. The carrying capacity of the commercial ship going to the NFT determines how many commodities can be brought for trade at one time. When returning to the base camp, the level of the NFT and the color of the card determine the rarity of the collected materials.

Upgrading of NFT cards
Upgrading of NFT cards: Here I hope that the cards that all of us open have their value regardless of the level. For example, when my SSR and SSSR are upgraded, they also need to add cards with low N card levels to upgrade and synthesize them.

N-card upgrade requires N-level cards
R-card upgrade requires R-level cards
SR card upgrade needs to add R+SR. In order to reflect the cost-effectiveness of SR, we can add R+SR when upgrading 1-10. Let the SR card upgrade cost slightly higher than R, but not too much.SSR and SSSR need to add N+R+SR cards to upgrade. Of course, at different levels, SSR and SSSR also need to be added.

Durability of frigates and merchant ships: What I am explaining here is that our ships have durability, and the durability is mainly to consume the sfl token: players can recharge or use planting materials to exchange for a certain kind of crystal, The main purpose of this crystal is to repair ships. As the level increases, the more crystals the player consumes, the more SFL is consumed.

Shipping cycle: To put it simply here, shipping reaches the top priority for a maximum of 3 days at a time, and here we can add one kind of NFT: seafarers. The function of the seafarer is to shorten the cycle by up to a factor of two. Of course, we can also add more sailor NFTs, and its NFT shortening cycle is also high and low, so that more players are willing to cast it.

Leaderboard system: Our leaderboard can be set to 4 types: 1: The type and number of NFTs held. 2: The longest shipping distance. 3: Goblin and Sunflower War 4: Consumption.

This ranking can be rewarded: such as SFL.

Why do you need to join the leaderboard? Mainly for those players who want to invest, give them a goal, what level they can achieve, and what kind of rewards they can get so that they can be motivated.

Here our games can be divided into two types: consumer players and life players. Our game needs to satisfy these two groups of people, and our game will have a long life. Here are some of my ideas for the sunflower game, I hope the founding team can see it

**Comment by wuxie1993** [comment]
niubi!!! 简直太棒了小秋

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
