### ISSUE TITLE
[PROPOSAL] Robot in the Goblin war

### ISSUE THREAD

**Issue by brian-man** [sunflower-land/sunflower-land#717]
Small proposal to consider:
If there's ever a "peace agreement" type situation out of the Goblin war, include a "bad actor" robot entity in the storyline and add a time-limited craftable NFT that depicts a robot being either jailed or attacked by representatives from both sides of the war.

In case it's not obvious: This is a not-so-subtle nod to the Anti-Bot efforts in SFL.

**Comment by adamhannigan** [comment]
@brian-man Definitely where we see this game going.

The bot situation is an on going war, they will essentially become a part of the game and we will incorporate some game design around them ;)

**Comment by Girish143566** [comment]
![Screenshot_2022-04-28-13-50-04-70_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/70050875/165724610-8189636f-5aec-4d21-b3b0-7e7d415aada4.jpg)
I bought blacklisted land by mistake what can I do know

**Comment by Girish143566** [comment]
I bought blacklisted land by mistake so please remove Blacklisted because I
will farming all time

Farm Number - #70944
Wallet address - 0x4B6DD037952fDb4Bcae6A866c27b456f5520E6AC
Transaction ID
- 0xf6ee5cb883c13560fab443ba1cf562a9eeba566ae2ad491934efafc476cb273f

**Comment by Girish143566** [comment]
I bought blacklisted land by mistake please remove Blackliste I will
farming all time
My farm all contacts
Farm Number - #70944
Wallet address - 0x4B6DD037952fDb4Bcae6A866c27b456f5520E6AC
Transaction ID
- 0xf6ee5cb883c13560fab443ba1cf562a9eeba566ae2ad491934efafc476cb273f

**Comment by Girish143566** [comment]
I bought blacklisted land by mistake please remove Blackliste I will
farming all time so please help me

My farm all contacts ID
Farm Number - #70944
Wallet address - 0x4B6DD037952fDb4Bcae6A866c27b456f5520E6AC
Transaction ID
- 0xf6ee5cb883c13560fab443ba1cf562a9eeba566ae2ad491934efafc476cb273f

**Comment by Girish143566** [comment]
Farm Number - #70944

Wallet address - 0x4B6DD037952fDb4Bcae6A866c27b456f5520E6AC

Transaction ID
- 0xf6ee5cb883c13560fab443ba1cf562a9eeba566ae2ad491934efafc476cb273f

Sir kindly help me Remove the Blacklisted because

I bought blacklisted land by mistake But I just bought a land.  They are
also blacklisted. Sir, I want to do a lot in this land.  I will never do
anything wrong

**Comment by brian-man** [comment]
@Girish143566 Please stop spamming github with unrelated-to-development things.  This is not the right use of github for basically any project that exists.
