### ISSUE TITLE
[PROPOSAL] Golem NFT

### ISSUE THREAD

**Issue by cargomesplay** [sunflower-land/sunflower-land#719]
Portugues
Ter um Golem no jogo no estilo do esquilo
Pequeno Golem = Aumente a colheita de pedras em 20%
Golem = Aumente a colheita de Ferro em 20%
Antigo Golem = Aumente a colheita de Ouro em 20% e quebre pedra sem precisar de picareta

Ingles
Have a squirrel-style Golem in the game
Little Golem = Increase stone harvesting by 20%
Golem = Increase Iron harvest by 20%
Ancient Golem = Increase Gold harvest by 20% and break stone without needing a pickaxe

![GOLEM-baby](https://user-images.githubusercontent.com/104114336/165661239-2087341e-8598-4834-9979-8c2868eefab5.png)
![GOLEM-baby-big](https://user-images.githubusercontent.com/104114336/165659886-9e8dd17f-b714-4d3a-a391-251955756d54.png)
![GOLEM](https://user-images.githubusercontent.com/104114336/165659884-42e0fd97-b7f4-4ef7-84d5-1c2e8f82daeb.png)
![GOLEM-big](https://user-images.githubusercontent.com/104114336/165659888-b88f28ed-9c6d-4caf-a33b-8f7fa09b8450.png)
![GOLEM-OLD](https://user-images.githubusercontent.com/104114336/165659891-fc8ef87c-8f6a-4d1c-be3f-93edb2bf04db.png)
![GOLEM-OLD-BIG](https://user-images.githubusercontent.com/104114336/165659892-eeb1f264-d034-40f0-9c57-d9321c7433ce.png)

![aplicacao](https://user-images.githubusercontent.com/104114336/165660759-d4d0f67f-7b22-474e-bd0c-83ccdbd92f22.png)

Wallet metamask: 0xf06a69aCa1BB0182F1D1CB188E052A8FB1C71295
wallet game: 0xb0E023545A38F10b6C787f37648695137aD94A91
discord nick: carloshq#3347

**Comment by adamhannigan** [comment]
Eu gostei o Ancient Golem 👏 

One small suggestion is to add thin border shadows to the bottom of these characters.

Right now we are holding off on new NFTs as they will be submitted through the community competitions. It is quite hard to manage submissions outside of these competitions.

**Comment by adamhannigan** [comment]
Could you please post it here: https://github.com/sunflower-land/sunflower-land/issues/734

**Comment by cargomesplay** [comment]
> Could you please post it here: #734

yes i will be there =)
