### ISSUE TITLE
[PROPOSAL] Bakery NFT

### ISSUE THREAD

**Issue by m1dnam** [sunflower-land/sunflower-land#721]
I suggest you guys to add a bakery building as an NFT to cook bread. Bread would be used to feed your farmer, hunger system would have 5 points and it would decrease 1 point each day, if you reach 0 points you’d still be able to farm but it would take longer to grow crops.

**Comment by adamhannigan** [comment]
Bread is on the roadmap! You will be able to use wheat + eggs ;)
