### ISSUE TITLE
Halvening not applied at the craft items and barn?

### ISSUE THREAD

**Issue by aayusharyan** [sunflower-land/sunflower-land#724]
Is it intentional or an oversight that halvening is not applied on the craft items (such as axes) and the barn animals. (Chicken)?

I believe not halving the prices for that would bring imbalance as it becomes more difficult to craft those items and the gap between players who have unclocked and are using axes and animals v/s who are yet to will become incresengily more over time.

Any thoughts?

**Comment by adamhannigan** [comment]
@aayusharyan This is currently intentional. Those items can actually be fractionalized. This means that in the future you would buy 0.1 axes to cut 0.1 wood. This helps reduce the inflation on the derived resources (eggs, wood, stone etc.) 😄
