### ISSUE TITLE
[IDEA] an Alternative game mechanic for Bees and honey PR

### ISSUE THREAD

**Issue by SteveChickenCX** [sunflower-land/sunflower-land#725]
After reading the PR here: https://github.com/sunflower-land/sunflower-land/pull/706

I have got an idea to break the cycle of plant, harvest, collect.

**therefore I propose a change**

### Bees can fly

after buying some bees you could send the bees to different flowers across the map to gather resources.

**Which flowers you ask?**

we can ask the artist to create some flowers designs that will be randomly spawned across the map:

**lets assume we create 5 different flowers:**

Red - increase the gain of honey by X%
Blue- reduce the flying time after gathering the honey by X%
Yellow- give the bees a chance to fly to another flower before returning
Golden- small chance X% to gain another bee when returning (RARE FLOWER)
White- double the honey gain (RARE FLOWER)

the more flowers the better, we could actually create some fun mechanism here  (by introducing plenty of flowers), that will be much more gamified and much less subjective to botting.

**Rules**

- every 12-48 hours a new set of flowers will be spawned (X flowers at a time) randomly across the map.

-  the player can send out bees to each the flower that he wants, there will be a "flying" distance that the bees need to fly (back and forth) and this will be the cooldown of that bee group.

- the more bees you have the more bees you can send out, it can also be possible to send more bees to a certain flower and increase its effectiveness.

**To feed or not to feed**

we could use the "flying time" as the limiting factor or\ or and add a feeding factor too.

another idea is to make "special plot lands" that are only usable to grow barn food (other than wheat) giving everyone a chance to play the bee game!

rambled enough, But I hope to see more varied gameplay options :)

in coding aspect, we already have randomized function that pop up different items (from the easter event)
calculating distance between points and factoring it into flying time is easy.
Random logic of spawning and random effects is easy to implement too.
bees flying animation and flowers can be filled by our great community artist !

let me know what you think :)

**Comment by eggc95** [comment]
Good and fun direction for bees mechanics! I also hope to see some kind of new gardening plots where bees get to pollinate flowers etc just like irl so they could grow some random art/deco NFTs

**Comment by xiaoqiu06** [comment]
Many ideas are good, but I haven't seen a proposal on the consumption of SFL tokens for a long time. Since I choose to issue games on the blockchain and add the concept of tokens, I don't have any profound ideas about the production and consumption of tokens. ideas and measures..

**Comment by jerryxjh** [comment]
An anti cheating measure is to add a kind of wild bees, which will fly to the farmland. If the farmer kills them by clicking with the mouse, the anti cheating measures will be triggered. For example, stop farming for five minutes for the first time, and after five minutes, the friends of the wild bees will come to look for him. If the robot kills a large number of bees continuously, they will be given a blocked account

**Comment by adamhannigan** [comment]
@SteveChickenCX Some great ideas ❤️ 

One concern around adding brand new gameplay elements is the development cost involved 😢 Ideally we want something we can prototype and iterate on top of. This implementation feels like a V2 implementation of how bees & honey could work.

We want to take the most simplest version of this idea and test whether players find it fun. For instance, could we build this with just 1 type of flower that is always in a fixed position and it would be just as fun?

Also, have you considered how this will fit into the overall economy and interact with other resources? Ideally we want to burn crops/wood while producing honey to help with the utility and inflation of the other resources

**Comment by Amon-S** [comment]
I really love Chickens Idea and i am already into the work for it,  I will develop a new branch so we can have both versions and see which one players prefer @SteveChickenCX

**Comment by SteveChickenCX** [comment]
> @SteveChickenCX Some great ideas ❤️
> 
> One concern around adding brand new gameplay elements is the development cost involved 😢 Ideally we want something we can prototype and iterate on top of. This implementation feels like a V2 implementation of how bees & honey could work.
> 
> We want to take the most simplest version of this idea and test whether players find it fun. For instance, could we build this with just 1 type of flower that is always in a fixed position and it would be just as fun?
> 
> Also, have you considered how this will fit into the overall economy and interact with other resources? Ideally we want to burn crops/wood while producing honey to help with the utility and inflation of the other resources

Hey Adam!

I don't think 1 type of flower in a fixed position will be just as fun.

Maybe we can start with 2 flowers with simple designs ( +X% honey, reduce speed by Y%) and just a pool of 20 locations with different distances from the starting point.
spawn around 5 flowers each 24 hours

"Also, have you considered how this will fit into the overall economy and interact with other resources? Ideally we want to burn crops/wood while producing honey to help with the utility and inflation of the other resources"

we can use sunflowers or any other crop that fit to "pay" for sending the bees and we can also use other crop to respawn the 5 flowers at different locations if we need more burning mechanism.

**Comment by adamhannigan** [comment]
@SteveChickenCX If the MVP doesn't prove fun, we may need to redefine the approach we take.

If the moving around part is fun, could we explore this in a different (but technically simpler way). An example is that the bees are just in random locations when you load the page, you need to find them and click on them to return them to their main position.



In terms of using crops, we will want a high level crop to be the requirement for bees. This ensures that a player has reached a certain crop level + is investing time from high level crops. Right now we have Radish + Parsnips + Wheat which are 12 hours+. I'm not sure if bees like these items 😅

**Comment by SteveChickenCX** [comment]
> @SteveChickenCX If the MVP doesn't prove fun, we may need to redefine the approach we take.
> 
> If the moving around part is fun, could we explore this in a different (but technically simpler way). An example is that the bees are just in random locations when you load the page, you need to find them and click on them to return them to their main position.
> 
> In terms of using crops, we will want a high level crop to be the requirement for bees. This ensures that a player has reached a certain crop level + is investing time from high level crops. Right now we have Radish + Parsnips + Wheat which are 12 hours+. I'm not sure if bees like these items 😅

I mean the fun part is the randomness, the fun feeling you get when you are bless by RNGesus.
we can start with bees in random locations but play around with randomization when spawning them for the MVP

bees don't really like parsnips wheat and Radish as far as I'm aware of.

what about another seed that will be unlocked with wheat, a flower seed with no selling values , let it use 2 plots if possible .
