### ISSUE TITLE
[PROPOSAL] Tap twice to get back to the farm on mobile

### ISSUE THREAD

**Issue by Bold-maverick** [sunflower-land/sunflower-land#726]
It would be great if we can tab twice and get back to the farm on the mobile version, just like with the space on the desktop version. Sometimes we wander far from home! 😅

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
