### ISSUE TITLE
[CONCEPT] Band Stand

### ISSUE THREAD

**Issue by Stevew00dy** [sunflower-land/sunflower-land#727]
The concept here is to create a building that will act as the hub for all in game music (that connects to the music player)

Like a shop the band stand would allow users to purchase NFTs of all in game music created by the community. 

The music player would start with one song (willow tree) and to add more songs to be able to play - they would first need to purchase them. If they took the NFT away from their farm to transfer or sell - they would no longer be able to listen to it in game. 

There could be different versions of this building that starts with one person (drums) and then add other instruments as more NFT's are created (like band stand levels) At max level, it could get an in game animation to help drive attention to purchase them.

Suggestions are to start with Romys playlist and then open this to the wider community.

**Comment by Z1kou** [comment]
We Already got that covered 😎

**Comment by Z1kou** [comment]
Check out #728

**Comment by Stevew00dy** [comment]
#728 https://github.com/sunflower-land/sunflower-land/issues/728
