### ISSUE TITLE
[IDEA] AN EVENT, A BANTER STAGE, AND MillionOnMars COLLABORATION

### ISSUE THREAD

**Issue by Z1kou** [sunflower-land/sunflower-land#728]
### **Stage Event and MoM Collaboration Proposal**
---

Hello everyone, I am here to present to you the work we have been cooking behind the scenes, Me and a beautiful team that i got to recruit got together and decided we will be making greatness, PS to the boys: ( IT FEELS WE ARE A FAMILY NOW AND I LOVE ALL OF YOU ❤️ ), We have been working on alot of different features on the game and so we have alot to unfold here, lets start !
### **Musical Stage Event**

https://user-images.githubusercontent.com/98262339/165874084-4ff1f0cc-0984-425b-9e3c-650e87ac4b88.mp4

**Purpose**: Banter Stage that will serve as celebration for the official launch of SFL. It includes Romy's NPC singing on stage , a crowd of lovely goblins and farmers cheering, beautiful fireworks, and the Devs in their sprite form wandering around. (And no, sadly we can't have Rick Astley's songs in the game 😢 )

**Mechanic**: 

- The stage will play original songs made by Romy and several members of the community. Later down the line, we plan on proposing the stage as a separate NFT that will act as the mechanic that plays music made from members of the community, we can also include the idea of making separate "Music Discs" per music, as mentioned in #727 . 
- When clicking on the dev sprites, each will display a short message directly from the team themselves. This provides a way for the Devs to show their appreciation and thanks in a unique way in-game 😄 
- Fireworks with different animations will go off to celebrate the game's official launch! 

**Status:**
- 90% complete. UI, SFX and some Coding left.

---

### **MillionOnMars Collaboration Proposal**

![Mars TELESCOPE VIEW](https://user-images.githubusercontent.com/98262339/165875191-3a381606-808d-4dcb-a769-56992dc5bbab.png)
![MELONDUSK WITH HIS BILLION DOLLARS MATERIAL](https://user-images.githubusercontent.com/98262339/165875198-d1b7693b-33ba-453c-acaa-b77942a22c78.gif)

We have worked on doing our own iteration of the MoM collaboration. Still a WIP. 

**Purpose:** To create a unique method of connecting two separate games and providing a foundation for the collaboration. 

**Mechanic:** 
- The telescope will allow you to view the planet Mars inside SFL 👀 We could also add a way to go to a docs of the collab when you click on the logo in the future !
- A character that is inspired from Leon Dusk from MoM: Melon Dusk. He is a cute melon-headed entrepreneur of the newly established FarmX company. He is planning on linking farming between earth and mars ! (or maybe buy both the planets who knows 👀 ). He will be interactable and will have a message fitting his personality when clicking him (We may leave the MoM team to decide on what message will be displayed.)

---
### **Contributors**

An honorable Mention to @Aestnelis for giving us permission to Animate/use the team's assets she created !

These are small previews of what we made, this work represents a few weeks of our hustle on something we believe on.

I want to thank the team whome I am working with for believing in what we are creating and believing in our potential, From that first message when I contacted you guys to be part of what we have, I would have never thought it will be as much of an amazing experience that it turned out to be, it is an honor to work with: @amon and @๛MG『Λlpha | AME who are the lovely developers of the team , @AetherZapdos | ≽(◕ ᴗ ◕)≼ & @Vergel who are amazing artists and I am so much amazed by their work every day , @rigale & @RadishPies Who makes us hear their amazing music , I am honored to be able to call us a team and a family, To everyone who is reading this, This is only the start! we will put our heart and soul to bring out some amazing features to the game we all love ❤️ !

A special thanks goes to @amon for being the first one to believe in the project a few months and helped me by giving me confidence in my work, My brother thank you !

---
### **Last Notes: **

This is a part of a much larger project that we're developing on the sidelines. The stage acts as STEP 1 to the whole project - an introduction. STEP 2 involves the devs coming back to tell the tale of a particular legend, which delves deep more into the game's lore. #409 and #456 will be in the latter part, but we won't get too deep into it since it'll be worked on much later 😃

**Comment by SteveChickenCX** [comment]
you guys are crazy!
I love to see the work and effort you put into these proposals.
Do I have a pixelated character too ??

**Comment by Z1kou** [comment]
@SteveChickenCX  Well your character was designed by @Aetherzapdos who is also part of this, How can we not include our favorite chicken 🤗 , PS: their might be a surprise for you when its out 😏

**Comment by SteveChickenCX** [comment]
> @SteveChickenCX Well your character was designed by @Aetherzapdos who is also part of this so absolutely !, How can we not include our favorite chicken 🤗 , PS: their might be a surprise for you when its out 😏

YES!!! ♥

I'm a fan of events, I think events in crypto games are even better than events in MMORPG from items-NFT  scarcity perspective

**Comment by Netherzapdos** [comment]
A pleasure to work with all of you ❤️ Props to Vergel for thinking up of the original concept, and absolutely awesome work from everyone else. This was just a humble idea that ended up being much more than what it intended to be 🎉
