### ISSUE TITLE
[ART] Goblin Town 

### ISSUE THREAD

**Issue by birborbirb** [sunflower-land/sunflower-land#729]
**Description**

Use this issue to share any goblin related designs you think might fit a goblin town. 
Since this is not an NFT, we can use the base asset pack from Sunny Side. 

**Requirements**

- The artwork must be original and designed by yourself or from the base asset pack from Sunny Side only.
- Please upload the minified and maximised version of your art with an example of it on the Sunflower Land Map

**Art Requests**

:white_check_mark: - You still can submit designs for these art requests even if there's this check mark. It's for organization purposes only.

- Goblin Town map :white_check_mark: 
- Goblin Bank :white_check_mark: 
- Goblin Blacksmith :white_check_mark: 
- Goblin Farmer :white_check_mark: 
- Goblin Barn Manager :white_check_mark: 
- Goblin Tailor :white_check_mark: 
- Wishing Well :white_check_mark: 
- Map decorations :white_check_mark: 

**Important Links**

Proposal: https://github.com/sunflower-land/sunflower-land/issues/710
Contributing guide: https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

Let's make it a fun task and always remember to be respectful to others. 💪

**Comment by SrCouve** [comment]
![ulti](https://user-images.githubusercontent.com/98098233/165841929-5611d504-9fe2-47d1-a1c8-4553a93ff2af.gif)
![ultibig](https://user-images.githubusercontent.com/98098233/165841937-2d02a00c-f5f0-46b5-9e0d-ce725e367d4f.gif)

**Comment by YetiGains070** [comment]
throne for the King Goblin!
Goblin Fishing Hut

**Comment by sfwhat** [comment]
**_Goblin Bank_**

![pixil-frame-0 (53) (7)](https://user-images.githubusercontent.com/95937808/165872823-0215f7d3-7837-4e75-bef7-12ec2022d1ab.gif)  ![pixil-frame-0 (53) (6)](https://user-images.githubusercontent.com/95937808/165872826-58c971f9-29e4-43ed-bb63-2027930ee2c3.gif)

**_The Aviator Goblin_**
![arkaplansunfl (8) (1) (1)](https://user-images.githubusercontent.com/95937808/165872978-74ebc268-eb5c-4775-9c63-47fc13c64185.gif)  ![arkaplansunfl (8) (1)](https://user-images.githubusercontent.com/95937808/165873011-7e16b846-2897-467e-846e-9499a515ff4e.gif)


Farm ID: 6127
@strugwhat (Twitter)

**Comment by Netherzapdos** [comment]
### **Master Blacksmith and his Apprentice**
---

So this just started as an idea of a goblin jumping up and down on the furnace bellow (the thing that pumps air into the fire) and was just testing it, and I really liked how the animation came out, so just decided to build an entire blacksmith area with a lot of personality 😋 

I humbly present Colborn the Master Blacksmith of Goblin Town, and his new apprentice, Arvid.

![Blacksmith Preview](https://user-images.githubusercontent.com/101855553/165875937-12c8e5ed-8cbb-457c-8ffc-79b2b060aa53.png)
![Blacksmith Preview Animated](https://user-images.githubusercontent.com/101855553/165875945-fd86a74d-dd68-40e5-8403-95abee7c384f.gif)

Still working it out but wanted to share my progress so far so I can alter things appropriately from feedback 😋

**Comment by VadimasVP** [comment]
![npcblacksmth](https://user-images.githubusercontent.com/102822587/165899971-5d85faad-b5a6-40d9-8e90-e54e01d8ad39.gif)
![npcblacksmthbig](https://user-images.githubusercontent.com/102822587/165900004-2987b94b-c10e-4609-b0c1-f00009eb69ed.gif)

**Comment by Netherzapdos** [comment]
Tribe/Town Banners
---
Just throwing an idea. Perhaps we can try throwing in some banners around the map if goblin town is going for a "tribe" look.

![Banners previews](https://user-images.githubusercontent.com/101855553/166097586-e0382f08-1ca8-4071-a7d2-09177671fb0d.png)

Raw assets here if anyone wants to try them. 
![War Banner 2 Raw2](https://user-images.githubusercontent.com/101855553/166097595-c5fd9d3a-c91b-4758-a614-88b2ee98ed1e.png) ![War Banner 2 Raw1](https://user-images.githubusercontent.com/101855553/166097593-6fec0ca2-ef34-49cc-b42a-9597523fab59.png)

**Comment by paluras** [comment]
> ## Tribe/Town Banners
> Just throwing an idea. Perhaps we can try throwing in some banners around the map if goblin town is going for a "tribe" look.
> 
> ![Banners previews](https://user-images.githubusercontent.com/101855553/166097586-e0382f08-1ca8-4071-a7d2-09177671fb0d.png)
> 
> Raw assets here if anyone wants to try them. ![War Banner 2 Raw2](https://user-images.githubusercontent.com/101855553/166097595-c5fd9d3a-c91b-4758-a614-88b2ee98ed1e.png) ![War Banner 2 Raw1](https://user-images.githubusercontent.com/101855553/166097593-6fec0ca2-ef34-49cc-b42a-9597523fab59.png)


  @Netherzapdos 
![flag](https://user-images.githubusercontent.com/98059798/166098481-4df2e07c-a904-4883-8db9-9a8c00d830dc.gif)
![flag1](https://user-images.githubusercontent.com/98059798/166098482-b662f5f1-0523-4a1c-b6c7-6b194085d99e.gif)

**Comment by Netherzapdos** [comment]
> > ## Tribe/Town Banners
> > Just throwing an idea. Perhaps we can try throwing in some banners around the map if goblin town is going for a "tribe" look.
> > ![Banners previews](https://user-images.githubusercontent.com/101855553/166097586-e0382f08-1ca8-4071-a7d2-09177671fb0d.png)
> > Raw assets here if anyone wants to try them. ![War Banner 2 Raw2](https://user-images.githubusercontent.com/101855553/166097595-c5fd9d3a-c91b-4758-a614-88b2ee98ed1e.png) ![War Banner 2 Raw1](https://user-images.githubusercontent.com/101855553/166097593-6fec0ca2-ef34-49cc-b42a-9597523fab59.png)
> 
> @Netherzapdos ![flag](https://user-images.githubusercontent.com/98059798/166098481-4df2e07c-a904-4883-8db9-9a8c00d830dc.gif) ![flag1](https://user-images.githubusercontent.com/98059798/166098482-b662f5f1-0523-4a1c-b6c7-6b194085d99e.gif)

Yo that is buttery smooth 🔥

**Comment by Driftingwood** [comment]
I was already working on this and had it posted in discord I will post my progress here as well.
![gobsssss](https://user-images.githubusercontent.com/25971765/166159341-86dea51e-86a2-4ec6-9edb-37001772c290.PNG)

**Comment by birborbirb** [comment]
Awesome designs everybody! I'm trying each of them on map. Really nice work :muscle:

**Comment by birborbirb** [comment]
Map decorations from AetherZapdos | ≽(◕ ᴗ ◕)≼#5017

![image](https://user-images.githubusercontent.com/104516639/166453770-21f245b8-4954-4ed4-bf3c-0b830ac5501d.png)
![image](https://user-images.githubusercontent.com/104516639/166453809-a3a7e9d9-dd15-4014-9ad9-321d0bccaf3c.png)
![image](https://user-images.githubusercontent.com/104516639/166453873-d554f17b-fe8f-431b-829b-0deb77b6cc2b.png)

**Comment by birborbirb** [comment]
Building design from Driftingwood#2908 on Discord
https://discord.com/channels/880987707214544966/929855792293773382/966087369944105020
![image](https://user-images.githubusercontent.com/104516639/166455168-83bd65cd-d1e3-4e53-961e-533607974885.png)

**Comment by birborbirb** [comment]
Goblin Npcs from vp#8785

![image](https://user-images.githubusercontent.com/104516639/166458532-69d8e900-8329-444d-a204-d66f2def61a1.png)

**Comment by paluras** [comment]
More deco.
![image](https://user-images.githubusercontent.com/98059798/166467209-2e91711e-94f7-46e0-8cd7-48ada191b3be.png)
![Sprite-0008](https://user-images.githubusercontent.com/98059798/166467553-f7c988b4-1e0c-49f0-a196-bac8afa06359.png)
![Sprite-0010](https://user-images.githubusercontent.com/98059798/166467556-0448072d-3d55-4f54-8350-ba63da5f0aec.png)

**Comment by FarmerKuenster** [comment]
Goblin wishing well! made to match the current SFL one. 

![wishing-well copy](https://user-images.githubusercontent.com/104322749/166610744-61093cf8-7202-4360-bece-9894f809dfd6.png)

![wishing-well large](https://user-images.githubusercontent.com/104322749/166610911-1589f7f7-fd63-4647-9727-185a191d9a70.png)


![sfl-goblin-wishing-well](https://user-images.githubusercontent.com/104322749/166610727-f5a2b090-f886-480e-a0e6-fdaa905c2bbd.png)

**Comment by VadimasVP** [comment]
Goblin wishing well.
![goblinwishingwell](https://user-images.githubusercontent.com/102822587/166636330-b5af300a-0aeb-44dd-85e7-3456e0be0ac4.png)


![goblinwishingwelbigl](https://user-images.githubusercontent.com/102822587/166636340-4b4fb5ab-5ffa-4622-919f-22490f410913.png)



https://user-images.githubusercontent.com/102822587/166636351-31c4335a-2c8c-42a4-bea7-2479e75c8a08.mp4

**Comment by koshcheid** [comment]
Tailor

![tailor-pr](https://user-images.githubusercontent.com/103416782/166946239-14a3ad97-7d72-4741-b89a-360d14d14050.png)
![tailor](https://user-images.githubusercontent.com/103416782/166946259-12aec677-1e13-4744-85a9-f2d3947ca16b.png)

Farm ID: 54830
Twitter: @koshcheid
Discord: Koshchei#4959

**Comment by F1rezd** [comment]
![Golbinmuscle mini](https://user-images.githubusercontent.com/103958221/166954194-4fde78b1-357f-4492-a96f-1e64b735847f.gif)
![GOBLIN OGRO BIG](https://user-images.githubusercontent.com/103958221/166954228-30bc2cf8-d095-43a6-9792-01c0511ca69e.gif)
![Golbin paisa](https://user-images.githubusercontent.com/103958221/166954246-d019ee1c-1f91-4ee9-813c-422c196448ac.gif)

**Comment by SrCouve** [comment]
![Golbinmuscle mini](https://user-images.githubusercontent.com/98098233/166997175-d2641a2b-5e9d-4268-b821-d731786cafe0.gif)
![GOBLIN OGRO BIG](https://user-images.githubusercontent.com/98098233/166997203-b185ff48-8eac-4909-b92f-3735ad8ebd70.gif)
![Golbin paisa](https://user-images.githubusercontent.com/98098233/166997252-70fbf680-de65-4bee-9edc-f14a962cc94d.gif)

**Comment by FarmerKuenster** [comment]
![goblin-farmer](https://user-images.githubusercontent.com/104322749/167044361-7abd2441-6ec2-43c9-be8c-cec53a0b5043.gif)
![goblin-farmer-large](https://user-images.githubusercontent.com/104322749/167044370-dfc0a436-cf21-4b10-8621-899971ab6207.gif)
![goblin-farmer-in-SFL-large](https://user-images.githubusercontent.com/104322749/167044390-42e17310-0640-486f-9266-391bac32328c.gif)


Goblin farmer/barn manager idea
farm id#: 32391
discord: farmerkunester#1626

**Comment by FarmerKuenster** [comment]
![blue mushroom](https://user-images.githubusercontent.com/104322749/167059569-e41cb7f4-7b14-48e1-8081-c1a5556d1278.png)   ![purple mushroom](https://user-images.githubusercontent.com/104322749/167059594-eb7b7f94-8469-4f43-9d5e-c5cf05bbf683.png)   ![red mushroom](https://user-images.githubusercontent.com/104322749/167059615-7c75cc8a-843f-4d56-8a5b-0c34724219b0.png)   ![goblintown-watertrough](https://user-images.githubusercontent.com/104322749/167059640-c94721ac-ad1e-489b-9e0f-15b1c2813e33.png)

![goblintown-watertrough-large](https://user-images.githubusercontent.com/104322749/167059789-f0f220b7-79bf-4593-acc4-0e53bf5876d9.png)

![blue mushroom-large](https://user-images.githubusercontent.com/104322749/167059807-6ee1d9d4-3898-4eb4-b1d5-8f6555feed34.png)
![purple mushroom-large](https://user-images.githubusercontent.com/104322749/167059820-a3b1f8ce-0d20-47a2-9335-c48237831128.png)
![red mushroom-large](https://user-images.githubusercontent.com/104322749/167059826-854187bf-d180-40a0-a24d-6dda61fbdcc4.png)
![water troph-and-mushrooms-large](https://user-images.githubusercontent.com/104322749/167059993-cd10a545-c996-4bfa-aa94-8432d4871d41.png)

Goblin farm water trough and decoration mushrooms
farm id#: 32391
discord: farmerkunester#1626

**Comment by Vergelsxtn** [comment]
Goblin town map idea (WIP)
![IMG_20220506_135243](https://user-images.githubusercontent.com/99605039/167074807-e178d253-6812-485b-ad5b-264495634c19.jpg)

**Comment by Netherzapdos** [comment]
### **Goblin Farmer**
---
<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/167083297-aeceaa5b-6551-43ce-8057-735ed800706c.gif" />
</p>

If there's one thing that Raymond the Goblin Farmer hates - it's losing his eyeglasses when crows take them away while he's sleeping at the porch. 

Raw Assets: 
![Goblin Farmer](https://user-images.githubusercontent.com/101855553/167083307-3f5a6f09-33a3-4bbb-b16f-99a0d1a712bc.gif)

(No Glasses)
![Goblin Farmer No Glasses](https://user-images.githubusercontent.com/101855553/167083313-f0b6238f-6f13-4291-90cd-149821863993.gif)

**Comment by sfwhat** [comment]
Constructor

![hammerdown](https://user-images.githubusercontent.com/95937808/167108226-188d5ca2-bb58-4c44-bd13-33b8f8321d0e.gif)Asset
![hammerdowncloth (1)](https://user-images.githubusercontent.com/95937808/167108222-1381506c-aec3-40f7-aa43-123d2fb809f2.gif) with clothes

![hammerdowncloth (2)](https://user-images.githubusercontent.com/95937808/167108227-59b5152c-bb00-42df-ac56-0ca1f62850ca.gif)

Farm ID: 6127
@strugwhat (Twitter)

**Comment by spencerdezartsmith** [comment]
> ![Golbinmuscle mini](https://user-images.githubusercontent.com/98098233/166997175-d2641a2b-5e9d-4268-b821-d731786cafe0.gif)
> ![GOBLIN OGRO BIG](https://user-images.githubusercontent.com/98098233/166997203-b185ff48-8eac-4909-b92f-3735ad8ebd70.gif)
> ![Golbin paisa](https://user-images.githubusercontent.com/98098233/166997252-70fbf680-de65-4bee-9edc-f14a962cc94d.gif)

Hey @SrCouve any chance you could put a hammer in this goblins hand?

**Comment by Vergelsxtn** [comment]
Here is my idea for goblin town, I've used some assets submitted here to see how they look on the map.

![5](https://user-images.githubusercontent.com/99605039/167236296-acd19b1d-c0f8-4e98-ab69-1785d163a87f.png)
Progress - 90%

**Comment by SrCouve** [comment]
Decoration suggestion for the map, little house inspired by the Hobbits' houses from the Lord of the Rings saga:


![image](https://user-images.githubusercontent.com/98098233/167243223-ec80dd05-a22f-431b-864d-89ea01efeb3e.png)

![image](https://user-images.githubusercontent.com/98098233/167243229-f80f90b8-8a71-40b8-ace9-7181d0234237.png)
![image](https://user-images.githubusercontent.com/98098233/167243247-2e32038e-4f44-49c3-8443-67123e97b3d1.png)

**Comment by SrCouve** [comment]
![image](https://user-images.githubusercontent.com/98098233/167243374-b9103ef8-1970-4c03-84f0-608c2b10928e.png)
![image](https://user-images.githubusercontent.com/98098233/167243396-0773669f-a1ae-49ab-b5c5-89281519f419.png)
![image](https://user-images.githubusercontent.com/98098233/167243429-6529680f-6cc5-41d7-a4cf-3faf534cad2c.png)

**Comment by SrCouve** [comment]
> Hey @SrCouve any chance you could put a hammer in this goblins hand?

Like this @spencerdezartsmith ? 
![Ogre hammer](https://user-images.githubusercontent.com/98098233/167244293-dff09043-5088-4a8f-ac96-694d85d9984f.gif)
![Ogre hammer big](https://user-images.githubusercontent.com/98098233/167244297-72988c65-bdcc-4190-82c9-793d972e170a.gif)
![hammer full](https://user-images.githubusercontent.com/98098233/167244299-bf2ddf8f-6d61-447a-a002-ec6e39f4e256.gif)

**Comment by LittleEins** [comment]
Preview:
![goblin-kubov25002](https://user-images.githubusercontent.com/104184348/167301234-56855028-3e79-494a-bebb-77eb670491ce.png)
Actual:
![goblin-kubov2-raw](https://user-images.githubusercontent.com/104184348/167301238-827815cb-c895-4b9d-979d-d006c3175dc1.png)

**Comment by sfwhat** [comment]
Barn Manager and his son

![barnmanegarity](https://user-images.githubusercontent.com/95937808/167323579-7b279f0c-8fef-44f0-8de4-5d1e3c0b8972.gif)
![goblinfarmerson](https://user-images.githubusercontent.com/95937808/167323592-12cb5efe-1f46-409f-bb60-8f31234298be.gif) ![goblinbarnman (5)](https://user-images.githubusercontent.com/95937808/167323585-3e3fd7d1-7473-4c73-851e-aac67d1b5009.gif)

**Comment by birborbirb** [comment]
Goblin Tailor from Baalex#6256

https://github.com/sunflower-land/sunflower-land/issues/710#issuecomment-1120028241

**Comment by sfwhat** [comment]
### Dungeon decor for goblin town

![dungeonshow-1 png (2)](https://user-images.githubusercontent.com/95937808/167522268-b246d464-6838-4ec8-a6e8-080c807ed83e.png)

![yrockdungeon](https://user-images.githubusercontent.com/95937808/167522068-7d28f28a-a295-4e99-b5ab-85f61125d27b.png) with farmer inside
![yrockdungeonempty](https://user-images.githubusercontent.com/95937808/167522071-6d0f3a3e-0ac0-4ff3-8cdb-784e7f16c9d7.png) without farmer

---

Farm ID: 6127
@strugwhat (Twitter)

**Comment by Netherzapdos** [comment]
> ### Dungeon decor for goblin town
> ![dungeonshow-1 png (2)](https://user-images.githubusercontent.com/95937808/167522268-b246d464-6838-4ec8-a6e8-080c807ed83e.png)
> 
> ![yrockdungeon](https://user-images.githubusercontent.com/95937808/167522068-7d28f28a-a295-4e99-b5ab-85f61125d27b.png) with farmer inside ![yrockdungeonempty](https://user-images.githubusercontent.com/95937808/167522071-6d0f3a3e-0ac0-4ff3-8cdb-784e7f16c9d7.png) without farmer
> 
> Farm ID: 6127 @strugwhat (Twitter)

this one is so good 😂

**Comment by Lightpacer** [comment]
> > ### Dungeon decor for goblin town
> > ![dungeonshow-1 png (2)](https://user-images.githubusercontent.com/95937808/167522268-b246d464-6838-4ec8-a6e8-080c807ed83e.png)
> > ![yrockdungeon](https://user-images.githubusercontent.com/95937808/167522068-7d28f28a-a295-4e99-b5ab-85f61125d27b.png) with farmer inside ![yrockdungeonempty](https://user-images.githubusercontent.com/95937808/167522071-6d0f3a3e-0ac0-4ff3-8cdb-784e7f16c9d7.png) without farmer
> > Farm ID: 6127 @strugwhat (Twitter)
> 
> this one is so good 😂

Thank you 😁 thought this might be reason of the upcoming war 😦

**Comment by JcEii** [comment]
### **Goblin SFL Statue**
![sample](https://user-images.githubusercontent.com/105348036/167801871-3a348bfa-3b47-489a-b36f-bdaac1b36f45.png)

I made 3 versions, I don't know what is good of them, just choose one.

the following are: Stone Goblin, Gold Hoodie Goblin, Gold Goblin.

**1. Stone Goblin SFL Statue**
![Stone_Goblin_Statue](https://user-images.githubusercontent.com/105348036/167803004-015e2992-4ce3-4158-b2de-4a97aeef912b.png)

**2. Gold Hoodie Goblin SFL Statue**
![Golden_Goblin_Hood_SFL_Statue](https://user-images.githubusercontent.com/105348036/167803094-0eaaebd8-14cf-43c9-87bd-27dd789da9a7.png)

**3. Gold Goblin SFL Statue**
![Golden_Goblin_SFL_Statue](https://user-images.githubusercontent.com/105348036/167803145-10722750-2ca1-4d73-9638-c25564557221.png)



Farm ID: 15747 
Twitter: @jcambasa

**Comment by birborbirb** [comment]
AMAZING GUYS ! Everyone here did a really great job!
This issue is technically closed, but you still can send your designs here. 

I'll keep updanting and improving the current goblin town when needed.
