### ISSUE TITLE
[PROPOSAL] Change "Reset Session" button name

### ISSUE THREAD

**Issue by JacobSobolev** [sunflower-land/sunflower-land#731]
hi guys,

So I had an incident with this button when doing the V1 accounts migration.
When I did the migration I started receiving "too many requests" error.
I thought it has something to do with my request getting in a queue maybe I should "clear the session"
It was like 1 hour before the halvening, I panic clicked it and lost around 200 SFL.

So I was thinking to change it to "Reset To Last Save" or "Reset Farm" or "Reset To Last Sync"

Fb#2440 from discord also suggested adding another message to the confirmation model to show how much SFL will be lost if you do so.
"you have X SFL not synced to the chain, are you sure you want to reset the session?

what do you think guys?
or am I the only degen that can think this way about this button😅

**Comment by adamhannigan** [comment]
@JacobSobolev Agreed, we can handle this more clearly by checking the changeset on chain + off chain.

We could be very explicit:

"You will lose 12 SFL and 3 sunflowers. Are you sure you want to continue?"

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
