### ISSUE TITLE
[ART] Mineral based NFTs

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#734]
This is a request for mineral based NFT items to craft at the Blacksmith! 🚀 

**Requirements**

- Minified art submission
- Dimensions and colour palette match the gameplay
- Screenshot of the asset used in the game
- A stone, iron or rock based craftable 

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

Note: Your art & mechanic may be modified/altered by the community if needed.

## Competition 🏆 

Probably my favourite part of Sunflower Land is seeing all the amazing submissions we have when we do a competition ❤️ 

**Deadline** 

6th May

**Prize** 

You will receive accreditation for your art in Open Sea (and our upcoming town hall 😏 )

You will get your design airdropped to your farm _(Rarity of items will differ amongst winners)_

**Winners**

We are looking for 3 winning designs for Season 1. Runner ups will likely make it into Season 2 gameplay.

Each winner will be chosen by:

1. Community ❤️ on the Github comment
2. Selected by the core team
3. A guest judge 😮

**Comment by LeShykun** [comment]
A Treasure ! Can be opened by clicking on it somehow for some surprises ( few stones ,  gold , sfl etc...)
![Annotation 2022-04-29 060913](https://user-images.githubusercontent.com/99097146/165893205-63605f4e-f56a-48bf-a988-5c74d042ec7e.png)
![trasure](https://user-images.githubusercontent.com/99097146/165893209-adf531b8-6b3f-4358-9dd3-ca23b9d281aa.png)

**Comment by AKCH1N** [comment]
## SFL Gold Rock
![SFL Gold Rock x400](https://user-images.githubusercontent.com/44812103/165897571-7b24e962-500e-4368-a7fa-475bc14724e8.png)![SFL Gold Rock original](https://user-images.githubusercontent.com/44812103/165897578-f8db530e-995d-4c8b-ac3a-e1ed5295a6d1.png)

**Comment by Nyp-Sfl** [comment]
**WHEAT STATUE** 
(Gold, iron, stone and some wheat to make)

![netdoğruuuu](https://user-images.githubusercontent.com/104236389/165913173-7ab90974-0cbe-4a16-aea2-ab715b17ad71.png)  ![netdoğru](https://user-images.githubusercontent.com/104236389/165913191-ae120775-0436-4a58-a040-f46718a66110.png)

**Comment by paluras** [comment]
Misterious head 
![image](https://user-images.githubusercontent.com/98059798/165932269-5803fff3-9a88-4327-80a5-fe18fcfc4800.png)
![Slice 1](https://user-images.githubusercontent.com/98059798/165932556-6b5e8bc1-9145-48dc-9c84-82c92f8c4f24.png)
![Head](https://user-images.githubusercontent.com/98059798/165932557-8bfba3ac-ba9c-4b5d-acdc-9723c3a1f58c.png)
![Slice 2](https://user-images.githubusercontent.com/98059798/165932559-6deb800c-521f-471e-869d-698188bc4909.png)

**Comment by InuBakaBo** [comment]
I have an idea, but I am not the best pixel artist so I won't be able to do it justice, hence why I would leave the art to you guys. (none of the examples below are my art, they were found on the internet)

I was thinking of something like a Rune Amulet like
![image](https://user-images.githubusercontent.com/98318794/165936021-65bbf741-1a8b-4b2f-8664-cc1f62badeda.png) OR ![image](https://user-images.githubusercontent.com/98318794/165935916-4960a82d-127f-47c4-acad-c8defe7967be.png)
(inspired from Laputa: Castle in the Sky or Dr.Stone)

Which would cost like 250 stones, 50 irons, 10 gold.
Description: Vibrates by resonating with a Runestone within the vicinity

![image](https://user-images.githubusercontent.com/98318794/165936507-b52427e3-e181-495e-8e63-124952e1c07d.png)

So a runestone which is invisible will appear somewhere on the map randomly (just like the easter egg in the easter event), and when you use the Rune Amulet, depending on where you click on the map it will react strongly or weakly. You would need to click within the range of the red circle to find the Runestone. If you click in the range of the blue circle it would hum twice loudly to indicate you are close. If you click outside of the blue circle it would hum once softly.
![image](https://user-images.githubusercontent.com/98318794/165935215-2c2b5c51-5999-4e46-b1d4-f5012d2b5820.png)

When you collect 5 Runestones one of the following would occur
- Instantly removes 5 hours of cooldown from all crop fields
- Instantly removes 5 hours of cooldown from all gathering resources (trees and ores)
- Instantly gives 5 of each seeds
- Instantly feeds all the animals (something related to 5?)
- Reduce tax of withdrawing SFL by 5% 

You are only able to use the Rune Amulet 5 times a day. Maybe even having tiered versions, where the higher tiered one is a bigger range and also would point at the direction of where the runestone is when you use it.

Lol I dunno, just brainstorming ideas...

**Comment by jpeyrol** [comment]
#736

## Iron Radish Statue

### Objective 

This pretty exclusive NFT, with the intention of being just not a decoration, but a NFT Buff to reward to all the radish farmers. 
This statue would give a 25% chance to the owner of having another radish when harvesting (subject to change to not be too OP).

### Description 

A lucky radish covered by Iron. For some reason, when having this trophy in your farm, you will have a chance to double the reward when harvesting Radish.

You can craft the Iron Radish Statue in the blacksmith.

## NFT

![miniIMG](https://teissieryannis.com/assets/img/final-radis.png) (1:1 - 100%)

![bigIMG](https://teissieryannis.com/assets/img/upscale-radis.png) (6:1 - 600%)

![preview](https://teissieryannis.com/assets/img/preview-final.png)

### Supply

1000

### Crafting costs

- **250** ![Radish](https://raw.githubusercontent.com/sunflower-land/sunflower-land/main/src/assets/crops/radish/crop.png)
- **35** ![Iron](https://raw.githubusercontent.com/sunflower-land/sunflower-land/main/src/assets/resources/iron_ore.png)
- **80** ![SFL](https://user-images.githubusercontent.com/10442760/163301505-94c5cfcc-c833-4ace-b39f-a9e667ba090a.gif)
Designed by [@jpeyrol] & [@TeissierYannis]

**Comment by sfwhat** [comment]
<html>
<html>
<body>


:musical_note:  Jukebox
--


- An Nft made from scratch, apart from looking cool,
this jukebox may allow it's owner to change in game music or mute game sounds.




</body>
</html>




 ##

Costs **_iron_**  and **_gold_**

![arkaplansunfl-1 png (1)](https://user-images.githubusercontent.com/95937808/165958533-7adf6e2b-9ee6-4e11-9d3f-bc9df3dff5cb.gif)
 <html>
<html>
<body>


![pixil-frame-0 (57) (9)](https://user-images.githubusercontent.com/95937808/165951552-f6d0d603-5328-459c-8425-6cbc9736e4ca.gif) (1:1) with flying notes
![pixil-frame-0 (57) (6)](https://user-images.githubusercontent.com/95937808/165951557-37055d98-6fdd-426b-a157-bec0e374e305.gif) (1:1) without
 ##


</body>
</html>
Farm ID: 6127

@strugwhat (Twitter)

**Comment by na66ime** [comment]
![doghouse4](https://user-images.githubusercontent.com/102286455/165960833-61cd9242-8690-4c74-9560-32cad19a5726.gif)

**Comment by SrCouve** [comment]
sword in the stone:
(Like Excalibur):
![image](https://user-images.githubusercontent.com/98098233/165971019-5bbb0d99-e5fe-4c11-9157-a0e01bd8b37d.png)
![image](https://user-images.githubusercontent.com/98098233/165971039-50fe27df-cc1a-4dbf-b48e-d0b03048e5b3.png)
![image](https://user-images.githubusercontent.com/98098233/165971064-de8759e6-c41a-4389-8657-98436d0801bc.png)
Option 2(small change in stone)
![image](https://user-images.githubusercontent.com/98098233/165971122-45d29b11-ed7d-4e9c-87fe-1218f0212890.png)
![image](https://user-images.githubusercontent.com/98098233/165971139-df31bd45-5c71-41e6-9318-195850e58b43.png)
![image](https://user-images.githubusercontent.com/98098233/165971160-6d2ad08f-014c-47ac-b8a6-7163c0d1e040.png)
Option 3 (Animated):
![163650291-e27eef82-0695-4d30-83a3-9be7932cb355](https://user-images.githubusercontent.com/98098233/165971425-d5bb3af0-521f-4ad2-8b33-9a9b929f453d.gif)
![163650331-d5723a84-d97b-4b33-8aab-70046cfb4244](https://user-images.githubusercontent.com/98098233/165971431-8f4a42e6-9f41-48dd-bff2-8da6ca324d0d.gif)
![163650589-0854ca0d-68d1-4fa8-91be-f98c33404614](https://user-images.githubusercontent.com/98098233/165971444-1adc22f3-9d0c-4d65-93d6-dd852e791d03.gif)

**Comment by Telknub** [comment]
The mining mole:

This is an idea I iterated on #494 , and with a bit of feedback from community artist Birb on Discord, I made some changes and this is the final version. The idea is an NFT that would be like the beaver but for collecting stone.
Here are the 3 tiers of the NFT:


Tier 1:
![Toupeira Final Tier 1 zoom](https://user-images.githubusercontent.com/38796969/165986133-f5a412eb-b9e1-4866-9709-132812a41458.gif)
![Toupeira Final Tier 1](https://user-images.githubusercontent.com/38796969/165986144-a61d4bdd-7cee-4daa-9f9a-1824ec288f41.gif)

Tier 2:
![Toupeira Final Tier 2 zoom](https://user-images.githubusercontent.com/38796969/165986177-6c7ef976-fe20-4c38-b003-561f2ddf9c3a.gif)
![Toupeira Final Tier 2](https://user-images.githubusercontent.com/38796969/165986182-46495a5b-25cc-4324-b2c9-8a1ed4283d95.gif)

Tier 3:
![Toupeira Final Tier 3 zoom](https://user-images.githubusercontent.com/38796969/165986413-773551a9-c497-4932-b6cd-0df737c3c110.gif)
![Toupeira Final Tier 3](https://user-images.githubusercontent.com/38796969/165986419-7eae210f-9297-4020-877a-71ca11f98a4d.gif)

**Comment by brian-man** [comment]
> ## 🎵 Jukebox

Thematic and time consistency seems off here.  It's not clear to me that SFL has indoor plumbing, much less electricity, batteries, and vinyl or CDs.

**Comment by Alexcnder** [comment]
Goblin STRIKE : No More Food

A symbol against the oppressor Team SUNFLOWER

This nft is there to show ur symapthy to Team Goblin

Cost:

Stone: 1000
radish: 10

![View NO SFL GL](https://user-images.githubusercontent.com/87881787/165991959-5aaf3281-4d3f-43fd-8b6b-5b1749dfc692.png)
![NO SFL GL](https://user-images.githubusercontent.com/87881787/165991963-78bf151c-e416-46d1-bd48-5c55080ec1d4.png)

![grafik](https://user-images.githubusercontent.com/87881787/165992697-f1b15cf9-36d4-4438-82b9-d2c3d2ce7504.png)

**Comment by cargomesplay** [comment]
Exemplos de uso 
Portugues
Ter um Golem no jogo no estilo do esquilo
Pequeno Golem = Aumente a colheita de pedras em 20%
Golem = Aumente a colheita de Ferro em 20%
Antigo Golem = Aumente a colheita de Ouro em 20% e quebre pedra sem precisar de picareta

obs: As descrições podem ser alteradas para o equilíbrio do jogo

Ingles
Examples of use
Have a squirrel-style Golem in the game
Little Golem = Increase stone harvesting by 20%
Golem = Increase Iron harvest by 20%
Ancient Golem = Increase Gold harvest by 20% and break stone without needing a pickaxe

obs: Descriptions can be changed for game balance



![tela](https://user-images.githubusercontent.com/104114336/166001312-a3b17edc-3ae4-4830-aa07-8a94481e696e.png)

Nível 1: Little Golem
![BABY-GOLEM](https://user-images.githubusercontent.com/104114336/166000586-b2fcf6ed-7867-427e-a724-84cb12e42031.png)
![BABY-GOLEM-BIG](https://user-images.githubusercontent.com/104114336/166000598-98a421bf-aee5-4af6-a2c4-13b35780586c.png)

Nível 2: Guardian Golem 
![GUARDIAN-GOLEM](https://user-images.githubusercontent.com/104114336/166000662-98a0ef7c-0e9d-4385-8bdb-1d7248612006.png)
![GUARDIAN-GOLEM-BIG](https://user-images.githubusercontent.com/104114336/166000678-09ce61c4-c0a7-46af-ae35-f24936a9e96a.png)

Nível 3: Ancient Golem
![ANCIENT-GOLEM](https://user-images.githubusercontent.com/104114336/166000738-6dfbc8bf-66b4-47d1-8d16-cf0b4a146e30.png)
![ANCIENT-GOLEM-BIG](https://user-images.githubusercontent.com/104114336/166000752-d8c58fbe-699b-440a-bcc8-87d8b3a4423e.png)

Wallet metamask: 0xf06a69aCa1BB0182F1D1CB188E052A8FB1C71295
Farm id: 29147
discord nick: carloshq#3347

**Comment by SrCouve** [comment]
I suggest you have a click interaction to open or close it, linked to a Buff, while it is active the buff is working, when the buff ends (may have a cooldown or not open again) you must press for I open again and activated the buff, I think it's a cool alternative to generate one more interaction and generate another gameplay, being in addition to just an Nft that gives a buff, but that you also have to interact with it, it can just be something interactive too


Rock Golem:
![image](https://user-images.githubusercontent.com/98098233/166078256-d1f8e4cf-d902-43af-a19b-c2a05311b6fa.png)
![image](https://user-images.githubusercontent.com/98098233/166078280-a0da0023-8e1b-4544-a9b3-d3ae9223651e.png)



Closed:
![image](https://user-images.githubusercontent.com/98098233/166078991-e98425f1-04fe-462f-b635-e395e23db1a3.png)

![image](https://user-images.githubusercontent.com/98098233/166078972-99bb5925-b2b3-4b96-9d75-afdd8e7788be.png)


**Full Animation:**
![Full anima](https://user-images.githubusercontent.com/98098233/166078350-bc716301-f74e-41bc-b899-bdf33c4fa41f.gif)
![full anima big](https://user-images.githubusercontent.com/98098233/166078411-b09b9ef7-7473-4c95-9061-31307c79a1ec.gif)

**Stay:**
![stay icon](https://user-images.githubusercontent.com/98098233/166078640-9f43354a-7bf3-4a6f-a8c0-7c0ff49abd1c.gif)
![stay](https://user-images.githubusercontent.com/98098233/166078570-0960aecf-d69c-4401-ba81-4af0ca63fbfb.gif)

**Opening:**
![Ope icon](https://user-images.githubusercontent.com/98098233/166078885-04a841ad-7e08-463a-9a11-ba20ab2964f7.gif)
![Open](https://user-images.githubusercontent.com/98098233/166078889-726c9e9f-4b8b-4497-bb19-7f0cfc5ee1c1.gif)

**Closing**
![Closed](https://user-images.githubusercontent.com/98098233/166079038-4307b1fc-16f9-464b-8467-a843ff59713d.gif)
![Close big](https://user-images.githubusercontent.com/98098233/166079046-3b1dbceb-5b89-4be2-b0cb-3654f94ffe6c.gif)

**Comment by paluras** [comment]
I a bit of a stretch but ill post it anyway.Magic obelisk.
![image](https://user-images.githubusercontent.com/98059798/166096555-d22139f4-dcbf-4c19-bfb6-a503ea03046f.png)

![magicobeliskbig](https://user-images.githubusercontent.com/98059798/166096699-96a62f99-72f9-40e8-941c-636f20997c42.gif)
![magicobelisksmall](https://user-images.githubusercontent.com/98059798/166096700-08c795d0-0c83-43a8-8fb8-0b738acd08ba.gif)

**Comment by Vergelsxtn** [comment]
Introducing ”Gold Luck” Statue.

Preview
![Preview goldluckstatue](https://user-images.githubusercontent.com/99605039/166129955-57a3a43b-ad77-4e90-83fe-63b9d4eefbf5.jpg)

Default
![Goldluckstatue](https://user-images.githubusercontent.com/99605039/166129961-2d1925b6-d2ae-42f3-aeb9-415278f9baaa.gif)

Upscale
![Goldluckstatue1](https://user-images.githubusercontent.com/99605039/166129963-60f0a098-d098-4fb4-9df0-8dbe9c7329a5.gif)

**Comment by Netherzapdos** [comment]
### **The Sculptor**
---
<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/166152367-6a13a3d1-8545-450e-b1f0-1fa207349339.gif">
</p>

<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/166152591-5d3e2b0f-cb11-4ea0-a117-e6298e00c413.gif">
</p>

**Farmer:** "I can't afford the T3 Scarecrow, so make me something scary!"
**Erik the Sculptor:** "What is a T3 Scarecrow?"
**Farmer:** "Doesn't matter, I just need something that will scare the crows away!"
**Erik the Sculptor:** "I'll get it done."

---
### **Zen/Balanced Stones**
---
<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/166152386-2c1cdb2e-fb00-4ab0-bd06-a18d86cce3d0.png">
</p>

<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/166152614-bb5954c0-5fd7-4727-852d-af50dc5bada2.png">
</p>

<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/166152615-2a1deedd-0233-4c53-8ba8-7180adddf908.png">
</p>

<p align="center">
  <img src="https://user-images.githubusercontent.com/101855553/166152617-dcae02a3-9862-4a6f-9478-f7f9d2d846e2.png">
</p>

**Comment by paluras** [comment]
Libra.
![image](https://user-images.githubusercontent.com/98059798/166196909-dabbfe58-2b94-4afe-9838-51e0e8451306.png)
![Libra2](https://user-images.githubusercontent.com/98059798/166197075-f00091a8-407a-4775-a1b6-3b685fcf41ae.png)
![Libra](https://user-images.githubusercontent.com/98059798/166197077-956382c0-6fc8-45eb-9473-aaa2e61697bd.png)

**Comment by Aestnelis** [comment]
Tractor, can be functional and made with stone/iron/rock

![tractor](https://user-images.githubusercontent.com/98103679/166319186-f18a8513-8fc8-497e-8717-d2eb417c3632.gif)
![bigtractor](https://user-images.githubusercontent.com/98103679/166319218-2de1cea0-39fe-4296-9b61-6f170c38564c.gif)
![sunflowertractor](https://user-images.githubusercontent.com/98103679/166319238-153eb66b-1272-4c69-bb5e-864bfa47e0db.gif)

**Comment by sfwhat** [comment]
## Moonflower Safe 
### Descrption
According to old stories this safe contains a mythical time called "The Night"

Requires sunflower and iron

![safetry-1 png (1)](https://user-images.githubusercontent.com/95937808/166439856-6984115c-061b-4453-b17c-0669c8d1bef3.png)![safetry-1 png (4)](https://user-images.githubusercontent.com/95937808/166441089-b6a367fb-b198-42d6-a2ab-8c6d4da770b3.png)

**Comment by AntonSaden** [comment]
![image](https://user-images.githubusercontent.com/46472951/166748375-5f54b615-37dc-4bd3-b402-fd58b788c6a2.png)
![037F5A10-B64C-41E3-B340-D2F441A32093](https://user-images.githubusercontent.com/46472951/166748503-b3efaa00-3dd0-4a79-8516-b004e9f6de35.png)

An NFT for all goblin supporters -> 
**### Goblin liberation** :  Liberate goblins from the racism of the Human kind , let them live freely in their homes . A statue to symbolize peace between races and  spread the word that the Goblins are not evil by nature.

> Requires stone

Farm ID: 4007
Polygon Address: 0x214e4E5FF88b3b921765f8E9DDB0A201b10565F8

**Comment by LittleEins** [comment]
Golden Bonsai
Requires:
10 Wood
10 Gold
10 Stone
10 SFL
Preview
![golden-bonsai](https://user-images.githubusercontent.com/104184348/166868068-c9294020-f505-4dc6-b0e7-453bb7bf9c43.png)
Actual-Size
![golden-bonsaii](https://user-images.githubusercontent.com/104184348/166868244-510ce5a6-b885-446d-913e-0cd88179b022.png)

Mini-Golden Bonsai
Preview
![golden-bonsai-mini](https://user-images.githubusercontent.com/104184348/166868342-7847028e-e37a-456c-bd5d-6a001e2eba1b.png)

Actual-size
![golden-bonsa-minii](https://user-images.githubusercontent.com/104184348/166868327-8a6d8046-fa10-4633-9e5e-db4a220e0e99.png)

**Comment by rissojavier** [comment]
# **Medusa** - ![Medusa](https://user-images.githubusercontent.com/88810285/167145528-6b4ce286-64a2-46df-9d92-4037befb49b5.gif)

Icon menu:
![icon-menu](https://user-images.githubusercontent.com/88810285/167144226-846722ae-22e9-4f8e-ba61-7e8974adb22b.png)

Capture:
![Capture](https://user-images.githubusercontent.com/88810285/167144284-5759a76c-0bf7-4205-b268-b87dd73d5257.gif)

> Farm id: 10242
> Polygon address: 0x5D338b5AFa38A9e53a69e2D6458CdA693A6BB214
> Instagram: @arq_risso

**Comment by brian-man** [comment]
> **Medusa**
@rissojavier Medusa should be turning someone else to stone, not herself.

**Comment by rissojavier** [comment]
> > **Medusa**
> 
> @rissojavier Medusa should be turning someone else to stone, not herself.

@brian-man

Athens, furious at the desecration of her temple, turned her into a statue, then realized that this would not be punishment enough, so Athens transformed Medusa into a monster with the deadly ability to turn anyone who looked her in the face into stone.

**Comment by brian-man** [comment]
> Athens, furious at the desecration of her temple, turned her into a statue, then realized that this would not be punishment enough, so Athens transformed Medusa into a monster with the deadly ability to turn anyone who looked her in the face into stone.

Interesting.  Link?

**Comment by benaxol12** [comment]
Name: Stontoise (Stone Tortoise)
![Stortoise](https://user-images.githubusercontent.com/98098031/167215384-4676b26d-b587-4704-9283-764121d42a5a.gif)
![Stortoise1](https://user-images.githubusercontent.com/98098031/167215389-7299be26-ec47-48ba-8bcd-7ba022834b21.gif)

**Comment by LUNCHBOX404** [comment]
**Stone of Help**

![31777-sfl-mineral_nft-stone_of_help](https://user-images.githubusercontent.com/104640972/167237004-0e47d7f8-2028-4088-baa0-3aba97951a5d.png)
![31777-sfl-mineral_nft-stone_of_help-8x](https://user-images.githubusercontent.com/104640972/167237007-15fe4b3f-2c02-43ce-92e2-02fa3e6bfb0d.png)

![31777-sfl-mineral_nft-stone_of_help-scene](https://user-images.githubusercontent.com/104640972/167237010-f5be3220-04d6-436b-a386-9ac146e58b2f.jpg)

<hr>
Farm ID: 31777  |  Discord: LUNCHBOX#0859  |  Twitter: @LUNCHBOX_404

**Comment by eArL2384** [comment]
I hope my entry is not too late

The First Farmer Statue
25 stone
15 iron
5 gold

Description:
The first farmer, the person who discovered sunflower land and told the farmers all over the globe about this pleasant and magical land

![IMG_20220507_162858](https://user-images.githubusercontent.com/104702521/167246350-e9c3c203-5a0b-45af-b9c6-e68d9bad3894.jpg)
![2022-05-07-16-27-25-756](https://user-images.githubusercontent.com/104702521/167246359-52638fb3-813b-4290-b9f6-0435d85f6771.jpg)

**Comment by eArL2384** [comment]
> I hope my entry is not too late
> 
> The First Farmer Statue 25 stone 15 iron 5 gold
> 
> Description: The first farmer, the person who discovered sunflower land and told the farmers all over the globe about this pleasant and magical land
> 
> ![IMG_20220507_162858](https://user-images.githubusercontent.com/104702521/167246350-e9c3c203-5a0b-45af-b9c6-e68d9bad3894.jpg) ![2022-05-07-16-27-25-756](https://user-images.githubusercontent.com/104702521/167246359-52638fb3-813b-4290-b9f6-0435d85f6771.jpg)

here is much more detailed make

![Screenshot_2022-05-07-19-40-45-41_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/104702521/167253111-764ae1ce-31e9-41ad-889b-66003cfd255c.jpg)


![2022-05-07-19-47-02-372](https://user-images.githubusercontent.com/104702521/167253129-ce718f16-7735-4ea0-8715-36e491b1c33e.jpg)

**Comment by adamhannigan** [comment]
Another round of amazing contributions ❤️ 🤗 

Each competition gets harder to judge as the art gets better and we have more talented artists joining the community.

Drum roll 🥁 

Being it Mothers Day, the special judge for this competition was non other than Mrs Bumpkin Builder 👵 

The winners are:

Community voting: @SrCouve Rock Golem 👏 
Team voting:  @Telknub Mole 👏 
Special Judge:  @LittleEins Golden Bonsai 👏 

The team will be working on adding these into the game over the coming weeks. Keep an eye out for your creations appearing on your farms! Well done everyone 🏆
