### ISSUE TITLE
Stack skills

### ISSUE THREAD

**Issue by Vitasya02** [sunflower-land/sunflower-land#738]
If skills of nft will stack(if u have more than one same nft)It can increase price on nft in open sea

**Comment by brian-man** [comment]
I'm unclear on the proposal.  Is the proposal to make it such that multiple Easter Bunny NFTs in a single farm means that you can yield (effectively) infinity carrots from a single seed planting?

That seems like a terrible idea.

**Comment by adamhannigan** [comment]
@Vitasya02 Thanks for the idea!

Currently you can stack different NFTs boosts together, but cannot stack the same NFT on top of each other.

This would lead to a whale/hoarding mentality of NFTs unfortunately
