### ISSUE TITLE
[IDEA] Beaver T1 and T2 Bonus invert

### ISSUE THREAD

**Issue by NoisyBucheron** [sunflower-land/sunflower-land#740]
Hi guys,

Since beaver T2 have the skill to cut by 2 the time to harvest wood and we can't keep the SFL flow to pay the axes, why not inverting this boost with beaver T1 so people buy more T1's to get the bonus wood in T2?

Cut time by 2 is more like a quality of life boost, and 20% more wood is a good reward!

Cheers

**Comment by adamhannigan** [comment]
@NoisyBucheron Good idea, this has been raised in a few circles.

I am considering giving it an axe boost instead. I.e. save 25% of your axe when cutting wood.

**Comment by nbkshocks** [comment]
> @NoisyBucheron Good idea, this has been raised in a few circles.
> 
> I am considering giving it an axe boost instead. I.e. save 25% of your axe when cutting wood.

Agree with this <3

**Comment by StockSavage** [comment]
> @NoisyBucheron Good idea, this has been raised in a few circles.
> 
> I am considering giving it an axe boost instead. I.e. save 25% of your axe when cutting wood.

Yeah the T2 beaver is pretty useless currently with a drain rate of 80 SFL per day and no way to make 80 SFL per day. It's only nice if you have a big reserve of SFL already. This would be a decent change.

**Comment by InuBakaBo** [comment]
> @NoisyBucheron Good idea, this has been raised in a few circles.
> 
> I am considering giving it an axe boost instead. I.e. save 25% of your axe when cutting wood.



> @NoisyBucheron Good idea, this has been raised in a few circles.
> 
> I am considering giving it an axe boost instead. I.e. save 25% of your axe when cutting wood.

Hi Adam, I don't think that's a great idea as the t3 effect just makes the t2 effect obsolete.

For example the t3 scarecrow retains the predecessors' effects, so if the t3 beaver were to retain the predecessors' effects then the t2 effect is obsolete. 

Maybe consider something like,
- 10% chance to gain 3x wood
- 10% chance to gain 5 stones
- 5% chance a squirrel runs out and drops some 5 wheat
-  increase the chance of gaining a fruit by 50% chance (new mechanic)
- etc

**Comment by DonatasDee** [comment]
> > @NoisyBucheron Good idea, this has been raised in a few circles.
> > I am considering giving it an axe boost instead. I.e. save 25% of your axe when cutting wood.
> 
> Hi Adam, I don't think that's a great idea as the T3 effect just makes the T2 effect obsolete.
> 
> For example the T3 scarecrow retains the predecessors' effects, (T1: +15% faster cooldown and T2: +20% more crops) so if the T3 beaver were to retain the predecessors' effects then the T2 effect is obsolete as you won't need axes if you have a T3 beaver.
> 
> Maybe consider something like,
> 
> * 10% chance to gain 3x wood
> * 10% chance to gain 5 stones
> * 5% chance a squirrel runs out and drops some 5 radish/wheat
> * increase the chance of gaining a fruit by 50% chance (new mechanic)
> * increase the chance of gaining Woodchips by 50% (new mechanic, Woodchips can be used as mulch on crop fields to reduce weeds from growing. When weeds grow randomly they extend/increase the cooldowns of the crops as they're sapping the nutrients away from the crops)
> * etc

These are amazing and exactly what we need. The buffs don't always have to all be related to wood itself.
Same goes for buffs in the future with other NFT's.

**Comment by NoisyBucheron** [comment]
Here's a better idea with it's art added:

Introduce 2 new ressources ingame and it's variations: 

### **Wood Resine**
![sesina2](https://user-images.githubusercontent.com/104263513/166106146-d55f381e-882a-446c-b0ed-ef884a339863.png)
![sesina](https://user-images.githubusercontent.com/104263513/166107408-166c4363-3d77-4826-a4b9-f353998e14cc.png)


_**Drop chance:**_
Equal to Mutant crops or Animal crops

_**Utility:**_
Used to craft can of paint and more...




### **Can of paint (multiple colors)**

![peinture64](https://user-images.githubusercontent.com/104263513/166107133-922525f6-2366-4208-b647-81b0a879e4fe.png)
![peinture](https://user-images.githubusercontent.com/104263513/166107415-2c66429a-b350-499d-a4da-e86b118c75b8.png)
![canpaintgreen](https://user-images.githubusercontent.com/104263513/166107484-af64fd22-bbd4-48a6-b4d6-3bb72576a6b7.png)
![canpaintgreensmall](https://user-images.githubusercontent.com/104263513/166107487-4f052a38-fa1a-4682-9c09-18eb4ee3b2bb.png)
![canpaintbluesmall](https://user-images.githubusercontent.com/104263513/166107561-73aebf77-43ec-40e4-8020-806d3704ad19.png)
![canpaintred](https://user-images.githubusercontent.com/104263513/166107563-abec0286-490a-4f43-ab67-5f1a8f73b45d.png)
![canpaintredsmall](https://user-images.githubusercontent.com/104263513/166107564-6b2b5b67-b534-4e1d-b6b3-4abdff433a19.png)
![canpaintblue](https://user-images.githubusercontent.com/104263513/166107565-cb09f318-0fca-4861-8f81-3692b4ca0a3a.png)



**_How to craft:_**
Tailor craft it for you

**_Ingredients:_**
Resine + fruits or vegetables

**_Utility:_** 
Customise your buildings ingame to flex ;)

### **Reason to have those new ingredients:**

With this we can keep the bonus of beaver T1 and T2 and even add a little bit more bonus to T3 if needed.

**_T1:_** 
Bonus 20% wood
50% more chance to drop Resine

**_T2:_** 
Previous T1 Bonus
Trees recover 50% faster
100% more chance to drop Resine

**_T3:_**
Previous T1 and T2 Bonus
Chop trees without axes
150% more chance to drop Resine

Cheers

**Comment by NoisyBucheron** [comment]
> Here's a better idea with it's art added:
> 
> Introduce 2 new ressources ingame and it's variations:
> 
> ### **Wood Resine**
> ![Resine V1](https://user-images.githubusercontent.com/104263513/166109368-abec6ad4-aff8-4859-aa21-573dfac815aa.png)
> 
> _**Drop chance:**_ Equal to Mutant crops or Animal crops
> 
> _**Utility:**_ Used to craft can of paint and more...
> 
> ### **Can of paint (multiple colors)**
> ![canofpaintgreen](https://user-images.githubusercontent.com/104263513/166109594-14b3673c-1039-41d2-81f9-925f5f47c29a.png) ![canofpaintpink](https://user-images.githubusercontent.com/104263513/166109595-1a9ebc5b-57a9-4785-a83c-bca52831cf62.png) ![canofpaintred](https://user-images.githubusercontent.com/104263513/166109596-4917a4df-2639-4276-8aaf-d7b9e7cace90.png) ![canofpaintyellow](https://user-images.githubusercontent.com/104263513/166109597-69e9ede3-8b05-4191-b86b-b57c67930c1a.png) ![canofpaintblue](https://user-images.githubusercontent.com/104263513/166109598-fd842151-6466-4b0b-ab4a-829db1241b00.png)
> 
> Etc...
> 
> **_How to craft:_** Tailor craft it for you
> 
> **_Ingredients:_** Resine + fruits or vegetables
> 
> **_Utility:_** Customise your buildings ingame to flex ;)
> 
> ### **Reason to have those new ingredients:**
> With this we can keep the bonus of beaver T1 and T2 and even add a little bit more bonus to T3 if needed.
> 
> **_T1:_** Bonus 20% wood 50% more chance to drop Resine
> 
> **_T2:_** Previous T1 Bonus Trees recover 50% faster 100% more chance to drop Resine
> 
> **_T3:_** Previous T1 and T2 Bonus Chop trees without axes 150% more chance to drop Resine
> 
> Cheers

Or the NPC for this could be 
![image](https://user-images.githubusercontent.com/104263513/166111624-b71374b0-2892-4042-a74b-1daa87fd11a0.png)

**Comment by DonatasDee** [comment]
I feel like the NPC is way too hardcore considering it's supposed to be a painter that uses a simple bucket of paint

**Comment by NoisyBucheron** [comment]
> I feel like the NPC is way too hardcore considering it's supposed to be a painter that uses a simple bucket of paint

Agreed, but he can be the paint seller at least. Or we can create another NPC that paint buildings ^^

**Comment by NoisyBucheron** [comment]
![canofpaintred](https://user-images.githubusercontent.com/104263513/166121237-993ce14c-e19e-4c94-aef8-0cdafd7b46b6.png)
Just a little modification to the art

**Comment by brian-man** [comment]
@NoisyBucheron @adamhannigan FYI
https://github.com/sunflower-land/sunflower-land/issues/780

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
