### ISSUE TITLE
[ART PROPOSAL] Traveler from The Far East // Mr. Chu 

### ISSUE THREAD

**Issue by LUNCHBOX404** [sunflower-land/sunflower-land#741]
Hello, Sunflower Farmers!

SuperSynapse and I are a husband/wife team who worked together to make a fun new character with some potential quests (see following messages).

The primary part of this proposal is for Mr. Chu and his cart, a self proclaimed 'Traveler from The Far East' looking for a new town to open his restaurant.

There are a few goals we had with this character:
 - Encourage players to grow more variety in their crops used to produce his food items
 - Add an additional progression path for players to unlock more NFT items and potentially a new crop (see following post)
 - Add diversity with an Asian character and fun 'Far East' inspired lore/items

<hr>

### Tada! Here's Mr. Chu.

![31777-sfl-far_east-mr_chu](https://user-images.githubusercontent.com/104640972/166463914-ba996c30-cad5-4d27-9440-0fb27c660bae.png)
![31777-sfl-far_east-mr_chu-8x](https://user-images.githubusercontent.com/104640972/166463883-b236fcb0-8eff-4d20-bb9c-fbbd0a3fa72d.png)

![31777-sfl-far_east-board-SCENE-8x](https://user-images.githubusercontent.com/104640972/166464204-5a8aeafc-247c-4142-a6d4-68548d685857.png)

When clicking on his cart you get this storefront (Pumpkin Bao ingredients used as placeholder UI):
![31777-sfl-far_east-board-MENU-8x](https://user-images.githubusercontent.com/104640972/166404364-c6f80858-12f0-4535-a5ff-66af27ab793d.png)

Each food item has a primary crop of each type. His first quest is to give him ingredients and create one of each type of food item in his restaurant.
![31777-sfl-far_east-board-FOOD-8x](https://user-images.githubusercontent.com/104640972/166404288-ac1e651f-7a82-4114-a8f3-f2e0eca2ee3a.png)

<hr>

### The food items in Mr. Chu's restaurant:

1. Sunflower Sushi
![31777-sfl-far_east-sunflower-sushi](https://user-images.githubusercontent.com/104640972/165990200-0305aff2-b1a3-4da2-a82f-c96f61f3750f.png)
![31777-sfl-far_east-sunflower-sushi-8x](https://user-images.githubusercontent.com/104640972/165987352-8d3be7a1-eda5-4ed4-b739-71da260065a0.png)

3. Potato Mantou (Bun)
![31777-sfl-far_east-potato-mantou](https://user-images.githubusercontent.com/104640972/166404328-7f0c2e18-ef38-400c-af37-f3e7b7938caa.png)
![31777-sfl-far_east-potato-mantou-8x](https://user-images.githubusercontent.com/104640972/166404319-dba339b0-df22-4e6b-8cb2-4cad312300be.png)

4. Pumpkin Bao
![31777-sfl-far_east-pumpkin-bao](https://user-images.githubusercontent.com/104640972/165990140-44516cae-00a1-469e-add5-7d77efece1c1.png)
![31777-sfl-far_east-pumpkin-bao-8x](https://user-images.githubusercontent.com/104640972/165987565-b4ae77bd-584b-4ff9-a1e1-5dc817f1966e.png)

5. Carrot Nigiri
![31777-sfl-far_east-carrot-nigiri](https://user-images.githubusercontent.com/104640972/165990123-415bdc9e-9cff-4d54-a8b7-2fb0ace7cf24.png)
![31777-sfl-far_east-carrot-nigiri-8x](https://user-images.githubusercontent.com/104640972/165987636-5148fd7a-a451-4fd2-ba7c-e1a9c4b421c7.png)

6. Napa Cabbage
![31777-sfl-far_east-cabbage-napa](https://user-images.githubusercontent.com/104640972/165990105-fd132f04-c8c1-4911-bdff-7f67172b90a6.png)
![31777-sfl-far_east-cabbage-napa-8x](https://user-images.githubusercontent.com/104640972/165987773-5ba935bd-bdde-4913-8ec8-1d4dcb122d9e.png)

7. Beet Nigiri
![31777-sfl-far_east-beet-nigiri](https://user-images.githubusercontent.com/104640972/165990091-82c77576-b4b9-4e3c-9910-4d6ce9847d92.png)
![31777-sfl-far_east-beet-nigiri-8x](https://user-images.githubusercontent.com/104640972/165987853-94d2cb38-b691-4ce0-96ab-67e46c4d5d90.png)

8. Cauliflower Onigiri
![31777-sfl-far_east-cauliflower-onigiri](https://user-images.githubusercontent.com/104640972/165990071-5f665b7a-03a8-4635-977e-93b384fc90ba.png)
![31777-sfl-far_east-cauliflower-onigiri-8x](https://user-images.githubusercontent.com/104640972/165987915-68ce1ac5-3bdc-4dcf-aba8-7366a6c983a7.png)

9. Parsnip Dumpling
![31777-sfl-far_east-parsnip-dumpling](https://user-images.githubusercontent.com/104640972/165990026-a714cf60-a57e-40a0-9e8f-5e7c82e4b985.png)
![31777-sfl-far_east-parsnip-dumpling-8x](https://user-images.githubusercontent.com/104640972/165988028-8e9fbd67-1784-4e58-ad20-30e56068488e.png)

10. Radish Maki
![31777-sfl-far_east-radish-maki](https://user-images.githubusercontent.com/104640972/165990012-e059a647-2919-4657-9c20-53b0fb89e8a3.png)
![31777-sfl-far_east-radish-maki-8x](https://user-images.githubusercontent.com/104640972/165988072-61c1640d-43f5-4f10-bb6d-ebf84b11d08b.png)

11. Wheat Noodles
![31777-sfl-far_east-wheat-noodles](https://user-images.githubusercontent.com/104640972/166404413-63e3085f-065b-4264-9c4c-818f94cf3210.png)
![31777-sfl-far_east-wheat-noodles-8x](https://user-images.githubusercontent.com/104640972/166404401-da8709dd-0151-4b49-b376-7e95a49edb8e.png)

<hr>

### Three NFTs that can be earned from Mr. Chu:

For more details on the journey we've come up with, see SuperSynapse's following post.

1. Guardian Lion Statue
_An intimidating creature._
Proposed Utility: +200% Defence (could be used for future combat like mutant crops, or base raids)

![31777-sfl-far_east-guardian_lion](https://user-images.githubusercontent.com/104640972/165989902-12e5c7a5-62b3-4428-867e-af39e25af495.png)
![31777-sfl-far_east-guardian_lion-8x](https://user-images.githubusercontent.com/104640972/165988614-eec77238-6a89-4fca-939b-c5188e410825.png)

2. Lucky Cat
_Brings you good fortune._
Proposed Utility: Boosts rice crop harvests by a random 20% - 80% 

![31777-sfl-far_east-luckycat3-1x](https://user-images.githubusercontent.com/104640972/166503851-cf92cb4c-f145-4593-982b-f82b26b502f7.gif)
![31777-sfl-far_east-luckycat3-8x](https://user-images.githubusercontent.com/104640972/166503870-1e419953-673a-4ed0-b523-8e9346e31627.gif)

3. Pet Cricket 
_A helpful critter._
Proposed Utility: When clicked, hops around and finds a free random seed (with cooldown)

![Pet-Cricket-animation](https://user-images.githubusercontent.com/104640972/166393872-2acd6ec6-9dde-458e-9c08-b88443663b11.gif)
![Pet-Cricket-animation_Large](https://user-images.githubusercontent.com/104640972/166393876-cc0a07be-7593-49d5-9750-4025a9424d73.gif)

<hr>

### A line up of all the assets for Mr. Chu:

![31777-sfl-far_east-board-ALL-8x](https://user-images.githubusercontent.com/104640972/166464304-f420bb5d-30c2-44ff-b96c-2115a15adf08.png)

Mr. Chu Button
![31777-sfl-far_east-mr_chu-button](https://user-images.githubusercontent.com/104640972/165993611-44844e8c-47e5-4e6e-a780-856d6f2a1afb.png)
![31777-sfl-far_east-mr_chu-button-8x](https://user-images.githubusercontent.com/104640972/165993142-e38be5fa-c3ae-4779-92ae-8301733fec59.png)

Mr. Chu Cart

![31777-sfl-far_east-mr_chu-cart](https://user-images.githubusercontent.com/104640972/166404632-3f3f72f0-ed45-415a-89b5-fd3d505b0b79.png)
![31777-sfl-far_east-mr_chu-cart-8x](https://user-images.githubusercontent.com/104640972/166404649-d3272ab1-5e86-41cf-94cb-c553286e8650.png)

Rice Bag
![31777-sfl-far_east-ricebag](https://user-images.githubusercontent.com/104640972/166404801-2762c351-4946-42dd-9297-602506801775.png)
![31777-sfl-far_east-ricebag-8x](https://user-images.githubusercontent.com/104640972/166404819-f15e0368-7b7d-42bf-8b5a-a2c34e5dbe4b.png)

Rice Bag Stack
![31777-sfl-far_east-ricebag-stack](https://user-images.githubusercontent.com/104640972/166404808-f5626565-ef22-4b54-b187-8cb408ded9d5.png)
![31777-sfl-far_east-ricebag-stack-8x](https://user-images.githubusercontent.com/104640972/166404826-567d66a2-e576-4f5c-876b-9ee4e8453f78.png)

Mr. Chu Flag
![31777-sfl-far_east-flag](https://user-images.githubusercontent.com/104640972/165993493-74fd3399-b054-4632-90f3-26bd61a91d16.png)
![31777-sfl-far_east-flag-8x](https://user-images.githubusercontent.com/104640972/165993364-e4c546d3-3b35-49b0-a246-767a37376919.png)

Mr. Chu Bench
![31777-sfl-far_east-bench](https://user-images.githubusercontent.com/104640972/165993464-5999e440-2b12-4dfa-b320-590d2faf55bb.png)
![31777-sfl-far_east-bench-8x](https://user-images.githubusercontent.com/104640972/165993448-df783018-27fe-44b9-a932-a3b07afcc220.png)

<hr>

LUNCHBOX's Farm ID: 31777
SuperSynapse's Farm ID: 27617
Discord: LUNCHBOX#0859
Discord: SuperSynapse#0786
Twitter: @LUNCHBOX_404
Twitter: @super_synapse

**Comment by SuperSynapse** [comment]
Here's the second part of this proposal!

Rather than having the NFTs craftable immediately, they can only be crafted after a series of quest progressions.

Quest #1
Partially touched on above, Mr. Chu needs each item from his restaurant to be crafted

**Comment by SuperSynapse** [comment]
Quest #3

**Comment by SuperSynapse** [comment]
Quest #4

**Comment by SuperSynapse** [comment]
**Mr. Chu Questline Finished:**

![31777-sfl-far_east-mr_chu-8x](https://user-images.githubusercontent.com/51135442/165995297-6a3741f0-6915-4a64-af70-914e3d0704e5.png)
![31777-sfl-far_east-4a-4x](https://user-images.githubusercontent.com/51135442/165995282-1badaf59-afa1-4363-971b-e2c643ac4604.png)
![31777-sfl-far_east-4b-4x](https://user-images.githubusercontent.com/51135442/165995341-eed84ad0-de01-42a3-ac8e-0b45d709e606.png)

At this point the player obtains rice seeds, unlocks rice seeds from the seed store, and unlocks the Guardian Lion Statue, Lucky Cat, and Pet Cricket as craft able NFTs from Mr. Chu's store.

![31777-sfl-far_east-guardian_lion](https://user-images.githubusercontent.com/51135442/165996539-f8796a45-4595-4d4d-921e-85f3955f3922.png)
![31777-sfl-far_east-lucky_cat](https://user-images.githubusercontent.com/51135442/165996545-dbaf979b-0875-4660-8a34-a791526a3642.png)
![31777-sfl-far_east-pet-cricket](https://user-images.githubusercontent.com/51135442/165996550-104370d0-cb38-4776-9e0e-377a39dbeea5.png)

We have some really cool ideas for these items, but don't want to get too far ahead of ourselves as this is a pretty long proposal as it is :D. We'd be very interested to hear ideas for these items, and what utility they could have besides decoration.

In addition, to sum up this post, here are the assets for the rice crop:

Empty Flooded Plot:
![Empty_Flooded_Plot](https://user-images.githubusercontent.com/51135442/165996174-0ea301d6-35fe-4cf8-82e4-cb70b5b31276.png)
![Empty_Flooded_Plot_Large](https://user-images.githubusercontent.com/51135442/165996183-1c9e9ee0-0c29-444b-9369-1dc9cb2db458.png)

Rice Seed:
![Rice_0](https://user-images.githubusercontent.com/51135442/165996203-2d35f35d-9305-48dc-85e0-3ad5a4577f87.png)
![Rice_0_Large](https://user-images.githubusercontent.com/51135442/165996209-dda6911f-4726-4c35-9bca-2bcfcb763c7b.png)

Rice Crop Growth 1:
![Rice_1](https://user-images.githubusercontent.com/51135442/165996261-931cedf4-47ee-4d60-9c8b-c1b603fecc48.png)
![Rice_1_Large](https://user-images.githubusercontent.com/51135442/165996269-3ef41c38-c4ce-4674-a68f-c23ebab73cc2.png)

Rice Crop Growth 2:
![Rice_2](https://user-images.githubusercontent.com/51135442/165996280-4a433f1a-e908-44d0-9d3f-d22ed820ec2e.png)
![Rice_2_Large](https://user-images.githubusercontent.com/51135442/165996298-90a7065d-37a2-45e9-9eb4-f4705e009319.png)

Rice Crop Growth 3:
![Rice_3](https://user-images.githubusercontent.com/51135442/165996310-3cb8532a-c905-45ca-ba73-1d9673561519.png)
![Rice_3_Large](https://user-images.githubusercontent.com/51135442/165996313-af6fc417-d7f7-4b2f-81fc-83d8c8645382.png)

Rice Crop Growth 4:
![Rice_4](https://user-images.githubusercontent.com/51135442/165996325-4ba59813-0eb6-442a-81c4-58f58084437d.png)
![Rice_4_Large](https://user-images.githubusercontent.com/51135442/165996334-f396c406-03e1-4b40-91a0-581abca7b0be.png)

Harvested Crop:
![Rice_5](https://user-images.githubusercontent.com/51135442/165996359-f0cdfcfb-e6e5-44f7-a4ec-0af3513dfeb4.png)
![Rice_5_Large](https://user-images.githubusercontent.com/51135442/165996369-26681cc3-85a2-46c3-9028-ab15ae189917.png)

**Comment by InuBakaBo** [comment]
OH wow.. this is probably the most effort of a proposal I have seen. Amazing work mate!

**Comment by DonatasDee** [comment]
Now THESE are the proposals that we need.

**Comment by 0xTuesdays** [comment]
Pretty amazing the time that was invested into this. Great stuff to the both of you. Would love to see this implemented.

**Comment by dujomaton** [comment]
Wow, very complete proposal. Love the idea of having more diversity in Sunflower Land (besides just humans + goblins). Art is next level, and being able to farm rice is a cool addition! Next level proposal!

**Comment by Gvstav0** [comment]
We need to reward true players. I really like the idea of quests. And you brought me something I wasn't thinking about: decoratives as rewards. This will create some sort of pride and story about your farm. In Clash of clans there are unique nfts that appear at your land and people use to let it there as souvenirs

**Comment by EB177** [comment]
This is an amazing proposal . Hoping it gets implemented ⭐️

**Comment by DragPlix** [comment]
Wow!! That's Amazing, would love to see this in-game! ⭐️ <3

**Comment by gavinrickard** [comment]
man some amazing stuff here LOVE IT !

**Comment by SopNami** [comment]
I love chinese culture and it is a very good proposal! Congratulations

**Comment by LUNCHBOX404** [comment]
@SopNami Thank you! I made Mr. Chu as a generic blend of Asian culture, mostly Japanese and Chinese. I'm American-Chinese myself! :)

**Comment by DeaerCui** [comment]
nice

**Comment by LeShykun** [comment]
This is some dope job ! Great job on making this, i believe these can also be used as a seasonal skins for the lunar year for example ! These skins should be considered into the game , wish u all the best😍

**Comment by someoneq** [comment]
这个风格太喜欢 ，石头狮子  招财猫。太有特色了！田园田园！
种豆南山下 
草盛豆苗稀 
晨兴理荒秽 
带月荷锄归

**Comment by SuperSynapse** [comment]
> 这个风格太喜欢 ，石头狮子 招财猫。太有特色了！田园田园！ 种豆南山下 草盛豆苗稀 晨兴理荒秽 带月荷锄归

Google Translation:

I like this style too, the stone lion lucky cat. So unique! Pastoral!
Planting beans at the foot of Nanshan Mountain
Caosheng bean sprouts thin
Morningside
Returning with a moon hoe

<hr>

Thankyou someoneq!!

**Comment by AkoSiBerto** [comment]
i love this it fits the SFL timeline

**Comment by yo121-eth** [comment]
```
wow that is a good idea, The first time I saw such a complete proposal and added more nft elements. And the quest chain is so creative. It's a great plan for a limited-time event! 
It is highly recommended to consider using this proposal!
```

**Comment by Unnamad** [comment]
That's a great idea. This should be taken seriously by officials

**Comment by zjg520** [comment]
good idea.i like very much

**Comment by David1983110** [comment]
This is the best proposal so far。

**Comment by BlockChainMeta** [comment]
Amazing work on this! All the positive comments are well-deserved.

**Comment by Netherzapdos** [comment]
Well done! Love the concept and designs, hope we can get more ideas like this 👍

**Comment by ShiningMinions** [comment]
This is a super cool idea and probably the best, well thought out, and implemented proposal. Some ideas I have for this too if it interests you. I think it would be cool if "Mr. Chu" randomly visited people's farms, instead of always being there. It makes a cool random event to happen. Or alternatively, make "Mr. Chu" a seasonal event of sorts. That would give the items much more uniqueness and scarcity.

**Comment by astardefi** [comment]
Very nice idea

**Comment by AncientHorse** [comment]
Wow, this took some serious work!  I like it all a lot.

**Comment by LUNCHBOX404** [comment]
And here's the Lucky Cat animated! (It's on a grass shadow)

![31777-sfl-far_east-luckycat-1x](https://user-images.githubusercontent.com/104640972/166129893-c7c4809f-bedd-450d-bdfa-6a13239cf8f9.gif)
![31777-sfl-far_east-luckycat-8x](https://user-images.githubusercontent.com/104640972/166129897-701e3ea0-c063-4b33-ae90-d536e799efb1.gif)

**Comment by SuperSynapse** [comment]
We also went ahead and did some additional work to make the **Pet Cricket** Animation. Here's the Cricket in the cage:
![Pet-Cricket-animation](https://user-images.githubusercontent.com/51135442/166129898-1e2f09c1-1433-4b88-be4c-454ea83d99c6.gif)
![Pet-Cricket-animation_Large](https://user-images.githubusercontent.com/51135442/166129899-2e1e87a8-428c-46d8-80f0-1d201a2bc69e.gif)


Our proposed utility is that every so often (lets say 1 hr) if you click on the cricket he will hop around and find a random seed for you (highlighted in yellow). When you click on the seed he goes back into his cage:

![Pet-Cricket-animation_Jumping_WITH_Seed](https://user-images.githubusercontent.com/51135442/166129942-bc3b9cf7-36b9-4686-9bb6-c53b8968f97d.gif)
![Pet-Cricket-animation_Jumping_WITH_Seed_Green_Large](https://user-images.githubusercontent.com/51135442/166129946-567149a1-77c1-4da4-a95f-72c23244396f.gif)

**Comment by baron** [comment]
This has to be the most amazing proposal I've seen. Love every aspect of it and those NFTs are fire!

**Comment by Aminbtdds** [comment]
Great job👏👏👏🍻

**Comment by spencerdezartsmith** [comment]
This is mind blowing 🤩 ❤️

**Comment by Joreee** [comment]
I made a github account to personally thank you for this art proposal. looks really awesome!

**Comment by SuperSynapse** [comment]
> I made a github account to personally thank you for this art proposal. looks really awesome!

Wow, that's quite a compliment! Thankyou!!!

**Comment by SuperSynapse** [comment]
@LUNCHBOX404 and I added a few updates in the previous posts:

- Updated Mr. Chu to a better top-down view with detail.
From this:
![31777-sfl-far_east-mr_chu-8x](https://user-images.githubusercontent.com/51135442/166516673-9aff45cc-cc1e-4b8e-8b3a-728c3284789f.png)
To this:
![31777-sfl-far_east-mr_chu-8x UPDATED](https://user-images.githubusercontent.com/51135442/166516711-d3b87666-c14b-4026-a858-af848b5a00e6.png)

- Updated animations for **Lucky Cat** and **Pet Cricket**
- Updated a few assets such as **Mr. Chu's cart** with shadows and tweaks
- Added Proposed utility and descriptions for the **Lucky Cat**, **Pet Cricket**, and **Guardian Lion**:

**Guardian Lion Statue**
_An intimidating creature._
Proposed Utility: +200% Defence (could be used for future combat like mutant crops, or base raids)

**Lucky Cat**
_Brings you good fortune._
Proposed Utility: Boosts rice crop harvests by a random 20% - 80%

**Pet Cricket**
_A helpful critter._
Proposed Utility: When clicked, hops around and finds a free random seed (with cooldown)

**Comment by SuperSynapse** [comment]
We realize this post has been closed/completed.

Due to the new standard of using Aha, we added updates such as a few tweaks, animations, and the finished water wheel for flooding the rice plain.

For anyone referencing this page for make sure to visit our continued update here: https://sunflower-land.ideas.aha.io/ideas/SFL-I-127
