### ISSUE TITLE
[PROPOSAL] Clan System

### ISSUE THREAD

**Issue by Ozweeg** [sunflower-land/sunflower-land#748]
Hi guys,
First of all, sorry for my bad england, i dont use google translate =)

I would like to see a clan system in the game. I think this innovation can improve daily online and people will start spending more time in game because of a lot of new everyday activities as daily clan tasks, shared resource pool and many other features.
I was thinking about it and came to the conclusion that clan system has unlimited development possibilities
For the start, I would like to offer you my thoughts on the implementation of some ideas

-------------------------------------------------------------------------------------------------------------------------------
1)New building "Clan Hall" with all information about ur clan or with research bar where u can find a clan to join

2)Everybody can create clan, but it will cost him "N(from 10 to 50)" SFL and the number of clans will be limited for the first time(up to 1k for example), max members in clan will be limited too and it will rise along with the rise of the clan level

3)U can choose any clan name and clan flag(moreover, u can add an opportunity to create ur own clan flag using .png file) and this flag will be set at clan member's farms near the Clan Hall

4)After creating clan, clan owner can make it "public" or "private"(sending request to join), set the minimum farm level for players who want to join his clan, appoint one member of the clan as his deputy and grant him the rights of the head of the clan in case of his departure, make a clan description with useful information(links, rules...)

5)Clan owner can set as well as the membership fee for joining, and the daily mandatory fee in tokens or resources

6)Clan will have its own pool of resources and SFL tokens that only the head of the clan can manage. It can be used in a lot of ways:

- Generall staking with bigger %APY
- Sending resources or SFL tokens to the clan member who needs it in the mose(but in little amounts with a strict daily limit)
- Crafting clan NFT's which will give bonuses to clan members, open up new opportunities for clan development, etc.

7)System of clan levels. Every clan member earn clan xp points for each his actions on the farm. Each new clan level will give its members a small buff to harvest, animal husbandry, tree felling, etc.

8)Daily clan tasks can help its members to improve clan level faster, task for example for clan with 10 people: Grow 150 pasternak, completing this task gives for the clan "N" XP point

7)Clan leaderboard, based on clan level

8)When a player joins an already developed clan, it will be necessary to make a linear unlock of clan bonuses
-------------------------------------------------------------------------------------------------------------------------------

This is just my initial ideas about clan system, but i think that this innovation has a lot of positive consequences:

**1. First of all, clan system will give a start to in-game communities for general development(i think this is the most important)
2. Token burning, based on crafting clan nft's
3. Improving daily online by adding more features and activities to the game**

**Comment by samadi307** [comment]
The same of this Game hahaha
I like this <3
![image](https://user-images.githubusercontent.com/53188622/166110510-31070914-fd9f-4ad3-be93-de5983398e50.png)

**Comment by ahh1539** [comment]
So a pyramid scheme clash of clans game? Seems that there is not much benefit for the average player and mostly just the clan leader benefits.

**Comment by Ozweeg** [comment]
> So a pyramid scheme clash of clans game? Seems that there is not much benefit for the average player and mostly just the clan leader benefits.

I dont think that clan leader has a lot of benefits, because i offered to create a clan with max 10 clan members, where everybody always communicate each other and make decisions about crafting nft's/sending resources together
