### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by Slypher** [sunflower-land/sunflower-land#75]
Hi Guys! 👋

I would like to change the game language, I looked at the source code and I didn't find support for translations, do you plan to implement this? I can translate to pt-br, I see many Brazilian players entering the game and the translation would facilitate the gameplay.

**Comment by MrRemiB** [comment]
+1, ready to translate to fr-FR

**Comment by chris-calo** [comment]
Would be sweet, but will require us to pull the strings out. I may own this later this week/next, once we get ahead on a few other things, as I do a lot with i18n. At any rate, I'll provide a de-DE translation when the time comes.

**Comment by chris-calo** [comment]
@Slypher @MrRemiB have either of you translated applications before? Any preference for collaboration method? I prefer [Lokalise ](https://lokalise.com/), but it's probably too expensive for our needs.

**Comment by MrRemiB** [comment]
Google sheet would be ok

**Comment by mattheuspirovani** [comment]
I can help with pt-BR too. @Slypher we can make the translation more regional, would be funny.

**Comment by Slypher** [comment]
> @Slypher @MrRemiB algum de vocês já traduziu aplicativos antes? Alguma preferência pelo método de colaboração? Eu prefiro [Lokalise](https://lokalise.com/) , mas provavelmente é muito caro para nossas necessidades.

I could contribute here with a pull request. There are also tools like the [webplate](https://weblate.org/pt-br/)
