### ISSUE TITLE
Remove Blackliste

### ISSUE THREAD

**Issue by Girish143566** [sunflower-land/sunflower-land#750]
I bought blacklisted land by mistake so please help me kindly remove Blackliste
![Screenshot_2022-04-30-09-40-14-42_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/70050875/166091991-92d59419-1594-4af4-b3c0-5aab87a5eb18.jpg)

**Comment by 17ss** [comment]
请点击"继续玩"
please click "Continue Playing"

**Comment by Kubeki** [comment]
> 请点击"继续玩" please click "Continue Playing"

Best answer by far

**Comment by Girish143566** [comment]
blacklist remove from my land please
Tell me one thing Whether or not to remove the blacklist answer me

**Comment by Girish143566** [comment]
I bought blacklisted land by mistake please remove Blackliste blacklist
remove from my land please
Tell me one thing Whether or not to remove the blacklist

answer me

My farm all contacts ID
Farm Number - #70944
Wallet address - 0x4B6DD037952fDb4Bcae6A866c27b456f5520E6AC
Transaction ID
- 0xf6ee5cb883c13560fab443ba1cf562a9eeba566ae2ad491934efafc476cb273f

**Comment by alvinphoebeartemis** [comment]
Hi @Girish143566 , we encourage you to create a ticket in this link for your issue. https://sunflowerland.freshdesk.com/support/solutions

This GitHub Repo is used for development purposes. Thank you very much.

**Comment by adamhannigan** [comment]
@Girish143566 Unfortunately this is buyer beware. You need to ensure the farm is not blacklisted if buying of someone.

In this case I would suggest asking for a refund from the person who sold it to you (if they misleading said it was not blacklisted)
