### ISSUE TITLE
We made the sunflower market（https://sunnymarket.club）

### ISSUE THREAD

**Issue by 842038707** [sunflower-land/sunflower-land#751]
Hello, we have made a special sunflower trading market, and we see that the official cooperation market will be launched at the end of May. Our players can't wait to make a deal, and I don't know if we can make a cooperation.
[https://sunnymarket.club](url)

**Comment by 842038707** [comment]
[https://sunnymarket.club](url)

**Comment by adamhannigan** [comment]
@842038707 Good to see ideas spinning off.

We encourage decentralised development but unfortunately cannot endorse or share any secondary links that have not been verified and audited properly.

Is the purpose of this to trade crop based resources of NFTs? If NFTs, what is the current problem with Open Sea?

**Comment by xiaoqiu06** [comment]
> @842038707很高兴看到联合发展。
> 
> 我们去鼓励中心化悲哀的是不能承认或分享任何但适当的评估和评估的证明。
> 
> 是为了交易判断基于 NFT 的资源吗？如果 NFT，Open Sea 当前的目的是什么？

opense can only hang at least 5U

**Comment by LeShykun** [comment]
Opensea kinda limit selling some resources like wood / stones / gold / axes ( you can't just sell 1 wood for $5 ), and the selling fees is kinda *meeh* 12.5% for each nft u sell is huge ! looking forward to trade on rarity ! the website of xiaoqiu06 is exactly what we need, paying with stable coins (usdt) and no fees! can you make an english version @xiaoqiu06 ?

**Comment by LeShykun** [comment]
Website working smoothly! ( https://polygonscan.com/tx/0x40a3a30c8dd4068c9fcbed9b3dec2083f64639652f549f1688f905aebe2eef10 )
 
 i can't believe i actually just bought 290 wood for $0.15 per unit this is amazing ! Any idea how can i list some items for sell on ur website? @xiaoqiu06

**Comment by LeShykun** [comment]
I still agree with Adam, if you can get audited and doxed i guess we can just use ur website for the time being until we get a proper marketplace on rarible !

**Comment by brian-man** [comment]
> Hello, we have made a special sunflower trading market, and we see that the official cooperation market will be launched at the end of May. Our players can't wait to make a deal, and I don't know if we can make a cooperation. [https://sunnymarket.club](url)

Is there a good reason the contract source isn't verified and published?
https://polygonscan.com/address/0x829bcb108b6158841e773ae2f001d4ca2032f024#code

**Comment by brian-man** [comment]
Brief analysis of the site:

The webpage source is pretty readable once you pretty-print it.  Functions such as `buy()` are easy to find, and a number of ABI json blocks are easily findable too.

Seller listing items
1. `setApprovalForAll()` on SLI address for the market
2. `createAsk()` on the market
    - `createAsk(address[],uint256[],uint256[],uint256[],address[],uint256[])` => `0x3bae2812`

Buyer purchasing items
3. `approve()` on the USDT or Matic address for the market
4. `acceptAsk()` for farms or `acceptAskToFarm()` for (N)FTs on the market
    - `acceptAsk(bytes32[],address[])` => `0xb9e722e7`
    - `acceptAskToFarm(bytes32[],address[])` => `0x75f53964`

Seller risk:
- contract source is not public, and uses a proxy
- `setApprovalForAll()` is pretty risky
- using the contract directly a narrower `approve()` might be sufficient; also perhaps revoking the approval immediately after the accept transaction[s]

Buyer risk:
- contract source is not public, and uses a proxy
- make sure you double-check the `approve()` amount
- make sure you're ok with the 5% fee
