### ISSUE TITLE
About The NFTs

### ISSUE THREAD

**Issue by David1983110** [sunflower-land/sunflower-land#752]
I'd like to know when it's going to do the empowerment ，I purchased three SFL Rock and so many other NFTs，Its current price is distressing to me。
Most of the NFTs are currently in decline ，because they are not as functional as the multiple players who own a few more plots。
so，i think，The team currently has an urgent need to enhance the functionality of NFTs。
Sorry, my English is very poor，I can only translate through software，

**Comment by xZ3D** [comment]
Not every NFT has a boost, some are just for decoration and should only be bought for that purpose.

**Comment by adamhannigan** [comment]
Hey @David1983110 Great to hear you have been getting involved in the project.

As @xZ3D some NFTs are purely decorative. Some of the current NFTs may or may not have functionality in the future - for all intents purposes you should consider these as decorative.

The price of an NFT will never influence whether an item earns a boost or not. We build the game, the community decides the prices. I hope you understand 😄

**Comment by David1983110** [comment]
Ok，Thank you for your reply 。
