### ISSUE TITLE
anti-bot system

### ISSUE THREAD

**Issue by dnavamosler** [sunflower-land/sunflower-land#753]
I found a handful of vulnerabilities, in fact I managed to create a script that can automate the whole process including skipping the captchas... I would like to collaborate to solve these bugs, I am an expert in frontend and I am dedicated to finding vulnerabilities. sorry for my english, use the translator.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
