### ISSUE TITLE
[IDEA] Wishing Well bonus for NFT Collectors

### ISSUE THREAD

**Issue by rodolfoddias0x** [sunflower-land/sunflower-land#754]
1- NFT owners are one the most enthusiastic players and along with liquidity providers they support the game's economy demanding resources from other players besides producing their own. 
2- Due the halving system, it will get harder to farm SFL through crops with time. 
3- This means that liquidity provision could turn into an effective way to farm SFL to keep farming resources in game. 

**What if we could link the NFTs you own in your farm with Wishing Well rewards?** 
Collectors would support the game entirely and would be rewarded for it. This way we could have increased demand for all NFTs and resources in game plus increased liquidity, both extremely relevant to support the game’s economy.

What makes the value of a NFT?
1- The NFT's **total supply** (rarity)
2- The **time** you need to collect the resources needed
3- The amount of **SFL** you spend to craft it

According to the total points the farm has, its owner could receive bonus rewards when making wishes to the well. The only way to take advantage on the rank would be providing liquidity to the game, which would benefit our economy. It shouldn't be a problem for those players, since they surely are committed to the game since they're collecting NFTs.

**Comment by xiaoqiu06** [comment]
This is the case, if there is no NFT holding amount reward, such as competition reward, no one will be willing to mint those NFTs, maybe the official has not realized these problems, they are too idealistic.

**Comment by dongdong-gitt** [comment]
agree

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
