### ISSUE TITLE
[BUG REPORT] Golden Cauliflower.

### ISSUE THREAD

**Issue by aminoz12** [sunflower-land/sunflower-land#755]
Hello Devs @adamhannigan, Lately i was thing about the Golden cauliflower, it's kind of dangerous. Imagine one of us having it and then going to the black market, buy all the cauliflowers there, then selling them on the game shop it's going to crush the earning in the game.

**Comment by NoisyBucheron** [comment]
The golden cauliflower bonus should be modified to "Yield 100% more crops" instead of augmenting the crop reward in the shop to prevent this

**Comment by DonatasDee** [comment]
That's not how it works to begin with lol. You just get twice as many is how it works.

**Comment by NoisyBucheron** [comment]
> 

Is it's the case the description is not well done as Scarecrow does the same thing.

![image](https://user-images.githubusercontent.com/104263513/166121867-dd9209f1-60a9-4c84-a9d0-17723d3fabd9.png)
![image](https://user-images.githubusercontent.com/104263513/166121870-c31e6d03-b47c-471c-b4ca-0924ff9f5592.png)

**Comment by aminoz12** [comment]
> That's not how it works to begin with lol. You just get twice as many is how it works.

the description said "DOUBLE THE REWARDS FROM CAULIFLOWERS". if i bought cauli from someone i'll sell them x2

**Comment by DonatasDee** [comment]
> 

No.

**Comment by NoisyBucheron** [comment]
> > > That's not how it works to begin with lol. You just get twice as many is how it works.
> > 
> > 
> > the description said "DOUBLE THE REWARDS FROM CAULIFLOWERS". if i bought cauli from someone i'll sell them x2
> 
> No. I know because a friend has one.

Then it's confirmed there is no problem with it, just a description that is not correct

**Comment by Aminbtdds** [comment]
It implies you get 60% on cauli instead of 30%, doesn't imply ur harvested caulis.
I guess the text should be corrected.

**Comment by adamhannigan** [comment]
Yes this is just a text description bug. You get double the cauliflowers when harvesting, not when selling

**Comment by pinkopero** [comment]
how about kuebiko? after buy seed free price, transfer another wallet and do it repeat. is it possible?

**Comment by pinkopero** [comment]
and t3 beaver has same problem i thought.
cut the wood for free and then transfer another friends wallet. it makes free wood with small gas fee.

**Comment by NoisyBucheron** [comment]
> how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?

No, seeds are not tradable. And there are only 200 kuebiko in 100000 players.

**Comment by NoisyBucheron** [comment]
> and t3 beaver has same problem i thought. cut the wood for free and then transfer another friends wallet. it makes free wood with small gas fee.

Same as kuebiko, the supply 300 players in 100000+ was studied to don't impact the wood supply

**Comment by pinkopero** [comment]
> > 쿠에비코 어때요? 시드를 무료로 구매한 후 다른 지갑을 옮기고 반복합니다. 가능합니까?
> 
> 아니요, 씨앗은 거래할 수 없습니다. 그리고 100,000명의 플레이어 중 200명의 kuebiko만 있습니다.


i mean i bought for free seed with kuebiko

> > how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
> 
> No, seeds are not tradable. And there are only 200 kuebiko in 100000 players.

no I didnt mean seed trading.  for example I bought all seed (1 sync) with kuebiko, and transfer kuebiko other session(friends or self) and buy all seed for free.

**Comment by NoisyBucheron** [comment]
> > > 쿠에비코 어때요? 시드를 무료로 구매한 후 다른 지갑을 옮기고 반복합니다. 가능합니까?
> > 
> > 
> > 아니요, 씨앗은 거래할 수 없습니다. 그리고 100,000명의 플레이어 중 200명의 kuebiko만 있습니다.
> 
> i mean i bought for free seed with kuebiko
> 
> > > how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
> > 
> > 
> > No, seeds are not tradable. And there are only 200 kuebiko in 100000 players.
> 
> no I didnt mean seed trading. for example I bought all seed (1 sync) with kuebiko, and transfer kuebiko other session(friends or self) and buy all seed for free.

You will do this for 2 or 3 friends maybe?
Then you will get banned for multi account after 2 or 3 days transfering to the same accounts probably in a loop

**Comment by pinkopero** [comment]
> > > > 쿠에비코 어때요? 시드를 무료로 구매한 후 다른 지갑을 옮기고 반복합니다. 가능합니까?
> > > 
> > > 
> > > 아니요, 씨앗은 거래할 수 없습니다. 그리고 100,000명의 플레이어 중 200명의 kuebiko만 있습니다.
> > 
> > 
> > i mean i bought for free seed with kuebiko
> > > > how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
> > > 
> > > 
> > > No, seeds are not tradable. And there are only 200 kuebiko in 100000 players.
> > 
> > 
> > no I didnt mean seed trading. for example I bought all seed (1 sync) with kuebiko, and transfer kuebiko other session(friends or self) and buy all seed for free.
> 
> You will do this for 2 or 3 friends maybe? Then you will get banned for multi account after 2 or 3 days transfering in a loop to the same accounts probably , but nice catch there

yeah thats what im saying. if multi account bot users doing this, it will bring market crash.

**Comment by NoisyBucheron** [comment]
> > > > > 쿠에비코 어때요? 시드를 무료로 구매한 후 다른 지갑을 옮기고 반복합니다. 가능합니까?
> > > > 
> > > > 
> > > > 아니요, 씨앗은 거래할 수 없습니다. 그리고 100,000명의 플레이어 중 200명의 kuebiko만 있습니다.
> > > 
> > > 
> > > i mean i bought for free seed with kuebiko
> > > > > how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
> > > > 
> > > > 
> > > > No, seeds are not tradable. And there are only 200 kuebiko in 100000 players.
> > > 
> > > 
> > > no I didnt mean seed trading. for example I bought all seed (1 sync) with kuebiko, and transfer kuebiko other session(friends or self) and buy all seed for free.
> > 
> > 
> > You will do this for 2 or 3 friends maybe? Then you will get banned for multi account after 2 or 3 days transfering in a loop to the same accounts probably , but nice catch there
> 
> yeah thats what im saying. if multi account bot users doing this, it will bring market crash.

They will get banned asap by the bot ingame anyways.
But it will be a good idea to put a withdraw block for 24h after you transfer a kuebiko to prevent this.

**Comment by pinkopero** [comment]
> > > > > > 쿠에비코 어때요? 시드를 무료로 구매한 후 다른 지갑을 옮기고 반복합니다. 가능합니까?
> > > > > 
> > > > > 
> > > > > 아니요, 씨앗은 거래할 수 없습니다. 그리고 100,000명의 플레이어 중 200명의 kuebiko만 있습니다.
> > > > 
> > > > 
> > > > i mean i bought for free seed with kuebiko
> > > > > > how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
> > > > > 
> > > > > 
> > > > > No, seeds are not tradable. And there are only 200 kuebiko in 100000 players.
> > > > 
> > > > 
> > > > no I didnt mean seed trading. for example I bought all seed (1 sync) with kuebiko, and transfer kuebiko other session(friends or self) and buy all seed for free.
> > > 
> > > 
> > > You will do this for 2 or 3 friends maybe? Then you will get banned for multi account after 2 or 3 days transfering in a loop to the same accounts probably , but nice catch there
> > 
> > 
> > yeah thats what im saying. if multi account bot users doing this, it will bring market crash.
> 
> They will get banned asap by the bot ingame anyways. But it will be a good idea to put a withdraw block for 24h after you transfer a kuebiko to prevent this. @adamhannigan what do you think?

I think that's not enough time. 
![1651421463917](https://user-images.githubusercontent.com/104716892/166154681-aca2cfd9-da52-4777-be7f-ecd03a91e53c.png)

5-6 days perfect but about 3 days ok.
or 
find other ways to prevent abuse.

**Comment by brian-man** [comment]
> how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
The code already protects against withdrawing while you have seeds or crops.

**Comment by brian-man** [comment]
> and t3 beaver has same problem i thought. cut the wood for free and then transfer another friends wallet. it makes free wood with small gas fee.

The code already protects against withdrawing Foreman while you have un-replenished trees.

**Comment by NoisyBucheron** [comment]
> > how about kuebiko? after buying seed for free, transfer another wallet and do it repeat. is it possible?
> 
> The code already protects against withdrawing Kuebiko while you have seeds or crops.

And you can't even withdraw seeds in sunflowerfarm.

**Comment by adamhannigan** [comment]
@NoisyBucheron You cannot withdraw Kuebiko while you have unplanted seeds on your farm 😄

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3
