### ISSUE TITLE
[ART] Mushroom NFTs

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#756]
This is a request for mushroom based NFT items to craft. We don't have an exact date on the mushroom launch but we want to launch mushroom gathering in stealth over the next 2 weeks.

We are looking for some initial community NFTs to showcase that are mushroom related 🤗 

Related: https://github.com/sunflower-land/sunflower-land/issues/164

**Requirements**

- Minified art submission
- Dimensions and colour palette match the gameplay
- Screenshot of the asset used in the game
- Requires mushroom to craft

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

Note: Your art & mechanic may be modified/altered by the community if needed.

**Deadline**

7th May. The actual launch date of the mushroom feature remains to be surprise 🤫 

**Prize**

You will receive accreditation for your art in Open Sea (and our upcoming town hall 😏 )

You will get your design airdropped to your farm (Rarity of items will differ amongst winners)

**Winners**

Ideally we are looking for 2 winning designs for Season 1. Runner ups will likely make it into Season 2 gameplay.

The winners of this competition will be chosen by core team, as the release of this feature will require a bit of stealthness.

**Comment by eArL2384** [comment]
heres a mushroom skewer 
![1651369018359](https://user-images.githubusercontent.com/104702521/166128570-e26d8ff3-17d4-43d1-b6f4-158ae8b61031.gif)

**Comment by NoisyBucheron** [comment]
![image](https://user-images.githubusercontent.com/104263513/166128922-65c1559c-7117-4b83-a461-9b866517fc83.png)
![mushroom 2](https://user-images.githubusercontent.com/104263513/166128929-4a5d5ecd-5249-4ca4-9f4f-15e4f822b2da.png)
![image](https://user-images.githubusercontent.com/104263513/166128943-190dac96-25b4-4e2b-8cb1-2a0b43614a50.png)

In case you guys don't have the mushroom model yet!

**Comment by SrCouve** [comment]
![Mush](https://user-images.githubusercontent.com/98098233/166129554-3ff487cd-d73d-4172-9ac3-a51ebcfcb647.gif)
![mush big](https://user-images.githubusercontent.com/98098233/166129555-0a8efd81-35bc-4739-8f4d-2283cbf52a6a.gif)

**Comment by NoisyBucheron** [comment]
The Mushroom soup:
![mushroom soupsmall](https://user-images.githubusercontent.com/104263513/166129549-b63f073b-008f-48c3-b2ab-2acfb4779ee8.png)
![mushroom soupbig](https://user-images.githubusercontent.com/104263513/166129513-dba5e5c0-a157-4e4d-b141-f3f5edb70578.png)
![image](https://user-images.githubusercontent.com/104263513/166129527-90558859-72cd-40bf-af30-b42cd393b19f.png)

**Comment by cargomesplay** [comment]
Arte fixa
O tamanho pode ser ajusto para melhor visual no game
![cogumelo-arte](https://user-images.githubusercontent.com/104114336/166130053-da24a377-e7ed-4035-b6cc-1e5f067a7050.png)


Arte animada 

![cogumelo2](https://user-images.githubusercontent.com/104114336/166129819-7582db21-1449-4742-921d-670843810628.gif)
![cogumelo2-big](https://user-images.githubusercontent.com/104114336/166129820-fe952d01-eea2-49b2-b10d-7a429d82b0ea.gif)


Farmer id: #29147
wallet in game farm: 0xb0E023545A38F10b6C787f37648695137aD94A91
wallet: 0xf06a69aCa1BB0182F1D1CB188E052A8FB1C71295

twitter
https://twitter.com/cargomesplay

discord: carloshq#3347

**Comment by block-kid** [comment]
A mushroom farm! 

I probably wouldn't eat red spotty mushrooms... but who know what young goblins get up to these days 😜 

Crafted using wood + mushrooms

Gives greater mushroom yields or faster growth.

![Screenshot 2022-05-01 132924](https://user-images.githubusercontent.com/102010324/166130996-8a4a1d35-f0d4-446b-80b7-257a2b00b9cd.png)

![Screenshot 2022-05-01 124238](https://user-images.githubusercontent.com/102010324/166131433-2d2a1b5a-90c2-4714-ae4d-b1b21e396096.png)

Farm ID: #999
Wallet: 0x41ca85eFcd4Df1599C97F40cbE5A64A412baEE5D
Discord: block_kid#0560

**Comment by gd-cloud** [comment]
We all know goblins love soup... 

![mushroom](https://user-images.githubusercontent.com/103484522/166131963-fe063626-eba7-4952-a1e3-9927e3173564.png)

![mushroo128l](https://user-images.githubusercontent.com/103484522/166131973-4de1261e-c440-41fb-aa28-c5104dd2194c.png)

![mushroomsoup1ol128](https://user-images.githubusercontent.com/103484522/166131981-95ad2051-396a-4eb2-b22d-404c1b56c44a.png)

![mushroomsoup2ol128](https://user-images.githubusercontent.com/103484522/166131987-466e82ef-f7ce-4bc2-a1fb-5a7d2442bd6b.png)

**Comment by gd-cloud** [comment]
Giant Mushroom Trampoline. 

![mushroom trampoline](https://user-images.githubusercontent.com/103484522/166139132-d9bf85eb-1fdd-4c84-9053-798b4bca563b.gif)


![trampoline_big](https://user-images.githubusercontent.com/103484522/166139336-36ff7fc0-03c2-4b91-a6fe-1697e3d19c9c.gif)

Farm ID #424
Discord gdcloud#1880

**Comment by Kerkus7** [comment]
![mushroom_kit_raw](https://user-images.githubusercontent.com/89840587/166141636-c49ed419-6846-4836-abf6-bb804cace933.png)

![mushroom_kit_raw_large](https://user-images.githubusercontent.com/89840587/166141849-cb4c0a5a-d530-4914-9f50-e44b8f1aac6c.png)


![mushroom_incorporated](https://user-images.githubusercontent.com/89840587/166141650-570d2af3-2452-466c-a0ed-1ed1cbe379f6.png)

Mushroom growing chamber! increases yield slightly like the easter bunny :)

wallet: 0x5aE57CA933c4493485235B46E7955C30f89FcEFB
discord: Kerkus_#2963

**Comment by Kerkus7** [comment]
![mush_lowres_raw](https://user-images.githubusercontent.com/89840587/166143691-f4f10639-02fe-4f76-94bf-2a3b9d7848a8.png)

![mush_lowres_raw_large](https://user-images.githubusercontent.com/89840587/166143695-5cdac5c3-e77d-4025-8db9-cafc0da0fa1c.png)

![mushroom_kit_lowres_incorporated](https://user-images.githubusercontent.com/89840587/166143687-873871bd-a5a5-4221-9cc7-8a8b50330846.png)

rework because the pixels weren't quite right. this one blends in a bit better.

wallet: 0x5aE57CA933c4493485235B46E7955C30f89FcEFB
discord: Kerkus_#2963

**Comment by NoisyBucheron** [comment]
Mushroom statue
![mushroomstatue500](https://user-images.githubusercontent.com/104263513/166145614-19456b49-8de6-48c8-920f-b0f25465d531.png)
![mushroomstatue](https://user-images.githubusercontent.com/104263513/166145616-6dfabd41-ff7e-482f-980a-3ab595f6b25c.png)
![image](https://user-images.githubusercontent.com/104263513/166145636-bf2af338-486d-4d87-813e-b00588de6f5a.png)

ID farm: 264
Twitter: https://twitter.com/BforBruno

**Comment by zxearl** [comment]
Mushroom Chair Umbrella
![pixel-25x25](https://user-images.githubusercontent.com/104722435/166147564-04784f70-752e-4369-9e7e-a5dc1e28b1eb.png)
![Capture-removebg-preview (1)](https://user-images.githubusercontent.com/104722435/166147596-c4780e79-7d7a-4d9b-94ee-254296a95d10.png)
![Capture sdsad](https://user-images.githubusercontent.com/104722435/166147620-1c678b9f-443c-4b34-98b5-800b277632e7.PNG)

ID Farm: 11956
Discord: Zxearl#9817
Polygon: 0x5B1B0C2122C015d583886a4F246bA6d709e53968

**Comment by NoisyBucheron** [comment]
Golden Mush!
![goldenmushroom100](https://user-images.githubusercontent.com/104263513/166150333-400aa8b6-14f1-40f2-a420-02178bc9cf18.gif)
![goldenmushroom500](https://user-images.githubusercontent.com/104263513/166150287-2b9cd728-7b95-4adf-9f1e-811a73df3b7e.gif)

**Comment by gd-cloud** [comment]
Golden Mushroom

![golden_mushroom0128](https://user-images.githubusercontent.com/103484522/166150504-98a726ba-0c3d-4ae4-8c04-e72b8821cc7c.png)

![golden_mushroom1128](https://user-images.githubusercontent.com/103484522/166150508-fcdf3d15-683a-45c0-bc8d-13ed537e833e.png)

Farm ID 424
Discord gdcloud#1880

**Comment by zxearl** [comment]
Mushroom Log
use to grow mushroom from spores, one log can grow up to 5 mushroom
x50 wood x30 mushroom spore x20 SFL
![pixil-gif-drawing (6)](https://user-images.githubusercontent.com/104722435/166155931-368162c4-09f3-4178-aa30-34d905152435.gif)


![pixil-gif-drawing (7)](https://user-images.githubusercontent.com/104722435/166155959-a492c242-9b6c-4180-9288-9b96a3649e5c.gif)

![Pixilart Sprite Sheet (2)](https://user-images.githubusercontent.com/104722435/166155977-3e920e76-46cd-4243-a2ef-00e3c32166e0.png)

![MGL](https://user-images.githubusercontent.com/104722435/166155983-2d4933ce-0dea-480d-aaf5-b49f63942c6c.PNG)
 
ID Farm: 11956
Discord: Zxearl#9817
Polygon: 0x5B1B0C2122C015d583886a4F246bA6d709e53968

**Comment by tryjapa** [comment]
Mushroom box enable the ablity to plant and harvest mushroom 
Max 3 per farm.
Craft items > Wood, SFL and mushroom.

Display it on the autumn part of the map

![mushroombox](https://user-images.githubusercontent.com/9723813/166169932-080cb494-4028-4c69-b94d-112e413ab9ec.gif)
![Sprite-0001-Recovered](https://user-images.githubusercontent.com/9723813/166170103-83c653ee-d55c-42f7-88dd-cbf55bf51c6e.gif)

![CloseView](https://user-images.githubusercontent.com/9723813/166170892-65033aff-90fa-40c1-8780-04d658d71849.png)
![mapview](https://user-images.githubusercontent.com/9723813/166170896-ba574ef1-3451-4703-a9fe-be5ff7356213.png)

Farm ID : 315
Wallet: 0xfeA5a8239c1Bceb0DA8E378d57B6496D3c16bEe6
Discord: tryjapa#9936

**Comment by Vergelsxtn** [comment]
![MushroomPreview](https://user-images.githubusercontent.com/99605039/166177569-4d98cb8a-c5fa-41d9-8516-a77d4625b28c.png)

Normal size
![MushroomgardenV2](https://user-images.githubusercontent.com/99605039/166177633-ae08ada1-a131-424e-a17f-4154b1a93414.png)


Preview
![MushroomPreview(1)](https://user-images.githubusercontent.com/99605039/166177600-2f4a5811-0622-49d4-bcda-a89d950ae589.png)

**Comment by LittleEins** [comment]
Mushroom Hunter / Vendor
Preview
![image](https://user-images.githubusercontent.com/104184348/166182862-bdaf2a85-2e6f-40ff-9f86-5d29e00851a2.png)
1000% size
![Mushroom Vendor](https://user-images.githubusercontent.com/104184348/166182868-495a0a4d-f467-4318-a50c-408bf27bbdc0.png)
Actual Size
![Mushroom Vendor-1](https://user-images.githubusercontent.com/104184348/166182972-7d2135c3-ae8c-4eca-9803-205dcb41ef9f.png)

Farm ID : #73795
Wallet: 0xd7A83720DD51EA74E2156dFfDC0d271b380d0635
Discord: LittleEinstein#0439

**Comment by paluras** [comment]
![image](https://user-images.githubusercontent.com/98059798/166224178-0b932f7b-36b8-41c1-ac70-b0a54d40e9df.png)

![Mush](https://user-images.githubusercontent.com/98059798/166224126-e2bbd6ff-5274-4344-ab6d-6cb7cef9ad7d.gif)
![Mush1](https://user-images.githubusercontent.com/98059798/166224129-9f9e7748-be22-4d67-814a-f33c23376106.gif)

**Comment by gd-cloud** [comment]
Mushroom house.
Requires wood, mushrooms and stones. Im sure there is a busy goblin inside...

![mushroomhouse](https://user-images.githubusercontent.com/103484522/166224658-0a625621-2723-4ccf-88b6-e997fd14b696.png)

Farm ID 424
Discord gdcloud#1880

**Comment by esp123** [comment]
![mushroom](https://user-images.githubusercontent.com/74337946/166245683-8d2f519a-40eb-4f09-bd00-248565f7e74d.png)
Mushroom-drying-rack...

**Comment by tryjapa** [comment]
Add a few mushroom on winter environment 

![mushroom-snow-real](https://user-images.githubusercontent.com/9723813/166346509-69c3728f-6078-4b85-aaa3-be00431d4297.png)
![mushroom-snow-zoom](https://user-images.githubusercontent.com/9723813/166346812-850a99ab-a694-4235-8c14-aabcbb2a2631.png)


![zoom-map-view](https://user-images.githubusercontent.com/9723813/166359310-7b045f2a-09af-43ee-8b81-d718c3bf11fe.png)

![Map-view](https://user-images.githubusercontent.com/9723813/166362697-e78ec167-c5c2-4f6a-af0d-874e64673eaf.png)

Farm ID : 315
Wallet: 0xfeA5a8239c1Bceb0DA8E378d57B6496D3c16bEe6
Discord: tryjapa#9936

**Comment by LittleEins** [comment]
Mushroom Deer
Endemic specie of deer who grazes for mushroom.
Effect - 20% Additional Yield for Mushrooms
Require
100 Mushrooms
25-50 SFL
![mush-deer22](https://user-images.githubusercontent.com/104184348/166409367-19e97ac9-f3a3-4f3e-9ffb-f6a82d0e9968.gif)

**Comment by brian-man** [comment]
Will the barn pig find truffles?  If so, art is needed for that too. :)

**Comment by sfwhat** [comment]
### Mushroom Chest

![goblingazeb-1 png (1)](https://user-images.githubusercontent.com/95937808/166588652-86761a59-25d7-49af-83d0-9405d51b2c24.png)
![mushchesoll1-2 png](https://user-images.githubusercontent.com/95937808/166589490-4e8b9e2b-7dd1-494e-b951-4d590562a43a.png) Open
![mushchesoll1-1 png](https://user-images.githubusercontent.com/95937808/166589504-96191566-d8d8-45ec-befb-89ffe7fcebc5.png) Closed

_
Farm ID: 6127
@strugwhat (Twitter)

**Comment by sfwhat** [comment]
Mushroom Gazebo

![goblingazeb-1 png](https://user-images.githubusercontent.com/95937808/166579070-ac052478-2be1-4d69-8964-e31e1a19f6f1.png)
![goblihatn](https://user-images.githubusercontent.com/95937808/166578173-e325e047-e823-4d21-a461-eb10f672679d.png)![gazebo](https://user-images.githubusercontent.com/95937808/166578465-77ad5e75-9d60-4c1c-b531-7052d267cbed.png)


_
Farm ID: 6127
@strugwhat (Twitter)

**Comment by LUNCHBOX404** [comment]
**Shroom Pin Cushion**
_Unlocks rare craftable at the tailor._

![31777-sfl-mushroom_nft-shroom_pin_cushion](https://user-images.githubusercontent.com/104640972/167229384-dedd31dd-5210-461a-8f0c-bd22a703170f.png)
![31777-sfl-mushroom_nft-shroom_pin_cushion-8x](https://user-images.githubusercontent.com/104640972/167229389-18f69cd0-5f8a-40a9-890a-f729f57c23bd.png)

![31777-sfl-mushroom_nft-shroom_pin_cushion-scene](https://user-images.githubusercontent.com/104640972/167229407-2f9e9b66-f0d2-4a15-a00a-340b2d782fb1.jpg)

<hr>
Farm ID: 31777  |  Discord: LUNCHBOX#0859  |  Twitter: @LUNCHBOX_404

**Comment by LUNCHBOX404** [comment]
**Foraging Basket**
_Increases amount of mushrooms foraged by XX%._

![31777-sfl-mushroom_nft-foraging_basket](https://user-images.githubusercontent.com/104640972/167229680-2cd92eb2-73fe-4afb-9f22-f8ae96e7ba82.png)
![31777-sfl-mushroom_nft-foraging_basket-8x](https://user-images.githubusercontent.com/104640972/167229688-30cd1d61-a86d-474b-afdd-fb304968ee8d.png)

![31777-sfl-mushroom_nft-foraging_basket-scene1](https://user-images.githubusercontent.com/104640972/167229701-621e42a4-84ec-4ac6-959b-4c998220fd26.jpg)
![31777-sfl-mushroom_nft-foraging_basket-scene2](https://user-images.githubusercontent.com/104640972/167229705-3a781add-a230-4e4a-9f6c-d38e3b4199ae.jpg)

<hr>
Farm ID: 31777  |  Discord: LUNCHBOX#0859  |  Twitter: @LUNCHBOX_404

**Comment by LUNCHBOX404** [comment]
**Mycelium Cart**
_Increases amount of mushrooms found by XX%._

![31777-sfl-mushroom_nft-mycelium-cart](https://user-images.githubusercontent.com/104640972/167229748-160f135c-8967-4c68-9251-4b7911359f31.png)
![31777-sfl-mushroom_nft-mycelium-cart-8x](https://user-images.githubusercontent.com/104640972/167229752-f757d8c0-32dc-4696-8aa7-888e325fb113.png)

![31777-sfl-mushroom_nft-mycelium_cart-scene3](https://user-images.githubusercontent.com/104640972/167229760-2d074262-86eb-44c9-b597-535790649cde.jpg)

<hr>
Farm ID: 31777  |  Discord: LUNCHBOX#0859  |  Twitter: @LUNCHBOX_404

**Comment by LUNCHBOX404** [comment]
**Fungi Gob**
_Loves to eat mushrooms. Increases amount of mushrooms found by XX%._

![31777-sfl-mushroom_nft-fungi_gob](https://user-images.githubusercontent.com/104640972/167229797-cf1e0271-f576-4f60-9d7d-cbc57c6f169e.gif)
![31777-sfl-mushroom_nft-fungi_gob-8x](https://user-images.githubusercontent.com/104640972/167229800-de244908-d7f3-4dbc-b08a-a7d271e908d5.gif)

![31777-sfl-mushroom_nft-fungi_gob-scene](https://user-images.githubusercontent.com/104640972/167229809-184afd33-c977-4886-bad6-98070a37d548.gif)

<hr>
Farm ID: 31777  |  Discord: LUNCHBOX#0859  |  Twitter: @LUNCHBOX_404

**Comment by LUNCHBOX404** [comment]
**Gnome Home**
_Oh so shroomy!_

![31777-sfl-mushroom_nft-gnome_home](https://user-images.githubusercontent.com/104640972/167229846-91121dca-f31c-4e98-9498-1576020687a4.gif)
![31777-sfl-mushroom_nft-gnome_home-8x](https://user-images.githubusercontent.com/104640972/167229850-90a9550e-dc64-4a5a-a4b1-729307fe9b84.gif)

![31777-sfl-mushroom_nft-gnome_home-scene](https://user-images.githubusercontent.com/104640972/167229855-5026dd46-1ddb-4900-a19f-16bcbf777dc6.gif)


<hr>
Farm ID: 31777  |  Discord: LUNCHBOX#0859  |  Twitter: @LUNCHBOX_404

**Comment by esp123** [comment]
mushroom head shield proposal...

![32x32shield](https://user-images.githubusercontent.com/74337946/167245620-4134bdc1-f776-4c12-a09f-17fef046ce4f.png)

![256x256shield](https://user-images.githubusercontent.com/74337946/167245626-46a05a5f-6e48-43cc-8c8d-e6332eb36bc4.png)

discord: deeefault#0033
farm id: #80399

**Comment by benaxol12** [comment]
![Muhsroom (1)](https://user-images.githubusercontent.com/98098031/167269092-c3947f83-4f46-4b70-8390-d5ab3446d75e.gif) ![Muhsroom (2)](https://user-images.githubusercontent.com/98098031/167269093-a6a9fcae-0f47-4e39-a273-6e26b743d90d.gif) ![Muhsroom (3)](https://user-images.githubusercontent.com/98098031/167269096-1e6fe460-7a92-40d8-8a57-fc4b2a3f16a1.gif)

Mushroom villagers 

![Mushrooms](https://user-images.githubusercontent.com/98098031/167269108-c548b9e0-bb42-4357-b11c-8dbe280f2b5f.gif)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
