### ISSUE TITLE
Chicken,  Gnome  V1 VS V2 = Wes LOST !

### ISSUE THREAD

**Issue by JoMcClane33** [sunflower-land/sunflower-land#757]
Hello, I am writing to tell you about my problem.

V2 is on and I'm happy to play it ! But but I do not agree because I invested in the gnome and in chickens and today I can no longer use them....

For the chickens ( buy V1 5 SFF ) gave me eggs every day and today I lost that advantage ...

For The Gnome on the V1 it was written that he could change the weather and today nothing?

I find that these advantages are lost when we believed in the project directly at V1 and that we are losing every day.

I would have liked to be able to use my chickens directly at the game's release to keep this advantage of V1

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
