### ISSUE TITLE
Town Hall Suggestion Art

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#758]
![image](https://user-images.githubusercontent.com/98098233/166132293-b5da4df9-55a0-409b-8069-12e7c6422b03.png)

![image](https://user-images.githubusercontent.com/98098233/166132298-dd669361-1dfe-4af2-a095-c274ef837599.png)

**Comment by DeaerCui** [comment]
I think it would be more interesting if the flag could be placed next to the city hall
