### ISSUE TITLE
Error when saving with Brave Wallet 

### ISSUE THREAD

**Issue by trentrand** [sunflower-land/sunflower-land#76]
When calling the contract with Brave Browser's new built-in wallet, the transaction succeeds but I'm shown an error.

Here's the error UI that is presented after signing a save transaction with my hardware wallet:
<img width="470" alt="Screen Shot 2022-01-02 at 11 54 35 AM" src="https://user-images.githubusercontent.com/6083067/147892989-2d5c3930-0e23-41fb-9d1a-706e040acada.png">

> Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
> ```{ error: { code: "-32000", message: "notifications not supported" }, id: "51", jsonrpc: "2.0" }```

**Comment by zinkkrysty** [comment]
To be honest, the new brave wallet is pretty much unusable. I am still using the old one (there's an option to toggle between them), and I regret not using MetaMask in the first place to start with.
