### ISSUE TITLE
Summary of some suggestions

### ISSUE THREAD

**Issue by DeaerCui** [sunflower-land/sunflower-land#760]
I would like to summarize some recent suggestions from players in China on sunflowers

1.The income of a person playing sunflowers is too low, and the production takes a long time. At the same time, it is also reducing production. [Increase NFT appeal orIncrease yield]

2.Add a friend list and get rewards by visiting friends

3.Improve the crackdown on Automation[Humans need rest, while robots do work 24 hours a day. It's not fair to us]

4.Bank NFT withdrawal does not have all options, which is not friendly to humans.

ID farm: 14703

**Comment by brian-man** [comment]
The SFL and experience from Sunflower (per time) is the highest of any crop in the game.

**Comment by xiaoqiu06** [comment]
Low-level crops earn more than high-level crops, so many farmers are reluctant to upgrade their land. So there is no efficient consumption of tokens. The longer I have been in contact with the sunflower, the more I can't understand the logic of the project's production.
