### ISSUE TITLE
Protecting honest players from account blocking.

### ISSUE THREAD

**Issue by RickFaker** [sunflower-land/sunflower-land#761]
I think there is a problem in the game: some players don't want to leave their nft and resources on the farm because there is a risk of being blocked by mistake. Also, maybe there are people who want to invest in the game by buying nft and resources on OTC, but they are afraid that they will be blocked by mistake.

**Comment by RickFaker** [comment]
I have a lot of resources in the game (more than most players), but I think it is risky to leave them on my farm (I think there is a risk of being blocked by mistake), so I transferred all my nft and resources to OS. I think that besides me there are players who would like to invest in the game or accumulate them on their farm, but they are also afraid of losing access to their funds by mistake. You need some kind of guarantee that your assets will not be blocked. For example: 
1) if a farmer has assets on his farm totaling 100 coins-then he is considered a good farmer and his assets of 100 coins will not be blocked, but anything higher can be blocked if he breaks the rules
2) if assets on the land are equal to 200 coins - the same, only in relation to 200 coins
3) if 400 coins-he has proven to goblins that he is a good host and trustworthy, and his assets will never be blocked.
If people come in with thousands of dollars to invest in the game they will need this feature 100%. Such investors are what the entire economy of the game is based on.
Conversely, if a person only sucks all the resources out of the game, the goblins don't believe this person and think he wants to suck all the resources out of their land and paste him up, so he invests more time in taking care of the land.
At the moment the game does not encourage players who invest in the game and accumulate resources and nft. Also, on the other hand, the game does not penalize those who sell all the resources from the game (having many multi-accounts).

**Comment by RickFaker** [comment]
Also about multi-accounts and honest players:
I really like your game and I am worried that multi-accounts will kill the economy of your game. there are many people in the telegram group who brag about having many accounts (8-15 accounts). I think that the only workable way to fight multi-accounts is to load farmers with work for 30-40 minutes a day. there should be daily work on the farm, with which a person with 1 account would cope easily, while someone who has many accounts would spend a day on it. It could be such an indicator as the care of the land. for the farm to watch and remove trash, weeds, pests insects (you can think of many things, If the land is not tended, the goblins get angry). also think that you can enter the game such an indicator as the wealth of land. it should include all the assets that are on the land, for example, from 1-100. if a person has few assets on land and he all withdraw and sell, then goblins see this and stop fearing the landlord (because he is poor).Goblins start to interfere with the growth of plants or steal coins or other. these 2 indicators (tended land and land wealth) would work together. if an honest player wants to withdraw assets from the land, then let him spend more time on the farm (taking care of the land). If he doesn't have time to take care of the land, then there is no need to withdraw assets from the land in large quantities. i think there will be many players who will be unhappy that they have to devote more time to the farm. my opinion is that it is better to let this part of players leave than people with multi-accounts will flood the market with assets and devalue all nft, resources and other. (People with multi-accounts sell resources for next to nothing, because they know they have it in unaccounted amount. The problem of multi-accounts should be approached holistically and this would probably be one of many ways to solve the problem of multi-accounts in the game. 
I translated it in a translator, so the text may not be accurate. 
The more and more often a person withdraws assets from the farm, the more time it takes to take care of the land, up to two hours a day. I wanted to add that if dishonest players shift the care of the farm to bots, bots are much easier to figure out than live humans. You can't be soft on this issue because it will ruin the whole project.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
