### ISSUE TITLE
[PROPOSAL] Wood Resine to Beaver T1 T2 T3

### ISSUE THREAD

**Issue by NoisyBucheron** [sunflower-land/sunflower-land#763]
Here's a better idea with it's art added for the T1 T2 bonus discussion:

Introduce 2 new ressources ingame and it's variations: 

### **Wood Resine**
![sesina](https://user-images.githubusercontent.com/104263513/166155410-409632fb-83d4-40ff-b0dc-5becd5f75908.png)
![Resine V1](https://user-images.githubusercontent.com/104263513/166109368-abec6ad4-aff8-4859-aa21-573dfac815aa.png)

_**Drop chance:**_
Equal to Mutant crops or Animal crops

_**Utility:**_
Used to craft can of paint and more...

### **Can of paint (multiple colors)**
![canofpaintblue100](https://user-images.githubusercontent.com/104263513/166155390-4ebae337-0357-4d9f-a082-54bdf11911d3.png)
![canofpaintblue500](https://user-images.githubusercontent.com/104263513/166155384-e997c1b6-637b-456e-ba87-a8ac929d6a6f.png)
![canofpaintgreen100](https://user-images.githubusercontent.com/104263513/166155385-3ba49e3e-3fca-4266-a6fb-259d828ecee6.png)
![canofpaintgreen500](https://user-images.githubusercontent.com/104263513/166155386-eecbf496-9db8-47a9-a5ad-9aff320c5e73.png)
![canofpaintred100](https://user-images.githubusercontent.com/104263513/166155387-ae43397c-879e-4ce9-ad2b-28108caa0820.png)
![canofpaintred500](https://user-images.githubusercontent.com/104263513/166155389-11ee4f97-f808-47b9-b528-264dde46935b.png)
![canofpaintpink100](https://user-images.githubusercontent.com/104263513/166155452-5ed9b4db-764e-4dae-a691-356763eb2269.png)
![canofpaintpink500](https://user-images.githubusercontent.com/104263513/166155454-e9e640a8-d57a-41cc-995d-34f5536a1636.png)
![canofpaintpurple100](https://user-images.githubusercontent.com/104263513/166157590-8df1ab3e-bec8-4a06-8322-268b7d2221f9.png)
![canofpaintpurple500](https://user-images.githubusercontent.com/104263513/166157589-e62541af-dddc-4e28-9177-7e1c54680807.png)
![canofpaintpurple100](https://user-images.githubusercontent.com/104263513/166157692-79978129-19d5-447f-86b5-2a4435a486ac.png)
![canofpaintpurple500](https://user-images.githubusercontent.com/104263513/166157677-3c59659f-c189-4d40-9f72-85f6842fe493.png)
![canofpaintgreenf100](https://user-images.githubusercontent.com/104263513/166157776-4bc2bd16-af42-45bd-abd0-61a7a1db8bfa.png)
![canofpaintgreenf500](https://user-images.githubusercontent.com/104263513/166157778-46c799ff-90e9-4aea-85ae-c39bf54eb644.png)

Etc...

**_How to craft:_**
Tailor craft it for you

**_Ingredients:_**
Resine + fruits or vegetables

**_Utility:_** 
Customise your buildings ingame to flex ;)

### **Reason to have those new ingredients:**

With this we can keep the bonus of beaver T1 and T2 and even add a little bit more bonus to T3 if needed.

**_T1:_** 
Bonus 20% wood
50% more chance to drop Resine

**_T2:_** 
Previous T1 Bonus
Trees recover 50% faster
100% more chance to drop Resine

**_T3:_**
Previous T1 and T2 Bonus
Chop trees without axes
150% more chance to drop Resine

Cheers

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
