### ISSUE TITLE
improve halving for farmers

### ISSUE THREAD

**Issue by Felp-22** [sunflower-land/sunflower-land#764]
@adamhannigan Currently halving is relatively unfair to crop holders, it is not feasible to hold crops for a long time as they are exposed to halving inflation, unlike resources such as wood, stones, iron and gold. my proposal is to change the halving system so that the reduction in the value of crops is changed, they can be fractionated similar to the other resources and so only the seeds will be affected by the halving they cost half and will produce fractions of crops, thus the value of each crop remains and whoever held their crop will not be affected.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
