### ISSUE TITLE
[REQUEST] Contributor Badges

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#766]
This is a request for 4 new badges which will be provided to contributors to the project.

**Request**

- 1 developer badge
- 1 artist badge
- 1 discord bage
- 1 liquidity provider badge

These badges will each give significant boosts in-game (e.g. 25% crop rewards)

**Requirements**

- Minified art submission
- Dimensions and colour palette match the gameplay

You have read the contributing guidelines:
https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

Note: Your art & mechanic may be modified/altered by the community if needed.

**Deadline**

We are looking to add these in over the next couple days so won't have much time to work with.

Ideally we will want these in the game on May 4th.

**Comment by cambrios1** [comment]
dev badge?
![devbadge-big](https://user-images.githubusercontent.com/98171636/166169713-13247dff-a2ce-4e62-80c2-cc903e57bb71.png)

**Comment by DonatasDee** [comment]
Please don't let these stack, please don't let these stack, please don't let these stack.

**Comment by NoisyBucheron** [comment]
![discordbadgebig](https://user-images.githubusercontent.com/104263513/166171705-326b2222-56a9-474b-8d30-59adf5125aed.png)
![discordbadge](https://user-images.githubusercontent.com/104263513/166171707-0cc8c08e-4864-47ec-8901-c4e8f5e6f217.png)

**Comment by victorrabello** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/90971807/166171817-fea69eee-338b-4fff-94db-f324c2bb2a99.png)
![Sprite-0002](https://user-images.githubusercontent.com/90971807/166171820-8765f202-a939-40ed-8691-61031ac27b1c.png)

**Comment by Netherzapdos** [comment]
---
**Art Contributor Badge**
![Art Contributor L](https://user-images.githubusercontent.com/101855553/166178797-c178f145-009a-4c2b-a5e3-bfe1ffeff9b0.gif)
![Art Contributor R](https://user-images.githubusercontent.com/101855553/166178798-d917a23d-d4cf-4446-b0eb-3ee53df9e8a7.gif)

---
**Liquidity Provider Badge**
![LP L](https://user-images.githubusercontent.com/101855553/166178831-5220fd6e-4936-4f39-ad0c-e5aad0cf53b8.png)
![LP R](https://user-images.githubusercontent.com/101855553/166178835-cd7229b1-d5a3-43e6-add2-cd1e10ee26db.png)

---
**Developer Badge**

![Dev Badge L](https://user-images.githubusercontent.com/101855553/166178909-e9529580-a8f2-4712-8ae2-2b27e12b3ee4.png)
![Dev Badge R](https://user-images.githubusercontent.com/101855553/166178910-0add6070-01fb-439b-b3c5-fdfae9c528bb.png)

Devs do love their coffee ☕ 

---
May or may not submit a discord badge, still thinking of a sprite 😅 

`Farm ID: 591`
`Polygon Address: 0xBE6f742Fa865F94902D0a49CC12F23FDb2C5AE68`

**Comment by eArL2384** [comment]
Art contributor badge
![Uploading 1651462203207.gif…]()

**Comment by eArL2384** [comment]
Artist Badge
![Uploading Screenshot_2022-05-02-11-34-47-31_99c04817c0de5652397fc8b56c3b3817.jpg…]()

**Comment by eArL2384** [comment]
Artist Badge
![1651462439064](https://user-images.githubusercontent.com/104702521/166181396-9fda38f4-515a-4153-9aeb-b70ec2b8b15c.gif)

**Comment by Dowell-long** [comment]
Art Contributor Badge
![1](https://user-images.githubusercontent.com/90394370/166204019-9829ec4d-5e20-473b-bcc4-3d957dee250b.png)

**Comment by Dowell-long** [comment]
![1+](https://user-images.githubusercontent.com/90394370/166207137-94effcc2-0672-4497-87ae-0c825b926cef.png)
![1](https://user-images.githubusercontent.com/90394370/166207163-8cdf4fd0-2b00-4130-8ebc-277bc70ab0ac.png)

Art Contributor Badge

**Comment by sfwhat** [comment]
Developer Badge
![New Piskel (3)](https://user-images.githubusercontent.com/95937808/166217100-7e7be781-902c-4f58-bb4c-e505ab319f9a.gif)
Art Contributor Badge
![New Piskel (2)](https://user-images.githubusercontent.com/95937808/166217104-3040f9fd-3373-4606-a1aa-04451bf52568.gif)
Discord Badge
![New Piskel (1)](https://user-images.githubusercontent.com/95937808/166217107-84fc5c47-60e5-427b-8d0b-2eddb50e8e29.gif)
Liquidity Provider Badge
![New Piskel (4)](https://user-images.githubusercontent.com/95937808/166217117-64bbe247-3696-4a22-b10a-4936f7222d3e.gif)
![Badges (2)](https://user-images.githubusercontent.com/95937808/166217108-9e5335d1-b514-4691-b265-449fdb4e560b.gif)![Badges (3)](https://user-images.githubusercontent.com/95937808/166217109-1976d676-c1da-4557-89ea-34031ed38cd7.gif)![Badges (4)](https://user-images.githubusercontent.com/95937808/166217110-e69aad79-6508-4830-8708-889226f9c7d3.gif)![Badges (1)](https://user-images.githubusercontent.com/95937808/166217112-447a0175-6b24-42cb-9cf0-e71409c6fa8b.gif)
> 


</body>
</html>
Farm ID: 6127

@strugwhat (Twitter)

**Comment by cambrios1** [comment]
![devbadge1px](https://user-images.githubusercontent.com/98171636/166219437-4e96b66f-a48d-4f6d-b0dc-a2940bb93c3a.png)
![discord1px](https://user-images.githubusercontent.com/98171636/166219439-d5defb83-fad6-4039-8d74-dff76b19c778.png)
![artbadge1px](https://user-images.githubusercontent.com/98171636/166219440-0da148e1-3371-484b-80e9-bd25ac1ccde2.png)
![lpbadge1px](https://user-images.githubusercontent.com/98171636/166219443-3a47eb99-b72c-4a4d-9ca2-4c73325a2cae.png)

Discord:
![discord badge](https://user-images.githubusercontent.com/98171636/166219465-c5551085-bf50-4589-8d18-e414b20eb150.png)

Dev:
![devbadge-big](https://user-images.githubusercontent.com/98171636/166219487-66190dbe-3982-464d-950f-5ee7bfd68421.png)

Art:
![art badge](https://user-images.githubusercontent.com/98171636/166219499-19d36540-e27b-42c6-8965-46cabd86a8b1.png)

LP:
![lpbadge](https://user-images.githubusercontent.com/98171636/166219518-b730841b-86f0-4406-a40e-c3af5f6b8726.png)

In game:
![signbadges](https://user-images.githubusercontent.com/98171636/166219531-16fb4ea6-79b1-4d9c-986d-7bed85a3acf5.png)

**Comment by Vergelsxtn** [comment]
![Contibutor-badgespreview](https://user-images.githubusercontent.com/99605039/166220681-2e9dc37c-4aae-48b2-a1a9-29e28f06608c.jpg)

Game developer badge
![gamedev-badgenormal](https://user-images.githubusercontent.com/99605039/166220844-e4513014-4d51-4596-b869-80d2a83e493e.png)
![Gamedev-badge](https://user-images.githubusercontent.com/99605039/166220856-4cf3e8db-6d2d-40b8-aaa6-c5608e5691b7.png)

Artist badge
![Artist-badgenormal](https://user-images.githubusercontent.com/99605039/166220706-fa4c28c6-4a6b-4a8a-ab38-4dc3299dba77.png)
![Artist-badge](https://user-images.githubusercontent.com/99605039/166220764-f9dab3f9-fcbc-4442-a393-ddfe30e36280.png)

Discord badge
(WIP)

liquidity provider badge
(WIP)

**Comment by Alexcnder** [comment]
Discord Badge:
![View SUpport](https://user-images.githubusercontent.com/87881787/166222481-557c0f2f-85a8-483c-9e35-ebde65ac6f36.png)
![SUpport](https://user-images.githubusercontent.com/87881787/166222490-36bebb96-5350-4418-830f-a0665b2201d6.png)
without badge background :
![without](https://user-images.githubusercontent.com/87881787/166222574-90dc8a4d-4eec-4aff-837d-32a862154ec0.png)

**Comment by hfdcy** [comment]
This is my work
![dotpict_20220503_022000](https://user-images.githubusercontent.com/103756612/166303350-bfb1bfe0-cc71-4404-8629-714ebf8b0416.png)

Developer badge
![dotpict_20220503_021954](https://user-images.githubusercontent.com/103756612/166303514-ca6c13de-3844-4499-ae40-6e75134f2036.png)

Artist badge
![dotpict_20220503_021957](https://user-images.githubusercontent.com/103756612/166303672-4396ee8a-8f4e-4a67-9f22-7c4fd231a0e0.png)

discord bage
![dotpict_20220503_021943](https://user-images.githubusercontent.com/103756612/166303715-1b64e4f4-8a10-439d-8777-5cfcca8f5ae7.png)

 liquidity provider badge

My farm IS ID（66545）

**Comment by Aestnelis** [comment]
**Developer badge - Artist badge - Discord Badge - Liquidity Provider Badge**
![mini badges](https://user-images.githubusercontent.com/98103679/166305192-fc7c93d8-f160-4107-a258-f5e39c8fc454.png)
![big badges](https://user-images.githubusercontent.com/98103679/166305211-5740bc3c-290e-4234-8f35-a5d25395c2ec.png)
![Sunflowermini badges](https://user-images.githubusercontent.com/98103679/166305227-b5fec3c0-e527-41d4-b748-73da395611b8.png)

**Comment by VadimasVP** [comment]
Discord Badge /  Liquidity Provider Badge / Artist Badge / Developer Badge
![2](https://user-images.githubusercontent.com/102822587/166308773-be109cf4-5549-4bb5-84ca-7c6354a7d809.png)

![1](https://user-images.githubusercontent.com/102822587/166308795-aa785760-5fb0-407c-b73b-4b5221c86c8b.png)

**Comment by ItsNight** [comment]
![image](https://user-images.githubusercontent.com/43474459/166336406-8f6dd0ed-d9ec-4bc7-8dd8-48f0ac93447f.png)

**Comment by Z1kou** [comment]
Here is my iteration:
![Badges Close up1000](https://user-images.githubusercontent.com/98262339/166367234-ef8eaa4b-8e48-4814-b7e2-70e9840b8882.png)

![Badges Close up](https://user-images.githubusercontent.com/98262339/166367160-c9a88f36-3011-486e-8a04-10e54bc0ba42.png)


![WITHDRAW UI WITH BADGES500centered](https://user-images.githubusercontent.com/98262339/166368359-cc894677-1608-4d05-af6e-2f1668af6eb1.png)

**Comment by benaxol12** [comment]
Artist badge - Discord Badge - Developer badges

![Badge artist](https://user-images.githubusercontent.com/98098031/166455183-5f2355da-3e5b-4520-a812-9a96e426df5d.png) ![Discord GİF](https://user-images.githubusercontent.com/98098031/166455351-f6f76d0f-3aa4-4a0b-9de0-e5732518278d.gif) ![dev badge 2](https://user-images.githubusercontent.com/98098031/166455533-a1b2bcda-2cef-4df1-803f-615e5e8571a5.gif)  ![Def badges 1](https://user-images.githubusercontent.com/98098031/166455573-e83ec630-9c46-4cab-b34c-14d89988a0b2.gif)
![Badge artist 64x](https://user-images.githubusercontent.com/98098031/166455634-93274f3b-ecfa-4ac7-a796-47346adad175.png) ![Discord GİF 64x64](https://user-images.githubusercontent.com/98098031/166455638-06e18d77-4671-4f93-9834-c8b58e41abbc.gif) ![dev badge 64x](https://user-images.githubusercontent.com/98098031/166455685-63b787bf-1fd0-433d-82c5-2019d5aa9015.gif) ![Def badges 1 64x](https://user-images.githubusercontent.com/98098031/166455711-25fa4f90-e93f-4abd-9f71-f02a199cf216.gif)

**Comment by ClaudioZephyrus** [comment]
![artist](https://user-images.githubusercontent.com/52145007/168412514-c97d7a10-6833-4069-8ba6-5e64d36f0359.gif)
Artist

![dev](https://user-images.githubusercontent.com/52145007/168412532-98b78e6f-1df7-4994-87a9-a2ca6f0198ba.gif)
Dev

![disc](https://user-images.githubusercontent.com/52145007/168412540-5bf1aa91-06e7-4cc3-bcde-28424bf0790f.gif)
Discord

![lpd](https://user-images.githubusercontent.com/52145007/168412548-2c54f5c3-ed5d-4937-be2b-3b0673575fe7.gif)
Liquidity Provider

**Comment by ClaudioZephyrus** [comment]
![artist](https://user-images.githubusercontent.com/52145007/168412761-177b8661-137e-4674-82de-f6cbf59e7c0f.gif)

**Comment by ClaudioZephyrus** [comment]
Discord
![disc-export](https://user-images.githubusercontent.com/52145007/168412838-03b47d22-666e-4fec-9892-02b903aa49dd.gif)

Artist
![artist](https://user-images.githubusercontent.com/52145007/168412846-1bfca786-aa8d-4035-80d5-545bed488321.gif)

Dev
![dev](https://user-images.githubusercontent.com/52145007/168412858-a0cca2fb-1262-49bb-a71b-2c094df87253.gif)

Liquidity Provider
![lpd](https://user-images.githubusercontent.com/52145007/168412884-115f2462-69b6-4e04-9020-fbf733b81999.gif)
