### ISSUE TITLE
NFT Buff Proposal

### ISSUE THREAD

**Issue by Krulzifer** [sunflower-land/sunflower-land#768]
Sunflower Statue - +20% more Sunflower
Potato Statue - +20% more potato
Farmer Bath - +20% exp for farming sklls
Nyon Statue - +20% exp for mining skills
Fountain - crops grow 2% faster
Sunflower Rock - x2 Sunflower gains
Apprentice Beaver (Revamp) - 20% discount for tools
Homeless Tent - +1% skill for gathering and farming skill

I think NFT's need some buff/boost for the game to encourage other players to craft and hold their NFT for the benefit of their farm not just for decorations. Thanks

This is just a suggestions

**Comment by LucasNunesMendes** [comment]
I think this is a cool idea. However, the values for the buffs are too high.

I think something between 0.1 - 0.5% is something to think about. If the buffs are not cumulative, something between 1% - 5% would be great.

**Comment by Krulzifer** [comment]
The buff for the bunny from the easter bunny event is my reference for this buffs. Still it's just a suggestion cause I think that people doesn't find any value to decoratuve NFT since it has no boost on their farms.
