### ISSUE TITLE
[IDEA] NFT Auctions instead of fixed prices for some NFTs

### ISSUE THREAD

**Issue by NotKeen** [sunflower-land/sunflower-land#769]
I have mentioned this idea here and there, but never properly written it out.

I propose to sell some NFTs in the form of _**Dutch Auctions**_ instead of fixed prices. Definition from Wikipedia: 

> .. it means an auction in which the auctioneer begins with a high asking price [..] and lowers it until some participant accepts the price ..

Example: 
Now - The Golden Cauliflower is sold for a fixed price of 500 Caulis, 100 Gold and 100 SFL on a first come, first served basis. Whether or not you get it, might mostly depend on luck being there at the right time with the resources ready.

Proposal - We start the sale with a very high price that should make no sense (say 2k Caulis, 400 Gold, 400 SFL or even more) and lower it in a predictable way over a time-span (_some days? some weeks? Open for discussion_) until it becomes very cheap, making sure it is sold out.

Notes:
- We would still predetermine the ratio of inputs (in this example 1:1 SFL:Gold and 1:5 SFL:Cauli)
- We would set the starting price in SFL, and the total price with all inputs would be generated with the ratios

**_For what kind of NFTs should an auction be used?_**

Imo, this makes the most sense for NFTs with a small Supply Limit. Because say we do this with a Woody the Beaver type NFT, the demand is mostly limited by the size of the playerbase, which will solve itself over time. _Of course we could still think about transforming NFT sales with fixed prices into an auction after a while, if they don't sell._

**_Analysis / Expected effects:_**
- This would improve the issue of _**Sale-timing fairness**_ (Getting a rare NFT wouldn't be so much about being there at the right time anymore)
- Maximizing SFL burned: We might get sales at higher prices than we anticipated, and we will make sure every NFT is sold in a short time-frame (this helps if we overestimated demand / would have set the fixed price way too high otherwise) 
- Risk: We might miss out on sales that would have come later with new players coming in / getting resources ready. This could be mitigated by setting a minimum sale price (after reaching this, the price lowering would stop) and announcing NFTs early so players can get ready

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
