### ISSUE TITLE
【IDEA】Blind box to get new land

### ISSUE THREAD

**Issue by Shine19880** [sunflower-land/sunflower-land#771]
It is recommended to change the method of acquiring new land. The materials in the game can be synthesized into blind box NFT, and the blind box can be sold or opened. Opening the blind box has a probability to open new land and other items.

The advantage of doing this is that：
1 . Increase material consumption and help deflation
2 . Increase the gambling scene, because if you open a new land in the blind box, you will make a profit or you will lose.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
