### ISSUE TITLE
[ART] Merch Store Art

### ISSUE THREAD

**Issue by Aestnelis** [sunflower-land/sunflower-land#774]
Wanted to make an Merch Store because i want people to buy clothes and stuff that has sunflower logo/assets on in. So by clicking that store, we can be directed to the site where we can buy these.
![image](https://user-images.githubusercontent.com/98103679/166230675-9598d42f-4eef-4529-8bf2-a8a0fa6b523a.png)
![image](https://user-images.githubusercontent.com/98103679/166230702-5b4d044c-b74f-41a3-ab94-2b86f7ed8a28.png)
![image](https://user-images.githubusercontent.com/98103679/166230708-75550245-9d15-4814-bd82-d9a517dcd347.png)

**Comment by adamhannigan** [comment]
This is awesome @Aestnelis ❤️ 

I'm sure Steve will love this! 🤗

**Comment by Aestnelis** [comment]
> This is awesome @Aestnelis ❤️
> 
> I'm sure Steve will love this! 🤗

Glad you like it^^

**Comment by LUNCHBOX404** [comment]
Hey! Great minds think alike! 

I was actually toying with the idea of a Merch Store and what it could look like this past week. I really like how the devs are the Homeless Beggar. Here's my art proposal of a **Homeless Shopping Cart** Merch Store 🤣

This would keep everything related to supporting the devs around the them of homeless.

Let me know what y'all think!

![31777-sfl-shoppingcart-merch](https://user-images.githubusercontent.com/104640972/166334883-65672ab7-31ef-4450-9000-120f9ea7aa2d.png)
![31777-sfl-shoppingcart-merch-8x](https://user-images.githubusercontent.com/104640972/166334899-9dabbb0b-d5a4-4811-96a6-ea53eaf253c6.png)
![31777-sfl-shoppingcart-scene1-8x](https://user-images.githubusercontent.com/104640972/166334901-59dad9b6-5fda-4a7a-92fc-7a1c3bf945ed.png)

**Comment by Stevew00dy** [comment]
I always imagined this would be part of the tailors. Then I saw @Aestnelis and realised that this is so much better. Then I see @LUNCHBOX404 and realise this is incredible and just getting better and better. The concept of the homeless man having a merch store to make money and keeping it all connected to the dev team is really clever.

**Comment by Stevew00dy** [comment]
What if we incorporate both ideas :) what about if we have the rail (without the lady NPC) and a smaller shopping cart with some goodies and create a duel built NFT between two artists :)

**Comment by LUNCHBOX404** [comment]
Thanks @Stevew00dy Is this something you would like me to edit down?

Here's a more zoomed out view to get a better idea of the cart size.
![31777-sfl-shoppingcart-scene3-4x](https://user-images.githubusercontent.com/104640972/166347557-946fd3bb-65b0-4e79-b81c-2c11efe92dae.png)

**Comment by alvinphoebeartemis** [comment]
Hi @Stevew00dy @adamhannigan 🤗, I can create a PR for this for aesthetics in-game if already approved to you both. 🤗 Thank you.

**Comment by Cicciolin0** [comment]
first the tent, now the cart. The hobo always get the best NFTs! wee need this cart in game ASAP!

**Comment by alvinphoebeartemis** [comment]
Hi Team, already create a PR, just waiting for the approval. 😊

Credits to @Aestnelis @LUNCHBOX404 for the awesome assets. ❤
