### ISSUE TITLE
[DOCS] Whitepaper Updates (Inconsistencies)

### ISSUE THREAD

**Issue by tiffanydys** [sunflower-land/sunflower-land#776]
# Whitepaper Updates

### Farming
- Change to `1 day`
<img width="771" alt="Screen Shot 2022-05-02 at 8 10 30 PM" src="https://user-images.githubusercontent.com/18549210/166231611-0cccfcf4-167d-4f6d-8836-9089bfcb07c3.png">

### Open Sea
- Remove link and add hyperlink -> [Sunflower Land Collectibles](https://opensea.io/collection/sunflower-land-collectibles)
<img width="599" alt="image" src="https://user-images.githubusercontent.com/18549210/166233422-0ac2368f-9634-4c3e-8c91-c7ab04798fc9.png">
<hr>

### Season 1 - Boosts
- Remove the word `Goblin` in `Goblin Scarecrow` (for consistency in the game and in OpenSea)
<img width="180" alt="Screen Shot 2022-05-02 at 8 33 55 PM" src="https://user-images.githubusercontent.com/18549210/166234543-e3d48798-6f59-4332-85f7-35ccba4a9456.png">
<img width="209" alt="Screen Shot 2022-05-02 at 8 33 28 PM" src="https://user-images.githubusercontent.com/18549210/166234559-95bdb866-fbeb-4ea0-8b5f-dbbaed81a81b.png">
<img width="1053" alt="Screen Shot 2022-05-02 at 8 32 22 PM" src="https://user-images.githubusercontent.com/18549210/166234566-1be9a36a-7b0e-4c33-b232-f0b124c726a8.png">
<hr>

- Update `Kuebiko` total supply
<img width="767" alt="Screen Shot 2022-05-02 at 8 52 34 PM" src="https://user-images.githubusercontent.com/18549210/166236717-e66f2e7c-25e6-44d8-a689-e9b92e1a3ee2.png">
OpenSea metadata:
<img width="170" alt="Screen Shot 2022-05-02 at 8 52 15 PM" src="https://user-images.githubusercontent.com/18549210/166236748-fc4a9c26-93fa-4588-a008-80278ceb7f4a.png">
<hr>

- Update `Farm Dog` total supply
<img width="756" alt="image" src="https://user-images.githubusercontent.com/18549210/166237974-29511dd6-867f-4d73-87e7-043846a1ffed.png">
OpenSea metadata:
<img width="73" alt="Screen Shot 2022-05-02 at 9 03 26 PM" src="https://user-images.githubusercontent.com/18549210/166238247-02093b9e-5b68-434e-bdd7-1f76b4d7f079.png">
<hr>

- Update `Golden Cauliflower` total supply
<img width="758" alt="Screen Shot 2022-05-02 at 9 23 08 PM" src="https://user-images.githubusercontent.com/18549210/166240926-c251069c-f26f-4076-9142-99fa039487a4.png">
OpenSea metadata:
<img width="156" alt="Screen Shot 2022-05-02 at 9 22 31 PM" src="https://user-images.githubusercontent.com/18549210/166240947-b494d309-7128-4423-9213-8ab8152cee0b.png">
<hr>

- Update `Woody the Beaver` total supply (remove extra `0`)
<img width="760" alt="Screen Shot 2022-05-02 at 9 24 01 PM" src="https://user-images.githubusercontent.com/18549210/166241103-9088510a-7b6d-4ac2-bd00-46903a49d876.png">
<hr>

- Remove `Lumberjack Skill` requirement for `Apprentice Beaver` 
<img width="762" alt="Screen Shot 2022-05-02 at 9 27 53 PM" src="https://user-images.githubusercontent.com/18549210/166242440-2b85e956-a874-4246-9723-8cc19b32ebcb.png">
<hr>

- Update `Foreman Beaver` requirement and total supply
<img width="762" alt="Screen Shot 2022-05-02 at 9 40 01 PM" src="https://user-images.githubusercontent.com/18549210/166244059-60ecc44c-d20e-4057-a36b-8b9094964437.png">
OpenSea metadata:
<img width="164" alt="Screen Shot 2022-05-02 at 9 43 22 PM" src="https://user-images.githubusercontent.com/18549210/166243932-58bb95da-0612-46d0-bcd9-2203e278cf4c.png">
<hr>

- Remove empty rows
<img width="815" alt="image" src="https://user-images.githubusercontent.com/18549210/166244626-27581941-9eb8-454c-a07a-74d0264e0b06.png">
<hr>

- Update `Mysterious Parsnip` total supply
<img width="767" alt="image" src="https://user-images.githubusercontent.com/18549210/166246441-f6f2d00e-3158-4cf3-96df-4cd3f7724319.png">
OpenSea metadata:
<img width="154" alt="Screen Shot 2022-05-02 at 9 58 16 PM" src="https://user-images.githubusercontent.com/18549210/166246314-efdfea01-c1dc-4888-8010-dd2451b0f1cc.png">
<hr>

- Add `Easter Bunny`
Price: All 7 Easter Eggs
Supply: 100000 `Event ended`
Functionality: Yield 20% more carrots
<hr>

### Decorations
- Update `Farm Cat` total supply
<img width="771" alt="image" src="https://user-images.githubusercontent.com/18549210/166245107-a409b2eb-f847-41a4-bc46-31292907ee3c.png">
OpenSea metadata:
<img width="65" alt="Screen Shot 2022-05-02 at 9 49 04 PM" src="https://user-images.githubusercontent.com/18549210/166244920-a53251c5-9dbb-42b7-adc0-842373d8c032.png">
<hr>

- Update `Goblin Crown` requirement
<img width="500" alt="image" src="https://user-images.githubusercontent.com/18549210/166245974-55f5e1aa-39fc-43fd-8741-fe3fb63b4de2.png">
<hr>

- Update `Fountain` requirement
![image](https://user-images.githubusercontent.com/18549210/166248229-e3c9bff1-8900-442e-980a-937650c3cfb9.png)
<hr>

- Remove duplicate item `Sunflower Cake` (as it is already in **Season 2 - Decorations**)
<img width="767" alt="image" src="https://user-images.githubusercontent.com/18549210/166268196-8fe77142-819c-48b8-b105-8c269512a484.png">
<hr>

- Update `Homeless Tent` requirement
![image](https://user-images.githubusercontent.com/18549210/166248920-0cb1260e-9da2-4144-bbf9-6f080cee307d.png)
<hr>

### Season 2 - Boosts
- Move `Chicken Coop` to **Season 1 - Boosts**
- Update `Chicken Coop` requirements and total supply
<img width="764" alt="image" src="https://user-images.githubusercontent.com/18549210/166269553-a214e894-f4bc-469a-90ea-eaa1b7b58fb8.png">

**Comment by jifenggg** [comment]
哔哔哔...→_→ 收到

**Comment by dongdong-gitt** [comment]
啥时候更新！

**Comment by dongdong-gitt** [comment]
When to update the quantity in the game

**Comment by tiffanydys** [comment]
> When to update the quantity in the game

The quantity in the game is the correct one. The one on the whitepaper document is wrong.

**Comment by adamhannigan** [comment]
Thanks @tiffanydys Just updated ✅ 

One small change, I have moved the Golden Egg into Season 2. The animal products will fall under that season 😄
