### ISSUE TITLE
[BUG] Not able to sync farm - Reason Unknown

### ISSUE THREAD

**Issue by aayusharyan** [sunflower-land/sunflower-land#779]
Since the last 2 days, the sync is not working. The endpoint is giving 500 Internal server error. There is no debugging available and I am not sure what is causing this. Since I am not able to sync, I am not able to pretty much do anything as the seeds and all are stocked out. 😅 

Evidence:
![image](https://user-images.githubusercontent.com/16634228/166322331-3a3f4be8-d68f-454c-acab-0e56ffd2c273.png)

**Comment by dongdong-gitt** [comment]
vpn

**Comment by aayusharyan** [comment]
> vpn
No, also a logical reason, if APIs are supposed to fail over VPN, all the APIs should fail. Everything is working, just the sync endpoint is failing.

**Comment by Pranav-yadav** [comment]
Looks like session issue... Not sure tho.
Or
The request being sent is malformed...


## Few Suggestions:
*(Try on your own risk/ Possibility of losing progress)*
1. Hard Refresh (I'm sure you've tried this.. 😄 )
2. Nuke/Delete the tokens from browser's localStorage manually..
3. Try to log into game from Mobile (e.g. with Metamask Inbuilt browser)...
4. Finally, if nothing works capture (save) the payload ,request as well as  response and share it with Adam through DM. *(rm sensitive info if any.. 😉 )*

**Comment by ShiningMinions** [comment]
@aayusharyan can you prefix the title of this issue with the word [FIX] ? In the meantime...

I attempted to help @aayusharyan with this problem. Unfortunately it was unsuccessful in the end, but I want to report my findings to hopefully speed-up the troubleshooting process. I don't think there's much anyone can do until a SFL team member troubleshoots on the back-end server.

@aayusharyan has a farm ID of the following: 18541. Upon visiting this farm I was looking for something strange, and indeed I found it:

![carrot-bad](https://user-images.githubusercontent.com/103600068/166726974-18e8584a-d84e-4568-a785-98b105412937.png)

Written onto the Polygon blockchain, he had a carrot value of "90". We know this is true because this is the number I see visiting his farm, and I also confirmed on polygon inventory contract. Since we know crop tokens have 18 decimal places, this is a VERY LOW number, like 0.000000000000000090 carrots.

### What I thought the problem was:

I was thinking the back-end server was having problems syncing with this low of a number. Perhaps server doesn't know how to handle such high decimal value, and therefore errors.

### My attempted work-around (which ultimately failed, but still good info to know):

If indeed the server was having issues with syncing low decimals from the blockchain, my attempted workaround was to send him .999999999999999910 carrots from my metaMask wallet. Doing this would put him at exactly 1 carrot on the blockchain. This is exactly what I did, and you can see he now has exactly 1 carrot in game, and on the blockchain:

#### Me visiting his farm after fractional carrot send:
![good-farm](https://user-images.githubusercontent.com/103600068/166728158-db083428-7c88-478b-a9ff-5a0641d19625.png)

#### Confirming carrot value for his farm on the blockchain:
![204-inventory](https://user-images.githubusercontent.com/103600068/166728176-7d7fb373-3e49-47a5-a4d5-a5dad4ad2b25.png)
> (note - "204" is the assetID of a carrot. This number represents exactly 1 carrot)

### Conclusions:

After this, @aayusharyan tried to "Sync on Chain" again, but unfortunately still getting 500 error and fails. I believe we simply need someone who has access to backend to take a look at this point :/

**Comment by brian-man** [comment]
> EDIT: See #632 - should have caused it most likely.

632 only affects balance of SFL.  This issue appears to be related to the balance of a crop.  I'm not seeing how the former could "cause" a bug related to the latter.

**Comment by brian-man** [comment]
> @aayusharyan can you prefix the title of this issue with the word [FIX] ? In the meantime...
@ShiningMinions 
I think you mean `[BUG]`.  The issue isn't fixing something.  A PR to address it would.

**Comment by ShiningMinions** [comment]
> > @aayusharyan can you prefix the title of this issue with the word [FIX] ? In the meantime...
> > @ShiningMinions
> 
> I think you mean `[BUG]`. The issue isn't fixing something. A PR to address it would.

Thank you, I fixed.

**Comment by ShiningMinions** [comment]
> > EDIT: See #632 - should have caused it most likely.
> 
> #632 only affects balance of SFL. This issue appears to be related to the balance of a crop. I'm not seeing how the former could "cause" a bug related to the latter.
> 
> Also, the content shown in discord when we were discussing it showed that the SFL balance seemed fine (<= 19 decimal places). As long as the decimal places of the SFL balance is <= 18, #632 has no impact.

My best guess is that the following happened to our friend @aayusharyan , which would be the same as https://github.com/sunflower-land/sunflower-land/pull/632 :

1. He somehow received .0000000000000000090 carrots to his farm from outside world.
2. He successfully synced to chain. He now has these carrots on his farm.
3. He sells carrots at shop.
4. He makes much progress and syncs to chain again, but this time failure.

No?

**Comment by brian-man** [comment]
> 3. He sells carrots at shop. Now has weird SFL balance (and also happened before [[FIX] Floor SFL balance to 18 decimal places after selling #632](https://github.com/sunflower-land/sunflower-land/pull/632) merge).
> 4. He makes more in-game progress and syncs to chain again, but this time failure.
> 
> No?

No. The data shown in discord (the json posted to the server) shows that the SFL balance is fine (nothing beyond 18 decimals).

**Comment by aayusharyan** [comment]
@ShiningMinions 
Updated the title.

**Comment by aayusharyan** [comment]
@ShiningMinions @brian-man 
Is it possible that in the backend, some more validation was introduced recently? Can we get a changelog? Not the exact change, but just like the summary of commits of what was improved in the last 5 days?


This is the farm JSON and this looks pretty fine to me and shouldn't cause any issues.
```
{
  "farm":{
    "balance":"179.54614999999999999",
    "skills":{
      "gathering":"17.7",
      "farming":"1229.82"
    },
    "fields":{
      "0":{
        "name":"Beetroot",
        "plantedAt":1651661970128,
        "multiplier":1
      },
      "1":{
        "name":"Beetroot",
        "plantedAt":1651661965183,
        "multiplier":1
      },
      "2":{
        "name":"Cabbage",
        "plantedAt":1651669748608,
        "multiplier":1
      },
      "3":{
        "name":"Beetroot",
        "plantedAt":1651661963421,
        "multiplier":1
      },
      "4":{
        "name":"Beetroot",
        "plantedAt":1651661964032,
        "multiplier":1
      },
      "5":{
        "name":"Beetroot",
        "plantedAt":1651661995778,
        "multiplier":1
      },
      "6":{
        "name":"Beetroot",
        "plantedAt":1651661994591,
        "multiplier":1
      },
      "7":{
        "name":"Cabbage",
        "plantedAt":1651669751829,
        "multiplier":1
      },
      "8":{
        "name":"Beetroot",
        "plantedAt":1651661997553,
        "multiplier":1
      },
      "9":{
        "name":"Beetroot",
        "plantedAt":1651661998516,
        "multiplier":1
      },
      "10":{
        "name":"Beetroot",
        "plantedAt":1651661972638,
        "multiplier":1
      },
      "11":{
        "name":"Beetroot",
        "plantedAt":1651661971925,
        "multiplier":1
      },
      "12":{
        "name":"Beetroot",
        "plantedAt":1651661971214,
        "multiplier":1
      },
      "13":{
        "name":"Beetroot",
        "plantedAt":1651661973283,
        "multiplier":1
      },
      "14":{
        "name":"Beetroot",
        "plantedAt":1651661974075,
        "multiplier":1
      },
      "15":{
        "name":"Beetroot",
        "plantedAt":1651661974753,
        "multiplier":1
      },
      "16":{
        "name":"Beetroot",
        "plantedAt":1651661977885,
        "multiplier":1
      },
      "17":{
        "name":"Beetroot",
        "plantedAt":1651661977230,
        "multiplier":1
      },
      "18":{
        "name":"Beetroot",
        "plantedAt":1651661975408,
        "multiplier":1
      },
      "19":{
        "name":"Beetroot",
        "plantedAt":1651661978711,
        "multiplier":1
      },
      "20":{
        "name":"Beetroot",
        "plantedAt":1651661979672,
        "multiplier":1
      },
      "21":{
        "name":"Beetroot",
        "plantedAt":1651661980441,
        "multiplier":1
      }
    },
    "inventory":{
      "Gold":"2",
      "Wood":"50",
      "Fountain":"1",
      "Pumpkin Soup":"1",
      "Green Thumb":"1",
      "Iron":"2",
      "Easter Bunny":"1",
      "Roasted Cauliflower":"1",
      "Cauliflower Seed":"1",
      "Potato Statue":"1",
      "Beetroot Seed":"28",
      "Goblin Crown":"1",
      "Radish":"46",
      "Sauerkraut":"1",
      "Cabbage":"2"
    },
    "stock":{
      "Pumpkin Soup":"1",
      "Parsnip Seed":"40",
      "Wheat Seed":"40",
      "Pickaxe":"30",
      "Radish Pie":"1",
      "Sauerkraut":"1",
      "Roasted Cauliflower":"1",
      "Iron Pickaxe":"5",
      "Cauliflower Seed":"49",
      "Stone Pickaxe":"10",
      "Axe":"40"
    },
    "trees":{
      "0":{
        "choppedAt":1651144020418,
        "wood":"5"
      },
      "1":{
        "choppedAt":1651144013081,
        "wood":"3"
      },
      "2":{
        "choppedAt":1651144023035,
        "wood":"4"
      },
      "3":{
        "choppedAt":1651144017991,
        "wood":"3"
      },
      "4":{
        "choppedAt":1651144016162,
        "wood":"5"
      }
    },
    "stones":{
      "0":{
        "minedAt":1650354225249,
        "amount":"2"
      },
      "1":{
        "minedAt":1650354225250,
        "amount":"2"
      },
      "2":{
        "minedAt":1650354225249,
        "amount":"4"
      }
    },
    "iron":{
      "0":{
        "minedAt":1649852824590,
        "amount":"3"
      },
      "1":{
        "minedAt":1649852344668,
        "amount":"3"
      }
    },
    "gold":{
      "0":{
        "minedAt":1649852795312,
        "amount":"2"
      }
    }
  },
  "isBlacklisted":false,
  "startedAt":"2022-05-04T23:06:08.539Z",
  "itemsMintedAt":{
    "Egg Basket":1650355135827,
    "Potato Statue":1650354658478,
    "Goblin Crown":1649991176037,
    "Easter Bunny":1650452749030,
    "Fountain":1649991296478
  },
  "farmHash":"<Removed for Obvious Reasons>"
}
```

**Comment by ShiningMinions** [comment]
@brian-man @aayusharyan And there you go - there's your answer:

![decimals](https://user-images.githubusercontent.com/103600068/166842617-9ef56e8b-cd62-4b0d-8896-a490945d2a86.png)

Same as https://github.com/sunflower-land/sunflower-land/pull/632

**Comment by brian-man** [comment]
> @brian-man @aayusharyan And there you go - there's your answer:
> 
> ![decimals](https://user-images.githubusercontent.com/103600068/166842617-9ef56e8b-cd62-4b0d-8896-a490945d2a86.png)
> 
> Same as #632
Wrong assessment.

```
"balance":"179.54614999999999999",
               123456789012345678
```
This has 17 decimal places.  #632 ensures that you have no more than 18, which has no impact on when you have < 18.

**Comment by aayusharyan** [comment]
@brian-man @ShiningMinions 
On that note, would something like this make sense?
[I am assuming that the backend is in JS]

Now -> `console.log(190.8186 - 179.54614999999999999);` results in `11.272449999999992`
Here, 190.8186 is the balance from the blockchain.

Now, doing this calculation in a naive fashion.

```
             11                          10
            7    5999999999999 
     190.81860000000000000
(-) 179.54614999999999999
-------------------------------
       11.27245000000000001
```

Now, obviously `11.27245000000000001` and `11.272449999999992` doesn't match so some assert in the backend is failing probably and causing this error.

**Comment by brian-man** [comment]
Possible, but hard to know what the back-end is unhappy with.  We're flying completely blind here. :|

**Comment by aayusharyan** [comment]
Yeah. I guess this needs to be checked by @adamhannigan 
Or you can share the part of code which was changed over the last week and we can try to debug What went Wrong here...

**Comment by adamhannigan** [comment]
@aayusharyan Thanks for raising this and the detail you provided.

The core team will tackle this tomorrow hopefully 💪 You are right, malicious actors could cause some harm by sending this to players 😢

**Comment by MrDizzy13** [comment]
@adamhannigan thank you so much.😢

**Comment by adamhannigan** [comment]
@aayusharyan This has been resolved and will go live on the May 9th release 🚀 (There is currently a freeze on production while the Goblin town is being worked on).

7-10 days ago, support for selling fractional crops was added to the front-end. This meant you could sell 0.000000000000001 of a crop. This led to some unexpected serialisation issues on the backend.

Without diving too deep into the backend architecture (for security reasons), the web3 `toWei` API did not play nicely with extremely small numbers. A fix has been made to handle these numbers more securely.

Thanks for raising this! 👏 We will close this issue once the fix goes live 😄

**Comment by brian-man** [comment]
@adamhannigan 
> the web3 toWei API did not play nicely with extremely small numbers
That's very surprising.  Definitely give feedback on the github for that module because that's kind of a huge deal in the ETHVM world.

**Comment by aayusharyan** [comment]
@MrDizzy13 
I am also in a similar situation. But currently there are no new releases as everyone is preparing for the major release of May 9th, so we need to wait till that release in order to sync.

**Comment by MrDizzy13** [comment]
> @MrDizzy13 
> I am also in a similar situation. But currently there are no new releases as everyone is preparing for the major release of May 9th, so we need to wait till that release in order to sync.

I hope we get the fix tomorrow...

**Comment by aayusharyan** [comment]
@MrDizzy13 No seeds to do anything in the game.

![sunflower](https://user-images.githubusercontent.com/16634228/167308800-4fb7594e-e4d7-439c-af30-29d01989944e.gif)

**Comment by MrDizzy13** [comment]
> @MrDizzy13 No seeds to do anything in the game.
> 
> ![sunflower](https://user-images.githubusercontent.com/16634228/167308800-4fb7594e-e4d7-439c-af30-29d01989944e.gif)

@aayusharyan fixed now. thanks to @adamhannigan ❤️

**Comment by aayusharyan** [comment]
Yes, it is fixed now. Thank you everyone. Closing this.
