### ISSUE TITLE
[CHORE] Fix hover/mouseEnter/collision for Stone, Iron, and Gold quarry locations

### ISSUE THREAD

**Issue by newb23** [sunflower-land/sunflower-land#784]
Currently, the hover/mouseEnter area/collision area for these items encompasses the entire animation and textbox area. I suck at UI and try to fix it, but, to no avail. Someone mind taking an "easy" one? 🤣

Video: https://user-images.githubusercontent.com/7065115/166404605-5445841d-1efd-4c91-89cd-44298ae02fa0.mp4

(thought: The trees in the forest should hold your clues...? Maybe? I don't know...)

**Comment by brian-man** [comment]
I did a little investigating. The hover area is determined by the containing `div` which gets its size from the gold_empty.png which has additional space around it for the spark effects when mining.  To fix this properly, I think the spark art and the node art would have to be different sizes but aligned.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
