### ISSUE TITLE
[PROPOSAL] Guilds

### ISSUE THREAD

**Issue by Rouler1** [sunflower-land/sunflower-land#786]
Hello there!

I was sitting and talking with DkO on his stream an we came out with this idea for a Guild.
Im not that great with writing posts but i will try my best to tell you my idea :)

1. Why should i join guild?
A. That is the main question that every person in every game ask themself, why should i join?
Guild should be the place where players can cooperate, help each other, talk about ideas and strategy.
First thing that come to my mind would be "help" button. Lets say i need 50 potato, i can go to my tavern/guild hall and ask my guild members to help me (ofc numbers here are random and would need calculation and balance keep that in mind). Every perosn can give me 10 potato at maks so i will need 5 people to give me 10 potatos to finish my "order".

B. Guild projects! That is one of the main reasons to join guild, not only you can talk with people but also you can have passive bonuses for your farm! This is the moment for guild leader to shine, he can chose the project and create a patch for his guild. For example leader will chose Potato statue as a project. To finish it we (as a guild) need to donate 10000 potatos, after that the statue will be placed in a guild hall/tawern building that will give passive bonus like +5% SFL for selling potatos. Then you will have opotion to upgrade that statue for another 20000 potatos that will give +10% bonus and so on. That will not only help guild to grow but olso set a patch for this guild as a masters of potatos, other guilds might have diffrent plans, maybe for carrots, maybe for wood or chickens! 

C. Guild trading post. It would give people in the guild options not only for helping each other by clicking "help" button but also by direct trading. Instead of selling my 100 carrots that i dont need i can trade that for SFL with my guild member and help him with getting his obcetive. 

2. Guild can lvl up!
For every lvl guild will unlock new projects and will have more slots for new people to join. I would start with 5 people per guild but that is just a sugestion. 

3. Chosing guild name and focus! 
That would help people to find a guild with corect focus, for example if i want to join guild that makes projects around animals i will try to find one that is focusing on animals and so on.

4. Daily quest that will improve lvl of a guild, also clicking "help" button and finishing the order will also give expirience to encourage clan members to help, Those quests can be as simple as log in into the game and as hard as click into 200 sunflowers.

5. Guild competition! We could make guilds tourmanets, guilds will have options to donate resources into a tourament pool, top 10 guilds will get unique rewards like +1% grow rate for crops ect.

6. Guild leader is just a leader.
That means leader is the same as a new member in terms of earning from any guild bonuses. The privilege of beeing a leader is to chose what is the next guild project, recruting, promoting and making shure that guild members are active and helping others. 

I hope i made it clear, ofc a lot o option can be added/change but this was my first idea of a guild system :)

**Comment by TheAncientDragon** [comment]
DkO here.. amazing proposal, simple as it could be.. and kinda effective..
i would just add something like a guild storage where members could send their materials to help in future projects chosen by guild leader.

cheers Amazing idea and nice time talking bout it

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
