### ISSUE TITLE
[PROPOSAL] Tier 2 Bunny NFT

### ISSUE THREAD

**Issue by Samuvieira07** [sunflower-land/sunflower-land#787]
![unknown](https://user-images.githubusercontent.com/98429443/166522971-f2593cb9-ff45-4e91-a6cf-935fb13cfa71.png)

Hi everyone, I got this idea when I was watching the movie Wallace and Gromit the curse of were rabbit.

The purpose of creating this NFT is to value our dear rabbit that we won at the Easter event, and with the large number of rabbits on the market I saw that it would be cool to have a tier 2 like the scarecrow and the beaver.

![were_rabbit_by_22tjones_decvdub-fullview](https://user-images.githubusercontent.com/98429443/166533181-5f4c8f3b-da29-4d3e-9169-599046fe7dfe.jpg)

Title | details
--------- | ------
Description |  Mutant Bunny - increase the harvested amount of carrots by 50% and 50% chance of dropping mutant crops
Mint Price | 100 SFL, 1 CarrotSword, 1 Easter Bunny, 2.000 Carrots
MintSuply| 300un

**Comment by SrCouve** [comment]
![Mutant Bunny 1](https://user-images.githubusercontent.com/98098233/166566808-ab489249-02a1-4af4-b1cc-44ac2f6de0cc.gif)
![Mutant Bunny 1 big](https://user-images.githubusercontent.com/98098233/166566817-1658e22a-02fa-4c77-911e-4d7cb8c3f8be.gif)

**Comment by Samuvieira07** [comment]
> They would have to nerf the carrot sword into the ground or buff this like crazy. Carrot sword is 300% mutant crop drop chance. Nobody would consume it to craft this.

![image](https://user-images.githubusercontent.com/98429443/166573669-b8483ae7-a514-47b2-916e-a008bd1e9448.png)
I looked at the game documentation and didn't see the information that the sword increases the chance by 300%

**Comment by TheAncientDragon** [comment]
> They would have to nerf the carrot sword into the ground or buff this like crazy. Carrot sword is 300% mutant crop drop chance. Nobody would consume it to craft this.

Dunno if its official but i did hear that mutant crop chance is something like 0.001% so, having 300% is like nothing 0.003%
having something too add on top wouldnt hurt that much if 0.001% is the real value

**Comment by StockSavage** [comment]
> > They would have to nerf the carrot sword into the ground or buff this like crazy. Carrot sword is 300% mutant crop drop chance. Nobody would consume it to craft this.
> 
> ![image](https://user-images.githubusercontent.com/98429443/166573669-b8483ae7-a514-47b2-916e-a008bd1e9448.png) I looked at the game documentation and didn't see the information that the sword increases the chance by 300%

Game docs are outdated sometimes, it's in the code and I've seen discussions about it from the devs from discord. It's 300% confirmed

**Comment by YetiGains070** [comment]
you dont know if the carrot sword gets use beside the boost it will give, maybe its used for combat(if that becomes a thing in the game). so dont get why someone would sacrifice the carrot sword for this lol. but i do like the idea of T2 bunny tho. but the recipe needs change for sure

**Comment by Samuvieira07** [comment]
The craft and bonus is just an idea that can be changed by the devs 😉

**Comment by AkoSiBerto** [comment]
u can see carrot sword description at Open sea..

**Comment by SuperSynapse** [comment]
> ![Mutant Bunny 1](https://user-images.githubusercontent.com/98098233/166566808-ab489249-02a1-4af4-b1cc-44ac2f6de0cc.gif) ![Mutant Bunny 1 big](https://user-images.githubusercontent.com/98098233/166566817-1658e22a-02fa-4c77-911e-4d7cb8c3f8be.gif)

Hahahahahaha, this is amazing. Not sure about the proposed utility, but very nice work! :D
