### ISSUE TITLE
[PROPOSAL] Sell 10 / Sell 5

### ISSUE THREAD

**Issue by MarkLPB** [sunflower-land/sunflower-land#791]
#Suggestion
Please add an option in selling, certain number of items instead of sell all only. Thank you.

**Comment by alvinphoebeartemis** [comment]
Hi @MarkLPB , this is already Work-In-Progress. Our team is currently designing for the best UI/UX for this. You may check on our PR for updates and reference. Thank you. 😎 

https://github.com/sunflower-land/sunflower-land/pull/703

**Comment by MarkLPB** [comment]
I see. Thank you
