### ISSUE TITLE
[PROPOSAL] URL Verification

### ISSUE THREAD

**Issue by alvinphoebeartemis** [sunflower-land/sunflower-land#799]
Hi Team, I would like propose a URL validation for players' protection (if not available) or some sort of 3rd party validation process (captcha) to prevent from phishing site considering also the UX of this process.

**Example:**
![image](https://user-images.githubusercontent.com/53922732/166962184-fc0a9cd6-7d47-46c1-a2f0-bb14884ef186.png)

**Comment by adamhannigan** [comment]
@alvinphoebeartemis Thanks for raising this, could you provide some example services we could use. Some other examples would also be useful of website flows that have implemented this 🙏

**Comment by alvinphoebeartemis** [comment]
Hi @adamhannigan , these are my suggestions on how we can also protect the game:

**Infrastructure**
1. Adding Cloudflare Services, like Cloudflare Bot Management (consideration of financial impact)
2. DDos protection, in-case of game's sudden growth (consideration of financial impact)

**Web App**
1. Additional slide captcha tools (www.geetest.com) when login
2. Google Site Verification API (https://developers.google.com/site-verification)
