### ISSUE TITLE
[PROPOSAL] Circulating Supply in Game

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#800]
Talking to several people on discord, I noticed that many think that the total supply of the token is the circulating one, I think it is interesting to leave the circulating supply represented in the game, especially when launching the token, thus making the investment more attractive, given that we have a lot of burn
![supppply](https://user-images.githubusercontent.com/98098233/166981656-796e7e22-e595-4c59-98aa-67e432878491.png)

_illustrative image with another font, just to better express the idea_

**Comment by xiaoqiu06** [comment]
Officials need to strengthen the game's consumption of tokens. Now low-level land and high-level land are almost the same. Advanced land has no more functions, and the production team needs to strengthen the internal circulation and consumption of the game economy.

**Comment by xiaoqiu06** [comment]
The internal trading system of the game will also appear, which can be USDT or MATIC as a transaction. and charge a fee. Allows the team to have a stable income. And when the token price is low, it is used to stabilize the market.

**Comment by SuperSynapse** [comment]
This is a great idea!

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
