### ISSUE TITLE
[Proposal] New Minting Costs to deter bots

### ISSUE THREAD

**Issue by Stevew00dy** [sunflower-land/sunflower-land#802]
After talking with various advisors, experts and also members of the community, there is a mutual agreement that right now the barrier to entry is low enough that it does not deter bots from trying to abuse the system. 

Suggestion : 

Increase the cost of Matic from 1 to 10 for minting a new farm. 

Raise the charitable donation to 25% and put 50% into the treasury with a dedicated 25% towards creating and improving the bot detection systems so they are funding their own capture.

Current model shows 1 Matic breakdown as follows:

0.1 Matic - Charity
0.9 Matic - Treasury

New proposal shows:

2.5 Matic - Charity
2.5 Matic - Anti Bot Systems
5 Matic - Treasury

At the time of writing 1 Matic - $1.04

I recommend we allow a final mint at 1 Matic (around the 12th May) to give everyone in the community a chance before deploying these new rates.

**Comment by vrillx** [comment]
I like it..even if better methods to apprehend bots are not discovered at least , people trying to cheat will pay a hefty amount if they get caught ...and if they get caught with multpile farms , 10 matic for each will definetly burn a whole in their wallet...

**Comment by PeachNooter** [comment]
This is definitely a step in the right direction! All for it!

**Comment by alvinphoebeartemis** [comment]
Count me in @Stevew00dy 😊 Good Idea.

**Comment by gloom1258** [comment]
a very competent solution, such an approach will prevent abuzu, the amount of costs for mint will be more than the potential profit during the development of the farm, thereby there will be enough time to catch scammers

**Comment by muco5417** [comment]
Good ıdea @Stevew00dy 🤠🤠🤠

**Comment by Zek-Cu** [comment]
Saludos.
Pienso que es buena idea.

**Comment by SuperSynapse** [comment]
@Stevew00dy 

Overall I'm in favor of the 10 Matic price, and add in some other features such as being unable to withdraw for a 2 week period.

I would say, however, that **bots are not the real problem**. It's human multi-accounting. I have several things to share that I believe would be valuable to you or the person who is in charge of the ban hammer, but don't want to discuss them publicly on github. If you're interested contact me on discord: SuperSynapse#0786

**Comment by xiaoqiu06** [comment]
> 在与各种顾问、专家和社区成员交谈后，双方达成共识，目前进入门槛足够低，不会阻止机器人试图滥用系统。
> 
> 建议 ：
> 
> 将 Matic 的成本从 1 增加到 10 来铸造一个新的农场。
> 
> 将慈善捐款提高到 25%，并将 50% 投入国库，其中 25% 专门用于创建和改进机器人检测系统，以便他们为自己的捕获提供资金。
> 
> 当前模型显示 1 Matic 细分如下：
> 
> 0.1 Matic - 慈善机构 0.9 Matic - 财政部
> 
> 新提案显示：
> 
> 2.5 Matic - 慈善机构 2.5 Matic - 反机器人系统 5 Matic - 财政部
> 
> 在撰写本文时 1 Matic - 1.04 美元
> 
> 我建议我们允许在 1 Matic（5 月 12 日左右）进行最后一次铸币，让社区中的每个人都有机会在部署这些新费率之前。

Direct 10matic. If you continue to build 1matic on 5.12, at least 30-40% will be seized by robots. But fundamentally, the continuous sale of land will depreciate the value of other commodities. I don't know if the project party lacks funds, so I have been opening fundraising to obtain land

**Comment by xiaoqiu06** [comment]
For robots, the problem is not the cost, but your low-level land can always get benefits, so there will be a lot of robots now. You need to fundamentally solve the problem.

**Comment by xiaoqiu06** [comment]
If you don't solve the fundamental problems of the game mechanics and keep opening up the land, you'll end up just letting the bots cut the leeks of the real players. V2 fails here. You need to think carefully about these questions of mine. Increases the empowerment and value of high-level land and reduces and controls the yield of low-level land.

**Comment by DeaerCui** [comment]
Increase the intensity of the ban and do not let go of a robot.
