### ISSUE TITLE
[IDEA] Automatic Logout and Variable Captcha System to Fight Against Bots and Macros

### ISSUE THREAD

**Issue by LordSamoht** [sunflower-land/sunflower-land#806]
**Some ideas against bots and macros:**

**- Automatic logout:** after an amount of time without player interaction, the game would automatically logout, I recommend something above a common, fast crop, like 35 minutes so pumpkins can grow while the player waits. Although this doesn't stop most bots and macros, when coupled with a captcha system at login it can hinder a good amount of them.

**- Captcha system on login:** though it seems self-explanatory, we can try to add a catch here: most bots and macros click on fixed positions on the screen, so simply varying the coordinates and even the size of the panel can stop some simple macros. Also, maybe we don't need to stick with a single type of captcha, if possible, we could vary what kind of captcha appears to the player, the "click x", the "puzzle piece", the "select pictures", the "turn the picture upright" and the "write word" are the most common, but more could be added or developed with time. The idea is that just one of the captcha systems would be selected so as not to annoy the players and not to delay the login too much. This way, a bot or macro would need to be highly sophisticated to bypass all possibilities, most people wouldn't even bother to try to make one on this situation.

Have a nice day
LordSamoht

**Comment by brian-man** [comment]
I think the automatic logout idea is awful.  Daily I've got a window open to harvest+plant the next cycle of pumpkins and/or carrots.  If the game automatically logged me out, those crops would basically be useless to me because the hassle factor would be too high.  I'd just be doing radishes daily and basically log in once a day; horrible for user engagement.

**Comment by LordSamoht** [comment]
That why there'd be some time before logout for a faster crop like pumpkins, also, the logout would be on the game only, not on the wallet, so it would just a click and a fast captcha to be back in the game and plant again, maybe you'd lose an extra 20 seconds if you're horrible at captchas and only for longer crops

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
