### ISSUE TITLE
[BUG] In ww On clicking 'Search Well For SFL' api returns 500

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#810]
On clicking "Search Well For SFL" button in ww modal the,

`<API-DEV>/wishing-well` is returning `500`

- Chain Scope: Testnet
- Event (logged before/while request is made):
event:
```json
{
"captcha": "03AGdOJPD__________________o_O_______________OGvHFO9zs1A",
"type": "VERIFIED"
}
```

- Request Timestamp: `Fri, 06 May 2022 10:49:56 GMT`
- Payload:
```json
{
    "sessionId": "0xfb55f____o_O________f8e1da701",
    "farmId": "30",
    "tokens": "0",
    "captcha": "03AGdOJPD__________________o_O_______________OGvHFO9zs1A"
}
```

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
