### ISSUE TITLE
[PROPOSAL] Adding 7days for NFTS to be not transferable.

### ISSUE THREAD

**Issue by Labochi** [sunflower-land/sunflower-land#815]
Hi guys, on this proposal I am suggesting to add 7 days for the NFTs with effect not to be transferable.

As we all know there are still multi-accounter out there that is not yet being detected by our radar. I am suggesting this so they can not transfer rare NFTS from time to time to gather the resources on their other farms. 

I would also like to include Crops in addition of this.
Cauliflower - wheat - radish can only be withdrawn after 7 days once they got harvested. 

The non-transfer effect will be effective on NFT's purchased and manually transferred.

**Comment by brian-man** [comment]
Prediction:
1. The average player will flood discord with "WTF, I don't own my (N)FTs"?
2. The whale doesn't care.  Waiting a week is just deferred revenue.

Not clear on the benefit here, but the cost is clear: bad UX and discord pollution.

**Comment by ShiningMinions** [comment]
I think this is already happening in this PR: https://github.com/sunflower-land/sunflower-land/pull/812

**Comment by SuperSynapse** [comment]
I'm not a fan of "artificial scarcity" All this does is delay the "selloff" for a week. 

With some exceptions, such as the goblin village being a great example, I'm not sure why everyone wants to force others to play the way they think they should.

If you have one farm, you should be able to use it however you want. Buy, trade, sell, etc. That's the beauty of the game!

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3
