### ISSUE TITLE
[IDEA] Stability of the SFL Token

### ISSUE THREAD

**Issue by Headlessraven** [sunflower-land/sunflower-land#816]
Hello guys ! 
That's my first time writing something in here i hope that it gonna be useful. I was thinking that since the crops are NFTs and people can sell them in the secondary market for some money it may affect the stability of the token unless something change, since the stock of the crops is so high in secondary market it will affect the price of the token, what if the SFL token used on NFT's get higher a little bit like that people will burn more SFL and like that players will need a big amount for the Token to craft more usefull NFT's.
Please tell me what you think i'm open to discuss this subject with you guys.
Have a nice day :) !

**Comment by soulscrypto** [comment]
_**i am really like this idia**_

**Comment by brian-man** [comment]
> _**i am really like this idea**_
What's the idea? I see concern but not a suggested course of action.

I have trouble reading the first post (not a critique, just context) so maybe that's why.

**Comment by Headlessraven** [comment]
> > _**i am really like this idea**_
> 
> What's the idea? I see concern but not a suggested course of action.
> 
> I have trouble reading the first post (not a critique, just context) so maybe that's why.

The idea is to increase the SFL token used to craft next NFT's so it would be burnt faster to keep the stabilty of the token

**Comment by brian-man** [comment]
> The idea is to increase the SFL token used to craft next NFT's so it would be burnt faster to keep the stabilty of the token
Ah, thanks.  If you wait one halving the price will double automatically.  Is that not enough?

**Comment by Headlessraven** [comment]
> > The idea is to increase the SFL token used to craft next NFT's so it would be burnt faster to keep the stabilty of the token
> 
> Ah, thanks. If you wait one halving the price will double automatically. Is that not enough?

it won't be enough because people keep a lot of crops that they sell in the secondary market so they can buy crops with money and sell them vs SFL like that i would be cheaper for them to get the token and it gonna ruin the economy because they will just sell SFL and they will not buy it

**Comment by brian-man** [comment]
> > > The idea is to increase the SFL token used to craft next NFT's so it would be burnt faster to keep the stabilty of the token
> > 
> > 
> > Ah, thanks. If you wait one halving the price will double automatically. Is that not enough?
> 
> it won't be enough because people keep a lot of crops that they sell in the secondary market so they can buy crops with money and sell them vs SFL like that i would be cheaper for them to get the token and it gonna ruin the economy because they will just sell SFL and they will not buy it

How would raising the SFL price help? The argument seems to be that whales have an infinite supply of funds and ways to obtain funds, so I'm not sure any price other than infinity would mitigate that.

**Comment by Headlessraven** [comment]
> > > > The idea is to increase the SFL token used to craft next NFT's so it would be burnt faster to keep the stabilty of the token
> > > 
> > > 
> > > Ah, thanks. If you wait one halving the price will double automatically. Is that not enough?
> > 
> > 
> > it won't be enough because people keep a lot of crops that they sell in the secondary market so they can buy crops with money and sell them vs SFL like that i would be cheaper for them to get the token and it gonna ruin the economy because they will just sell SFL and they will not buy it
> 
> How would raising the SFL price help? The argument seems to be that whales have an infinite supply of funds and ways to obtain funds, so I'm not sure any price other than infinity would mitigate that.

it's not the fact that keeping the price of SFL higher that matters all it matters is burning more SFL so the economy won't get affected easily like what happened on axie infinity

**Comment by brian-man** [comment]
> it's not the fact that keeping the price of SFL higher that matters all it matters is burning more SFL so the economy won't get affected easily like what happened on axie infinity

My understanding is:
1. This game is "play to own" not "play to earn".  So what happens to PlayToEarn games is somewhat irrelevant as the goals and positioning are different.
2. My recollection is that the devs have stated "keeping the price of SFL higher" is explicitly not a goal.
3. I think you're underestimating the effect of the halvings.

**Comment by xiaoqiu06** [comment]
> > 保持更高的 SFL 价格并不是事实，重要的是燃烧更多的 SFL，这样经济就不会像在 axie infinity 上发生的那样容易受到影响
> 
> 我的理解是：
> 
> 1. 这个游戏是“为拥有而玩”而不是“为赚钱而玩”。因此，PlayToEarn 游戏发生的事情有些无关紧要，因为目标和定位不同。
> 2. 我的回忆是，开发人员曾表示“保持 SFL 的价格更高”显然不是目标。
> 3. 我认为你低估了减半对循环 SFL 供应的影响。如果团队从现在开始对游戏没有做任何事情，那么 SFL 的市场价格将在代币发布后大约一周左右开始每减半翻一番。

If you don’t make money, who will play chain games? What is the fundraising function for the project side that does not make money?

**Comment by xiaoqiu06** [comment]
I think your attitude has made V2 go bankrupt immediately, maybe V3 will be donating 10W horseshoes soon

**Comment by SuperSynapse** [comment]
It's a game and if the game theory plays out the way it's intended, the halvenings takes care of this issue.

Over time resources become worth less SFL, SFL production becomes more scarce, and massive amounts of SFL are burned through in game NFT minting.

These are all **massively** working in your favor! Play the game to enjoy it, and don't worry about any swings in price. Welcome to crypto!
