### ISSUE TITLE
[CHORE][BUG][TESTNET] Update Visit URL due to React Router

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#824]
## Description
Visiting a farm via url `?farmId=x` does not work anymore. it just proceeds to the normal loading of the account's farm. Need to change the link in Land Description seen in Opensea.

![image](https://user-images.githubusercontent.com/89294757/167256856-764d0a47-8d58-4a16-88fc-d25a4cde2755.png)

This also affects the link generated in Share button. Though Visit button works properly since URL pathname is correct (it ignores the search param)
**Share your farm**
![image](https://user-images.githubusercontent.com/89294757/167256027-261b3949-34fc-429e-bf5b-250dc62d5c53.png)

**Share visited farm**
![image](https://user-images.githubusercontent.com/89294757/167255865-96f943a6-6c0e-42a2-9de3-af41245afe71.png)

## TODO
- update land metadata (idk how 😅)
- update share link in `Menu.tsx`

Feel free to pick this up. Comment to own so there wont be duplicate work 😄

**Comment by Amon-S** [comment]
![image](https://user-images.githubusercontent.com/104429317/167259078-074d2ccb-81a8-496f-b5d4-ceb1cfbdd6e1.png)

shouldn't the visitFarm function send a "VISIT" state instead of "EXPLORE"?

**Comment by adamhannigan** [comment]
@j923sneaks Thanks for the reminder 🙏 

This is done in our open sea farm metadata (not done in this repo). Will fix it up now - note that Open Sea sometimes needs to manually refresh metadata for this to work.

**Comment by j923sneaks** [comment]
@adamhannigan yep no rush. still have time before next release :)

**Comment by j923sneaks** [comment]
> update share link in `Menu.tsx`

Will pick this up
