### ISSUE TITLE
[PROPOSAL] Do not withdraw tokens on May 9, you will receive NFT

### ISSUE THREAD

**Issue by IvanSkazkin** [sunflower-land/sunflower-land#825]
**Hello**
Who will not withdraw tokens from May 9 to May 20 will receive an NFT sunflower holder
This will help prevent people from immediately withdrawing coins at the start
Nft gives +20 sunflower yield
Either increase the supply of seeds by 100

**Comment by SuperSynapse** [comment]
Withdrawal of SFL is important for commerce and the LP. 

I appreciate the sentiment of holding, but also realize this allows people to buy too. Just like the marketplace getting added for resources, having a value on items IS the purpose of the game.

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3
