### ISSUE TITLE
[FEAT] Import SFL token address to Metamask.

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#828]
Once a user withdraws SFL, it would be good to add the token address into their Metamask. This will make it easier for them to see the SFL that has been transfer.

**Includes**

Once SFL is withdrawn, inside of the success modal include a button to add the token to your wallet.

1. User Withdraws SFL
2. Success modal shows
3. User clicks button to add SFL token address to Metamask

**Technical Details**

See this API - https://ethereum.stackexchange.com/questions/99343/how-to-automatically-add-a-custom-token-to-metamask-with-ethers-js

**Comment by newb23** [comment]
Dibs! I got this one!

**Comment by Pranav-yadav** [comment]
> Dibs! I got this one!

/wen Add SFL Token button 
Jk ... take your time.. 😄
