### ISSUE TITLE
[BUG] Unable to Sync After Update

### ISSUE THREAD

**Issue by LUNCHBOX404** [sunflower-land/sunflower-land#836]
I have not been able to sync my farm after the update today at around 9p EST. There's an error in the contract. Help!

What's been done so far:
Crtl + Shift + R on Sunflower Lands tab
Reset MetaMask in advanced 

![sfl-unable_to_sync](https://user-images.githubusercontent.com/104640972/167324535-31f4686f-16a5-4f31-aca8-40d171c396be.png)

Farm #31777

**Comment by SuperSynapse** [comment]
Lots of people in the #Farmer-chat are dealing with this issue in the discord.

**Comment by LUNCHBOX404** [comment]
This issue can close now. I was able to sync.
