### ISSUE TITLE
[MISTAKE] Doesn't display t2 scarecrow

### ISSUE THREAD

**Issue by IvanSkazkin** [sunflower-land/sunflower-land#837]
After the update, does not display t2 scarecrow. The scarecrow is not used on the farm. Everything is grown, synchronization was done before that. And still can't get out 
I can't withdraw opensea

**Comment by SuperSynapse** [comment]
My game is bugged (can't sync) but my goblin scarecrow is showing just fine.

Not saying you aren't having an issue, just wanted to add it may be unique to your account.

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3
