### ISSUE TITLE
[Proposal] Enhance social attributes, game attributes: names, marriage system, new ways to generate land, honor, replicas, social division

### ISSUE THREAD

**Issue by blockpanda** [sunflower-land/sunflower-land#841]
Sunflower Land is supposed to be a casual game, but crops with shorter maturity time have higher returns, which will lead to taking up a lot of farmers' time on planting, making farmers more utilitarian than entertaining and not achieving the effect of relaxation and leisure. So I think we should add game attributes, social attributes. Let the farmers spend their time on the game entertainment, harvesting happiness and making money, instead of only planting.

1. Name identification.
Farmers can spend a certain amount of SFL, for example, 1 SFL, to cast a farm nameplate with their own exclusive name, such as LIU's farm.

2. Marriage system.
Farmers need to choose their gender and upload their contact information to the marriage system. When the farm reaches a certain level, farmers can make a random match on the marriage system, and men and women will add friends to discuss whether to build houses, get married, and produce offspring. To build a house, both parties need to provide equal materials and SFL, and to produce offspring, they need to provide SFL and time.

3. New way of adding farms.
The offspring produced by the farmer will have a piece of his own farm, submit the farm to the official and get a certain SFL, and the official will issue the farm to the new comer.

4. Honor system.
After decorating NFT will get a certain honor value, the honor value of the top 100 players will get a certain bonus

5. Copy system.
Add copies, farmers need to team up and pay SFL to explore the copies and get rare materials

6. Social division of labor.
Divide players into different professions, some rare items need different professions of players to complete together.

A good GameFI should have a good depth and breadth, vertical level division allows players to have room to explore the horizontal content, players get positive feedback in the play, in the positive feedback in the continuous output (assets released in the game), and these outputs can also be consumed in different dimensions (the "output" of the assets used up behavior). The social attribute is crucial to make players pay more attention to long-term value, build their own farms, and achieve "effective consumption", which means that players consume SFL not for the purpose of earning more, but for gameplay and socialization, showing their social value in the game. The "effective consumption" means that players consume SFL not for earning more, but for gameplay and socialization, showing their social value in the game.

**Comment by Netherzapdos** [comment]
I'm not sure with your reasoning on your first paragraph. Literally NO ONE is forcing anyone to plant the shorter time plants. This is very much still a casual game. It's up to the player whether they want to take a more active or passive approach when playing the game.
