### ISSUE TITLE
BUG,why my land be strange? i pay it so much money to buy NFT in opensea

### ISSUE THREAD

**Issue by wuxie1993** [sunflower-land/sunflower-land#842]

**Comment by wuxie1993** [comment]
Since the casting of my land, I have planted my land regularly every day and paid attention to the project dynamics, and bought a lot of NFT in the opensea. But today, my land has been blocked, can you tell me why? So multi-script players you don't ban, but to ban a real sincere player

**Comment by Pranav-yadav** [comment]
> @adam Hannigan

you tagged as well as pinged wrong Adam 🤣

**Comment by wuxie1993** [comment]
@adamhannigan

**Comment by wuxie1993** [comment]
@adamhannigan i need your help，As a loyal planter, I am really angry about this incident

**Comment by wuxie1993** [comment]
@Stevew00dy hey，handsom woody，i just want a answer

**Comment by Amelavnyt** [comment]
Guys look at discord buying land from opensea has a risk

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
