### ISSUE TITLE
[IDEA][ART] Updated Blacksmith.

### ISSUE THREAD

**Issue by VadimasVP** [sunflower-land/sunflower-land#847]
Hey everyone.

Nothing special, just added some details and NPC.

![blacksmith_building1](https://user-images.githubusercontent.com/102822587/167479145-cf3c5a28-94f3-44d5-a910-c8eb273b5829.gif)

![blacksmith_buildingbig1](https://user-images.githubusercontent.com/102822587/167479211-3fc13e33-8385-4455-9ca0-e13c9d871974.gif)

![blacksmithdiffernce](https://user-images.githubusercontent.com/102822587/167478726-bb05c70f-4f6a-4ed9-b439-a39c335a0545.gif)

Also, since there are no more NFTs left, only tools. It might be more correct to rename it to "Blacksmith", just my opinion.

**Comment by SuperSynapse** [comment]
Good suggestion!

**Comment by alvinphoebeartemis** [comment]
Hi @VadimasVP looking into it. 😊 I'll create a PR for this.

**Comment by VadimasVP** [comment]
> Hi @VadimasVP looking into it. 😊 I'll create a PR for this.

It would be great. Thank you.

**Comment by alvinphoebeartemis** [comment]
HI @VadimasVP already created a PR. We are waiting for the approval of Adam. Thank you :)
