### ISSUE TITLE
[BUG REPORT] Can't withdraw Scarecrow while seed in INVENTORY

### ISSUE THREAD

**Issue by Ozweeg** [sunflower-land/sunflower-land#848]
I wanted to withdraw my Scarecrow and sell it, i gathered all vegetables from beds and made a sync with blockchain with 22 empty beds
![image](https://user-images.githubusercontent.com/91004257/167480266-d2f871bc-589f-4caf-8f26-c3c80131cc88.png)
I asked about this problem in different chats, and some people met same problem, this problem appears because i have seed in my inventory
![image](https://user-images.githubusercontent.com/91004257/167480504-a51330de-83d9-455a-bfa9-a4f017c97ed5.png)
But I had to be able to withdraw the scarecrow, because of the presence of seeds in the inventory prohibits to withdraw only Kuebiko
![image](https://user-images.githubusercontent.com/91004257/167481193-3a86994f-16b6-4f97-9829-34a4079749a2.png)
My friend has the same problem with Nancy

**Comment by brian-man** [comment]
My spidey sense tells me this relates to Goblin Town changes (crafting durations / withdraw period) rather than seeds.

**Comment by brian-man** [comment]
Update: Issue understood.

You crafted a Goblin Crown 10 hours ago.  You have 6 days and 14 hours left before you can Withdraw any of the interesting FTs.

- The farm in question
https://opensea.io/assets/matic/0x2b4a66557a79263275826ad31a4cddc2789334bd/34208
- EOA
https://polygonscan.com/address/0x9615879d2f6bE3765FC36fC2E1826e84c3c72f42
- Farm contract address's token transactions
https://polygonscan.com/address/0x7173a09112f3cf3264e7c84b6303cfb565526430#tokentxnsErc1155
- Transaction the minted a Goblin Crown
https://polygonscan.com/tx/0xb5406616aaf89888289b215512fa19eb53bb923236ccf5cd794620d35fd4260d

@adamhannigan Please confirm this is intended behavior.

**Comment by Ozweeg** [comment]
> Update: Issue understood.
> 
> You crafted a Goblin Crown 10 hours ago. You have 6 days and 14 hours left before you can Withdraw any of the interesting FTs.
> 
> * The farm in question
>   https://opensea.io/assets/matic/0x2b4a66557a79263275826ad31a4cddc2789334bd/34208
> * EOA
>   https://polygonscan.com/address/0x9615879d2f6bE3765FC36fC2E1826e84c3c72f42
> * Farm contract address's token transactions
>   https://polygonscan.com/address/0x7173a09112f3cf3264e7c84b6303cfb565526430#tokentxnsErc1155
> * Transaction the minted a Goblin Crown
>   https://polygonscan.com/tx/0xb5406616aaf89888289b215512fa19eb53bb923236ccf5cd794620d35fd4260d
> 
> @adamhannigan Please confirm this is intended behavior.

**Comment by brian-man** [comment]
> But i crafted my Scarecrow before this changes in the game, its not ok i think

The current implementation cares about when you last craft _anything_.  The age of the item you want to withdraw is irrelevant.

I don't like this design FWIW, which is why I asked Adam to confirm if the implementation has this behavior intentionally or not.

**Comment by MarketParticipant** [comment]
Crafting is not the only issue.  I haven't crafted anything since 4/25 and can't withdraw a Nancy.
