### ISSUE TITLE
[Request] Fix Saving Progress

### ISSUE THREAD

**Issue by system32uwu** [sunflower-land/sunflower-land#85]
Please keep this off-chain for some time and then synchronize gradually, who thought saving directly to the blockchain every 25 minutes was a smart idea? (It obvious 99% of the players are bots farming stuff) The whole network is down trying to process all this transactions, it seems you didn't even bother to use the testnet first to stress-test this "feature".

You can cache or store all the changes in IPFS if you want a decentralized system so badly, and then go gradually sending those transactions to the blockchain with an automated tool (query from ipfs -> push transactions to smart contract). You'll of course have to decide what must be instantly recorded in the blockchain in case there's something so important. The user can pay the estimated gas fees in advance to the contract or to another contract that will then make all the transactions happen. If you want the game to have success instead of massive hate this should be addressed ASAP.

**Comment by mattheuspirovani** [comment]
Sorry, but i completely disagree. From the Polygon website:

_Polygon combines the best of Ethereum and sovereign blockchains into a full-fledged multi-chain system.

Polygon solves pain points associated with Blockchains, like high gas fees and slow speeds, without sacrificing on security. This multi-chain system is akin to other ones such as Polkadot, Cosmos, Avalanche etc, but with at least three major upsides_

Well, if that's the proposal, they shouldn't have a problem with a lil farm game.

Keep the game 100% ON Chain. To me, that's the only way to evolve the tech.

**Comment by Pranav-yadav** [comment]
Guess what, it's not their (Sunflower Farmers dev's) concern, dev's ( @maticnetwork and @0xPolygon ) Polygon Network should've done this kind of testing (on test network).
Obviously, Polygon dev's r aware that such hype could cause their blockchain to get congested due to tons of transactions and should be their concern.

Btw, I also think that using IPFS or (similar decentralized system) could help.

PS: I'm newbie in Blockchain 🙂

> Please keep this off-chain for some time and then synchronize gradually, who thought saving directly to the blockchain every 25 minutes was a smart idea? (It obvious 99% of the players are bots farming stuff) The whole network is down trying to process all this transactions, it seems you didn't even bother to use the testnet first to stress-test this "feature".
> 
> You can cache or store all the changes in IPFS if you want a decentralized system so badly, and then go gradually sending those transactions to the blockchain with an automated tool (query from ipfs -> push transactions to smart contract). You'll of course have to decide what must be instantly recorded in the blockchain in case there's something so important. The user can pay the estimated gas fees in advance to the contract or to another contract that will then make all the transactions happen. If you want the game to have success instead of massive hate this should be addressed ASAP.

**Comment by system32uwu** [comment]
> Well, if that's the proposal, they shouldn't have a problem with a lil farm game.

Which "lil" farm game? I see a huge farm game here, but size is not the problem (AXS is even bigger than this), the problem is how you're handling data, the biggest error here was to assume you can implement a game in Solidity for a Blockchain like you would in Node for a private dedicated VPS. Using structs and arrays everywhere and looping through them with a lot of conditionals at once requires a lot of computing power, up to the point that you'll need to do what AXS did which is creating your own Blockchain.

> From the Polygon website

Polygon can only take 7.2k TPS, there's no need to read anywhere else nor to blame the technology itself. Name a sidechain that can take more than that without reaching the current state of Polygon, if you can, then just migrate to it.

Otherwise just restricts bots, using captchas or whatever, your interpretation of scalability is farfetched if you keep thinking this is a viable implementation for the blockchain.

> Keep the game 100% ON Chain. To me, that's the only way to evolve the tech.
To evolve what? There are hundreds of thousands of technologies, Polygon is not the only one, for a solution like this you should always implement caching like any other game does, but it's a **must** in this case since we're dealing with the Blockchain and not with a private server which resources are dedicated only to yourself.

> dev's ( @maticnetwork and @0xPolygon ) Polygon Network should've done this kind of testing (on test network).
?..
> PS: I'm newbie in Blockchain slightly_smiling_face
Ah, makes sense. Just learn the basics of Solidity and Blockchain, once you read the smart contracts that were written in this project you'll understand how ridiculous it is.

**Comment by arthurbolsoni** [comment]
the focus of the project is to be fully blockchain with no external servers. if you think the game should be off-chain just quit github and choose another project to collaborate on. it's a total waste of time this kind of discussion on github, where the focus is on developers

**Comment by mattheuspirovani** [comment]
@system32uwu 
I'm from Brazil, here any public app reaches millions of users easily. Compared to what I'm used to in my daily basis, the game is small.

"7.2k TPS", you can't take that number seriously.

But it's like @arthurbolsoni  said, the project's focus is different. You can participate in other initiatives.

**Comment by system32uwu** [comment]
> the focus of the project is to be fully blockchain with no external servers

Do you even know what the blockchain is? Just google it:

> a system in which a record of transactions made in bitcoin or another cryptocurrency are maintained across several computers that are linked in a peer-to-peer network.

The blockchain is a set of external servers that are distributed, so your statement makes no sense. In my original comment I even mentioned that if you wanted to be fully **decentralized** (which is the word you should've used instead), you can totally user other systems, like IPFS (which almost every dApp and blockchain game uses).

What does the rest of your comment mean? I'm a GitHub user because I contribute to FOSS development and I'm doing my contribution here, I admit that my original comment was personal, but I explained the problem and provided a possible solution to it, and even explained why you can't implement a game for the blockchain in the same way you would for a private server of your own.

> it's a total waste of time this kind of discussion on github, where the focus is on developers

So, you like open source software yet you don't approve users of said software to complain about it failing in a certain aspect? It seems you haven't been here for long and have never read the mailing lists of other software projects.

"This kind of discussion on github"? I invite you to read [the kind of discussions GitHub was made for](https://docs.github.com/en/discussions), which seems you have never read, I'll quote it for you so you don't keep "wasting" your time in this discussion.

> GitHub Discussions is a collaborative communication forum for the community around an open source project. Community members can ask and answer questions, share updates, **have open-ended conversations**, and follow along on decisions affecting the community's way of working.

**Comment by Pranav-yadav** [comment]
> > Well, if that's the proposal, they shouldn't have a problem with a lil farm game.
> 
> Which "lil" farm game? I see a huge farm game here, but size is not the problem (AXS is even bigger than this), the problem is how you're handling data, the biggest error here was to assume you can implement a game in Solidity for a Blockchain like you would in Node for a private dedicated VPS. Using structs and arrays everywhere and looping through them with a lot of conditionals at once requires a lot of computing power, up to the point that you'll need to do what AXS did which is creating your own Blockchain.
> 
> > From the Polygon website
> 
> Polygon can only take 7.2k TPS, there's no need to read anywhere else nor to blame the technology itself. Name a sidechain that can take more than that without reaching the current state of Polygon, if you can, then just migrate to it.
> 
> Otherwise just restricts bots, using captchas or whatever, your interpretation of scalability is farfetched if you keep thinking this is a viable implementation for the blockchain.
> 
> > Keep the game 100% ON Chain. To me, that's the only way to evolve the tech.
> 
> To evolve what? There are hundreds of thousands of technologies, Polygon is not the only one, for a solution like this you should always implement caching like any other game does, but it's a **must** in this case since we're dealing with the Blockchain and not with a private server which resources that are dedicated only to yourself.
> 
> > dev's ( @maticnetwork and @0xPolygon ) Polygon Network should've done this kind of testing (on test network).
> 
> ?..
> 
> > PS: I'm newbie in Blockchain slightly_smiling_face
> 
> Ah, makes sense. Just learn the basics of Solidity and Blockchain, once you read the smart contracts that were written in this project you'll understand how ridiculous it is.

### I think you r getting crazy because, either you want to cash out from polygon mainnet or your tx is stuck.. 😂
PS: no offense

**Comment by system32uwu** [comment]
I closed on accident, mb

**Comment by system32uwu** [comment]
> @system32uwu I'm from Brazil, here any public app reaches millions of users easily. Compared to what I'm used to in my daily basis, the game is small.
> 
> "7.2k TPS", you can't take that number seriously.
> 
> But it's like @arthurbolsoni said, the project's focus is different. You can participate in other initiatives.

What's a "public app"? Is it a game like sunflower farmers that runs in the blockchain?

**Comment by system32uwu** [comment]
> ### I think you r getting crazy because, either you want to cash out from polygon mainnet or your tx is stuck.. joy
> 
> PS: no offense

What does that have to do with the current discussion? And in any case that's more reason for me to be discussing this here, this product is affecting not only its user's experience but every other user of the network as well.

**Comment by mattheuspirovani** [comment]
> What's a "public app"? Is it a game like sunflower farmers that runs in the blockchain?

This discussion will not take place, after all we are not part of the project. You have your point of view and i have my. Respect you.

After all, why dont you send me some Lapataia?

**Comment by system32uwu** [comment]
You don't even understand what OSS is: 

> after all we are not part of the project

which just shows the level of discussion some of the defendants of this project has, I'm muting notifications and hoping the developers read my original proposal not scrolling to this end, I'd be ashamed to have such individuals in my projects.

**Comment by Pranav-yadav** [comment]
> You don't even understand what OSS is:
> 
> > after all we are not part of the project
> 
> which just shows the level of discussion some of the defendants of this project has, I'm muting notifications and hoping the developers read my original proposal not scrolling to this end, I'd be ashamed to have such individuals in my projects.

Best of luck. Though, as I'd mentioned earlier, I support that looking towards IPFS or similar decentralized system may help for this problem. 👍

**Comment by mattheuspirovani** [comment]
>who thought saving directly to the blockchain every 25 minutes was a smart idea?

With this kind of statement, would be a shame if you are in.

**Comment by ruevers** [comment]
> > who thought saving directly to the blockchain every 25 minutes was a smart idea?
> 
> With this kind of statement, would be a shame if you are in.

Sorry man, but he make the point, doing game save every 25 minutes is screwing up the polygon network, and other games and users who respect the phisical limits of the network. So I think if the devs not solve the problem, the market will do by yourself.

**Comment by adamhannigan** [comment]
Hey everyone, some great discussion points here. Let's just remember to try keep it focussed on the issues at hand and the technical solutions we can propose.

Our vision is to be a completely on chain game. We are racing against centralised MetaVerse ideas to become the real MetaVerse which is owned by the community.

**Comment by Tracya2021** [comment]
I am not a blockchain technician or a computer scientist. I understand something but in an amateur way.
I have been playing Sunflowers Farmers for two days and there is no way to play, the gas rates are very high and 80% of the txns fail.
The idea seems good to me for what is in the immense but disappointing for the fledgling world of Play to Earn, but if it continues like this I think it will starve since it is not playable.
It is just a player's usage opinion.

**Comment by arthurbolsoni** [comment]
there is not only one polygon blockchain to place the game.

**Comment by system32uwu** [comment]
What was obvious ended up happening. I actually congratulate the developers on their decision to temporarily disable the game, and I hope to see some of the suggestions discussed here implemented for the next version. Recognizing errors and listening to users is key to success, I wish you guys the best.

Just remember that 100% on-chain is impossible for a game this big, but it can be 100% decentralized with other solutions like IPFS as mentioned. And finally, you can always create your own blockchain, like Axie Infinity did with Ronin

**Comment by adamhannigan** [comment]
Our dream is decentralisation but we can not get there on our first deployment.

On launch, we will have aspects of centralisation. Our design methodology is to deploy in a way in which we can hand the control over to a DAO, oracles and hopefully purely on-chain one day.

Right now the technology does not exist for completely on-chain at this sort of scale. We will get there. The hope is that this project becomes a catalyst for people to learn about the on-chain versus off-chain debate and actually come up with a decentralized solution!

**Comment by adamhannigan** [comment]
@system32uwu The new Sunflower Land includes a mix off off-chain data which enables users to save when they want. 

Closing this issue as it will be addressed in the new release. Thanks
