### ISSUE TITLE
[IDEA] [ART] Moroccan Couscous

### ISSUE THREAD

**Issue by OverDr1ve** [sunflower-land/sunflower-land#851]
Hi, I’m proposing a new item to craft that will allow players to unlock additional farming slots.

This item comes with a Moroccan touch, it’s Couscous. The most popular in Morocco is the Couscous with 7 vegetables.

The idea is to combine 7 vegetables to craft it.

Recipe example :
- 50 Potatoes
- 50 Pumpkins
- 50 Carrots
- 50 Cabbage
- 50 Beetroot
- 50 Cauliflower
- 50 Wheat

I was just trying to work with what’s available, but it would be more authentic if we replace  :
- Beetroot with Onions (non-existent crop)
- Cauliflower with Tomatoes (non-existent crop)

![DFD33520-942C-468C-B360-85429C34AEF2](https://user-images.githubusercontent.com/49151446/167499912-7f764a05-8dfc-45b6-bc8b-0e57033c8db9.png)

![9CF90E4E-8E6E-4409-ADE2-D6E3D2B6761F](https://user-images.githubusercontent.com/49151446/167499916-6c118284-0208-48ae-9c48-825a957f8678.png)

Aaand let’s not forget about the goblin (again with a moroccan touch 😁):

![B25B3F76-5416-4300-B617-8C83C0D00779](https://user-images.githubusercontent.com/49151446/167500256-d99ceda8-2352-4218-b379-eefde9c3a973.gif)

![EDAE5549-B142-46D1-A679-84918BA3A3AA](https://user-images.githubusercontent.com/49151446/167500251-20733a9e-e927-437f-85e5-ca922292d09c.gif)

Final look :

![D60C0D6C-F7E3-4874-BE04-54386EA1B24F](https://user-images.githubusercontent.com/49151446/167501332-5049db6d-2774-49c8-9bda-dd04952f3ba5.gif)

Discord : Nordmar#7145

**Comment by LeShykun** [comment]
Heeey i want this! Also cute goblin with tarbouche !

**Comment by Amon-S** [comment]
I was working for fun on a tajine but a that cous cous looks tasty <3

**Comment by Abidox808** [comment]
Awesome idea.

**Comment by na66ime** [comment]
mmmm looks tasty

**Comment by aayusharyan** [comment]
Quick question, this is a non utility NFT in the game?
Asking because recipies provide utility in the game.

**Comment by OverDr1ve** [comment]
@aayusharyan As I mentioned above, this item allows you to unlock additional farming slots.

**Comment by GoblinMoyo** [comment]
Im drawing Onions and Tomatoes right now. Tomorrow ill post here.
