### ISSUE TITLE
[PROPOSAL] Add a warning to next crop halving on shop NPC

### ISSUE THREAD

**Issue by future2back** [sunflower-land/sunflower-land#860]
Could you please add a warning to next halving on shop NPC?

For me it's the best place to notify everyone that it's not a good season to stock seeds. Should i click on NPC Shadow or join Discord every day?

40 wheat = Aprox 2 days
40 radish = Aprox 2 days
40 parsnip = Aprox 1 day
80 Cauliflower = Aprox 1 day and 5 Hours
80 Beetroot = Aprox 15 Hours
90 Cabbage = Aprox 8 Hours
100 Carrot = Aprox 5 Hours
100 Pumpkin = Aprox 2 Hours
....

More than 7 days of seeds stocked. Is it wrong to store seeds and make sure I keep playing and staking SFL for free?

My strategy was to reinvest but now I have to count how much time and SFL I lost doing my stock yesterday and woke up today with the announcement on discord that we ll have a halving at the same day. Imagine if you were a new player? Usually games can have a lot of information and players can play simultaneous games, dedicate yourself to real life, makes it difficult to be 100% dedicated to everything. which for me makes the need for everything to be very explicit.

We could have a real-time average of next halving?

Sorry if I'm lost, but has anyone else felt this way?

Sad.

Thank you.

**Comment by future2back** [comment]
Not to mention the crops that could have waited a little longer to making craft.

My strategy was to buy more SFL token when it was available to achieve my goals but I did not because of this feeling.

Surely people who collected SFL and sold felt better than I did. Crazy no?

The question is, what is the best profile for the health of this project? Which one was encouraged?



Think about it.

**Comment by gvmturl** [comment]
The least they should do to mitigate the damage is calculate the seeds and crops that people had before the halving and double the value, or something more fair.

**Comment by cdxgg** [comment]
I support the proposal

**Comment by brian-man** [comment]
> The least they should do to mitigate the damage is calculate the seeds and crops that people had before the halving and double the value, or something more fair.

The core team may have reasons they don't want to do this, but arguably that is mitigated by the seed holding limits and seed supply limits in the shop.

**Comment by future2back** [comment]
> The least they should do to mitigate the damage is calculate the seeds and crops that people had before the halving and double the value, or something more fair.

I don't believe it, but maybe preventive action for next time could happen.


> > The least they should do to mitigate the damage is calculate the seeds and crops that people had before the halving and double the value, or something more fair.
> 
> The core team may have reasons they don't want to do this, but arguably that is mitigated by the seed holding limits and seed supply limits in the shop.

They also could try changing Buy / Sell to Seeds / Crops

![image](https://user-images.githubusercontent.com/74167741/167788160-82abf533-b847-4d16-81b4-72d2db8e0321.png)

and add Sell to seeds and make it available if Kuebiko is not activated.

![image](https://user-images.githubusercontent.com/74167741/167788694-cb304a21-f56e-482e-ae47-3758d8b2053d.png)


Something like that. Also Halving warnings on shop and calculate an approximately time left.

**Comment by pegaxyracing** [comment]
Let's wait and see what the developers propose for this problem, I hope it doesn't go unnoticed.

**Comment by rodolfoddias0x** [comment]
Honestly, I see it as part of the game. You are a farmer, after all. I believe every player must be aware of the game rules and take their decisions around them. The way it is now, the decision making is actually an aspect of the gameplay. 

You can still stock your seeds and avoid paying fees, just be sure to take a look at the supply before you do it. The information is there, use it.

**Comment by future2back** [comment]
> Honestly, I see it as part of the game. You are a farmer, after all. I believe every player must be aware of the game rules and take their decisions around them. The way it is now, the decision making is actually an aspect of the gameplay.
> 
> You can still stock your seeds and avoid paying fees, just be sure to take a look at the supply before you do it. The information is there, use it.
> 
> You're talking about damage mitigation, but why should they be accountable of player's bad decisions? I also did lose some seeds but I totally understand it was my fault. I won't do it again. Lesson learned.

What I proposed was to add warnings as it was done for selling crops and going to the goblin village. Who wants to make a bad decision? It sounds like the players are just dedicated to this game?
It happened to me, you and more people because the information is not clear. Maybe you missunderstood, my intention was to strengthen the project and not ask for a mitigation.

Thank you.
