### ISSUE TITLE
[PROPOSAL] Specifying Town Hall Standards

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#861]
# Specifying Town Hall Standards

There are few points that I would like to put forward, to make sure this the purpose of *Town Hall* remains professional, ..

1. Add different role for Team (Adam, Romy and Spencer) as *Team* / *Core Team* / *Core Dev*
    Or
   Completely _Remove_ the core team members from Town Hall as the purpose of this is to show *Community Contributors* and 
   let interested players help them.. There's difference between *Core Team* and *Contributors*. And, hence the contributor badges must also be burned (only respective owners can burn) if any added to the Core Team farms (I know they need it for testing 👀, 3-4 are enough, burn others)
   PS: I would suggest latter, No hard feelings, ❤️ team

2. *Coder* & *Artist* roles are toooo(o_O) generic, we should add separate roles as
     - *Certified Coder* - those with "Certified Coder" role on SFL Discord. (Ask me, it's difficult to get this, and should be)
     - *Coder* - newbie coder *(late to the party but have great potential)* 🤓  (given manually)
     - *Certified Artist* - those with "Certified Artist" role on SFL Discord. 
     - *Artist* - newbie artist *(late to the party but have great potential)* ❤️  (given manually)
     
3. As per [2], separate the contributor level badges for all those, as well the their **`Levels`** in home, and the `%` of boosts provided.

4. Remove Admins (Woody, ChickenCX , other if exists), the same reason stated under [1].
    PS: No hard feelings, ❤️ admins

5. Take care of proper `%` of boosts provided for contributor levels, like Contributor Level 1 and 2
6. As, mentioned earlier if any wrong (in above context) badges are minted and sent to farms with wrong roles (like team or any other roles) they **must** be burned (only respective owners can burn).. (Irrespective of Team Supply 👀 )

PS: ATM this was posted, Contributors Include: Certified Coders, Coders, Certified Artists, Artists, Moderators, Ambassadors. 👍 

@adamhannigan @spencerdezartsmith @Rofrtd you should discuss on this and specify the `standards`.. 👍

If you support this proposal react to this post with yay 👍  else nay 👎

**Comment by aayusharyan** [comment]
This is a really great proposal.

**Comment by SuperSynapse** [comment]
Great proposal! I agree as well

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
