### ISSUE TITLE
[PROPOSAL] - Introduce a token / sub token name for micro SFL

### ISSUE THREAD

**Issue by aayusharyan** [sunflower-land/sunflower-land#862]
## Summary
With the speed of halvening, it will be soon that the new farmers will have very low fractional SFL balances. This would be a bit weird from a new gamer point of view. What I propose is that we introduce a smaller token (like 1/1000000th of SFL) and manage the halvening situation. Obviously, the fraction can be decided later (depending on the future of halvening). Bu the idea is something like having a smaller token which is easy to manage. It might take time to develop / implement that's why proposing this early so when we have say 3-4 halvening down the line, we can easily handle this as the token will be ready.

## Why we should consider this now?
The 5 million and 10 million halvening had a gap of like 3-4 weeks. So, next halvening should theoretically take 8 weeks and then 16 weeks and then 32 weeks (so, total 8 + 16 + 32 = 56 weeks), roughly a year, give or take. (And this is `without` addition of new players).
Currently, the buying price of sunflower is 0.00025, after 3 halvening, it will be 0.00003125 which is a really low number and we humans are used to 2 decimal, at max 4. So, 1 year down the line, the in game currency will be really low and people will feel difficulty in playing (in terms of calculating their yeilds). 

## Proposal
Create a newer and smaller token (or atleast in the UI) to handle it and show it better. I am not a crypto developer and I don't know if say wei/ETH or satoshi/BTC are same tokens or separate, but all I know is like the former is a very small number and latter is the commonly used currency to trade and I can chose to see my balance in either of them. (Then I guess they are the same currency, but idk, anyway). My proposal is to create something similar of that sorts which will give a better perception of the game. Something like microSFL (µSFL) (1 SFL = 1000000 µSFL). So, here after 1 year, 1 sunflower will be 31.25 µSFL which is a good and readable number.

## Future Plan
After that, next halvening will take another 1 year, then Sunflower buying price will be 15.625 µSFL and then after 2 more years it will be 7.8125 µSFL and then after 4 years, it will still be 3.90625 µSFL. Now, this is a total of 8 years from now. Which is plenty of time for us to plan and forsee in advance and till that time, the UI will be good (I mean, without this, it will be 0.00000390625 SFL and that's just a VERY VERY VERY low number to calculate the yeild in head).

## Priority?
I would suggest this is not a very high priority thing, but atleast get the discussion around this started, so by the time next halvening happens, or the one after that. We will have some sort of mechanism in place. (That would be about 6 months from now). This is long term discussion and not just an immediate fix/proposal.

**Comment by vrillx** [comment]
You make it sound like theres something wrong with the current token ..which is not..theres 10 mil available of it ..if you want more token buy more from quickswap ,or plant and sell seeds ....definetly NO .

**Comment by aayusharyan** [comment]
Hey @vrillx 
If you read the proposal carefully, I have mentioned that it might be possible to use it with the same token like how other major Cryptocurrencies are doing.

Also, this proposal was never about the upper limit of 10 million. This was about the lower limit of fractional SFL which would be difficult to comprehend by the players.

**Comment by adamhannigan** [comment]
@aayusharyan Some interesting ideas 🤗 

From a user experience POV, the decimal points are extremely ugly/confusing for new players.

I imagine new players coming and earning $0.0000025 for a Sunflower one day. This would seem extremely underwhelming for a player.

I like the proposal around different denominations. A huge part of this will be the language we use to convey this so the different denominations make sense. We have to remember that we are designing for a lot of first time crypto users.

Do you have any idea for the terms or gameplay/UI appearance of it?

**Comment by vrillx** [comment]
read this proposal again , twice, trying to figure out... wont we eventually end up to the same awkward to read numbers ?  ... just looking at those numbers you posted makes my head hurt ... i think the game should continually develop features ( like more ways to aquire sfl ) that keep us far away from those kinda of numbers or the need of a microtoken...

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
