### ISSUE TITLE
Contributing guidelines are Missing

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/sunflower-land#87]
### Issue:
- The Contributing guidelines are **not** specified in this repo (at least on main branch)
- **`CONTRIBUTING.md` file is missing**
> I'm not sure if this repo is open for outside contributions

### Possible solution: 😊
- I believe that adding **`CONTRIBUTING.md`** file with appropriate guidelines would make it easy for open source dev's to contribute.

**Comment by adamhannigan** [comment]
@Pranav-yadav Great suggestion! We are scaling so quickly and these sort of things help a lot :)
