### ISSUE TITLE
【提案】【建议社区投票】用1%的NFT交易手续费打造真实农场，给项目方一个“币价螺旋升天”超过BAYC的办法，保证SFL成为万倍币！

### ISSUE THREAD

**Issue by money9201** [sunflower-land/sunflower-land#873]
我希望大家都是这个自治游戏的一份子，多出一份力，来建设好这个游戏，建议发起投票，建议如下：
       1、游戏还在测试阶段，等待正式上线后，协议：利用游戏里各种nft交易的手续费1%转到一个黑洞地址收集，直到这个黑洞地址达到1000万美金后，将该黑洞地址经费交给第三方机构用于运营正式农场。建议官方用这个资金在全世界随便哪里包一块真实的农场。（可以是萨尔瓦多这种可以使用加密货币的地方，增加氛围）
       2、随着游戏中各种nft数量增加，nft收集率，进行排名rank 。（必须要算抵押超过1个月的nft进行排名，增加nft质押率）排名rank1-100，有资格享受该真实农村的每年收益10%平均按比例分配给这100人，每年免费游玩农场2次；rank100-500，每年免费游玩农场1次；rank500-1000，打5折游玩门票费用，VIP待遇；rank1000-10000，打7折，低级VIP待遇等。
       3、真实农村可以按照正规运营办法管理，另外农场对外开放，旅客过来游玩注册玩这个链游可以打9折门票！变相引流！真实农场数量规模可以随着这个游戏群体扩大而扩大，项目做大后可以在世界各地开更多的旅游农场，甚至全球很多国家都有这样的农场！这样的话这个游戏可能会比BAYC更加内卷上天。
       4、游戏内加入一下具有实际功能性nft，比如NFT女仆1，发售40个，持有该nft抵押一个月以上，每年可以享受该农场高级私人服务等。NFT女仆2，发售400个，持有该nft抵押一个月以上，每年可以享受该农场高级按摩服务等。可以发挥想象，加入各种能在农场中真实使用的nft项目，当然打造消耗的资源比例非常高。
     5、注重真实农场社交圈的培养文化，进一步引流，促进游戏玩家人数，通过游戏玩家人数进一步吸引到农场游玩，增加旅客人数，互相促进。
     6、希望大家支持的能够投票我的这个提议！

**Comment by money9201** [comment]
大家顶顶我啊 我的sunlfower 农场编号：251 大家可以来参观 哈哈

**Comment by axiyaya** [comment]
真实个好主意啊，看你农场，没少氪金吧

**Comment by money9201** [comment]
> 真实的好主意啊，看你农场，没少氪金吧

对呀

**Comment by money9201** [comment]
希望大家能支持这个想法
