### ISSUE TITLE
[PROPOSAL] In-game Marketplace

### ISSUE THREAD

**Issue by MarkLPB** [sunflower-land/sunflower-land#875]
Hello, is it possible to have **Marketplace inside the game?** So that players could trade their asset inside the game. I think this could also prevent scams from p2p trading. Thank you.

**Comment by vrillx** [comment]
its coming ..no eta on  it yet though

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
