### ISSUE TITLE
[BUG] initial url on local testing

### ISSUE THREAD

**Issue by JacobSobolev** [sunflower-land/sunflower-land#876]
when you test the client locally, the initial URL is http://localhost:3000/#/visit/undefined instead of http://localhost:3000/#/farm/undefined
it creates an issue when you test for new items and you have to correct the URL every time.

![image](https://user-images.githubusercontent.com/9072434/167817117-de7a294c-005e-4025-bfca-400e10c5b8d3.png)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
