### ISSUE TITLE
when can i play this game!

### ISSUE THREAD

**Issue by samljh** [sunflower-land/sunflower-land#877]
100,000 farms have already been minted!!  i can't into games...

**Comment by Amon-S** [comment]
This is not the place for this kind of question, please keep github for coding stuff, if you have more questions about the game you can go into discord

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
