### ISSUE TITLE
[IDEA] Playground 

### ISSUE THREAD

**Issue by DonatasDee** [sunflower-land/sunflower-land#880]
Art for this idea made by @VadimasVP , UI @tiffanydys. 

Howdy everyone,

I was recently thinking that we actually lack diversity on the map as far as representation comes, not only models but also skin color/gender and them actually interacting with one another - hence got an idea to make a _Playground_ for children characters to share and play in together. 

The blonde boy is a reference to [`Little Prince`](https://en.wikipedia.org/wiki/The_Little_Prince), this could be played around with in the future.

It also can work beautifully as an early wood sink alongside the SFL cost, it doesn't need buffs and could be used as a requirement for future events or mints as is the case with other decorations currently.

Price implementation and supply could vary but I would propose adding a fair cost of **500 Wood and 100 SFL** - Wood needs instant syncs to not diminish value of beavers, SFL could get some minimal support also and considering the pricing of current SFL as of writing this (0.19 cents) the price point of 100 seems fair. 1000 Supply also keeps the item semi-rare, that however is the point that is easily the most interchangeable.

**UI**

https://user-images.githubusercontent.com/102658496/168206649-9ce61265-53b2-482b-b863-898587613854.mov

Most of the assets are animated, their placement on the map, near the road to Goblin Village.
![image](https://user-images.githubusercontent.com/102658496/167919422-45d113c0-96f7-4f03-a15d-d3636a6cdf0d.png)
**ACTUAL ASSETS**

![icon](https://user-images.githubusercontent.com/102658496/167919104-c3365cc9-dc2c-4796-810f-55b7fe900c4d.gif)
![iconbig](https://user-images.githubusercontent.com/102658496/167919175-b97cada2-ac05-458f-a340-3d99791b1e29.gif)

![playing](https://user-images.githubusercontent.com/102658496/167916870-072a4c86-e429-4b28-8a80-a8214e57d177.gif)
![playingbig](https://user-images.githubusercontent.com/102658496/167916873-ae4054ae-838b-42d7-bedc-c7eadff156be.gif)

![swing](https://user-images.githubusercontent.com/102658496/167916217-be66798c-5dc7-4bac-a4db-8a6489ee80d5.gif)
![swingbig](https://user-images.githubusercontent.com/102658496/167916220-8b96ad04-4c7d-4714-b325-1f21fe08b410.gif)
![swing1](https://user-images.githubusercontent.com/102658496/167916244-a014c4d7-9887-470d-a36f-f7374acc6260.gif)
![swingbig1](https://user-images.githubusercontent.com/102658496/167916249-9dd28500-a79f-4c39-8fee-706129c14891.gif)

![decor](https://user-images.githubusercontent.com/102658496/167916324-6c24f4a9-0045-4f9d-87d9-365b6895c2eb.png)
![decorbig](https://user-images.githubusercontent.com/102658496/167916325-13d2209a-4987-4932-90b3-d1a04dc6c599.png)
![decor1](https://user-images.githubusercontent.com/102658496/167916414-3ad828a3-da29-4f74-a7aa-653cad5637fb.png)
![decorbig1](https://user-images.githubusercontent.com/102658496/167916417-62359b0c-0a6a-4d3a-8197-a431cc708b0b.png)
![decor3](https://user-images.githubusercontent.com/102658496/167916446-b17a34ae-aa6d-412d-800b-a5141b4d9668.png)
![decorbig3](https://user-images.githubusercontent.com/102658496/167916450-0bcfe3ee-76de-442e-94ca-2f072cebb9d9.png)

**Comment by LeShykun** [comment]
YES I WANT THIS !!! great proposal lads i wish it gets into the game somehow

**Comment by LittleEins** [comment]
Got some goosebumps with that literary reference @DonatasDee ! I really loved that work of Antoine de Saint-Exupéry <3 We really have to see that child inside us even if we're adult already <3 Loved the quote of the fox and it will always have a place in my heart <3 Lets continue to tame each other and build a strong relationship with the community <3

**Comment by Grraarrgghh** [comment]
This is the kind of content I come for

**Comment by SteveChickenCX** [comment]
I love it! , As this is a big structure ingame I would recommend increasing the wood requirements .

**Comment by DonatasDee** [comment]
> I love it! , As this is a big structure ingame I would recommend increasing the wood requirements .

Was thinking of doing 500 Wood at first

**Comment by DonatasDee** [comment]
**UPDATED PRICE TO 500 WOOD AND 100 SFL**

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
