### ISSUE TITLE
[PROPOSAL] PART 1 OF  A 3 PARTS EVENT : BANTER STAGE

### ISSUE THREAD

**Issue by Z1kou** [sunflower-land/sunflower-land#882]
### This is part one in a three parts event : BANTER STAGE  It contains a detailed description of what this part includes, and information on the work that has been done on it !

TEAM: 🌻 🌻  @Z1kou, @Amon-S, @Aetherzapdos, @Vergelsxtn, @๛MG『Λlpha | AME, @rigale, @RadishPies 🌻 🌻 

- [x] Creating Assets for both the stage the crowd Animating the Team assets made by @aestnelis,
- [x] Adding stage With a crowd Animation
- [x] Adding Team NPC's with animation, And a message From The Team
- [x] Adding A Easter Egg
- [x] Adding Sound effects & Music for everything above
- [x] Coding and maintaining All of the above with the daily changes of the game  (Thanks to  @Amon-S ❤️ )

This banter stage idea started with @Vergelsxtn Wanting to celebrate the launch of the game, We took it and implemented it in our vision of our event that will introduce both Elemental Wizards & Axololts in the game, We have added animation for every NPC of the team, Created the stage with a crowd Animated and kept growing our team as we are working on it, we ended up making everything from assets and their animation, to the music side of the event and then finally the implementation of everything, Here is a  preview of all the functions of the event it represents the hard work of more than, Show my boys some love everyone and enjoy ❤️ 

**PREVIEW LINK** : [https://streamable.com/f4zr0c](url)

**Comment by SteveChickenCX** [comment]
This is incredible! 
It actually makes them game feel much more alive!

Suggestions:

1. Swap Chicken to the barn area
2. text box can be : ....... text......... - name of character 
3. could be nice to let the character walk further (if it doesn't require much more work)


Is it possible to add more text boxes for every character and randomly choose one each click? (could be fun) 

well done friends, glad to see you work together to achieve great things!♥

**Comment by Amon-S** [comment]
> This is incredible! It actually makes them game feel much more alive!
> 
> Suggestions:
> 
> 1. Swap Chicken to the barn area
> 2. text box can be : ....... text......... - name of character
> 3. could be nice to let the character walk further (if it doesn't require much more work)
> 
> Is it possible to add more text boxes for every character and randomly choose one each click? (could be fun)
> 
> well done friends, glad to see you work together to achieve great things!♥

Hey, Chicken thank you for reviewing.
I will need more quotes from the team to make more

**Comment by LeShykun** [comment]
Incredible work friends ! from all the aspects, would love to see this in game

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
