### ISSUE TITLE
[ART] DINOSAUR EXHIBITION

### ISSUE THREAD

**Issue by victorrabello** [sunflower-land/sunflower-land#885]
I wanted to make a fun decoration that matches something in the game, I thought it was fun to make a dinosaur and it would look interesting on the farm (I took a reference, but I wish someone wiser could do better hahah)

![dino](https://user-images.githubusercontent.com/90971807/167981453-a8d7404f-183d-47c2-a6c0-c5026a0e63bf.png)

![dinoDs](https://user-images.githubusercontent.com/90971807/167981471-e6f1cfd2-8e3d-4084-9ec9-f7af691c475c.png)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
