### ISSUE TITLE
[SUGGESTION] Add additional GitHub <actions> to keep the repo tidy

### ISSUE THREAD

**Issue by newb23** [sunflower-land/sunflower-land#887]
Some of these do similar, or in some cases, the exact same things, but, I wanted to provide options.

https://github.com/marketplace/actions/close-stale-issues
https://github.com/marketplace/actions/issues-translator
https://github.com/marketplace/actions/triage-issues
https://github.com/marketplace/actions/auto-label
https://github.com/marketplace/actions/super-labeler
https://github.com/marketplace/actions/needs-attention
https://github.com/marketplace/actions/multi-labeler
https://github.com/marketplace/actions/pr-title-checker
https://github.com/marketplace/actions/pr-label-by-files
https://github.com/marketplace/actions/add-to-github-projects-beta

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
