### ISSUE TITLE
Animals death

### ISSUE THREAD

**Issue by RichRick76** [sunflower-land/sunflower-land#890]
I suggest that animals should die if not feed for a few days. Because like in real world we feed them 2-3 times a day. In sunflowerland maybe 2-3 days not feed should die or should cost some sfl to revive them. Its also a burning mechanism for animals/sfl as well. Thanks so much

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
