### ISSUE TITLE
[BUG] Unable to Sync After Update

### ISSUE THREAD

**Issue by xanxuz** [sunflower-land/sunflower-land#894]
I tried to sync after the update of the halving and my farm can't sync anymore. This has been the case for many people in the discord server, so I'm opening this issue for everyone with the same problem to expose their case here.

What I found so far is that many are getting the same error (deadline passed) when trying to make the sync even if the fee is ridiculous high

### This is the case for the [Contract 0x48be563a8090cf756ca8595252f144cbba31b238](https://polygonscan.com/address/0x48be563a8090cf756ca8595252f144cbba31b238)

**Extreme high fees**
![image](https://user-images.githubusercontent.com/11968584/168087886-eb2afb18-b5e9-4db5-9859-56b81fb302fc.png)

**Multiple transaction errors on the contract**
![image](https://user-images.githubusercontent.com/11968584/168086904-ed9480b7-e9e8-4ffd-90c2-c4853376019e.png)

**Detail of one contract with the same transaction error**
![image](https://user-images.githubusercontent.com/11968584/168086983-7804125f-b588-4457-b0ae-c80a4b16506d.png)

**Comment by ThomasDev62** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by tryjapa** [comment]
Similar problem... not able to interact with any option on goblin town :( always getting high fees(like 6, 9, 15 matic).
But synch the farm is working fine.

**Comment by xanxuz** [comment]
> Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

The problem is not polygon, it's the game itself who has the problem, try to make a transfer between some of your accounts, and you will see that the transfer will go through as usual.

**Comment by xanxuz** [comment]
> Similar problem... not able to interact with any option on goblin town :( always getting high fees(like 6, 9, 15 matic). But synch the farm is working fine.

Can you share a link from **polygonscan** with your transaction and screenshot (as I did in the description of the issue)? That way we can facilitate the info to the devs and anyone who has the same problem as you

**Comment by spencerdezartsmith** [comment]
> I tried to sync after the update of the halving and my farm can't sync anymore. This has been the case for many people in the discord server, so I'm opening this issue for everyone with the same problem to expose their case here.
> 
> What I found so far is that many are getting the same error (deadline passed) when trying to make the sync even if the fee is ridiculous high
> 
> ### This is the case for the [Contract 0x48be563a8090cf756ca8595252f144cbba31b238](https://polygonscan.com/address/0x48be563a8090cf756ca8595252f144cbba31b238)
> **Extreme high fees** ![image](https://user-images.githubusercontent.com/11968584/168087886-eb2afb18-b5e9-4db5-9859-56b81fb302fc.png)
> 
> **Multiple transaction errors on the contract** ![image](https://user-images.githubusercontent.com/11968584/168086904-ed9480b7-e9e8-4ffd-90c2-c4853376019e.png)
> 
> **Detail of one contract with the same transaction error** ![image](https://user-images.githubusercontent.com/11968584/168086983-7804125f-b588-4457-b0ae-c80a4b16506d.png)

Hey there... the error you are getting `SunflowerLand: Deadline Passed` happens when the transaction goes for longer than 5 minutes. The solution here would be to increase gas as polygon is congested and your transaction is taking too long.

**Comment by xanxuz** [comment]
@spencerdezartsmith That's the case for one random transaction I pick from the contract in polygonscan that has the same problem as me.

Although when I tried Trust wallet app and Microsoft Edge the error appears to be different

![image](https://user-images.githubusercontent.com/11968584/168311292-588a5960-0eac-4a28-b597-98223e09e14a.png)

![image](https://user-images.githubusercontent.com/11968584/168311252-ffcc5b3d-1d1d-464b-84c4-093275d52edb.png)

**Comment by xanxuz** [comment]
I ended up resetting my session and I managed to sync. I lost profit from before/after halving.

Good luck to anyone trying to solve this without losing his progress.
