### ISSUE TITLE
Sync Issues after May 9 update

### ISSUE THREAD

**Issue by AerySviel** [sunflower-land/sunflower-land#895]
Good day!

I was able to sync after the May 9 10-million halvening, but didn't receive replenishment of seed.

Tx: 0xee10cae59c6519d192b49a265501352476e81d8cc2d1392bcf4f65ae2dfbbf3b

Tried to sync again but getting gas fee errors and "too many requests errors".

Continued farming with remaining seeds, then yesterday May 11,  I saw in Discord that restoring session worked for others, so tried it and farm state was back before the halvening (It's as if my previous sync was not recorded).

The seeds were there but lost SFL due to crop price difference after halving. 

Continued Farming but still can't sync until now due to gas fees. Pulled console and found an error on "Content Security Policy of your site block the use of eval in JavaScript".

<img width="705" alt="error" src="https://user-images.githubusercontent.com/105450696/168132952-27189f49-4a44-4068-a315-e3ecc7f74fe7.PNG">

**Comment by xanxuz** [comment]
#894

**Comment by Mobali243** [comment]
Same issue here...

So I'm unable to sync game data on chain or buy new seedlings.

So frustrating... A fix in sight?

**Comment by AerySviel** [comment]
> Same issue here...
> 
> So I'm unable to sync game data on chain or buy new seedlings.
> 
> So frustrating... A fix in sight?

Some people had done restore session and it worked for them, but didn't work for me.

You could try it, but you will lose progress though.

Still no update on this, even on their discord 😒

**Comment by Mobali243** [comment]
Restored the session, have lost progress for nothing...

Still unable to sync.

I guess I have no other solution than to give up, hoping that the game developers will find a solution someday...

**Comment by AerySviel** [comment]
> Restored the session, have lost progress for nothing...
> 
> Still unable to sync.
> 
> I guess I have no other solution than to give up, hoping that the game developers will find a solution someday...


Okay, so I was able to sync again. 

First I checked in goblin village what was the last save state I was in (the amount of SFL). Then I opened console (chromium browsers), right clicked on reload button and clicked "empty cache and hard reload". Did a restore session, logout of my farm, Signed in again, did another hard reload. Checked goblin village, returned to the farm and tried syncing. Was able to sync, and the SFL coincide with the one shown in goblin village. 

Hope you can make it work.
