### ISSUE TITLE
[PROPOSAL] What happens after hitting level 10 in Farming

### ISSUE THREAD

**Issue by WillyWagon** [sunflower-land/sunflower-land#896]
I've been wondering what happens after hitting lvl 10 in Farming. It would be a waste to just stop xp gain there, if this is just a soft cap and you can go over 5000xp, what does it contribute to?

If I understand how things work now, once you pick Green Thumb or Barn Manager, you're basically locked into picking the level 10 version of that specialty (Crops or Animals Route).

I'll be trying to give this area of uncertainty more attention with a couple of ideas I've been pondering on.

**Option A**
You would restart from level 1 like a new player with the same XP thresholds. Restarting would allow people who picked Green Thumb/ Barn Specialist to have a chance at earning the other specialisation badges they were locked out from.

You could stretch out the leveling progress with bigger XP thresholds (1.2-1.5x) since if you reached level 10, you definitely have all the tools available to maximise your XP gains.

If badges become withdrawable, people would be able to buy both but that is a whole different subject I'll not be discussing here.

This would be easier to implement than Option B and would give the people who are hardcore sf farmers a chance at something they only had access to by buying it on opensea.

**Option B**
You would continue on leveling past level 10, onwards to 15 or even 20! People who picked the Animal route can pick the Crop Route, or other way round at the 15 mark. To keep in theme with how you'd be locked, you'd be required to pick the level 20 of that route. People who want to specialise, could go the Animal/ Crop route twice. 

This is where it can get a bit creative which boosts you get at the 15 and 20 threshold and how much xp they would require, but here is my quick suggestion:

**Crop Route**
_Level 15 Green Hands_
- Crops are worth 5% more (10% total)
- Increase mutant crop chance

_Level 20 Seed Magician_
- Crops grow 10% faster (20% total)
- Increase mutant crop chance

**Animal Route**
_Level 15 Barn Optimiser_
- Animals yield 10% more goods (20% total)
- Increase mutant animal chance

_Level 20 Animal Whisperer_
- Animals Produce goods 10% faster (20% total)
- Increase mutant animal chance

Option B needs a lot more thought put into it. How you would scale beyond even that and more balancing problems I'd guess. 

This does not focus on the Gathering aspect, since I believe not a single person will hit 5000xp anytime soon or is close. And If someone is, 👀

**Comment by ElcomJ** [comment]
Hi Willy, how are you?

Your proposal for lvl 15 and 20 are really good, I would really like them to be really added to the game.

But I think the buff given by lvl 20 could be bigger, since it would be a level that would probably be very difficult to reach.

Congratulations on your proposal and have a great day

**Comment by WillyWagon** [comment]
@ElcomJ 
For the crop route, the level 20 badge could maybe be a yield increase like T2 scarecrow, 10%-15% but that is more in the devs their hands for balancing with other NFT's.
For the animal route there is not enough information to really know what could be a big boost, so any placeholder boost will do.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
