### ISSUE TITLE
(Proposal) Separate/Standalone skills for Farming and for Animal growth

### ISSUE THREAD

**Issue by vrillx** [sunflower-land/sunflower-land#900]
- allow farming/animal growth to be  separate/standalone skills 
- allow players to train both ...
- people shouldnt be able to level growing cows when they are planting sunflowers ....should we level mining gold ore because we plant potatoes ? 
- -I hope these become separate skills before animals land ingame and those who already picked barn manager skill can have the xp gatehred there added to green thumb skill . 
- Its just not logical to have people level skils by doing things not related to them ... Hope this gets adressed .

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
