### ISSUE TITLE
[HELPDESK] Questions regarding WW on Discord

### ISSUE THREAD

**Issue by AncientHorse** [sunflower-land/sunflower-land#905]
I've a compiled a list of questions players have been asking regarding the Wishing Well.  If these are added to freshdesk it will ease some pressure from the mods.

If I don't claim my rewards after 72 hours, do rewards still accumulate?
Can I still farm crops after depositing to Wishing Well?
Are Wishing Well rewards taxed like withdrawals?
What happens to my Wishing Well rewards if I sell my farm before claiming them?
Do I pair WMATIC or MATIC with SFL?
If I add more liquidity to the Wishing Well before it's time to claim, can I increase my rewards?

**Comment by AncientHorse** [comment]
No point in bringing up a problem unless you have a solution, right?  I'll take a stab and answering these questions in the morning and if coredevs approve my answers someone with access can cut/paste to freshdesk.

**Comment by AncientHorse** [comment]
Before someone commits these to help desk, a coredev should bless the answers.


**If I don’t claim my rewards after 72 hours, do rewards still accumulate?**

The Wishing Well rewards are awarded on a rolling 72 hour cycle.  To maximize your rewards, they should be claimed as soon as they are available.

**Can I still farm crops after depositing to the Wishing Well?**

Yes, making a wish does not impact your ability to farm or craft.

**Are Wishing Well rewards taxed like withdrawals?**

No, rewards are deposited directly to your farm.  However, if you chose to withdraw any SFL (regardless of source), the standard tax applies.

**What happens to my Wishing Well rewards if I sell my farm before claiming them?**

The new owner of the farm will not be able to claim any rewards.  You will also not be able to receive any awards without your farm.

**Do I pair WMATIC or MATIC with SFL to contribute to the Wishing Well?**

Quickswap will automatically convert your MATIC to WMATIC when adding liquidity.

**If I add more liquidity to the Wishing Well before it’s time to claim, can I increase my rewards?**

You can increase your liquidity position whenever you’d like.  However, your reward is based on your liquidity position at the start of the 72 cycle.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
