### ISSUE TITLE
[PROPOSAL] Shortening the games periods of idleness and offering a more engaging environment to the player.

### ISSUE THREAD

**Issue by gd-cloud** [sunflower-land/sunflower-land#906]
Thinking about Sunflower Land as a long-term experience for the players, I believe it should go way beyond it’s current resources management canvas. To keep the players engaged, it needs to dive in other aspects like exploration and discovery. It could be very enjoyable to explore other systems and discover new mechanics while you are waiting for your growing crops.
So, in order to shorten the players  periods of idleness, I would like to propose some funs activities based on mini games. The intention behind this is to make these mini games part of the game core experience. 

Mini-game 1 - Tower Defense

https://user-images.githubusercontent.com/103484522/168408140-5a60194c-3892-478c-8485-6fc05244fc9d.mp4

The goblins/skeletons/undeads have decided to invade the farm. Set up your towers and prevent them from stealing your crops. 

You would need to build at least one tower to be able to join this game. Axes, pickaxes and sickles* could be used inside the mini game. 
These tools could be used to remove obstacles from the battle field, allowing the player to build towers where they were initially located. 

Axes remove trees
Pickaxes remove stones
Sickles remove grass

In this example I used a concept tower. Building/crafting a tower means that you are able to join the game. Fees must be applied to keep everything balanced according to the games economy. The towers could be implemented in the future game’s building system.
Each creature has a monetary value (sorry goblins). In this prototype, the monetary value of each goblin is 0.01 SFL.

**Mini-game 2 - Into the wild**

This mini game can be part or be available at the land expansion phase.
The players need to craft a Adventurer’s Bag NFT and some tools (axes, pickaxes and sickles) to be able to leave their main farms and explore a brand new map in searching for resources.

Trees, stones and grass locations are randomly generated on the map. The players can chop trees, collect stones and minerals just like they current do on their farms. However, while the players are in the wilderness, there is a limit of resources that they can 
carry on their bags.

The Adventurer’s Bag can hold up to

Stones x ??
Gold x ??
Iron x ??
Wood x ??
Grass x ??

Any other resources like mushrooms or any kind of treasure won’t affect the players bag capacity.

The players will be able to receive your collected resources only after they go back to the their farms and sync on chain.

_To be updated..._

**Mini-game 3 - Fishing**

_To be updated..._

**Comment by SteveChickenCX** [comment]
I Love tower defense games, it's a great suggestion but I'm unsure if it's something the team should prioritize atm.

**Comment by gd-cloud** [comment]
Yeah I’m aware of that and I completely understand. This is kind of an ambitious proposal and in any way should be seen as a priority for the game. It is essentially based on ideas and possibilities that could be explored in long-term and any of this needs to look like something essential. These are just one of many other tools that could be used to keep the game evolving in some way beyond the most players expect. I will keep dropping some other mechanics ideas here in case they can be useful on a more appropriate moment.

**Comment by vrillx** [comment]
i love the tower game loll... hope in the future we get to build some nasty towers to kill ....farmers :)
