### ISSUE TITLE
[ART][IDEA] 🥕 UPGRADE BUNNY! 

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#907]
![BUNNY GRAY](https://user-images.githubusercontent.com/98098233/168416883-f48b9cf9-e6be-43c5-8800-f8bd4d00087b.gif)
![BUNNY GRAY big](https://user-images.githubusercontent.com/98098233/168416911-ce2ec7e9-01bc-4167-8657-cd86358e681a.gif)

Fred the Bunny

| EFFECT  | 
| ------------------- | 
| Earn 60% More Carrots |  

|COST | 
| ------------------- | 
| 1 x ![image](https://user-images.githubusercontent.com/98098233/168417199-a1092ad7-dea3-4301-aa86-227ea84b7e58.png)|  
| 5000 x  ![image](https://user-images.githubusercontent.com/98098233/168417138-ea5433f1-fb0c-4871-92cb-f7f1677b9391.png) |  
| 100 ![image](https://user-images.githubusercontent.com/98098233/168417417-47e445ca-93f0-4538-ac71-e8f6fb3b5d6e.png)|  

| SUPPLY  | 
| ------------------- | 
| 200  |  

_We currently have a Supply of 50,000 rabbits, its cost could also be 5 rabbits_

**Comment by Alexcnder** [comment]
i saw someone talking about a Rabbit + Carrot sword maybe make Rabbit like beaver 3 tiers
1st
the one we got
2nd
 the one you recommended
and then t3

Rabbit king or what it was called

**Comment by vrillx** [comment]
only if they ban the 2 mil illegal carrots from opensea..which btw has become a storage hub for banned accounts to protect theyr ingame assets.

**Comment by future2back** [comment]
> 

Illegal carrots? What you mean?

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
