### ISSUE TITLE
[IDEA] [PROPOSAL] [ART] - Fishing NFT Ideas in Sunflower Land - Proposal by Jc Eii 

### ISSUE THREAD

**Issue by JcEii** [sunflower-land/sunflower-land#909]
### Fishing NFT Ideas in Sunflower Land - Proposal by Jc Eii
**Part 1**

Good day Engineers, Developers, Moderators and Contributors. My name is Jc, a Programmer college student, fishing game fanatic, college journalist and an art contributor from the Philippines. I would like to share my ideas and arts related to fishing. I don’t think if this proposal can be approved by the board, but hopefully.

My proposal is all about fishing nft ideas on Sunflower Land, whereas I designed some of the fishing rods, fishes, and the market on it. I spent weeks, days, months to be able to finish it. I don’t know if it is good or not. But it is good from my point of view. I explain some of my fishing ideas on the following below:

**I.	Mr. J's shop
II.	Market
III.	Rods
IV.	Fishes
V.	Locations
VI.	Fishing and its Price, Crafts, Probability, nft.**

_--Note: This is only my idea. --_

### I.	Mr. J's Shop
Mr. J's Market can be found on the seas (south on farm); he is fishing and starved. On my idea, the player can fish after accessing his shop, but first the player should give him some delicious Potato chips that can be cooked in the kitchen, it needs 300 potatoes or less for me and 45 sfl to be able to access his shop.

Illustration:
(Potato Chips in Kitchen)
![image](https://user-images.githubusercontent.com/105348036/168424928-13843a92-85a8-4db8-86b1-f584604a648c.png)

![image](https://user-images.githubusercontent.com/105348036/168424966-55593b3a-c711-4ebc-bba0-9d002790d7b6.png)
(Before Giving Potato Chips)  --- ---------------------------------------------  (After Giving Potato Chips)

Animated Illustration:

![mrj-illust](https://user-images.githubusercontent.com/105348036/168425012-f1712390-acab-4f0a-93d5-3055fd0cffae.gif)

Mr. J's 64x48
![Mr J-64x48](https://user-images.githubusercontent.com/105348036/168425042-83f39dd0-70c6-4cff-b830-022c3531ca57.gif)

Mr. J's 256x192
![Mr J-256x192](https://user-images.githubusercontent.com/105348036/168425078-07886ae9-c914-4fe8-a102-2abe70bab516.gif)

_Story of Mr. J's expedition:_
Mr. J is an engineer and an angler. Before he became an angler, he also had a dream to become an angler; his wish was to become a happy angler and to catch massive fish and pufferfish.

One day, Mr. J's became a successful engineer and he designs many rods for fish; he also masters some fishing skills and fishing species. After he saves some money, Mr. J starts his expedition in the seas, using his own boat to make his dream come true.
In the middle of raging oceans, Mr. J's survives on monstrous waves with his boats. As day came by, he stranded on a land called "Sunflower Land" as he continued fishing, and making his dream come true.

### II.	Market
After accessing Mr. J's shop, in the “buy” tab, the player can buy some rods that can be used in fishing. (It is possible to put some nft craft to help players and the game (to burn the players own sfl)). The second tab is “sell” whereas the player can sell his watched fish into sfl.

Buy Tab:
![image](https://user-images.githubusercontent.com/105348036/168425131-dfef9e6e-dcac-472a-804f-5dbba85e0beb.png)

Sell Tab:
![image](https://user-images.githubusercontent.com/105348036/168425140-c2970c5a-5247-48b4-bb7f-bc62dc666e70.png)

In short, the purpose of the shop of Mr. J is to start fishing, buy some rods, sell some fish, and also in my own idea, it is possible to add some crafted nft to help to burn sfl and make the sfl value pump.

### III.	Rods 
Rods are the important for anglers to catch some fishes. In the game, the only rod available are just called “rod” and it is not available because the fishing is not available in the game (that is why I propose this proposal to add some ideas in fishing). But for me, single rod is not enough in the game (just like pickaxe, it has types: Wooden axe, stone axe, and iron axe.)

So, the one who proposed this proposal Suggests adding some rods, and I have ideas below to support the fishing nft in the game. So here are some rods based on my own idea to help the game.

**1.	Beginner's Rod** - For beginners that is used to fish.

256x224
![rod1-256x224](https://user-images.githubusercontent.com/105348036/168425291-56fa358c-1cba-410c-a302-97061f69a46f.png)
![image](https://user-images.githubusercontent.com/105348036/168425441-78ad1479-097e-483b-9841-ba8c7de22a46.png)

64x56
![rod1-64x56](https://user-images.githubusercontent.com/105348036/168425293-78d1ffb0-bdd5-47ee-9253-19a862d3cca0.png)

32x28
![rod1-32x28](https://user-images.githubusercontent.com/105348036/168425299-7d826875-db94-4cbd-b457-ae8ed6893bc7.png)

16x14
![rod1-16x14](https://user-images.githubusercontent.com/105348036/168425304-7e516de5-f8d6-49b2-a99f-c18c8bf1f279.png)

**2.	Goblin's Rod** - A Goblin Made rod that is luck on fishing.
256x224
![rod3-256x224](https://user-images.githubusercontent.com/105348036/168425353-9d7c52e2-c839-4bed-8795-77e59975b957.png)
![image](https://user-images.githubusercontent.com/105348036/168425450-a67bc5db-16b7-4c82-8d36-e191d181e600.png)

64x56
![rod3-64x56](https://user-images.githubusercontent.com/105348036/168425380-308d7e52-94e5-4105-88f1-aa6432ee98e9.png)

32x28
![rod3-32x28](https://user-images.githubusercontent.com/105348036/168425384-f61d94fb-26d4-49a5-995a-a2f66aa79107.png)

16x14
![rod3-16x14](https://user-images.githubusercontent.com/105348036/168425388-1b777f8f-9764-4ba0-ae63-a6593ed7672a.png)

**3.	Mr. J's Class A-Rod** - Moderate rod that is made by Mr. J to catch some Hot or Cold season rare fishes.
256x224
![rod2-256x224](https://user-images.githubusercontent.com/105348036/168425393-037dc907-7dde-4883-9de5-c16561ba68d6.png)
![image](https://user-images.githubusercontent.com/105348036/168425454-3049bbbb-1061-4bde-91db-51e5f5f1876b.png)

64x56
![rod1-64x56](https://user-images.githubusercontent.com/105348036/168425399-082a8e2f-5a47-4942-b9aa-d8593c24a8c3.png)

32x28
![rod1-32x28](https://user-images.githubusercontent.com/105348036/168425401-0c8979e6-1b65-4e6f-8f16-a6562ec7b214.png)

16x14
![rod1-16x14](https://user-images.githubusercontent.com/105348036/168425408-a240f8b9-71e0-4d85-be3d-ccda52781e51.png)

**4.	Mr. J's Class S-Rod** - High-Rate rod that can catch mutant fishes.
256x224
![rod4-256x224](https://user-images.githubusercontent.com/105348036/168425478-fce46758-29e7-497a-addf-a2cd8377b74e.png)
![image](https://user-images.githubusercontent.com/105348036/168425459-3d798c6d-57aa-4d70-9450-7f705830f2f7.png)

64x56
![rod4-64x56](https://user-images.githubusercontent.com/105348036/168425532-06c6495d-1f37-4bf0-9df9-ce401380a17d.png)

32x28
![rod4-32x28](https://user-images.githubusercontent.com/105348036/168425535-f8190d35-3f8a-49d9-b000-4bd23845022a.png)

16x14
![rod4-16x14](https://user-images.githubusercontent.com/105348036/168425548-a69025c5-1f42-49dc-af39-1c96fa89cb94.png)

**5.	King's Rod** - A best rod in Sunflower Land.
256x224
![rod5-256x224](https://user-images.githubusercontent.com/105348036/168425572-3be259c0-da4f-4bae-8257-4faecef14fde.png)
![image](https://user-images.githubusercontent.com/105348036/168425462-6be602b7-18c4-4a60-9fce-9bafae4242a5.png)

64x56
![rod5-64x56](https://user-images.githubusercontent.com/105348036/168425579-5b3ea3e9-9aac-4f39-ae22-b99a644fada9.png)

32x28
![rod5-32x28](https://user-images.githubusercontent.com/105348036/168425584-76dde606-7ceb-40ce-858c-b0418bd441cc.png)

16x14
![rod5-16x14](https://user-images.githubusercontent.com/105348036/168425589-1c73073b-7c8e-4990-b9e4-f834390734e1.png)

This Rods can support the game, every type of rods has own probability and compatibility in every fishes. This can also help to burn sfl of Sunflower Land. Also, rod will be broken once the player catches 3 fishes (Maybe 3-5 catches then the rod broke).

**IV.	Fishes**
	Rods are useless without fish; fishes may have a significant role in the game (instead of farming, animals, and forging). Furthermore, the following below are my ideas or fishes based on my own ideas. I detailed every fish (except herring, the common fish. I suggest changing the name of the trout to herring because herring is the most common fish in the world). On the other hand, caught fish can be sell, collect, or cooked.

_--note: Some of fishes are my own idea but most of them are true--_ 

### 1.	Common Saltwater (5 Fishes)
**•	Herring** – The common sea fish.
256x256
![image](https://user-images.githubusercontent.com/105348036/168425720-324c1d94-cfce-4707-b29e-9102de28d9d1.png)
![fishda-256_0000_Layer1](https://user-images.githubusercontent.com/105348036/168425748-823b10fa-ff1c-48cc-bf28-a2663809f761.png)

64x64
![fishda-64x64_0000_Layer1](https://user-images.githubusercontent.com/105348036/168425761-f0038589-5ff6-48c9-846a-c428ea8ce8c8.png)

32x32
![fishda-32x32_0000_Layer1](https://user-images.githubusercontent.com/105348036/168425762-c6e3c216-c502-4395-96b7-f636ebb15ac2.png)

16x16
![fishda-16x16_0000_Layer1](https://user-images.githubusercontent.com/105348036/168425767-e320272f-f11a-4fee-a91f-0f3e96312d08.png)

**•	Sardine** - Most populated sea fish in the world.
256x256
![image](https://user-images.githubusercontent.com/105348036/168425797-96c7a749-a1c5-4068-859d-e36b5cf2ca51.png)
![fishda-256_0004_Layer1](https://user-images.githubusercontent.com/105348036/168425837-5c7e9acf-8ed2-4a63-9297-eb413ed590dc.png)

64x64
![fishda-64x64_0004_Layer1](https://user-images.githubusercontent.com/105348036/168425844-b085f60e-cdb0-4d46-b94c-ac27aba339e0.png)

32x32
![fishda-32x32_0004_Layer1](https://user-images.githubusercontent.com/105348036/168425847-746b877e-3747-41c4-9f70-ab516d9b56e2.png)

16x16
![fishda-16x16_0004_Layer1](https://user-images.githubusercontent.com/105348036/168425849-5b4efadb-6eeb-4d1c-b0a1-7eb6b68e58c6.png)

**•	Snapper** - Cutest Sea fish and can be caught during rainy seasons.
256x256
![image](https://user-images.githubusercontent.com/105348036/168425857-7f55a8dc-1ded-4e0a-8749-1f761a2068e3.png)
![fishda-256_0005_Layer1](https://user-images.githubusercontent.com/105348036/168425887-52930691-27ff-490e-9ba7-ff7a55197493.png)

64x64
![fishda-64x64_0005_Layer1](https://user-images.githubusercontent.com/105348036/168425916-301e6d3a-0286-4578-adf6-59cbbafb7107.png)

32x32
![fishda-32x32_0005_Layer1](https://user-images.githubusercontent.com/105348036/168425918-cea22122-2fa6-4171-83c6-d38aaf5eb2c0.png)

16x16
![fishda-16x16_0005_Layer1](https://user-images.githubusercontent.com/105348036/168425923-6eade811-49fb-48ff-b709-ac922086d923.png)

**•	Tuna** - Most caught fish in the world because of its nutrients.
256x256
![image](https://user-images.githubusercontent.com/105348036/168425990-1a741de8-ef5e-4902-a357-0379d51fa3e3.png)
![fishda-256_0003_Layer1](https://user-images.githubusercontent.com/105348036/168425996-5eb2eb14-730a-4ad8-b988-fd989adbe123.png)

64x64
![fishda-64x64_0003_Layer1](https://user-images.githubusercontent.com/105348036/168426000-6d2bfea5-6a61-442a-b35a-5395193bb8a8.png)

32x32
![fishda-32x32_0003_Layer1](https://user-images.githubusercontent.com/105348036/168426003-922b0ea8-3ea6-441e-b461-082b514e4ce2.png)

16x16
![fishda-16x16_0003_Layer1](https://user-images.githubusercontent.com/105348036/168426009-204fa7b8-0d01-48e8-bf8a-05acd035b4ab.png)

**•	Salmon** – Soft-meat and expensive fish.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426015-3f9ea840-c462-46f9-ae13-4e799445c69f.png)
![fishda-256_0002_Layer5](https://user-images.githubusercontent.com/105348036/168426023-0f7323de-5f63-44db-9bff-6863d33aa288.png)

64x64
![fishda-64x64_0002_Layer5](https://user-images.githubusercontent.com/105348036/168426030-9980b736-0e4e-442d-9bf7-982fe107186c.png)

32x32
![fishda-32x32_0002_Layer5](https://user-images.githubusercontent.com/105348036/168426032-7b2bdf67-67f4-4060-8f47-1a7aa781f81d.png)

16x16
![fishda-16x16_0002_Layer5](https://user-images.githubusercontent.com/105348036/168426036-21ed6bb0-dcb7-4fe2-8f78-5504cc9659ae.png)

### 2.	Rare Saltwater (5 Fishes) 
**•	Pufferfish** - A fish that inflates but poisonous.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426094-52dca284-c78e-44c8-ad00-0ab73c87ce9b.png)
![fishda-256_0001_Layer1](https://user-images.githubusercontent.com/105348036/168426100-5cac9db5-efd9-4fd2-a376-7b94d1f6c6cb.png)

64x64
![fishda-64x64_0001_Layer1](https://user-images.githubusercontent.com/105348036/168426108-0d38fba6-bf87-4d90-90a2-6b407c561ed2.png)

32x32
![fishda-32x32_0001_Layer1](https://user-images.githubusercontent.com/105348036/168426114-c18af997-a7bb-4efb-99aa-ead4b721786b.png)

16x16
![fishda-16x16_0001_Layer1](https://user-images.githubusercontent.com/105348036/168426116-48b479b0-d740-486b-b4dc-e3c6a4ffaf3a.png)

**•	Goldband** - A fish that lives in surface.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426123-a2b2027a-6f16-4e12-a4f9-94016b572d56.png)
![fishda-256_0006_Layer1](https://user-images.githubusercontent.com/105348036/168426137-2a37711a-954b-42fe-a96e-b31b42006b96.png)

64x64
![fishda-64x64_0006_Layer1](https://user-images.githubusercontent.com/105348036/168426140-11ec5c51-5321-4599-be9f-91033a5f5120.png)

32x32
![fishda-32x32_0006_Layer1](https://user-images.githubusercontent.com/105348036/168426144-463408bf-908f-4f78-9d8c-5c31ec68b267.png)

16x16
![fishda-16x16_0006_Layer1](https://user-images.githubusercontent.com/105348036/168426151-f12bb25f-fc35-4e08-92e0-9a6053a7b562.png)

**•	Milk Fish** - A fish that is rare above sea level.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426216-07ea8c94-4644-43cf-84bf-8913805287cb.png)
![fishda-256_0007_Layer1](https://user-images.githubusercontent.com/105348036/168426226-3e16761e-fa2f-41cf-b746-f90478c8ac74.png)

64x64
![fishda-64x64_0007_Layer1](https://user-images.githubusercontent.com/105348036/168426230-46ec9283-8caa-4ea5-95c9-ff84cbf653b7.png)

32x32
![fishda-32x32_0007_Layer1](https://user-images.githubusercontent.com/105348036/168426232-7a1757d1-19eb-431e-864c-af455c81f1ff.png)

16x16
![fishda-16x16_0007_Layer1](https://user-images.githubusercontent.com/105348036/168426234-6aff70a0-8213-4774-8d0a-41e9b5c0a51c.png)

**•	Mackerel** - One in school of fishes and it is difficult to catch.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426242-020a2d09-9a0a-4e59-94da-4eee70cb3054.png)
![fishda-256_0008_Layer1](https://user-images.githubusercontent.com/105348036/168426261-e215f3db-c44e-484c-8d6c-4b90f1b330ad.png)
64x64
![fishda-64x64_0008_Layer1](https://user-images.githubusercontent.com/105348036/168426267-0b9075c5-a6ed-4cdd-87d3-f538946bb93c.png)

32x32
![fishda-32x32_0008_Layer1](https://user-images.githubusercontent.com/105348036/168426269-b3726ffa-2afe-4924-80df-96ff6bcabb8e.png)

16x16
![fishda-16x16_0008_Layer1](https://user-images.githubusercontent.com/105348036/168426274-19d0349e-8867-49e4-9fa6-044f7fd45310.png)

**•	Sea Urchin** - A poisonous, avoid some spines!
256x256
![image](https://user-images.githubusercontent.com/105348036/168426281-022c7c9f-758f-4696-b4b4-10194db3626a.png)
![fishda-256_0009_Layer18](https://user-images.githubusercontent.com/105348036/168426284-b70405a3-6ad5-40c6-9450-1cdd5f3f5436.png)

64x64
![fishda-64x64_0009_Layer18](https://user-images.githubusercontent.com/105348036/168426287-f8beb7ff-2739-4a75-86b8-f6eabc39209d.png)

32x32
![fishda-32x32_0009_Layer18](https://user-images.githubusercontent.com/105348036/168426291-aed7f4a6-3ceb-43b5-9f68-c1f8bd67a65c.png)

16x16
![fishda-16x16_0009_Layer18](https://user-images.githubusercontent.com/105348036/168426293-b19161f4-4a79-4b1f-96bb-842c999e3337.png)

### 3.	Common Freshwater (5 Fishes)
**•	Eel** - It looks like a snake but is not venomous.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426342-cabb4959-41cf-43f4-be43-96a76d67f118.png)
![fishda-256_0010_Layer12](https://user-images.githubusercontent.com/105348036/168426343-91ee322b-d75c-414f-9e35-ad0ff6731e69.png)

64x64
![fishda-64x64_0010_Layer12](https://user-images.githubusercontent.com/105348036/168426348-5dd9133c-fc5a-49b8-af37-b2fb2d23046d.png)

32x32
![fishda-32x32_0010_Layer12](https://user-images.githubusercontent.com/105348036/168426350-6a948649-db66-407c-a6ab-af600707d794.png)

16x16
![fishda-16x16_0010_Layer12](https://user-images.githubusercontent.com/105348036/168426355-278c9a9a-74be-4e0a-bb11-86a422645cd1.png)

**•	Trout** - Valuable salmon alternative.
256x256
![image](https://user-images.githubusercontent.com/105348036/168426362-f582854f-5fb4-4d99-bd87-2f021c2a8482.png)
![fishda-256_0011_Layer14](https://user-images.githubusercontent.com/105348036/168426372-1e7f4253-e43a-45e0-8a80-ba2df0c3655b.png)

64x64
![fishda-64x64_0011_Layer14](https://user-images.githubusercontent.com/105348036/168426376-4600c156-2910-4fbe-aa05-789bad16e187.png)

32x32
![fishda-32x32_0011_Layer14](https://user-images.githubusercontent.com/105348036/168426382-a758e2e7-4c30-4c14-b64c-0398fa0cc0ef.png)

16x16
![fishda-16x16_0011_Layer14](https://user-images.githubusercontent.com/105348036/168426386-4de27c07-7603-4a77-a301-8b2935fd58e2.png)

**Comment by JcEii** [comment]
I can't post the 2nd part because of multiple images I upload, but I have a file or document.

[Fishing Idea Proposal(Sunflower Land) By Jc Eii.pdf](https://github.com/sunflower-land/sunflower-land/files/8692949/Fishing.Idea.Proposal.Sunflower.Land.By.Jc.Eii.pdf)


That is all, this idea is my own concept and if any, valid or violent reaction, and some add-ons to my proposal comment below to edit or submit my document file. I want to help and contribute to the community because I like fishing, my dream to be an engineer, but I like to fish as my hobby. So hopefully, this proposal is approved by the board. Thank you very much!

For more collaboration or anything else, contact me:
Twitter: @jcambasa
Email: rjcagaming@gmail.com
Farm no.: 15747
Software used: Medibang and Photoshop

**Comment by JcEii** [comment]
### Fishing NFT Ideas in Sunflower Land - Proposal by Jc Eii

**Part 2 - Continuation (Without Picture)** 

_--I cant post or upload pictures :((--_

**•	Walleye** - Native yellow pike that can live on cold or warm temperatures.
**•	Tilapia** - Common fish in ponds and lakes.
**•	Largemouth Bass** - They can eat their own family.

1.	Rare Freshwater (5 Fishes)
**•	Gar** - Long narrow jaw fish but it’s not sword fish.
**•	Koi** - One of most populated fish in the world but rare to find in pond and lake.
**•	Catfish** – Big-mouth and resembled with cat's Whiskers.
**•	Bluegill** - Known as "bream" and food of Largemouth bass.
**•	Sturgeon** – Biggest freshwater fish in the world.

_--note. The Class of Cold Season, Hot Season, Mutant fish, and Legendary fish designs will be followed up once this proposal approves, any changes can do by the engineer, programmer, or myself. --
--note 2. Cold and Hot Climate will be available in land expansion (Cold climate in the north and hot climate in the west). --_ 

### 2.	Cold Climate (5 Fishes)
**•	Minnow** - A fish that can survive under glaciers.
**•	Stone Fish** - Dangerous fish but expensive.
**•	Ghost Fish** - One of the rarest ice fish in the world, they can live without water.
**•	Barb** - They can live either warm or cold, but they remain to live in cold lakes.
**•	Iceberg Koi** - Rarest and endangered koi species that lives in extreme cold temperatures.

### 3.	Hot Climate (5 Fishes)
**•	Red Piranha** - One of dangerous fish, in the world that lives near volcanoes.
**•	Black Fish** - Ancestors of piranha, endangered and fatal fish.
**•	Lava Koi** - A fish that can live inside a volcano crater lake.
**•	Bone Fish** - One of the rarest fish in the world that lives on warm surface.
**•	Predator Fish** - A carnivorous fish and size-like sturgeon, but it lives in hot seasons.

_--Own Fact. Mutant Fish are the most expensive one than Legendary fish, Mutant fish are the rarest fish in the world that cannot be seen by many people on these days, legendary fish are very rare to caught because they’re living in the surface of the ocean. –_ 

### 4.	Mutant (5 Fishes)
**•	Groupers** - A largemouth fish that is hard to catch because of its rarity in seas.
**•	Flower Horn** - Ornamental fish that can be your pet.
**•	Axolotl** - It can be your friend and pet.
**•	Sunflower Fish** - A fish that lived about five million Years ago, most people have seen it.
**•	Goblin Fish** - A rare fish in sunflower land that comes from the stories of most goblins.

### 5.	Legendary Saltwater (6 Fishes)
**•	Octopus** - A three heart species in the world.
**•	Shark** - One of fish in pre-historic years.
**•	Whale** - Heaviest fish in the world.
**•	Stingray** - A fish that lives in sea surface.
**•	Sword Fish** - An elongated carnivorous fish on earth.
**•	Sunfish** - Bigger than whale and rarest fish in the ocean.

### 6.	Legendary Freshwater (6 Fishes)
**•	Goldfish** - A golden freshwater fish, but it is not gold!
**•	Paddlefish** - A fish that lived a million years ago and living on the surface of lakes.
**•	Rainbow Trout** - A nutrient fish that lives in extreme colds and lakes.
**•	Golden Koi** - rare fish in sunflower land because of expensive price on market that can break the value of sfl.
**•	Arapaima** - Biggest fish like whale or sunfish that lives in cold ponds.
**•	Sawfish** - scariest fish in the world.

The following above are those fish that I would suggest adding to Sunflower Land; some of them can sell through Mr. J’s shop, but some of them cannot because of high value of it, Mr. J's own money are not enough money on it.
_--note. In every category has its own spawn time (example: pufferfish 12pm utc time)--_

### I.	 Fishing, locations, and its Price, Crafts, Probability, nft.

**i.	How to fish?**
To be able to fish, the player must select the rod and click on the available bubbles (bubbles that can be seen in seas or lakes) or fishing spots on lakes and seas. The possible number of fish that the player can get is up to 1-3 fish, but it depends on their own class. On the other hand, if the fishing rod does not respond, the player will find some spots, else the player will sync the game so the number of fish in the game may reset. (Exclude mutant and legendary fish)

**ii.	Fishing Locations**
The following are the locations of fish based on their rarity and habitat. The possible area that fish can be caught, also the available bubbles (this always occurs because some of the goblins throw some food at fish), the available bubble maybe the location of mutant fish or legendary.

**1.	Location**
**a.	Sea** – Seas will be the habitat of common, rare, mutant, and legendary saltwater fishes.

**b.	Lake, stream, pond etc.** – This will be the habitat of common, rare, mutant, and legendary freshwater fishes.


_-- note: Hot and Cold climate habitat will be available in land expansion, so I don’t add some location of those fish category. –_

**2. Fishing spots**
	
Fish will be available in every spot in lakes or seas, common fish and rare fish will be caught on every spots. On the other hand, those bubble will be available once in 3 days.
Illustration:

_-- note: bubbles are location of either mutant or legendary with just 30% rate, the remaining 70% will be common or rare fishes.”_

**iii.	Matrix of Rods and Fishes and its Price and Probability**
I do some matrix in every price, probability, need crafting items, etc. so that the players, Designers and Contributors may understand its every fundamental (like what is the probability of this rod for this kind of fish), so I listed below the matrices to be able to know it.

_--This is my suggestion, Developers or Engineer may do some change of values if the proposal approves--_

The matrix are on this file, I cant upload the images...
[Fishing Idea Proposal(Sunflower Land) By Jc Eii.pdf](https://github.com/sunflower-land/sunflower-land/files/8692961/Fishing.Idea.Proposal.Sunflower.Land.By.Jc.Eii.pdf)


That is all, this idea is my own concept and if any, valid or violent reaction, and some add-ons to my proposal comment below to edit or submit my document file. I want to help and contribute to the community because I like fishing, my dream to be an engineer, but I like to fish as my hobby. So hopefully, this proposal is approved by the board. Thank you very much!

For more collaboration or anything else, contact me:
Twitter: @jcambasa
Email: rjcagaming@gmail.com
Farm no.: 15747
Software used: Medibang and Photoshop

**Comment by o6ris13** [comment]
This proposal is very complete I think, very good job. It almost like a proposal for a fishing game. 
This is a very advanced proposal more than the game propose for now.

**Comment by vrillx** [comment]
I think Fishing Rods shouldnt determine the fish we catch ..Baits should .... or at least a combinations of 2 ...havin baits bought /produced frequently could also be more economically viable....overall the idea is sound and looks like alot of work been done .

**Comment by PigaPigaPiga** [comment]
This is **AMAZING**, I love it, amazing work..! Would love to see such an elaborate Sunflower Fishing (yeah, almost 'minigame') structure be implemented to the game, with even a lot of progression, balancing and future expansion options to..

- To add to your proposal here, I'd firstly address your art.. I love almost all of it, although I feel like the fishermans head is bouncing a bit too much, his glasses 'drop' a bit too much in relation to his hair I think, which is making it look like it's his head stretching rather than his body .. I'm not completely sure that's intended? Or is he headbanging/nodding a bit? All the rest I love

- Secondly,, related to the "mechanics" of the Fishing Rods, I'd like to suggest to give them each "a chance of damage fishing", so every time someone catches a succesful fish either the durability of the Rod used, or some chance of Destruction, would help add to the sustainability of the Fishing mini-game.. I don't think Rods should also be single use, like the Axes are, because that quickly becomes something people might not want to 'waste SFL/materials on', but if they always have a chance to be used a few times (maybe with 80-90% chance of earning back profits as a baseline? increased with higher rarities .. and some chances of profits), then it could be a fun addition to the game for all 👍 

- Thirdly I'd suggest to add a whole "Fishing" Skill tree to the Farmer Skills of the Home Interface. Perhaps every 5 levels could decrease the chances of fish getting away (increasing the odds of getting fish), or adding a few % boosts for certain types of Fish to be found using any Rod (maybe for the higher levels) .. Here there could also be "2 paths" like for Farming and Tools, where one Path could help increase the quantity of Fish/SFL sell price for Fish, and the other could help increase the chance for rarer fish to be found 🙏🐟

- And forth and lastly, I'd love to see a bit more "progress depth" and longlivity to this Fishing sub-minigame, apart from just the XP/Skills to grind up, some upgrade paths to work towards.. For this I'd suggest to increase the price/requirement gaps between the various Rods a huge deal.. And make a part of the requirements to crafting the higher tier rods, to spend something that's made with the Fish easilier made available to obtain with the Rod on the level just below. So a "Common/T1" Rod just requires Wood and SFL, but the T2 Rod (or unlocking it perhaps) could require a handful of rare fish to be crafted .. and the T3 Rod could use some Hot/Cold fish to be crafted (or some odd other random item found fishing) .. By doing that there's going to be a bit more "luck" involved into upgrading and working towards ones Fishing skill .. and the value of the individual Fish could also change depending on who/how demanded each type of Rod could end up being

**Comment by JcEii** [comment]
**Thank you @PigaPigaPiga  @vrillx  @o6ris13, I will do all of you suggestion and Improve my proposal.. Thank you for suggesting, it helps the proposal to make it approved my the board, thank youu, I will update you all once I revised this proposal...**

**Comment by AncientHorse** [comment]
The quality of some of these submissions is incredible!

**Comment by cdxgg** [comment]
太棒了！

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
