### ISSUE TITLE
(Proposal) Update Skills Display

### ISSUE THREAD

**Issue by vrillx** [sunflower-land/sunflower-land#917]
As we open home this is what we see 

![image](https://user-images.githubusercontent.com/103634238/168447011-aff4662d-c888-4fce-a241-64e955fb0718.png)

Make it something along these lines 

![image](https://user-images.githubusercontent.com/103634238/168449348-afff9325-97be-4ebf-897a-89a3164d230d.png)

Display all active skills like this ...

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
