### ISSUE TITLE
(Proposal) Buff List Display

### ISSUE THREAD

**Issue by vrillx** [sunflower-land/sunflower-land#918]
Over time as we accumulate more and more NFT is gonna get harder and harder to keep track of all the buffs we have active in our farms , which is why i would like to suggest an buff list display . 

We could add a second tab near the Skill tab (Home Building ) named Buffs ..players can click it and view all active buffs present : 

![image](https://user-images.githubusercontent.com/103634238/168447529-f352d126-b589-456f-a5ea-7275f804629c.png)

Buffs

![image](https://user-images.githubusercontent.com/103634238/168447436-79f2c886-8ecb-470b-b8a6-b6b772b187b0.png)

**Comment by Amelavnyt** [comment]
I 100% agree with the idea I just don't think it should look like this, not all crops get the same buffs so you should be able to check each resource by itself.
right now I'm working on making that a feature ;)
![image](https://user-images.githubusercontent.com/102462117/168489130-e58c0b0e-87fa-4ef5-bf2d-48b32296626e.png)
