### ISSUE TITLE
[BUG]Bulk buying in the 'Craft'  does not match the improvement done in the 'Shop'

### ISSUE THREAD

**Issue by Mo-Feng** [sunflower-land/sunflower-land#925]
Bulk buy 10 Iron Pickaxe makes no sense as the supply is only 5. Once the supply is less than 10, the 'buy 10' button is unclickable. It should be better to be coherent with the 'Shop', i.e. the bulk buy button changes according to the current supply.🥝

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
