### ISSUE TITLE
[BUG] Planted crops instantly ready to harvest after refresh, error on save (out of sync)

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#927]
Barbatos has reported a problem where he cannot save, because his planted crops appear instantly harvestable on refresh. 

It is repeated every time he refreshes.

"the game shows me that the crop is ready ahead of time" causing it to error, on attempted save.

He said the problem started after he harvested crops, went to goblin village, and came back and the crops were suddenly unharvested.

Farm ID 31272

Harvesting exactly 1 crop (as requested, from me):
![image](https://user-images.githubusercontent.com/105506388/168551986-7d68da80-07ef-4588-b71d-f931d0a42819.png)

Attempting to save after harvesting 1 crop: (The time index of this save is roughly 15-20 minutes prior to this post)
![image](https://user-images.githubusercontent.com/105506388/168552049-bf1f20bf-740a-49a9-b79c-f5fd4c692563.png)

He had a recent sync with no issues.
https://polygonscan.com/tx/0x90e35f57cf53864812be633315aeacefdf9062e811b09764c4e4771a79911442

Regular village inventory vs goblin village inventory comparison:
![image](https://cdn.discordapp.com/attachments/881648372249939980/975673545151623168/unknown.png)
![image](https://cdn.discordapp.com/attachments/881648372249939980/975673684649975838/unknown.png)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
