### ISSUE TITLE
[PROPOSAL] Shovel Stealing Goblin (SSG) Adjustments

### ISSUE THREAD

**Issue by newb23** [sunflower-land/sunflower-land#929]
### Proposal
Currently, the SSG is stealing the shovel at fixed intervals of 57 crops harvested. For longer duration grow crops, this feels like a nice number, but for those of us on the Sunflower and Potato hustle, it gets real old, real quick, particularly on mobile where the screen space is much smaller, and there is no option to zoom whatsoever.

I am proposing a couple slight changes to the logic that will both lengthen the time in-between SSG appearances, reducing frustration for human players, while simultaneously boosting the the bot-busting logic's effectiveness by adding variability.

 ### Mafs
Credit for the table is belonging to @brian-man; Thanks!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/omni/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/omni/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  | seconds |   | plants | cycles
-- | -- | -- | -- | --
Sunflower | 60 | 1.778151 | 183.23 | 8.33
Potato | 300 | 2.477121 | 131.53 | 5.98
Pumpkin | 1800 | 3.255273 | 100.09 | 4.55
Carrot | 3600 | 3.556303 | 91.61 | 4.16
Radish | 86400 | 4.936514 | 66.00 | 3.00

</body>

</html>

Taking **Radishes** as the math baseline, use `66*Log(radishGrowiimeInSec)*Log(plantGrowtimeInSeconds)/22` to give you the new number of cycles it will take to get the SSG event again.

*Note: 66 is an average of 3 cycles of plants at baseline (3 rounds of Radishes) 

Using the above, Sunflowers would take 8.33 cycles (or 183.23 total plants, or ~1/2 of a shop re-fill) before the SSG event. Potatoes would take 5.98 cycles (or 131.53 total plants, or ~3/4 of a shop re-fill) before the SSG event. Etc etc...

One final additional note, is that we can also add some variability into the equation by having a range in which we start our base number (Ex: `Rand([57 - 70])` vice `66`). This will add some "noise" into the equation so that scripts will not be able to simply "do the math" to further get around "stop every X and prompt human to find SSG".

Thoughts?

**Comment by pab3507** [comment]
I had a similar idea. Maybe this is over-engineering but I was thinking the probability of getting your shovel stolen could follow a gamma distribution such that the expected number of (maybe radish) harvests before getting the shovel stolen was 57. Then, we could have it so that the rate parameter is a function of the last X crops harvested so that if you have harvested a lot of sunflowers lately then the probability of getting the shovel stolen is smaller and if you have harvested a lot of wheat lately then the probability to get the shovel stolen is higher.

**Comment by c-py** [comment]
@newb23 @pab3507 I have raised a PR for this in https://github.com/sunflower-land/sunflower-land/pull/944.

I didn't see this github issue until after the fact, however the shovel thief will exponentially back off.
