### ISSUE TITLE
[BUG] Egg Basket from Easter isn't disabled

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#930]
The egg basket from easter isn't disabled in the crafting menu. Many people report this bug, wasting precious support hours.
![image](https://user-images.githubusercontent.com/105506388/168583694-49305c2e-ece1-4d0c-8207-6b41e8456d14.png)
![image](https://user-images.githubusercontent.com/105506388/168583708-31bb9074-eb7b-426e-84c8-220a7511524a.png)
![image](https://user-images.githubusercontent.com/105506388/168583721-aa518f79-ee1c-46ad-a41d-631ffcb0625d.png)
![image](https://user-images.githubusercontent.com/105506388/168583796-df55b52f-3475-4725-a64a-1d80464ba31d.png)

**Comment by yokosogithub** [comment]
network issue

**Comment by future2back** [comment]
Is it open for craft or not????

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
