### ISSUE TITLE
[IDEA][PROPOSAL] Weather System with different buffs

### ISSUE THREAD

**Issue by tryjapa** [sunflower-land/sunflower-land#934]
Hello great community of farmers my idea is make our interaction with the farm even more immersive and fun.

Every day ( we could make it random or the same for everyone)

A new environment will be apply with a small buff or debuff  
Could also help the team to estimulate a crop or a material and the otherway around as well.

These are just random numbers to help to understand my idea.

**Rainy day :**
(decrease harvest time for crops X,Y,Z 5%  and sunflowers worth 10% less)

![farm-rain](https://user-images.githubusercontent.com/9723813/168698759-c6b53517-3b94-46c7-b804-3dd904f0c296.gif)

**Sunny day:** 
(sunflower worth 15% more)
![SunnyDay](https://user-images.githubusercontent.com/9723813/168698955-9700677c-dd1c-442c-9493-a66f66457b2d.png)

**Misty day**
(Increase mutant crop chance 1%)

![fogFarm](https://user-images.githubusercontent.com/9723813/168699426-29f4aa8c-4cbd-4040-a20b-6a894418a6bd.png)

Would be nice hear more feedbacks about it :) 
Feel free to suggest changes and other mechanics to my idea.

Farm ID : 315
Discord: tryjapa#9936

**Comment by MrSnorch** [comment]
COOL IDEA!

**Comment by AlexanderGanichev** [comment]
I really like the idea👍

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
