### ISSUE TITLE
[IDEA] "Manure Compost" Rare NFT

### ISSUE THREAD

**Issue by WinterRoll1205** [sunflower-land/sunflower-land#939]
In the future, there will be manure produced from pigs, which is mainly used as fertilizer for crops. But we grow crops too, so why don't we use them from the comfort of within our own farm to boost their production?
Description (note that the numbers are likely to change upon release):
- Costs 1 manure to produce
- Composting takes 4 hours 
- After composting, an 8-hour boost will be available but will need to be manually enabled.
- When enabled: 
   + All crops planted during the boost grow 30% faster than without the boost (it's a compound effect if you also have Nancy the scarecrow)
   + Crops are considerably more likely to yield chests with corresponding seeds.
I figured it would only take a considerable amount of wood to produce, but you would need quite a lot of SFL as well.

**Comment by VitaliyPasiuta** [comment]
Can add a new NFT item like a bathtub to craft manure and we can craft boost version of bathtub with some automatization, example you stack 5 manure heap to box and the machine make finished product one by one.

P.S. I can make mistake with gramma e.t.)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
