### ISSUE TITLE
[PROPOSAL/IDEA] Add Announcement Board for Github Art Requests/Proposals/Ideas Ingame

### ISSUE THREAD

**Issue by LittleEins** [sunflower-land/sunflower-land#942]
Problems with current game

- I love the game so bad T_T, is that a problem :<
- There is no GitHub links in-game for farmers
- Community-driven voting for art competitions is somehow not fair when promoted, advertised, etc.

Goal of this feature

1. Add an announcement board that will link to latest SFL related Github Proposals/Art Request/Ideas.
2. Create a community-voting for ideas/art proposals that is fair for everyone with the help of every farmers ingame.
3. Maybe we can also put Tutorial Infographics in this announcement board?
4. This will also let more farmers to be involved especially in this current version of our game where we continue to grow and be a better version than yesterday.(Steve,2022)
Preview:
![announcement](https://user-images.githubusercontent.com/104184348/168857548-dbbdc7ec-aa6b-49b4-a096-bf648a133a96.png)

Raw-Zoom:
![announcement-raw](https://user-images.githubusercontent.com/104184348/168857610-30e553ef-7851-4f28-b752-2ac44f5b4f94.png)

Raw-Actual:
![announcement-raw-100](https://user-images.githubusercontent.com/104184348/168857618-2e51a11d-1341-4c04-846b-aaa89749193e.png)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
