### ISSUE TITLE
[ART PROPOSAL] EDITABLE SIGN

### ISSUE THREAD

**Issue by ek0onsec** [sunflower-land/sunflower-land#945]
I saw proposal #932  and I think the idea is great! So I'm proposing another sign design as well as possible integration on our farms.

sign asset (16x20):

![sign_asset](https://user-images.githubusercontent.com/72947786/169013545-c66248f0-9463-4bc5-b2bc-5b1183f72e7e.png)

preview :
![image](https://user-images.githubusercontent.com/72947786/169014056-9e18da7c-c0cb-42c8-9ee8-4d8e26a2f56a.png)

in-game asset preview :

![image](https://user-images.githubusercontent.com/72947786/169014297-aef74650-fff7-464b-9772-840843e90e9c.png)

![image](https://user-images.githubusercontent.com/72947786/169014397-ceb878d4-859f-4821-8cf6-2119b8f067a7.png)

Farm : 7044
Wallet : 0x93228Ff4C4695Ff015121130B986f7345FCa938C
Discord : Ek0#6086

**Comment by AlexanderGanichev** [comment]
Good job! I think it should be craftable and cost 50 wood, with emission = ∞.

**Comment by SuperSynapse** [comment]
This is a great idea! especially for people visiting your farm!

Would be really cool as well if they could add messages on little notes.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
