### ISSUE TITLE
[IDEA / PROPOSAL] Golden Cauliflower New Mechanic

### ISSUE THREAD

**Issue by WeHawt01** [sunflower-land/sunflower-land#946]
Hello fellow Farmers !

I have thought about this new mechanic to make it more intriguing for the Golden Cauliflower, because I am scared that the following halving's golden cauliflower would not make such a large impact for the lucky few farmers who were able to obtain it. I came up with a far more fascinating mechanic that would be more in accordance with the price of a golden cauliflower and its exceptional rarity, not to mention how difficult it was to craft with over 1000 players vying for it.

-My theory is that the Golden Cauliflower will simply have this mechanism on the Cauliflowers. Regardless of the halving, the prices of purchase and resale will always remain at the original V2 prices before the halving. That was, if I recall properly, three or four halving's ago. So it's either 0.3 or 0.225 SFL. Furthermore, at a resale price of 0.446 or 0.3345. Based on the item's incredibly low supply, this would have a negligible influence on the game. And the plan to solely affect cauliflower appears to be the most logical and feasible.

This approach would be far more in line with the item's cost and extreme rarity, with over 150k Farmers expected very soon. 

Any constructive criticism on this proposal would be highly appreciated. 

Farm ID 
297

**Comment by MEGALLO69** [comment]
Hello there, I agree with you that the Golden Cauliflower right now has no significant impact. We can request a buff, but what you just proposed cannot be implemented because it implies that you can buy cauliflower from the black market and sell it on your farm, which is a mechanic that has the potential to break the game entirely. If you have seen the land expansion, that's when the Golden Cauliflower can really shine! You may wonder why. Because, for example, if you increase your land and have 50 plots with The Golden NFT can provide you with what a 100 plot farm can provide, and you may go as far as you want with it.

**Comment by Ruhtrayeh** [comment]
Maybe harvesting twice as much and not paying for Cauliflower seeds, or everyone who has Golden artifacts in the land, would make the land turn golden.

**Comment by WeHawt01** [comment]
> Maybe harvesting twice as much and not paying for Cauliflower seeds, or everyone who has Golden artifacts in the land, would make the land turn golden.

Yes actually this could be a very possible and doable idea.

**Comment by SuperSynapse** [comment]
> Maybe harvesting twice as much and not paying for Cauliflower seeds, or everyone who has Golden artifacts in the land, would make the land turn golden.

In my opinion this is where multiple NFT stacking comes in. This is the value of the Kuebiko. If you want both, you should craft/purchase both.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
