### ISSUE TITLE
[PROPOSAL] Solution to burn SFL and resources

### ISSUE THREAD

**Issue by JoMcClane33** [sunflower-land/sunflower-land#953]
Today I thought to propose a sustainable solution on the game which would allow to have a stable economy in game (SFL and stable resources) by having a lot of burn.

![tools](https://user-images.githubusercontent.com/104658526/169157424-e37c5574-a561-477e-bcb0-88434e73c85d.png)

For me there is a problem of resources in large quantities and very little burn and that is why I propose in these examples that the buildings not be in full access directly so we should make resources and pay for upgrade to unlock tools every time .

![1er exemple](https://user-images.githubusercontent.com/104658526/169152535-5211989b-57eb-4dba-bf7e-bd4fb5f550b5.png)

For the second example, there could be storage limits to limit purchases on the black market and balance farming and the price of SFL.

We would have the 1st stage of wood storage limited to 500 wood maximum that we must upgrade to have 1000 wood maximum.

We would have the same for wheat. For the storage wood or wheat craft it could be a craft like the radish pie which is not transferable and forces people to do it if they want to increase their wood capacity

These ideas are unlimited and can fit with your idea of ​​land expansion.

For fishing ask us to build our fishing hut, to build our boat... For animals build enclosures, buildings...

If this crafting system is more developed there will always be burn and then it's up to you to add the NFTs in addition to the in-game crafts.

Nothing also prevents these crafts in addition to resources from asking for SFL to burn the game currency.

Lots of ideas can be added to force people to play and stay on the game and not get out of the game quickly

Thank you feel free to add your ideas

**Comment by brian-man** [comment]
So what you're saying is that people either [a] shouldn't collect resources (once "full") or [b] should be forced to craft FTs whether they want them or not (to consume wood)?

As a player I think that's a failure mode.  Introduce natural and compelling resource consumption rather than prevent storing items in your farm.

Also, are you looking to block withdraw of resources as well? Because with a hard cap on farm storage, people would just do that instead.

**Comment by JoMcClane33** [comment]
No I authorize the withdrawal and if people want to withdraw it withdraws the wood but you are limited to  

level 1 has 500 wood
level 2 1500 wood 

But you want to make the beaver T3 with 5000of wood  will have to increase your storage or buy your beaver T3 on opensea ;)

**Comment by KKonst27** [comment]
Mega-cool idea!

**Comment by JoMcClane33** [comment]
Exactly ! and it can be for everything! The kitchen, for example, to enlarge our land or unlock the wheat, we arrive in the game, why is it already built ???

Let us make wood to build it to have access and if all this is done for all the buildings the economy will be much better! (other examples: the tailor, the barn...)

**Comment by Stevew00dy** [comment]
I like the idea of building progression through gameplay. Giving people enough to start and then over time they can work towards doing more.

**Comment by Renz198** [comment]
Great idea, this could be applied to any buildings/future buildings that promotes gameplay and burning resources. It will also scale the game in the long run. Eg. for fishing, if you upgrade blacksmith youll unlock more fishing poles to get more valuable/rarer fish. Land expansion will benefit most out of this.

**Comment by SuperSynapse** [comment]
I think you have some good suggestions here, however I'm not a huge fan of this for a key reason that it additionally benefits people multi-farming, and further hinders those who are just now starting the game.

It's difficult enough as it is to farm resources to spend for massive items (such as the Foreman Beaver).

What I would be interested to see, is a progression like this that makes it cost less SFL in the crafting of the pickaxes, OR has possibility to yeild multiple pickaxes with a single craft.

I envision that over time larger scale mining (such as the mines we see ingame) will be the path of progression to making a single farm more competitive against people using many multiple low level farms.
