### ISSUE TITLE
[PROPOSAL] Withdraw clicking

### ISSUE THREAD

**Issue by AlexanderGanichev** [sunflower-land/sunflower-land#959]
It really annoys players because it takes too much time. I think there should be a button **"select all"** or/and a box that asks how much of selected resourse do you wanna withdraw. 
![nDkDQ8Bbgl](https://user-images.githubusercontent.com/41728647/169250193-e1809450-14e1-471a-bebd-8e06e843365b.gif)

**Comment by SteveChickenCX** [comment]
a quick and easy fix can actually be just keybinding it to "space" as an additional key .

any dev wanna add that :) ?

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
