### ISSUE TITLE
Has this been forked to bnb?

### ISSUE THREAD

**Issue by agoralive** [sunflower-land/sunflower-land#96]
Same problem with ETH and the damn kitties back in the day....

Forked yet?

**Comment by adamhannigan** [comment]
@agoralive Not that we know of yet.

It is open source, but brands and assets are licensed so creators have to be wary of any breaches of agreements.

**Comment by imgntn** [comment]
@agoralive since it was an asset flip, you can buy the same assets for $30 here https://danieldiggle.itch.io/sunnyside
