### ISSUE TITLE
Goblin town border [Visual]

### ISSUE THREAD

**Issue by notKVN** [sunflower-land/sunflower-land#962]
Hello team,

The goblin town background has this border across the bottom and left side of the screen. Visible on both, mobile and computer - green border there.
[The downloaded image has it grayish instead.](https://sunflower-land.com/play/assets/goblin_background.25a1a9c7.png)

**Comment by birborbirb** [comment]
I already noticed it and this will be fixed! 
Thanks for your feedback!

**Comment by VadimasVP** [comment]
![frogg](https://user-images.githubusercontent.com/102822587/169350507-7131e12f-8425-4b91-96c3-241fbe749f60.gif)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
