### ISSUE TITLE
[PROPOSAL] Add Quickswap link to the menu

### ISSUE THREAD

**Issue by notKVN** [sunflower-land/sunflower-land#965]
This one is quite simple but I think might be handy to have the button for QuickSwap added to the menu if someone needs quick access. 
Adding an example image with the menu button implemented.
Could be named differently as well.

![QS menu](https://user-images.githubusercontent.com/105289121/169354943-858f3946-7fcb-436c-bb02-dea573e21143.PNG)

**Comment by aayusharyan** [comment]
Actually, there was a link in the old version. Dec'21 around. That was in the top right, it looked pretty good.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
