### ISSUE TITLE
[IDEA]Sunflower land social system interaction buff 

### ISSUE THREAD

**Issue by Tsuki-Sy** [sunflower-land/sunflower-land#972]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-2dcb5a99-7fff-3e3b-3a95-2abc6e18dec8"><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Author: Tsukilab.crypto#2906</span></p><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2022/5/16</span></p><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Translator: davidtian#0625</span></p><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2022/5/19</span></p><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Current problems in game</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-indent: -18pt;margin-top:12pt;margin-bottom:12pt;padding:0pt 0pt 0pt 18pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.</span><span style="font-size:6pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> &nbsp; </span><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The social aspect of the game needs to be strengthened, players can only communicate in discord, and there is no other interaction.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-indent: -18pt;margin-top:12pt;margin-bottom:12pt;padding:0pt 0pt 0pt 18pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2.</span><span style="font-size:6pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> </span><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;When growing long-term crops, more fun elements are needed.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-indent: -18pt;margin-top:12pt;margin-bottom:12pt;padding:0pt 0pt 0pt 18pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3.&nbsp; Users are lacking immersion in the word &ldquo;farmer&rdquo;.</span></p><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Fu</span><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">nction purpose</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-indent: -18pt;margin-top:12pt;margin-bottom:12pt;padding:0pt 0pt 0pt 18pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.</span><span style="font-size:5pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; </span><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Adding social attributes to the game can let gamers interact in-game and increase the joy of playing.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-indent: -18pt;margin-top:12pt;margin-bottom:12pt;padding:0pt 0pt 0pt 18pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2.</span><span style="font-size:5pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; </span><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Increase the user viscosity and bring up the gamer&rsquo;s activeness.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;text-indent: -18pt;margin-top:12pt;margin-bottom:12pt;padding:0pt 0pt 0pt 18pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3.</span><span style="font-size:5pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> </span><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;&nbsp;Increase immersions with creating &ldquo;Farmer&rdquo; personal nfts.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">e.g.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">400 sunflowers, 50 carrots, 20wheats and 5$SFL to craft this nft.</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Total: Unlimited</span></p><p dir="ltr" style="line-height:1.38;margin-left: 18pt;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(For new users to get involved, it is not recommended to consume their wood and minerals )</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Farmer LV. | EXP. Required | buff
-- | -- | --
Lv1 | 1 | ——
Lv2 | 5 | Increases the 2%chance of getting a positive buff
Lv3 | 18 | Increases the 3%chance of getting a positive buff
Lv4 | 72 | Increases the 4%chance of getting a positive buff
Lv5 | 220 | Increases the 5%chance of getting a positive buff

Details of buff
1.   Players can only give away 10 buffs a day.
If you reach the daily limit, the prompt will show "Your helps today have reached to limit, please try again tomorrow," and the reset time is at 23:59:59 UTC daily;
2.    Players can only keep one buff at the same time, the buff will last for 8 hrs 
After buff disappearing, other players need to help buff again
3.    When getting a buff,The Players can choose to keep it or burn 1 $SFL to refresh it, one can only refresh 10 times a day.
     The cost is halved with each production reduction); each buff can be reset up to 10 times; after reaching the upper limit, it can't be changed, and must be waited for a new round of buffs daily reset
4. If you already have a buff, when other players are trying to help, the system will prompt, "This player already got a buff, please turn to others to help.”

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-afd686ef-7fff-00ad-cb8f-ab61ec158b8f"><div dir="ltr" style="margin-left:0pt;" align="center">

BUFF type | BUFF description | Lv1 Farmertrigger probability | Lv2 Farmertrigger probability | Lv3 Farmertrigger probability | Lv4 Farmertrigger probability | Lv5 Farmertrigger probability
-- | -- | -- | -- | -- | -- | --
crops（40%） | Increase crop yield2% | 10% | 10.20% | 10.51% | 10.93% | 11.47%
  | Increase crop yield3% | 6% | 6.12% | 6.30% | 6.56% | 6.88%
  | Increase crop yield5% | 4% | 4.08% | 4.20% | 4.37% | 4.59%
  | Reduce crop yields2% | 10% | 9.80% | 9.51% | 9.13% | 8.67%
  | Reduce crop yields3% | 6% | 5.88% | 5.70% | 5.48% | 5.20%
  | Reduce crop yields5% | 4% | 3.92% | 3.80% | 3.65% | 3.47%
wood（40%） | Increase wood production2% | 10% | 10.20% | 10.51% | 10.93% | 11.47%
  | Increase wood production3% | 6% | 6.12% | 6.30% | 6.56% | 6.88%
  | Increase wood production5% | 4% | 4.08% | 4.20% | 4.37% | 4.59%
  | Reduce wood production2% | 10% | 9.80% | 9.51% | 9.13% | 8.67%
  | Reduce wood production3% | 6% | 5.88% | 5.70% | 5.48% | 5.20%
  | Reduce wood production5% | 4% | 3.92% | 3.80% | 3.65% | 3.47%
pasture（20%） | Increase pasture yields2% | 5% | 5.10% | 5.25% | 5.46% | 5.74%
  | Increase pasture yields3% | 3% | 3.06% | 3.15% | 3.28% | 3.44%
  | Increase pasture yields5% | 2% | 2.04% | 2.10% | 2.19% | 2.29%
  | Reduce pasture production2% | 5% | 4.90% | 4.75% | 4.56% | 4.33%
  | Reduce pasture production3% | 3% | 2.94% | 2.85% | 2.74% | 2.60%
  | Reduce pasture production5% | 2% | 1.96% | 1.90% | 1.83% | 1.73%

</div></b>
</body>
</html>
Considering whether the effect of the buff will affect the current T3, the above data is for reference only and can be adjusted appropriately;

Ps:
At present, this proposal may still have many imperfections, and there is even no art draft. If you like my proposal and agree with these, you are very welcome and thank you for providing some artistic images of "Farmer" and the icon of "buff" ;

In addition, I don't know if there will be difficulties in the functional issues involved in the proposal (such as going to other people's farms to provide buff), but I still hope that developers can think of ways to overcome them or implement them in another way. This type of game, interactive gameplay with friends may be an inevitable link;

I think a good game requires not only a balance between in-game output and consumption, but also a perfect social gameplay. The social system is also equally important. If the land is expanded, or other gameplay that has been decided to go live, it will take 3-6 months to develop. The time in between is very boring for most players, and the loss of users will be a pity.

Finally, thanks to the Chinese community partners who helped me translate this case (because my English is really not very good)
Here is tsukilab.crypto#2906 Hope the friends in the community can make this game a great work~~
Thanks to K' 🍯#1688 and TreasureGoblin.wallet#1582 for his comments on the revision of this case

If you like my proposal, please vote for me, thank you~

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
