### ISSUE TITLE
[BUG] Cannot withdraw SFL - 500 FAILED_REQUEST

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#973]
Severity: Normal
Summary: API 500 FAILED_REQUEST when withdraw attempted.

- [x] Farm is not banned/flagged.
- [x] Sufficient SFL on-chain balance for withdraw. 
(0xE6fb07c2E38029Ebb87E1A19A99Bad813fb2E6e3 29.74426333779219823 SFL > 29.73 SFL)
- [x] Tested to see if it's a rounding issue.

Timestamp: Request was made approximately 18:02 (6:02PM) on 2022-05-20 UTC+0 

Details:
RDiego 100617

Fails before an on-chain tx is attempted.

Cannot withdraw 29.73 SFL. He said he also tested 29 SFL with the same error, yesterday.

![image](https://user-images.githubusercontent.com/105506388/169591415-3ceb7635-b8d0-4f4c-b3a1-061209ec9182.png)
![image](https://user-images.githubusercontent.com/105506388/169591435-7207d0c6-a7c5-41f1-b537-12154a6029b3.png)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
