### ISSUE TITLE
[PROPOSAL] Add SFL to Metamask Button

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#975]
Add a button on the main "sunflower-land.com" website, or in-game to add SFL to metamask.

Why?
Multiple users have fallen victim to sending their SFL token to the contract address.

1. They copy the token address, to add it to metamask to import.
2. They go to their goblin village bank.
3. They select deposit.
4. They click the copy button beside their farm address.
5. Discord (occasionally) locks the clipboard, blocking the copy request.
6. They pastes the token contract address into the send address field (and think it's the bank address).
7. They don't double check.
8. They send the SFL. It is gone.

```
async function AddSFLToken(){

	const tokenAddress = currentTrade.to.address;
	const tokenSymbol = currentTrade.to.symbol;
	const tokenDecimals = parseInt(currentTrade.to.decimals);
	const tokenImage = currentTrade.to.logoURI;

	try {
	  const wasAdded = await ethereum.request({
		method: 'wallet_watchAsset',
		params: {
		  type: 'ERC20',
		  options: {
			address: '0xd1f9c58e33933a993a3891f8acfe05a68e1afc05', 
			symbol: 'SFL',
			decimals: 18, 
			image: 'https://sunflower-land.com/assets/nft_land.fc43adde.png',
		  },
		},
	  });

	} catch (error) {
		console.log(error);
	}
}
```

**Comment by SuperSynapse** [comment]
PLEASE!!!

Great suggestion @sir-canada

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
