### ISSUE TITLE
[Bug] Farm Dog has different stats in game from Opensea

### ISSUE THREAD

**Issue by SuperSynapse** [sunflower-land/sunflower-land#980]
So I did a quick search and didn't see this addressed, but the Farm Dog has two different descriptions. Ingame:

![image](https://user-images.githubusercontent.com/51135442/169660919-eab890d8-c860-4bc6-ad89-e0a1bdc27e37.png)

and in Opensea:

![image](https://user-images.githubusercontent.com/51135442/169660933-0c2466c8-a600-4855-81fa-2ba0df909d8f.png)

Which one is correct?

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
