### ISSUE TITLE
[PROPOSAL]Sfl Burn 

### ISSUE THREAD

**Issue by DonPablo69** [sunflower-land/sunflower-land#985]
Hey :)I had a little idea that could amuse more than one
Implementing a roulette system to burn sfl could be interesting it will suffice to bet an amount to win other sfl or we could win a daily boost system for example  10% faster on sunflo or potatoes, if someone can draw a funfair roulette model it could be interesting to add this type of mechanism,we could also bet resources for example 5 wood to win 10 or just lose this would allow us to burn resources,

**Comment by Saipax** [comment]
Honestly winning 24 hour boosts for a specific crops by betting SFL is a great idea

**Comment by DonPablo69** [comment]
yes I will see a wheel to spin if someone is able to draw a picture that would be really cool :)
