### ISSUE TITLE
Proposal of possible solution to fix bot issue with the game

### ISSUE THREAD

**Issue by AshishKumar-AK** [sunflower-land/sunflower-land#99]
I had lengthy discussion in our discord #community-dev channel but I will summarize the proposal here for consideration for DEVs:

1. Make new forks of games smart contracts.
2. Introduce Shape drag fill based captcha to game's UI during save click. Player will have perform this captcha check.
3. Introduce a [middle layer backend proxy JSON RPC API](https://devblogs.microsoft.com/cse/2017/04/18/using-a-layer-7-proxy-for-ethereum-blockchain/) with similar API calls like polygon's PRC API, which will be used by Game's frontend web UI to handle save button captcha function of the game and then call game smart contract with following workflow:
   a. When Player will hit save and perform shape fill captcha successfully, metamask should pop up, asking user to sign and send the transaction. this payload will be generated and signed with additional data payload ([reference](https://docs.metamask.io/guide/sending-transactions.html):
```
  {
	"user_wallet_address": "0xwalletaddresshere",
	"is_captcha_verified_correct": "YES"
}, this_playload_signature_signed_by_verifying_player: "xxxxSignatureValueherexxxxx" 
```
  b. Then this middle proxy API, add additional data parameter signing this whole payload with its owns private key whos public key is known to smart contract and validate that indeed this came from game's authorized backend proxy API.
```
{
another_signature_signed_by_games_centrailzed_backend_server_just_prove_that_it_indeed_came_from_game_backend_server_not_directly_from_any_bot_since_key_is_secured_with_game_centrailzed_backend: "xxxxSignatureValueherexxxxx"
}
```
  c. and calls the smart contract, now the contract has all the data to make validate the transaction that it came from a player verified with captcha, signed by backend API and has player's wallet address to deposit his farm yield earnings and rewards.

5. Team can deploy this solution on any public cloud serveless platform aws lambda/azure functions to be very cost efficiently and upscale/downscale based on traffic load.

P.S I am not a web3.0 DEV and coming from web2.0 space so not sure about feasibility of this solution

**Comment by JeromeRadlach** [comment]
this introduces a single point of failure which could prevent anyone from interacting with the SC. its much easyer to deal with bots by economics.

**Comment by AshishKumar-AK** [comment]
> this introduces a single point of failure which could prevent anyone from interacting with the SC. its much easyer to deal with bots by economics.

I don't think so! I haven't seen any existing web2.0 game failing due to scale. I don't think AWS/Azure cloud will fail to scale just by a simple API call.

**Comment by adamhannigan** [comment]
@AshishKumar-AK The current solution will use off chain anti-botting verification.

For launch, we are looking into Captcha approaches. This can be a little annoying for players though, in the future we want to gamify this approach and detect bots by how they are playing the game.

Any ideas?
